### ISSUE TITLE
Cannot login into authserver, password is always wrong

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-core#10]
**Description:**

On some setups players cannot login. This does not happen on every setup and the exact cause needs to be determined.
Any input is welcome, I'm still unable to reproduce it on my end.

Original issue: #6 
A temporary solution is provided here: https://github.com/ValorenWoW/sunstrider-core/issues/6#issuecomment-414628109
Compiling in debug mode instead of release may also work.

**rev. hash/commit:** 

43e369d

**Comment by woiwoz** [comment]
Yes, this should not be the case for everyone, depending on the compiler or other environment. But it can be solved by the way I submitted before. Thank you

**Comment by woiwoz** [comment]
I'm personally more interested in the dungeons, and what I'm doing now is migrating the Trinity script (excluding WLK content) to this core for testing. I hope this is a very meaningful job.

**Comment by kelno** [comment]
Same issue and more info here:
https://github.com/TrinityCore/TrinityCore/issues/22343

**Comment by PadreWoW** [comment]
Same problem always wrond password :(
And where is manual how to create new account from console?

+ how to confugure Auth Console to log logins and wrong password?

**Comment by talamortis** [comment]
change the c++17 to c++14 this will solve the issue.

**Comment by PadreWoW** [comment]
i need to reinstall VS 2017 application?

**Comment by talamortis** [comment]
No you have it installed right click on Authserver and worldserver and go to the following and change the command line from c++17 to c++14

![image](https://user-images.githubusercontent.com/6143065/45883006-c78e9b00-bda7-11e8-92a8-72ceba78cc96.png)

**Comment by PadreWoW** [comment]
i'll try
thanks

**Comment by PadreWoW** [comment]
Now i see CONNECTED and can not create character :(

**Comment by talamortis** [comment]
have you done for both auth and worldserver?

**Comment by PadreWoW** [comment]
yep
both working

**Comment by PadreWoW** [comment]
maybe something wrong with DB or config?

**Comment by talamortis** [comment]
after you changed did you recompile the source?? - Im just pulling all latest fixes then i can help test

**Comment by PadreWoW** [comment]
recompiled of course

**Comment by ratkosrb** [comment]
I have the same issue. First it was saying my password is wrong, and after adding /std:c++14 it now gets stuck at Connected.

**Comment by PadreWoW** [comment]
Me too - stuck on CONNECTED

**Comment by ratkosrb** [comment]
video of this bug https://streamable.com/phrnu

**Comment by kelno** [comment]
This should be fixed in this last commit, please confirmed.
SInce this seems to be a compiler bug, authserver will stay in c++14 for now.

**Comment by PadreWoW** [comment]
All fixed! Thanks!

**Comment by kelno** [comment]
Maybe try using the volatile keyword to prevent optimizing on some var.
