### ISSUE TITLE
Implement missing LockTypes

### ISSUE THREAD

**Issue by SUN-Leekie** [ValorenWoW/sunstrider-core#100]
**Description:**
While fixing the quest [Birds of Feather](https://www.wowhead.com/quest=9397/birds-of-a-feather), I checked the Goober in question *Kaliri Nest*(181582) which has Lock.dbc id 43 which goes to LockType.dbc id 13 meaning `LOCKTYPE_OPEN_KNEELING`.

**Current behaviour:**
The player doesn't kneel when opening the Kaliri Nest.
https://streamable.com/hdine

**Expected behaviour:**
Player should kneel when opening the Kaliri Nest.
https://youtu.be/qilrLprvwCs?t=73

**Steps to reproduce the problem:**
1. `.quest add 9937`
2. `.go obj 21935`
3. Right click on the gameobject

**rev. hash/commit:** 
10057

**Comment by kelno** [comment]
https://i.imgur.com/H0l6W4D.jpg
