### ISSUE TITLE
First time here,Is this project [instance] and [creatures script] open source?

### ISSUE THREAD

**Issue by DarkmoonRabbit** [ValorenWoW/sunstrider-core#101]
I don't understand "Partly open source" in the README.md file.

Instance and creatures scripts: open source?;

AntiCheat: not open source?;

**Comment by kelno** [comment]
Instance & creatures scripts are mostly closed. Most world creatures scripts are present.
Anticheat is closed as well.

Closing as this is a question and not an issue.
