### ISSUE TITLE
Script Paralytic Poison & Paralysis

### ISSUE THREAD

**Issue by SUN-Leekie** [ValorenWoW/sunstrider-core#104]
**Description:**
Paralytic Poison: 35201
Paralysis: 35202

**Current behaviour:**
Paralysis is never triggered.

**Expected behaviour:**
Paralysis should be triggered when Paralytic Poison **expires** (not dispelled).

**Steps to reproduce the problem:**
.aura 35201

**Comment by kelno** [comment]
Fixed in https://github.com/ValorenWoW/sunstrider-core/commit/9f4e545b43443909da0b79c9b15287744decfaa7
