### ISSUE TITLE
Reputation from quest is given twice

### ISSUE THREAD

**Issue by SUN-Leekie** [ValorenWoW/sunstrider-core#105]
Ex: quest 10116
> **Reputation with Kurenai increased by 550.**
> Wanted: Chieftain Mummaki completed.
> Received 11 Gold, 36 Silver.
> **Reputation with Kurenai increased by 550.**

The last line should not be there.

**Comment by kelno** [comment]
Fixed with 7d83dfa72d6291d370ac0608a2cdf7f75d9e3b4e

**Comment by SUN-Leekie** [comment]
You removed the first line not the last. x)
