### ISSUE TITLE
smart_scripts Database table not data

### ISSUE THREAD

**Issue by woiwoz** [ValorenWoW/sunstrider-core#11]
smart_scripts Database table not data,Can it be open source? Personally, I think this is very necessary, which is missing a lot of data.

**Comment by SUN-Leekie** [comment]
All of our scripts are removed before our server release to secure a little bit of our hard work. This is why you will find no scripts in the core and smart_scripts empty.
Everything will be public after our release. We will soon open a public realm for beta testing that will have the scripts.

**Comment by woiwoz** [comment]
That's fine. Thank you!
