### ISSUE TITLE
[Rogue] Shiv applies 3 poisons at once instead of one.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#110]
**Description:**

Rogue ability Shiv applies 3 poison stacks with one use, should be 1 poison stack. Could hint at weird poison procrate from special abilities in general.

**Current behaviour:**

As above.

**Expected behaviour:**

Shiv should apply one poison.

**Steps to reproduce the problem:**
1. Apply a poison (Wound Poison or Deadly Poison as they have more than 1 stacks) to your offhand weapon as a Rogue
2. Cast Shiv (spell ID: 5938) on a target
2. The target now has 3 stacks of your offhand poison after one Shiv

**rev. hash/commit:** 

latest

**Comment by kelno** [comment]
It was two different bugs, and you were right about this being related to weird proc rate.
- Poison had two changes of proccing for each spell (dunno why this was like this, this is the same at TC)
- Shiv applied the poison one more time because of faulty logic in the spell
