### ISSUE TITLE
Hello, my friends, do you have plans to open private servers?

### ISSUE THREAD

**Issue by woiwoz** [ValorenWoW/sunstrider-core#12]
Hello, my friends, do you have plans to open private servers? 
Also, can anyone else in this open source project submit code as a volunteer?

**Comment by kelno** [comment]
I'd like to keep the issues for code issues only. Our current canal of communication is Discord, is there any way you can use a VPN to join it?
Yes we plan to open a server, we're currently preparing the beta.
I'm closing this issue but you can still respond here.

**Comment by woiwoz** [comment]
I can only buy a server from the United States or other countries to build a VPN myself. I'm in China now, and the firewall in China is annoying.....

**Comment by woiwoz** [comment]
I'll leave you a message here after I set up VPN this afternoon.
