### ISSUE TITLE
Mob spawns in ghostlands are too scarce (spiders/bats/tigers)

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#126]
**Description:**

There are too little random mobs all over Ghostlands, especially in the eastern - central side (around Sanctum of the Sun) - we can walk seemingly forever and not encounter any of them. Should definitely be more of them all over the place.

**Comment by kelno** [comment]
Somewhat fixed with https://github.com/ValorenWoW/sunstrider-core/commit/e712b68e23c1a791c304d5aaf485ae7636ff6c48
