### ISSUE TITLE
[Rogue] Distract breaks Vanish

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#131]
**Description:**

Rogue's spell Distract (1725) removes the effects of Vanish (1856) probably also Mage's Invisibility (effect 32612) and other Invisibility related spells. It should not remove those effects.

Fixed in TC with: https://github.com/TrinityCore/TrinityCore/pull/14824

**Comment by kelno** [comment]
Should it also break stealth in general or not?

**Comment by Jerrythemagicdog** [comment]
Distract does not break stealth for the caster or the target affected by it.
Source: http://wowwiki.wikia.com/wiki/Distract
No mentions of Stealth, the spell remained the same through all expansions.
