### ISSUE TITLE
Spells occasionally miss

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#132]
**Description:**

Spells occasionally miss. They are not supposed to be labeled as a "miss" in TBC only as "resist". Not sure if it's just a misnaming or a bugged mechanic. The "miss" on spells was introduced in WotLK.
Here's a post from 2008 wowhead:
https://www.wowhead.com/forums&topic=5794#p54972

"Spell hit reduces the chance your spells will "miss" a target. Most effective for targets above your level. Misses are shown to you as full resists in wow, but they are not exactly the same thing."

**Comment by kelno** [comment]
That is voluntary to make obvious when a spell is missed because of the incompressible %, so that when you're hit capped you never see resist and know those cannot be avoided.
But since this is getting reported all the time, I'll change it back haha.
