### ISSUE TITLE
[Karazhan] Ythyar's (Consortium vendor and repair) sometimes leave his spawn point

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#139]
**Description:**
Ythyar (17518) spawn point is broken, he has fallen through the floor and is on top of a pillar in Curator's room (should be directly above near a ramp leading to Chess Event)

**Comment by kelno** [comment]
![gkgyi9b](https://user-images.githubusercontent.com/3866946/50999836-94754080-152b-11e9-89ac-cf5d983a215b.jpg)
This is his original spawn point. Need to find how he did end up there in your instance.

**Comment by Jerrythemagicdog** [comment]
This is where he belongs yup, I believe he fell through the ground in my instance and ended up in an unreachable place.

**Comment by kelno** [comment]
I mean that's where he IS spawned currently. The issue here is that he moves for some reason, else he would never move from here. Could be that he aggroed something, was affected by a fear, etc etc.
