### ISSUE TITLE
Fel Reaver aggro

### ISSUE THREAD

**Issue by Klaceyes** [ValorenWoW/sunstrider-core#14]
**Description:**

The Fel Reaver is taking the aggro 
**Current behaviour:**

when coming close to him, it aggro and losing it directly when out of los

**Expected behaviour:**

It should aggro only if attacked

**Steps to reproduce the problem:**

Coming close to him will make him aggro, if moving back he'll just reset his LoS

**rev. hash/commit:** 

*bugued right now*

**Operating system:** 

Windows 10

**Comment by SUN-Leekie** [comment]
The Fel Reaver aggroing is the right behavior according to a [beta video](https://www.youtube.com/watch?v=CDrqI86dL5g) and its state on retail.
