### ISSUE TITLE
[Karazhan] Shade of Aran bugs

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#140]
**Description:**

- Shade of Aran's Arcane Missiles do not work, he instantly cancels them in order to cast another spell. 
- Before casting Arcane Explosion he should teleport everyone including himself to the exact middle of the room. 
- The Water Elementals he summons are not spread around the room and spawn on top of eachother (they should be in each corner.) 
- The Blizzards he summons should be moving around the room in a clockwise manner. 
_(wowwiki: Circular Blizzard: Large AoE that moves slowly clockwise around the room. Deals 1313 to 1687 frost damage every two seconds and slows movement speed by 65%; does not hit the center of the room )_
- When he reaches 20% of mana he's supposed to Polymorph everyone and drink (per wowwiki: _At 20% mana or less (about 30k), Aran mass Polymorphs the entire raid, conjures some water, and starts drinking. After about ten seconds, or if his drinking is interrupted, the polymorph breaks and Aran does a pyroblast for 7000-7500 fire damage on the whole raid. )_
Currently he casts Evocation, a spell he should not be casting at all (according to wowwiki and my memory. )
Sources: http://wowwiki.wikia.com/wiki/Shade_of_Aran

**Comment by kelno** [comment]
Thanks.
Need video reference for each of those issues, except the Arcane Missiles ones.

**Comment by Jerrythemagicdog** [comment]
Here's a video of a kill from retail: https://youtu.be/l0DB4lzAttw
