### ISSUE TITLE
[Karazhan] Chess Event causes a crash.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#141]
**Description:**

Starting Chess Event in Karazhan crashes the server.

Tested on the PTR

**Comment by kelno** [comment]
![fhwjnfn](https://user-images.githubusercontent.com/3866946/51002586-094c7880-1534-11e9-87a0-b5b0ffbca5d4.png)
![jyexhzd](https://user-images.githubusercontent.com/3866946/51002606-1a958500-1534-11e9-9d59-2a972a303982.png)
