### ISSUE TITLE
Various mobs miss immunity to stun

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#142]
**Description:**

Rogue's spell Gouge works on mobs otherwise immune to CC. Tested in Karazhan on Skeletal Ushers and Arcane Protectors. Should be immune to Gouge too.

**Comment by kelno** [comment]
There is no general "immune to CC" mechanics, that's set per creature and per mechanic. Gimme gimme the ids of those npcs.

**Comment by Jerrythemagicdog** [comment]
Skeletal Usher: 16471
Arcane Protector: 16504
Mana Feeder: 16491

**Comment by kelno** [comment]
Okay. This spell is a stun like the others actually. Are those mobs supposed to be immune to stun?

**Comment by kelno** [comment]
"In end-game raiding, Gouge has proven useful in interrupting caster enemies if they are immune to stunning with [Cheap Shot] or silencing with [Kick]. It may be expensive energy wise, but it will at least buy time and prevent extra damage to your fellow raid members."

Apparently it's still supposed to work on many mobs... Closed until further notice
