### ISSUE TITLE
[World Boss] Doom Lord Kazzak issues.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#144]
**Description:**
Doom Lord Kazzak (18728) is a world boss that's supposed to have a long respawn timer.

**Current behaviour:**

- Currently the respawn timer is set to 2h30min20s.

**Expected behaviour:**

- The respawn timer according to many retail sources is anywhere between 4 to 7 days

Sources:
-Respawn timer: 
https://www.mmo-champion.com/threads/1195395-Doom-Lord-Kazzak-Spawn-Time
https://us.battle.net/forums/en/wow/topic/12674209750#post-5

**Comment by kelno** [comment]
https://github.com/ValorenWoW/sunstrider-core/commit/dcb8cdc9b4b705a5d99deb8b31b4e759bca8c15b
