### ISSUE TITLE
[World Boss] Doomwalker issues

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#145]
**Description:**

Doomwalker as a world boss should have a longer respawn timer.

**Current behaviour:**

Doomwalker has a respawn timer set to 1 day in game

**Expected behaviour:**
The respawn timer should be anywhere between 2-4 days according to reports from retail at the time.

Sources:
https://www.mmo-champion.com/threads/1123445-Doomwalker-s-spawn-time-Anyone-know
https://us.battle.net/forums/en/wow/topic/8796449630
https://www.dual-boxing.com/threads/17549-I-know-this-is-kinda-stupid-but-anyone-know-the-spawn-time-on-Doomwalker

**Comment by kelno** [comment]
https://github.com/ValorenWoW/sunstrider-core/commit/dcb8cdc9b4b705a5d99deb8b31b4e759bca8c15b
