### ISSUE TITLE
Raid bosses' Armor values are incorrect.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#146]
**Description:**

Raid bosses in TBC had certain armor values on retail which are different currently for Sunstrider.
The issue comes from incorrect value of  'ArmorModifier' (mostly being 1 everywhere) in creature_template in accordance to 'unit_class' (1 or 2 for all of those below) corresponding to table's creature_classlevelstats column 'class'.

**Current behaviour:**
Current values on Sunstrider are _(first value is creature ID, second armor value, third expected value)_:
Gruul's Lair:
- High King Maulgar (18831): 6719 / 7700
- Gruul the Dragonkiller (19044): 6719 / 7700

Magtheridon's Lair:
- Magtheridon (17257): 6719 / 7700

Zul'Aman:
- Nalorakk (23576): 6719 / 7700
- Akil'zon (23574): 6708 / 7700
- Jan'alai (23578): 6719 / 7700
- Halazzi (23577): 6719 / 7700
- Hex Lord Malacrass (24239): 6708 / 6200
- Zul'jin (23863): 6719 / 7700

Serpentshrine Cavern:
- Hydross the Unstable (21216): 6719 / 7700
- The Lurker Below (21217): 6719 / 7700
- Leotheras the Blind (21215): 6719 / 7700
- Fathom-Lord Karathress(21214): 6708 / 6200
- Morogrim Tidewalker(21213): 6719 / 7700
- Lady Vashj (21212): 6708 / 6200

Tempest Keep:
- Void Reaver (19516): 6708 / 8800
- High Astromancer Solarian(18805): 6708 / 6200
- Al'ar (19514): 6719 / 7700
- Kael'thas Sunstrider (19622): 6708 / 6200

Hyjal Summit:
- Rage Winterchill (17767): 6708 / 6200
- Anetheron (17808): 6708 / 6200
- Kaz'rogal (17888): 6708 / 6200
- Azgalor (17842): 6708 / 6200
- Archimonde (17968): 6708 / 6200

Black Temple:
- High Warlord Naj'entus (22887): 6719 / 7700
- Supremus (22898): 6719 / 7700
- Shade of Akama (22841): 6719 / 7700
- Teron Gorefiend(22871): 6708 / 6200
- Gurtogg Bloodboil(22948): 6719 / 7700
- Reliquary of Souls:
- Essence of Suffering (23418): 6719 / 0
- Essence of Desire (23419): 6719 / 7700
- Essence of Anger (23420): 6719 / 7700
Mother Shahraz (22947): 6708 / 6200
Illidari Council:
- Gathios the Shatterer (22949): 6708 / 6200
- Illidan Stormrage (22917): 6719 / 7700

Sunwell Plateau:
- Kalecgos (Dragon 24850): 6708 / 6200
- Sathrovarr the Corruptor (24892): 6708 / 6200
- Brutallus (24882): 6719 / 7700
- Felmyst (25038): 6708 / 6200
- The Eredar Twins:
- Grand Warlock Alythess (25166): 6708 / 6200
- Lady Sacrolash (25165): 6708 / 6200
- M'uru (25741): 6719 / 7700
- Shadowsword Fury Mage (25799): 4643 / 5700
- Shadowsword Berserker (25798): 4929 / 7100
- Void Sentinel (25772): 4786 / 6800

**Sources**:
https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/137892-raid-raid-boss-armor.html

> Original Guide by Dayve of <Eternity> on Gorgonnash.
> 
> I've been doing a fair bit of testing on mob armor over the past month. I've been using pretty much the same method as Lactose, although I use imp. Thunder Clap (which has a fixed damage amount).
> 
> To make things easier, I wrote a simple addon that watches for TC hitting my target, calculates how much it should have hit for before armor reduction, and outputs into a chat window the range of armor values that could have produced the observed hit (taking into account any armor debuffs of course). My estimates were then taken from the intersection of all the ranges that I recorded. From the size of the ranges, the accuracy of the results should be about +/- 30.
> 
> So far, I've managed to get results for almost every trash mob and boss in SSC, TK, BT, and Hyjal. Some of the values are different from the ones Lactose obtained. I'll just list the boss armor values, because those are the useful ones .

> Notice that all but 2 of the bosses have either 6200 or 7700 armor. A similar pattern occurs in the trash mobs: 5475/5700/5950 or 6800/7100/7400 for level 70/71/72 mobs. In terms of percentage reduction, these values result in either 34.15% or 39.15% armor reduction vs attackers of the same level as the mob.

**Comment by kelno** [comment]
Long story short: Most of them are fixed with 8bdacb7bd301226913a7210e134bde65273e7887.
Also did fix Void Reaver in dd062e5f2c90e800a78369e892bdac521fc8c673
If there are any specific cases left we can reopen this.
