### ISSUE TITLE
SMART_EVENT_JUST_SUMMONED not triggered when summoned with a spell

### ISSUE THREAD

**Issue by SUN-Leekie** [ValorenWoW/sunstrider-core#148]
Reproducing steps:
* .cast 36555
Observe that the monsters are not randomly moving but they do if you summon them with a `.npc addtemp  21306`

**Comment by kelno** [comment]
Failed to reproduce, they do random move for me with the current script.
Send your whole script?

**Comment by SUN-Leekie** [comment]
Somehow it works now.
