### ISSUE TITLE
Hellfire Superiority display isn't working

### ISSUE THREAD

**Issue by Klaceyes** [ValorenWoW/sunstrider-core#15]
**Description:**

Hellffire Superiority display isn't showing on screen

**Current behaviour:**

Buff with the id 32071 (wowhead source) called Hellffire Superiority is showing when taking the 3 bases on the hellfire peninsula, but the actual status of the top-screen display isn't shown at all.

**Expected behaviour:**

We should've seen when entering the Hellfire Peninsula the actual status of the occupation Horde / Alliance on the top of the screen with two little towers icons

**Steps to reproduce the problem:**

Just entering the Hellfire Peninsula

**rev. hash/commit:** 

*None*

**Operating system:** 

Windows 10

**Video**

https://www.youtube.com/watch?v=WOY3qZPNlPY

It looks like sometimes it is working

**Comment by woiwoz** [comment]
当玩家登陆时应该发送世界状态,worldstate()?

**Comment by kelno** [comment]
I'm not event sure what was the problem, world state system was a bit of a mess, a little rewrite bit of cleaning up fixed it.
