### ISSUE TITLE
[Warlock] Devour Magic gives "invalid target" when trying to cast on enemy players and units.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#154]
**Description:**
Devour Magic returns an "invalid target" when attempting to devour enemy players' buffs in a duel and NPCs buffs in the world.

**Current behaviour:**

Any attempt to Devour buffs from enemy units and players returns "Invalid target" error message.

**Expected behaviour:**

Devour Magic should work on enemy units.

**rev. hash/commit:** 
rev. 10154 (1ebf0609a394) 2019-01-11 00:00:40 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Gimme specific example, could not reproduce in my setup

**Comment by Jerrythemagicdog** [comment]
Tried in a duel with spells like Arcane Intellect (27126), Dampen Magic (10174), Unending Breath (5697), Detect Invisibility (132) and on random mobs in outland (17160 for example) with spells like Lighting Shield.

screenshot: https://imgur.com/a/gLYmsdr
