### ISSUE TITLE
[Druid] Lifebloom doesn't use snapshotting properly.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#157]
**Description:**
Lifeblooms final tick (the heal after it runs out / gets dispeled) benefits from present bonus healing, instead of bonus healing that was present upon cast. Final lifebloom tick healing should be calculated from healing bonus present on cast.

**Current behaviour:**

Lifebloom final tick benefits only from druid's current healing and not the bonus healing that was present on cast.

**Expected behaviour:**

Lifebloom's final tick should be calculated from healing present on cast.

**Steps to reproduce the problem:**

1. Equip one healing item on a druid
2. Cast Lifebloom
3. Unequip the healing item
4. The final tick of lifebloom will heal depending on current bonus healing and not bonus healing present on cast.

**Sources**:
https://youtu.be/yyaK3qTbsVI?t=6m20s
Druid has casted lifebloom on himself when wearing Y bonus healing+548 heal from mace
(You can see the icons next to player frame portrait to indicate which weapons he has equipped)

Final tick heals him for 1218 into catform (+20% heal) while he has equipped dps staff instead of healing mace. So base value before 20% heal from talent was something like 1015.

https://youtu.be/yyaK3qTbsVI?t=2m27s
Druid has casted lifebloom on himself when wearing X bonus healing+548 heal from mace
(You can see the icons next to player frame portrait to indicate which weapons he has equipped)

Final tick heals him for 1043 while he has still equipped heal mace.

The reason why both values (1043 and 1015) are not same is because he had more agility equipped in one of those cases. Lifeboom HoT ticks were 141 for 1043 final bloom and 135 for 1015 final bloom.

**rev. hash/commit:** 

Sunstrider rev. 10154 (1ebf0609a394) 2019-01-11 00:00:40 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Make sense. Thanks for the numbers here.

**Comment by kelno** [comment]
Notes:

From source 1:
135 * 7 = HB * 0.52 + 273
	-> HB = 1292
(600 + HB2 * 0.343) * 1.2 = 1218
	-> HB = 1209
