### ISSUE TITLE
Npc's / monsters aggro broken

### ISSUE THREAD

**Issue by Klaceyes** [ValorenWoW/sunstrider-core#16]
**Description:**

Npc are having a bad reseting of their aggro

**Current behaviour:**

When leaving a combat, the npc is starting to go back to his starting point, but if we are too close from him, he start attacking again without finishing it's course

**Expected behaviour:**

It should leave entirely the fight, and going back to it's initial position. Even if we are close to him during it's move

**Steps to reproduce the problem:**

Doing like on this video : https://www.youtube.com/watch?v=XkeVbg6HD3c

**Operating system:** 

Windows 10

**Comment by woiwoz** [comment]
![qq 20180903115349](https://user-images.githubusercontent.com/11075449/44966830-22369300-af70-11e8-9201-496cf9a47c60.png)
When a creature dies or breaks out of combat, there should be a delay in re-engagement, as shown in the Mangos project

**Comment by woiwoz** [comment]
We should also increase the judgment of IsInEvadeMode () when a creature enters combat.
