### ISSUE TITLE
[Warlock] Seed of Corruption does not activate when crossed a damage threshold.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#162]
**Description:**
Imbeds a demon seed in the enemy target, causing 1050 Shadow damage over 18 sec. When the target takes 1045 total damage or dies, the seed will inflict 1111 - 1290 Shadow damage to all other enemies within 15 yards of the target. Only one Corruption spell per Warlock can be active on any one target.

**Current behaviour:**
Seed of Corruption doesn't detonate on damage, only on target death.

**Expected behaviour:**

Seed of Corruption should detonate after crossing a certain damage threshold (from tooltip) and dealing damage within 10 yards

**Steps to reproduce the problem:**

1. Cast Seed of Corruption on a pack of mobs
2. Use spells like Blizzard (10187), Arcane Explosion (27082) or any Warlock damaging spell (such as Shadow Bolt (27209).
3. The seed doesn't detonate.

**rev. hash/commit:** 

Sunstrider rev. 10209 (6426fb604472) 2019-01-14 10:06:28 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Was broken in https://github.com/ValorenWoW/sunstrider-core/commit/9e09a92a94a5bdcab3203d8085e78d3a8d40ab87
