### ISSUE TITLE
[Mage] Water Elemental issues

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#163]
**Description:**
Water Elemental hp, mana values and spell costs are incorrect - hp and mana values are too high even on a naked character and his spells cost too much. He also melee attacks the enemies when in range.

**Current behaviour:**

1) Waterbolt mana cost is too high. 321 mana
2) Freeze cost is too high 449 mana
3) Water Elemental mana pool is too high. 6840 on naked mage, going above 8k on geared mages.
4) Water elemental health pool is too high. 6452 on a naked mage, going above 7k on geared mages.
5) Water elemental melee attacks people when in range.

**Expected behaviour:**

1) Waterbolt mana cost should be 224 mana
https://youtu.be/fja5OBiCClU?t=11m45s
Water elemental has 1440 mana before cast, 1216 after cast = 224
Water elemental has 1216 mana before cast, 992 after cast = 224

https://youtu.be/P0ou5D_v3uY?t=8m19s
Water elemental has 942 mana before cast, 718 after cast = 224
Water elemental has 718 mana before cast, 494 after cast = 224

Also http://wowwiki.wikia.com/wiki/Summon_Water_Elemental?oldid=1548530
lists correct value of 224 mana

2) Freeze mana cost should be 313 mana
Quite hard to spot due to quality
https://youtu.be/P0ou5D_v3uY?t=8m30s
Water elemental has 450 mana before cast, 148 after cast = 302
It could have recieved mp5 tick, because wowwiki lists 313 mana cost.

3) Water Elemental mana pool should be around 3k on s3 geared mages
https://imgur.com/a/y9peaIK
Scaling from intelect that was added in 2.1 seems to be close to 0,8

https://youtu.be/P0ou5D_v3uY?t=8m5s
Low geared mage, tried to equip same mana pool he had and it was around 370 intelect and his pet has 2985 mana.

https://youtu.be/fja5OBiCClU?t=11m50s
Late season 3 video. S3 geared mage, tried to equip same mana pool he had and it was around 439 intelect and his pet has 3038 mana.

**It's mana costs actually scale with base mana (10% for waterbolt and 14% for freeze) so its base mana is 2240** 

https://youtu.be/fja5OBiCClU?t=12m1s
If you continue watching the video, you will see that water elemental didnt cast last 7 seconds of his duration, because he was out of mana.

4)
https://youtu.be/P0ou5D_v3uY?t=8m23s
Low quality, but it looks like 3459 health on water elementa with 9132 hp on player? (equal to 592 stamina) Dont know how he got that much health with this gear...

https://youtu.be/hDBIyF0O9bE?t=6m50s
Bit clumsy, I watched slow motion and counted hits recieved by pet. Mage had 10323 health (equal to 711 stamina)
numbers were: 661, 1334, 1392=3507 And the health bar was almost empty after last hit (5% left?). So i guess it had like 3691 ish health. 

After some math it i got 1,95 scaling coeff for health per stamina. So If I round it up to 2 we get water elemental base health 2275 or 2269.

5) Water Elemental should not melee attack targets close to him - his only form of attack is his spell Waterbolt.

**rev. hash/commit:** 

Sunstrider rev. 10209 (6426fb604472) 2019-01-14 10:06:28 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
1 & 2 are the result of 3.

**Comment by kelno** [comment]
Mana part should be fixed with:
https://github.com/ValorenWoW/sunstrider-core/commit/cb269a5d39005d121870fbbb208155ab1ce5e987 
Health is also updated with:
https://github.com/ValorenWoW/sunstrider-core/commit/3b07f615e941517bba4bf8b8cfbcc3423bafe1a0
Melee is not fixed yet.

Test again?

**Comment by Jerrythemagicdog** [comment]
The mana costs are fixed, the amount of mana the pet has still seems a bit too much, although close.

**Comment by kelno** [comment]
I'll consider this fixed for now then :p
