### ISSUE TITLE
A gnoll in Westfall is mounted on a Dragonhawk

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#169]
**Description:**
A Gnoll in Westfall (GUID: 1085374) is mounted on a Dragonhawk.

**Expected behaviour:**
The gnoll should not be mounted on a dragonhawk.

**Steps to reproduce the problem:**

1. Go to GUID: 1085374
2. He's mounted on a freakin epic Dragonhawk!

**rev. hash/commit:** 
Sunstrider rev. 10233 (64c4a89) 2019-01-16 22:11:16 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
I removed the "fixate" part as this is a global issue not related to that specific creature.

**Comment by kelno** [comment]
https://i.imgur.com/X69gAZF.jpg
He's actually fabulous
