### ISSUE TITLE
[Priest] Shadow Word: Death backlash damage applies through absorbs.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#178]
**Description:**
Shadow Word: Death (32996) backlash damage goes through absorb effects like Power Word: Shield. 

**Expected behaviour:**

The damage should be absorbed (but still be able to break effects that break on damage like Polymorph, etc. - that part works now but it might change if damage is absorbed. )

Here's how it's implemented on Warmane (combat log): 

> Slurpjuice casts Shadow Word: Death at Timber Worg.
> Slurpjuice's Shadow Word: Death failed. (Not yet recovered)
> Slurpjuice's Shadow Word: Death is refreshed.
> Slurpjuice's Shadow Word: Death hits Timber Worg for 850 Shadow.
> Slurpjuice is afflicted by Shadow Word: Death.
> Timber Worg casts Chilling Howl.
> Slurpjuice's Chilling Howl is refreshed.
> Slurpjuice is afflicted by Chilling Howl.
> Slurpjuice's Reflective Shield hits Timber Worg for 67 Holy.
> Timber Worg's attack was absorbed by Slurpjuice.
> Slurpjuice gains 1 health from Slurpjuice's Blessed Recovery.
> Shadow Word: Death was absorbed by Slurpjuice for a moment. (Tick Absorbed)
> Shadow Word: Death dissipates from Slurpjuice.

**Steps to reproduce the problem:**

1. Apply Power Word: Shield (25218)
2. Cast Shadow Word: Death (32996)
3. The backlash damage will go through the shield.

**rev. hash/commit:** 

Sunstrider rev. 10269 (2e509ac3ffb0) 2019-01-19 11:18:46 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
Test with this exact problem reproduced: "spells priest shadow_word_death"
