### ISSUE TITLE
[Quest] 'The Cliffspring River' - can't take a water sample.

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#192]
**Description:**

'The Cliffspring River' (4762) doesn't let the player take a water sample using Empty Sampling Tube (12350) from the Cliffspring waterfall (.go xyz 7202.930176 -401.865601 31.605042 1) (tried under it also. ) It should reward the player with Cliffspring River Sample (12349)

**Current behaviour:**

Can't take a sample.

**rev. hash/commit:** 

Sunstrider rev. 10283 (2e80439ee9a2) 2019-01-22 18:43:47 +0100 (master branch) (Unix, DEBUG, Static)

**Comment by kelno** [comment]
It's supposed to be taken at (6885.42, -649.448, 88.502)
But it's bugged indeed.
