### ISSUE TITLE
Compiling issue: Windows

### ISSUE THREAD

**Issue by talamortis** [ValorenWoW/sunstrider-core#22]
Hi, Sorry this is not a complete template for this but i was wondering how i would compile this? 

I don't have any issues with compiling TC or AC (a project i work with) but i seem to get compile errors on this. I would like to test this source out and maybe push a few PR's to help development of this. I enjoyed TBC back in the day and also wrath.

Any Help would be great! Thanks.

**Comment by kelno** [comment]
Hello, install process should be indentical to TC. We also got install documentation [here](https://github.com/ValorenWoW/sunstrider-core/tree/master/doc).  
If you still got issues with this, please join our discord at http://valoren.org to get assistance!
