### ISSUE TITLE
spell charge can be used in combat stats.

### ISSUE THREAD

**Issue by szhxjt1334** [ValorenWoW/sunstrider-core#31]
**Description:**

spell charge can be used in combat stats. spell Id:100 
I test it in duel pvp.
rev:Sunstrider rev. 9562 (c8a845a1417d) 2018-09-08 22:46:24 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by kelno** [comment]
Can't reproduce, are we talking about the warrior charge?
For me the spell is grayed out when in combat.

**Comment by szhxjt1334** [comment]
The spell is ok. The combat's stats in duel is not working as intended.
