### ISSUE TITLE
Viper trap summons only 1 or 2 Viper.

### ISSUE THREAD

**Issue by szhxjt1334** [ValorenWoW/sunstrider-core#32]
**Description:**
The number of Viper trap triggered viper is wrong. 
Viper trap triigered 2 vipers only.

Sunstrider rev. 9562 (c8a845a) 2018-09-08 22:46:24 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)

**Comment by kelno** [comment]
Thanks. Can you provide source(s) this was the case on TBC?

**Comment by talamortis** [comment]
not a valid source but here is some info

https://wow.gamepedia.com/Snake_Trap

**Comment by kelno** [comment]
https://www.youtube.com/watch?v=XyZyuExJah8&gl=BE
I count about 8 of them in this video. 
(the video shows a retail bug detailed on the snake trap page, fixed in 2.4)

**Comment by kelno** [comment]
Okay I did not understand your issue, you're saying we only have two on this core and there should be more.
