### ISSUE TITLE
Message at connecting: ADDON: CRC (0x4c1c776d) for addon X is wrong

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-core#33]
This message appears in server console when any player connects and gets to characters screen.

	ADDON: CRC (0x4c1c776d) for addon Blizzard_RaidUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_TalentUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_TradeSkillUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_TrainerUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_TimeManager is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_AuctionUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_BattlefieldMinimap is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_BindingUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_CombatLog is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_CombatText is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_CraftUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_GMSurveyUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_GuildBankUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_InspectUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_ItemSocketingUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_MacroUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_RaidUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_TalentUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_TradeSkillUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_TrainerUI is wrong (does not match expected 0x1c776d01), sending pubkey
	ADDON: CRC (0x4c1c776d) for addon Blizzard_TimeManager is wrong (does not match expected 0x1c776d01), sending pubkey

**Comment by kelno** [comment]
@hufsa Yes indeed but setting it back to 0x1c776d01LL doesn't fix the problem. I don't seem to have the error anymore with the Lich King CRC... I don't really understand why.

**Comment by hufsa** [comment]
@kelno I haven't looked closely at this in your core. In my core, I just truncated the addons table after changing the standard CRC to the BC value and the proper info was saved when logging in with the TBC client.

**Comment by kelno** [comment]
Thanks I'll try to do that.

**Comment by kelno** [comment]
Fixed
