### ISSUE TITLE
Preparation is not working.

### ISSUE THREAD

**Issue by szhxjt1334** [ValorenWoW/sunstrider-core#34]
**Description:**

When activated, rogue will not  finish the cooldown on your Evasion, Sprint, Vanish, Cold Blood, Shadowstep and Premeditation abilities.

Sunstrider rev. 9583 (f49f8fbe4771) 2018-09-10 05:49:40 +0200 (master branch) (Unix, RelWithDebInfo, Static) (worldserver-daemon)
<Ctrl-C> to stop.

**Comment by woiwoz** [comment]
case 14185:                                 // fix Preparation Rogue
				{
					if (m_caster->GetTypeId() != TYPEID_PLAYER)
						return;

					const PlayerSpellMap& sp_list = m_caster->ToPlayer()->GetSpellMap();
					for (PlayerSpellMap::const_iterator itr = sp_list.begin(); itr != sp_list.end(); ++itr)
					{
						uint32 ClassSpellId = itr->first;
						if (SpellInfo const *spellInfo = sSpellMgr->GetSpellInfo(ClassSpellId))
						{
							if (spellInfo->SpellFamilyName == SPELLFAMILY_ROGUE && (spellInfo->SpellFamilyFlags & 0x26000000860LL))
								m_caster->ToPlayer()->GetSpellHistory()->ResetCooldown(ClassSpellId, true);	
						}
					}
					return;
				}

**Comment by woiwoz** [comment]
This is my code to fix this problem.
