### ISSUE TITLE
Can not create character (always CONNECTED and nothing more)

### ISSUE THREAD

**Issue by PadreWoW** [ValorenWoW/sunstrider-core#38]
**Description:**

Can not create character (always CONNECTED and nothing more)

**Current behaviour:**

After login to authserver I can not create character - always CONNECTED and nothing more

**rev. hash/commit:** 

last rev

**Operating system and compiler:**
Windows Server 2016

No Firewall!
Ports opened (tested by Telnet)

![error](https://user-images.githubusercontent.com/6802530/45886158-1432a000-bdc1-11e8-92d6-805a68898a97.jpg)

![error2](https://user-images.githubusercontent.com/6802530/45886164-185ebd80-bdc1-11e8-9d7f-234f7887c70e.jpg)

**Comment by kelno** [comment]
1 - What realmlist are you using in your realmlist.wtf? You need 192.168.6.223, I believe 127.0.0.1 won't work with you
2 - Is the RealmId in your worldserver.conf set to 1?
3 - Did you change any config others than DB settings in worldserver.conf?

**Comment by talamortis** [comment]
Change your address to 192.168.6.223 and your localaddress to 0.0.0.0 give that a try

**Comment by PadreWoW** [comment]
1 - realmlist - set realmlist 192.168.6.223
2 - Yes - 1
3 - Yes - but how can other settings affect the connection?

**Comment by PadreWoW** [comment]
**"Change your address to 192.168.6.223 and your localaddress to 0.0.0.0 give that a try"**

0.0.0.0 - not working
localhost - not working
127.0.0.1 - not working

**Comment by PadreWoW** [comment]
Did you add something to RBAC tables?

**Comment by kelno** [comment]
"but how can other settings affect the connection?"
-> That I can think of, WorldServerPort and BindIP
iirc the timezone in db can also cause problems but you're with the default one so you're clear.

So your authserver is clearly working and the problem is at the worldserver part. I'm out of obvious ideas.
We don't use RBAC tables.

- Double check if both your auth and worldserver are connected to the same auth db if you got several dbs.
- Make sure no other authserver or worldserver is running

**Comment by PadreWoW** [comment]
only one server, only one DB :(
no others

Do you have working server?
Can you show me you config, DBs ?

**Comment by PadreWoW** [comment]
Tested with 1.0.2 - NOT WORKING
JUST F*CKING CONNECTED!!!!!

**Comment by PadreWoW** [comment]
Please test your core
I think problem in core - not in my config

**Comment by kelno** [comment]
We're using it everyday locally + a test server is running with this code, something is different on your end.

Here are my config files:
[authserver.txt](https://github.com/ValorenWoW/sunstrider-core/files/2406047/authserver.txt)
[worldserver.txt](https://github.com/ValorenWoW/sunstrider-core/files/2406049/worldserver.txt)

As well as my db config 
https://i.imgur.com/ev5gCnv.png

**Comment by PadreWoW** [comment]
no differents.....only MySQLExecutable..... i have Xampp and MySQLExecutable is here E:\Xampp\mysql\bin

**Comment by PadreWoW** [comment]
Tried to use your config......core crash

**Comment by kelno** [comment]
You replaced the db configs line? I erased them from my shared configs

**Comment by woiwoz** [comment]
I also met this question once, but then somehow disappeared. I don't know how to reproduce this situation.

**Comment by PadreWoW** [comment]
of course i replaced config lines!
I'm not a beginner!

I have my own test server based on OregonCore since 2012 !
But with this core i dont know what happening! :(

**Comment by PadreWoW** [comment]
I checked DB and core and saw:
1) No mob/boss/npc scripts in core
2) No SmartAI scripts in DB

Is it normal????

**Comment by kelno** [comment]
Could you try being more civil ? We're trying to help you and have no obligations to do so.
My config file has all the new configs, it's just that I keep updating it without replacing all the file with the maintained worldserver.conf.dist
We're all using last rev at the moment so that's probably not the issue. 
Also please keep to the issue subject (look for already closed issue about this, or the readme, or the wiki, or discord... the info is already in several places.)

**Comment by PadreWoW** [comment]
Sorry that I'm so nervous
I become angry when I can not understand something.....

Probably not the issue?
You assume this or you checked this?
I did all by the manual and still can not login to the server - no logs, no errors - nothing at all
Just CONNECTED (when wrong password, client said that password is wrong! but when password is ok - just "connected") - from this I can conclude that "auth" is OK, but "world" is bugged

**Comment by PadreWoW** [comment]
Tested on Virtual Machine (Client -> connect to VM throught network) - the same - CONNECTED
and on Localhost (Client on the same machine with the server) - the same - CONNECTED

**Comment by talamortis** [comment]
hmm in your character database please delete all fields for `instance_reset` then try maybe you have a sql flood

**Comment by PadreWoW** [comment]
What does the table instance-has to do with the inability to create a character?

**Comment by talamortis** [comment]
well if your not getting passed the Connected screen its not going to retrieve character list if the sql is looping also we have had this issue on a 3.3.5 source which comparing code seems similar so just wondering if it was doing the same as what it was doing on the 3.3.5.

**Comment by PadreWoW** [comment]
All the same - "connected" and nothing more

**Comment by PadreWoW** [comment]
Can you give me detailed manual and list of software (exactly what you use) for Core compiling and your DBs (auth, characters, world)?

**Comment by PadreWoW** [comment]
I can't understand what's wrong....
Tried clean install:
Win Serv 2016 x64
MariaDB 10.1.36 x64 (no Xampp!)
Cmake 3.8.1 x64
Boost 1.67 x64
OpenSSL 1.0.2p x64
VS 2017 Community x64

FUC*NG "CONNECTED"!!!!!!!!
WHAT A HELL?????

**Comment by PadreWoW** [comment]
Can you give me your auth, characters and world DBs? I don't know what else to do :(

**Comment by PadreWoW** [comment]
checked world conf line by line - on last rev there are no auction bot config lines!
but problem with "connected" is still here :(

**Comment by kelno** [comment]
world and characters databases can't be the problem.
Here is my auth table if you want to check it, but it should be the same you already have
[auth.zip](https://github.com/ValorenWoW/sunstrider-core/files/2419344/auth.zip)

The first account "test" has the password "test".

**Comment by PadreWoW** [comment]
I'll try, but I think problem in Characters table

**Comment by PadreWoW** [comment]
the same bug :(((((

**Comment by PadreWoW** [comment]
I'm 99% shure that the problem is in Characters DB

**Comment by woiwoz** [comment]
No, after you start the server, log on to your account. For the first time, you may have to wait a few minutes.

**Comment by woiwoz** [comment]
It feels more like the core is initializing something.

**Comment by jameyboor** [comment]
Check your firewall. Are ports 8085 and 3724 allowed through it?
Check your Anti-Virus, is it blocking any network traffic?

Download TCPView:
https://docs.microsoft.com/en-us/sysinternals/downloads/tcpview

Start up the authentication and world server and check for Local Port, are 3724 and 8085 both on LISTENING? Are any other processes using port 8085? Is the world server the only one using it?
Such as:
http://puu.sh/BBjrC/100c16fd6d.png

Open up the WoW Client with the `-console` parameter. How far does it get when you connect?

Get this:
https://www.netresec.com/?page=RawCap

Then sniff your localhost and connect with your client. Do you see any data?

**Comment by PadreWoW** [comment]
> 
> 
> No, after you start the server, log on to your account. For the first time, you may have to wait a few minutes.

I waited 20 minutes........just stuck on CONNECTED

**Comment by jameyboor** [comment]
YES THERE IS NETWORK TRAFFIC ON LOCALHOST, YOU JUST DON'T KNOW HOW IT WORKS APPARENTLY.

See, that's how you talk. You really think people want to help you like that? Follow my steps, quite sure it'll fix it.

**Comment by PadreWoW** [comment]
> 
> 
> YES THERE IS NETWORK TRAFFIC ON LOCALHOST, YOU JUST DON'T KNOW HOW IT WORKS APPARENTLY.
> 
> See, that's how you talk. You really think people want to help you like that? Follow my steps, quite sure it'll fix it.

no comments......
I can only say - learn network technology and learn to read carefully

https://github.com/ValorenWoW/sunstrider-core/issues/38#issuecomment-423800510
https://github.com/ValorenWoW/sunstrider-core/issues/38#issuecomment-423942059
https://github.com/ValorenWoW/sunstrider-core/issues/38#issuecomment-424270285

p.s I don't want YOU to help me

**Comment by jameyboor** [comment]
Then don't follow my steps and stay stuck. All good with me.

**Comment by PadreWoW** [comment]
I was not going to do that nonsense that you wrote

**Comment by jameyboor** [comment]
I know that you don't need software to view listening ports buddy buyo. But that piece of software just shows it through a better display.

I also know, my dear friend, that packets sent from localhost to localhost do not go through the network adapter. That doesn't mean that there can't be software blocking it. I sent you the RawCap link because that software allows you to sniff localhost packets.

I then suggested the client console to check at what GRUNT login phase the client is stuck. But hey, you're a know it all so you must know that by yourself as well.

So then Mr senior system admin, why don't you fix it yourself if you're that good. Why don't you just debug the world server and see if it gets any incoming packets. And then once you see that it doesn't you'll notice it's not actually the core's fault. Then you'll finally put your ego aside and try doing what I told you to do and you realize something else is listening on port 8085. :)

**Comment by PadreWoW** [comment]
I am speechless.....
PLEASE TURN ON YOU BRAINS AND READ MY POSTS CAREFULLY!

I TESTED PORTS BY TELNET AND NETSTAT!!! TESTED!!!!!! THEY ARE LISTENING AND FREE!!!!!!!!!

I can not fix it because I'M SYSTEM ADMINISTRATOR! NOT PROGRAMMER!!!!!! DO YOU KNOW DIFFERENCE?

Please just shut up and stop bullshit. I'm tired to read your nonsense.

I need help from competent people! Not from you!

**Comment by jameyboor** [comment]
Still didn't sniff or checked if worldserver receives any traffic.

**Comment by PadreWoW** [comment]
Read my previos post

**Comment by kelno** [comment]
You may need to empty your characters database for this to work.
