### ISSUE TITLE
Will there be a seperate db repository?

### ISSUE THREAD

**Issue by oppahansi** [ValorenWoW/sunstrider-core#39]
Title. 

Like many other emulators offer a seperate db repo, will you offer one too?

**Comment by kelno** [comment]
We currently have the db in releases in this repo https://github.com/ValorenWoW/sunstrider-core/releases

**Comment by oppahansi** [comment]
thx,

but are there any plans to seperate db stuff from core repo?

**Comment by kelno** [comment]
-> see my edit

**Comment by oppahansi** [comment]
I am not sure, maybe I am just used to cmangos core repo + db repo systems
basically seperating most db stuff from core repo.

**Comment by kelno** [comment]
Okay. I have no problem with creating one when we see a good reason to, until then it will stay in releases.
