### ISSUE TITLE
creature don't move home when they chase with the distance they should enter evade and go home.

### ISSUE THREAD

**Issue by szhxjt1334** [ValorenWoW/sunstrider-core#4]

**Comment by SUN-Leekie** [comment]
Hello, can you please provide more information on where this happened? I just tried it and saw no problem with monsters resetting.

**Comment by kelno** [comment]
This was fixed in 41f7dc5a6f0b67743c8845ac7abe7a1afcc10ad4, are you using an older revision?

**Comment by kelno** [comment]
Then case closed!
