### ISSUE TITLE
Arathi Bassin BG flags can't be retaken

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-core#41]
All flags in Arathi Bassin are actually never spawned/despawned, but made visible when needed.
When a flag is taken once, it cannot be taken again.
For example, after the start of the bg:
- Horde player takes the forge (flag goes to gray-horde)
- Alliance player takes the forge (flag goes to gray-alliance)
- Horde player takes the forge (flag goes to gray-horde)
- Alliance player cannot take the flag anymore. His client does not allows it anymore (While the server does)
Here is a video on how to reproduce: https://cdn.discordapp.com/attachments/483668912895164426/496413074383831053/flagbug.webm

Additional notes
- This is fixed if the player restart his game or reenter the map.
- This only affect the player that has already opened the flag. Other players standing near the action the whole time can still use the flag.
- The Update Fields are exactly the same the first time the flag appears and the second time it appears. This is not the cause of the problem.
- The flag are actually buttons, we may want to check how buttons are usually handled

Some ideas:
- Spawn new banners instead of reusing them. Or regenerate banners guid? Potentially dangerous.
- Send a loot release?

**Comment by kelno** [comment]
https://cdn.discordapp.com/attachments/483668912895164426/496413074383831053/flagbug.webm

**Comment by Nolin7777** [comment]
👍
