### ISSUE TITLE
Something wrong with Appender/Logger system

### ISSUE THREAD

**Issue by PadreWoW** [ValorenWoW/sunstrider-core#42]
**Description:**

Something wrong with Appender/Logger system

**Current behaviour:**

I can not see logs: Player, Character, Chat (in Console and in Files)
Can not change color of GM log in console (every time i see INFO color)

**Steps to reproduce the problem:**

My config:
Appender.Console=1,2,1,"1 9 8 13 7 12"
Appender.Server=2,2,0,Server.log,w
Appender.GM=2,2,1,GM.log
Appender.Chat=2,2,1,Chat.log
Appender.Char=2,2,1,Char.log
Appender.DBErrors=2,2,0,DBErrors.log
Appender.Warden=2,2,1,Warden.log

Logger.root=5,Console Server
Logger.server=2,Console Server
Logger.commands.gm=2,Console GM
Logger.chat.log=3,Console Chat
Logger.entities.player.character=4,Console Char
Logger.sql.sql=3,Console DBErrors
Logger.warden=3,Console Warden

**rev. hash/commit:** 

last rev

**Comment by kelno** [comment]
Can anyone confirm this?

**Comment by PadreWoW** [comment]
any news?

**Comment by kelno** [comment]
There is something wrong with your config.
- You've set a logger with filter "entities.player.character" and level 4 (warning), there is only one log line in the code with this filter and it is level 3, so this logger will never be used.
- There is not log lines with the filter "chat.log"

I don't remember seeing the console colors ever working so this part might be a bug indeed.

**Comment by PadreWoW** [comment]
Wait....I need log file with CHAT - you said that I can not create such line?
console colors are working, but strange....
you can use my config for colors and see the result

**Comment by kelno** [comment]
You can create loggers for all that, but please follow the tutorial from TrinityCore I linked to learn how.

About the colors, are you on windows or unix ?

**Comment by PadreWoW** [comment]
Windows Server 2016

**Comment by kelno** [comment]
I don't think it's supposed to work on windows.

**Comment by PadreWoW** [comment]
It works
Trust me
But not for all logs.....and i don't know why

![default](https://user-images.githubusercontent.com/6802530/46539742-09e3cc00-c8c0-11e8-9c63-0c3547c3d264.png)

**Comment by PadreWoW** [comment]
Your tutorial frfom Trinity is useless for me....
There is no answer how to force core to create Chat logs......

**Comment by kelno** [comment]
I can't really give you a better explanation on what's wrong with your config than I already did, and I'm not here to write the config file myself.

There is no logging line for character chat so you'd have to create one to be able to print them in console.

I'm going to close this one as there is no real issue except for the colors, which we don't really care about. Issues are not for support.

**Comment by PadreWoW** [comment]
but how can administrators read chats without logs????

**Comment by kelno** [comment]
Chat logs are still saved in db in `logs` database
