### ISSUE TITLE
Shaman unable to get call of fire quest

### ISSUE THREAD

**Issue by nyana987** [ValorenWoW/sunstrider-core#4418]
**Describe the bug**

Cannot pick up the quest for call of fire at all. I can get the other totem quests though
**Character name**

nyanachan
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=
https://classic.wowhead.com/quest=1522/call-of-fire
**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Wrong NPC.
