### ISSUE TITLE
ring of blood - nagrand arena bugged.

### ISSUE THREAD

**Issue by vulezije** [ValorenWoW/sunstrider-core#4419]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by vulezije** [comment]
cant start the quest

**Comment by Jerrythemagicdog** [comment]
Thanks, we believe we've found all the cases now, live with next update. For now if there are still issues please open a ticket.
