### ISSUE TITLE
Barber

### ISSUE THREAD

**Issue by bugged-tech** [ValorenWoW/sunstrider-core#4420]
I suggest adding an npc with an option to change the hairstyle or facial hair for free or for gold, your choice.

**Comment by Jerrythemagicdog** [comment]
That's the appearance change service on the website. Thanks for the suggestion, usually we try to stay away from adding NPCs.

**Comment by bugged-tech** [comment]
Yeah, but probably no one buying that for coins coz its not worth.

**Comment by bugged-tech** [comment]
> That's the appearance change service on the website. Thanks for the suggestion, usually we try to stay away from adding NPCs.

Yeah, but probably no one buying that for coins coz its totaly not worth.
