### ISSUE TITLE
netherstorm quest, Captain Tyralius

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4421]
when you free captain tyralius, only one person can get quest completion after opening the prison bubble.  has a 2-3-5m cooldown on the orb before you can do it again for the next person.  captain will respawn, then bubble will respawn, then you can open the bubble again and do it for the next perswon

**Comment by Jerrythemagicdog** [comment]
Yes, the quest requires you to interact with the prison.
