### ISSUE TITLE
[Darkmoon faire hand in bug]

### ISSUE THREAD

**Issue by Slamminn** [ValorenWoW/sunstrider-core#4423]
Hello, I reported this bug about 5 months ago now, no word on it being acknowledged or anything, so I thought I would repost it again with updated findings (and a video of showing the bug)

**Describe the bug**
Once handing in ~15 hand-ins of 'Dense grinding stones' the quest moves to "Chronos", where you should still be able to hand in these for tickets. However, the quest is bugged. So that you can-not select the quest (nothing happens when you click on it). He also has the other quest for handing in "Rugged armour kits" however this one works correctly (shown in the video). It is just the dense grinding stone hand in that doesn't work. 

**Character name**
N.A.

**To Reproduce**
Basically you can not repeat the quest, because nothing happens when you click on it. I have uploaded a youtube video (unlisted) in the link below to show this in-game. This footage was captured on the 5/11/2020. (link below)

**Expected behavior**
You should be able to accept and complete the hand-in, but nothing happens (basically it doesn't even respond to clicking it).

**Screenshots/videos**

Video Link: https://www.youtube.com/watch?v=MCSLegUqW4A&feature=youtu.be

**Additional context**
Again posted this a about 5 months ago, nothing has been commented or acknowledged, so I thought I would highlight this issue again (I would like to get the darkmoon faire amulet, via the use of dense grinding stones (I have them all already), but I have been sitting on them for ages because I can't complete the hand-ins.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
