### ISSUE TITLE
Improved Counterspell

### ISSUE THREAD

**Issue by summen** [ValorenWoW/sunstrider-core#4424]
**Describe the bug**
if used only for the 4 sec silence through talents and not interrupting any cast, it occures sometimes to have just no effect. there is no "resist" shown, neither on the targets combat text nor inside combat log. its just not shown anywhere, but cooldown gets activated.
Not sure about it, but seems to accure more often on priests. but maybe thats just random percaption.

**Character name**
Summen

**To Reproduce**
yet i didnt find a way to reproduce it. think its only an issue in pvp, never recognized it in pve.

Spell: https://wowwiki.fandom.com/wiki/Improved_Counterspell

**Expected behavior**
4 sec silence or "resist" prompt/log

**Comment by Jerrythemagicdog** [comment]
The silence effect and the interrupt effect can be resisted separately with no combat log message.
