### ISSUE TITLE
alchemy... swapping masteries

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4425]
jupiterchan was an elixir master, i dropped elixir mastery (paying 150g) and i should be able to go to the transmute master simply by talking to  stormwind nethterstorm (zarevhi) and learn transmute mastery, but I don't see the option.  I don't remember there being a reputation requirement, but i am friendly with consortium... and i couldn't find any reference to one on popular wow information sites.  I also checked potion mastery, in Cenarion Refuge and I can't take potion mastery there either on this same toon.  I checked the elixir master in shat, i can relearn elixir mastery.

Either the toon is bugged or swapping alchemy masteries is not working the way its described on wowhead and other major wow information sources and on other private servers.  you pay the gold to drop the current mastery, you talk to the other master and instantly learn it (without doing the original mastery quest for the new mastery

**Comment by Jerrythemagicdog** [comment]
Thanks, that's a problem after recent changes, fixed with next update.
