### ISSUE TITLE
Bloodmaul Brewmaster

### ISSUE THREAD

**Issue by crookqtftw** [ValorenWoW/sunstrider-core#4427]
**Describe the bug**
<Fighting the Bloodmaul Brewmaster, he cast's a debuff that lasts 24 seconds its supposed to make you drunk. The problem is that after the 24seconds is done you still remain drunk>

**Character name**
<Nightmarish - > Bloodmaul Brewmaster >

**Expected behavior**
<For the drunkeness to be gone after 24seconds. Maybe my expectation is wrong>

**Comment by Jerrythemagicdog** [comment]
The drunkenness effect is independent of the buff, thanks for the issue though. Maybe that's something we should consider changing seeing how irritating it is for players.
