### ISSUE TITLE
training dummies in orgrimar/thunder buff... and others?

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4428]
the training dummies in orgrimar and thunderbluff are missing.

at least they're not in their usual spot.

**Comment by michaelkittrell** [comment]
i did find 2 dummies below thunderbluff on the ground, but the ones up on hunter rise are missing.

**Comment by Jerrythemagicdog** [comment]
There is no usual spot for dummies in TBC, there are dummies in Orgrimmar behind the Warrior trainer building and in front of Orgrimmar.
