### ISSUE TITLE
Zulaman eagle boss gauntlet, can't run in "event in progress"

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4429]
A few weeks ago ZA changed in that if you die during the eagle boss gauntlet... you can't run in because "event in progress"... prior to that if you died you could run back in and rejoin your group (in addition to being able to ress between packs if you were fast enough).

was this intended behavior?

or did it happen as an unintended consequence of the fix to this issue   https://github.com/SunstriderEmu/BugTracker/issues/4315

**Comment by Jerrythemagicdog** [comment]
Yes, that's intended.
