### ISSUE TITLE
nagrand maghar quests showing exclamation even if you don't have rep to talk to them, Warden Bullrok

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4431]
Warden Bullrok (55.74, 37.96) shows a quest exclamation point for a toon that can't talk to him (no maghar rep).

if this is correct behavior, im pretty sure its inconsistently implemented on other factions/quests.

**Comment by Jerrythemagicdog** [comment]
Seems correct.
