### ISSUE TITLE
Felsworn Daggermaw/Daggermaw Lashtails (Raptors) using wrong Infected Bite spell

### ISSUE THREAD

**Issue by Massie323** [ValorenWoW/sunstrider-core#4435]
**Describe the bug**

The Raptors in Bladed Gulch (Blade's Edge Mountains) wrongly use the 3 minute Infected Bite ability instead of the 30 second one, making it ridiculous to pull more than 3 of them as you will take high DoT damage over 3 minutes as well as a huge increase in Physical DMG taken.

**To Reproduce**

1. Engage a Felsworn Daggermaw or Daggermaw Lashtail
2. Wait a few seconds for it to apply the ability.

Correct Spell: 
Level scaling Infected Bite
https://db.rising-gods.de/?spell=7367
https://db.endless.gg/?spell=7367
https://www.wowhead.com/spell=7367/infected-bite

Wrong current Spell: 
Infected Bite from ZG Raptors
https://db.endless.gg/?spell=24339#used-by-npc
https://wotlk-twinhead.twinstar.cz/?spell=24339

Strange Database anomaly:
Endless DB lists two Infected bites for the 2 Raptor versions
https://www.wowhead.com/spell=16128/infected-bite (used by Elite Raptors in front of Gruul)
https://db.endless.gg/?spell=16128#used-by-npc

**Expected behavior**

Instead of the ZG Infected Bite, the non-elite raptors in BEM should use a much lower hitting and shorter lasting spell. 
I don't know if the bites should still stack, however with the correct version, having the debuffs stack would be a lot more bearable.

**Additional context**

The bites tick for ~250 DMG per tick over 3 minutes, matching the values for ID 24339.

**Comment by Sheikthecatman** [comment]
Thanks! The raptor spell has been corrected and fix will be live next server restart.
