### ISSUE TITLE
 The Ring of Blood: Rokdar the Sundered Lord quest is bugged !!!

### ISSUE THREAD

**Issue by vankata232** [ValorenWoW/sunstrider-core#4436]
**Describe the bug**
Roktar one of the bosses of Nagrand arena chain quests (I believe it's called :''The ring of Blood" ) is bugged and doesnt count as completed quest after he's being killed. I've killed him numerous times but it doesnt complete .

**Character name**
Bobodebeliq

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Sounds like someone tagged your creature, the quest credits correctly.

**Comment by vankata232** [comment]
> Sounds like someone tagged your creature, the quest credits correctly.

What do you mean , the quest credits correctly , have you tried it ? ... We killed him at least 10 times yesterday  and the quest wasnt completed,also today a friend of mine (Bobkata - nickname did it and didnt work ) so i dont know what you are talking about ???

**Comment by vankata232** [comment]
What are you talking about ??? The quest isnt fixed ! I did it at least 10 times yesterday and couldn't complete it , also today a friend of mine and guildees did it and also said its bugged and they couldn't complete it as well.









 >-------- Оригинално писмо --------

 >От: Jerrythemagicdog notifications@github.com

 >Относно: Re: [SunstriderEmu/BugTracker]  The Ring of Blood: Rokdar the
 Sundered Lord quest is bugged !!! (#4436)

 >До: SunstriderEmu/BugTracker  

 >Изпратено на: 10.11.2020 00:26



 
 
  
  
  
Sounds like someone tagged your creature, the quest credits correctly.
