### ISSUE TITLE
Songflower

### ISSUE THREAD

**Issue by jebossue** [ValorenWoW/sunstrider-core#4437]
This "bug" rely to the old post Songflower #901

Actually there's absolutely no Corrupted Songflower in felwood. 
https://classic.wowhead.com/object=164886/corrupted-songflower

I wonder if you did this in purpose, therefore is that a way to nullify all buffs that should be available with classic ?
With the incoming "nearly impossible" SWP those kind of buffs can make a difference between a kill and an other 10 hours try on a boss ;)
So the final question is : which buff can we expect to use for that last progress ? 
Apart from adal buff.

Thanks a lot for this great server !

**Comment by Jerrythemagicdog** [comment]
All world buffs are removed when entering a raid.
Here are some Corrupted Songflowers on the live server right now:
![image](https://user-images.githubusercontent.com/46463908/98604124-0a3ec480-22db-11eb-85ee-f186cc372d95.png)

**Comment by jebossue** [comment]
Thx for the answer, quite weird i have check every position in felwood maybe not the same position as classic or someone already used it.
Sorry for the inconvenience
