### ISSUE TITLE
Kael'thas legendary daggers VERY HARD to loot

### ISSUE THREAD

**Issue by GigilPiq** [ValorenWoW/sunstrider-core#4438]
- Current behavior:

Kael'thas legendary daggers in the second phase (Infinity Blades) are almost impossible to be loot on death. There is something about the hitbox being very very small or the entity being under map. Changing the camera angle kinda fixes the problem but it's very unreliable and slow.

- Expected behavior:

Kael'thas legendary daggers should be easily looted ?

- Steps to recreate issue:

Step 1: Start Kael Event
Step 2: Kill all 4 adds.
Step 3: Kill the Infinity Blades, try to loot them.

**Comment by Jerrythemagicdog** [comment]
That's not something we can change, sorry!

**Comment by kelno** [comment]
Confirming that, this is clientside unfortunately, not something we can really affect.

**Comment by Massie323** [comment]
Is there any reason though why it has suddenly started to happen now? Like weeks ago this wasn't an issue, and now it seems like Kael's arcane asscheeks are overshadowing the target hitbox of the daggers.

**Comment by kelno** [comment]
I've heard report of the issue since the very beginning, in this place and others (like recently on the Headless Horseman)
