### ISSUE TITLE
Weapon disappeared on relog.

### ISSUE THREAD

**Issue by Bushidorae** [ValorenWoW/sunstrider-core#4439]
**Describe the bug**
I had a Mongoose enchanted Vindicator's Brand from Exalted reputation with The Aldor.  I did a scryers quest and dropped below exalted reputation with The Aldor.  When I logged back in the weapon had completely disappeared from my inventory.  I returned my reputation to exalted to test if it would return to my inventory if I relogged and it did not.

**Character name**
Raion

**To Reproduce**

1. Obtain exalted with The Aldor and Vindicator's brand with mongoose enchant. 
2. Drop reputation by doing a quest that negatively effects aldor reputation.
3. Relog.

Item: https://www.wowhead.com/item=29124/vindicators-brand
Spell: https://www.wowhead.com/spell=27984/mongoose

**Additional context**
I would really like the bug fixed and the item restored for my character.  Thank you!

**Comment by Jerrythemagicdog** [comment]
You have the item equipped on your character.
