### ISSUE TITLE
Donating to buy coins

### ISSUE THREAD

**Issue by Oyock** [ValorenWoW/sunstrider-core#4440]
I, as well as several other Americans, have been unable to donate to the store because our cards recognize fasterpay.com as a unsavory source. Some of our banks have been unwilling to participate, and furthermore, ordering a prepaid card does not allow the process either, when decentralized from a bank. Hopefully you guys can add a different source such as paypal or something more reputable for Americans to more easily donate. Otherwise, myself and our friends will be unable to contribute to the server.

**Comment by Jerrythemagicdog** [comment]
Thanks, we're looking into adding more options.
