### ISSUE TITLE
ssc, lurker... spout still not fixed

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4442]
comment in this original report 12 days ago says let you know if its not fixed.

https://github.com/SunstriderEmu/BugTracker/issues/3740

Was there Sunday and first spout about 5s in he spouted in a random direction and killed 5 people instantly.

**Comment by michaelkittrell** [comment]
if i recall correctly it worked fine for the first couple weeks of release then something changed and this random spouting behavior started happening.

**Comment by kelno** [comment]
Seems fixed now, do tell if that's still happening sometimes
