### ISSUE TITLE
Ring Of Blood

### ISSUE THREAD

**Issue by Belfin1** [ValorenWoW/sunstrider-core#4443]
**Describe the bug**

Ring of Blood questline is bugged and wont complete when killing the third quest boss
**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Fixed with next update (soon), thanks for the issue.
