### ISSUE TITLE
BT, Supremus, threat addons

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4444]
omen and diamond both were reporitng pretty bad data for this fight.

in the first 30s of p1 after the pull... tank was at 30k, then tank was at 8k then tank was at 17k.  My threat as a hunter (and other people complaining) was all over the place i was below then i was above (and didn't pull) and then i was even.  

My wife who raids in another guild echo'd that omen/diamond are reporting weird shit in their raid too.

any chance you guys could think about what is different for supremus and adjust it so these addons are reporting threat better?

i know thats not really your job to fix addons, but i have to imagine that its some data coming from the server thats producing this result.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
Omen (and probably DTM) relies on a certain emote text from the boss to signal the threat wipe, it was currently done at incorrect times.

**Comment by michaelkittrell** [comment]
you guys are so awesome.  thanks
