### ISSUE TITLE
Marks of Kiljadaen quests

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4446]
The first Marks of Kiljadaen quest gives Shatar rep and is reported to player

The "More marks" and "single mark" quest seem to give rep but do not report it to player.

**Comment by michaelkittrell** [comment]
give rep at neutral at least.  pretty sure they all stop giving rep at shatar honored, but didn't specifically test that just now.

**Comment by Jerrythemagicdog** [comment]
That's expected.

**Comment by michaelkittrell** [comment]
why is it expected that they don't report the rep you get from shatar?
