### ISSUE TITLE
Alchemy mastery quest

### ISSUE THREAD

**Issue by bugged-tech** [ValorenWoW/sunstrider-core#4448]
Hi, I accidentally dismissed the alchemy mastery quest and now can't do it again, is there an option to restore?

**Comment by Jerrythemagicdog** [comment]
Pick up the quest again from the specialization trainers.

**Comment by bugged-tech** [comment]
> Pick up the quest again from the specialization trainers.

Im in thrallmar, and can't take again that quest

**Comment by Jerrythemagicdog** [comment]
Yes, you probably handed that quest in and need to go to one of the specialization trainers in Shattrath, Cenarion Refuge or Stormspire depending on which specialization you've picked. If you wish to switch it then you need to complete that quest chain and then you'll be able to switch to any other specialization for 150 gold.
