### ISSUE TITLE
The Fel and the Furious, smv quest

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4452]
i was in a group with 4 people who needed quest.  i did it with the first toon and completed it.  i was in process of doing on the second toon and i got a message that it failed for it and the other 2.  At this point a fel reaver ran up to the controls and attacked the defender there.  I dropped quest retook it on 3 toons went back to the controls, killed the fel reaver.  Clicking on the controls (with the this is a quest object sparklies) results in a message "You have no target".   I dropped the 3 toons from the group, dropped and retook the quest, same issue.  I waited a bit tried a few things that didn't really work, eventually i was able to click a control and control a fel reaver.  i did the quest it shows completed in my quest log, but im unable to turn it in (QUEST giver says "You're back, so i'll assume the operation went well.  what've you got to report? but only a cancel button available).  I took the 3rd char and did the quest, turned it in.  The fel reaver ran up again and i had to kill it.  4th toon drops and retakes quest and gets the same "no target" message when clicking the controls.  when i finished the 4th toon, i ran up the stairs at the back and dropped the buff, turned in quest real quick.  Dropped quest on 2nd toon, redid it, did the same stairs thing with dropped the buff and turned in.  not sure if the stairs thing makes any difference or maybe its turning in the quest immediately after clicking off the buff.  

also, everytime you use the rockets it seems that you kill exactly 9 infernals.  seems ... calculated.

**Comment by Jerrythemagicdog** [comment]
There's a timer on the quest, I don't think the quest is expected to work in party. Fighting NPCs on stairs has no impact on being able to complete the quest. If there's an error saying "You have no target" that means there's no nearby Fel Reaver to control. Sounds like something that is an issue primarily for players multiboxing.

**Comment by michaelkittrell** [comment]
its not logical for me to think that if a quest isn't working its because I'm in a group...  or a raid for that matter.

if you don't want to fix the quest so it works in a group...  maybe you can instead make it so the controls won't activate/sparkle if you are in a group.  At least then you wouldn't be fumbling around wondering why it wasn't working or what target you're supposed to have and wondering if the quest is bugged or what...
