### ISSUE TITLE
Bug with a wand that droppes for UB(HC)

### ISSUE THREAD

**Issue by feelmyname** [ValorenWoW/sunstrider-core#4453]
The Black Stalk, wand, that droppes in UB(H), does not give my chatacter any intellect, though gives other stat just fine. 

[https://i.imgur.com/ueW5o4n.png](url)
[https://i.imgur.com/4pm2eA8.png](url)

**Comment by Jerrythemagicdog** [comment]
Clear your Cache and take a look at the item stats.
