### ISSUE TITLE
Badge of Justice limit

### ISSUE THREAD

**Issue by stme00** [ValorenWoW/sunstrider-core#4454]
**Describe the bug**

I seem to have reached a limit of how many BoJs I can have on a character. Did Kara yesterday but the amount of BoJ in bag is not counting up more than 169. The same happens to a guild mate.

**Character name**

Stekpanna

**To Reproduce**

1. Doing any HC or raid boss that reward BoJ when you have 169 BoJ in bag
2. 
3. 

Item: https://wowhead.com?item=29434
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

Being rewarded BoJ

**Screenshots/videos**

N/A

**Additional context**

**Comment by Jerrythemagicdog** [comment]
There's no such issue with your character, this test was performed with a copy of your character 
![image](https://user-images.githubusercontent.com/46463908/98964509-c927f980-2500-11eb-935b-aecacc59cf8a.png)
