### ISSUE TITLE
Quest Zapped Giants in Feralas - Can't validate quest

### ISSUE THREAD

**Issue by Najaxx** [ValorenWoW/sunstrider-core#4455]
**Describe the bug**
I have the 15 miniaturization residues but I can't validate the quest. The complete quest button is grey.

**Character name**
Najaxx

**To Reproduce**

1. loot the items
2. went to validate
3. cant click

**Expected behavior**
validate quest

thank you

**Comment by Jerrythemagicdog** [comment]
Issue happened because of the downtime, for now just move the items from bank to inventory, sorry!
