### ISSUE TITLE
BT reliquary of souls, crash bug?

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4456]
We were in BT at ROS and lagged out several times in p2.  We assumed it was a server crash (could not reconnect for 30+ seconds each dc) and just random... but after we gave up the server didn't go down again (if it was ever crashing i didnt verify)  

my wife's guild was in ROS several hours later and at ROS they lagged "so badly that it was unplayable"... but they did manage to finish the fight without dcing.  

if you guys don't know what the crashes were today... maybe take a look at ros/bt

**Comment by Jerrythemagicdog** [comment]
Not RoS related, but thanks for the issue
