### ISSUE TITLE
Sleeveless T-Shirt does not drop

### ISSUE THREAD

**Issue by ayse33** [ValorenWoW/sunstrider-core#4457]
So after a talk with one of the gm's,it was confirmed that the shirt indeed does not drop,the shirt drop off alliance players when looted and most alliance npcs in alterac valley but for some reason it doesn't drop on endless which is sad considering that shirt is quite unique and has flavor text making fun of alliance players.

Staff,it would  be much appreciated if you can make the shirt drop again,and i can guarantee most horde players that do av will have it equipped,thanks.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
