### ISSUE TITLE
botanica, Tempest Forge Peacekeeper

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4458]
in botanica normal, if you are a prot pal fighting the tempest-forge peacekeeper... and he does a knock up.  he will do some sort of evade and teleport on you and oftentimes heal for half his health.   If you are fighting 2-3 mobs with it, they also will exhibit similar behavior.

can you make the teleport on evade timer a bit longer or fix the peacekeeper unable to target you while you are knocked up by his effect?

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart, thanks.
