### ISSUE TITLE
Birds of a feather quest is bugged (Not spawning birds when nest opened)

### ISSUE THREAD

**Issue by alextarapatin** [ValorenWoW/sunstrider-core#4459]
**Describe the bug**
Bird nest does not summon baby bird when interacted with

**Character name**
Lockhotdot

**To Reproduce**
Accept the quest and interact with a nest - See no bird appear

Quest: https://www.wowhead.com/quest=9397/birds-of-a-feather

**Expected behavior**
A bird should spawn and the nest disappear when used

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
