### ISSUE TITLE
Portals at The Dark Portal not working

### ISSUE THREAD

**Issue by InhumanGM** [ValorenWoW/sunstrider-core#4460]
**Describe the bug**
The portals to Stormwind City and Orgrimmar located at The Dark Portal, Hellfire Peninsula, are not functional.

**To Reproduce**

1. Go to The Dark Portal
2. Try to click on one of the portals.

**Expected behavior**
Clicking on the Stormwind City portal should teleport you to Stormwind City.
Clicking on the Orgrimmar portal should teleport you to Orgrimmar.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.

**Comment by InhumanGM** [comment]
Issue has resurfaced, now the portals can be clicked on but nothing happens after clicking.

**Comment by Jerrythemagicdog** [comment]
Indeed, fixed with next restart, thanks.

**Comment by Godmatik** [comment]
Those portals are supposed to be cosmetic and should not teleport you at all, unless this was a custom planned change?

**Comment by Jerrythemagicdog** [comment]
It's something players are used to from playing other servers like Warmane I suppose and it's a nice convenience so I suppose it goes under custom changes.
