### ISSUE TITLE
quest <Plants of Zangarmarsh>

### ISSUE THREAD

**Issue by pasler** [ValorenWoW/sunstrider-core#4461]
**Describe the bug**
I abadonned the quest, because of completing issue and when i want to take it again the NPC Lauranna Thar'well had no quests.

**Character name**
Vlasta

Quest: https://www.wowhead.com/quest=9802/plants-of-zangarmarsh

**Comment by Jerrythemagicdog** [comment]
You're over the reputation limit at which the quest is available to hand in.
