### ISSUE TITLE
Hunter pet not showing up after dismount attack, hunter pet spawning after dismount with 70% health.

### ISSUE THREAD

**Issue by timk900** [ValorenWoW/sunstrider-core#4462]
Hunter pet not showing up after dismount attack, hunter pet spawning after dismount with 70% health. Ive done the attack/dismount thing multiple times to test it. Seems to happen everytime i fly near the ground and straight when i attack/auto dismount. the pet health thing is just constant

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
