### ISSUE TITLE
aggressive flying fish in ssc

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4463]
ssc fish are sometimes able to get above water and on platforms (near edges but clearly out of the water and attacking)

also, they seem a little more aggressive this week, don't usually have trouble making it to platforms but saw a lot of dead people today.  doubt they all just forgot how to jump.

**Comment by Jerrythemagicdog** [comment]
That's expected because of some imprecisions there, spawning fish is just a height check with some leeway for water walking which will still spawn fish.
No changes to the fish have been made since release, thanks for the issue.
