### ISSUE TITLE
argent crusade quartermaster

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4464]
argent crusade quarter master in lights hope chapel in eastern plagueland seems to be missing?

**Comment by Jerrythemagicdog** [comment]
If I remember correctly he was removed because of completely incorrect costs before launch and some possibilities of abuse, so the costs would be the first thing to fix here.

**Comment by Sheikthecatman** [comment]
![image](https://user-images.githubusercontent.com/59149613/100545154-d8c27480-325a-11eb-919e-27004336ea26.png)
She's there
