### ISSUE TITLE
The old hilsbrad foothills help thrall

### ISSUE THREAD

**Issue by Ruvexx** [ValorenWoW/sunstrider-core#4466]
hello i cant seem to finish the quest escape the durnholde. trall is not giving the option to help him and i cant finish the quest wich i need to go to a dungeon the black morass. please fix the quest or furfill the quest. thank you!

**Comment by Jerrythemagicdog** [comment]
You need to free the Orc prisoners and defeat Lieutenant Drake first in order to start the Thrall escort. Once you escort Thrall and defeat all the bosses the quest will complete.
