### ISSUE TITLE
ZA removing flask on death

### ISSUE THREAD

**Issue by falopaa** [ValorenWoW/sunstrider-core#4468]
The flask effect persisting through death is not working on some death on ZA, have happened me a couple of times now my flask suddenly disappear after dying

 Falopa

**Comment by Jerrythemagicdog** [comment]
Sounds like some addons are lying to you about the flask durations.

**Comment by falopaa** [comment]
that is not possible: both times this have happened to me first i wasnt the only one affected, my friends as well lost their flask. Second i checked with my raid if they could see my flask on and they couldnt. Finally i used another flask while cheking my stats and they went up after using it.
