### ISSUE TITLE
Status: Terminated !!!

### ISSUE THREAD

**Issue by Akioqq** [ValorenWoW/sunstrider-core#4469]
Hello ! What does Using automated software / bots mean? I don't use any programs! I play normally, you are confusing me with someone! Check the logs again! This is definitely a big mistake on your part!

My nickname in the game: Whisperwind, female human rogue alliance 

I urgently demand to unblock my account!

**Comment by Akioqq** [comment]
WHY U CLOSED!

**Comment by Jerrythemagicdog** [comment]
This is an issue tracker for in-game issues, not a way to ban appeal. If you'd like to appeal a ban send an email to hello@endless.gg
