### ISSUE TITLE
ZA flask getting removed while chest farming before 2 hours

### ISSUE THREAD

**Issue by falopaa** [ValorenWoW/sunstrider-core#4470]
The flask effect persisting through death is not working on some death on ZA, it has happened to me a couple of times now, my flask suddenly disappear after dying way before 2 hours.

no add-on were involved on this since last two weeks this has happened i wasnt the only one affected, some of my friends as well lost their flask. Second i checked with my raid if they could see my flask on and they couldnt. Finally i used another flask while cheking my stats and they went up after using it.

plz dont close this issue if you hadn't ask for details

**Comment by Jerrythemagicdog** [comment]
You've provided no details, no Flask names and no reproduce steps, it's pretty difficult to work with that little information.
At the same time you're the only player reporting this issue with the content being out for a long time now which leads me to believe it's an oversight on your end.
