### ISSUE TITLE
The big bone worm

### ISSUE THREAD

**Issue by DwarvenJoe** [ValorenWoW/sunstrider-core#4471]
This quest has to be bugged I have now tried completing it on 3 diffrent characters with hundreds of attempts on each and the big bone worm will not spawn, spent hours just hitting that drum and no matter how bad my RNG is that just cant be right, the chance for this questmob to spawn has to be increased by a huge amount.

**Comment by Jerrythemagicdog** [comment]
Thanks, the chance was indeed really low, fixed with next update.
