### ISSUE TITLE
ZG Potion (Swiftness of Zanza) lost on death

### ISSUE THREAD

**Issue by Massie323** [ValorenWoW/sunstrider-core#4473]
**Describe the bug**

The speedbuff potion is lost upon death when it should persist through it.

**To Reproduce**

1. Drink Swiftness of Zanza
2. Die
3. Look at buff bar

Item: https://classic.wowhead.com/item=20081/swiftness-of-zanza
Quest: https://classic.wowhead.com/quest=8243/zanzas-potent-potables

**Expected behavior**

The buff should stay through death.

**Comment by Jerrythemagicdog** [comment]
https://classic.wowhead.com/item=20081/swiftness-of-zanza#comments:id=3081346

**Comment by Jerrythemagicdog** [comment]
The client data is also consistent with that comment.
