### ISSUE TITLE
Warlock pet disappears when dismounting

### ISSUE THREAD

**Issue by frumslol** [ValorenWoW/sunstrider-core#4474]
My pet randomly disappear when i dismount, it seems to happen more often when i dismount while jumping.  I thought this was odd because it did not happen on another server that i used to play on.

I've watched youtube videos to see if this is how it's supposed to be but it seems like the pet spawn should be delayed for about a second. I do not know if this is the solution but it would give you time to land before the pet spawns. Another solution would be to not have the pet despawn while mounted

It happens for both the Imp and the Voidwalker. (The only two pets I have to try with)
I've also spoken to a hunter who seems to have the same issue

Not sure if these are the correct IDs
https://tbc-twinhead.twinstar.cz/?spell=688
https://tbc-twinhead.twinstar.cz/?spell=697

I would really appreciate if you could take the time to fix this because in my opinion it makes the class unplayable. It's quite tedious to summon a pet for 10 seconds every time i dismount.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, resolved with next restart.
