### ISSUE TITLE
bm spiders not dropping netherweb spider silk

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4475]
i believe black morass spiders are supposed to drop netherweb spider silk.

==

https://www.wowhead.com/item=21881/netherweb-spider-silk

https://wowwiki.fandom.com/wiki/Netherweb_Spider_Silk

https://tbc-twinhead.twinstar.cz/?item=21881

**Comment by ghost** [comment]
The Netherweb Spider Silk was intentionally removed from the tarantulas.

_Originally posted by @Jerrythemagicdog in https://github.com/SunstriderEmu/BugTracker/issues/2225#issuecomment-597379611_
