### ISSUE TITLE
karazhan, pulling spiders on the stairs

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4476]
In karazhan heading up to moroes trash, we often manage to pull the spiders from the basement from the stairs.  Sometimes when summoning players on the stairs they drop through the floor into the basement.

**Comment by Jerrythemagicdog** [comment]
Summoning through stairs fix was deployed a few days ago, let us know if it still happens, thanks.

**Comment by Ironjudgment** [comment]
Happened yesterday. Also happens when summoning or reviving hunter pets.

**Comment by Jerrythemagicdog** [comment]
Summoning a player through stairs happened yesterday?
Reviving hunter pets fix live with next update.

**Comment by michaelkittrell** [comment]
pulling spiders from top of stairs still a thing as of 1/1/2021.  not sure who did it, but we did have a hunter in group.
