### ISSUE TITLE
[Vanilla] Scarab Brooch proc does not absorb damage

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-core#4477]
**Describe the bug**
The Scarab Brooch itemID=21625 spell effect does not absorb damage when applied to target.

**To Reproduce**
1. Equip Scarab Brooch as healing class
2. Use Scarab Brooch 
3.  Heal target/self and observe buff effect is applied.
4. Take damage in duel and it does not absorb anything.

Item: https://classic.wowhead.com/item=21625/scarab-brooch
Spell buff (works): https://classic.wowhead.com/spell=26467/persistent-shield
Spell (absorb, does not work): https://classic.wowhead.com/spell=26470/persistent-shield

**Expected behavior**
The amount of shield created via the trinket into spellID=26470 should be absorbed by the player in damage calculations

rev. 15918

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
