### ISSUE TITLE
Can't compleate the first aid quest

### ISSUE THREAD

**Issue by Twistedpower** [ValorenWoW/sunstrider-core#4478]
When you use the bandage on the hurt soldiers it doesn't count as the 15 needed to complete and so you fail no matter what. This means that hoard can't get first aid lvled.  Please fix.

https://i.imgur.com/UAv93Kt.jpeg

**Comment by Jerrythemagicdog** [comment]
There is no counter in the quest, if there was the quest would show 0/15 patients saved at the start.
If that was the case you'd also be able to do it across multiple attempts where the goal here is to save 15 patients during the event. 
Keep saving patients until the quest completes.
