### ISSUE TITLE
Ignore/Delete - Not a bug

### ISSUE THREAD

**Issue by Khalmknight** [ValorenWoW/sunstrider-core#4479]
***EDIT*** I am stupid, ignore or delete. this is not a bug but a fool that misclicks. If a GM could contact me to rectify my foolishness i would be eternally greatful.

I have just dropped the Band of Eternity Quest in Caverns of Time and it has given me a Defence Ring rather than the Healing Ring i should get.

**Character name**
Eklacious

**To Reproduce**
N/A

Item: https://tbc-twinhead.twinstar.cz/?item=29294
Quest: https://tbc-twinhead.twinstar.cz/?quest=10467

**Expected behavior**
I think i should have got this Ring - Correct me if im wrong please: https://tbc-twinhead.twinstar.cz/?item=29306

**Screenshots/videos**
![WoWScrnShot_111720_215209](https://user-images.githubusercontent.com/74598152/99382288-7004ff00-2920-11eb-8c38-121339ab01c4.jpg)

**Additional context**
I obviously got the Prereq. quest for the defence ring as well. did them back to back so didnt notice

**Comment by Jerrythemagicdog** [comment]
You can swap it out once you reach Exalted for a price.
