### ISSUE TITLE
Mobs respawning too fast making questing and farming nearly impossible for appropriate level players

### ISSUE THREAD

**Issue by Bladeadhunter13** [ValorenWoW/sunstrider-core#4480]
The monsters in the game is respawning faster then  I, or anyone I have talked to, can kill them and progress through a quest or zone. multiple times be in middle of a quest killing mobs and they respawn behind me trapping me in faster then i can recharge my health and mana to continue killing them. Even have been doing normal quests with group of 3 people in an area and the mobs respawned so fast they killed us multiple times half way through the mob lair. Another issue I and other have had problems with is escorting quests, where you are to just walk person through a mob filled area, and the mobs respawn faster then the escort can walk through the area and gets killed over and over basically blocking and locking that quest chain for me, I have even tried to do the escort quest almost 20 levels higher and still can't get it finish. It is making the game unenjoyable and questing or farming inconvenient if you are not maxed level. Due to fact that I have not gotten to Outlands I do not know if the respawn issue consists there as well. Monster/Mobs are spawning too fast for me and few others I have talked with to do quests enjoyably or at all

All of my characters

expect some breathing time from my first mob to my tenth or twelfth mob, so I can kill mobs, into lairs taking food/drink breaks and not be caught in group of 10 mobs by end of my 15 seconds of sitting

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the respawn time depends on the amount of people in the zone, the feedback is mixed on it, some players say it's fine as is, some say it's too fast, we're trying to strike a balance there.
