### ISSUE TITLE
Mh Npc's not spawning 

### ISSUE THREAD

**Issue by Wargrim** [ValorenWoW/sunstrider-core#4482]
We were with the guild in MH.
Last Thursday, was a good run but then the server crashed again and again, so we said okay lets come back sunday to clear this. We came back and had an empty Horde Camp. Only Thrall (maybe he played Last Man Standing) was there.

Wargrim

Normally Thralls should also spawn Taurens to help him once he comes to 20%, we let him tank some doomguards but he is not calling for help either or the taurens are just deaf and dont want to help their chieftain.

If you could recall the horde camp so we got normal Npc's there again it would be wonderful

Just whisper any guy from the guild <Easy Peasy in Time> they can show you the ID.

Thanks Wargrim

**Comment by Jerrythemagicdog** [comment]
Resolved in game.
