### ISSUE TITLE
Marks of Kil Jaeden quest bug

### ISSUE THREAD

**Issue by deathmagnetic2** [ValorenWoW/sunstrider-core#4483]
**Describe the bug**
 Hi, the quest Marks of Kil´Jaeden is not working properly my character has 20 marks and when trying to retrieve the quest, the Continue button is grayed out. The question mark is yelow.

**Character name**
 Draconnian

Item: https://www.wowhead.com/item=29425/mark-of-kiljaeden
Quest: https://www.wowhead.com/quest=10325/marks-of-kiljaeden

**Expected behavior**
 Just to complete quest.

**Screenshots/videos**
 https://ibb.co/YkTvqJx

**Additional context**

**Comment by Jerrythemagicdog** [comment]
You're past the reputation where you're able to hand Marks of Kil'jaeden in (Honored). 
https://endless.gg/armory/character/draconnian/reputation
