### ISSUE TITLE
Fishing Bauber Bug

### ISSUE THREAD

**Issue by crookqtftw** [ValorenWoW/sunstrider-core#4484]
**Describe the bug**
<When I fish and the bauber is supposed to be right clicked to loot the fish it doesn't "go away" or loot it, it just miss fires so to speak I know I am not alone with this issue and I think this is a fresh issue, probably from today. Its time wasting for me to click and nothing to happen not even saying the fish got away, when it really shouldn't. One other fisher man has also told me about the same exact problem. It's really annoying, fisihing basiclly for nothing.>

**Expected behavior**
<To say "fish got away" or to loot the bauber>

This happened on my character "Nightmarish" -troll it also happened to a friend "Melphalan"

**Comment by Jerrythemagicdog** [comment]
Can you provide a clip of what you're describing? I don't see anything irregular when it comes to how the bobber behaves.

**Comment by crookqtftw** [comment]
Okay so I dont know how to make a video, so It will take some time but its
really not to difficult to describe. So when I fish and the bauber shakes
and I right click on it. Two things should happen. 1. "fish got away" 2.
Loot.

Now a third thing happens, nothing. Nothing happens neither of the two
options happen. It seems as if the school has depleeted a little but I
havent looted anthing also the fish doesnt "get away". Its that simple.

I have been fishing on this server for 3 weeks now This started happening
yesterday and I am not the only person this is happening to Melphalan is
also having this issue.

I farmed 5 Primal Waters for 1hour instead of 10 as I usually do.

Thanks for the repply

**Comment by crookqtftw** [comment]
I made the video its my first ever ingame video. I appologize for me sounding like a wounded deer and for the buzzing noise in advance, its a bad ventilator from my laptop. i
Its also 512mb... I also apologize for that too, first video like I said.

https://we.tl/t-EpfyR4POWp

There's the link for the video

**Comment by Jerrythemagicdog** [comment]
Thanks for the video.
You get no loot and the loot window closes instantly because of your autoloot which is possible because of how chances are laid out for Pure Water.
We'll correct the chances though so that it always contains some loot as described here: https://wowwiki.fandom.com/wiki/Pure_Water
