### ISSUE TITLE
ssc, the big circle patrolling boglord

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4485]
ive seen this reported before, happened again last week.

occasionally, between the 1st and 2nd mob pack heading to leo (1st being at the T where the 2 bog lords meet up) 2nd being the one in front of the 2 witches 2 defenders pack... groups occasionally pull the patrolling bog lord some how.  

you get put into combat and he teleports in from an unknown location.  no idea how it manages to get pulled, this last week we were not in combat for several seconds drinking before suddenly we were in combat and he came teleporting in.

he teleports in to the area staging area where you pull the 2nd pack up to to kill (like 10 yards back from the top of the ramp yards on the edge closest to flk...

**Comment by michaelkittrell** [comment]
while you're addressing this, maybe he shouldn't respawn / be despawned if you kill leo and are doing FLK.  we killed leo, all the trash to flk, had 2-3 pulls on flk and then randomly... (like he was alive but not patrollign because we weren't in range) he came patrolling through on our 3rd or 4th pull. 

or maybe he should always patrol as long as there is any player in the instance.

**Comment by Jerrythemagicdog** [comment]
Someone pulls the bog lord on the other side of the instance and he teleports in because of zone combat, those were all of the previous cases.
The bog lord does patrol as long as someone is in the instance, that's how all of the patrols work in raids currently.

**Comment by michaelkittrell** [comment]
we had 0 dead.  even if we had dead we would've ressed them.  i do not think your statement is correct.

ive seen this multiple times in different raids/guilds.
