### ISSUE TITLE
Upper Blackrock Spire First boss not summonable

### ISSUE THREAD

**Issue by Titanorital** [ValorenWoW/sunstrider-core#4486]
Hello,

"Pyroguard Emberseer" (first boss of Upper Blackrock Spire) isn't reacting to player clicking on the altar. It's supposed to make all the mobs in the room attacking you, and when they're all dead the boss start attacking too. But boss and mobs doesn't react when we click on altar. I tried with 1-2-3 player channeling but nothing happens. I contacted a GM in game and he confirmed the bug and suggested me to report it here.

It's impossible to skip this boss since the door behind him only opens when we kill him.

Regards,

Titano

**Comment by kelno** [comment]
Thanks, fixed with next server update
