### ISSUE TITLE
Warrior Thunderclap and Demoralizing shout bug 

### ISSUE THREAD

**Issue by stitalahov** [ValorenWoW/sunstrider-core#4487]
**Describe the bug** 
I have the improved Thunderclap wich is 20% attack slow and Demoralizing shout wich is 420 ap reduction but when i use it on a enemy the icon says thunderclap is only 10% attack speed and shout 300 ap reduction i dont know if it is only the icon bug or my spells dont work i tried deleting cahe file from game but nothing changed

**Character name**
Stitalahov

**To Reproduce**
1. Cast Thunderclap on target affected by 10% attack speed slow instead of 20%
2. cast Demoralizing shout target affected by 300 ap reduction insted of 420
3. 
![tc](https://user-images.githubusercontent.com/74673900/99562582-941c1b00-29c8-11eb-820f-b54645b33a06.jpg)
![tcb](https://user-images.githubusercontent.com/74673900/99562587-95e5de80-29c8-11eb-947d-490e6d85e606.jpg)
![ds ](https://user-images.githubusercontent.com/74673900/99562599-98e0cf00-29c8-11eb-817e-8e852c906122.jpg)
![dsb](https://user-images.githubusercontent.com/74673900/99562605-9aaa9280-29c8-11eb-8c9a-0edcffff14de.jpg)

**Comment by Jerrythemagicdog** [comment]
The aura tooltips are not updated, same as every other improved tooltip in the game.
