### ISSUE TITLE
Cursed Talismans can't be finished

### ISSUE THREAD

**Issue by DennyCZE** [ValorenWoW/sunstrider-core#4489]
**Description**
Quest cannot be completed because necessary item is not dropping.

Item: https://www.wowhead.com/item=30157/cursed-talisman
Quest: https://www.wowhead.com/quest=10484/cursed-talismans

**Expected behavior**
Significant higher droprate (or atleast it should be dropping that item)

Best regards
Dennor

**Comment by Jerrythemagicdog** [comment]
![image](https://user-images.githubusercontent.com/46463908/99695583-a4de9680-2a85-11eb-8aec-1df28ee671b7.png)
The drop rate for all of the appropriate Orcs is 33%

**Comment by DennyCZE** [comment]
Thank you for investigation and your time.

I guess it was just luck/un-luck (about 15-20 mobs without drop).
