### ISSUE TITLE
Warlock Pet Disappears Sometimes when Demounting

### ISSUE THREAD

**Issue by diroccoa** [ValorenWoW/sunstrider-core#4490]
---
name: Bug report
about: Warlock pet despawns when warlock is dismounted occasionally
title: ''
labels: ''
assignees: ''

---

**Describe the bug**
Warlock pet depawns when daze or manual demount about 25% of the time. Daze is not required.

**Character name**
Gammy

**To Reproduce**
1.Summon Pet.
2.Run around and mount/demount pet will despawn about 2/10 times.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

Warlock Pet should not despawn

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/11067734/99691348-607fd600-2a46-11eb-9293-091e16a5a75c.png)
![image](https://user-images.githubusercontent.com/11067734/99691906-f287de80-2a46-11eb-930b-c8a2b7b84330.png)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, the screenshots are really helpful and helped us find the issue.
Fix live with next restart.

**Comment by kelno** [comment]
Fixed with https://github.com/kelno/sunstrider/commit/a98d7eff61170e1f626cbd526397341343bdbb2b
