### ISSUE TITLE
Quest starter item Gorgrom's Favor does not work

### ISSUE THREAD

**Issue by soltariyo** [ValorenWoW/sunstrider-core#4491]
**Describe the bug**
An item which drops from NPC Dorgok in Blade's Edge Mountains that starts a quest returns "You don't meet the requirements for that quest" when right clicked. On retail this quest is only available to Alliance, might have something to do with it not working here (my character is Alliance so it should work.)

**Character name**
Zinni

**To Reproduce**
1. Kill Dorgok in Blade's Edge Mountains on an Alliance character to receive quest starter item.
2. Right click on item.
3. Accept quest.
4. Receive error message saying you do not meet the requirements for that quest despite as Alliance you should be able to.

Item: https://wowhead.com?item=31363/gorgroms-favor
Quest: https://wowhead.com?quest=10797/favor-of-the-gronn

**Expected behavior**
As an Alliance character I expect the quest to be picked up normally when I accept it.

**Screenshots/videos**
https://a.uguu.se/k2fkklUPrG4b_2020-11-19_23-13-41.mp4

**Additional context**
N/A

**Comment by ghost** [comment]
Looks like [A Date with Dorgok](https://www.wowhead.com/quest=10795/a-date-with-dorgok) is a requirement. 
I don't see it completed on "Zinni".

**Comment by Jerrythemagicdog** [comment]
Indeed, that quest needs to be completed before to use the item.
However that seems incorrect and the requirement should rather be that the player is on the A Date with Dorgok (10795) quest or has it completed for the Gorgrom's Favor (31363) to drop in the first place.
Thanks for the issue, corrected with next update, for now you'll have to complete A Date With Dorgok (10795).

**Comment by soltariyo** [comment]
Ah, makes sense. Thanks a lot.
