### ISSUE TITLE
Another bugs i found.

### ISSUE THREAD

**Issue by PPGGPilot** [ValorenWoW/sunstrider-core#4493]
**Describe the bug**

1. Completing the "Underground Assault" quest does not increase your alliance reputations.
2. Lotherias does not offer a "Moonglow Vest" quest.

**To Reproduce**

1. After completing the "Underground Assault" quest a message appears "Reputation with Alliance increased by 605" but in fact no reputation increases.
2. Lotherias does not offer a "Moonglow Vest" quest to players who meet the requirements.

1. NPC: https://classic.wowhead.com/npc=6579/shoni-the-shilent QUEST: https://classic.wowhead.com/quest=2040/underground-assault QUEST (ANOTHER WEBSITE): https://tbc-twinhead.twinstar.cz/?quest=2040 ANOTHER WEBSITE: https://tbcdb.com/?quest=2040
2. NPC: https://www.wowhead.com/npc=6034/lotherias, QUEST: https://www.wowhead.com/quest=1582/moonglow-vest

**Expected behavior**

1. I checked few different websites for that quest because it was marked obsolete in wowhead.com. In vanilla (or classic) it increases your Gnomeregan Exiles and Stormwind reputations but in TBC completing the "Underground Assault" quest should increase your all alliance reputations.
2. Lotherias should offer a quest 'Moonglow Vest' to players who meet the requirements: minimal level of 8 and minimal leatherworking skill of 70.

**Screenshots/videos**

I have no screenshots/videos.

**Additional context**

N/A

**Comment by Sheikthecatman** [comment]
Thanks! Fixes will be live next server restart

[Underground Assault fix (99ff13bc052d1f1cb65becb8f77672a3b8b79d6b)](https://github.com/kelno/sunstrider-scripts/commit/99ff13bc052d1f1cb65becb8f77672a3b8b79d6b)

[Moonglow Vest quest requirements fix (8bbef0e52fa89fd82dd7c75485c3c763a564fde8)](https://github.com/kelno/sunstrider-scripts/commit/8bbef0e52fa89fd82dd7c75485c3c763a564fde8)
