### ISSUE TITLE
shattered hand mobs not giving exp

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4494]
in hfp there are a bunch of mobs up and down the road to hell fire citadel (the one that goes down between a ravine ending with the instance dungeons up above.  they give rep to friendly, but they do not give exp.  contrast this with the coilfang mobs in zangarmarsh that give similar rep to friendly and exp .  oversight or intentional?

**Comment by Jerrythemagicdog** [comment]
Looks like an oversight. 
Thanks for the issue, fixed with next restart.
