### ISSUE TITLE
loot issue with fishing pools

### ISSUE THREAD

**Issue by Ashnod666** [ValorenWoW/sunstrider-core#4495]
The first cast in every fishing pool i have fished in nagrand over the past 2 days has come up empty. I have fished numerous pools in that time and not once was the first cast loot of any kind.

**Character name**
Mihn, horde druid

**To Reproduce**
1. cast fishing line in any fishing pool
2. loot nothing
3. do not profit

pure water, mudfish and bluefish schools

**Expected behavior**
cast to produce loot or fish got away notice

**Comment by kelno** [comment]
Thanks, fixed with next server update
