### ISSUE TITLE
earth elemental totem, chain combat

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4496]
ran out of ramparts towards thrallmar.  got agro from the mobs on teh bridge, dropped earth ele totem, kept running for thrallmar.  

got spammed with messages + combat, -combat.   2-3x every 5s until i got the message "earth elemental totem destroyed" 60s or so later...  then the i stopped getting spammed.

**Comment by Jerrythemagicdog** [comment]
Sounds expected if the Earth Elemental keeps aggroing new enemies and puts you in combat.
