### ISSUE TITLE
No loot window when hooking the fish for the first time in new school in Terrokar forest

### ISSUE THREAD

**Issue by Vahapet** [ValorenWoW/sunstrider-core#4498]
I am fishing in Terrokar forest for darter quite usually. Today I've faced this issue for the first time.

Each time you are starting fishing in new school in Terrokar (Darter or Mixed, didin't checked Skettis ones), the first time you're successfully hooking the fish, you don't get loot window. All the next ones working normally. Tried to abandon fishing daily, relogging, switching off addons, restarting client. Haven't seen it yesterday.

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
https://github.com/SunstriderEmu/BugTracker/issues/4495
