### ISSUE TITLE
Random crashes in WaypointMovementGenerator

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-core#45]
Always here:
https://i.imgur.com/DLerRa3.png

**Comment by ryancheung** [comment]
`WaypointMovementGenerator::OnArrived` got called again after last call and set `_done` to `true`. There should be some problem in `movespline->updateState(t_diff, handler);`

**Comment by ryancheung** [comment]
I've compared the spline update code with trinitycore 3.3.5 and they are different. Trinity 3.3.5 call `WaypointMovementGenerator::OnArrived` in `WaypointMovementGenerator::DoUpdate`, but sunstrider-core are not.

**Comment by kelno** [comment]
Yes our WaypointMovementGenerator is not the TC one, we can't use TC as a reference for this one.

**Comment by kelno** [comment]
https://i.imgur.com/n9v5HLC.png
