### ISSUE TITLE
Grulloc Has Two Skulls is broken (Again)

### ISSUE THREAD

**Issue by EndlessLex** [ValorenWoW/sunstrider-core#4500]
**Describe the bug**
This bug was reported before back in July, (bug #3890) and it says it was fixed in a later update.
Attempting to complete the quest now (November 20th) it seems to be having the same issue. The Skull you are supposed to loot does not spawn, at least not anywhere that it can be seen or looted.

**Character name**
Lexington and Buncertain

**To Reproduce**
Just Kill Grulloc and have the quest to collect his Dragon Skull

https://www.wowhead.com/item=32379/grullocs-dragon-skull
https://www.wowhead.com/quest=10995/grulloc-has-two-skulls

**Expected behavior**
Once Grulloc is killed there should be visible large white dragon skull that is able to be clicked to be looted.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/74805293/99866844-1c8ded80-2b7a-11eb-923a-741ea84ab912.png)

**Additional context**
Please help, and thank you!

**Comment by Massie323** [comment]
You need to kill him on top of the bag, or basically exactly where he spawns. If you pull him too far away from it (as seen in the screenshot), he will not spawn the skull.

**Comment by Jerrythemagicdog** [comment]
It was requiring the person with the killing blow to be on the quest, which might not always be the case.
Restriction removed with next update.
