### ISSUE TITLE
No S2 Merciless Gladiator Maul 

### ISSUE THREAD

**Issue by DruDrui** [ValorenWoW/sunstrider-core#4501]
**Describe the bug**
Missing the Gladiator's Maul and the S2 version Merciless , too - after update for S4
Expect to trade Honor Point and Marks (like other S2 items) but this item(s) is/are missing

**Character name**
Druid Class - Alliance / Champions Hall SCity

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the item will be on the vendor after the seasons change tonight.
