### ISSUE TITLE
Missing s2 weapon at NPC.

### ISSUE THREAD

**Issue by Altfarm** [ValorenWoW/sunstrider-core#4502]
Missing s2 weapon at NPC Captain O'Neal (SW).
Merciless Gladiator's Maul (price : 27000 honor, 40 Alterac Valley marks) (item id:32014).
Edit : Also missing on Horde side at NPC Sergeant Thunderhorn (OG).

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the item will be on the vendor after the seasons change tonight.
