### ISSUE TITLE
Whipped frenzy or how can melee ppl can abuse 30% haste

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4503]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast [enslave demon](https://db.endless.gg/?spell=11726) to [Maiden of Pain](https://db.endless.gg/?npc=19408)...
2. Cast [Whipped Frenzy](https://db.endless.gg/?spell=34086) to party/raid members
3.  PROFIT 30% melee haste buff

**Expected behavior**

**Screenshots/videos**

![Screenshot_4](https://user-images.githubusercontent.com/31289782/99911409-47f11380-2d05-11eb-9125-a74662d43397.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
