### ISSUE TITLE
warlock summon bug

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4504]
noticed several times that a first summon on a person fails.  started up sometime in the last 2 months as far as i think.  2nd summons seem to be fine but sometimes that first summon on a person seems to have a high "fail rate".  this is not the rare bug where a person can't be summoned at all until they relog, it seems to only affects the first summon on that person.  in at least some cases, that first summon goes on a random person in teh group/raid.   could be an addon or something, but ive seen it too many times to say its misclicking or not real.

**Comment by Jerrythemagicdog** [comment]
Would love a clip of it happening.

**Comment by Altfarm** [comment]
Summon have an hidden cast time after you finish all the animation that takes like 3 secondes, at the end of thoses 3 secondes, the person you target is summoned, so, if you swap target after the summ animation, the summ swaps too. it happens on Classic too. Or any other tbc private.

**Comment by michaelkittrell** [comment]
we had so much trouble with summon at the beginning of this server that i have ptsd about doing anything after clicking summon.  at one point, the devs "fixed" the original summon bug by making sure that whatever person you were targetting when you started casting is the person who was summoned at the end.  No idea if this is still the case.  I am familar with the you summon whomever you are targetting a the end of summon like on warmane.  

I don't record myself unfortunately, it is possible there is no bug, but im pretty sure there is one somewhere.  it happens more often than i could chalk it up to a mistake.  i summon myself a lot multiboxin (which is how i know sometimes it goes to a random person in the group also have anecdotal evidence from comments in raid and random people porting to me after completing a summon and noticing that my target is still the person i intended to summon)...   i join 5-8 raids a week as warlock so i play it a lot.

**Comment by cbiprw** [comment]
i have never had a summon fail, not once.
if you are you using gearscore delete that :poo:

**Comment by michaelkittrell** [comment]
i do use the gearscore lite addon, it may or may not be trash.
if it is responsible for this bug, be far better for the server to fix it on their side then ask 10k players to stop using a popular addon (regardless of whether the addon is trash)

**Comment by z5n** [comment]
issue has since been fixed
