### ISSUE TITLE
Karazhan Reputation Ring

### ISSUE THREAD

**Issue by dan224** [ValorenWoW/sunstrider-core#4505]
Okay, whenever you get to exalted with the Violet Eye, you have the chance to drop your ring and select any of the others rings available for you, so whenever i delete my Violet Eye Band, the NPC should be billing you 75g for the ring of your choice, but instead is giving me 75G everytime i do it.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next restart.
