### ISSUE TITLE
Missing gear at Honor vendor.

### ISSUE THREAD

**Issue by Altfarm** [ValorenWoW/sunstrider-core#4506]
NPC PvP vendors only sell Boots/Wrist with arena rating req.
There's no more honor offset without req, except at QD for t6 tokens, or badges.
(Vindicator gear and lower).
For exemple: Vindicator's Dragonhide Boots id 33880, should be purchasable for 13,923, honor and 40 Eots mark, without rating.
Every "vindicator" gear should be purchasable for honor without arena rating req during s4 in capitals.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
