### ISSUE TITLE
Onyxia's Lair

### ISSUE THREAD

**Issue by dimiwilson** [ValorenWoW/sunstrider-core#4507]
**Describe the bug**
At Onyxia's Lair the mobs until to get to Onyxia they having a really high HP suck a 400 million as you can see in the following screen shot.
Plus the Onyxia summons some small dragons called ''Onyxian Whelp'' they having like 7 million HP each dragon he spawns.

**Character name**
Onyxian Lair Guard
Onyxian Warder
Onyxian Whelp

woulb apreciated to fix this issue plase.
Thanks in advance

**Screenshots/videos**
[https://ibb.co/TtDt2Bt](url)

**Comment by Godmatik** [comment]
Your screenshot doesn't work and I haven't been to Onyxia on this server, but see below for what the figures should be:

Onyxia Warder should have around 80k health, it's possible the current Onyxia Warder inside the raid is the WotLK version.
https://classic.wowhead.com/npc=12129/onyxian-warder

Onyxian whelp should have around 2.5k health. Again, the current version might be using Wrath numbers.
https://classic.wowhead.com/npc=11262/onyxian-whelp

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.

**Comment by dimiwilson** [comment]
Thanks for taking care.
Greetings
Dimi
