### ISSUE TITLE
[SPELL] Curse of Doom

### ISSUE THREAD

**Issue by cepheys** [ValorenWoW/sunstrider-core#4508]
**Describe the bug**
Curse of Doom can be casted on players pets.

**To Reproduce**
1. Cast CoD on players pet
2. ....
3. Pet ded

Spell: https://wowhead.com?spell=603

**Expected behavior**
CoD should not be possible to cast on players pets

<img src="https://i.imgur.com/9clbQiS.png" />

**Comment by Godmatik** [comment]
Confirmed should not be castable on player's pets either, wowhead comments confirm this.

https://classic.wowhead.com/spell=603/curse-of-doom#comments

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue and sources, fixed with next update.
