### ISSUE TITLE
Naaru Rations are not available for pet feeding

### ISSUE THREAD

**Issue by Noire86** [ValorenWoW/sunstrider-core#4509]
**Describe the bug**
Title says it all, naaru rations food is not feedable for Wind Serpent. 

**To Reproduce**
Try to feed Naaru Ration to a Wind Serpent

**Expected behavior**
Obviously, Naaru Ration is a bread-type food, so it must be appropriate for feeding pets.

**Comment by Noire86** [comment]
Proof from WH: https://www.wowhead.com/item=34780/naaru-ration#comments:id=351795

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
