### ISSUE TITLE
Suggestion: Enchant Weapon - Deathfrost during Winter's Veil event

### ISSUE THREAD

**Issue by Massie323** [ValorenWoW/sunstrider-core#4510]
Since the Midsummer event was skipped and by the looks of it, no plans were made to provide alternative means to get the event-bound items, specifically the enchant recipe, is there any chance to have the enchant be added in some accessible form such as a Vendor, or added to the Loottable of a mob?

Considering the Feast of Winter Veil event is around the corner, it would be thematically appropriate to link the recipe to that event instead, either in form of being in the present's loottable or in form of a drop from the Greench boss or inside the quest reward related to the Greench. Of course that's assuming Winter Veil doesn't get the same treatment as Midsummer, with devtime being focused on SWP.

For how unique and situationally powerful the enchant is, it's a real shame that there's was practically no chance to acquire it since Midsummer was effectively skipped.

Recipe ID: https://www.wowhead.com/item=35498/formula-enchant-weapon-deathfrost
Greench ID: https://classic.wowhead.com/npc=13602/the-abominable-greench
Greench Quest ID: https://classic.wowhead.com/quest=6984/a-smokywood-pastures-thank-you
Greench Quest reward: https://classic.wowhead.com/item=17726/smokywood-pastures-special-gift

**Comment by Jerrythemagicdog** [comment]
Thanks for the suggestion, but we're not looking to make the enchant available.
