### ISSUE TITLE
Starving Hellboars

### ISSUE THREAD

**Issue by frumslol** [ValorenWoW/sunstrider-core#4511]
The aggro range on Starving Hellboars in Hellfire Peninusla is very long. I can't cast a spell from 36 yards without getting charged as a level 59 Warlock. Compared to a Bonechewer Scavenger (lvl 58) where i can stand at around 20 yards without pulling aggro. I think the aggro range of a Starving Hellboar can accurately be compared to the aggro range of Fel Reaver

**Comment by Godmatik** [comment]
Blizzlike, during TBC the helboars had very long aggro range, the wowhead comments from the 2.0 patches confirm this.

https://www.wowhead.com/npc=16879/starving-helboar

**Comment by Jerrythemagicdog** [comment]
There are some players saying that every creature with their name starting with "Starving" should have a bigger aggro range, maybe worth looking into some time.
