### ISSUE TITLE
battleground ghost teleport

### ISSUE THREAD

**Issue by cbiprw** [ValorenWoW/sunstrider-core#4512]
sometimes (if you only pvp it happens **MANY TIMES per day**) when you die and they attack the gy that you are supposed to spawn on, your ghost won't get teleported to the next available graveyard, i don't know how to reproduce this, it seems totally random, all battlegrounds except wsg are affected, but for some reason, i think, especially AV, yes that one where the fascist generals will afk report you for simply not playing the kind of objective **they think** is right, like imagine having to ghost walk to your corpse (if you are lucky) **two times in a row**, that's basically 2 minutes of a player doing nothing, try explaining that to the fascist generals, why your party frame was "dead" for 4 minutes in a 10 minute game

**Comment by beauxq** [comment]
I think it happens most (and is very reproducible) with Frostwolf and Stormpike Graveyards.

**Comment by beauxq** [comment]
In AV and AB and EOTS:
This is the algorithm that should be done every time my spirit is released
and every time the graveyard that I'm dead at is assaulted by the other faction.


    Make a list of the contestable graveyards currently controlled by my faction.
    (This list could be already made before this event.)
    
    if the size of that list is zero:
        teleport me to the starting area graveyard
    else:
        teleport me to whichever graveyard on that list is closest to me


Note that the starting area graveyard is not on the list. No one should ever be teleported to the starting area graveyard while their faction has any contestable graveyard.

(The same algorithm can be used in WSG too, because the number of contestable graveyards is always zero.)

**Comment by Jerrythemagicdog** [comment]
Reproduce steps:
![image](https://user-images.githubusercontent.com/46463908/100146370-b662dc80-2e91-11eb-824d-22d4c1eb2c2e.png)

1. Die as Alliance next to this graveyard when it's controlled by Alliance
2. Release Spirit, the character will correctly be moved to the graveyard
3. While waiting in the resurrection queue, have a Horde character capture the outpost
4. The Alliance character won't get ported to its other controlled graveyard.

**Comment by kelno** [comment]
Thank you.
Fixed for Alterac Valley with next server update
