### ISSUE TITLE
Wand damage considered physical damage

### ISSUE THREAD

**Issue by cohonez** [ValorenWoW/sunstrider-core#4513]
Wanddamage is considered physical damage, where it should be considered magical damage. Debuffs that reduce physical damage dealt decrease your characters wand damage when it shouldn't.

Charactername: Cohonez

To reproduce:

The "Green Sludges" in Skulk Rock, Hinterlands apply a stacking debuff that decrease physical damage dealt by 5%. Stack it by getting hit and watch your wand damage dwindle. At 10 stacks, 100% of physical damage dealt is reduced and your wand shots dont hit anymore. At this point they dont show up in the combat log anymore.

Green Sludge: https://www.wowhead.com/npc=2655/green-sludge
Corrosive Acid ability: https://www.wowhead.com/spell=9459/corrosive-ooze

I expect my wand-damage not to be affected by physical damage debuffs. Wandshots resist, they dont miss. They are considered magic damage.

This has further minor implications in PvP scenarios, where talents and effects that reduce physical damage taken reduce wanddamage when it shouldnt.
![Wand_damage_physical](https://user-images.githubusercontent.com/74948882/100053365-2cc6f680-2e20-11eb-9dda-a29ed1e12673.jpg)

**Comment by kelno** [comment]
Thanks, fixed with next server update

https://github.com/kelno/sunstrider/commit/85f4d293acffda14a4e07773e7869f44461d6ee6
