### ISSUE TITLE
Hunter Pet Ravager yellow colour changes after dismissing/calling

### ISSUE THREAD

**Issue by mneu3** [ValorenWoW/sunstrider-core#4516]
Hunter Pet Ravager yellow colour changes after dismissing/calling

After taming a yellow Ravager from blades edge and mounting up or dismissing the pet and calling it back after mounting off or sth like that, the colour randomly changes to a red or purple one and stays like that forever.
I tamed a yellow one about 3-4 times and everytime after dismissing and recalling it back, the colour changes... 
I just cant get a yellow one for longer than some minutes :-D even after feeding it and bringing it to a happy status.
Can anybody help me with this bug or made the same experience? 

Best regards,

Dahbu

**Comment by Jerrythemagicdog** [comment]
The creature has 4 different model ids which are randomized on each summon.
