### ISSUE TITLE
I cant give you my money

### ISSUE THREAD

**Issue by devilsagb** [ValorenWoW/sunstrider-core#4517]
**Describe the bug**
The payment system is cumbersome, i tryed with 4 different credit cards and i cant donate.
Please add paypal or something else.

**To Reproduce**

it explains by itself..    im from Chile, and the cards are 2 visa and 2 mastercard cards.

**Expected behavior**

To accept my money.

**Additional context**
I rlly like the server, but the payment system is making me crazy.

**Comment by Jerrythemagicdog** [comment]
Thanks, we're looking into using other payment processing services.
