### ISSUE TITLE
Upper Blackrock Spire: Pyroguard Emberseer

### ISSUE THREAD

**Issue by Epic-Gamer123** [ValorenWoW/sunstrider-core#4518]
Location: Blackrock Spire (Dungeon)
NPC: Pyroguard Emberseer  ( https://www.wowhead.com/npc=9816/pyroguard-emberseer )

With the latest update to 2.4 for some reason attempting to start the fight by using the Blackrock Alter within the room, nothing happens. Your character will just stand there and channel for the full 10 minute duration and the fight will not start. Originally on the server only 1 person needed to click the alter, in vanilla only 3 people need to use the alter. I have attempted to use the altered with up to 5 people and still the fight won't start. 

As this fight does not work, there is currently no way to enter the remaining parts of the dungeon due to the locked door that only opens after the boss is defeated. (Unless you have BWL attune from before the bug started).

**To Reproduce**
1. Click the Blackrock Alter on any number of characters.
2. Wait.

**Expected behavior**
1. After clicking the alter and channeling for a short time, the Blackhand Incarcerators within the room will become hostile and attack you.
2. Pyroguard Emberseer will 'power up' and after a short time will become hostile and attack the player
3. Upon death of Pyroguard, the door to the remainder of the dungeon will open.

**Comment by kelno** [comment]
Thank you for the detailed report. It should have been fixed some days ago already.
You can answer here again if it's now and I'll look at it again.
