### ISSUE TITLE
Mage Molten armor + combustion

### ISSUE THREAD

**Issue by aknin2tm** [ValorenWoW/sunstrider-core#4519]
Combustion proccs beeing eaten up by Molten armors return dmg proc (Got Molten Shields talent)

**Comment by Jerrythemagicdog** [comment]
Sounds expected, if you find proof that it shouldn't add it here and we'll look into it.

**Comment by aknin2tm** [comment]
"When activated, this spell causes each of your Fire damage spell hits to increase your critical strike chance with Fire spells by 10%. This effect lasts until you have caused 3 critical strikes with Fire spells."

dont get how that would be expected? Should i expect molten armor direct dmg procs to counter shaman grounding totems aswell or is the proc classified as an "aoe spell". As it is now any autoattack from melee or pets will render combustion completely useless as a talent. I didnt really go check and just assumed that this was not working as intended - i suppose a play around would be armor swap during combustion. Although i dont recall this being an issue when playing fire mage in tbc before.

"Redesigned. When activated, this spell causes each Fire damage spell you cast to increase your critical strike chance with Fire damage spells by 10%. This effect lasts until you have caused 3 critical strikes with Fire spells. 3 minute cooldown. Previously, it increased the critical strike chance of the next fire spell by 100%, only guaranteeing one critical strike. The cooldown was 5 minutes." Found this on wow.gamepedia for combustion - Vanilla patchnotes. "Fire damage spell you cast" although the wording is from a different version of the game i still dont think molten armor procs are intended to mix with combustion(crit chance and charges)
