### ISSUE TITLE
[Profession] [Blacksmithing] [Master Axesmith]

### ISSUE THREAD

**Issue by Trev87** [ValorenWoW/sunstrider-core#4520]
I have proffesion blacksmithing (360 skill) and I learned specialization weaponsmith (after completing 'The Way of the Weaponsmith' quest). In the Everlook I learned another specialization - Swordsmith. Unfortunatelly, I changed my mind and go back there to unlearn the Swordsmith specialization, but after NPC told me, I will pay 100G, nothing happend. I try it at the NPC who learned my this specialization, but nothing happend. NPC says that I must find someone in Everlook (I tryed another NPC´s with specializations then - nothing).

**Character name**
Trevio

**Expected behavior**
To fix this I want pay 100G and unlearn this specialization and then I want to lea new one.
[https://github.com/SunstriderEmu/BugTracker/issues/3207#issuecomment-623774621](url)

Thank you for your help.

**Comment by Trev87** [comment]
[https://github.com/SunstriderEmu/BugTracker/issues/3207#issuecomment-623774621](url)

**Comment by Jerrythemagicdog** [comment]
Luckily you haven't been charged or paid any gold.
Thanks for the issue, fixed with next update.
