### ISSUE TITLE
Hunter Pet issues

### ISSUE THREAD

**Issue by cha99** [ValorenWoW/sunstrider-core#4521]
Hello, 
the bug is that sometimes my pet doesn't obey my commands even though I order It to specially when I try to use kill command like my pet stand next to the target I order it to do that technique but he won't like it's not in range. This started exactly when the patch came out and I've done the second boss of SSC (The Lurker below)  like was standing on one of the three little platforms and my pet was next to me when the boss in the middle platform shows up I clicked on used the macro that supposed to make my pet attack I see it use it's speed boost but still standing next to me instead of going to the middle platform. So after few tries I changed My position hoping that my pet will attack this time and it worked but sometimes as I said I tried to use kill command but it doesn't work even though my pet is right next to boss.  
(Note) My pet is always on passive mode he only respond with my macros and they work perfectly. 
My character's name is Deenz (Sunstrider) 

Expected Behavior : 
1-Mouse wheel up/Shift Mouse wheel up pet attacks target 
2-I click R/A/4/3 to Use Kill command macros
What Happened : 
I use the key binds above yet sometimes I face no response from pet  
This is the Boss that started the bug : 
https://fr.wowhead.com/npc=21217/le-r%C3%B4deur-den-bas
These are the Spells : 
https://shadowlands.wowhead.com/spell=34026/kill-command

I hope the bug get fixed. 
Thank you in advance :D

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4525

**Comment by kelno** [comment]
Thanks, fixed with next update

**Comment by cha99** [comment]
Thanks a lot for your help :D
