### ISSUE TITLE
ssc, bog lord random combat

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4524]
we wiped at morrowgrim 2-3x, were ressing up... we suddenly enter combat and 5-8s later a bog lord suddenly appears out of nowhere.   no one was running in (we killed the ttp one... and 30m later we later killed the first boglord near hydross so it definitely wasn't that one).  lurker, leo and flk were a 1 shot and trash was pretty quick.  We killed the patrolling bog lord in first part of leo's room.    

doesn't seem right.   i assume we were at 2 hours after killing it in leo's room and that its linked with morrogrim, but seems unnecessarily inconvenient.  why not do something custom and link it to morrowgrim and leo so it doesn't respawn if you kill either of them.  

its not a big deal, but its also not a big deal to have it not respawning and attacking/wiping a raid because they don't know that this particular mob often killed in leo's room is linked to some random other boss in ssc.

**Comment by Jerrythemagicdog** [comment]
Not the vanishing Bog Lord again please, we're looking to go away from zone combat anyway.

**Comment by michaelkittrell** [comment]
fair enough!
