### ISSUE TITLE
Figurine panther Bugged (Epic one)

### ISSUE THREAD

**Issue by Wuehgros** [ValorenWoW/sunstrider-core#4527]
**Describe the bug**

 follow and attack ennemy and broke my blind !
**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://fr.wowhead.com/item=35702/figurine-de-panth%C3%A8re-de-chantelombre
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

https://clips.twitch.tv/FaintElatedCheddarCeilingCat
**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
