### ISSUE TITLE
Deviate Fish (raw) has no effects

### ISSUE THREAD

**Issue by Massie323** [ValorenWoW/sunstrider-core#4529]
**Describe the bug**
Normally when you eat an uncooked Deviate Fish you one of few effects such as a sleep or size shrink.
However currently the fish does absolutely nothing when consumed.

**Character name**
Ratsmacker

**To Reproduce**

1. Eat Deviate Fish

Item: https://classic.wowhead.com/item=6522/deviate-fish

Spell: 
https://classic.wowhead.com/spell=8064/sleepy
https://classic.wowhead.com/spell=8065/invigorate
https://classic.wowhead.com/spell=8066/shrink
https://classic.wowhead.com/spell=8067/party-time
https://classic.wowhead.com/spell=8068/healthy-spirit
https://classic.wowhead.com/spell=8070/rejuvenation

**Expected behavior**

Upon consuming a Deviate Fish, it should give you one of the listed effects for a short duration.

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart, thanks.
