### ISSUE TITLE
Maraudon staff portal is always open but not functioning

### ISSUE THREAD

**Issue by Massie323** [ValorenWoW/sunstrider-core#4530]
**Describe the bug**

Inside the portal room of Maraudon, you're supposed to summon a portal that leads to the waterfall area of the instance. 
Right now the portal is permanently active and clickable, however nothing happens on interaction. I have yet to test the interaction on using a staff on top of the existing portal.

**To Reproduce**

1. Go through the outer entrance of Maraudon.
2. Go to the portal room (behind Kolk - The First Khan)
3. Click on the portal

Item: https://classic.wowhead.com/item=17191/scepter-of-celebras
Quest: https://classic.wowhead.com/quest=7046/the-scepter-of-celebras
Object: https://vanillawowdb.com/?object=178404
Spell: https://classic.wowhead.com/spell=21127/maraudon-portal

**Expected behavior**

I'm not 100% sure if the portal being up permanently is a TBC feature or just a jank script bug.
The bug is either the portal being up permanently and/or the portal not being clickable.
Normally the room is supposed to be empty and a portal is created by using the staff in the middle.

**Comment by Massie323** [comment]
Edit; Summoning an own version of the portal with the staff works fine and can be properly interacted with (assuming it isn't overlapping 1:1 with the broken portal)

**Comment by Jerrythemagicdog** [comment]
It's an addition in WotLK but I don't see a reason not to keep it for players' convenience.
https://wowwiki.fandom.com/wiki/Patch_3.0.8_(undocumented_changes)#Dungeons_and_Raids
