### ISSUE TITLE
Auchenai Crypts - Sirrak Boss Mechanics

### ISSUE THREAD

**Issue by Healluminati** [ValorenWoW/sunstrider-core#4531]
**Describe the bug**

**Character name**

**To Reproduce**

1. Pull boss
2. Have casters stand at bottom of stairs to LoS casting debuff
2. B. Have casters try to LoS in a cubby hole to remove casting debuff.
3. Casting debuff refreshes and does not drop off.
4. Wipe

**Expected behavior**

**Comment by Jerrythemagicdog** [comment]
You can't LoS it.
