### ISSUE TITLE
tk, kt fight weaps spawning below platform unlootable

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4532]
kt, p3 weapons, we killed weaps on top of platform with KT... where they spawned.  

at least two weaps, one of which was dagger, spawned below the platform and were unlootable... or at least no one ever found the magic spot to click where you could loot it.  i tried zooming in, still couldnt loot it.

**Comment by Jerrythemagicdog** [comment]
Change your camera angle it's not about zooming in.
