### ISSUE TITLE
Misdirect and Distracting shot on Gurtogg

### ISSUE THREAD

**Issue by lrdelange** [ValorenWoW/sunstrider-core#4533]
**Describe the bug**
On the pull of Gurtogg our Hunter used MD on the Main tank, Aimed shot, Arcane shot, Distracting Shot...At the first milisecond of the pull the hunter had threat (because he started combat), after the damage from Aimed and Arcane shot the Main Tank had threat... but when the damage from the Distracting shot came in... he changed targets to a "random" raid member...

**Character name**
Raiders involved: Ficci (Hunter that pulled), Bigqwick (Main Tank), Hunterboy (the poor bastard that got clapped)

**To Reproduce**
(We did not reproduce as we wanted to clear BT)
1. Pull Gurtogg with MD on MT, open with Aimed Shot, Arcane Shot, Distracting Shot... have some one be eating during pull with health restoring.

Creature: https://www.wowhead.com/npc=22948/gurtogg-bloodboil

**Expected behavior**
I checked the internet and saw that in WoTLK MD with Distracting shot was changed:
"This is a taunt, and can be very dangerous if used with [Misdirection]. It forces the target to attack the hunter, causing the mob to ignore its threat list rather than generating high threat. The taunt cannot be Misdirected."

However on the TBC patch it says:
"World of Warcraft: The Burning Crusade Patch 2.0.6 (23-Jan-2007): Misdirection will now redirect the threat from Distracting Shot."

**Screenshots/videos**
Screen of the pull:
![image](https://user-images.githubusercontent.com/43291625/100498805-0e853180-3165-11eb-8028-e751d826456c.png)

Screen of the Combatlog:
![image](https://user-images.githubusercontent.com/43291625/100498815-1c3ab700-3165-11eb-9474-509ee514fbba.png)

**Comment by kelno** [comment]
Well that's a funny one... the bug is actually the following:
You get threat from getting power (mana, rage, energy)... and Pet Happiness is also a power, so a hunter feeding its pet generates threat. And happiness works with a big scale, meaning that a hunter can get a huge 10k threat from a tick of it.
Fixed with next update!

**Comment by kelno** [comment]
Thanks. I tested distracting shot and misdirect interaction and everything seems to work as intented. On TBC it's just plain threat given and nothing related to taunt.
I would guess Hunterboy here did something that made him generate a lot of threat, I'm still trying to figure out what.
Looking at your sheet, line 12 we see a SPELL_ENERGIZE event that looks like a possible culprit, I'm still looking into this.

**Comment by kelno** [comment]
I made a fix that could have fixed it, it prevents getting threat from eating or regenerating pet happiness. Will re open if that still happens.
