### ISSUE TITLE
Guild Logs cant be seen

### ISSUE THREAD

**Issue by gozkok** [ValorenWoW/sunstrider-core#4534]
Hello, 

This is Umbaku. We are in "Baby Guild" as Horde and we are having a big issue of not seeing Guild Logs. We have been in touch with GMs and they have told us to open a Bug report. Could you please fix that we have big numbers of active players and we cant see anything.

**Comment by michaelkittrell** [comment]
would be interesting to maybe make the guild logs avaialble on the website for guild members to see... since the in game UI is pretty limited/shit especially if you have guild repair on.

**Comment by Ironjudgment** [comment]
A quick local fix is to use this macro:

/run GuildEventLog_Update()

**Comment by z5n** [comment]
duplicate of #2405
