### ISSUE TITLE
Healthy Dragon Scale

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4535]
The item/quest Healthy Dragon Scale is a soulbound item that begins a quest (drops off Plagued Hatchlings in scholomance may drop elsewhere i dunno)  

You can pick up like dozens of them.  Should probably be treated like other quest items where if you have one, it doesn't drop/on corpse for you.

**Comment by michaelkittrell** [comment]
ok so apparently this is a repeatable quest... for argent dawn faction.  im exalted (999/1000), but these are still dropping 1 per kill which is super annoying with 25 of these whelps in the room.  They don't stack, aren't sellable so i have to delete them...

also according to some of the comments, you have to do a pre-quest to be able to see/loot these.  pretty sure i never did the pre-quest.

https://classicdb.ch/?quest=5529

mentions in teh comments
By Firan on 12/05/2006 (Patch 2.0.1)
You can only loot the scales after you have completed https://classicdb.ch/?quest=5529, and is begun by the scale which drops off of plagued hatchlings.
Report|Reply
Rating: +10 [-] [+]By Anonymous on 07/20/2006 (Patch 1.11.2)
You have to finish Plauged Hatchlings, first, or you can't see the healthy scales.


https://www.wowhead.com/quest=5582/healthy-dragon-scale

You can only loot the scales after you have completed http://www.wowhead.com/?quest=5529, and is begun by the scale which drops off of plagued hatchlings.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
