### ISSUE TITLE
After S3 set with Honor update Veteran's PvP Items are no longer available?

### ISSUE THREAD

**Issue by foxkrm** [ValorenWoW/sunstrider-core#4536]
**Describe the issue**
After the Merciless weapons and Vengeful armor set arrived with honor buy i can't see any Veteran's PvP Items for buy. Are these will be available any longer? 

**To Reproduce**

1. As db.endless.gg sais; [Veteran's Band of Triumph](https://db.endless.gg/?item=33057) sold via Honor and marks by [Lieutenant Tristia](https://db.endless.gg/?npc=26395).
2. There are NOT there. None of Veteran's item.
3. Sells only Vindicator's and Guardian's

**Expected behavior**
>re-index Veteran's Items

**Comment by Jerrythemagicdog** [comment]
Those aren't available and won't be.
