### ISSUE TITLE
tk, kt fight weaps spawning below platform unlootable 

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4537]
https://github.com/SunstriderEmu/BugTracker/issues/4532

repost,  i definitely did change camera angles in addition to zooming... 

we had 10-15s to try and loot and no one could 2 of the corpses which looked like they were spawned underneath the platform with small parts of them portruding through the floor.

**Comment by Jerrythemagicdog** [comment]
That's just how the weapons and their models are, not something we can affect.
