### ISSUE TITLE
Timbal and SWD self DMG

### ISSUE THREAD

**Issue by Manabatterie** [ValorenWoW/sunstrider-core#4538]
**Describe the bug**
If using Timbal Trinket from MGT as a SP and the trinket procs on the self dmg effect from SWD you also get dmged. 

**Character name**
Manabatterie // NFW

**To Reproduce**

1. Equip Timbal Trinket
2. Use Shadow Word Death on any target 
3. Wait for trinket to proc on the self dmg effect

**Expected behavior**
Not to self dmg. It should just proc on DMG to the target 

**Screenshots/videos**
https://imgur.com/08dnM2W

Thank you, if its not a bug just give a quick feedback.

**Comment by Jerrythemagicdog** [comment]
I wasn't able to find a source whether it's intended or not, looks like an oversight and a particular interaction with Shadow Word: Death and the way the backlash damage works.
Fixed with next update.
