### ISSUE TITLE
Quest : Membership Benefits bugged

### ISSUE THREAD

**Issue by Cocio21** [ValorenWoW/sunstrider-core#4539]
**Describe the bug**

Membership Benefits quest is not showing, im exalted.

**Character name**
Shortstabber 

**To Reproduce**
N/A as the quest is not showing up at all

Quest: https://www.wowhead.com/quest=9887/membership-benefits

**Expected behavior**
 Expected gems, got nothing xD

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/63900239/100557148-6b890080-32a7-11eb-86a9-a63550b00ece.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
Keep in mind the quest is only repeatable once a month so perhaps you'll have to wait until the beginning of the next month to pick it up again.

**Comment by Cocio21** [comment]
When is next update if you know this ? :)

Also im aware its a single monthly quest, but i havnt done it since about august when i got exalted with them.

**Comment by Cocio21** [comment]
Nvm, can confirm its fixed with update today :)
