### ISSUE TITLE
Mind Control "Target is too low level"

### ISSUE THREAD

**Issue by Massie323** [ValorenWoW/sunstrider-core#4540]
**Describe the bug**

At Level 66, trying to Mind Control a low level target (~lvl 40) with rank 3 or rank 2 Mind Control will result in the error message "Target is too low level". I am not aware of any restrictions existing back in the day, as videos float around of people memeing [booty bay boats since 2007.](https://youtu.be/N_K4uIeFAc4?t=89)
I have yet to find the exact threshold, as each rank of MC has a different "minimum".

**Character name**

Visionpull lvl 66

**To Reproduce**

1. Find a mob that is below ~lvl 40
2. Attempt to cast max rank Mind Control
3. "Target is too low level"

Spell: 
https://db.endless.gg/?spell=605 rank 1
https://db.endless.gg/?spell=10911 rank 2
https://db.endless.gg/?spell=10912 rank 3

**Expected behavior**

Mind Control has an upper level maximum, but not a minimum.

**Additional context**

My guess is, considering that the upper level limit scales with the character's level (+2;+3;+4; for each respective rank), some code is causing the entire boundary to scale including the minimum level. I have yet to test the exact thresholds for each rank, but results for lvl 70 should be different to lvl 66.

**Comment by kelno** [comment]
Thanks, fixed with next server update
