### ISSUE TITLE
Gnomish Net-O-Matic Projector causes self-entrapment on log in

### ISSUE THREAD

**Issue by SGTgopher** [ValorenWoW/sunstrider-core#4542]
When My character is equipped with the Gnomish Net-O-Matic Projector engineering trinket, My character becomes trapped in a net for a short time after logging in

Character: Maulmaster

To reproduce: equip Gnomish Net-o-Matic Projector, log in.

affected items: Gnomish Net-O-Matic Projector

My character should be free to move when I log in regardless of the item being equipped

![World Of Warcraft Screenshot 2020 11 30 - 08 16 22 80](https://user-images.githubusercontent.com/75260181/100620854-875ec780-32e4-11eb-9e13-151ac24297ef.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update. It might root you one last time after that.
