### ISSUE TITLE
magisters terrace quest, tyrith

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4543]
the corpse you talk to in mgt n for the quest magisters terrace does not show a yellow a yellow question mark.  would be nice if it did.

**Comment by michaelkittrell** [comment]
maybe the scyryers orb for the 2nd part of the quest too.

**Comment by kelno** [comment]
Thanks for reporting.

**Comment by kelno** [comment]
Fixed with next server update
