### ISSUE TITLE
random warlock pet in battlegrounds after res

### ISSUE THREAD

**Issue by cbiprw** [ValorenWoW/sunstrider-core#4545]
after you die you spawn with a random pet, tested in AB, EOTS, i really don't want to cast for 6 seconds and spend 1200 mana (that is if you are specced) after each death to "test" the other two battlegrounds :P

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks
https://github.com/kelno/sunstrider/commit/273e291b73cd5d02dcd730ef77732274874d049b
