### ISSUE TITLE
Teleport to Moonglade bug

### ISSUE THREAD

**Issue by Lamooerte** [ValorenWoW/sunstrider-core#4547]
**Describe the bug**

**I didnt get the Spell Teleport to Moonglade(with my druid)**

**Character name**
**Lamooerte**

**To Reproduce**

1. I did get the Quest for Bearform.
2. But i never got the Teleport to Moonglade spell

https://www.wowhead.com/spell=18960/teleport-moonglade

**Comment by Ironjudgment** [comment]
Greetings, your character 'Lamooerte' hasn't completed any 'Heeding the Call' quests, meaning you haven't started the quests. Please have a look here and follow the guide: https://classic.wowhead.com/guides/druid-class-quests-classic-wow
