### ISSUE TITLE
Who broke my Murloc Costume?

### ISSUE THREAD

**Issue by BasedForfrost** [ValorenWoW/sunstrider-core#4549]
I still look like a shaman and not a stitched up Murloc with the Murloc Costume
Shaman

**To Reproduce**
1. Use Murloc Costume
2. Look normal
3. Cry

![image](https://user-images.githubusercontent.com/62028592/100907139-f4ff2500-3497-11eb-9e1a-417dc86fee67.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
