### ISSUE TITLE
Warlock gets a random demon when resurrected at GY during battlegrounds.

### ISSUE THREAD

**Issue by alextarapatin** [ValorenWoW/sunstrider-core#4550]
**Describe the bug**
Warlock gets a random demon when resurrected at GY during battlegrounds.

**Character name**
Lockhotdot

**To Reproduce**
1. Get a warlock with all demons learned.
2. Go to any BG with any summoned demon.
3. Die and get resurrected at GY.
4. You will receive each time a different demon(including Fel Guard, even if you dont have talents for it).

**Comment by Woran123** [comment]
I've experienced exactly the same bug today. I've played EOTS and AB. In both BG's I got random summoned demons upon resurrecting.

**Comment by cepheys** [comment]
I have experienced the same bug too.

**Comment by Jerrythemagicdog** [comment]
Fixed with next restart.
