### ISSUE TITLE
Pets/demons cant jump over the Iceblood graveyard hill

### ISSUE THREAD

**Issue by alextarapatin** [ValorenWoW/sunstrider-core#4551]
**Describe the bug**
Warlock and hunters pets/demons cant jump over the Iceblood graveyard hill on Alterac Valley BG

**To Reproduce**
1. Get a hunter/warlock with any active pet/demon
2. Go to Iceblood graveyard.
3. Jump over the hill from the screenshot.

**Expected behavior**
Pet/demon should jump down too, instead he goes around the hill.

**Screenshots/videos**
<a href="https://ibb.co/fXYhCTv"><img src="https://i.ibb.co/kGgRhP1/Wo-WScrn-Shot-112120-164811.jpg" alt="Wo-WScrn-Shot-112120-164811" border="0"></a>

**Comment by z5n** [comment]
issue has since been fixed, thanks!
