### ISSUE TITLE
Leg Armors & Scope Enchants

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#4552]
**Describe the bug**
Leg armors and scopes are not able to be enchanted via trade window on a lower level item.

The below listed items do not allow for enchantment via trade window:
>Nethercleft leg armor
>nethercobra leg armor
>runic spellthread
>golden spellthread 
>khorium scope
>Stabilized Eternium Scope

**Character name**
N/A

**To Reproduce**
N/A

https://www.wowhead.com/item=29536/nethercleft-leg-armor#comments

**Expected behavior**
The above mentioned leg armors and scopes should be able to be traded onto another players low level item via trade window.
This is normal for TBC 2.4.3 as i have played many TBC private servers and it has always been possible. This is also evident by the above wowhead link comments.

**Screenshots/videos**
N/A

**Additional context**
N/A

**Comment by mickwow** [comment]
Hello, i would like to add something i forgot and left out. I am speaking in reference to BOP (bind on pickup) items specifically. It does not let you trade enchant the leg armor onto BOP lower level items. However it does let you trade enchant onto BOE (bind on equip) lower level items. This should be changed so that BOP items can be enchanted.

**Comment by Jerrythemagicdog** [comment]
This is completely expected behaviour.
https://www.wowhead.com/item=29536/nethercleft-leg-armor#comments:id=97437
