### ISSUE TITLE
PALADIN BUG RESSITANCE + BUG BOK BUFF 

### ISSUE THREAD

**Issue by Jeavitto** [ValorenWoW/sunstrider-core#4553]
Character name : Whitewolf

 king is 10% stats buff ... but my king is not .... bc,  if i have 10 000 hp without king  i cant have 10700 + - with king... this is not 10% ?!

and next ... my ressitance is bug too.... i can have MAX 70 ressistance 

my aura 70
my aura + shadow priest ressist buff . still 70 ressist ... how ?

**Comment by michaelkittrell** [comment]
shadow resist from priest and paladin shadow aura have never stacked on any normal tbc server to my knowledge.  i don't believe the 35 to all resistances from mark of the wild stacks either.  you can have 35 from mark or 70 from 1 shadow resistance buff.
