### ISSUE TITLE
Mo'arg Doomsmith in netherstorm

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4556]
Moarg doomsmith near eco dome does some sort of saw blade effect (doomsaw).   sometimes it goes away when the mob dies, sometimes it persists for 20-30s after the mob dies just hovering over the dead body.

**Comment by michaelkittrell** [comment]
hmm actually just had it happen again and it was only like 15s.  looks like just persists after death like fire on the ground or something

**Comment by michaelkittrell** [comment]
sometimes it despawns with kill, sometimes it persists significantly longer.  

not a big deal but something may not be quite right here.

**Comment by Sheikthecatman** [comment]
Thanks! The doomsaw should despawn on death after next server restart!
