### ISSUE TITLE
Blackblade of Shahram abysmal proc rate

### ISSUE THREAD

**Issue by Massie323** [ValorenWoW/sunstrider-core#4557]
**Describe the bug**

It's kinda rough to find real data on the proc chance, but when comparing classic videos to this server, it seems like the proc-chance is abysmally low around 1% if not less, whereas in videos the blade procs between every 2nd to 5th hit, usually proccing multiple times from a whirlwind or cleave. I am uncertain if the proc follows level scaling reduction past 60.

**Character name**

Ratsmacker

Item: https://classic.wowhead.com/item=12592/blackblade-of-shahram
Spell: https://classic.wowhead.com/spell=16602/shahram
NPC: https://classic.wowhead.com/npc=10718/shahram

**Expected behavior**

In the second video below, the uploader compares the proc rate to that of thunderfury which in itself hovers between 30% to 20% per hit. Again, I could not find any data on whether this was affected by level scaling @lvl70, however wowhead comments mention people dualwielding these with Titan's grip in Wotlk to get about 5 of them spawned at a time.

**Screenshots/videos**

https://youtu.be/Ph7_ZD554aE?t=21 Blackblade in Classic pvp
https://youtu.be/YGhVEasWOzU?t=9 Blackblade in Classic pvp
https://www.youtube.com/watch?v=aoFE_TnECRw Blackblade multi-proccing on a single whirlwind

**Additional context**

On a minor note, the summoned NPC's model is supposed to be visually in Shadowform, but he appears without this cosmetic effect.

**Comment by NeonicSupersonic** [comment]
Classic items have reduced proc rates in tbc. For example hoj used to be bis due to how great xtra attack was.

**Comment by Massie323** [comment]
This isn't strictly true across all classic items. Some classic effects have that general rule apply, such as Crusader Enchant or HoJ following the formula [proc%] * 0.6 = [proc%@lvl70], others were directly nerfed into the ground like Nightfall in patch 2.4.2: "Nightfall now has a chance to fail on targets over level 60." -> <0.1% proc rate.
Yet other items are completely exempt from this formula, such as [Darkmoon Card: Heroism](https://www.wowhead.com/item=19287/darkmoon-card-heroism) retaining its full proc rate & effectiveness.
Additionally, I've done more research and it seems like the Blackblade of Shahram retained its proc rate all the way until the end of MoP where it has been replaced by a reworked version in the UBRS rework.
While the image link from [this wowhead](https://www.wowhead.com/item=12592/blackblade-of-shahram#comments:id=329288:reply=583457) comment on patch 5.0.5 is defunct, the author of the image provides more context in [this forum post](https://xpoff.com/threads/possible-ubrs-changes.49484/#post-724685), showcasing that he managed to proc the blade enough times to get 9 stacks of the +50 stats buff by dualwielding it and using Bladestorm, which seems accurate if translated from the classic videos scenarios where it's only being wielded as a single weapon yet procs frequently on every single to third hit.
Meanwhile on this server, it struggles to barely proc even once across 80 hits.

I assume the main reason so little data exists on this weapon is because of the extremely rare droprate in Classic in addition to UBRS only being run for Jed/Rend, while in TBC you can't really solo Drakkisath as a class that can wield the Blade, due to him being a Boss-Level enemy, meaning he will keep hitting you with crushing blows while bleeding you with his 9 second disorient for 3k fire dmg in addition to his flamestrike, on top of nerfing your own melee damage with a massive 100% attack speed Thunderclap.
And once you reach Wotlk, the massive disparity in weapon damage just doesn't make this weapon interesting enough to grind out when you could just be wielding Shadow's Edge/-mourne instead.
Besides that, it's a pain to farm Drakkisath since Rend's arena is a huge mandatory time-waste, even with the drop-rate of the epic being increased post-classic.

**Comment by pinkisnotgay** [comment]
@Jerrythemagicdog fix when
![obraz](https://user-images.githubusercontent.com/44933866/102815654-fe135000-43cc-11eb-80bb-deeb8b46c72b.png)

**Comment by Massie323** [comment]
Only took 3 years thx xd
