### ISSUE TITLE
right click inspect

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4558]
sometimes when you right click someone and inspect you can see their items.  other times you hover them and can't get any item information (though you can see the icons of the items they are using).   Seems to be related to whether or not the person you are inspecting is your active target.  for example right click someone from raid frames maybe see items detail maybe not.  target them right click inspect always see the items.

probably an addon issue, but if you can fix it server side that would be nice.

**Comment by Jerrythemagicdog** [comment]
Yes that is an addon issue.
