### ISSUE TITLE
hunter pet doesn't want to attack / cant find a path during combat.

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4559]
pet decided at some point to move up on this ledge, probably because i was tanking below the flag (not on ledge or anything like that).  after i moved away the pet apparently couldnt figure out how to path to the centurion.    after combat, it took the arrow path to return to its master.  reminds me of the issue of the pet refusing to cross the water from the platforms to attack lurker/nagas in ssc.

![image](https://user-images.githubusercontent.com/5479930/101287159-c771ee80-37ab-11eb-97b2-c29985010328.png)

**Comment by michaelkittrell** [comment]
maybe related to these?  

https://github.com/SunstriderEmu/BugTracker/issues/4521

https://github.com/SunstriderEmu/BugTracker/issues/4525
         was in ssc on wed 11/25 and pet still didn't want to cross water so probably not fixed as stated by 4521.

**Comment by michaelkittrell** [comment]
this was in mechanar btw.  mech normal.

**Comment by z5n** [comment]
unable to reproduce
