### ISSUE TITLE
Crystal Spire of Karabor procs from judgement of light

### ISSUE THREAD

**Issue by NeonicSupersonic** [ValorenWoW/sunstrider-core#4560]
When player with health below 50% hits target with judgement of light placed by paladin wielding Spire of Karabor he gets healed by scepeter affix which provides small amount of healing to targets below 50%. This is completely wrong interaction for number of reasons.
1)To start, jol healing before wrath should count as a target self healing and not paladin healing and thus cant proc paladin items (but can proc healing items equipped on attacking character i suppose).
2)It is very unlikely that JoL should proc from scepeter in any circumstances to begin with since jol isnt a direct healing spell.

Either way, spire shouldnt proc from JoL.

**Comment by pinkisnotgay** [comment]
fking whiteknight 😡

**Comment by NeonicSupersonic** [comment]
get rekt

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks for issue.
