### ISSUE TITLE
trade bug when in mailbox

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4564]
if one person is in the mail box and a 2nd person attempts to trade with that first person they both become trade bugged and can't initiate trades with other people until at least 1 of them relogs.

once either one of them relogs, both can initiate trade again.

**Comment by michaelkittrell** [comment]
additionally when you are "trade bugged" you can't put a bag in an empty bank bag slot (that you had previously purchased or purchased after you become trade bugged).  you get the error message "you can't do that right now".  after relogging you can put bags in bank bag slots fine.

**Comment by kelno** [comment]
This happens with some mail addons such as Postal.
Postal has a TradeBlock option by default which triggers this.
/postal TradeBlock

I'll try to see if that's fixable.

**Comment by kelno** [comment]
Definitely fixable

**Comment by kelno** [comment]
Fixed with next server update
