### ISSUE TITLE
items in the guild bank

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4566]
items with variable stats for example Phantom Dagger of the Bandit level 70... do not show stat details inside the guild bank.  

instead of seeing 

phantom dagger of the bandit      77-144 damage, 65 dps, 12 agi, 18 stam, 25 attack, requires level 70....

i see 
phantom dagger                             77-144 damage, 65 dps, requires level 70.

i believe this is also true of items with charges like eye of night/chain of twilight owl.

**Comment by michaelkittrell** [comment]
does not seem to affect blue items... i assume the blue items do not have variable stats.

**Comment by TheGreyMouser** [comment]
Also affects blue items.  IE  Silver Ring...  should be Silver Ring of the Tiger, or Monkey, etc.  Displays only "Silver Ring" with not stats or "of the"

**Comment by z5n** [comment]
unable to reproduce, issue has likely since been fixed
