### ISSUE TITLE
medallion of karabor

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4569]
not sure when it happened, but i have 2 medallions of karabor in my bank.  

32649, Medallion of Karabor 49 stam, 40 shadow resist (no tp proc) item level 141
32646, Medallion of Karabor, Quest item,   no stats

i assume the quest version didn't get consumed on some quest turn in.

**Comment by Jerrythemagicdog** [comment]
Yes, it doesn't get consumed.
