### ISSUE TITLE
za, stair issues

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4571]
had a mage blink through the stairs twice in one za.   once at janalai (firehawk) once at zuljin.

also had a medicine man summon his totem under the stairs going up to bear boss... where it was unkillable by pet or range (spell/hunter) or melee.

**Comment by kelno** [comment]
Some reworks were done in those areas, is this still happening?

**Comment by Jerrythemagicdog** [comment]
Still happening on the stairs leading up to Janalai.
```
1. .tele ZA
2. .go xyzo -73.185646 1150.720947 5.537245 0.003932
3. Cast blink
```

**Comment by z5n** [comment]
issue has since been fixed
