### ISSUE TITLE
 Sha'nir in Lower City quest doesn't give rep for aldor. 

### ISSUE THREAD

**Issue by lazarijus1990** [ValorenWoW/sunstrider-core#4572]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Make sure to understand how reputation works when going from hated towards friendly.
