### ISSUE TITLE
 Sha'nir in Lower City quest doesn't give rep for aldor. 

### ISSUE THREAD

**Issue by lazarijus1990** [ValorenWoW/sunstrider-core#4573]
**Describe the bug**
Sha'nir quest in Lower City doesn't give rep for aldor.  I spent 360+ dreadfang venom sack (spiders) to lower the hostility with aldor to get to neutral, but instead of getting 10-12k reduced hostility with aldor i got from repeated quests, i got hated even more with aldor and it also lowered my scryers rep :(. 

**Character name**
 Character name: Welikepie (undead rogue)

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=25802
Quest: https://wowhead.com?quest=10019
Spell: https://wowhead.com?spell=

**Expected behavior**
 I should've gotten around 10k-13k reduced hostility with Aldor, from 20k to 7k-8k unfriendly

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Make sure to understand how reputation works when going from hated towards friendly.
