### ISSUE TITLE
bt stairs issue

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4576]
blinking down the stairs at the teron trash can drop you through the floor into ROS.  first big room, not the ramp going up top.  and yes the mobs agro and tp up.

**Comment by Jerrythemagicdog** [comment]
Stairs:
.go xyz 529.864075 108.324883 159.692062 564

**Comment by kelno** [comment]
Some reworks were done in those areas, is this still happening?

**Comment by Jerrythemagicdog** [comment]
Yes, still happening.

```
1. .tele bt
2. .go xyzo 555.368835 110.744347 155.437820 3.148676
3. Cast Blink
```
