### ISSUE TITLE
[Item] Shard of Contempt procs of stance change

### ISSUE THREAD

**Issue by lordaplala** [ValorenWoW/sunstrider-core#4577]
**Current behavior:**

When switching stance as a warrior without attacking anything and while being outside of combat, there's a chance to proc shard of contempt.

**Expected behavior:**

It should not proc

**Steps to recreate issue**

Step 1: Equip the trinket
Step 2: Chance stance multiple times
Step 3: notice when trinket procs

**id's:**
https://fr.wowhead.com/item=34472

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
