### ISSUE TITLE
Stealth Actionbar Missing

### ISSUE THREAD

**Issue by diroccoa** [ValorenWoW/sunstrider-core#4579]
**Describe the bug**
The stealth/prowl actionbar change does not occur when you activate prowl

**Character name**
rabiesbabies

**To Reproduce**

1. Cast cat form
2. Cast prowl

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

after casting prowl the action bar should change to the stealth actionbar and after attacking or coming out of stealth it should revert to the cat form action bar

**Screenshots/videos**

Catform ![image](https://user-images.githubusercontent.com/11067734/101996037-2fcd3e00-3c8c-11eb-9da3-22f0eb473e62.png)

Prowl 
![image](https://user-images.githubusercontent.com/11067734/101996047-3eb3f080-3c8c-11eb-9d64-a4fd410a7218.png)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Yes it should, make sure you're not using any addons altering action bars such as SpeedyActions or SnowfallKeyPress.

**Comment by diroccoa** [comment]
Hello there,
I tested by removing all addons and took some screenshots. I am still not receiving a stealthbar when going into prowl

![1](https://user-images.githubusercontent.com/11067734/102260984-49f65e80-3ece-11eb-8427-f76577120eba.png)
![2](https://user-images.githubusercontent.com/11067734/102260990-4a8ef500-3ece-11eb-8acf-9564823ed9f6.png)
![3](https://user-images.githubusercontent.com/11067734/102260978-482c9b00-3ece-11eb-8faf-165e13057dc1.png)
