### ISSUE TITLE
Ignite partially resist

### ISSUE THREAD

**Issue by Rindback** [ValorenWoW/sunstrider-core#4581]
**Describe the bug**

Hi Ive been noticing once I transfered to Fire spec that ignite can actually partially resist which from what I remember shouldn't be possible. From what I know is that Ignite is a binary spell.

**Character name**
Afrina

**To Reproduce**

1. Cast Fireball on target crit on target applies ignite and ignite partially resist.
2. 
3. 

https://wowwiki.fandom.com/wiki/Ignite_(old)

**Expected behavior**

Since ignite are suppose to be in the binary spell it should not be able to partially resist.I think this is one of the reason whe fire have been performing so good in this server. It was the same problem on Warmane. Link down below

http://forum.warmane.com/showthread.php?t=391707

**Screenshots/videos**
Here's 2 screenshots taken from a video proving that ignite did partially resist

https://ibb.co/sq4Ppsc

https://ibb.co/qsZLYj6

Here is the link to full video

https://www.youtube.com/watch?v=WM9LxA6GjDk&t=614s&ab_channel=Robin

**Additional context**
Im not sure how the server works when it comes to resistance but it just feels that partially resist occur way often than on different servers as well but thats an different issue.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, but that's not what I meant when I asked you to create an issue with proof. You're linking one thread from another private server which even contains an argument whether it's working correctly or not.
Please provide retail proof if you're trying to prove something's wrong.
