### ISSUE TITLE
hyjal ally camp evade 

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4582]
these mobs are all stuck evading (in pretty much the spot they are shown) about 1s before this picture was taken... until the prot pal came back and picked them up after killing the batch of ones that didn't get stuck.   cryptfiends were still sending out scarabs even while evading though.

![image](https://user-images.githubusercontent.com/5479930/102023230-2d7ce980-3d49-11eb-8af8-6da076606d20.png)

**Comment by z5n** [comment]
unable to reproduce
