### ISSUE TITLE
Seal of Blood dmg goes through bubble

### ISSUE THREAD

**Issue by B0nisek** [ValorenWoW/sunstrider-core#4584]
seal of blood self dmg from auto attack goes through bubble - bug or feature?

**Comment by NeonicSupersonic** [comment]
Supposed to, its a direct health degen or smth like that which goes through all immunities. Same damage mechanic as shatter damage on (pre-nerf) gruul. Should be still absorbed by pws, but I suppose that pws interaction works properly (havent tested myself).

**Comment by B0nisek** [comment]
yeah? dmg from sacrifice is immune tho - as it should imo

**Comment by Jerrythemagicdog** [comment]
The spell has an attribute that makes it ignore invulnerability.
