### ISSUE TITLE
Allegiance to the Aldor bug

### ISSUE THREAD

**Issue by Massterwan** [ValorenWoW/sunstrider-core#4585]
Finished city of light , picked Allegiance to the Aldor , quest and this happened.
Aldor rep increase but shows as unfriendly , scryers decreases but shows as neutral.
Character named : Massterwan
Thanks you

**Comment by Jerrythemagicdog** [comment]
Not a bug, your race has a racial bonus with the opposing faction which results in you starting at a lower point with the Aldor.
