### ISSUE TITLE
Quest: Bombing Run ( Ogri'la ) Fails to give credit

### ISSUE THREAD

**Issue by EndlessLex** [ValorenWoW/sunstrider-core#4586]
**Describe the bug**
The quest Bombing Run in Blades Edge mountains for the Ogri'la quests does not do anything when you bomb one of the fel cannons with the supplied Skyguard Bombs you are given for the quest. The cannon does not die and no health is taken away from the cannon. I have tried both north and south camps..

**Character name**
Lexington

**To Reproduce**
1. Accept quest Bombing Run
2. Fly north or south to either forge Camp Wrath or Terror 
3. While flying mounted, Use the bombs on any one of the Cannons.
4. Observe no credit given.

Item: https://www.wowhead.com/item=32456/skyguard-bombs
Quest: https://www.wowhead.com/quest=11010/bombing-run

**Expected behavior**
Cannon is destroyed by bombs and +1 is added to your credit towards  the 15 total you need destroyed.

**Comment by Jerrythemagicdog** [comment]
You're not supposed to bomb the cannons but the cannonball stacks, make sure to read the quest text.
