### ISSUE TITLE
Alar/akama qlest bug

### ISSUE THREAD

**Issue by fifiendless** [ValorenWoW/sunstrider-core#4588]
**Describe the bug**
I kill alara 2 times with my guild and qlest is not on the qlest list. I wear this mask when we fight Alar. I did alar killed but the problem is with ashtounge trick. The first log is not forced but wow it's alright when i killed the alar ruse of ashtounge it lights green i have a screen on it.

**Character name**
nickname: Fifi

**To Reproduce**
i have done this qlest many times on this server as well,only on this character, I did not pass the quest, despite the fact that I beat him with others whom I did
1. before starting the fight I wore an ashtongue cow
2. I survived the whole fight
3. after killing alar I only passed one part of qlest slain alar

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
expects to pass my qlestu, without qlestu, I can't help with  progress

**Screenshots/videos**
https://ibb.co/8g0KWsV

**Additional context**
the character was transfered from the horde

**Comment by Jerrythemagicdog** [comment]
Looks like you haven't been present to complete the quest then, other players have completed this quest without issues.

**Comment by fifiendless** [comment]
Hi,
Look on recaunt  i was terenie and kill alar. I kill alar 2 Times  and
qlest is not completed  just 1 part that ruuse of..
What if i kill alar 3rd time and will be the same? Can you ask drag my gm
master he see me on alar or asceta  we was in confuse  why im not completed

śr., 16 gru 2020, 10:11 użytkownik Jerrythemagicdog <
notifications@github.com> napisał:
