### ISSUE TITLE
Teron Gorefiend Ghosts evade and teleport

### ISSUE THREAD

**Issue by Sarlisark** [ValorenWoW/sunstrider-core#4589]
The Ghosts spawning from Shadow of Death  have a tendency to evade and  teleport to the raid--> wipe it ;
If you look down to Teron  it mostly happens on the left hand side. 
My raid believed it had sth to do with standing to close or at the wrong positon in context to the walls and boxes; eg: the ghosts spawn in/on the boxes/walls and could not walk to the raid--> evade (regenarating health) and port;
A different theory we had was that the ghosts are to far or cannot normally reach  certain postions on the Teron plattform and so would port  because of distance/reachability to their target.
Since one ghost alone reaching the raid is quite bad, especially if all other ghosts are still at spawn postion, it tends to improve the chance of wipes and is a big problem for killing Teron
Will try to make videos and pictures the next time we do Teron thought that could take some tiem since we do a Winter break

**Comment by Jerrythemagicdog** [comment]
Would need a clip of it happening, thanks for the issue.

**Comment by Sarlisark** [comment]
Since my guild is probably not continuing raiding and even if we will propably not do Teron, and then not try to wipe by finding the bug intentionally. I will not be able to take a video of this happening.
Sorry for this
thank you for waiting for me to try to get better documentation
