### ISSUE TITLE
Teron Gorefiend Shadow of Death No controllable ghosts spawn

### ISSUE THREAD

**Issue by Sarlisark** [ValorenWoW/sunstrider-core#4590]
If a person dies while under the effect of Shadow of Death by other sources like constructs on the way back or  the AoE, the controllable Vengeful spirit  does somtimes not spawn, even though the Constructs do. This usually causes a wipe since their are 4 Constructs that do not get attacked, spawning to close to the raid.
If you would still become a Spirit you would have at least a chance to kill them  before they wipe the raid, even if they reach the raid.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue. Works as intended.
