### ISSUE TITLE
Alch Stone (+40% potion efectiveness) does not affect fel mana potion ticks

### ISSUE THREAD

**Issue by NeonicSupersonic** [ValorenWoW/sunstrider-core#4593]
And probably healing from fel regeneration potions aswell. Probably were broken in sunwell patch since alch trinket with fel mana pots for sure worked in t5 and should normally work as per retail tbc.

Were tested negative with both improved/unimproved trinkets.

Sources:
https://wowwiki.fandom.com/wiki/Alchemist%27s_Stone
https://www.wowhead.com/item=13503/alchemist-stone#comments:id=101587
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/2960

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
