### ISSUE TITLE
Quest : Membership Benefits bugged

### ISSUE THREAD

**Issue by Cocio21** [ValorenWoW/sunstrider-core#4595]
**Describe the bug**
Membership benefits quest not showing up.

**Character name**
Droodzero

**To Reproduce**
See pic, quest just not showing up.

Quest: https://wowhead.com?quest=https://www.wowhead.com/quest=9887/membership-benefits

**Expected behavior**
Like on my exalted rogue, i expected the nice gem bag ^^

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/63900239/102400102-bf068880-3fe1-11eb-8f50-5a9aaecda07f.png)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Try again with the new month!

**Comment by Cocio21** [comment]
I havnt done it on my drood at all yet -.-

It was the same issue on my rogue when it got exalted

**Comment by Cocio21** [comment]
Just to confirm, the quest does not appear at all, not even on my rogue either even tho it was fixed with an update after my last report. Did this fix maybe get rolled back in another update by mistake ?

This seems to be an issue solely with a rep of exalted, the quest was there on my mage in Dec, at witch point it was not yet exalted with them, after getting exalted its not showing quest on my mage either.

![image](https://user-images.githubusercontent.com/63900239/103567386-01760380-4ec4-11eb-8945-eb6263824766.png)
