### ISSUE TITLE
casting totems without totems

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4598]
so ive been told a few stories about casting totems without totems in your bag.  IE casting Grace of air with your air totem in your bank.

I could not do this with my first shaman, but i knew others who could.   a few months later i made a 2nd shaman and this shaman can bank his totems and cast all 4 totems.   It is supposedly related to having a "totem" equipped in your totem slot which if i remove the kar a healing totem from my totem slot i can no longer cast any totems... re-equip i can cast all totems.

the really weird thing is my main pc suffered an error so i swapped to my wife's computer... on that computer my 2nd shaman could not cast totems until he got them from the bank.  I re-banked them after testing this and still couldn't cast without them in my bag.  The next day I fixed my main pc, banked my totems and to this day I can cast all 4 totems without them in my bag. 
 

something weird and inconsistent about this behavior.

**Comment by Jerrythemagicdog** [comment]
It's the same as WotLK where if you have a totem equipped in your totem slot you can cast totems which we've decided to keep.
Thanks for the issue though!

**Comment by michaelkittrell** [comment]
that doesnt explain why on my wife's pc i need totems in my bag and on my pc i don't need totems in my bag on the same toon.
