### ISSUE TITLE
swp, kalecgos, stuck in combat bug

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4600]
when kalecgos resets... anyone who was "down" gets ported up but is stuck in combat. 

you must relog (afaik) to clear the combat bug.  

then if you later cast a spell on someone who didn't relog, you are put into combat again and have to relog again.

would be really nice if when kalecgos resets all players in instance are removed from combat.

**Comment by kelno** [comment]
Thanks, fixed with next server update
