### ISSUE TITLE
Spell - Holy Paladin - Sanctified Light

### ISSUE THREAD

**Issue by Centuri0n123** [ValorenWoW/sunstrider-core#4601]
Current behavior:
The passive spell from talents  sanctified Light don't add 6% chance to the spell critical chance.

Character Name:
Andivh

To reproduce:
--Player starting combat with random NPC.
--Player start to cast Holy light (rank 6) on himself until run out of mana.
--Player cheked if the number of holy lights casted is equal to the number recorded in recount (addon) , 
--Player checked that the critical chance of the holy light is equal to the nominal critical chance of all his spells 
-- sanctified Light not add 6% of critical chance to the Holy light spell to the overall critical chance   (it must be around to 31% for my toon)

Screenshoot:

![WoWScrnShot_121920_105037](https://user-images.githubusercontent.com/65864019/102693874-a5389180-41eb-11eb-8013-4255c9c4e0f9.jpg)
![WoWScrnShot_121920_111452](https://user-images.githubusercontent.com/65864019/102693908-cf8a4f00-41eb-11eb-82b8-34c08960a36d.jpg)

Expected behavior:
-- the critical chance of the spell holy light must be higher than the overall critical chance.  (around 6% )

id's:
/script DEFAULT_CHAT_FRAME:AddMessage("\124cff71d5ff\124Hspell:20361\124h[Sanctified Light]\124h\124r");

Additional:
Not additional effect over the skill of holy light, like tier sets bonus, or enchants

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Talents are never displayed in your character sheet stats page (especially when providing the bonus to only one spell).
When trying to determine whether a % chance proc / improvement works as intended make sure to use bigger sample sizes.
Here's a test performed on a naked paladin with the talent and 4.52% base crit chance. Results are within the margin of error over a 1000 casts (which is still not ideal when trying to prove a relatively small number like 6%)
https://cdn.discordapp.com/attachments/198080855833313290/789904563493797898/paladintest.png
