### ISSUE TITLE
alchemy changing masteries

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4602]
thanks for fixing the alchemy changing masteries thing...

i changed masteries on another of my alchemists (potion), but when i went to stormspire, i couldn't take transmute mastery.  after 10-15m and a exit/relog, i was eventually able to take trasnmute mastery.

seems like there is either a delay or you have to exit game/relog after dropping alchemy masteries.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Can't reproduce, here are the steps I've tried:
1. Unlearn Potion Mastery in Zangarmarsh.
2. Move to Stormspire and talk to Zarevhi
3. Click on the gossip to learn Transmute Mastery
4. Character is correctly taught Transmute Mastery.

If the NPC doesn't offer the gossip that could be a Cache issue as gossips are Cached.
If you remember any details feel free to add them to this issue.

**Comment by michaelkittrell** [comment]
hmm really not sure.   i did a 2nd alchemist about 30m later and he changed with no problem.  there is no way i was mistaken... the option was definitely not there, after talking to him multiple times.  

strange, thanks for checking it out though.
