### ISSUE TITLE
Mounting off animation and sound bug

### ISSUE THREAD

**Issue by Swedishjoker** [ValorenWoW/sunstrider-core#4604]
As the title suggests, there's been a visual & audible bug for a while now, where you constantly hear the "mounting off" sound from other people even though they're standing still. 

It is very distracting to have in your ear when you're trying to do other stuff. I'm providing a video with an example of this. 

https://user-images.githubusercontent.com/76394102/102713383-2f562800-42c8-11eb-97d9-d143ccebc143.mp4

**Comment by Jerrythemagicdog** [comment]
It's the Christmas event transmog and you mouseovering them with an addon causing an inspect.

**Comment by SabreValkyrn** [comment]
To disable the event transmog dismount sound, create an empty file at `<TBC>\data\Sound\Spells\SpiritWolf.wav`
