### ISSUE TITLE
The Battle for Arathi Basin! Quest for Tabard of the Defiler

### ISSUE THREAD

**Issue by Cansius123** [ValorenWoW/sunstrider-core#4606]
**Describe the bug**
There is no Quest Progress if you assault the Bases so you can´t finish the Quest

**Character name**
Cansius

Item: https://www.wowhead.com/item=20131/battle-tabard-of-the-defilers#comments
Quest: https://www.wowhead.com/quest=8105/the-battle-for-arathi-basin

**Expected behavior**
When i Assault a Base that my quest progress is working and maybe get the Tabard #3001

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks for the issue!
