### ISSUE TITLE
Disappearing Quest Items and BG Marks

### ISSUE THREAD

**Issue by Traque** [ValorenWoW/sunstrider-core#4607]
My quest items and battleground marks (particularly AV marks) are disappearing after logout. This makes the game unplayable. So far I have lost around 20 BG marks with this bug and do not feel obtaining more just to lose them. Additionally, I have noticed that upon logout certain quests are repeatable that should not be, such as the first turn-in of the Concerted Efforts quest. Essentially, I believe the logout mechanism of Endless WOW is buggy and does not save your progress, or at least mine.

Current behavior:
Sporatic loss of quest items/credit or BG marks on logout.

Expected behavior:
No loss of quest items/credit or BG marks on logout.

Steps to recreate issue
In my experience, just do a quest to get quest items or credit for killing a quest mob, and then log out. Upon logging in the credit for the quest, quest items, or BG marks you obtain will be lost.

**Comment by Jerrythemagicdog** [comment]
Disable your bag addons.

**Comment by Traque** [comment]
I just did but the 20 AV marks I had did not come back.
