### ISSUE TITLE
Quest items, credit, and marks not saving on relog

### ISSUE THREAD

**Issue by Traque** [ValorenWoW/sunstrider-core#4608]
I posted this previously, but now I have a screenshot as well (as I completely cleared Mana Tombs, relogged, and lost credit for 5 of the mobs which I had credit for before the relog). My quest items and battleground marks (particularly **20** AV marks) are disappearing after logout. So far I have lost around 20 BG marks with this bug and do not feel obtaining more just to lose them. Additionally, I have noticed that upon logout certain quests are repeatable that should not be, such as the first turn-in of the Concerted Efforts quest. Essentially, I believe the logout mechanism of Endless WOW is buggy and does not save your progress, or at least mine.

**I tried turning off the bags addons I had, which did not recover my marks or quest items. This does not appear to be a fix**

Current behavior:
Sporatic loss of quest items/credit or BG marks on logout.

Screenshot
![image](https://user-images.githubusercontent.com/35206203/103192654-71263600-48a7-11eb-90f2-0d155098e7bd.png)

Expected behavior:
No loss of quest items/credit or BG marks on logout.

Steps to recreate issue
In my experience, just do a quest to get quest items or credit for killing a quest mob, and then log out. Upon logging in the credit for the quest, quest items, or BG marks you obtain will be lost.

**Comment by Jerrythemagicdog** [comment]
You're the only person this happens to, either you're not paying attention to your items or playing multiple servers and mixing them up.
Thanks for the issue, if you find a case where this happens repeatedly and you're certain it happens you can add it to the issue.
I've tried the above with a copy of your character and there's no issue.
