### ISSUE TITLE
S4 hunter axes

### ISSUE THREAD

**Issue by Herby25** [ValorenWoW/sunstrider-core#4609]
**Describe the bug**
The requirement of hunter s4 OH axe is wrong. It should require 1750 rating and 1000 arena points.
But @ vendor you will need 2050 rating and 2625 arena points for the hunter offhand..makes no sense^^
The requirement of the mainhand is fine, offhand should be equal to mainhand.
So all in all: both hunter s4 axes 1750 rating and 1000 ap

**Expected behavior**
Please change the requirement of the hunter s4 oh axe 

**Screenshots/videos**

![WoWScrnShot_122820_113746 (2)](https://user-images.githubusercontent.com/70513805/103209696-fb9c8300-4903-11eb-881f-1dd56a4fbd75.jpg)
![WoWScrnShot_122820_113752 (2)](https://user-images.githubusercontent.com/70513805/103209699-fc351980-4903-11eb-8aab-b9b3a3e96307.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update (price corrected for both items).
