### ISSUE TITLE
Orb of Deception not working

### ISSUE THREAD

**Issue by Matrijx** [ValorenWoW/sunstrider-core#4610]
**Describe the bug**
 Orb of Deception does not alter the appearance of its user. The buff is correctly applied, but the appearance altering effect is not.
**Character name**
 Matrijx, but it was also by guildmates on multiple characters/races.

**To Reproduce**

1. Equip and Use Orb of Deception
2. ...
3. Profit

**Expected behavior**

Unlike what is currently happening, Orb of Deception should alter the appearance of its user to look like a member of the opposing faction.

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Fixed with next server update. Also fixes some pirate custome stuff
