### ISSUE TITLE
Cloak of Shadows Not Working in Cities

### ISSUE THREAD

**Issue by pbrigido** [ValorenWoW/sunstrider-core#4611]
**Describe the bug**
Tried to use CoS in Booty Bay, Gadgetzan, and Ratchet.  Any DoTs  remain on after CoS has been cast.

**Character name**
All

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
Remove all harmful spells and effects, and increase 90% resistance for 4 sec.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Which DoTs are you talking about?

**Comment by pbrigido** [comment]
Sorry, for the slow reply.

The DoTs that weren't cleared were 4 from a Warlock (can't remember which ones).  All 4 remained after casting CoS.  Had a fire Mage with the same thing.
