### ISSUE TITLE
Dire maul North vendor Stomper Kreeg <The Drunk> 

### ISSUE THREAD

**Issue by echostage** [ValorenWoW/sunstrider-core#4612]
**Describe the bug**
unable to access Stomper Kreeg <The Drunk> inside Dire maul North vendor for drinks after being friendly with vendor. At first i was only able to do the quest reward from vendor but after unable to get access to vendor

**Character name**
Echostage

**To Reproduce**

1. to get friendly i used ogre suit created inside Diremaul north ...
2. used suit at vendor in order to be able to talk 
3. Did the quest to "The Gordok Taste Test"  quest=5528 after quest was unable to get access to vendor from Stomper Kreeg

Item: 1. https://classic.wowhead.com/item=18284/kreegs-stout-beatdown
         2. https://classic.wowhead.com/item=18269/gordok-green-grog

**Expected behavior**
After quest https://classic.wowhead.com/quest=5528/the-gordok-taste-test player are granted access to vendor to buy items and drinks

**Screenshots/videos**
https://imgur.com/8Jr1sh0
https://i.imgur.com/8Jr1sh0.png
![DM N](https://user-images.githubusercontent.com/48146992/103372696-b5305b00-4aa0-11eb-81eb-6bca4c7911f1.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
