### ISSUE TITLE
Multiple characters

### ISSUE THREAD

**Issue by Ravendir** [ValorenWoW/sunstrider-core#4614]
**Describe the bug**

Multiple characters, multiaccaunting, think for sale, 4 hunters
**Character name**

Clazeazull, Clazeazuil, Clazeazul
**To Reproduce**

1. Cast X o

n target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**
![WoWScrnShot_123120_021524](https://user-images.githubusercontent.com/76796955/103388178-44c12280-4b10-11eb-8bff-907399db6aeb.jpg)
![WoWScrnShot_123120_021530](https://user-images.githubusercontent.com/76796955/103388180-47bc1300-4b10-11eb-8257-03bf63f3b5cd.jpg)
![WoWScrnShot_123120_021533](https://user-images.githubusercontent.com/76796955/103388183-4985d680-4b10-11eb-9b1f-537c8d2ce58f.jpg)
![WoWScrnShot_123120_021538](https://user-images.githubusercontent.com/76796955/103388185-4b4f9a00-4b10-11eb-84c8-99735038f836.jpg)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Please open a ticket in-game for these, this is an issue tracker for issues with the game.
