### ISSUE TITLE
karazhan, hunter pull

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4617]
in karazhan, after the skeletal ushers, if hunter doesnt dismiss pet the pet always pulls a random usher when you jump down  heading to opera (the room below where you pull the first 2 performers down to).  probably has to do with the pet pathing around the stairs

**Comment by michaelkittrell** [comment]
btw if you walk down the ramp to the area below opera the pet follows you correctly.  if you jump as most people do, you pull that random usher from god knows where.

**Comment by z5n** [comment]
issue has since been fixed
