### ISSUE TITLE
Arrows in quiver disappearing when logging out

### ISSUE THREAD

**Issue by flashbacks225** [ValorenWoW/sunstrider-core#4622]
**Describe the bug**
Upon logging back into the game arrows in the quiver seem to split and vanish from the quiver 

**To Reproduce**
1. buy arrows 
2. logout -> log back in 
3. check quiver 

**Screenshots/videos**
https://www.youtube.com/watch?v=si4haiD1tAI&feature=youtu.be
edited out the loading screen

![image](https://user-images.githubusercontent.com/57075057/103708894-59d30100-4fa9-11eb-9d43-c26dc371c042.png)

**Additional context**
seems to have something to do with the split stack outside of the quiver

**Comment by bjh368** [comment]
Never happened to me, and I can't reproduce it using your steps. Is this reproducible on your end? Can you see if it happens without addons as well?

**Comment by flashbacks225** [comment]
Yes, I can reproduce it almost every time I log out and in. I think I have narrowed it down to the auto buying addon I use called "steal your carbon" https://github.com/TekNoLogic/StealYourCarbon it acts like an auto repair but this auto restocks arrows food water when talking to vendors I have tried to see if I can reproduce the issue with food and water but they seem to be perfectly fine just arrows in the quiver
