### ISSUE TITLE
Mana Thistle should restore mana upon gathering.

### ISSUE THREAD

**Issue by BasedForfrost** [ValorenWoW/sunstrider-core#4625]
As long as I've been herbing, I'm surprised in myself (or rather I had forgotten) that Mana Thistle is supposed to restore mana after being gathered, much like other TBC herbs having their own special properties (Felweed yielding Fel Blossoms, Dreaming Glory giving health per 5 buff, etc.) 

https://www.wowhead.com/item=22793/mana-thistle#comments
https://wowwiki.fandom.com/wiki/Mana_Thistle

**Comment by NeonicSupersonic** [comment]
It does, or did long ago.
Its either chance based proc or procs only when you are not full mana (which might be wrong) or both.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, indeed after re-adding new spawn points the spell was missing.

**Comment by BasedForfrost** [comment]
Wanted to bump this and post that the spell has been readded correctly, however it does not restore mana. I noticed awhile ago that the spell effect came back but I didn't want to repost until I saw the changelog to confirm that this is what happened.

![image](https://user-images.githubusercontent.com/62028592/106226314-de81fb00-61b4-11eb-8bc1-c82767e901df.png)
