### ISSUE TITLE
hfp, fel reaver doesn't path when out of range

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4626]
western fel reaver in hfp doesn't path when out of range.  its sometimes visible and just stands there for 20-30m at a time when it should be constantly patrolling.  very specifically south of the temple of telmat, you can farm the vultures and watch the fel reaver standing off in the distance never moving on both sides east or west.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
That's a common thing across all creatures with huge visibility distance that exceeds the update range.
When there are many players in HFP it's less of a problem as there is pretty much always someone nearby to update them, when it's pretty barren like now it won't happen.
There are solutions for this but they don't seem to be worth it (at least for open world cases, raids are still updated as usual).
