### ISSUE TITLE
BT, mob packs immune to soothe animal/mind soothe

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4627]
were the recent changes to BT that made certain mob packs immune to mindsoothe and soothe animal intentional?  specifically the first pack heading to ROS.  the patrolling wolves are not soothable anymore nor are the rest of the humanoids that used to be soothable.   can still skip the pack (even without mindsoothe)... so why bother making them immune?  doesnt make sense.

**Comment by mechanicsTBC** [comment]
intended for consistency between all packs in all raids
