### ISSUE TITLE
Siphon Life uses Improved Shadow Bolt Stack

### ISSUE THREAD

**Issue by infohut** [ValorenWoW/sunstrider-core#4628]
Siphon Life uses a stack of Improved Shadow Bolt. Corruption and other DoT's do not use Improved Shadow Bolt stacks. The talent specifically says "non-periodic" sources.

**Expected behavior**

Siphon Life should not be consuming Improved Shadow Bolt stacks.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
