### ISSUE TITLE
Lots of wintrader!

### ISSUE THREAD

**Issue by Herby25** [ValorenWoW/sunstrider-core#4629]
**Describe the problem**
Pls Do something agains fuucing wintrader!
Often they climed up to 1900 rating...the can buy s3 weaps and full s4 gear without any REAL requirements.
They Do IT over so many weeks !

**Character name**

Bazzi
Bazookax
Rollandaa
Broola
Kotyara
Kappaross
Emgru
Xplay
Redmoonn

**Expected behavior**
Im writing in the name of many players!
Delete their teams, their gear wich gotten from wintrading or bann them.it sucks so hard.
Otherwise endless will lose much players.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report.
