### ISSUE TITLE
2 raids in the same instance

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4633]
in hyjal (and im being told others too)

you can have two different raids in the same instance.

2 people in a raid at hyjal horde camp

made a 2nd raid with someone with same raid id, entered and zoned over into horde camp.  

waved at the people in the other raid. 

you shouldn't be able to have two raids in the same instance/id.

**Comment by z5n** [comment]
unable to reproduce
