### ISSUE TITLE
Talonstrike obtainable at level 10

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#4634]
**Describe the bug**
The item "Talonstrike" was obtainable at level 10 in burning crusade,
The entire questline should be obtainable at minimum level 10. (which all of it is except for one quest)
The problem is the 2nd quest in the chain does not appear as the level requirement is higher than 10.

**Character name**
N/A

**To Reproduce**
N/A

https://db.endless.gg/?quest=438 - it says here level 10 on endless db, but not in game.
https://db.endless.gg/?item=3462 - this is the item Talonstrike.
https://www.shadowpanther.net/twinkweapons.htm

**Expected behavior**
Entire quest chain should be minimum level 10.
**Screenshots/videos**

n/a

**Additional context**
n/a

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
