### ISSUE TITLE
[Mage] Cone of Cold range doesnt benefit from leeway, while Frost Nova/Arcane Explosion does

### ISSUE THREAD

**Issue by endlessbughunter** [ValorenWoW/sunstrider-core#4637]
**Current behaviour**
If you jump, Frost Nova/Arcane Explosion range gets bigger. But this is not true for Cone of Cold

**Expected behavior**
Cone of Cold should be affected by leeway too, unless you dont intent to have leeway on this server, then it needs to get removed from Frost Nova/Arcane Explosion

**Comment by kelno** [comment]
Thanks, fixed with next server update
