### ISSUE TITLE
Invalid target when clicking on Geyser in Scouring the desert quest 

### ISSUE THREAD

**Issue by TheGreyMouser** [ValorenWoW/sunstrider-core#4638]
https://classic.wowhead.com/quest=9422/scouring-the-desert#comments   doesn't seem to work.  Gives an "Invalid target" error when I click the gyser.  Suggestions?

**Character name**
frostyjack

**To Reproduce**

1. Accept and attempt to complete quest by clicking on geyser.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**
<!

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
To dev: when looking at this make sure the geyser buff is purged when entering instances/raids.

**Comment by z5n** [comment]
closing in favor of #1867 as it seems that the current behavior when clicking is no longer an "Invalid target" error, but now:
> After clicking, it's dissapearing without leaving buff on character.
