### ISSUE TITLE
Arena Grand Master 

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#4641]
**Describe the bug**
After completing the first quest "arena master", then the second quest "arena grandmaster" should remain open on the npc "short john mithril" as a repeatable quest (blue question mark).

**Character name**
N/a

**To Reproduce**
n/a

https://db.endless.gg/?quest=7810 - first quest
https://db.endless.gg/?quest=7838 - second quest (this should be repeatable)
https://www.wowhead.com/quest=7838/arena-grandmaster#comments - shows on wowhead as repeatable

**Expected behavior**
second quest should show up and be available on the npc as repeatable.

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/75056834/104678072-c20aab00-573e-11eb-9f4e-380d12e862fc.png)

**Additional context**

**Comment by z5n** [comment]
unable to reproduce, issue has likely since been fixed
