### ISSUE TITLE
[Mage] Invisibilty delay

### ISSUE THREAD

**Issue by endlessbughunter** [ValorenWoW/sunstrider-core#4642]
**Current behavior**
When you leave invi, there is like a 1 delay before you can see enemys, while enemys can already attack you

**Expected behavior**
When you leave invi, there should be no delay and instantly being able to see enemys

**Comment by Jerrythemagicdog** [comment]
That's just the object visibility update period, it can vary depending on when exactly you leave invis (or zone out of duel) but it's definitely not 1s, should be really little in arena maybe a bit more in the duel zone.

**Comment by endlessbughunter** [comment]
Hello Jerry, especially in arena the delay is in a way, that you as mage are able to get attacked while you cant target enemies yourself yet. It is definitly roughly 1 second. Do you want me to gather some proof?

**Comment by endlessbughunter** [comment]
https://www.twitch.tv/videos/875613505?t=00h31m24s

mage gets sapped before enemy priest is even visible, after 1 sec delay priest is targetable
