### ISSUE TITLE
bt, supremus evading during kite phase

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4643]
if supremus is dragged onto the ramp (behind where he normally spawns)...

he can evade resetting 25% of health instantly with no warning

this most often happens when a player is punted onto the ramp (during kite phase) or kites him up or across the ramp.  

its not like he stops moving or anything, hes chasing and suddenly just gains 25% health.

**Comment by kelno** [comment]
This happens if Supremus can't path to his target for some period of time, he'll go to soft evade (and eventually completely evade if his target can't be reached for a longer time)
