### ISSUE TITLE
[Mage] Invisibilty doesnt get canceled on singletarget spells

### ISSUE THREAD

**Issue by endlessbughunter** [ValorenWoW/sunstrider-core#4646]
**Current behavior**
Go into Invisibilty, use Fireblast/Counterspell vs a mage who is in Invisibility aswell. Fireblast/Counterspell go on CD, nothing happens to enemy mage, he even stays in Invisibilty
 
**Expected behavior**
enemy mage should be fireblasted/counterspelled

also pls reopen https://github.com/SunstriderEmu/BugTracker/issues/4642 regarding mage Invisibilty delay, I've added a clip showcasing the problem

**Comment by ghost** [comment]
#1697

**Comment by z5n** [comment]
duplicate of #1697
