### ISSUE TITLE
[Mage] Polymorphing an already polymorphed target should not be possible, unless the new Polymorph has a longer duration

### ISSUE THREAD

**Issue by endlessbughunter** [ValorenWoW/sunstrider-core#4647]
**Current behavior:**

Polymorphing an already polymorphed target will be succesful and apply the new Polymorph with DR

**Expected behavior:**

Polymorphing an already polymorphed target will only be succesful, if the duration of the first Polymorph is shorter than the newly applied Polymorph

**Supporting evidence/data:**

Watch: https://youtu.be/-J55f0puu9A?t=689

**Comment by Jerrythemagicdog** [comment]
We allow replacing your own spells.
