### ISSUE TITLE
Southsea Treasure does not drop from Polly for the quest Plundering the Plunderers

### ISSUE THREAD

**Issue by Keerp96** [ValorenWoW/sunstrider-core#4648]
**Describe the bug**
Rogue class quest Plundering the Plunderers cannot be completed, after interacting with The Jewel of the Southsea and spawning Polly and using the E.C.A.C. on her and then killing her she does not drop Southsea Treasure.

**Character name**
Keerp

**To Reproduce**
1. Interact with The Jewel of the Southsea
2. Use E.C.A.C. on Polly
3. Kill Polly

https://classic.wowhead.com/quest=2381/plundering-the-plunderers
https://classic.wowhead.com/object=123462/the-jewel-of-the-southsea
https://classic.wowhead.com/npc=7167/polly
https://classic.wowhead.com/npc=7168/polly
https://classic.wowhead.com/item=7968/southsea-treasure
https://classic.wowhead.com/item=7970/e-c-a-c

**Expected behavior**
Southsea Treasure should drop from Polly

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/1152200/104887923-bc96a600-5974-11eb-98fb-1ad5b3de8883.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update. For now you'll have to deal with the big bird!
