### ISSUE TITLE
Stuck in reputation KoT

### ISSUE THREAD

**Issue by Centuri0n123** [ValorenWoW/sunstrider-core#4649]
**Describe the bug**
I am raiding with my guild sQUAAD once a week and my reputation haven't move since long time ago

**Character name**
Andivh/Alliance- level 70 paladin

**To Reproduce**
1. Doing several times HS and my rep didn't get exalted is stuck in rev

**Expected behavior**
It get reputation from killing mobs inside the 25man instance hiyal Summit 

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/65864019/104983658-33668a00-59db-11eb-8d8b-b960d9fcfdd6.png)
![image](https://user-images.githubusercontent.com/65864019/104983776-70cb1780-59db-11eb-9d24-bdd8226cc267.png)

**Additional context**
after killing mobs my reputation bar didn't move

**Comment by Sarlisark** [comment]
Ehm, Mount Hiyal is Scale of the Sands, not Keepers of Time, so of course  you will not get any reputation for KoT in Hiyal.
