### ISSUE TITLE
[Paladin] More then one seal can be active  and proc in short time period. 

### ISSUE THREAD

**Issue by sposobniy** [ValorenWoW/sunstrider-core#4654]
Describe the bug: 
When you switch seal , in short time period they both active on you ~ 0.5 sec , If you do hit in this time  , you will get proc from both  .

https://imgur.com/LWkxOyp 
https://youtu.be/x1xCoYKPszU  1) on this video , first hit i get proc from both seals did SoB to SoC . (not like normal seal of twist SoC=>SoB) .  2) then i buff seal for heal and mana regen and they also did proc in same time .
 
Possible to abuse it  with reconing and w.o. , with stop attack and seal swapping . 

How this was on retail : 
Only one seal  can be active , seal of twist was based on delay SoC proc 
https://youtu.be/1ud1KQvvs1M

**Comment by pinkisnotgay** [comment]
The way Seal Twisting works here in intended.

**Comment by Jerrythemagicdog** [comment]
You can twist any seal into any seal on Classic which is what the implementation is based off of.
Seal of Command has a tiny cooldown to prevent multiple procs and the abuse you're outlining here.
If you have a specific abuse in mind then showcase the specific abuse, don't just say "it's possible".
Thanks for the issue.
