### ISSUE TITLE
Question: parital resists on bossed

### ISSUE THREAD

**Issue by Sarlisark** [ValorenWoW/sunstrider-core#4655]
When fighting bosses I recently realised on my SP, that  ticks of my dots and also direct spells like  Death and Mind Blast are often partially resisted, even though the bosses (Teron/Gurtogg in this case) had Elements on them and I myself was Hit capped with 16.5% shadow spell Hit (Talents and gear).
My queston is whether that is intended and happens on all classes or is a bug for shadow Priests. I know that partial resists are usually dependend on the  Resistance scores of you and your enemy( the stuff you gather for Mother) So would I need to gather spell pen to reduce that score of the boss, or jsut have to except this  over all  5-15% dmg loss through  up to 50% resisted partials?

**Comment by Jerrythemagicdog** [comment]
You can find information on that in many places on the internet, partial resists are a part of boss fights.
