### ISSUE TITLE
NPS Ursangous doesn't give a paw

### ISSUE THREAD

**Issue by AlexFranc** [ValorenWoW/sunstrider-core#4658]
**Describe the bug**
I killed Ursangous 4 times. But it didn't give his paw. In wowhead() paw drops with 86% chanse.

**Character name**
Saitigar

**To Reproduce**

1. Go to Kalmdor, Ashenval, 42.2 66.0
2. Kill Ursangous

Nps: https://classic.wowhead.com/npc=12678/ursangous

**Expected behavior**
Dropped paw.

**Comment by AlexFranc** [comment]
NPS Shadumbra - doesn't give his head(https://classic.wowhead.com/npc=12677/shadumbra)

**Comment by Sheikthecatman** [comment]
You have to be Horde and talk to [Senai Thunderheart](https://db.endless.gg/?npc=12696) about the creatures to initiate the hunt, which then allows the paw and head to be dropped from both creatures.

**Comment by AlexFranc** [comment]
I tried to speak with Senai. But she didn't give me any quests or any tips about quests of "The hunt".

**Comment by AlexFranc** [comment]
I found the solution. First, you need to speak Warcaller Gorlach in Ogrimmar. And then Senani Thunderheart will speak with you.
