### ISSUE TITLE
Hunter - Aimed Shot cast time

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4661]
Cast time is 3 sec instead of 2.5
Patch 2.3.0 (13-Nov-2007): Added reduction of healing done to that target by 50%, shot time reduced by 0.5 seconds to 2.5 seconds. The reduced healing effect does not stack with Warriors' Mortal Strike or with Rogues' Wound Poison.  
https://www.youtube.com/watch?t=496&v=NoKD723_yAM

**Comment by charles-de-goulash** [comment]
Made a new hunter, this one has 3 sec cast time on Aimed, but the same gear/talents..?

**Comment by Jerrythemagicdog** [comment]
> Added reduction of healing done to that target by 50% and cast time was reduced to 3 sec from 3.5 sec. The reduced healing effect does not stack with Warriors'  [Mortal Strike] or with Rogues'  [Wound Poison].


https://wowwiki.fandom.com/wiki/Aimed_Shot?oldid=1636963
https://wow.gamepedia.com/Aimed_Shot#:~:text=Aimed%20Shot%20is%20a%20level,a%20significant%20amount%20of%20damage.
