### ISSUE TITLE
Hunter - Trap trigger radius

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4662]
**Bug description**
The radius is less than 5 yards.
Trigger distance is not modified by victims stealth (level).

**Expected behavior**
Trap radius equals melee attack range and is affected by stealth.

**Supporting evidence**
Hotfix (2015-01-08): "Freezing Trap now has a trigger radius of 3 yards (down from 5 yards)."
[Classic WoW test](https://gitlab.com/lights-vengeance/issues/-/issues/220#note_298363523)
https://github.com/SunstriderEmu/BugTracker/issues/1699#issuecomment-574538453
comments from a [classic wow reddit discussion](https://www.reddit.com/r/classicwow/comments/ikcauz/pvp_against_hunters_after_they_feign_for_trap/):
> Invoqwer  4 months ago
I've found that it is literally impossible to disarm a trap while
unstealthed (5yd trigger radius?) but while I am stealthed it has
like a 2 yd trigger radius, not sure why this works like this

> SpicyCheetoh  4 months ago
... Also trap radius is affected by your level og stealth. So rogues
and druids can casually walk through them most of the time.

> The trigger range on Hunter’s traps are reduced by Stealth when the stealthed player is a similar or higher level than the Hunter. [WoW Classic "Not a bug" List](https://eu.forums.blizzard.com/en/wow/t/wow-classic-not-a-bug-list/50941)

note:There are comments here and there mentioning that melee attackers are able to hit the hunter from the other side of the trap. This happens when leeway comes into play - https://eu.forums.blizzard.com/en/wow/t/the-frustration-of-hunter-in-pvp-vent-thread/111178
> The Melee Leeway: This situation only happens against good PvPers, but when you put down a freezing trap, and they know and run around it while you are ALSO running around the trap, both going merry go around, yet they still hit you while you are on the OTHER side of the trap by a HUGE margin (We’re speaking 6+ yards), while they have 100% DPS uptime on you while not being affected by trap AND hitting you from the additional melee range after the first hit, is annoying as hell to the point that I am considering swapping class for PvP.

**Comment by Jerrythemagicdog** [comment]
It is 5 yards from the middle of the trap.
Hitbox sizes are universal on the server, comparisons to retail with Orcs, Taurens and other slightly bigger races will show different results.

> Trigger distance is not modified by victims stealth (level).
Thanks for the sources but we're not really interested in making hunters' lives more miserable than they already are for the sake of emulating Classic.

**Comment by ghost** [comment]
So if I understand this right, all races have tauren-like hitbox on this server? Because on classic servers, hitting a hunter who is standing directly on the trap is only possible if one of the players is tauren, because melee range ends up being more than 5 yards. @Jerrythemagicdog

**Comment by charles-de-goulash** [comment]
> Thanks for the sources but we're not really interested in making hunters' lives more miserable than they already are for the sake of emulating Classic.

Honestly this trap range problem is making their lives more miserable than anything else. It bothers me and I don't even play a hunter.

**Comment by ghost** [comment]
Please take a look at this video @Jerrythemagicdog   
https://youtu.be/By8Ny6BJwKY?t=429  
On Endless, all races can easily hit the hunter and ignore the trap.
