### ISSUE TITLE
Framedropping While im moving the mouse

### ISSUE THREAD

**Issue by Poyso** [ValorenWoW/sunstrider-core#4664]
When i move my cursor fast, my games start lagging/framedropping

Badcombo

**To Reproduce**

**Expected behavior**
Like if i move faster my mouse, the game shouldnt framedrop

**Screenshots/videos**
https://streamable.com/nnxm09

**Comment by ghost** [comment]
untick Hardware Cursor, that usually works

**Comment by Poyso** [comment]
> untick Hardware Cursor, that usually works

How can i remove it?
