### ISSUE TITLE
AoE range leeway

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4666]
Leeway check for AoE abilities should take only the caster's movement state into account (not the target's).
https://youtu.be/DkPntjprhjA?t=19

**Comment by ghost** [comment]
Someone posted these formulas, idk if they're correct:

Melee attack: **MAX(5, SourceCombatReach + TargetCombatReach + 4/3) + IfSourceAndTargetAreRunning(8/3)**
Ranged attack: **SourceCombatReach + TargetCombatReach + AttackRange + IfSourceAndTargetAreRunning(2)**
AoE: **TargetCombatReach + AttackRadius + IfSourceIsRunning(2)**

**Comment by Jerrythemagicdog** [comment]
That's currently the case.
