### ISSUE TITLE
Rot Hide Clues

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#4667]
**Describe the bug**
The quest is not showing on the "corpse laden boat". I suspect this may be due to the quest level requirements not being correct.

https://db.endless.gg/?quest=439

**Expected behavior**

The quest should show up as available to pick up from the corpse laden boat. Check and adjust the minimum level requirement to lvl 10.

Could you please also ensure the remaining quests in this questline have a minimum level requirement of 10 so i dont have to keep coming back to create new bug reports for each quest in this questline? 

Many thanks and much appreciated!

![image](https://user-images.githubusercontent.com/75056834/106353961-6f3a1180-6342-11eb-8a15-dd3015e1c0e9.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update (for the rest of the chain too).
