### ISSUE TITLE
Withered Flesh quest

### ISSUE THREAD

**Issue by TheGreyMouser** [ValorenWoW/sunstrider-core#4668]
withered bog lord samples not dropping per wowhead.  https://www.wowhead.com/item=29481/withered-bog-lord-sample
I have ONE from aprox 30 withered bog lord kills.   I have 8 mote of life from these 30 kills.  Something is wrong here.  Drop rate on withered bog lord samples should be 14%.  So far, it looks like 3% or less.

**Comment by TheGreyMouser** [comment]
Screw it.. ABANDONED QUEST

**Comment by Jerrythemagicdog** [comment]
The chance is at 15%. Sounds like you were getting unlucky!
