### ISSUE TITLE
The "Oh, It's Real" quest can only be completed by one character on the account.

### ISSUE THREAD

**Issue by PPGGPilot** [ValorenWoW/sunstrider-core#4670]
**Describe the bug**
The "Oh, It's Real" quest can only be completed by one character on the account. I successfully completed the quest and the entire chain with the first character on my account. When I try to complete that quest with another characters, the target NPC is inactive, there is no question mark above his head, nothing happens when I clicked on him. Tried several times after logging out and logging back in, and after deleting the cache folder. Still the same for both characters.

**To Reproduce**
1. Start and finish the chain of alliance quests in Theramore - Dustwallow Marsh (This Old Lighthouse -> Thresher Oil -> Dastardly Denizens of the Deep -> Is it Real? -> Nat's Bargain -> **Oh, It's Real** ->Take Down Tethyr!). All should be ok and quests doable.
2. Start the same chain with a different character on the same account.
3. Now you will only be able to complete the first 5 quests. When you try to complete the 6th quest - "Oh, It's Real", you will notice that the target NPC is inactive. 

1st quest of the chain: https://www.wowhead.com/quest=27216/this-old-lighthouse
2nd quest of the chain: https://www.wowhead.com/quest=27217/thresher-oil
3rd quest of the chain: https://www.wowhead.com/quest=27218/dastardly-denizens-of-the-deep
4th quest of the chain: https://www.wowhead.com/quest=27219/is-it-real
5th quest of the chain: https://www.wowhead.com/quest=27220/nats-bargain
**6th and the bugged quest of the chain**: https://www.wowhead.com/quest=27221/oh-its-real
7th quest of the chain: https://www.wowhead.com/quest=27222/take-down-tethyr#
Bugged, inactive NPC: https://www.wowhead.com/npc=23905/major-mills

**Expected behavior**
The entire quest chain can be completed by all characters on the account.

**Screenshots/videos**
I have no screenshots/videos.

**Additional context**
N/A

**Comment by Sheikthecatman** [comment]
When Tethyr is alive Major Millis will not give quests, I've tested accepting the quest with multiple characters on the same account and it works.

**Comment by Sheikthecatman** [comment]
However, an issue was found were Major Millis would not be able to give quests if Tethyr despawned. The fix for that is applied next server restart.

[4a8400fba0f4079759f0f4c28b5fd48319062165](https://github.com/kelno/sunstrider-scripts/commit/4a8400fba0f4079759f0f4c28b5fd48319062165)
