### ISSUE TITLE
za, zulkin fire form transformation delayed by lynx pounce

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4671]
this happened to me 2 ids out of 3 about a month ago forgot to report.  haven't done many za's lately.

in za, when zuljin is transitioning from lynx form to final fire hawk form, if he enters the aoe dash and pounce phase right before... he continues it well after he should transition to fire hawk.  

not sure he should do that.

**Comment by Jerrythemagicdog** [comment]
Yes, the boss will finish current spells before transitioning.
