### ISSUE TITLE
Problem with attacking Netherwing NPC.

### ISSUE THREAD

**Issue by Merzerbug** [ValorenWoW/sunstrider-core#4673]
Problem is that i wanted to farm Nether Dragonscales (https://www.wowhead.com/item=29548/nether-dragonscales) but i have a friendly reputation with Netherwing Faction (https://www.wowhead.com/faction=1015/netherwing). Even when i select faction in my Reputation interface and click on 'At War' option, i still can not attack this NPCs. Tried with Nether Drake (https://www.wowhead.com/npc=18877/nether-drake), Mature Netherwing Drake (https://www.wowhead.com/npc=21648/mature-netherwing-drake) and Lesser Nether Drake (https://www.wowhead.com/npc=21004/lesser-nether-drake)

This happened on character named Merzer, lvl 70 Night Elf Druid.

Message i get when i try to attack after i mark faction 'At War' is 'Invalid Target', and like i described in ticket i posted i was able to do this on server i've previously played on. I tried re-logging the game, deleting 'Cache' folder, attacking with different spells, AOE spells, charging...

**Comment by kelno** [comment]
Fixed with next server update
