### ISSUE TITLE
Pet - Passive

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4674]
**Bug description**
The command is delayed by pet's attack. This can lead to pet breaking crowd control when we want it to stop attacking and return to it's Stay position. In some scenarios (mostly PvP), having the pet next to you is not a good idea.

**Expected behavior**
Pet should immediately cease to attack and then follow/stay.

**To Reproduce**
1. Summon Water Elemental
2. Command Stay
3. 〃 Attack
4. 〃 Passive

> Pet Passive  ([source](https://classic.wowhead.com/guides/hunter-dps-macros-classic-wow#pet-passive))
This will set your pet to passive, **instantly** calling it back towards you and stopping it from dealing damage until commanded to.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
