### ISSUE TITLE
Alchemy Discoveries

### ISSUE THREAD

**Issue by Samcolt357** [ValorenWoW/sunstrider-core#4676]
I've made hundreds of potions, elixirs and flasks recently but I have not made any discoveries.  Is the system for discoveries working as expected?  Am I just unlucky?

**Comment by Jerrythemagicdog** [comment]
Sounds like you're getting unlucky, the discoveries system was tested multiple times.
Feel free to include your character name if the problem persists though and we'll look into it, perhaps there's an actual issue.
