### ISSUE TITLE
[core] Spells increasing chance to hit dont negate spells increasing chance to resist

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4680]
Talents such as Shadow Focus currently dont penetrate talents such as Unbreakable Will.

Which means, if you have 5/5 shadow focus, you still have 15% chance to miss(resist) your fear or silence instead of having just 5%.

All spell hit rating gems/talents/spells/auras that grant either pure hit or reduce chance to resist should be negating auras that increase chance to resist.

Gamebreaking.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, please provide proof that effects modifying hit rating should have an effect against mechanic resistance (stun, fear, silence, etc) effects.
The above described is already in effect for talents like Warlock's Suppression (18174) and its interaction with e.g. Cloak of Shadows (31224) which is just a regular interaction.

**Comment by Evolvee** [comment]
Spell hit rating gives the exact same "effect" as these talents such as Shadow Focus -- increase chance to hit or reduce chance to be resisted = its the exact same thing, just differently worded.

There are hitcaps for PVP and PVE (due to level etc.), but if you go over the "hitcap", the additional hit starts counting exactly towards negating talents (auras applied on character) that increase the chance to resist.

I dont have any proof, you would have to login on classic wow (which isnt rly a proof itself due to being emulated on legion), its a common sense...

If the above interaction works properly, it could be an issue of the specific talents and/or spells not having proper mask to be affected by such talents... Great example is talent "Silent Resolve" that is known to be the most bugged shit on private servers working only towards all the "positive" buffs instead of the priests debuffs (dots) as well...

**Comment by Jerrythemagicdog** [comment]
> There are hitcaps for PVP and PVE (due to level etc.), but if you go over the "hitcap", the additional hit starts counting exactly towards negating talents (auras applied on character) that increase the chance to resist.

This is correct and consistent with the CoS and Suppression example, however we're talking about mechanic resistance effects which are completely separate effects, that much can be observed just by comparing spell effects (CoS EFFECT_0 is 186 which is handling the decreased hit chance part, Unbreakable Will EFFECT_0, 1 and 2 are 117 which are handling the mechanic resistance part).
Silent Resolve seems to be working correctly, the dispel resistance part can be observed on spells like Hex of Weakness. We also run automated tests each week to confirm these mechanics don't break.
Classic could be a source for this, TBC would be the best source or even LK if there's any guarantee it didn't change.
Definitely not a common sense issue when we're talking about different effects and supposed interactions between those.

Some more discussions:
https://github.com/ccshiro/cc-buglist/issues/2184
https://old.reddit.com/r/classicwow/comments/8ws967/lesser_known_fact_about_the_resist_talents/e1yjcx0/

**Comment by kelno** [comment]
Thanks for reporting. It doesn't seem obvious at all to me as suggested, I'd need to see good sources for that one.
Reading the whole conversation now I basically I agree with Jerry, one effect is about mechanic resist chance, and the other one about regular hit chance, those are distinct effects that don't interact in any way I know about.
Closing for now, if someone gets some serious proof for that, open a new issue.

**Comment by Evolvee** [comment]
As a shadow priest with 3% hit rating and 10% hit from Shadow Focus, I resist almost every second silence against other priests... Even tho i should have only 2% chance to resist. If you think thats correct then yea... no point in arguing. I will put the talents into spirit tap, it has a better use then.

**Comment by Evolvee** [comment]
Wait.. now when I think of it, are you saying that all people should from now IGNORE all talents that increase chance to hit? Because they are essentially worthless once you get a hit cap (since what you are saying is that those talents are only for "PVE" related hit-cap scenarios and arent doing anything at all in PVP)? Because everyone gets the default PVP spell hitcap just from the starter gear...

Mages:
![image](https://user-images.githubusercontent.com/1942409/107505655-51b84380-6b9d-11eb-9576-e42effb2805c.png)

this talent is useless, better spend it inside Improved Arcane Missiles

![image](https://user-images.githubusercontent.com/1942409/107505821-8cba7700-6b9d-11eb-90c1-73128b6ceaca.png)

Elemental Precious?? nooo better spend it on Frost Warding guys.

![image](https://user-images.githubusercontent.com/1942409/107505966-b4114400-6b9d-11eb-9657-efb050654190.png)

Arctic Winds only 2/5? Nooo you need to put it at 5/5 because noone can negate it.

Ele shamans, do you like your talents to be wasted? Great! Put them inside Elemental Precision!
![image](https://user-images.githubusercontent.com/1942409/107506242-1bc78f00-6b9e-11eb-8356-720c60eb74c3.png)

Yo warlocks, do you think this does anything?
![image](https://user-images.githubusercontent.com/1942409/107506371-49acd380-6b9e-11eb-9939-3c084c89194f.png)
You just got Jebaited, but atleast now you have slightly bigger chance to apply dot into cloak of shadows!! WOW! Much worth.

![image](https://user-images.githubusercontent.com/1942409/107506707-c8a20c00-6b9e-11eb-9717-8b419765f235.png)

Shadow Focus 5/5? Are you some kind of PVEr? Put them inside Shadow Affinity instead so you dont overaggro Winterspring Yetis.

**Comment by kelno** [comment]
Okay I've checked a bit more, I see where you're coming from and how it can make sense. Indeed currently those talents don't do anything if you're already hitcapped. (unless cloak of shadows or special effects like that)
The current logic does very clearly separate the regular "hit chance" calculations from the additional mechanic resist chance like Unbreakable Will or Master Poisoner. Just like you can't overcome the resist chance from the magic resistance score with hit chance. I'm very sure this is correct for the magic resistance, I'm not so sure for the mechanic resist chance. 
But the burden of proof is on the players for that one!

**Comment by Evolvee** [comment]
Even if everything I said is not true at all (in some distant universe far outside of our galaxy)... you are intentionally increasing resists on a pure arena-only PVP server... Judging by the custom edits (https://endless.gg/changes) to spells like Escape Artist or literally all melee specs profiting from hit rating instead of spell hit rating.. I was under the impression you want to reduce resists, therefore making arenas not entirely about RNG?

**Comment by ghost** [comment]
Resist to X mechanic is a separate check

**Comment by Evolvee** [comment]
You should make an announcement then to let players reset their talents and put them somewhere else, because right now they all think those talents are actually doing SOMETHING.

**Comment by Klimpb** [comment]
Cmon guys, this is old news, good thing I archived all my previous reports on various shitservers in the past.


http://web.archive.org/web/20190630122529/http://www.arenajunkies.com/topic/1764-spell-hit-cap/
http://web.archive.org/web/20160503152511/http://www.arenajunkies.com/topic/11477-55-supression-ftw/#entry99763
http://web.archive.org/web/20080312054619/http://elitistjerks.com/400756-post19.html

and the fact that it's working as described in classic as well.
But these links were already linked previously, so not sure what the hold up is about.

**Comment by kelno** [comment]
Thanks. The second link just points to the same test as the first one, but the other two point to two different tests done on retail, I can go with that.
Applied with next server update

**Comment by Jerrythemagicdog** [comment]
Some more discussion with the opposite evidence: https://web.archive.org/web/20080616091615/http://elitistjerks.com:80/f40/t11257-mechanics_spell_hit_counterspell/

There is also the question of melee spells and behaviour there (do talents like Rogue's Precision interact with e.g. Priest's Unbreakable Will?) as well as spells that can be resisted "per effect" (Counterspell, Frost Nova, Frostbolt, Blast Wave, etc).

If we are to argue as to what's hypothetically better for the game then we were for removing the Fear and Silence mechanic resistance parts of for example Unbreakable Will and the 4% spell miss chance talent components from Rogues and DS Druids.
If the spell hit / mechanic resistance interaction described above is correct in the first place it doesn't solve the issue at all, just reduces the chance of it happening.

**Comment by Jerrythemagicdog** [comment]
Tests done on Classic:
Warlock with 3% hit rating and 5/5 Suppression (+10% increased hit chance on Affliction spells) vs Paladin with 2/2 Unyielding Faith (+10% to resist Fear effects). 

100 Fear casts, 2 Resists (due to 1% incompressible resist chance).

**Comment by Evolvee** [comment]
This is a nobrainer mechanic, any serious PVP server would not even blink an eye over this... I dont get the need of "proving" something like this, especially since its a general knowledge nowadays since Corecraft 8 years ago and was talked over multiple times.

I wouldnt say a thing if you were trying to replicate retail 1:1 but cmon... with all the already custom changes done to the server, this discussion is a complete waste of time compared to some of them.


"Incompressible 1% spell resist chance removed (hit caps are unaffected)."
"Melee leeway and AoE spell are reduced to 2y (down from 2.66)."
"Spell leeway is set to 10% of the spell distance but never longer than 3 yards."
"Channeled spells leeway is set to 10% of the spell range but never longer than 3 yards."
"Escape Artist is unaffected by talents like Subtlety. "
"The following abilities are affected by melee hit instead of spell hit rating.... literally all melee spells"
"Intervene being instant and not range dependant" --- **HUGE** 
"Combat timer set to static 6 seconds."
"Diminishing Returns timer set to static 18 seconds."
"No hitting through pillars." --> **this is a pretty shit one btw, it causes tremor totems being unhittable if you put them behind bottom pillar in blade edge arena**
"All character races have the same hitbox sizes."


> If the spell hit / mechanic resistance interaction described above is correct in the first place it doesn't solve the issue at all, just reduces the chance of it happening.

Yea because 2% resist and 15% resist on CRUCIAL CCs are the same... Kapp

By the way.... when we are speaking about the resist per effect... I have never resisted a single Garrote silence on this server despite having flat 15%.

**Comment by Jerrythemagicdog** [comment]
Just to clear it up: since Kelno's comment the fix was applied and is live for the past 2 days on the Tournament Realm.

> By the way.... when we are speaking about the resist per effect... I have never resisted a single Garrote silence on this server despite having flat 15%.

Sounds like you're unlucky then!

Still looking for examples or explanation of melee hit chance vs mechanic resistance talents.

**Comment by Evolvee** [comment]
👍

**Comment by Evolvee** [comment]
By the way I just tested the Garrote silence effect vs 5/5 Unbreakable Will and out of 100 tries I didnt resist a single one.

The test was done with 0 hit rating rogue (naked).

You might want to run your weekly automated test and check this ^^

**Comment by Jerrythemagicdog** [comment]
Depending on when you've tested we've experimentally applied some of the ideas from this part of the comment yesterday and are looking for feedback:

> If we are to argue as to what's hypothetically better for the game then we were for removing the Fear and Silence mechanic resistance parts of for example Unbreakable Will and the 4% spell miss chance talent components from Rogues and DS Druids.

**Comment by Evolvee** [comment]
You should announce such critical changes before you apply them... Otherwise ppl are going to play with something they dont know doesnt work. Especially since it worked before.

As for the feedback: It is not good to make a custom changes into talents/mechanics just for 1 class without editing other classes to balance things out as well. 
And as for the actual resist feedback: It is not good to remove fear and silence mechanic from Unbreakable Will simply because
1) the tooltip will be wrong, confusing normies and ppl who dont check github (pretty much everyone)
2) It punishes classes that can negate the resistance by either picking anti-resist talents OR hit rating gems
3) It artificially boosts certain combs (which are top ladder already) while punishing other combs, further increasing the difference between them (you seriously want to boost RM even further? U kidding? As if the fact they are doing +30% dmg than what they are supposed to wasnt bad enough)
4) and finally, you create an issue that you just solved - by removing the chance to resist you make spell hit talents useless - same as if they didnt work at all

**Comment by Evolvee** [comment]
Okay, seriously... Can you turn the proper functionality of the talent (or all talents for that matter) RIGHT? I dont get why do you want to boost RM even further. The server is literally **UNPLAYABLE** due to rogues raping everything on open, especially as RM. 

Even deathside server with glaives and full SWP was more playable than your server, and I mean it in all seriousness... the damage output in here is just retarded... Giving RM 100% resist protection on top of it just nails the coffin. Noone even uses stuns anymore... why would they, better use unremovable, untrinketable silence that the 5Head admins made unresistable as well.

**Comment by lucasss18** [comment]
Nerfing a cloth classes defence ability that already has 0 mobility talents is not the way to go to make the game more balanced.

**Comment by Jerrythemagicdog** [comment]
Experiment concluded. Unbreakable Will, Heightened Senses, and Balance of Power are back to their default state with the next update on the arena realm.

**Comment by Evolvee** [comment]
@Jerrythemagicdog @kelno the issue described in this topic was not fixed

I am still resisting fears and silences with 15% spell hit (10% shadow focus + 5% gems and enchants from gear)

![image](https://user-images.githubusercontent.com/1942409/112651263-83832200-8e4c-11eb-8696-1cff1b85f15f.png)
![image](https://user-images.githubusercontent.com/1942409/112651312-8ed64d80-8e4c-11eb-8e79-6a4ca1524d44.png)

**Comment by Jerrythemagicdog** [comment]
The chance for a level 70 target to hit a spell on a level 70 target on our realms is 97% (incompressible 1% chance to resist removed, 1% hit chance added to everyone across the board to not affect hit caps).
In this case, your Psychic's Scream hit chance against Unbreakable Will is essentially ~12% as 3% of your total 15% ensure you're hit capped.

**Comment by Evolvee** [comment]
https://i.imgur.com/Lp2mLwb.png

idk, maybe im unlucky 🤡

**Comment by Jerrythemagicdog** [comment]
I've just done this test on the Tournament Realm, I can repeat it with you if you'd like, I'm not resisting any Psychic Screams.
My Priest ended up with 111 Hit Rating, which shouldn't be relevant in this test and 5/5 Shadow Focus.

**Comment by Evolvee** [comment]
By the way, someone in discord mentioned that you are calculating spell resistance chance to resist into %.

Can you tell me how much Spell Resistance is 1% "hit rating/chance to resist" on this realm? 
_In other words: if you cant get the cap on either of those stats (pene/hit rating), which one is the one more worth to go for?_

**Comment by kelno** [comment]
Good question, but that's some theorycraft question and not really a rule question, that's outside the scope of this issue. The rules are not different here compared to other realms.

**Comment by Jerrythemagicdog** [comment]
Resistance chance for binary spells due to resistances equals to average damage reduction of non-binary spells.
Resistance coming from School Resistance can not be overcome with hit rating only by spell penetration. That's based on research from developers over at cmangos (the thread is linked here https://github.com/cmangos/mangos-classic/commit/ea114d788c43dba6ed785a3dd1cd67c79a1ba182#commitcomment-19618880 some more discussion on our bugtracker about the resistance system in general: https://github.com/SunstriderEmu/BugTracker/issues/3638)

**Comment by kelno** [comment]
From Jerry: "melee hit doesn't affect stun resistance talents like unbreakable will at least on classic tbc beta, tested the spell hit stuff to re-confirm and it's the same as on classic"
Seems we're good now where we are with spell hit working against stun chance, but melee hit not doing it.

**Comment by kelno** [comment]
And more confirmation: https://tbc.wowhead.com/news/blizzard-explains-bug-fix-regarding-spell-resist-in-burning-crusade-classic-324594

**Comment by Evolvee** [comment]
They are just retarded. First they claimed that cloak should be only 80% (they even made a "not a bug list" about it), then they claim its 90% from beggining to the end of the expansion and 80% was only in the beta of retail TBC (which means they are emulating the beta client not 2.4.3 rofl)... Cant trust anything they say at this point as they dont have to prove anything and can just change their previous statements whenever it fits their current narrative.
