### ISSUE TITLE
Cruel's Intentions

### ISSUE THREAD

**Issue by andy1111111111** [ValorenWoW/sunstrider-core#4681]
**Describe the bug**

Is it possible that npc didnt give me "Cruel's Intentions" quest?
**Character name**

Patkan (rog, undead, horde)
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Depending if you've completed the chain.
