### ISSUE TITLE
(Suggestion) Fix for a few excessively good consumables

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4682]
1. [Elixir of Detect Lesser Invisibility](https://tbcdb.com/?item=3828) / [Detect Invisibility](https://tbcdb.com/?spell=132) (Warlock)
Make em effective against lesser invisibility ([Succubus Invis](https://tbcdb.com/?spell=7870), [Lesser Invis Pot](https://tbcdb.com/?item=3823)), but NOT against *greater* invisibility ([Mage Invis](https://tbc-twinhead.twinstar.cz/?spell=66), [Invis Pot 18](https://tbcdb.com/?item=9172)). I believe this was originally the intended behaviour.
2. [Elixir of Camouflage](https://tbc-twinhead.twinstar.cz/?item=22823)
Renders tracking abilities useless. It also doesn't take up Guardian/Battle elixir slot.  
Maybe reduce the duration to 20-30 sec and give it a long cooldown.
3. [Free Action Potion](https://tbcdb.com/?item=5634)
Made undispellable in TBC, but the duration remained 30 sec.  
imo reduce the duration to 12-15 sec and limit how many can be carried in the backpack. Unique(3-5) ?
4. Size-altering items inside battlegrounds, such as [Noggenfogger Elixir](https://tbcdb.com/?item=8529), [World Enlarger](https://tbcdb.com/?item=18660) ...  
Since there are no bg enemy frame addons for tbc, targeting/locating these players can be difficult. There are multiple ways to abuse this. For example, casting projectile-less spells (e.g. Arcane Blast) from a bush somewhere, or stacking these effects and ninja capping a flag.

**Comment by Jerrythemagicdog** [comment]
Thanks, we'll think about it!
