### ISSUE TITLE
Re-applying auras that increase basic stats should NOT cause loss of those stats on application

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4683]
The issue is with "greater" party-scale buffs vs "normal" single-target buff, which have the same amount of bonus stat, but with different duration.

Currently:

You have 12k HP, you have Power of Fortitude 100 stamina buff on yourself. You re-buff yourself with the same value of stamina via Power Word:Fortitude and instead of having still 12k HP and 100 stamina buff, you end up with 11k HP and 1k HP "lost" (still max 12k HP).

So currently, if you want to get a combat from your partner by re-applying stamina (its the lowest cost buff), you end up with your partner losing almost 1k HP.

Expected:
Reapplying auras that increase basic stats (stamina/intel) should NOT cause a loss of the bonus value
This also goes for SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE (BoK) auras.

**Comment by Evolvee** [comment]
Btw, this may or may not be true for weapon swaps as well.. currently you lose the entire stamina bonus if you swap between the exact same weapons... however the mechanic of "reapplying" here is different

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
The issue happens when using different spells, i.e. going from Power Word: Fortitude to Prayer of Fortitude and the other way around.
When applying Power Word: Fortitude on a target with Power Word: Fortitude no recalculation is done.

**Comment by Evolvee** [comment]
classic-like 🤦🏿‍♂️
