### ISSUE TITLE
Account creation | Password restrictions aren't shown on page

### ISSUE THREAD

**Issue by DaturoDewitt** [ValorenWoW/sunstrider-core#4684]
**Describe the bug**
When creating an account there is no information on what password-restrictions you have to follow.

**Character name**
Not applicable.

**To Reproduce**
1. Visit https://endless.gg/account/creation
2. Try choosing a strong password
3. Be perplexed that your password generator creates invalid passwords
4. Change the settings...
5. Repeat 4 until a password is accepted

Site: https://endless.gg/account/creation

**Expected behavior**
Hover action or something that shows what character sets are allowed.
e.g. a-z, A-Z, 0-9, !, ?, etc.

**Screenshots/videos**
Not applicable.

**Additional context**
Honestly this is just something that annoyed me. Imo you can ignore this if amending that takes more than 5mins of work.

**Comment by Jerrythemagicdog** [comment]
Thanks, we'll look into clarifying it!
