### ISSUE TITLE
Eredar Twins Bug

### ISSUE THREAD

**Issue by Nostaglicdude** [ValorenWoW/sunstrider-core#4691]
Eredar Twins Bug
1. While doing Eredar Twins, we had the ranged and healers stack on top of the balcony for tighter healing sync. However, each attempt, 5 seconds into the fight, the entire group gets one-shotted by shadow nova, searing flames, shadow images, shadow blades at the same time! Even before Conflagrate is being cast. That should never happen. Even more, the shadow images manage to reach the raid to stun the entire group when they should die before reaching the top balcony group.  
2. Also, Shadow Nova hitting for 5k+ damage instead of the accurate number 3,238-3,762 shadow damage. 

**Character name**
Lowonholy

Lady Sacrolash
Confounding Blow — Confounds the target for 6 seconds, dealing 7353-9947 Shadow damage. Cannot occur more than once every 25 seconds. Temporary aggro drop.
Dark Touched — Healing effects reduced by 5%. Stacks up to 20 times, or a maximum of 100% healing reduction for 3 minutes. Can only be removed by being hit with Fire damage from either Twin.
Inv weapon hand 08.png  Shadow Blades — An attack dealing 2550 to 3450 physical damage. Also applies
Dark Strike — dealing 450 Shadow damage every 2 seconds and slowing the target by 10% for 10 seconds. Stacks up to 5 times, the timer is updated on each new stack.
Shadow Nova — A nova type attack dealing 3238 to 3762 Shadow damage to every player within a 10 yard radius of the player it is casted on. Usually targets the player with the 2nd highest aggro on Alythess. Cannot occur more than once every 30 seconds.

**Shadow Image — Lady Sacrolash randomly spawns multiple Shadow Images which die on their own after a short amount of time. They cannot be targeted, and will typically only do one of their available attacks on a random player :
Melee attacks — causes the target to become Dark Touched, and applies Dark Strike.**
Shadowfury — Causes 1826 to 2174 Shadow damage and stuns everyone within 10 yards for 2 sec.

Grand Warlock Alythess
Pyrogenics — A buff on Alythess increasing all Fire damage of spells and effects done by her with 35%.
Flame Touched — A stackable debuff causing 300 Fire damage every 2 seconds. Stacks up to 20 times or a maximum of 6000 per 2 sec. Can only be removed by being hit with Shadow damage from either Twin.
Conflagration — A debuff placed on a target dealing 1600 Fire damage to everyone within 8 yards and also causes them to gain the debuff as well. In addition, it confounds the target for 6 seconds and scorches players within 8 yards for 1600 Fire damage each second. Usually casted on the player that is 3rd on Sacrolash's aggro.
Blaze — Causes 5525-7475 Fire damage. Leaves a patch of fire on ground which Burn for 2300-2700 Fire damage.
Flame Sear — A debuff placed on 3-5 random players dealing 650 Fire damage every half second for 6 seconds for a total of 7800 Fire damage.

**Expected behavior**
Shadow Images not touching the raid where we are positioned at the top of the balcony nor should shadow strike. It should be accessible to do the top balcony strategy to avoid being stunned ever. Otherwise, it is virtually impossible. 

**Screenshots/videos**
Do not have video to show. But can confirm about the shadow image bug staying alive until they hit someone on the top balcony when they should be dead before reaching the top balcony. 

**Additional context**
Historically, guilds have used top of the balcony strategy to avoid being stunned by shadow images and being hit by shadow strike to make healing much tighter and simpler.

**Comment by Jerrythemagicdog** [comment]
Shadow Images have a Shadowstep spell.
Spell damage was increased on all spells throughout the fight.
