### ISSUE TITLE
[Mage] Fire mage's talent Blazing Speed

### ISSUE THREAD

**Issue by Erlenkeel** [ValorenWoW/sunstrider-core#4692]
Mage's fire talent Blazing Speed bugged here discribe of this talent: 1/2 Gives you a 5% chance when hit by a melee or ranged attack to increase your movement speed by 50% and dispel all movement impairing effects. This effect lasts 8 sec.

It works for every movement impairing effect but not for rogues crippling poison which slow you on 50%

**Comment by ghost** [comment]
It can probably be resisted due to Vile Poisons talent

**Comment by Erlenkeel** [comment]
Anything cant stop this effect, so firemage / pompyro not really viable to play in pvp without it
