### ISSUE TITLE
charge/intercept pathing

### ISSUE THREAD

**Issue by beefjurkey** [ValorenWoW/sunstrider-core#4696]
Any class with a charge/intercept is able to get it off consistently from los (most warriors abuse the hell out of this).
Ontop of that, if given the right circumstance (blades edge bridge for example), they can charge up to 50/60 yards......as well as being in los.

**Comment by Jerrythemagicdog** [comment]
LoS charges: That's just lag for the most part. You need to keep in mind your character is fairly behind for the server compared to where it is for you and your position is only updated every so often.
As for bridge pathing there is some leeway as to how far they can charge but if you do some research for example through old videos you can see that it's pretty close, perhaps it's further in some cases but it's pretty difficult to balance and from what we're hearing the way Charges work right now is decent.
We're definitely not going the blizzlike route with charges where standing on top of the tomb would give "no path available".
