### ISSUE TITLE
Improved Hamstring overtuned

### ISSUE THREAD

**Issue by beefjurkey** [ValorenWoW/sunstrider-core#4697]
Similar to my post about macestun proc % here, improved hamstring is proccing so much that warriors are literally spamming all of their spare rage on it to get either a proc from improved hamstring or macestun (warriors have bused rag gen also)
It often ends up that you cant move once a warrior has hit you once until they are in a full cc chain

**Comment by Jerrythemagicdog** [comment]
Same as other issues: numbers please.
