### ISSUE TITLE
Endless rage applying with dodge/parry/missed attacks

### ISSUE THREAD

**Issue by beefjurkey** [ValorenWoW/sunstrider-core#4698]
Endless rage reads "you generate 25% more rage from damage dealt"
Yet it still applies to misses/parrys/dodges
We actually tested this on the target dummy too make sure its correct

**Comment by Jerrythemagicdog** [comment]
No rage is generated on misses, other than that the issue is correct as long as it's not one of those misworded talents.
Thanks for the issue, fixed with next update.
