### ISSUE TITLE
warlock pet resistance

### ISSUE THREAD

**Issue by beefjurkey** [ValorenWoW/sunstrider-core#4700]
Warlock pets have been EXTREMELY weak here on endless.
Partially due to the overtuned melee damage (1 melee 1 shots my pet all the time), also because of how the resistances have been scripted here.
Warlock pets should be able to fully resist any spell. yet if a non binary spell is casted on it...it CANT fully resist here (a spell that doesn't have chance to proc cc). I have tested this myself
On every other server casters have not been able to blow up pets....but here they do that all the time, which is crazy considering they have 218 resistance self buffed. Imagine you had 218 resistance as a player....casters would barely touch you (then motw/shdw prot ontop of that)
For example, my pet gets banished 4/5 times even when coe is NOT on it....even druids with 20 spell pen consistantly hit clones and roots on it (it should resist 9/10 of these if not more)
So resistance is just not working correctly on both binary and non binary spells with lock pets

**Comment by beefjurkey** [comment]
ALSO pet spells arnt getting any spell hit or spell pen at all, so pet abilitys missing all the time

**Comment by Jerrythemagicdog** [comment]
Please provide proof the resistance system is not working correctly.
This should answer your questions: https://github.com/SunstriderEmu/BugTracker/issues/3638
