### ISSUE TITLE
[core] [spell] [priest] Vampiric Embrace stops healing when its caster is dead

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4703]
Its probably handled as if the priest is healing the party members, therefore doesnt work once dead. 

E.g.: U dot someone, VE, dead, party members no longer get healed from dots ticking.

Also it seems like if you kill someone (fatal hit), the fatal hit isnt considered for healing through Vampiric Embrace either.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
I see a check specifically to make sure the Priest is alive in order to proc, could you provide some video proof or other evidence that shows it should proc while he's dead?

**Comment by Evolvee** [comment]
nvm, ur probably right
and i see that the killing blow is already reported so closing, sry
