### ISSUE TITLE
Please don't end battlegrounds early if the teams have close to the same numbers.

### ISSUE THREAD

**Issue by beauxq** [ValorenWoW/sunstrider-core#4704]
**Describe the bug**
Battlegrounds end early when the teams have the same number of players.

**To Reproduce**

Play an Alterac Valley with 10 Horde and 10 Alliance.

**Expected behavior**
The game should play to the end because the teams have the same number of players.

**Additional context**
There's nothing wrong with playing a BG 7 vs 7, or 3 vs 4, or an AV with 29 vs 32.

The battlegrounds should only end early if one team heavily outnumbers the other team, like 15 vs 4, or 1 vs 3.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, it's a configurable setting we can adjust and we'll look into it for the Sunstrider realm.
