### ISSUE TITLE
can't shift after completing druid epic flight form quest

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4706]
killed anzu flew to zangarmarsh, turned in quest vanquish the raven god (while in flight form).  Got the follow up quest, turned that one in too, got another turned that one in as well.  After doing all the turn ins, started flying around to see the new speed improvement, wasn't applied.  Tried to shift out of flight form, got message "you are in shapeshift form".  

Tried to shift into moonkin, travel, cat same error message (I may have been flying so this may be invalid for boomkin/cat/bear attempts, but you should be able to shift in and out of flight form mid air for sure.).

Landed near a mob, moonfired it which pulled me out of flight form...  could then shift in and out of flight form with no problem (even while flying which is normal as well)

**Comment by lucashawks** [comment]
x2 the same here!

**Comment by kelno** [comment]
Thanks for reporting.
I can't reproduce this, I don't know what quests you're referring to either with that second follow up.
First one is " vanquish the raven god", second one is "Eternal Vigilance"? Then third one?
