### ISSUE TITLE
Zul'Gurub, Bloodlord Mandokir Eyes on you

### ISSUE THREAD

**Issue by lucashawks** [ValorenWoW/sunstrider-core#4707]
**Describe the bug**
The eyes on you one shot you too if you don't generate aggro at the moment.
**Character name**
Bestdudu
**To Reproduce**
Cast Eyes on you
you do nothing
he kill you

**Screenshots/videos**
https://prnt.sc/105bfut

**Comment by michaelkittrell** [comment]
had a similar experience... nearly 1 shot without doing anything.

los seemed to work though.  

not sure what the "correct" behavior is, was always told just stop all action until its over.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
