### ISSUE TITLE
[CORE] [Spell] [Priest] Vampiric Embrace does not heal if the spell invoker is in LOS towards party members

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4708]
Reproduction:

1) Apply dots and vampiric embrace on a target.
2) Healing starts, for both yourself and your party members.
3) Move your party member 1 in line of sight (behind pillar)
4) Healing stops when your party member 1 is in LOS to you (not to the enemy target that has vampiric embrace applied)

Expected: Healing shouldnt stop

E: Just to make it more clear - it stops healing the party member 1 who is in los to you, it doesnt stop healing yourself. The whole vampiric embrace handling seems to be hard-tied to the priest in all of its aspects, it shouldnt be.

**Comment by Jerrythemagicdog** [comment]
In case there's any doubt, retail: https://youtu.be/Fv_CJDCmGO8?t=266
The party member (Rogue) is downstairs behind the big pillar blinding the druid, ticks of healing can still be observed on his frame
from the Vampiric Embrace on the Warlock that the Priest is dealing damage to. This is visible when the Rogue comes back into the frame later from behind the pillar so there's no doubt as to where he was and that he was not in LoS of the Priest.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
