### ISSUE TITLE
[CORE] [Spell] [Priest] Shadow Word: Death backlash damage doesnt count towards Damage treshold for CC break

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4709]
Reproduction:
Cast fear on shadow priest, have the fully dmg stacked shadow priest swd into end of the cast. Fear continues even tho the priest received 1500 backfire damage. It never breaks.

If I compare it to other similar damage that I cause, fear breaks almost INSTANTLY on this server, even with a single pet hit. However thats not the case with SWD.

Same applies to druid roots and other CCs that have a *chance* to break on dmg taken.

According to you own website: **"More consistent CC break rules."** https://endless.gg/changes You have one thing right there, it is consistent - it never does anything xd

**kinda gamebreaking**

E: The "issue" could be that swd backlash is treated as a dot and you have set extremely retarded amount of dot damage to break CC opposed to direct dmg

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
For a Discipline Priest with the starter gear from the Arena Realm the chance for a SW:D to break from e.g. Psychic Scream is around ~16%, for a Shadow Priest with more spell damage a bit higher.

**Comment by Evolvee** [comment]
This isnt just fear, its roots, frost nova etc...

And 1500 backfire dmg should be almost 100% guarantee to get out of such ccs.

**Comment by Jerrythemagicdog** [comment]
Yes, this is a general fix for all CCs that break on damage.
