### ISSUE TITLE
death release inadvertently pulls, works poorly with fast reset feature

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4711]
when you ress, you stand up at your corpse for a split second before being released to graveyard.

with fast reset, if 24 people take the fast reset ress... and one person is late and releases under boss feet, you can agro the boss again.

happened a couple times on twins swp.

a little weirdness with priests in angel form as well, you get an enter combat message but it clears quickly.

also some ground effects like the twins blazes may be on ground at the designated reset point (persisting past boss reset) causing problems/pointless deaths.

**Comment by kelno** [comment]
Thanks for reporting, I'm applying some fixes for tonight

**Comment by kelno** [comment]
Should be fixed now
