### ISSUE TITLE
'Unbreakable Will' has no effect on silence or fear effects.

### ISSUE THREAD

**Issue by lucasss18** [ValorenWoW/sunstrider-core#4712]
**Describe the bug**
The Priest Talent 'Unbreakable Will' has no effect on silence or fear effects.

**To Reproduce**

1. Cast Silence/Psychic scream on Priest target with unbreakable will
2. repeat
3. observe 0% resist

I tested it against improved counterspell, silence, improved kick, psychic scream.

Talent:
https://db.endless.gg/?spell=14791

**Expected behavior**
"Increases your chance to resist Stun, **Fear, and Silence effects** by an **additional 15%**."

**Comment by Jerrythemagicdog** [comment]
That's true for the Arena Realm: https://github.com/SunstriderEmu/BugTracker/issues/4680

**Comment by Evolvee** [comment]
WHO wanted such change? Noone asked, literally, unless there is some random RM player in your team not being able to get to weps...with the server already being custom tuned to heavily favor melees over everything else...

**Comment by Evolvee** [comment]
Bump
