### ISSUE TITLE
bt, illidari nightlord pack agroing weirdly.

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4713]
BT, ILLIDARI night lord pack that patrols towards ROS/bb

recently has started agroing funny.   for example if you kill the 2 stalkers in front of the door to bb/ros and the raid is sitting there waiting for the nightlord to path back he gets around the mother door area and one or both of his adds will teleport/rogue gap close in at approximately 80-100 yard range (way way farther than normal body pull range).  

in one raid we had not previously agro'd this pack.

another weird thing that may or may not be related is if you wipe on this pack the 2 demon adds sometimes appear near the door to ros/bb and the illidari nightlord paths by himself until he reaches them and then they relink and patrol together.  (this has been a thing for months pretty sure)

saw this last week in my na guild and again today in my eu guild.  we often wait here for that patrol, so pretty sure this is a newish bug.

**Comment by michaelkittrell** [comment]
raid was standing roughly where todac is, nightlord pack agro'd from roughly where the red star is

![image](https://user-images.githubusercontent.com/5479930/109207758-b90df000-7766-11eb-845c-c660b33fbbfc.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
