### ISSUE TITLE
Level cap on AH did not work

### ISSUE THREAD

**Issue by Bboper** [ValorenWoW/sunstrider-core#4714]
When placing in the level range on the AH it didn't work and displayed all level ranges
Bboper

1. Go to any auction house ( the one i encountered it on was silvermoon)
2. Type in a low level range (i did 0 to 16)

The auction house will show all levels not the one you placed it at

**Comment by Jerrythemagicdog** [comment]
Thanks, 0 should correct to 1 in that case, if you use 1-16 it works just fine though.
