### ISSUE TITLE
Troll Berserking

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4715]
**Describe the bug**
The buff consists of one percent modifier (1.1 - 1.3) instead of two — base (1.1) and health-based (1.0 - 1.3).

**Expected behavior**
> source: [r/classicwow Troll Racial stacking buffs? - comment by Serasangel](https://www.reddit.com/r/classicwow/comments/cew2qp/troll_racial_stacking_buffs/eu6c7ue/)
Berserking just always gives you 1,1 and additional 1-1,3 (which ends at 1,43 on the lowest health scenario if those 2 are the only sources)
so with RF a 15 % quiver, quick shots and a low health berserking you could put Ashjrethul from 3,4 down to 1,14 weapon

> source: [Hunter Guide by Lactose <Cráb People>](https://web.archive.org/web/20080913174038/http://hunterguide.wikispaces.com/Theorycraft#GeneralHaste)
There is an exception to the above - the Troll racial Berserking. A x% Berserking haste works like this:
HastedSpeed = WeaponSpeed*(1 - x%)
This can be rewritten into:
HastedSpeed = WeaponSpeed / (1 / [1 - x%])
So, using a 2.9 weapon, with a 15% quiver and 30% Berserking active:
HastedSpeed = 2.9 / ([1 + 15%] * [1 / (1 - 30%)])
HastedSpeed = 2.9 / (1.15*[1/0.70])
HastedSpeed = 2.9 / (1.15*1.42857)
HastedSpeed = 1.77

> source: [r/classicwow Troll Racial stacking buffs? - comment by Superstate](https://www.reddit.com/r/classicwow/comments/cew2qp/troll_racial_stacking_buffs/eu5q0b9/)
It is less complex than you think. The 43% is derived from Berserking effectively applying TWO buffs: one 10% base increase that is always applied, and then another 0-30% based on health lost from 100% to 40% current health. The maximum gain is therefore 1.1 * 1.3 = 1.43.

> source: [r/classicwow Berserking - comment by fusionpit](https://www.reddit.com/r/classicwow/comments/it9k90/berserking/g5depwn/)
This depends on whether you are a Rogue/Warrior or a Caster.
**For Rogues and Warriors**, the amount of haste is linear between 10% haste @ 100% hp and 30% haste at 40% hp: -0.33333333333333x+43.333333333333 where x is your % hp.
**For casters**, you actually get between 11.11112% haste @ 100% hp and 42.85715% haste @ 40% hp: 30044.98364/(x+170.1741257)-100.0955843 is a very close approximation, where x is your % hp.

> source: [r/classicwow How does haste work in classic wow? - comment by Calindromeda](https://www.reddit.com/r/classicwow/comments/cjjcee/how_does_haste_work_in_classic_wow/eve5pq4/)
if the values are based on troll berserking haste then thats where youre getting confused. thats 10%-43% because the first 10% is base and the rest is is a roll from 0%-30%. So itd maxed out at Wpn speed / (1.101.3). So with numbers youd get 2.7 / (1.11.3) = 1.88. So the tldr is that troll berserking tooltip is shit and you actually get a 10% base haste and then a second roll on the next haste value

> source: [wowhead Berserking comment by admielke on 2012/06/14 (Patch 4.3.4)](https://www.wowhead.com/spell=26297/berserking#comments:id=922851:reply=549790) [cataclysm]
If your spell is 2.0 and you have 20% haste from gear that would make it 1.6. If you use Berserking then you'll have it changed to 1.28 and if you had Bloodlust then it would go from 2.0 to 1.2 (Bloodlust is counted first), and using Berserking makes 1.2 to 9.6 second cast. In short: Berserking takes your finished spell (after gear and buffs) and reduces it by 20%.

> source: [r/classicwow Troll or Orc hunter in TBC? - comment by MwHighlander](https://www.reddit.com/r/classicwow/comments/jxckx7/troll_or_orc_hunter_in_tbc/gcvocsr/)
Berserking tooltip is still broken in TBC.
It grants both 10% spell and cast speed, plus up to 30% more stacking multiplicity with itself at 40% health remaining...
... granting 10% spell and cast speed at full health, linearly up to 43% more cast and attack speed at 40% health or lower.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
