### ISSUE TITLE
The Tower of Althalaxx

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#4717]
https://db.endless.gg/?quest=1140

The quest in the above link is not available to obtain for the minimum level requirement of 13.

Could you please kindly fix the level requirement to minimum lvl 13.

Please ensure the remaining quests in the entire questline are all minimum lvl 13.

Many thanks for your efforts.

**Comment by Sheikthecatman** [comment]
Thanks! [1140](https://db.endless.gg/?quest=1140) and [1167](https://db.endless.gg/?quest=1167) had the wrong level requirements.
