### ISSUE TITLE
Vengeance procc chance on absorbing shields is 100%

### ISSUE THREAD

**Issue by lucasss18** [ValorenWoW/sunstrider-core#4718]
**Describe the bug**
When the paladin hits a target that absorbs the damage the talent Vengeance proccs even without critting the target.

**To Reproduce**

1. Hit a a target with absorb damage shield up
2. make sure it didnt crit
3. observe vengeance proccing 

Spell: https://db.endless.gg/?spell=20059

**Expected behavior**

"Gives you a 5% bonus to Physical and Holy damage you deal for 30 sec **after dealing a critical strike from a weapon swing, spell, or ability.**  This effect stacks up to 3 times."

It is not supposed to procc from normal swings on absorb shields without critting.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
