### ISSUE TITLE
Tome of Valor - cannot re pick up

### ISSUE THREAD

**Issue by westlakem** [ValorenWoW/sunstrider-core#4721]
**Describe the bug**
Accidently destoryed tome of valor from my bags.  Cannot pick up the quest again from Brother Sarno

**Character name**
Nightbeast

**To Reproduce**

1. Talk to Brother Sarno on a level 20 paladin
2. Delete the tome out of your bag without accepting the quest it gives you

https://tbcdb.com/?item=6776

**Expected behavior**
should be able to pick up another tome

**Comment by Jerrythemagicdog** [comment]
You don't need to complete the quest, you'll receive Ressurection through autolearn.
If you want to complete the quest though, open a ticket in game and a GM will restore the Tome for you.
