### ISSUE TITLE
No Teleport: moonglade for druids

### ISSUE THREAD

**Issue by trickdaemon** [ValorenWoW/sunstrider-core#4722]
**Describe the bug**

Teleport moonglade is not trained at level 10 nor by doign the quest that requests you to ues teleport moonglade. 
**Character name**

Trickdaemon
**To Reproduce**

Confirmed by other druids by the NPC in Darnassus

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=
https://db.endless.gg/?spell=18960
**Expected behavior**

expected it to be learned
**Screenshots/videos**

![image](https://user-images.githubusercontent.com/79805241/109428465-40f13580-79c5-11eb-9c22-294c904f745a.png)

**Additional context**

Thank you

**Comment by trickdaemon** [comment]
Also cannot learn Aquatic form at 16

**Comment by trickdaemon** [comment]
Update: aquatic form was trained at 26 not 16 as intended (received ingame mail saying 16th level aquatic form) - still no moonglade tele

**Comment by trickdaemon** [comment]
Maybe I should make another post but I don't want to spam...


Energy ticks are bugged in cat form, you lose a full energy tick when you powershift which kinda ruins feral dps as a spec :(


Thank you, I can try to take pictures to demonstrate this if needed.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
