### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by yelloworc** [ValorenWoW/sunstrider-core#4725]
**Describe the bug**
I've looked in all the possible sections in the keybind menu and yet i cannot find the "interact with mouseover" or "interact with" keybinds anywhere. Is this not available at all or will it be implemented at any time?

**Character name**
Quorra

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
That's not something we control, we don't modify or patch the client in any way, sorry!
The game client comes as is from its 2008 version.
