### ISSUE TITLE
Warlock Pets loosing their spells

### ISSUE THREAD

**Issue by Notfrank1** [ValorenWoW/sunstrider-core#4728]
Hello,

My warlock is lvl 41 and while leveling my imp have had bloodpact aswell as my voidwalker have had his aggro spell.

They are now gone and can't be casted / seen / found.

I have seen my pet trainer to try learn new spells, but I can't since my pets allready "know" these spells.

I have uninstalled my addon pack, still can't find the spells.

The spells are simply removed from my pet bar and conserning several pets.

I would guess the problem came up when lvl 2 of named pet spell should have been learned automatically. 

Best regards,
Notfrank.

**Comment by Dschever** [comment]
Open spel book, they are here.
 After update client, auto-learn spel delet old demon spels. They need add again.

**Comment by Notfrank1** [comment]
Hello, 

To be clear with you, it's not fixed. This is not concerning me summonig my pets. It's not the warlock spells, but the spells my pet have.

When I summon my pet, he (as in my void walker and imp) are missing spells. Blood pact for example can not be casted or found, and also it can't be learned since it is allready auto learned.

Also blood pact along with the other spells my pets have are not within my spell book, they never have been.

Best regards,
Notfrank
