### ISSUE TITLE
Treant Muisek

### ISSUE THREAD

**Issue by Qizzli** [ValorenWoW/sunstrider-core#4730]
**Describe the bug**

When using the Treant Muisek Vessel on a dead Wandering Forest Walker, no quest progress is gained.
**Character name**

Blessings
**To Reproduce**

1. Get quest Treant Muisek
2. Kill Wandering Forest Walker
3. Use quest item

Item: https://classic.wowhead.com/item=9606/treant-muisek-vessel
Quest: https://classic.wowhead.com/quest=3126/treant-muisek

**Expected behavior**

Quest progress to be gained.
**Screenshots/videos**

https://streamable.com/wbvl3z
**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
I've just attempted to reproduce and the quest works using the same steps.
Perhaps you were in a raid group or your addon doesn't update the progress correctly.
Edit: from the video attached maybe actually your bags were full.
