### ISSUE TITLE
Seal of vengeance isn't procing additional damage on attack.

### ISSUE THREAD

**Issue by westlakem** [ValorenWoW/sunstrider-core#4731]
**Describe the bug**
In patch 2.2 SoV applied additional damage when you applied the DoT after 5 stacks had been applied
![image](https://user-images.githubusercontent.com/4505074/109601083-44cba780-7aec-11eb-9228-74967a973bd5.png)

After attacking a target dummy for about 5 minutes, the DoT damage worked, but there was no additional damage applied after 5 stacks were reached.

![image](https://user-images.githubusercontent.com/4505074/109601250-7e9cae00-7aec-11eb-94bb-c4c55efa6d93.png)
Those 20 "Holy Vengeance" are applications that got resisted.

![image](https://user-images.githubusercontent.com/4505074/109601327-a3912100-7aec-11eb-9015-99af25d06489.png)

This is backed up by the in-game combat log.

**Character name**
Nightbeast

**To Reproduce**

1. Level a paladin to 64+ (to get SoV)
2. Go to Stormwind and attack a target dummy, keeping the seal of vengeance seal active.
3. Notice there is no additional damage after 5 stacks are applied.

https://tbcdb.com/?spell=31801
https://wowwiki-archive.fandom.com/wiki/Seal_of_Vengeance

**Expected behavior**
Seal of Vengeance should do additional damage when it is applied and there are already 5 stacks on the mob.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the fix will be live with next update.
Damage is set to equivalent of a tick of 5 stacks of the DoT for now, will need a source on this to confirm what it actually should be.

**Comment by westlakem** [comment]
@Jerrythemagicdog I can confirm that SoV is now adding damage on each attack.  I have not been able to find any resources that state how much that damage should be though.

**Comment by kelno** [comment]
Closed this then, if someone has information on the correct value you can make a new issue
