### ISSUE TITLE
Arelion's Mistress Scroll Possible Issue

### ISSUE THREAD

**Issue by Rosnarr** [ValorenWoW/sunstrider-core#4732]
**Describe the bug**
You can use the Carinda's Scroll of Retribution on the quest Arelion's Mistress to turn and allied player into a rat. It's mostly harmless, unsure if it's intended.

**Character name**
Rosnarr

**To Reproduce**

1. Finish the Chain to reach Arelion's Mistress
2. Target an Allied player with the scroll and cast it
3.  Squeak, squeak. 

Item: https://www.wowhead.com/item=23693/carindas-scroll-of-retribution
Quest: https://www.wowhead.com/quest=9472/arelions-mistress

**Expected behavior**
You are meant to use the scroll on Viera Sunwhisper to achieve revenge.

**Screenshots/videos**

**Additional context**
You can either intentionally or unintentionally turn an ally into a rat, which can be a bit disruptive and wastes the item, requiring a repeat

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
