### ISSUE TITLE
I was a lot of things...

### ISSUE THREAD

**Issue by TobiasThoren** [ValorenWoW/sunstrider-core#4735]
**Describe the bug**

Quest name: I was a lot of things...
Shadowmoon tuber mounds don't disappear when dug up. You have to guess when they have truly respawned. There are also only 5 mounds available in total. Approximately 2 min respawn rate.

**Character name**

Freak - Windrunner

**To Reproduce**

1. Call boar to a mound.
2. Pick up tuber.
3. Mound still there, won't activate boar.

Item: 30356 https://tbcdb.com/?item=30356
Quest: I was a lot of things... https://tbcdb.com/?quest=10514

**Expected behavior**

Should be more mounds spawning randomly. They should disappear when dug up so you can see when they are picked.

**Comment by DaturoDewitt** [comment]
Also the activation is really inconsistent reaaaally would appreciate only having to get 1 or 2 Tubers instead of 10....

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
