### ISSUE TITLE
Warlock Fel Domination Not Working

### ISSUE THREAD

**Issue by Benzilla95** [ValorenWoW/sunstrider-core#4738]
**Describe the bug**
The Demo talent for Fel Domination isn’t working as intended. After activating the talent it should reduce the cost and cast time of your pet. Although, it doesn’t.

**Character name**
Benzilla - Windrunner

**To Reproduce**
Simply activate the Demo talent Fel Domination and try to cast any pet.

https://www.wowhead.com/spell=333889/fel-domination 

**Expected behavior**
After activating the talent it should reduce the cast time of your pet by 6 second and also make it cost 0 mana.

**Screenshots/videos**
Will add later if requested.

**Additional context**
Appreciate you taking the time to look at it and look forward too seeing it get fixed.

**Comment by Jerrythemagicdog** [comment]
The spell works, maybe you didn't have points in Master Summoner at that point.
As of 7:24 PM CET 3/3/2021 your character is specced into Affliction so I can't confirm anything further than that.
