### ISSUE TITLE
Prisoner of the Bladespire quest marker

### ISSUE THREAD

**Issue by NeonicSupersonic** [ValorenWoW/sunstrider-core#4739]
Opening cage with key (not quest item) during the quest makes quest marker (object?) placed on cage to fall (dead) on the ground, making quest to have incorrect position (below cage instead where model is above the ground) and impossible to complete without some 200iq shenanigans of farseeing this outcome and trying to click quest item below cage on the ground instead on obvious cage position.

**Comment by Jerrythemagicdog** [comment]
Thanks, size increased with the next update (still will require you to stand under the cage and use the whistle).
