### ISSUE TITLE
quest 9227

### ISSUE THREAD

**Issue by TheGreyMouser** [ValorenWoW/sunstrider-core#4741]
**Describe the bug**
https://classic.wowhead.com/quest=9227/superior-armaments-of-battle-exalted-amongst-the-dawn
Wowhead states 6 of each insignia needed, quest on endless says 30 of each.  

**Character name**
frostyjack

**To Reproduce**

accept quest in lights hope
2. 
3. 

Item: https://wowhead.com?item=
Quest 9227
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Clear Cache, displays 6 for me correctly.
