### ISSUE TITLE
Druid(cat) energy tick timer wrong

### ISSUE THREAD

**Issue by ImTheTree** [ValorenWoW/sunstrider-core#4742]
There is a "problem" that makes feral very bad in dps...

on windrunner, the energy timer resets every shapeshift/powershift. means when i powershift, i have to wait a second for the next energy  tick.
that nerfs the feral dps very hard, since u cant time ur powershifts to instantly have 60 energy after each powershift (powershifting right before the energy tick comes)

On sunstrider its working like it has to, energy ticks has **its own** timer, thats how it should work.

**How to reproduce:**
1. go in cat form
2. waste ur energy
3. powershift right before the next energy tick comes
4. look at the energy bar and realise u have to wait...

usually if u powershift right before the tick occurs, it should not reset the tick timer and u get 40 energy (from feral(resto) spec) plus 20 energy from the tick.

(btw i dont know if it got changed on sunstrider too after the release of windrunner, but some weeks ago, it was not like that.)

Please fix so feral doesnt feel clunky af^^

**Comment by trickdaemon** [comment]
Please see #4726.

**Comment by Jerrythemagicdog** [comment]
There's already an issue open about this suggestion.
