### ISSUE TITLE
Small amounts of damage do not proc ardent defender

### ISSUE THREAD

**Issue by NeonicSupersonic** [ValorenWoW/sunstrider-core#4744]
Ardent defender does not proc from small (below 100) damage attacks even when those attacks reduce paladin below 35% and fulfill proc requirements. Can be easily replicated with aoe pulling any low lvl dungeon.

**Comment by Jerrythemagicdog** [comment]
Ardent Defender is just a passive in TBC (like Molten Fury but for the Paladin).
