### ISSUE TITLE
Login unavailable

### ISSUE THREAD

**Issue by Nail5602** [ValorenWoW/sunstrider-core#4745]
**Describe the bug**

**Character name**
I can't sign in and start playing.

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

![image](https://user-images.githubusercontent.com/80048064/109971459-589f2580-7d07-11eb-9387-af55982b3325.png)
![image](https://user-images.githubusercontent.com/80048064/109971510-65bc1480-7d07-11eb-9668-948cc77b0b23.png)

**Comment by Nail5602** [comment]
Help me please! login: noskill5602

**Comment by Jerrythemagicdog** [comment]
Hello, please try following these steps:

> For anyone getting the "Login unavailable - Please contact Technical Support" error upon logging in, here is a fix.
> 
> First, close your game. This will not work if your game is open upon changing the Config.wtf file.
> Navigate to your client folder, open WTF, then open the Config.wtf file.
> 
> Locate the line SET realmName and make sure it is set to SET realmName "Windrunner"

**Comment by Jerrythemagicdog** [comment]
Hello, please try following these steps:

> For anyone getting the "Login unavailable - Please contact Technical Support" error upon logging in, here is a fix.
> 
> First, close your game. This will not work if your game is open upon changing the Config.wtf file.
> Navigate to your client folder, open WTF, then open the Config.wtf file.
> 
> Locate the line SET realmName and make sure it is set to SET realmName "Windrunner"
