### ISSUE TITLE
login

### ISSUE THREAD

**Issue by Nail5602** [ValorenWoW/sunstrider-core#4746]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Hello, please try following these steps:
For anyone getting the "Login unavailable - Please contact Technical Support" error upon logging in, here is a fix.

First, close your game. This will not work if your game is open upon changing the Config.wtf file.
Navigate to your client folder, open WTF, then open the Config.wtf file.

Locate the line SET realmName and make sure it is set to SET realmName "Windrunner"
