### ISSUE TITLE
Skettis mob spawns are messed up on Windrunnder

### ISSUE THREAD

**Issue by buddykinman** [ValorenWoW/sunstrider-core#4747]
**Describe the bug**
Skettis mob spawns are all out of whack

**Character name**
Souperbolt

**To Reproduce**

1. Go to skettis lake in outland

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
