### ISSUE TITLE
Priest talent in discipline tree Unbreakable will seem to not work at all. Silence will never resist, nor does fears. 

### ISSUE THREAD

**Issue by Iretons** [ValorenWoW/sunstrider-core#4748]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Evolvee** [comment]
![image](https://user-images.githubusercontent.com/1942409/110053420-ad6b8c00-7d59-11eb-9d5f-74dc31dcdfca.png)

maybe this time the staff will actually give their 5Head take behind intentionally nerfing this talent, especially combined with the fact that any other change here requires NASA-level research on its **blizzlike** behavior :)))

**Comment by Jerrythemagicdog** [comment]
Only for Arena Realm: https://github.com/SunstriderEmu/BugTracker/issues/4680

**Comment by Evolvee** [comment]
And maybe not...

Still curious why you are constantly linking an open github issue that **HAS NOTHING TO DO** with the particular problem ppl are talking about here.
