### ISSUE TITLE
botanica, mobs near warpsplinter

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4750]
the pathing and movement of mobs near warpsplitner is pretty bad.  mobs frequently teleport to people anywhere near the bridge and even sometimes on the path to warp from the bridge.  you can see this by standing on teh bridge, heal a tank.  mobs will teleport to healer.  even pulling as tank half the mobs will pull the other half will do nothing then teleport in.  can also affect warp spliter's summoned mobs which is pretty unfortunate because some strategies rely on positioning warp so you can pick up the adds/blow them up.  botanica normal, both windrunner and sunstrider.

**Comment by kelno** [comment]
Fixed since
