### ISSUE TITLE
Game crashes when the highborne spirits attack me or get attackedevery time

### ISSUE THREAD

**Issue by SGTwizardfist** [ValorenWoW/sunstrider-core#4753]
I am trying to level and complete a quest in Darkshore and every time I get attacked or attack or someone else attacks a highborne spirit my game crashes giving me an error
![75622136-c77cf800-5b62-11ea-98d3-faf4b6a50f3c](https://user-images.githubusercontent.com/17819402/110101504-75b01480-7d58-11eb-8827-25f5e98808ce.png)

I have tried clearing my cache and I looked at a previous post that had the same issue but I saw that it was open and never solved, I am stuck in the area since I am surrounded by spirits and any help would be appreciated.

**Comment by Jerrythemagicdog** [comment]
Download a new client, there's no other solution to this, your game files are corrupted.
