### ISSUE TITLE
weird pet pathing

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4754]
near slabs, moving slight forward from this spot and standing still...  causes pet to climb into the sky in a series of steps until hes not visible anymore.

![image](https://user-images.githubusercontent.com/5479930/110153453-4cb37200-7da0-11eb-8550-964fb1e9cb18.png)

**Comment by michaelkittrell** [comment]
![image](https://user-images.githubusercontent.com/5479930/110153603-83898800-7da0-11eb-8acb-9757a9a11a64.png)

**Comment by z5n** [comment]
unable to reproduce
