### ISSUE TITLE
PLEASE HELP ME

### ISSUE THREAD

**Issue by klewdo** [ValorenWoW/sunstrider-core#4755]
i log into my character and it just says 'error retrieving character list' 

please help me i dont want to lose my toon. It seemed to have bugged out just after i activated duel spec on the endless.gg website i dont know if thats relevant.

'De' is my charcter name 

server is windrunner

![errror1](https://user-images.githubusercontent.com/80130216/110175365-96519a80-7e3c-11eb-8001-87daa4a7aafd.PNG)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Looks like you've resolved your issue judging by the last time you've logged in.
Do you remember doing anything specific?

**Comment by klewdo** [comment]
i have not resolved my issue im still stuck at the 'Error retrieving character list' message
prior to this happening i changed my spec with the duel spec feature online and i got kicked from the game and i havent been able to get back in since

**Comment by Jerrythemagicdog** [comment]
Okay, we're looking into it, thanks.

**Comment by klewdo** [comment]
thankyou!

**Comment by Jerrythemagicdog** [comment]
Could you try again?

**Comment by klewdo** [comment]
still the same error message :(

**Comment by Jerrythemagicdog** [comment]
Okay, how about now?

**Comment by klewdo** [comment]
same result. i had my friend to attempt log in on my account to rule out whether or not it was an issue on my end but he had the same result too.

**Comment by Jerrythemagicdog** [comment]
Okay, let's move this conversation to Discord, it will be much easier: Jerry#9132

**Comment by klewdo** [comment]
thanks jerry youre a king for helping!
