### ISSUE TITLE
Random Enchantment vendor items.

### ISSUE THREAD

**Issue by Cxstom** [ValorenWoW/sunstrider-core#4758]
The random enchantment is not generated in vendors and you get the blank item.

Synon

**To Reproduce**
1. Go to an NPC with random enchantment vendorable items.
2. Buy the item.
3. Get scammed by the spaghetti code.

Item: https://classic.wowhead.com/item=6565/shimmering-gloves

**Expected behavior**
The item should be generated with a random enchant, at the moment you pay for an item that ends up being this: http://prntscr.com/10e1cbj
http://prntscr.com/10e1cqj

**Comment by kelno** [comment]
Vendor: https://db.endless.gg/?npc=3572

**Comment by kelno** [comment]
Thanks, fixed with next server update
