### ISSUE TITLE
Distraction at Manaforge B'naar

### ISSUE THREAD

**Issue by justismce** [ValorenWoW/sunstrider-core#4760]
**Describe the bug**
Quest: Distraction at Manaforge B'naar is not being offered by Exarch Orelis.

**Character name**
Joheed

**To Reproduce**

1. Accepted the quest: Off to Area 52
2. Turned in quest: Off to Area 52
3. Accepted quest: You're Hired!
4. Exarch Orelis offers 0 quests.

Quest: https://www.wowhead.com/quest=10241/distraction-at-manaforge-bnaar

**Expected behavior**
Orelis should offer the quest: Distraction at Manaforge B'naar

**Screenshots/videos**

![exarchorelis](https://user-images.githubusercontent.com/80149939/110201265-2f2de900-7e30-11eb-8859-c47ee4cf837c.png)

**Additional context**
My character, Joheed, is allied with the Aldor.

**Comment by Jerrythemagicdog** [comment]
You need to be Friendly with the Aldor in order to pick up that quest chain.
Since you're a Blood Elf you start at Friendly with the Scryers and lower reputation with the Aldor.
After completing City of Light you're only at Neutral with the Aldor which results in you not being able to pick it up.
