### ISSUE TITLE
Bugged Quest - Dont Kill the Fat One

### ISSUE THREAD

**Issue by papagungun** [ValorenWoW/sunstrider-core#4763]
**Describe the bug**
the quest Dont Kill the Fat One  Boulderfist Invader slain (10), Unkor Submits
I am able to get Unkor the Ruthless to submit and i get a notification on the screen, but the quest log is not updated with the objective. i have relogged, restarted, and abandon the quest several time and still dose not work

**Character name**
Papagungun

**To Reproduce**
1. Pickup the quest at level 70 from Kilrath in the Terokkar forest
2. kill 10 Boulderfist Invader's
3. attack Unkor the Ruthless

Quest: https://wowhead.com?quest=9889/dont-kill-the-fat-one

**Expected behavior**
Unkor the Ruthless submits he dose not die but quest task is not updated

**Additional context**
i am not the only one to have this issue

**Comment by Jerrythemagicdog** [comment]
https://www.wowhead.com/quest=9889/dont-kill-the-fat-one#comments:id=26543
Kill the 10 ogres first, then beat Unkor.
Thanks for the issue!
