### ISSUE TITLE
Kara mob spawn timer

### ISSUE THREAD

**Issue by Trigonsz** [ValorenWoW/sunstrider-core#4765]
When we were clearing Karazhan the mobs have a spawn time of 10 min, so when we were trying to kill the boss the trash mobs aggro us and we wipe. 

Pames 

To Reproduce
 
1. Kill trash
2. Trash respawn after 10 min
3. and wipe

Expected behavior
Should take 2 hours to respawn

**Comment by Trigonsz** [comment]
Please fix this very annoying, been wiping for 2 hours on boss because boss respawns behind and we aggro it, then we have to re clear trash mobs again. very sad ;(

**Comment by Godmatik** [comment]
Which trash specifically? The trash before Attunmen has a very quick respawn and that is blizzlike.

**Comment by Trigonsz** [comment]
> 
> 
> Which trash specifically? The trash before Attunmen has a very quick respawn and that is blizzlike.

Yes the trash right before attunmen has like 7-10 min respawn and is that supposed to be like that?

**Comment by Godmatik** [comment]
Yes that is correct, Blizzard intentionally increased the respawn times of those specific trash mobs. We don't know why, but it is blizzlike.

Not a bug.
