### ISSUE TITLE
Rogue Gouge bug

### ISSUE THREAD

**Issue by Durial123** [ValorenWoW/sunstrider-core#4767]
**Describe the bug**
Simply put the bug is when you gouge a monster and run away, when the duration of gouge runs out the mob gets a hit on you no matter the distance between you and the mob

**Character name**
Durial

**To Reproduce**

1. Cast gouge on a mob
2. run away from the mob while gouge incapacitates them
3. note location of the mob and when the first attack hits you

**Comment by Jerrythemagicdog** [comment]
It was the last attack that was dealt to you as the Gouge landed, no damage is actually dealt to you.
You can observe that by watching your HP bar.
