### ISSUE TITLE
Pet on passive prevents its auto-casts

### ISSUE THREAD

**Issue by ujellyx** [ValorenWoW/sunstrider-core#4768]
**Describe the bug**
Having the pet on passive (only tested on Hunter so far), the pet doesn't always use the abilities that are on auto-cast, especially Growl. If you toggle the auto-cast during combat it works fine for the fight - until the next mob.

**Character name**
Xqt

**To Reproduce**
1. Enable passive on pet and enable auto-cast on Growl.
2. Send pet into combat.
3. Pet doesn't use Growl.

**Expected behavior**
Pets should use the auto-cast abilities no matter the mode they're in.

**Comment by kelno** [comment]
I can't reproduce this, maybe this is:
https://github.com/SunstriderEmu/BugTracker/issues/3594 ?

Closing for now as I believe this is the case. I'll reopen if new input is given.
