### ISSUE TITLE
Felblood Fillet fishing daily

### ISSUE THREAD

**Issue by EvilRocki** [ValorenWoW/sunstrider-core#4769]
**Describe the bug**
Felblood Fillet fishing daily quest:
You need to fish in the green lava pools in SMV, but this does not seem to work.
I can use the fishing skill, and the cast bar begins, but there is no fishing line or bobber.
The quest can be finished by fishing in the Pools of Aggonar in Hellfire.

**Character name**
Shocci

**To Reproduce**

1. Cast fishing in a lava pool in SMV

Quest: https://www.wowhead.com/quest=11669/felblood-fillet#comments

**Expected behavior**
Fishing in lava should be possible and always give grey fish (Felblood Snapper) and while on the daily quest, the quest fish (Monstrous Felblood Snapper).

**Screenshots/videos**
Didn't take any since reproducing is extremely simple.

**Additional context**
none

**Comment by z5n** [comment]
unable to reproduce
