### ISSUE TITLE
Issue 2565 posted in March of 2020 is still an issue. Fish will show up in the lootable box then disappear. 

### ISSUE THREAD

**Issue by mjk6994** [ValorenWoW/sunstrider-core#4770]
https://github.com/SunstriderEmu/BugTracker/issues/2565

Also, quite often when right clicking after the caught animation happens, it will say fish got away, even when you right click it and a fish shows up lol.

**Comment by kelno** [comment]
Thanks for reporting and bringing attention to it again, closing this one since this is already reported
