### ISSUE TITLE
Fish getting away more often than normal, and loot disappearing. 

### ISSUE THREAD

**Issue by mjk6994** [ValorenWoW/sunstrider-core#4771]
**Describe the bug**
Fish getting away more often than normal, and loot disappearing. 

**Character name**
Itsred

**To Reproduce**
Fish.

**Expected behavior**
Being able to loot your fish.

**Screenshots/videos**
https://vimeo.com/520555058

**Additional context**
Issue with it happening before: https://github.com/SunstriderEmu/BugTracker/issues/2565

**Comment by kelno** [comment]
Do you have some addons here that might close the window? I can't reproduce this in my setup.
