### ISSUE TITLE
eots, dead no option to revive

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4777]
eots, sometimes when you die (and probably because opposite faction takes that graveyard and the other 3 towers are capped) you don't get tp'd to the only other avialable gy for ress (starting location).

**Comment by kelno** [comment]
Alright, it didn't happen in my test but I heard about this from other players as well, any more detail is welcome.

**Comment by Jerrythemagicdog** [comment]
Issue has been fixed since then.
