### ISSUE TITLE
Power Word: Fortitude buff tooltip bug

### ISSUE THREAD

**Issue by Llwydy** [ValorenWoW/sunstrider-core#4778]
When you have the Improved Power Word: Fortitude Talent, although the spell tooltip displays the buff correctly, the buff tooltip doesn't. Note that although I don't have screenshots of it, it also displays incorrectly on other players.

Currently a L23 priest with two talent points in Improved Power Word: Fortitude

![WoWScrnShot_030721_193737](https://user-images.githubusercontent.com/80220742/110252389-0cf5b180-7f7d-11eb-8568-32a759f819ff.jpg)
![WoWScrnShot_030721_193741](https://user-images.githubusercontent.com/80220742/110252393-0e26de80-7f7d-11eb-97bc-c2b7a8199aad.jpg)

**Comment by michaelkittrell** [comment]
a lot of the buffs/spells that are castable on low level players scale down.  

is that what you are talking about?  or did you expect to get 1000 hp buff on a level 23?

**Comment by Llwydy** [comment]
No, the tooltip says 10 stamina (which is correct) and the buff says 8 stamina (just like in the screenshots). It’s purely a visual glitch. It still gives the stamina though, the buff tooltip just isn’t displaying the extra 30% stamina increase that the talent gives. Not that big of a deal.

**Comment by Jerrythemagicdog** [comment]
The tooltip doesn't update as is the case for many talents with the old client.
You can notice the talent works by checking your stats before and after the talent.
