### ISSUE TITLE
windrunner, auto-skill, paladin, greater blessing of kings

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4779]
for some reason my paladin didn't get gbok from the auto skill leveling thing.  it could be because i didn't spec into it until after i was already 70?  upon dualspec/respec still didnt get it.   havent been to trainer, but seems odd.

**Comment by Jerrythemagicdog** [comment]
Yes, that's why autolearn only triggers on levelup.
