### ISSUE TITLE
spellstrike hood and pants much lower drop rate as compared to any other pattern?

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4780]
spellstrike hood and pants much lower drop rate as compared to any other pattern?

is this really intentional?  whitemend drops frequently, the kara enchants as well.  not sure why spellstrike hood/pants are so so so low.

same was true on sunstrider, but really makes no sense on windrunner.

**Comment by Jerrythemagicdog** [comment]
It was updated last update to 10%.
