### ISSUE TITLE
Mob threat table / aggro bug when attacking opposite faction

### ISSUE THREAD

**Issue by Sorisx** [ValorenWoW/sunstrider-core#4783]
When you attack and kill a player of the opposite faction while he has aggro of a mob, threat is transfered to you instead of mob resetting after player deat. Happened on multiple occasion, so I'm sure it's not a proximity from reset spot issue.
To reproduce, get aggro from a mob, have someone of the opposite faction kill you, and you'll notice that the mob won't properly reset and start to attack you even if you haven't generated any threat towards it.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Not how it works unless you're near the creature's home, it resets and aggroes on to you immediately, which it can do at any point if not engaged.
There's no threat sharing or passing happening.
