### ISSUE TITLE
alchemy 20 hr cooldown instead of 12 hr

### ISSUE THREAD

**Issue by chudzi** [ValorenWoW/sunstrider-core#4784]
my alchemy transmute CD on windrunner is still 20hrs why? 

so initially i deleted my ache and relog out and in first few times it works. (12hr cd)

however now everytime i transmute i get 20 hour cd even if i delete the cache and log out and in.

please tell me how to fix this?

is the transmute only for primal might or does it work on diamonds too?
![alchemy cd](https://user-images.githubusercontent.com/65384720/110267053-f2d8c500-7fb6-11eb-93d8-8511896b312b.png)

**Comment by Jerrythemagicdog** [comment]
Relog and don't delete your Cache.
