### ISSUE TITLE
warlocks pet losing abilities

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4788]
my son is leveling a warlock and he said his pet has been randomly slowly losing abilities for like the last 10 levels (26-36).  He logged out/relogged in and summoned an imp/dimissed summon again, pet has 0 abilities.  An imp that literally has no firebolt, runs into melee range and slaps a mob if sent to attack.  blueberry has lost taunt ability, felhunter has no abilities.  they had abilities at one point but just slowly over time permanently lost their abilities.  

he hasn't respec'd or anything.   he is using the endless wow download with elvui and questhelper.

charname bagisapurse, windrunner

**Comment by Jerrythemagicdog** [comment]
They're in your Spellbook, Pet tab.

**Comment by michaelkittrell** [comment]
thanks!
