### ISSUE TITLE
pet despawn/recall distance

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4789]
**Describe the bug**
Pets can chase an enemy much further, from the master, than they should be able to.  
Currently warlocks are abusing this (maybe not intentionally) in combination with #4772 .

**Expected behavior**
Hunter pet should despawn at roughly 60 yards distance from the hunter.  
https://www.youtube.com/watch?v=ztEqxr9gnp8&t=63s  
Not sure how a warlock pet should behave. Probably gets recalled at the same distance.

Sunstrider rev. 30986 (835bd5487be4)

**Comment by ghost** [comment]
bump!

**Comment by kelno** [comment]
Not sure of the detail here, it feels like on retail the pet just disappears when it gets out of sight range? While we have a longer range than retail. 
For now I've made a little change to make the pet being recalled if it gets further than 60y.

**Comment by ghost** [comment]
the problem is still present with shaman greater fire elemental and possibly other pets @kelno
