### ISSUE TITLE
The Fel and the Furious

### ISSUE THREAD

**Issue by Kadur2019** [ValorenWoW/sunstrider-core#4790]
**Describe the bug**

After completing the quest, the quest appeared as completed in the quest book but I couldn t validate it on pnj. I logged out, my character appeared as dead on the main screen and was actually dead in Wildhammer stronghold when logged in but no durability loss.
I tried to go back to the portal as ghost, couldn t take the portal. I ressed at graveyard and came back to green portal and couldn t take it either.
**Character name**

Xadwulf
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

- being able to validate the quest when it is completed.
- not dying from nothing.
- being able to take the portal again.
**Screenshots/videos**

**Additional context**

**Comment by InhumanGM** [comment]
Resolved in game
