### ISSUE TITLE
Completed quests showing up in Quest log

### ISSUE THREAD

**Issue by dmo90** [ValorenWoW/sunstrider-core#4791]
**Describe the bug**
Completed several quests last night and picked up some others
Now like 3 of the quests I completed last night are showing in my quest log again
I have some quests I picked up last night where the quest giver npc says i'm on the quest but it is not in my quest log

**Character name**
Danakin

https://www.wowhead.com/quest=10098/terokks-legacy
https://www.wowhead.com/quest=10285/return-to-andormu
https://www.wowhead.com/quest=9495/the-will-of-the-warchief

I completed these three quests last night but they are now in my log again
I'm literally wearing one of the quest rewards on my character right now
I have disabled all addons and issue persists

https://www.wowhead.com/quest=11096/threat-from-above
The quest giver npc says I am on this quest but it is missing from my quest log

**Comment by dmo90** [comment]
Yep it's letting me complete the quest twice, now I have 2 quest rewards from one quest

**Comment by Jerrythemagicdog** [comment]
Thanks for the details here!

**Comment by Jerrythemagicdog** [comment]
Fixed with next update - 9cbd5cc2d5ff1ec59643e2269e3bb197bbeb4f9b
