### ISSUE TITLE
Paladin still using blood elf charger after free faction change.

### ISSUE THREAD

**Issue by Ghost1six** [ValorenWoW/sunstrider-core#4793]
**Describe the bug**
After previously taking the free offer of a faction change from Horde to Alliance on the Windrunner server, my paladin is still riding the blood elf charger mount when casting the summon charger spell.

**Character name**
Hearthvader

**To Reproduce**

1. Cast Summon Charger

Spell: https://www.wowhead.com/spell=23214/summon-charger

**Expected behavior**
When summoning my charger mount, the color should be the Alliance gold and blue charger. 
I'm getting the copper and red charger of the Blood Elves.

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/80274110/110348067-4111b680-7fff-11eb-810d-aa9a23e84c26.png)

**Additional context**
This has only happened after using the free faction change from Horde to Alliance on the Windrunner server.
I have deleted my Cache>WDB folder and WTF folder and restarted the client.
I uninstalled the wow 2.4.3 client and permanently deleted the folder contents and reinstalled the client using the Endless.gg installer.

**Comment by Ghost1six** [comment]
I've confirmed that others in game also see the red charger, it isn't a client side issue.

**Comment by steak-house** [comment]
why would you even report this bug this is cool as shit

**Comment by kelno** [comment]
Thanks, fixed with next server update
