### ISSUE TITLE
SP, bite's quest (near quag)

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4795]
Naturalist Bite in SP ... does not seem to trigger his event/give the "boon to help you to deal with Quagmirron"

the cage opens, then nothing.  should spawn some mobs and i believe should give a group nature resist buff.

**Comment by michaelkittrell** [comment]
as i was running out, the mobs spawned basically on top of me.  so perhaps they spawn, they just aren't visible and don't come running like they probably should.  still didn't seem to get the buff.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
