### ISSUE TITLE
Drakefist Hammer Haste Buff Not Stacking

### ISSUE THREAD

**Issue by CeasefireShaman** [ValorenWoW/sunstrider-core#4796]
**Describe the bug**
When one dual-wields the Drakefist Hammers (crafted BoP epic maces), the haste proc does not stack. Instead, it renews. This is a bug, as it stacks with other haste procs, such as the one from the mace that drops in Shadow Labs.

**Character name**
Ceasefire

**To Reproduce**
1. Wield two Drakefist Hammers, attack target dummy, see that you get one constantly renewing one and not two separate procs, as you should get.

Item: https://www.wowhead.com/item=28437/drakefist-hammer?bonus=6883

**Expected behavior**
Each hammer has the chance to proc its own haste buff. What actually happens is that it just renews the duration over and over.

**Comment by Jerrythemagicdog** [comment]
From that same link:
https://www.wowhead.com/item=28437/drakefist-hammer?bonus=6883#comments:id=288739
