### ISSUE TITLE
Quest: Shutting Down Manaforge Ara, Turning Point

### ISSUE THREAD

**Issue by jstn4all** [ValorenWoW/sunstrider-core#4797]
**Describe the bug**

I finished the quest for shutting down Manaforge Ara, it was late so i went to bed. The next day i returned to the game and the crystal in my inventory was gone. I went back to Manaforge Ara, got the crystal again. I returned the Thalodien to turn in the quest and he would not accept it. I then dropped the quest, resigning myself to having to do it all yet a third time, but now Thalodien doesn't even have the quest for me to pick up again...  This has now also happened for another quest ive done: Turning Point" I have all the items in my bag, and cannot turn in the quest!!!

**Character name**

Zappy

Item: https://www.wowhead.com/item=29411/ara-access-crystal
Quest: https://www.wowhead.com/quest=10365/shutting-down-manaforge-ara#comments , https://www.wowhead.com/quest=10507/turning-point

**Expected behavior**

 I need items from this quest, i would like to be able to turn it in!!

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, can you provide your character name so we can check what's going on?

**Comment by jstn4all** [comment]
Added the name: Zappy
