### ISSUE TITLE
botanica, patrolling 2 pack of demons near 3rd boss.

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4799]
the patrolling 2 pack of demons near 3rd boss, the green one doesnt patrol with the red one... and comes when red one is pulled. sometimes the green one flys in like it was supposed to be pathing but it wasn't and the server updated its position or something so it just flies across to where its supposed to be.  it seems not quite correct.

**Comment by michaelkittrell** [comment]
the green one is often stationary on the far side of the ramp.  maybe its intended but the pathing or the updating seems wonky.

**Comment by kelno** [comment]
Thanks, fixed with next server update
