### ISSUE TITLE
Arena Vendor Duplicate

### ISSUE THREAD

**Issue by DirtySwampMan** [ValorenWoW/sunstrider-core#4800]
**Describe the bug**

Arena vendor Vixton Pinchwhistle in Area 52 seems to be duplicated. There is a 2nd model overlapping with the main one, but doesn't show its name. When you click on Vixton and the copy they have the exact same items but they are offering different arena point prices - stats on the items are the same so I don't believe this is intended.
Comparing Vixton to the arena vendor right beside him Evee Copperspring, they both offer the same items but Evee has 6 pages of items while Vixton has 5. This means there are a few items missing from Vixton, but I don't think this is as big of a deal as the duplicated vendor offering lower prices.
**Character name**

Kyln
**To Reproduce**

1. Go to Area 52 and look at arena vendor Vixton Pinchwhistle - you can see the idle animations are off sync to differentiate the models

https://www.wowhead.com/npc=20278/vixton-pinchwhistle
note this npc seems to have been placed specifically for this server - actual location is in Area 52 - Netherstorm

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, he's gone with the next update.
