### ISSUE TITLE
Ring of Blood questline bug

### ISSUE THREAD

**Issue by knifevsface** [ValorenWoW/sunstrider-core#4801]
Stuck on Rockdar the Sundered Lord quest, not receiving credit for the kill.
Abandoning and restarting the quest myself, or having another group member start the quest doesn't fix the issue.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
I would suggest clearing your Cache and trying again as many players have already successfully completed that chain with no issues.
