### ISSUE TITLE
Transmutation Mastery bugged

### ISSUE THREAD

**Issue by oHwned** [ValorenWoW/sunstrider-core#4802]
**Describe the bug**
So I noticed that the alchemy transmute had a 12 hour CD, which I assume is a feature being on Endless. Once i completed transmutation mastery it increased to 20 hours. So I paid 4 Primal Mights to increase my Cooldown timer.

**Character name**

oHwn

**To Reproduce**

1. Complete Transmutation Mastery Quest
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
