### ISSUE TITLE
Character  - secondary specialization spell missing

### ISSUE THREAD

**Issue by Pockejkamo** [ValorenWoW/sunstrider-core#4803]
Dear all,

for my secondary specialization I am missing one, or maybe more spells. Specifically I am missing the "totemic call" for my restoration specialization. For primary specialization, the spell is there.

I might be missing more spells, which I didnt noticed, could you please try to fix this and check the rest of the spells?

Character name - Pedro.

There is no behaviour to explain or show. The spell is missing and I would guess, that it has something to do with automatic spell learning during leveling, when I respected the talents few times.

Thank you

Jiri (Pedro)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Those spells are not missing, they're still in your spellbook.
If by missing you mean they're gone from your action bar then that's just a side effect of changing specializations.
You can use an addon like ActionBarSaver to make this process more convenient.
I've checked your character and you still know the spell.
