### ISSUE TITLE
[Druid] Omen of Clarity bug

### ISSUE THREAD

**Issue by Loitta** [ValorenWoW/sunstrider-core#4805]
Druid's talent Omen of Clarity (OoC) doesn't work as it should. After entering a Clearcasting state and using skill Ferocious Bite resets all energy points to zero and no matter how much the energy scale is filled.  

**Voittamaton**

How does it work:

1. Cast OoC, 
2. Shapeshift into Cat form,
3. Use any ability (Mangle, Rake, Claw) to get 1 or more combo points,
4. Attack any target,
5. Wait until the Cleracasting state appears,
6. Use Ferocious Bite.

Spell: Omen of Clarity https://imgur.com/1ql9qN3 https://www.wowhead.com/spell=16864/omen-of-clarity, 
Clearcasting https://imgur.com/u4jTPQe https://www.wowhead.com/spell=135700/clearcasting 

**The Clearcasting state reduces the mana, rage or energy cost of your next damage or healing spell or offensive ability by 100%.**

**Now it looks like this 0:30 - 0:40 https://www.youtube.com/watch?v=7yp-tl4WYt4&ab_channel=Janowar
This is how it should work  2:31 - 2:35 https://www.youtube.com/watch?v=Ok3hD-_Zuno&ab_channel=HypnoDroid**

GM said it works fine and I'm mistaken about it.
Hope you will fix it guys!

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/3307
