### ISSUE TITLE
Humar the Pridelord

### ISSUE THREAD

**Issue by Tomslacite** [ValorenWoW/sunstrider-core#4806]
**Describe the bug**

As a hunter when you tame Humar the Pridelord an elite black lion in the Barrens you can learn spells and get Training Points but as i tried today it doesn't work. No Training Points and no spells
**Character name**

Tippyjuice
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

https://classic.wowhead.com/npc=5828/humar-the-pridelord

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
You need to level up your pet to get those.
