### ISSUE TITLE
Blood Oath of the Netherwing is not showing up

### ISSUE THREAD

**Issue by lamprador** [ValorenWoW/sunstrider-core#4809]
After completing the "Ally of the Netherwing" quest on Mordenai he does not unlock any new quests, so the quests for the Netherwing reputation are not available.
Here we can see that this is not how it is supposed to work: https://db.endless.gg/?quest=11012

Thank you for your time.

**Comment by Jerrythemagicdog** [comment]
You need 300 Riding to access that quest.
