### ISSUE TITLE
[core] [priest] [spell] Mind Control is instantly canceled when another CC expires

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4810]
repro:

fear someone
MC someone at 4 sec remaining
observe MC getting instantly canceled for no reason

100% repro

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
It happens when a controlling player attempts to move while the target is MCed and has another CC effect (stun, fear, etc), not when some other CC expires with an MC.
Closing because it's a duplicate.
