### ISSUE TITLE
Quest: Malevolent Remants not tracking killed mobs correctly.

### ISSUE THREAD

**Issue by DaturoDewitt** [ValorenWoW/sunstrider-core#4815]
**Describe the bug**
Severed Defenders don't count towards the 'Severed Spirit slain 0/20' tracker.
Quest: Malevolent Remnants

**Character name**
DaturoDewitt

**To Reproduce**
1. Accept quest Malevolent Remnants.
2. Kill 'Severed Spirits' and 'Severed Defenders'
3. Only 'Severed Spirits' count towards the tracker

> Quest: 
> https://www.wowhead.com/quest=10184/malevolent-remnants
> Mobs:
> https://www.wowhead.com/npc=19881/severed-spirit
> https://www.wowhead.com/npc=20934/severed-defender

**Expected behavior**
Severed Defenders count towards the quest progress.

![grafik](https://user-images.githubusercontent.com/49022685/110630674-f67e6e80-81a5-11eb-8ca9-c42943fbeca9.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update!
