### ISSUE TITLE
2v2 is not giving bonus arena points on Windrunner

### ISSUE THREAD

**Issue by estenv** [ValorenWoW/sunstrider-core#4817]
From https://endless.gg/fresh

"Arena points flush will happen twice a week, with more points awarded in 2v2 and 3v3"

The first arena flush did not give any bonus points for 2v2.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.

**Comment by estenv** [comment]
Restart for updates happened yesterday but todays flush still gave regular 2v2 points

**Comment by estenv** [comment]
Apparently 3v3 is also giving normal amount of points.
