### ISSUE TITLE
Strange 1 shots on last boss SHH-H

### ISSUE THREAD

**Issue by MechaPhoton** [ValorenWoW/sunstrider-core#4818]
so first of all sorry no screenshot.

but during our SHH-H run today me and the other party memebers experienced a bug where the final boss would charge a player and deal damage of roughly 3.5k and that player would die from full health + shields of over 10k with no other damage taking event in combat log.

this happened to mage, warlock , and a holy paladin.

**Comment by MechaPhoton** [comment]
ok did a few more attempts, same bug, got a screen shot. i was at full health + mana barrier + ice armor about 1s before this 

https://imgur.com/0CNMYhL

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
