### ISSUE TITLE
Shifting Naaru Sliver buff uptime is inconsistent

### ISSUE THREAD

**Issue by BasedForfrost** [ValorenWoW/sunstrider-core#4819]
Shifting Naaru Sliver places a circle on the ground that grants a spell power buff, and while standing in the circle the buff will activate and fade back and forth on different elevations of ground, such as stairs or bridges.

**Character name**
Quaack

1. Stand on a stairwell
2. Use Shifting Naaru Sliver
3. Watch buff bar for Limitless Power

https://imgur.com/a/sA9sDoH

**Comment by z5n** [comment]
unable to reproduce
