### ISSUE TITLE
Honor Guards in Stormspire are invisible, and killing people.

### ISSUE THREAD

**Issue by Zience** [ValorenWoW/sunstrider-core#4820]
**Describe the bug**
Is an invisible mob, unable to been seen or targeted or damaged, killing people,

**Character name**
Zience

**To Reproduce**
Do the quest Full Triangle, and the 3 mobs will appear. 

**Expected behavior**
Not to be attacked by an invisible, invincible mob.

**Comment by Jerrythemagicdog** [comment]
Move your camera, certain angles make creatures appear invisible on the old client.

**Comment by Zience** [comment]
That wasn't the issue. When the adds were spawned, one of them would instantly die. And then be respawned, however a player would be unable to interact with the add, AND no NPC's would either. As a GM, I would recommend flying out there and watching as someone turns in the quest.
