### ISSUE TITLE
Powershift

### ISSUE THREAD

**Issue by Angol36** [ValorenWoW/sunstrider-core#4822]
If you powershift as a druid, your energy regeneration will be reset to 2sec. normal it will not res you use a skill = 0Energy waiting for the Global CD 1.5s powershift and normal you would then arrive after 0.5s your 20 energy regeneration. which is not the case which is an extreme nerve for powershifting

**Comment by Angol36** [comment]
> If you powershift as a druid, your energy regeneration will be reset to 2sec normal, it will not res you use a skill = 0Energy waiting for the Global CD 1.5s powershift and normal you would then arrive after 0.5 your 20 energy regeneration. which is not the case which is an extreme nerve for powershifting



> If you powershift as a druid, your energy regeneration will be reset to 2sec normal, it will not res you use a skill = 0Energy waiting for the Global CD 1.5s powershift and normal you would then arrive after 0.5 your 20 energy regeneration. which is not the case which is an extreme nerve for powershifting

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4726
