### ISSUE TITLE
WoW Client keeps closing itself when i try to launch the game

### ISSUE THREAD

**Issue by Arjeii** [ValorenWoW/sunstrider-core#4823]
Whenever I try to open the client it automatically drags all my open programs to my main screen, then the screen turns black, and it closes itself. (The client is still running, it just closes). I got no error message, or anything like that.

I just downloaded Endless for the first time. I didn't have a TBC Client already on my pc, so I downloaded the Launcher and then I downloaded the client from there. Thereafter, I tried to launch the game and all this started happening.

The expected behaviour here would be that the client opened and ran like wow normally does.

Let me know if there's any additional info you'd need to solve this issue.

**Comment by Jerrythemagicdog** [comment]
Have you tried this solution?
```
If you're getting a black screen when swapping to windowed mode - it's a GAMMA issue. Open up config.wtf inside of your WTF folder and add these 2 lines:
SET gxWindow "1"
SET gxMaximize "1"
```

**Comment by Arjeii** [comment]
That worked! Thanks alot.
