### ISSUE TITLE
SSC - Trash immune to sheep

### ISSUE THREAD

**Issue by Jamesrandi** [ValorenWoW/sunstrider-core#4826]
Coilfang Priestresses are immune to sheep

https://wowwiki-archive.fandom.com/wiki/Coilfang_Priestess

"Can be polymorphed, sapped, seduced or mind-controlled and feared."

**Comment by MihawkEntropius** [comment]
Selected: [Coilfang Priestess]
SpawnId: 93815 Entry: 21220
Mechanic Immunity: Charm, Disorient, Disarm, Distract, Fear, Root, Silence, Sleep, Snare, Stun, Freeze, Incapacitate, Polymorph, Banish, Horror, Interrupt Cast, Daze, Sap.

**Comment by Jerrythemagicdog** [comment]
https://www.twitch.tv/videos/944243673?t=1h16m51s

Not immune to sheep, only immune to MC.
