### ISSUE TITLE
Prince Malchezaar p2 swings

### ISSUE THREAD

**Issue by ssaip** [ValorenWoW/sunstrider-core#4827]
**Current behaviour:**

Prince Malchezaar sometimes hits up to 5 times.

My assumption is that he gains Thrash, and one of those swings immediately triggers another Thrash buff/procc, or that the parry haste incorrectly gives him an instant attack.

I'm attaching screens where 5 swings happen at the same time, which should not be possible.
![1](https://user-images.githubusercontent.com/1868725/110968873-54eb4e80-8358-11eb-8683-6707083eb6d5.png)
![2](https://user-images.githubusercontent.com/1868725/110968875-5583e500-8358-11eb-97a4-98612dcdf947.png)

As well as a log from a different try where 4 swings happened at the same time:
![3](https://user-images.githubusercontent.com/1868725/110968877-561c7b80-8358-11eb-9295-5f21fc62e2d3.png)

**Expected behaviour:**
Prince Malchezaar is supposed to periodically gain "Thrash", which will give him 2 extra attacks. 
In addition to that he can parry in p2, which will give him parry haste (40% faster attack on NEXT swing).

So in worst case we get 1 auto attack + 2 thrash attacks = 3 swings
and 1 (ONE) additional hit **soon after**, because of parry haste.

**Source(s):**
https://wow.gamepedia.com/Prince_Malchezaar
https://www.wowhead.com/spell=3391/thrash

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
The boss dual-wields in that phase.
Parry haste can build up and significantly reduce the timer of the next attack if the boss repeatedly parries before the next attack, which is most likely what happened here.
Unless we can look at more accurate combat log timestamps (with milliseconds) we won't be able to tell if there's an issue here.

**Comment by ssaip** [comment]
Attached is part of my very limited amount of logs for this fight from the day after.

`
20:45:38.636 swing
20:45:39.175 swing
20:45:40.588 swing
20:45:40.642 swing
20:45:40.642 thrash
20:45:40.642 thrash
`
While it does look correct that within a single spellbatch only a maximum of 3 attacks happened (swing + thrash), I'm particularly interested in the last 4 swings that happened within 0.054 seconds. 
How can I find out if that is a MH or OH swing?
There are no parries in the log around this area. Normal swingtimer seems around 1 sec at that time, what is the offhand swingtimer? are they just overlapping?

Looking at the damage it seems that the first swing is always the offhand, closely followed by mainhand and 2 more mainhand swings from thrash? is that correct?

Another example:

`
20:45:57.800 swing
20:45:57.848 swing
20:45:57.848 thrash
20:45:57.848 thrash
`
which are also 4 swings and while not in the same spellbatch, they are only 0.048s apart.
There are no parries in that area either.
(I marked those areas with ====== in the log)
[malchezaar.txt](https://github.com/SunstriderEmu/BugTracker/files/6143285/malchezaar.txt)

**Comment by kelno** [comment]
Thank you for the details. 

> How can I find out if that is a MH or OH swing?

There is no good way to do that except by looking at damage.

> 20:45:38.636 swing 20:45:39.175 swing 20:45:40.588 swing 20:45:40.642 swing 20:45:40.642 thrash 20:45:40.642 thrash

This ones look normal to me yes. Looks like an offhand closely followed by a main hand.
Though the main hand and offhand timers are not the same so this overlap shouldn't appear at each hit. That part seem working as intended when reading your log.

Here is your cleaned up log for reference, only containing attacks done by Malchezaar
```
3/13 20:45:38.636  SWING_DAMAGE,3205
3/13 20:45:39.175  SWING_DAMAGE,1707
3/13 20:45:40.588  SWING_DAMAGE,1977
3/13 20:45:40.642  SWING_DAMAGE,2963
3/13 20:45:40.642  SPELL_EXTRA_ATTACK
3/13 20:45:40.642  SWING_MISSED,DODGE
3/13 20:45:40.642  SWING_DAMAGE,3751
3/13 20:45:42.007  SWING_DAMAGE,1769
3/13 20:45:42.007  SPELL_EXTRA_ATTACK
3/13 20:45:42.007  SWING_MISSED,DODGE
3/13 20:45:42.007  SWING_DAMAGE,3627
3/13 20:45:44.218  SWING_MISSED,MISS
3/13 20:45:44.499  SWING_DAMAGE,1479
3/13 20:45:45.907  SWING_MISSED,DODGE
3/13 20:45:46.244  SWING_DAMAGE,2918
3/13 20:45:46.244  SPELL_EXTRA_ATTACK
3/13 20:45:46.244  SWING_MISSED,DODGE
3/13 20:45:46.244  SWING_DAMAGE,3184
3/13 20:45:47.311  SWING_MISSED,DODGE
3/13 20:45:48.296  SWING_DAMAGE,2852
3/13 20:45:48.757  SWING_DAMAGE,1728
3/13 20:45:50.132  SWING_MISSED,DODGE
3/13 20:45:50.391  SWING_DAMAGE,1495
3/13 20:45:51.755  SWING_DAMAGE,3182
3/13 20:45:51.755  SPELL_EXTRA_ATTACK
3/13 20:45:51.755  SWING_MISSED,DODGE
3/13 20:45:51.755  SWING_MISSED,DODGE
3/13 20:45:52.034  SWING_MISSED,DODGE
3/13 20:45:53.486  SWING_DAMAGE,1790
3/13 20:45:53.802  SWING_MISSED,DODGE
3/13 20:45:54.910  SWING_MISSED,MISS
3/13 20:45:55.813  SWING_MISSED,DODGE
3/13 20:45:56.346  SWING_DAMAGE,1889
3/13 20:45:57.800  SWING_DAMAGE,1606
3/13 20:45:57.848  SWING_DAMAGE,3724
3/13 20:45:57.848  SPELL_EXTRA_ATTACK
3/13 20:45:57.848  SWING_MISSED,MISS
3/13 20:45:57.848  SWING_DAMAGE,3128
3/13 20:45:59.260  SWING_DAMAGE,1505
3/13 20:45:59.892  SWING_DAMAGE,3299
3/13 20:46:00.680  SWING_DAMAGE,1691
3/13 20:46:01.917  SWING_DAMAGE,2744
3/13 20:46:02.180  SWING_DAMAGE,1845
3/13 20:46:03.608  SWING_DAMAGE,1877
3/13 20:46:03.608  SPELL_EXTRA_ATTACK
3/13 20:46:03.608  SWING_DAMAGE,3412
3/13 20:46:03.608  SWING_DAMAGE,2866
```

**Comment by kelno** [comment]
I'll close for now, I think this is just a matter of luck, Trash being able to add 2 extra attacks is really inducing a lot of random in this fight.
