### ISSUE TITLE
 [The Vengeful Harbinger] quest is bug

### ISSUE THREAD

**Issue by CagriZ** [ValorenWoW/sunstrider-core#4831]
After doing this quest, it cannot be completed. Please, fix it. Thanks

**Comment by Sheikthecatman** [comment]
![image](https://user-images.githubusercontent.com/59149613/111044318-103ee080-8448-11eb-8a8e-1e4d5822d8a6.png)
Works fine on my end, you have to talk to the gameobject (draenei spirit)

What exactly is the issue?

**Comment by CagriZ** [comment]
Now no problem because we killed final mob in the distant place and its worked. Previously, when npc died next to him, his spirit did not rise.

Thanks
