### ISSUE TITLE
Druid talent  - Force of Nature

### ISSUE THREAD

**Issue by Turtlepower1** [ValorenWoW/sunstrider-core#4832]
**Describe the bug**
Looks like talent is not working as it should be.Spawn of treants should be in the area that player selected, not near the player by default ,otherwise what the sense of area selection? And also aggro should be generated by the enemy which appear to be in area you selected, like this u can select you target more accurate.Atleast this talent was working like this on any other servers, kindly ask to check.

**Character name**
Turtlepower

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, but it's a duplicate: https://github.com/SunstriderEmu/BugTracker/issues/2650
