### ISSUE TITLE
Input bug

### ISSUE THREAD

**Issue by Cacus911** [ValorenWoW/sunstrider-core#4833]
**Describe the bug**
Pressing my movement key ''A'' and the keybind ''Z'' just stales my character in place and doesnt activate the action bound to ''Z''

**Character name**
Cacus

**To Reproduce**

1. press A and keep it pressed down
2. press Z
3. nothing happens

**Expected behavior**
Character should do the attack bound to ''Z'' (charge/intercept)

**Comment by Cacus911** [comment]
every single other keybind works when pressing ''A'' except ''Z''... very confusing

**Comment by Jerrythemagicdog** [comment]
Looks like an issue with your keyboard, nothing we can do on our end sorry!
