### ISSUE TITLE
crash on login

### ISSUE THREAD

**Issue by Andyislam** [ValorenWoW/sunstrider-core#4834]
**Describe the bug**
HEarthed to aldor tier on scryers. Game crashes on startup only on this toon. 

**Character name**
cameltotemz

**To Reproduce**
Log in and looks like crash as soon as assets are loaded

Error log below

WoWBuild: 18606
Realm: Windrunner [51.178.93.59:8085]
Local Zone: Shattrath City
Local Player: Cameltotemz, 00000000000194AD, (-1795.27,5657.99,129.655)
Add Ons: AtlasLoot ItemRack Omen Recount DBM_API pfQuest-tbc pfUI-tbc 

=========================================================
Assertion Failed!

 App:         /Users/andyislam/Documents/World of Warcraft TBC 2.4.3/World of Warcraft.app
 File:        /Volumes/F2/usrbuild/xb/build/WoW_8606patch2.4.3/WoW/Source/Mac/../ObjectMgrClient/ObjectMgrClient.cpp
 Line:        2025
 Error Code:  0x85100086
 Time:        2021-03-14 03.02.36 EDT

 Assertion:   Illegal client GUID dereference at /Volumes/F2/usrbuild/xb/build/WoW_8606patch2.4.3/WoW/Source/Mac/../Object/ObjectClient/Movement_C.cpp:73! Provided GUID 0xF11000000000007B

---------------------------------------------------------
Thread 0 (0x303) (Current)
  0 0x0004393a <unknown>
  1 0x00043f38 <unknown>
  2 0x000512e8 <unknown>
  3 0x000049c5 <unknown>
  4 0x000050f8 <unknown>
  5 0x0009aaf7 <unknown>
  6 0x0038b8de <unknown>
  7 0x0031e06f <unknown>
  8 0x0008ded3 <unknown>
  9 0x000946ad <unknown>
 10 0x00251fb7 <unknown>
 11 0x0025203f <unknown>
 12 0x0025349a <unknown>
 13 0x000f1159 <unknown>
 14 0x000a1be7 <unknown>
 15 0x000a1def <unknown>
 16 0x000a31b6 <unknown>
 17 0x003a33f6 <unknown>
 18 0x003a4972 <unknown>
 19 0x005dd68e <unknown>
 20 0x0017c905 <unknown>
 21 0x0000b5ea <unknown>
 22 0x002bb224 <unknown>
 23 0x002c05f7 <unknown>
 24 0x002c0882 <unknown>
 25 0x00011f05 <unknown>
 26 0x000036f9 <unknown>
 27 0x92e4f9a8 _InvokeEventHandlerUPP(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*, long (*)(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*)) + 26
 28 0x92de8fdf DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 1970
 29 0x92de8176 SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 376
 30 0x92de7ff2 _SendEventToEventTargetWithOptions + 40
 31 0x92e02f4e ToolboxEventDispatcherHandler(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*) + 1303
 32 0x92de9459 DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*) + 3116
 33 0x92de8176 SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*) + 376
 34 0x92e034f9 _SendEventToEventTarget + 33
 35 0x92f83329 _ToolboxEventDispatcher + 82
 36 0x92f831eb _RunApplicationEventLoop + 192
 37 0x0000382a <unknown>
 38 0x000024fe <unknown>
 39 0x00002425 <unknown>
 40 0x00000001 <unknown>

Thread 1 (0x9f03)
  0 0xa7d5731e _mach_wait_until + 10
  1 0xa7cdfb7d _nanosleep + 322
  2 0xa7cdfa02 _usleep + 54
  3 0x0004e178 <unknown>
  4 0x00044a61 <unknown>
  5 0xa7e0a5f8 __pthread_body + 137
  6 0xa7e0d7f7 __pthread_start + 78
  7 0xa7e097ce _thread_start + 34
  8 0x00000000 <unknown>

Thread 2 (0x9e03)
  0 0xa7d76542 _sem_wait + 10
  1 0x00044a61 <unknown>
  2 0xa7e0a5f8 __pthread_body + 137
  3 0xa7e0d7f7 __pthread_start + 78
  4 0xa7e097ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 3 (0x6203)
  0 0xa7d76542 _sem_wait + 10
  1 0x00044a61 <unknown>
  2 0xa7e0a5f8 __pthread_body + 137
  3 0xa7e0d7f7 __pthread_start + 78
  4 0xa7e097ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 4 (0x6303)
  0 0xa7d76542 _sem_wait + 10
  1 0x00044a61 <unknown>
  2 0xa7e0a5f8 __pthread_body + 137
  3 0xa7e0d7f7 __pthread_start + 78
  4 0xa7e097ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 5 (0x802f)
  0 0xa7d571c2 _mach_msg_trap + 10
  1 0xa7d5770f _mach_msg + 47
  2 0x9a2b1b17 _glcDebugListener + 416
  3 0xa7e0a5f8 __pthread_body + 137
  4 0xa7e0d7f7 __pthread_start + 78
  5 0xa7e097ce _thread_start + 34
  6 0x00000000 <unknown>

Thread 6 (0x15307)
  0 0xa7d571c2 _mach_msg_trap + 10
  1 0xa7d5770f _mach_msg + 47
  2 0xa7d6f396 _mach_msg_server + 301
  3 0x0002c638 <unknown>
  4 0xa7e0a5f8 __pthread_body + 137
  5 0xa7e0d7f7 __pthread_start + 78
  6 0xa7e097ce _thread_start + 34
  7 0x00000000 <unknown>

Thread 7 (0xac03)
  0 0xa7d5731e _mach_wait_until + 10
  1 0xa7cdfb7d _nanosleep + 322
  2 0xa7cdfa02 _usleep + 54
  3 0x00014e91 <unknown>
  4 0x000d78b7 <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x951a3352 -[NSThread main] + 39
  8 0x951a31fb ___NSThread__start__ + 1220
  9 0xa7e0a5f8 __pthread_body + 137
 10 0xa7e0d7f7 __pthread_start + 78
 11 0xa7e097ce _thread_start + 34
 12 0x00000000 <unknown>

Thread 8 (0xae03)
  0 0xa7d5a7aa ___psynch_cvwait + 10
  1 0xa7e0db46 __pthread_cond_wait + 738
  2 0xa7e0b5d5 _pthread_cond_wait + 25
  3 0x0028af73 <unknown>
  4 0x0006df0c <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x951a3352 -[NSThread main] + 39
  8 0x951a31fb ___NSThread__start__ + 1220
  9 0xa7e0a5f8 __pthread_body + 137
 10 0xa7e0d7f7 __pthread_start + 78
 11 0xa7e097ce _thread_start + 34
 12 0x00000000 <unknown>

Thread 9 (0x13607)
  0 0xa7d571c2 _mach_msg_trap + 10
  1 0xa7d5770f _mach_msg + 47
  2 0x93460829 HALB_MachPort::SendMessageWithReply(unsigned int, unsigned int, unsigned long, unsigned long, mach_msg_header_t*, bool, unsigned int) + 119
  3 0x9343bba1 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 49
  4 0x93438d85 HALC_ProxyIOContext::IOWorkLoop() + 1517
  5 0x9343858c HALC_ProxyIOContext::IOThreadEntry(void*) + 208
  6 0x93468d46 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned long, unsigned int) + 20
  7 0x93438263 HALB_IOThread::Entry(void*) + 71
  8 0xa7e0a5f8 __pthread_body + 137
  9 0xa7e0d7f7 __pthread_start + 78
 10 0xa7e097ce _thread_start + 34
 11 0x00000000 <unknown>

Thread 10 (0x13403)
  0 0xa7d5731e _mach_wait_until + 10
  1 0x948e9ec2 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7e0a5f8 __pthread_body + 137
  5 0xa7e0d7f7 __pthread_start + 78
  6 0xa7e097ce _thread_start + 34
  7 0x00000000 <unknown>

Thread 11 (0x13207)
  0 0xa7d5731e _mach_wait_until + 10
  1 0x948e9ec2 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7e0a5f8 __pthread_body + 137
  5 0xa7e0d7f7 __pthread_start + 78
  6 0xa7e097ce _thread_start + 34
  7 0x00000000 <unknown>

Thread 12 (0xc703)
  0 0xa7d5a7aa ___psynch_cvwait + 10
  1 0xa7e0db46 __pthread_cond_wait + 738
  2 0xa7e0d1fa _pthread_cond_timedwait + 27
  3 0x0028ae6d <unknown>
  4 0x002ab8f8 <unknown>
  5 0x002aba42 <unknown>
  6 0x0010ca43 <unknown>
  7 0x0010cc30 <unknown>
  8 0x951a3352 -[NSThread main] + 39
  9 0x951a31fb ___NSThread__start__ + 1220
 10 0xa7e0a5f8 __pthread_body + 137
 11 0xa7e0d7f7 __pthread_start + 78
 12 0xa7e097ce _thread_start + 34
 13 0x00000000 <unknown>

Thread 13 (0x13103)
  0 0xa7d5c3fe ___select_nocancel + 10
  1 0xa7d5a375 _select + 78
  2 0x002aae38 <unknown>
  3 0x002abdf6 <unknown>
  4 0x0010ca43 <unknown>
  5 0x0010cc30 <unknown>
  6 0x951a3352 -[NSThread main] + 39
  7 0x951a31fb ___NSThread__start__ + 1220
  8 0xa7e0a5f8 __pthread_body + 137
  9 0xa7e0d7f7 __pthread_start + 78
 10 0xa7e097ce _thread_start + 34
 11 0x00000000 <unknown>

Thread 14 (0xcd0b)
  0 0xa7d76542 _sem_wait + 10
  1 0x00044a61 <unknown>
  2 0xa7e0a5f8 __pthread_body + 137
  3 0xa7e0d7f7 __pthread_start + 78
  4 0xa7e097ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 15 (0xd10b)
  0 0xa7d571c2 _mach_msg_trap + 10
  1 0xa7d5770f _mach_msg + 47
  2 0x9384e3b7 ___CFRunLoopServiceMachPort + 289
  3 0x9384dae1 ___CFRunLoopRun + 2896
  4 0x9384cc94 _CFRunLoopRunSpecific + 584
  5 0x93865a8d _CFRunLoopRunInMode + 82
  6 0x92a8d5f4 -[__CoreSchedulingSetRunnable runForever] + 579
  7 0x92a8d22d +[__CoreSchedulingSetRunnable _run:] + 129
  8 0x951a3352 -[NSThread main] + 39
  9 0x951a31fb ___NSThread__start__ + 1220
 10 0xa7e0a5f8 __pthread_body + 137
 11 0xa7e0d7f7 __pthread_start + 78
 12 0xa7e097ce _thread_start + 34
 13 0x00000000 <unknown>

Thread 16 (0x12613)
  0 0xa7d76542 _sem_wait + 10
  1 0x006b5275 <unknown>
  2 0xa7e0a5f8 __pthread_body + 137
  3 0xa7e0d7f7 __pthread_start + 78
  4 0xa7e097ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 17 (0x1250f)
  0 0xa7d76542 _sem_wait + 10
  1 0x006b5275 <unknown>
  2 0xa7e0a5f8 __pthread_body + 137
  3 0xa7e0d7f7 __pthread_start + 78
  4 0xa7e097ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 18 (0x100f)
  0 0xa7d5a7aa ___psynch_cvwait + 10
  1 0xa7e0db46 __pthread_cond_wait + 738
  2 0xa7e0d1fa _pthread_cond_timedwait + 27
  3 0x0028ae6d <unknown>
  4 0x00512f76 <unknown>
  5 0x0010ca43 <unknown>
  6 0x0010cc30 <unknown>
  7 0x951a3352 -[NSThread main] + 39
  8 0x951a31fb ___NSThread__start__ + 1220
  9 0xa7e0a5f8 __pthread_body + 137
 10 0xa7e0d7f7 __pthread_start + 78
 11 0xa7e097ce _thread_start + 34
 12 0x00000000 <unknown>

Thread 19 (0x5007)
  0 0xa7d58ab6 ___workq_kernreturn + 10
  1 0xa7e099c1 __pthread_wqthread + 415
  2 0xa7e097aa _start_wqthread + 34
  3 0x13237910 <unknown>

Thread 20 (0x203b)
  0 0xa7d58ab6 ___workq_kernreturn + 10
  1 0xa7e09a74 __pthread_wqthread + 594
  2 0xa7e097aa _start_wqthread + 34
  3 0x54485244 <unknown>

Thread 21 (0x4b5f)
  0 0xa7d5731e _mach_wait_until + 10
  1 0x948e9ec2 _MPDelayUntil + 22
  2 0x0068f807 <unknown>
  3 0x006b52a9 <unknown>
  4 0xa7e0a5f8 __pthread_body + 137
  5 0xa7e0d7f7 __pthread_start + 78
  6 0xa7e097ce _thread_start + 34
  7 0x00000000 <unknown>

Thread 22 (0x14823)
  0 0x00000000 <unknown>

Thread 23 (0x7f2f)
  0 0xa7d76542 _sem_wait + 10
  1 0x00044a61 <unknown>
  2 0xa7e0a5f8 __pthread_body + 137
  3 0xa7e0d7f7 __pthread_start + 78
  4 0xa7e097ce _thread_start + 34
  5 0x00000000 <unknown>

Thread 24 (0xa8b)
  0 0xa7d76542 _sem_wait + 10
  1 0x00044a61 <unknown>
  2 0xa7e0a5f8 __pthread_body + 137
  3 0xa7e0d7f7 __pthread_start + 78
  4 0xa7e097ce _thread_start + 34
  5 0x00000000 <unknown>

=========================================================

**Comment by Andyislam** [comment]
also tried without any addons. can log in fine on another toon on the server.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Look like you've resolved your issue as you're online.
