### ISSUE TITLE
Bloodthirst rank 6 bugged, way less dmg than the tooltip says. 

### ISSUE THREAD

**Issue by Deenise** [ValorenWoW/sunstrider-core#4838]
**Describe the bug**

Bloodthirst might be bugged. Its supposed to be 547 base dmg, but it does 350ish dmg and thats on leather, cloth, mail and plate.

**Character name**

Jayquellin
**To Reproduce**

1. Cast X on target affected by ...
2. Bloodthirst doing 60% of the dmg its supposed to do. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=Bloodthirst rank 6

**Expected behavior**

Expected it to do 500+ dmg as the tooltip says, not 350. 

**Screenshots/videos**

https://ibb.co/kxLk6TG
**Additional context**

**Comment by blblblaz** [comment]
![image](https://user-images.githubusercontent.com/53877162/111085398-ebb63780-851f-11eb-943a-7fb0038c34a5.png)

just did a quick test, Warrior with 1868 attack power, Bloodthirst takes 45% of warrior attack power, so 840.
Keep in mind that Bloodthirst is physical damage which is reduced by armor, the creature you hit in your screenshot has around 5900 armor which amounts to around 36% physical damage reduction
