### ISSUE TITLE
the mail from reporting spammers is almost as annoying as the spammers

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4843]
love the fact we can report spammers and it gets dealt with quickly...

absolutely hate the thank you message that comes with a gift that you can't delete unless you accept the gift (or return the message and then you can delete the returned message).

could we get an account level toggle on whether we want to receive the "thank you" gift/message?  Or could the message come with a delete option (send it initially as a returned message from yourself?)

im reporting sometimes 30-40 a day, that's a lot of trash messages I just would rather not deal with.   

maybe if the gift you received was always the same so you could just delete the entire stack at once instead of searching in your bags for 4 different items and deleting 4 different stacks.

**Comment by Jerrythemagicdog** [comment]
Disabled with next update, thanks.
