### ISSUE TITLE
Priest angel form triggering pull

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4844]
dungeon boss, thespia in sv specifically.

group wipes, priest is in angel form.   
Boss resets.  
not priest takes soulstone.   
priest ends angel form and boss pulls.  

i assume the priest player is alive for a split second or something transitioning to corpse form and thats what is pulling, but probably would be better if it didn't pull.

**Comment by kelno** [comment]
Thanks for reporting, fixed with next server update
