### ISSUE TITLE
UBRS Pyroguard Emberseer's doors

### ISSUE THREAD

**Issue by SotelEndlessgg** [ValorenWoW/sunstrider-core#4845]
**Describe the bug**
Pyroguard Emberseer's doors don't open properly after killing the preceding packs guarding the runes.

**Character name**
Sotel

**To Reproduce**

1. Kill the Blackhand NPCs guarding the runes

**Expected behavior**
When you kill the pack of 4, the rune should disappate. After all the runes are gone, the door should open

**Additional context**
I wondered if the summoned NPCs from the Summoners or fleeing NPCs might have an impact.

**Comment by Sheikthecatman** [comment]
Thanks! This issue seems to be caused if you evade or reset the mobs in the dungeon. Fixed next server restart
