### ISSUE TITLE
Gold spammers.

### ISSUE THREAD

**Issue by MrBulrok** [ValorenWoW/sunstrider-core#4846]
**Describe the bug**
People who are below level 19 are spamming the shit out from the global chat, and its really fucking with me. Please do something to make this go away, spam limit or find out how are they spamming global at level 1. Unless it's just you guys trying to promo your gold sites.

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/80741605/111265479-d3364200-8631-11eb-9e51-f8f4a57454b9.png)

**Additional context**
Please do something, im really enjoying this server and i'd hate to quit just because gold spamers are making it unplayable for me. Thanks.

**Comment by Jerrythemagicdog** [comment]
We're updating the server soon with anti-spam solutions.

**Comment by MrBulrok** [comment]
Cheers! Keep up the good work!
