### ISSUE TITLE
Energy Bug

### ISSUE THREAD

**Issue by peachmachine** [ValorenWoW/sunstrider-core#4847]
**Describe the bug**
When u shapeshift in cat form right before energy ticks u dont get 20 additional energy like u should, energy is constantly 40. It doesent metter if u shapeshif correctly or not.

**Character name**
Peachmachine a newcomer

**To Reproduce**
So bassicly every time u shapeshift into cat form you should get 40 evergy but if u powershift right before the tick of energy you should always get 60. On endless u dont get that additional 20 energy.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4726
