### ISSUE TITLE
Druid Flying Form not granted on lvl70 (windrunner realm)

### ISSUE THREAD

**Issue by c2lhu** [ValorenWoW/sunstrider-core#4848]
**Describe the bug**
This behavior is custom for this server. The spells are granted automatically on levelling. One of those is the fly form for druids. I have come across a bug where I was not granted the fly form on level 70. I tried relogging multiple times but I can't seem to get it. Every other player I talked to got his flying form spell automatically on his spellbook upon reaching level 70. Now from what I can understand this is probably a bug concerning the riding skill. When I reached level 70 I still had riding skill 75, (not 150 - journeyman). So to get to fly you need skill at 300 (expert). Maybe I did not get the flying form because my riding skill was still low. Now I went and trained riding to 150 (via town trainer for free) and stuck with no flying form.

**Character name**
Character name: Tokyoredhood (Windrunner realm)

**To Reproduce**
level druid character to 70 with slow horse. (un tested)

Spell: https://www.wowhead.com/spell=165962/flight-form

**Expected behavior**
As advertised should get flying form spell for free on level 70

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
There is no "free flight form" advertisement.
To get the basic 60% Flight Form you need 150 Riding, then you can proceed to learn it at the trainer.
If you happen to have 150 Riding before you reach the level then the spell is going to be taught to you through auto-learn.

**Comment by c2lhu** [comment]
ok thanks for the clarification, I happened to not have 150 skill, so I will need to learn it the old fashioned way now (in this case 800g fee is required tho)
