### ISSUE TITLE
Digging Up the Past [Quest]. 

### ISSUE THREAD

**Issue by Clingon26** [ValorenWoW/sunstrider-core#4849]
**Describe the bug**
Cannot loot the charred bone on the ground, been stood around for an hour in case of a visual bug waiting for "respawn". however still not able to pick up

**Character name**
Shatpanker [Alliance]

https://www.wowhead.com/quest=9680/digging-up-the-past

![image](https://user-images.githubusercontent.com/80785517/111366290-37d1bb00-868b-11eb-8dc2-483d62fc9d3e.png)

**Comment by michaelkittrell** [comment]
he was probably in a raid group.  you can't do the quest in a raid group.
