### ISSUE TITLE
Mining rich deposits

### ISSUE THREAD

**Issue by cottywow** [ValorenWoW/sunstrider-core#4850]
**Expected behaviour:**
Rich deposits should yield somewhere between 5-8 ores. (Mined 5-8 times)

**Actual behaviour:**
All rich deposits can be mined exactly 5 times.

**Steps to reproduce:**
1. Find a rich vein
2. Mine it and note the number of times it was be mined
3. Repeat until convinced

[Wowhead comment](https://www.wowhead.com/object=181569/rich-adamantite-deposit#comments:id=54803) from 2007 about rich adamantite:
"Each vein can carry 5-8 Ores ..."

This includes both *Rich Thorium* and *Rich Adamantite*.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Data on our side at the time of the issue:
Rich Adamantite - min attempts 5, max attempts 7.
Rich Thorium - min attempts 4, max attempts 5.

We've increased the max attempt amount for Rich Adamantite to 8, live with the next update.
