### ISSUE TITLE
Demon Forged Breastplate Proc not working

### ISSUE THREAD

**Issue by SotelEndlessgg** [ValorenWoW/sunstrider-core#4853]
**Describe the bug**
https://db.endless.gg/?item=12628

The Demon Forged Breastplate "Equip: When struck has a 3% chance of stealing 120 life from the attacker over 4 sec." is not working properly. After receiving thousands of melee hits, it did not happen once. Conversely, the Skullflame Shield under the same circumstances, the occurrence happened many times. They both have a 3% chance that is applied when being struck. The effect is not being resisted, it's simply not being cast.

**To Reproduce**
1. The easiest method for a player is to equip the item and then gather a large swarm of melee mobs, such as the Scarlet Monastery Armory.

**Expected behavior**
The proc is supposed to apply a small DoT that leeches HP. The proc is normally high enough to allow multiple instances of this happening at once

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, I get it to proc, perhaps there was an issue at the time that is now resolved.
