### ISSUE TITLE
Worn Dragonscale skinning causes mob to despawn with no skins

### ISSUE THREAD

**Issue by Goontrain** [ValorenWoW/sunstrider-core#4854]
**Describe the bug**

When killing the Firemane Dragonkin in Dustwallow Marsh, including the searing hatchlings and searing whelps, i was trying to skin them for worn dragonscales. Every time a Worn Dragonscale would drop, the mobs body would despawn with any skins I had skinned and i would get no skinning loot.
**Character name**

Goontrain - 45 NE hunter
**To Reproduce**

1. Cast X on target affected by ...
2. as above
3. 

Item: https://wowhead.com?item= Worn Dragonscale
Quest: https://wowhead.com?quest= N/A
Spell: https://wowhead.com?spell= Skinning

**Expected behavior**

I expected to get the skins that were skinned
**Screenshots/videos**

I dont know how to do this...
**Additional context**

**Comment by Jerrythemagicdog** [comment]
Loot window's empty in some cases, skinning yields no loot.
