### ISSUE TITLE
40g~ from mailbox never appeared in bags.

### ISSUE THREAD

**Issue by Jokez85** [ValorenWoW/sunstrider-core#4855]
**Describe the bug**

I opened mail clicking gold from AH. And 40g did not show up in my bags.
**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
You've received 42 gold from your Large Prismatic Shards auction at 2021-03-18 07:56:48 (server time).
Then you've given 50 gold to https://endless.gg/armory/character/dels at 2021-03-18 17:30:53 (server time).
Hope this explains what happened to your gold.
