### ISSUE TITLE
fast reset + hunter pets

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4857]
with the fast reset feature

sometimes if you release (and get insta ressed) then summon a pet you dismissed after wipe was called...  the pet somehow still has agro/is on agro table and pulls the boss.

specifically noticed at tk void reaver

**Comment by kelno** [comment]
Thanks for reporting. 
I can't reproduce this, what react state are you using with your pet?

**Comment by kelno** [comment]
Closed, but if anyone has more info you can give it here or open a new issue.
