### ISSUE TITLE
UD riding trainer doesn't teach riding skill to non UD exalted players

### ISSUE THREAD

**Issue by Talarok** [ValorenWoW/sunstrider-core#4858]
**Describe the bug**
The event that allows the NPC Velma Warnam ID 4773 to recognize an exalted player of another race to see her ride training menu is not working.

**Expected behavior**
Player of non native race who is exalted with said race should be able to train riding and get the reduction in price due to reputation benefit.
![Velma](https://user-images.githubusercontent.com/48861986/111739003-add74d00-8858-11eb-924d-6a7edec9c80a.png)

**Comment by Talarok** [comment]
![image](https://user-images.githubusercontent.com/48861986/111799188-2b26b000-88a1-11eb-9ba8-f4f42f83e4de.png)

**Comment by kelno** [comment]
The exalted mechanic described here doesn't work for any faction.

**Comment by kelno** [comment]
Fixed with next server update
