### ISSUE TITLE
Warrior Spell Reflect Against Warlocks in Blood Furnace

### ISSUE THREAD

**Issue by foxxhound** [ValorenWoW/sunstrider-core#4859]
**Describe the bug**
Shadowmoon Warlock's(18619) ability Shadow Bolt(12739) is not reflected back at the caster via Warrior's Spell Reflection(23920).

**Character name**
Greatest

**To Reproduce**

1. Add Ability Spell Reflection(23920).
2. Modify Warrior's Rage > 24 Points
2. Summon Shadowmoon Warlock (18619)
3. Cast Ability Spell Reflection(23920) before Shadowmoon Warlock's Shadow Bolt cast is finished within the duration of Spell Reflection.

NPC: https://tbcdb.com/?npc=18619
Spell: https://wowhead.com?spell=23920

**Expected behavior**
Shadow Bolt should be reflected back to the caster.

**Screenshots/videos**
None.

**Additional context**
Multiple mobs are ignoring Spell Reflection with Shadow Bolt throughout the expansion. This is one instance where I was able to confirm the behavior.

**Comment by Jerrythemagicdog** [comment]
The spell they're using is not reflectable.
Thanks for the issue though.
