### ISSUE TITLE
Minimize WoW

### ISSUE THREAD

**Issue by wheinlein4** [ValorenWoW/sunstrider-core#4860]
When I changed it to windowed mode it when to a black screen. Now when I log in it just minimizes to my system tray every time I open it.

**Character name**
Dylor

**To Reproduce**
Pressing play on the launcher

**Expected behavior**
The game to load.

**Comment by Jerrythemagicdog** [comment]
If you're getting a black screen when swapping to windowed mode - it's a GAMMA issue. Open up config.wtf inside of your WTF folder and add these 2 lines:
SET gxWindow "1"
SET gxMaximize "1"
