### ISSUE TITLE
Warrior Slam Resetting Swing Timer

### ISSUE THREAD

**Issue by Pocatauntas** [ValorenWoW/sunstrider-core#4861]
**Describe the bug**
Slam appears to be resetting the swing timer which hurts rage generation and clips damage. After an auto attack, a warrior should be able to cast slam without resetting auto attack swing timer thus increasing DPS output while also maximizing rage spending and gains. I have the talent to reduce slam cast time as well and am using a swing timer addon to ensure I am not clipping slams ontop of my auto attacks. I've tested this for days now and the issue is persistent. 

The optimal DPS rotation for PVE Arms warrior should be: Auto Attack > Slam > MS then wait for next Auto Attack > Slam > Whirlwind.
This is currently impossible as there is never enough rage generated because every cast of slam is resetting my auto attack.

**Character name**
Pocatauntas

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by artieau** [comment]
Please provide proof how this should work in TBC

**Comment by Jerrythemagicdog** [comment]
This is correct behaviour in TBC.
