### ISSUE TITLE
respec not saving until logout

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4862]
I activated primary spec.
went to trainer, paid 1g to unlearn skills
spec'd out a new tree
played for about 1.5 hours
crashed out.
logged in with original primary spec instead of new one.
went to trainer, trainer charges me 5g to unlearn skills.

maybe spec should save when you change it.   or maybe trainer shouldn't charge you for a spec that was never saved.

**Comment by artieau** [comment]
As the website prompt states, logout your character after you activate a spec that way.
