### ISSUE TITLE
master loot to someone not in the raid causes loot to disappear?

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4863]
at gruul

master looter assigned a piece of gear to a player who had just hearthed.

player did not get the gear.
gear disappeared from the body
player did not have mail

GRULL ID 21537
MASTERLOOTER sourcerer
target player: purplecheeks
t4 druid legs

**Comment by Jerrythemagicdog** [comment]
Can't reproduce.
In my tests using the same steps the player either doesn't appear on the ML list or when trying to loot to someone outside a message saying "Player not found." is given.
