### ISSUE TITLE
Robe of the Elder Scribes

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4864]
**1.** Internal cooldown is ~45 sec.

> Then I decided to try again with this chest piece because I was bored and wanted to see if the "Internal Cooldown" was actually 45 seconds.
This time around, it was proccing like crazy. The internal cooldown is not 45 seconds by any means, I believe Blizz did fix it.
Edit: From what I can tell, the Internal Cooldown is 20 seconds. I timed it, after the first Proc faded, I set the counter and was killing a mob for 20 seconds I then received a new Proc at 25-26 seconds. This is from my tests, because I do receive them more often than 45 second intervals. [[source](https://www.wowhead.com/item=28602/robe-of-the-elder-scribes#comments:id=174820)]

> I really like this robe for my shadowpriest. Its internal cooldown on the proc seems far shorter than 45-50 seconds as stated above. For me it procs every other mob when I'm soloing which is really good (about once every 20-25 seconds). I would probably only swap this out for a robe with better stats/crit/hit and consistent damage, but for a brand new 70 that soloes a lot this is a great chestpiece. [[source](https://www.wowhead.com/item=28602/robe-of-the-elder-scribes#comments:id=433555)]

**2.** Procs on spell hit, not on spell cast (btw same issue with Quagmiran's Eye, Mana Etched 4-piece bonus, BoW, etc.)

> Even though the proc is worded exactly the same as the Crusade card, it procs on spell *cast* like clearcasting does, not on spell hit. [[source](https://www.wowhead.com/item=28602/robe-of-the-elder-scribes#comments:id=95185:reply=13298)]

> This only procs off of casting the spell, not whether or not the spell deals damage. [[source](https://www.wowhead.com/item=27683/quagmirrans-eye?bonus=6710#comments:id=154214:reply=26709)]

> Quagmirran's Eye has the same "harmful spells" wording and I know for a fact it also procs off counterspell and polymorph so not only damage spells are considered harmful. If it works like Quagmirran's Eye, it will also proc off aoe spells. You don't even need to hit anything with the spell. Might be useful for soloing hard elites. Just spam rank1 arcane explosions until this procs, pop trinkets and pull elite :) [[source](https://www.wowhead.com/spell=37619/spell-power-bonus#comments:id=46433:reply=4198)]

**3.** Chance to proc seems to be lower than 20%
Patch 2.3.0 (2007-11-13): Proc rate increased from 5% to 20%.

**Comment by Jerrythemagicdog** [comment]
https://wowwiki-archive.fandom.com/wiki/Robe_of_the_Elder_Scribes?oldid=1466639

This one mentions a cooldown of 50 seconds.

**Comment by ghost** [comment]
Probably not updated for later patches. With 50s ICD some blues are better than this robe.

**Comment by Jerrythemagicdog** [comment]
The proc chance is updated.
