### ISSUE TITLE
Troublesome Distractions NPC for quest doesn't spawn.

### ISSUE THREAD

**Issue by DaturoDewitt** [ValorenWoW/sunstrider-core#4865]
**Describe the bug**
Waiting for an NPC to spawn to continue a quest line, but he just seems to be on vacation...
(Checked several times at different time intervals and also waited like 20ish minutes)

**Character name**
DaturoDewitt

**To Reproduce**

1. Be on quest [Troublesome Distractions](https://tbcdb.com/?quest=10273)
2. Wait for NPC to respawn/appear
3. Do Taxes
4. Grow old and happy
5. Die

Quest: https://www.wowhead.com/quest=10273/troublesome-distractions
NPC: https://www.wowhead.com/npc=20071/wind-trader-marid

**Expected behavior**
NPC actually comes back to work.

**Screenshots/videos**
This is where I would put a picture of him, if I had one....

**Additional context**
I know this is silly, but honestly you can't write more than he's not here. Thank you for your hard work <3

**Comment by InhumanGM** [comment]
Wind Trader Marid is spawned in, he just isn't in his usual spot.

Whenever someone with [[Troublesome Distractions]](https://db.endless.gg/?quest=10273) speaks to Wind Trader Marid, he walks over to Voidwind Plateau where the player who started the dialogue then has to kill him. If the player doesn't follow through and kill him, then he doesn't respawn and go back to his normal spot, leading many to believe that the NPC isn't spawned in.

However, when Wind Trader Marid _is_ killed, it takes 60 seconds for him to respawn in his normal spot.

![image](https://user-images.githubusercontent.com/65207651/111896394-b0b87600-89ef-11eb-812d-536beed26d72.png)

**Comment by DaturoDewitt** [comment]
Hmm yea I also checked that spot after looking up locations.. will check again today thanks

**Comment by DaturoDewitt** [comment]
I think I know what the Problem is if somebody dies to him the NPC won't return to his original position near the stone and just stands above the corpse of the player.

**Comment by InhumanGM** [comment]
> I think I know what the Problem is if somebody dies to him the NPC won't return to his original position near the stone and just stands above the corpse of the player.

Just tested, it seems that is the case. After seeing that the NPC wasn't in its usual spot, I went to its current location and found it a bit far away from where it is supposed to be.

![image](https://user-images.githubusercontent.com/65207651/112038730-9b3f6b00-8b19-11eb-92f5-b4be043a2a7e.png)

![image](https://user-images.githubusercontent.com/65207651/112038737-9da1c500-8b19-11eb-848d-6cc8d92e5173.png)

**Comment by DaturoDewitt** [comment]
Also, after reviving he started 'following' me immediately like he has infinite aggro range?

**Comment by InhumanGM** [comment]
Can confirm, he followed me from his normal location all the way over here

![image](https://user-images.githubusercontent.com/65207651/112327516-df527d00-8c8b-11eb-97da-2c0a72b37ee4.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
