### ISSUE TITLE
Wow Bug

### ISSUE THREAD

**Issue by Bocarqt93** [ValorenWoW/sunstrider-core#4866]
**Describe the bug**

Stairs and doorsteps stuck

**Character name**

Jaine
**To Reproduce**

1. I'm stuckin on almost every doorstep or stairs and in order to proceed i need to jump.That happens even in bg's and dung's 
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by artieau** [comment]
Models are client side and how blizz made them sadly
