### ISSUE TITLE
Bugged Chat?

### ISSUE THREAD

**Issue by ffeyde42** [ValorenWoW/sunstrider-core#4868]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by ffeyde42** [comment]
windrunner character Whatthe cannot see any chat on screen, cannot send any messages, and cannot join any channels. It was working fine, I went to log in and it made me re patch the client, (Which caused all settings to be reset). Since then I cannot communicate in game.

**Comment by artieau** [comment]
Suggest reinstalling a fresh 2.4.3 client
