### ISSUE TITLE
mobs ignore CC when choosing a target

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#4870]
When the main target is under crowd control effects, mob should aggro onto a non-controlled player.

**Comment by artieau** [comment]
Can you share an example?
It would depend on what CC as to whether the player is dropped off the aggro table for the duration

**Comment by ghost** [comment]
Fel Overseer's Intimidating Shout in Shadow Lab. Yesterday only our tank got hit by it, and the mob continued to wail on him. From memory, this should not happen.

**Comment by Jerrythemagicdog** [comment]
There was a change at some point in TBC where bosses don't ignore feared targets anymore, some notable examples include Nightbane.
