### ISSUE TITLE
Weird frame drops randomly

### ISSUE THREAD

**Issue by Kro331** [ValorenWoW/sunstrider-core#4871]
Just started a account and was getting into leveling a toon but i noticed every 20-30 seconds my frames drop for a bit and it keeps doing it over and over. thought maybe it was the area i was in maybe alot of traffic but it still doing it out of starter area and its making leveling unplayable. never had this problem before with others servers. Any ideas whats causing this?

**Comment by ghost** [comment]
disable Hardware Cursor in Video Options
