### ISSUE TITLE
Holy Nova doesn't cause guards to attack the caster

### ISSUE THREAD

**Issue by BasedForfrost** [ValorenWoW/sunstrider-core#4872]
Not sure if this is a bug or not, but this is something that could easily be abused by griefers that I discovered accidently. It appears that since Holy Nova causes no threat, guards don't seem to care if you hit enemy players with it, so you can attack Hunters and Warlocks for instance who have pets set to defensive and be killed by the guards because their pet defended them.

1. Go to a populated neutral zone such as Area 52.
2. Cast Holy Nova on an enemy player
3. The guards don't attack the caster

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
