### ISSUE TITLE
karazhan curator, not resetting properly

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4874]
if you reset curator (by running to hallway before the 2 arcane dudes), you often get stuck in combat and he continuously re-engages even if you stay in that hallway.

**Comment by Jerrythemagicdog** [comment]
Sounds like they're not sufficiently far enough then.

**Comment by michaelkittrell** [comment]
i think you are mistaken...  something, an effect or a pet or someone not being dropped from combat is is causing curator to re-agro from 100+ yards over and over and over.  only way to fix it is to alt-f4 and log back in.   seen this go on for 3-4 straight minutes.
