### ISSUE TITLE
Items disappearing for bank and bags

### ISSUE THREAD

**Issue by Ha3a** [ValorenWoW/sunstrider-core#4875]
**Describe the bug**
Items keep disappearing from my character, usually the get mailed back to me, but not always.
Last night I put my  [Lamp of Peaceful Radiance] to my bank before kara to make room for more shards and after raid it was gone. After raid I continued to farm some motes of mana and logged out with 6 primal manas and 4 motes of mana, in the morning I had 4 motes of mana and another stack that had 6 motes of mana.

This is intermittent but it has been going on for quite a bit now. I have some screenshots where some of my items have been sent back to my character a bit later.

**Character name**
Kidder

**To Reproduce**
Intermittent

Item: 
https://www.wowhead.com/item=28412/
https://www.wowhead.com/item=22457

**Expected behavior**
Items not disappearing from my bags or bank

**Screenshots/videos**
https://media.discordapp.net/attachments/815141002531831858/821167742203199518/unknown.png
Example how items get mailed back

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
The item is in your mailbox.
