### ISSUE TITLE
Nightbane did not drop SSC quest item

### ISSUE THREAD

**Issue by endlessggg** [ValorenWoW/sunstrider-core#4876]
**Describe the bug**
My guild group (<HYPE> - Raid Leaders were Havocswurm and Rafflington) cleared Kara last night.  After we downed Nightbane, I went to loot the dragon and it did not provide the quest item to me.  After checking my quest log, the quest is bugged out in my log.  There is no quest text.  I would like to get my quest item, please.  :)

**Character name**
Yugepenance

**To Reproduce**

1. I tried looting the dragon several different times to no avail.
2. 
3. 

Item: https://www.wowhead.com/item=31751/blazing-signet
Quest: https://www.wowhead.com/quest=13431/the-cudgel-of-kardesh
Spell: https://www.wowhead.com/spell=39145/the-mark-of-vashj

**Expected behavior**
When we killed the boss, I got my quest item.

**Screenshots/videos**
Here is a shot of my quest log.  However, I didn't get Nightbane quest loot.  My raid group can vouch that I didn't get the item and the quest is messed up.

![image](https://user-images.githubusercontent.com/81241448/112168686-83222700-8bbf-11eb-95c3-7dafc1458aee.png)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
That's not the correct quest, you need to hand that one in and take the next one.

**Comment by endlessggg** [comment]
That's the problem - I can't.  Here is me picking up the quest from quest giver

![image](https://user-images.githubusercontent.com/81241448/112193939-5fb6a680-8bd6-11eb-9435-918808ae7d97.png)
