### ISSUE TITLE
2 set Oblivion Raiment set bonus not working 

### ISSUE THREAD

**Issue by arcanewater11** [ValorenWoW/sunstrider-core#4877]
**Describe the bug**
I have 2-peice Oblivion Raiment and I'm not getting any increased mp5  

**Character name**
Arcanewater

**To Reproduce**
1. I have the gloves of Oblivion and the Spaulders of Oblivion. So shoulders and gloves. 
2. I have tested both in combat and ooc mana regen. Both visually and via my characters stat sheet. 
3.  I did multiple checks and timed my mana regen with 0 change to the mana ticks other than the very small loss of mp5 from int when I take the gloves off. 

https://www.wowhead.com/item=27778/spaulders-of-oblivion?bonus=6710 
https://www.wowhead.com/item=27537/gloves-of-oblivion?bonus=6710

**Expected behavior**
My spirit gives me 267 mana per 5 when not casting and i'm getting about a 106 every 2 sec with  or without the set bonus. A bonus of 45 mana per 5 should increase these ticks by 18/every 2 secs but its clearly not. 
**Screenshots/videos**
https://imgur.com/gallery/HAiBmNu
**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Read the tooltip very carefully.
