### ISSUE TITLE
I have completed "The Second and Third Fragments" but can't turn in. 

### ISSUE THREAD

**Issue by Goarr939** [ValorenWoW/sunstrider-core#4879]
**Describe the bug**
In my quest log it says that the quest "The Second and Third Fragments" is complete but I can not turn it in to Khadgar. The ? remains silver despite the fact my quest log says complete. 

**Character name**
Goarr

**To Reproduce**

https://www.wowhead.com/quest=9832/the-second-and-third-fragments

**Expected behavior**
I would be able to turn in the quests. 

**Screenshots/videos**

**Additional context**
I relogged my account and my characters and still could not turn in.

**Comment by michaelkittrell** [comment]
did you perhaps bank the fragments?

**Comment by Goarr939** [comment]
thanks, but both fragments in my bags. I moved them to all of my different bags as well.

**Comment by Goarr939** [comment]
I have also tried loading with all addons turned off and still nothing. I don't want to re-do the quest if I don't have to but ultimately if I have to I will.

**Comment by Jerrythemagicdog** [comment]
Could you provide a screenshot of your quest log with the objectives complete?

**Comment by Goarr939** [comment]
![WoWScrnShot_032421_144947](https://user-images.githubusercontent.com/81281041/112381480-3ec28400-8cb0-11eb-8939-e6f491f3636a.jpg)

**Comment by Goarr939** [comment]
l
![WoWScrnShot_032421_145159](https://user-images.githubusercontent.com/81281041/112381695-7f220200-8cb0-11eb-8a52-ac4a39845afe.jpg)

sorry this one highlights the right quest

**Comment by Goarr939** [comment]
Sorry not 100% sure on the process here. Does someone involved with the server look at these, do we solve these as a community?

Just unsure if I wait for a fix on something like this or just try and delete the quest and the items and start again (I mean I would prefer not to). Not really sure on how Github works, I am unaware if the people responding to this post are people associated with the operation of the server or just other people from the community that play popping on to offer what help they can and I am not familiar enough with Github to find these answers myself, I apologize if I seem naive.
