### ISSUE TITLE
Sanctity Aura Is currently applying 10% increased damage to Ranged attacks

### ISSUE THREAD

**Issue by Fishcowduck** [ValorenWoW/sunstrider-core#4880]
As title states Sanctity Aura is applying to Ranged attacks (Unsure if its only improved Sanc Aura or normal also)

Have a pally with Sanctity Aura in a hunters group and he will receive the benefits of the buff on all ranged attacks.

**Comment by kelno** [comment]
Thanks, fixed with next server update
