### ISSUE TITLE
vendor for arena points S2 / S1 gear

### ISSUE THREAD

**Issue by Grizellda** [ValorenWoW/sunstrider-core#4881]
Name: Grizelda

In Area52(Netherstorm) There are two vendors for the pvp arena iteems. One sells Gladiator (S1) and the other Merciless (S2). S1 / S2 offers for the same number of arena points and people who don't know about it can be confused and mistakenly buy a class of worse gear for arena points. I accidentally bought shuders like this today and GameMaster refused to return them to me. Please fix and delete the arena vendora that sells S1 gear so that people don't lose gear unnecessarily or please reduce the number of arena points to S1 as it should be

Thank you

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
