### ISSUE TITLE
tk instances, nethergon mana/health pots

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4882]
nethergon mana/health pots don't seem to be dropping in bot/mech/arc.

**Comment by michaelkittrell** [comment]
noticed some nethergon potions dropping in TK last week off of trash.

**Comment by kelno** [comment]
Checked now, drop rate seems to be okay. I didn't check for every NPC but I could see some NPC in each of those instances do drop it.
