### ISSUE TITLE
essence of earth 

### ISSUE THREAD

**Issue by ffeyde42** [ValorenWoW/sunstrider-core#4883]
essence of earth is not dropping from elementals. I killed 102 of the desert rumblers in Sithilis tonight and zero drops. I looted numerous random greens, 2 blues, and a purple, but no essence. 
The problem with this is that Thorium shield spikes require that essence, which currently only seems to be dropping from random chests. I did test it in the badlands for about 15 mins also with no drops.

Whatthe is name on Windrunner

https://classic.wowhead.com/npc=11746/desert-rumbler

**Additional context**
I jumped on retail to make sure they do drop and looted 4 in five minutes

**Comment by kelno** [comment]
Thanks for reporting.
They currently have 2.5% drop chance. Which seems consistent with what WoWHead classic says (2%). With this very low chance, you probably just were unlucky.
