### ISSUE TITLE
Items getting deleted from bags

### ISSUE THREAD

**Issue by Ha3a** [ValorenWoW/sunstrider-core#4884]
**Describe the bug**
Items disappear from bags. This has been going on for a while. I have no clue what is causing it but it is very annoying and would love if someone could checkout what is wrong with my character.
Previously you returned my arca offhand that had got deleted, but still missing 6 primal mana that were deleted at the same time.
Today after running some dungeons I relogged and I lost 15x large prismatic shards as well as 14x spirit shards from my bags.
Also after that I cannot turn in even when I have the daily heroic item in my bags.

Also an auction of mine did not sell and didn't get the item mailed back to me in the auction expired mail

Some items that are deleted are returned to me by mail but not all.

**Character name**
Kidder

**To Reproduce**

Be online or log out.

Item: 
https://www.wowhead.com/item=22449/large-prismatic-shard
https://www.wowhead.com/item=22457/primal-mana
https://www.wowhead.com/item=28558/spirit-shard

**Expected behavior**

Items not get deleted from my bags

**Screenshots/videos**

Picture of daily heroic quest with quest item
https://media.discordapp.net/attachments/795738924252135425/825054239217811506/unknown.png?width=1161&height=520

Picture of my mailbox
https://cdn.discordapp.com/attachments/499981636964974614/825056450132050021/unknown.png

Picture of auction expired mail
https://cdn.discordapp.com/attachments/499981636964974614/825056855646404638/unknown.png

**Additional context**

**Comment by Ha3a** [comment]
Cannot confirm if  a soul bag has been causing this, but after I unequipped  [Box of Souls] this hasn't happened for a few days.

**Comment by Jerrythemagicdog** [comment]
Thanks for the details.

**Comment by Jerrythemagicdog** [comment]
The issue should be resolved now. Please leave a comment in the issue if you're still having trouble.
