### ISSUE TITLE
Quest: [Threat from Above] doesn't track kills

### ISSUE THREAD

**Issue by DaturoDewitt** [ValorenWoW/sunstrider-core#4886]
**Describe the bug**
Killing Ogres in The Barrier Hills don't count towards the quest

**Character name**
DaturoDewitt

**To Reproduce**
1. Start quest
2. Try killing the different Ogre variants
3. None appear to progress quest

Quest: https://www.wowhead.com/quest=11096

**Expected behavior**
Ogre kills progress quest

**Screenshots/videos**
Imagine ogre corpses and an sad Daturo

**Additional context**

**Comment by Jerrythemagicdog** [comment]
They do, you were probably in a raid.
