### ISSUE TITLE
Launcher stuck on initializing.

### ISSUE THREAD

**Issue by initializingg** [ValorenWoW/sunstrider-core#4887]
So, i downloaded and installed the launcher just fine. no issues, allowed it access through firewall. But it is just stuck at initializing 0%. hasnt budged in over 30 mins. my internet is running great, speedtest says im getting 150-200 mb/s down. And my computer was built less than a week ago. im at a loss here.

I have also tried deleting and reinstalling the laucnher, and rebooting my PC. still just initializing.

**Comment by Jerrythemagicdog** [comment]
Try reinstalling the Launcher, some users are experiencing issues when the launcher is blocked by their firewall.
