### ISSUE TITLE
Hunter pet respawning dead in BGs

### ISSUE THREAD

**Issue by jasel99** [ValorenWoW/sunstrider-core#4888]
**Describe the bug**
When hunter pet gets killed in battlegrounds, after you die and spawn at the graveyard, the pet is spawned dead with you at the graveyard.

**Character name**
Neighy

**To Reproduce**

1. Have your pet die in a battleground
2. Die yourself
3. Get resurrected at the graveyard by the spirit healer

**Expected behavior**
When you spawn, the pet will also spawn with you but it will be dead, so you must use Revive Pet to bring it back to life.

**Additional context**
If you leave the battleground while your pet is dead, and revive it by using Revive Pet when outside the battleground, the pet also loses happiness.

**Comment by kelno** [comment]
Thanks, fixed with next server update
