### ISSUE TITLE
Netherwing Eggs

### ISSUE THREAD

**Issue by bugseeker159** [ValorenWoW/sunstrider-core#4889]
**Describe the bug**

Not enough Netherwing Eggs' spawn locations at Shadowmoon Valley, there are only 5 locations that always spawn eggs the other 30+ locations don't work.
The eggs found respawn every 3 hours (normally 15 minutes to 2 hours), the dynamic respawn implemented in the server doesn't reduce the timer.

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item : https://tbcdb.com/?item=32506

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
They're pooled all over the Netherwing Isle and parts of Shadowmoon Valley near the Dragonmaw Fortress, there aren't that many of them up at the same time though.
