### ISSUE TITLE
"Enslaved Netherwing Drakes" are missing in the game

### ISSUE THREAD

**Issue by PawOrmstrupMadsen** [ValorenWoW/sunstrider-core#4891]
**Describe the bug**
"Enslaved Netherwing Drakes" are missing in the game, which is a required mob to complete "The Force of Neltharaku"

**To Reproduce**
1. Go to Dragonmaw fortress, they should be enslaved by Subjugators.

Quest: https://wowhead.com?quest=10854/the-force-of-neltharaku

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/11302862/112737648-46a65080-8f5c-11eb-9cc9-8a9451030951.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, they're there just on a long respawn timer.
Fixed with the next update.
