### ISSUE TITLE
Alliance druid quest - "Heeding the Call" (quest ID 5924) not available at any trainers

### ISSUE THREAD

**Issue by greedyf00x** [ValorenWoW/sunstrider-core#4892]
**Describe the bug**
Quest "Heeding the Call", on of the entry quests which should lead druid to his "Teleport Moonglase" (spell id 18960) is not available for taking from any druid trainers on alliance side.

**Character name**
Rictusempra - Realm: Sunstrider

**To Reproduce**
1.  Travel to Teldrasil (or Stormwind)
2.  Find druid trainer named Kal [NPC ID 3602] (or in case of Stormwind, Theridran [NPC ID 5505])
3.  Conclude no entry quest is available

Quest: https://wowhead.com?quest=5924
Spell: https://wowhead.com?spell=18960

**Expected behavior**
Quest chain shall be obtainable for alliance druids

**Screenshots/videos**
N/A

**Additional context**
N/A

**Comment by Jerrythemagicdog** [comment]
The quest is autocompleted for you due to autolearn.
