### ISSUE TITLE
Teleport moonglade spell not available for Alliance druids

### ISSUE THREAD

**Issue by greedyf00x** [ValorenWoW/sunstrider-core#4894]
**Describe the bug**
I dont have teleport to Moonglade spell, and all spells are learned from the trainer.

**Character name**
Rictusempra (Server - Sunstrider)

**To Reproduce**
1. Open spellbook
2. Search spells
3. Conclude that teleport moonglade is not available

Spell: https://www.wowhead.com/spell=18960/teleport-moonglade

**Expected behavior**
Castable teleport spell shall be available in spellbook.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
It wasn't taught to you due to a mistake with the autolearn system, we'll teach it to you directly in game.
