### ISSUE TITLE
Hunter Pet/Pathfinding in general/LOS

### ISSUE THREAD

**Issue by norbi33** [ValorenWoW/sunstrider-core#4895]
So hunters or any class with pet have wierd pathfinding what i mean with this is:
For example:
**AV**:
1#when you go down from the middle graveyard your pet going in a big circle to get down ther
2#Some to the bunkers meanwhile warrior can charge up on the bunker while my pet walks down.. or up
**WSG**:
1#the trees on the middle you can shot through (spells,ranged attack) have no LOS
2#Other bg's i diden't try but i'm sure they are more then just this.
**Pet problems**:
1# they take some % aoe dmg like a player do which have to be reduced by the pet special ^ability^
2#If a pet dies in a bg which was reported i see but still you have to revive it afther you released so the spirit healer wont revive it.
3#Pet sometime stuck what i mean with this they just stand in a place and you can't do anything with them you have to dissmiss and resummon to get them working.

**Comment by Jerrythemagicdog** [comment]
Thanks, issue has been resolved since then.
