### ISSUE TITLE
Kirin'var village dancing sword

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4897]
some mob near the town hall summons a dancing sword.  this sword persists way too long after its master dies.  Literally had it autoing me for 5+ minutes around 1000 yards from where it was originally spawned and attacked me.  (it de-agro'd or timed out at around 55.15, 84.95 which is extremely far from where it spawned/spawns).

had the same issue twice in the same questing session

**Comment by Jerrythemagicdog** [comment]
The summon duration is 30 seconds, but it seems to disregard the duration if currently in combat.
Thanks, fixed with next update.
