### ISSUE TITLE
naberius, kirin'var village, stuck in combat

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4898]
naberius spawns some purple ground effect that does damage.   After killing naberius, it persisted for 5+ minutes (probably 10+ minutes) and prevented me from exiting combat.  Killed several mobs, which didn't help me drop combat.   Tried logging out / alt-f4/sit macro and instead just got insta killed (in combat at time of logout).  

the ground effect (several minutes after killing naberius)
![image](https://user-images.githubusercontent.com/5479930/112752775-80da1700-8f89-11eb-8d61-36483e40c717.png)

this is where i finally "de agro'd".   pretty freaking far and 5+ minutes after naberius was killed.
![image](https://user-images.githubusercontent.com/5479930/112752781-8d5e6f80-8f89-11eb-9c57-941e537dfdf5.png)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, but the void zone lasts 26 seconds, can't make this happen.
