### ISSUE TITLE
when the cows come home, kirin village quest (and other "group" quests)

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4899]
When cows come home is supposed to be a group completable quest... at least when you start it, it asks the other members of the group if they want to accept it.  Did the quest literally 5x.   Clicking accept on all other members in the group (not a raid).   Only the person who started the quest ever got completion credit.

**Comment by michaelkittrell** [comment]
Same/similar issue with the robot escort quest near the RUins of Enkaat (ns)  (did 1x, no one else got credit)

same/similar issue with the Drijya needs your help quest (ns near eco dome) (did 2x, no one else got credit).

**Comment by Sheikthecatman** [comment]
I just tested [When the Cows Come Home](https://www.wowhead.com/quest=10337/when-the-cows-come-home) and it credited the whole group, [Sabotage the Warp-Gate](https://www.wowhead.com/quest=10310/sabotage-the-warp-gate) has the same credit logic.

Make sure to do these in a party and not a raid.

**Comment by Sheikthecatman** [comment]
[Mark V is Alive!](https://www.wowhead.com/quest=10191/mark-v-is-alive) Same logic there.

**Comment by michaelkittrell** [comment]
i don't think i was in a raid, but its possible...  however if i was in a raid, no one should've gotten credit.  
I literally dhad to do the quest 5x with a different toon starting it each time.
