### ISSUE TITLE
Meeting at the Blackwing Coven, blades edge quest

### ISSUE THREAD

**Issue by cramslan** [ValorenWoW/sunstrider-core#4902]
**Describe the bug**
Costume in quest "Meeting at the Blackwing Coven" breaks immediately upon engaging in dialogue with npc Kolphis Darkscale.

**Character name**
Shoujotwo

**To Reproduce**
Get the 5 costume scraps from the cultists in and around the cave Kolphis is in. Make the costume, and attempt to speak to Kolphis Darkscale who becomes friendly when the costume is on. I have tried this at least six times but always the costume breaks when I right click on Kolphis. At first I thought it was because I had healed my pet (who doesn't get the disguise buff), and then tried again with pet released. As soon as I right click to speak with him, I can't make it to further dialogue because the disguise breaks and Kolphis is unfriendly again.

https://www.wowhead.com/quest=10722

**Expected behavior**
Once I put on the disguise, I should be able to speak with Kolphis Darkscale and continue dialogue with him.

Probably intended behavior: warlock and hunter pets should also get the Overseer Nuuar buff, cultists in the cave should probably become friendly when the Overseer Nuuar costume is on. (I don't know this for certain)

**Comment by Jerrythemagicdog** [comment]
Can't reproduce, all cultists including Overseer are friendly.
Try clearing your Cache, disabling Addons and trying agian.
