### ISSUE TITLE
Frankly, It Makes No Sense... quest bugged

### ISSUE THREAD

**Issue by Shaacks** [ValorenWoW/sunstrider-core#4903]
**Describe the bug**
For this quest you are supposed to click on an item that allows you to mind control a scorpion to tag the mobs. (That's the objective of the quest) The item to mind control doesn't work and doesn't allow me to complete the quest.

**Character name**
Shaacks

**To Reproduce**
1. Click on the MC device. 

Quest: https://www.wowhead.com/quest=10672/frankly-it-makes-no-sense

**Expected behavior**
To MC the scorpions

**Comment by Jerrythemagicdog** [comment]
Possibly because the scorpions are currently mind-controlled.

**Comment by Shaacks** [comment]
False. No one was around during the quest
