### ISSUE TITLE
The Battle of Darrowshire - Quest is not working

### ISSUE THREAD

**Issue by greedyf00x** [ValorenWoW/sunstrider-core#4906]
**Describe the bug**
Last quest of the chain - The Battle of Darrowshire [questID 5721] is not working. After placing Relic Bundle in center of Darrowshire, the battle wont start

**Character name**
Insendio - Sunstrider

**To Reproduce**
1. Go to Darrowshire in Eastern Plaguelands
2. Locate the town center (near the well)
3. Right click on Relic Bundle from your bag to place it in the town center
4. Wait couple of minutes - Nothing happens

Item: https://db.endless.gg/?item=15209
Quest: https://db.endless.gg/?quest=5721

**Expected behavior**
After placing the Relic Bundle in center of the town, undead armies shall start approaching from 4 directions and attacking the village and its inhabitant spirits.

**Screenshots/videos**

**Additional context**

**Comment by z5n** [comment]
closing in favor of #5642, more recent
