### ISSUE TITLE
Bugs with relic ( totem of astral winds)

### ISSUE THREAD

**Issue by Wishuuwell** [ValorenWoW/sunstrider-core#4907]
**Describe the bug**
I tested with 1 rank wf, damage did not increase from proc

**Character name**
 Wishyouwell

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Wishuuwell** [comment]
https://www.wowhead.com/item=27815
https://www.wowhead.com/spell=32911

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
