### ISSUE TITLE
My bad, taking the wrong quest from the violet eye

### ISSUE THREAD

**Issue by Killblitz** [ValorenWoW/sunstrider-core#4908]
**Describe the bug**
isnt a bug, is my bad taking the wrong quest

**Character name**
Killblitz

**To Reproduce**
Hi i take the wrong ring from The Violet Eye quest, please can u reset it? ty!
i take https://tbcdb.com/?quest=10729 Path of the Violet Mage
when i should have taken https://tbcdb.com/?quest=10731 Path of the Violet Assassin
already deleted the ring Violet Signet https://tbcdb.com/?item=29284
Please help me, tyvm

**Expected behavior**
You can reset this quest ID=10729 from my char: Killblitz  with GM privileges

**Comment by Jerrythemagicdog** [comment]
You can pick the other ring once you reach Exalted with the Violet Eye
