### ISSUE TITLE
Endless.gg purchased triple specialization and its now gone

### ISSUE THREAD

**Issue by Seeya99** [ValorenWoW/sunstrider-core#4911]
**Describe the bug**

I purchased triple specialization and was using it fine for the last few weeks... and now its gone??
**Character name**

Seeya
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
"Seeya" has 3 specializations available.
Make sure you're looking at the right character on the website.
