### ISSUE TITLE
Mana Tombs Quest : Someone Else's Hard Work Pays Off

### ISSUE THREAD

**Issue by Timespent** [ValorenWoW/sunstrider-core#4913]
THIS IS ON THE WINDRUNNER FRESH SERVER

**Describe the bug**

I formed a group and cleared all of Mana tombs on normal mode. The starter quest that you pickup outside has you kill mobs in the dungeon then turn in that quest to an NPC in the dungeon to begin a new escort quest. After we tried the escort and wiped we reset the instance to try again. When we cleared again, the npc was not there, and there was no way to make him spawn without turning in the previous quest.

**Character name**

Timespent, Prot pally

**To Reproduce**

1. Start and turn in https://www.wowhead.com/quest=10216/safety-is-job-one
2. wipe on the following escort quest
3. reclear, see he isnt there to try again

Prequest: https://www.wowhead.com/quest=10216/safety-is-job-one
Quest: https://www.wowhead.com/quest=10218/someone-elses-hard-work-pays-off

**Expected behavior**

The npc should be accessible to those who are trying to retry the quest.

**Comment by Timespent** [comment]
Possibly a continuation of this problem? https://github.com/SunstriderEmu/BugTracker/issues/677 Since I'm not "turning in" the previous quest anymore as I had wiped on It once already.

**Comment by hotdogsteven** [comment]
![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/0ffcc087-1085-41b5-98dd-eace05b4b821)
gossip menu should show up if you have https://www.wowhead.com/tbc/quest=10216/safety-is-job-one completed but not https://www.wowhead.com/tbc/quest=10218/someone-elses-hard-work-pays-off

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
bf4a641c1cbc1ad3485d409ae045005845c92836
