### ISSUE TITLE
Shadow Labs Frag Key 

### ISSUE THREAD

**Issue by vvvenzyme** [ValorenWoW/sunstrider-core#4914]
**Describe the bug**
Have the quest for Kara Attune to get 1st key frag from Shadow Lab - druid looted it and key disappeared and did not respawn 

**Character name**
Classicgamer

**To Reproduce**
Druid started looting the object and I waited for his cast timer to go off. He looted it and the key disappeared and did not respawn. 

https://www.wowhead.com/quest=9831/entry-into-karazhan#comments

**Expected behavior**
Key frag would respawn or still be accessible? 

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The key fragment is not in the object but in a creature that spawns next to the object.
