### ISSUE TITLE
Druid swift flight form "no mere dream" quest bugged

### ISSUE THREAD

**Issue by ScaredMoney** [ValorenWoW/sunstrider-core#4915]
**Describe the bug**
On the quest chain for the druid swift flight form. "No mere Dream" is bugged. Clintar Dreamwalker is supposed to start the escort quest in a spirit form , but it never starts. many sites say to accept it in unshifted form which I have tried. Also abandonned and reaccepted many times. Also made sure grasp of the emerald dream debuff wears off. Also tried logging in and out many times.No progress can be made. Windrrunner Server. Totally felt like I watsed 5k gold.

**Comment by Jerrythemagicdog** [comment]
The quest is completed, you just have to talk to Dreamwarden Lurosa.
The RP event is missing.
