### ISSUE TITLE
Flask is not persisting thru death

### ISSUE THREAD

**Issue by Comebackbabe** [ValorenWoW/sunstrider-core#4916]
Issue:
I have attempted to flask 5 times on this server during my 10 man kara guild raids. every single time we die in that dungeon i lose the flask, i have asked multiple people about the situation and no one can seem to tell me what is going on. Also i have not found a single other person suffering from this same issue. I have also tried to run no addons and it still happens. Im not sure exactly what is happening here but i do know i haven't been able to use my flask properly on this server because of it not persisting thru death for me. i have many guildmates that can confirm that this is happening to me as well.

**Character name**
Comebackbabe
https://endless.gg/armory/character/comebackbabe

**To Reproduce**
1. Be Comebackbabe
2. Die in kara with a flask on
3. lose flask

https://tbc.wowhead.com/item=22866/flask-of-pure-death

**Expected behavior**
I would like to have the flask i have used to be restored but more so i need the item to be fixed so i can properly consume and play the game

**Additional context**
im not sure exactly how to recreate this on another toon, or even if it is affecting anyone else but me. but what i do know is it is happening to me right now at a 100% rate of consistency.

**Comment by Comebackbabe** [comment]
possible pervious problems with flask #4468 and #4059 with the same issue also i have tried reviving via res and release in several situations and it always results in the lose of my flask well within the 2hr mark

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue. I've tried to reproduce with a copy of your character with no success.
Perhaps it has something to do with you using Elixir of Shadow Power or Elixir of Major Shadow Power?

**Comment by Comebackbabe** [comment]
> Thanks for the issue. I've tried to reproduce with a copy of your character with no success.
> Perhaps it has something to do with you using Elixir of Shadow Power or Elixir of Major Shadow Power?

hi thanks for reply currently doing some texting could be due to something specific to kara or being in a raid group. i will try to recreate tomorrow with similar conditions
