### ISSUE TITLE
A Necessary Distraction is impossible to complete

### ISSUE THREAD

**Issue by Hanilforever** [ValorenWoW/sunstrider-core#4917]
The Scroll of Demonic Unbanishing, which should have a 35% drop rate, does not drop at ALL off of Sunfury Warlocks. I tried to complete this quest for an entire hour, to no avail. Without the Scroll drop, the quest can't be completed.

**Character name**
Hanil

**To Reproduce**
1. Just accept the quest from the Aldor hub in Shadowmoon Valley, and attempt to collect the Scroll from the Sunfury Warlocks.

Quest: https://www.wowhead.com/quest=10637/a-necessary-distraction
Item: https://www.wowhead.com/item=30811/scroll-of-demonic-unbanishing

**Expected behavior**
Again, you should be able to loot the Scroll off of Sunfury Warlocks. It appears that they either don't actually have it on their loot table, or the drop rate is somehow extremely, extremely low.

**Comment by Jerrythemagicdog** [comment]
I can assure you that the quest does work, it's been completed thousands of times.
The drop rate of the scroll is 35% from Sunfury Warlocks (21503) and Sunfury Summoners (21505).

**Comment by Hanilforever** [comment]
Okay, well that's certainly strange, because I dropped and re-picked up the quest twice, and spent an entire hour farming them and received nothing. So maybe you could, I don't know, look into it, since that's the nature of a bug report.

**Comment by Hanilforever** [comment]
Maybe I should have mentioned that this is on Windrunner, and not Sunstrider.
