### ISSUE TITLE
Level 70 Character boost!

### ISSUE THREAD

**Issue by Dtrushx** [ValorenWoW/sunstrider-core#4919]
**Describe the bug**
I boosted my character to 70 - In-game name Dtrush and did not receive friendly factions as stated in the description. Instead i got a message from GM Artie, telling me to go fuck myself.

**Character name**
Dtrush

**To Reproduce**

1. Buy level 70 boost
2. Have GM's tell you to go fuck yourself
3. Never get refunded

Item: 
Quest: 
Spell: 

**Expected behavior**
Pissed off customer.

**Screenshots/videos**

**Additional context**
Please fix this or acknowledge you made a mistake, and correct the issue.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Your reputations were corrected.
I don't see why would you say a GM told you "to go fuck myself". That's not what happened at all.
The GM informed you that you can do dungeons without having Friendly reputations, which is true.
