### ISSUE TITLE
ssc, morrowgrim fast reset + trash respawn

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4920]
was doing ssc morrowgrim...

during a pull (at 18% or so), murlock trash respawned and wiped us.

releasing was governed by fast reset which was a bit unfortunate since trash was pathing.

we eventually made the call to unstuck after people repeating failing to get 25 people to release at the right time.  So we made the call to unstuck.  at some point someone must've released, agro'd the murlocks again and they zone tp'd and wiped the raid again.   the people who released (killed at elevator in ssc) were still under the fast reset effect... when they released, back to morrowgrim's room.  

at this point 90% of the raid had unstuck cooldown, and the rest effectively can't release because everytime they do they ress in morrowgrims room surrounded by murlocks.  this condition persisting at least 20m.

raid id 209151,  this ticket made during the issue if you want to analyze the logs and figure out what went wrong

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
