### ISSUE TITLE
accidental/fast pulls don't trigger fast reset.

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4922]
We were trying some speed kills tonight and on pull someone insta died so we wiped it.  Expected to reset, instead released to the graveyard.  

this also sucks when a hunter feigns death after a wipe and stands up and pulls the boss (or trash respawn) because they were too close, now everyone is releasing at graveyard.  simiar things happens if someone takes a soulstone... or uses the sit macro/login on 2nd client to force dc themselves.  If they login too close to boss, wipes and clears the fast reset condition.

I assume the fast reset doesn't trigger unless you do enough damage or after a certain duration of a pull/fight or if the raid is also fighting random trash....  but having to run back because of a mistake like this seems counter to the goals of the fast reset feature.  You probably don't want people bubble and running through dieing to boss and fast reseting the raid, but im sure a solution can be devised that prevents that while not forcing 25 people to make a 10m run back to morrowgrim because of a huntard.

**Comment by Jerrythemagicdog** [comment]
The boss needs to be engaged for some time in order for the reset feature to trigger to prevent abusing the feature.
