### ISSUE TITLE
Beast Lord Mantle

### ISSUE THREAD

**Issue by Jakoovs** [ValorenWoW/sunstrider-core#4924]
Hey,

on the server Windrunner I was in "The Steamvault" and the endboss dropped the "Beast Lord Mantle" ... I pressed NEED with my hunter (Lovac) and the other players greeded the item. Something went wrong and it counted mine as well as greed and now a druid got the item who doensn't need it. And the item is not tradeable... The name of the druid is "Sepit" ... The item is still in his inventory. 
Can you transfer the item to my hunter lovac? I farmed shoulders now for days and now this bug occured... Please help me.

**Comment by Jerrythemagicdog** [comment]
There is no player named "Sepit" on the server.
