### ISSUE TITLE
Caged Squirrel Duplicates in Undercity Cause FPS Drop

### ISSUE THREAD

**Issue by Mortisanti** [ValorenWoW/sunstrider-core#4929]
**Describe the bug**
There are countless duplicates of Caged Squirrel NPCs spawned inside of the cages within The Apothecarium of Undercity. When facing the camera toward the room, FPS drops to ~24.

**Character name**
Moltisanti

**To Reproduce**
1. Log into the Windrunner realm
2. Navigate to The Apothecarium in Undercity
3. Go down the ramps and stairs until you're in the alchemist room below with hanging bodies and tesla coils
4. Locate the southeastern room with caged NPCs, turn camera toward the room, and walk in to notice FPS plummet

NPC (ID: 5739): https://classic.wowhead.com/npc=5739/caged-squirrel

**Expected behavior**
I am assuming there should only be one Caged Squirrel NPC, but instead there are 20+ which causes the FPS to plummet when viewing the room.

**Screenshots/videos**
[Screenshot](https://i.imgur.com/OM4jlDe.jpg)

**Additional context**
Server: Windrunner

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
