### ISSUE TITLE
Zanzil Touch debuff rogue quest

### ISSUE THREAD

**Issue by Revan255** [ValorenWoW/sunstrider-core#4930]
**Describe the bug**
Well i finish the quest of rogues but i stayed with the 7 days debuff of zanzil's touch

**Character name**
Revhan

**To Reproduce**

1. I simply finish but the debuff dont disappear
2. 
3. 

Item: dont have any
Quest: https://classic.wowhead.com/quest=2609/the-touch-of-zanzil
Spell: https://pt.classic.wowhead.com/spell=9991/toque-de-zanzil

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
The quest is automatically finished for you when you reach an appropriate level due to autolearn.
