### ISSUE TITLE
Meeting at the Blackwing Coven

### ISSUE THREAD

**Issue by Bins2130** [ValorenWoW/sunstrider-core#4931]
**Describe the bug**
Upon gathering the 5 cloth scraps to make into an overseer uniform and using it near the quest mob within about 5 sec it bugs and puts you back to your normal character form.  I attempted this 6-7 times (very tedious having to gather the 5 scraps again and again), trying different things like dismissing pet and using literally last second to run in and do the dialogue.  Everytime it dropped just before I could get through it

**Character name**
Bellaya

**To Reproduce**

1. Gather 5 scraps
2. Use them to create Overseer Uniform - use said uniform
3. Try to talk to NPC to get through dialogue (failing halfway through and losing disguise)

Quest: https://www.wowhead.com/quest=10722/meeting-at-the-blackwing-coven

**Expected behavior**
Disguise should hold until removed or until it times out (this is the behavior my first character had with this quest

**Screenshots/videos**

**Additional context**

**Comment by z5n** [comment]
can't reproduce
