### ISSUE TITLE
cant log on my caracter

### ISSUE THREAD

**Issue by avermed123** [ValorenWoW/sunstrider-core#4932]
cant log on my caracter on account always got disconect when i log in game

**Comment by InhumanGM** [comment]
Character name?

**Comment by avermed123** [comment]
Spacecreater

**Comment by avermed123** [comment]
i need spam Ustuck and its help me to log

**Comment by avermed123** [comment]
without unstuck i cant log, today i have similar problem

**Comment by avermed123** [comment]
i log in world and in one second i got disconect

**Comment by avermed123** [comment]
i can log on my other characters without problems, but cant log on only Spacecreater

**Comment by avermed123** [comment]
why nothing changes??

**Comment by avermed123** [comment]
i even cant log on my character

**Comment by avermed123** [comment]
20 hour left and i stil cant log in world

**Comment by InhumanGM** [comment]
It's a problem with your client, I advise a reinstall. If it happens again, create a ticket in-game.
