### ISSUE TITLE
Dissapeared items in bag

### ISSUE THREAD

**Issue by multitnr** [ValorenWoW/sunstrider-core#4933]
**Describe the bug**
items dissapear

**Character name**
Rasist

**To Reproduce**
I saw this after buy Manuals from Burko

I dont remember really becouse i was buy new items from Auction, and manuals from Burko, it was 2021.04.07 between 23:00-23:59 UTC+2:00

**Expected behavior**
Dont know really. I only saw troubles after buying manuals from npc Burko. 

**Screenshots/videos**
no screen shots 

**Additional context**
i buyed about 5 items from auction that cost 150g, dont know names of it becouse  i was buy the best items for me.

**Comment by InhumanGM** [comment]
There are no records of any items going missing from your character.

**Comment by multitnr** [comment]
> There are no records of any items going missing from your character.

i was buy items from AH, and after take them from mail, i get only 1 ring, other just didnt appear in my bag, and dissapeared from mail. relogged and reEnter game twice...

**Comment by InhumanGM** [comment]
From what I see here, you only purchased one ring— a ring that is currently sitting in your inventory.
