### ISSUE TITLE
Warlock Pets Lose Buffs on Mount & PetAbandon script not working

### ISSUE THREAD

**Issue by nowayhoseb** [ValorenWoW/sunstrider-core#4934]
Description: A new pet is re-summoned every time the warlock teleports/mounts.

Current behavior: If Warlock mounts summoned pet will lose all non-warlock buffs after dismounting. Long established PetAbandon script does not function to preserve buffed pet.

https://web.archive.org/web/20130811112339/http://elitistjerks.com/f80/t17008-pve_raiding_compendium/

Source for "/run PetAbandon()" cases : "- Demons about to die can be dismissed and nearly instantly resummoned with Fel Domination. This will conserve their buffs, and bring them back with full health and mana. The command to dismiss a demon is /run PetAbandon(), which can be macro'd and assigned to a button."

**Comment by kelno** [comment]
Thanks, fixed with next server update
