### ISSUE TITLE
Deep Thunder does not procc the 4 second stun.

### ISSUE THREAD

**Issue by Becknarn** [ValorenWoW/sunstrider-core#4935]
**Describe the bug**

Deep Thunder does not proc the stun.

**Character name**

Becknarn (Blood elf paladin)

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item= https://www.wowhead.com/item=28441/deep-thunder
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell= https://www.wowhead.com/spell=34510/stun

**Expected behavior**
 

**Screenshots/videos**

**Additional context**

**Comment by Becknarn** [comment]
[https://i.imgur.com/YYbinVF.jpg](url)



I did a duel and did over 200 hits. 0 procs.

Also I spoke with warriors who reported no issue, could it be related to paladins?

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
This is performed with a copy of your character on the live realm.
Recount won't show you Mace Stun procs.
![image](https://user-images.githubusercontent.com/46463908/114019856-343ae980-986f-11eb-8a57-b5d9bca50bdd.png)
