### ISSUE TITLE
UBRS Pyroguard Emberseer is spawnable multiple times

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4937]
If you click the stone to start the emberseer event with two characters at nearly the same time it summons him twice.   Not sure if you can do it more than twice but probably.   Not sure what the correct behavior is, but on warmane you needed to channel the stone with 3 chars IIRC to start it.

After killing both, i immediately went through the door which closed behind me shortly thereafter.  In subsequent runs, I was careful to spawn him only once... and noted that the the doors did not close behind me like they did on the double/bugged spawn.

**Comment by Sheikthecatman** [comment]
Thanks, fixed in [38526b3a7be27f4b1a5f4d2746ef1e7477693ac8](https://github.com/kelno/sunstrider/commit/38526b3a7be27f4b1a5f4d2746ef1e7477693ac8). Update will be live next server restart.
