### ISSUE TITLE
Cant log in world on my character

### ISSUE THREAD

**Issue by avermed123** [ValorenWoW/sunstrider-core#4938]
Cant log on my character in world, always got disconect after 1 seconed when enter in world 
20 hour left nothing changes WTF?
its my second Issue and nothing changes

**Comment by avermed123** [comment]
character name Spacecreater

**Comment by avermed123** [comment]
i can log in world only if i will spam butoon Unstuck in manage characters on my account

**Comment by avermed123** [comment]
???

**Comment by avermed123** [comment]
why you close it

**Comment by InhumanGM** [comment]
> why you close it

https://github.com/SunstriderEmu/BugTracker/issues/4932#issuecomment-815952157
