### ISSUE TITLE
zg, hooktooth frenzy

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4940]
zul gurub, hooktooth frenzy fish are skinnable for rugged leather... thats probably not correct

not sure what they're supposed to drop, one link says nothing, another link says zulian mudskunk which im pretty sure should only be fishable, but i dunno

https://www.wowhead.com/npc=11374/hooktooth-frenzy#comments
https://wowpedia.fandom.com/wiki/Hooktooth_Frenzy

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
