### ISSUE TITLE
ssc, Acid Geyser boglord

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4945]
question...   should the poison spitting boglords in ssc seem to continue to spit in the first targeted direction and do not change direction relative to the person targeted.

an example would be quagmiron in sp.  If you move the direction of the poison changes vs ssc underbog collosus, once the person is targetted the poison continues to be sprayed in that same location until the effect ends several seconds later.

according to this wow article, the target should be able to change the spit direction.

https://wowwiki-archive.fandom.com/wiki/Underbog_Colossus

Acid Geyser - Does ~2k nature damage per tick over around 10 seconds in a frontal cone to a random player in range. Ranged DPS can out range being targeted since the target range is **~35 yards** (shadow priests be careful!). You can not out range the damage if someone in front of you is targeted, the target and damage distances are different. The Underbog Colossus will turn to face a random person when using this, so you cannot face the colossus away from the raid to avoid people getting hit by it - spreading people out so that not everyone gets it at once is the best way we've found to deal with it.
An effective way of reducing damage done by the Geyser is to have all members of the raid stand close to the mob, and keep an eye on who he is targeting. **The person who is targeted for the geyser should run through the mob, thereby spinning him around away from the group.** However your raid may wipe because of the spore quake...

**Comment by Jerrythemagicdog** [comment]
Thanks for the source, fixed with next update.
