### ISSUE TITLE
Quest "I work ... For the Horde!"

### ISSUE THREAD

**Issue by Limitofdetection** [ValorenWoW/sunstrider-core#4946]
**Describe the bug**
In this quest we are supposed to pick up some objects on the ground, they appear indeed shiny, but I cannot loot them

**Character name**
Lod

https://www.wowhead.com/quest=10086/i-work-for-the-horde

**Screenshots/videos**
We can see here the item shining, but when the mouse is on it, there isn't the gear to be able to pick it up:
![image](https://user-images.githubusercontent.com/82308236/114296337-178af580-9aab-11eb-9bf7-c31eb27d3278.png)

**Comment by InhumanGM** [comment]
What are the coordinates of that object?

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we've looked into it a long time ago, it's consistent with retail at the time and not something we can change.
