### ISSUE TITLE
Morcrush rare spawn

### ISSUE THREAD

**Issue by darkjesterr** [ValorenWoW/sunstrider-core#4947]
**Describe the bug**
Morcrush a rare elite spawn in Blades Edge Mountains is respawning on a 5 minute timer (should be longer)

**To Reproduce**
Kill rare, wait 5 minutes, he will spawn again in one of his spawn locations

NPC: https://www.wowhead.com/npc=18690/morcrush

**Expected behavior**
Respawn takes multiple hours

**Comment by InhumanGM** [comment]
What source do you have that shows the spawn time should be longer?

**Comment by darkjesterr** [comment]
The silver border around it...

but sure, let people make 1000g an hour killing this thing

**Comment by Jerrythemagicdog** [comment]
Fixed with next update, thanks.
