### ISSUE TITLE
Clam Meat Vendor

### ISSUE THREAD

**Issue by darkjesterr** [ValorenWoW/sunstrider-core#4948]
**Describe the bug**

Haljan Oakheart sells Clam Meat

**To Reproduce**

1. Open trade with NPC, buy Clam Meat

Item: https://classic.wowhead.com/item=5503/clam-meat
NPC: https://classic.wowhead.com/npc=3962/haljan-oakheart

**Expected behavior**

Clam Meat not sold.

**Comment by InhumanGM** [comment]
This vendor does indeed sell Clam Meat properly, the items make it into my bag with no issue. Maybe if you have a bag addon, disable it if you're not seeing the items in your inventory.

![image](https://user-images.githubusercontent.com/65207651/114308184-f5947180-9ab0-11eb-9856-5e649d90946f.png)

**Comment by darkjesterr** [comment]
The vendor is not supposed to sell Clam Meat

**Comment by InhumanGM** [comment]
What source tells you that?
According to two other databases, this vendor does sell Clam Meat in TBC:
https://tbc-twinhead.twinstar.cz/?npc=3962
https://tbcdb.com/?npc=3962
