### ISSUE TITLE
Weaponsmith quest bugged

### ISSUE THREAD

**Issue by membrillo1** [ValorenWoW/sunstrider-core#4949]
I leveled blacksmith to around 365, I went through the Weaponsmith quest and Master Hammersmith quest as well then dropped the profession a couple of weeks ago. 
Now i am lvleling it up again but i am unable to get the Weaponsmith quest from the NPC in Ogri called Krathok Moltenfist so i cant learn again the weaponsmith spec nor go through the master hammermisth quest npc in Everlook.

Character: Membrillo
This is the Weaponsmith quest.
https://classic.wowhead.com/quest=5302/the-way-of-the-weaponsmith#comments

After being weaponsmith i should be able to speak with this npc Lilith in Evelook who will be able to make me master hammersmith. https://classic.wowhead.com/npc=11191/lilith-the-lithe

Thanks!

**Comment by Jerrythemagicdog** [comment]
You can pick up the Hammersmith quest (Sweet Serenity) in Everlook, I've tried it using a copy of your character.
After you complete the quest you should be rewarded with Hammersmithing.
![image](https://user-images.githubusercontent.com/46463908/114324486-865b6380-9b2a-11eb-9782-6d7762b71019.png)

**Comment by Jerrythemagicdog** [comment]
Resolved in game.
