### ISSUE TITLE
Auto-learn and double specialization interaction

### ISSUE THREAD

**Issue by mizmar** [ValorenWoW/sunstrider-core#4951]
Spells available only on inactive specialization don't auto-learn.

1. Change to secondary specialization (through website)
2. Learn new spell from talent
3. Change to primary specialization
4. Level up, enough to be eligible for new rank of that spell
5. Change to secondary specialization
6. New rank of that spell is not auto-learned unless character reaches new level with secondary spec

**Comment by kelno** [comment]
Thanks, fixed with next server update
