### ISSUE TITLE
Quest:Field Duty (Silithus)

### ISSUE THREAD

**Issue by Noldorinriad** [ValorenWoW/sunstrider-core#4952]
**Describe the bug**
I've encounter a issue while doing a quest in Silithus the quest name is " Field Duty " given by " Windcaller Kaldon " in Cenarion Hold, after signing the Field Duty Papers and bringing it to" Krug Skullsplit " at the Orgrimmar Legion Post, Krug don't let me start the next part which is Fighting an elite lvl 60

**Character name**
" Noldorin " realm Windrunner

Quest: https://wowwiki-archive.fandom.com/wiki/Quest:Field_Duty_(Horde)

**Expected behavior**
I expected Krug Skullsplit to make me able to do the next part of the quest which is ( Reporting for duty, sir.) as seen on the screenshot, but i only see the random message above.

![Field Duty](https://user-images.githubusercontent.com/82489294/114654655-8a31e600-9ce2-11eb-8dd0-616865b866f4.png)

**Comment by z5n** [comment]
thanks, fixed with next restart
