### ISSUE TITLE
Weapon damage on Sunstrider and Windrunner

### ISSUE THREAD

**Issue by SaiyaS** [ValorenWoW/sunstrider-core#4954]
**Describe the bug**
Weapon damage does not work accordingly!

**To Reproduce**
The easiest way is with 2 simliar rings an the weapon damage ring enchant, but it is also reproducable with all kind of weapon damage sharpening or weighting stones for either melee or range weapon damage.

**Current Behavior** 
The weapon damage enchant lowers your damage and adds it up again. Which just equals out and has no use at all.

**Screenshots** Character Bowgoesskrrt on Sunstrider but I was also able to reproduce on windrunner
![WoWScrnShot_041421_222014](https://user-images.githubusercontent.com/82544419/114780169-51901c00-9d77-11eb-98c6-660fb640907f.jpg)
![WoWScrnShot_041421_222006](https://user-images.githubusercontent.com/82544419/114780175-5359df80-9d77-11eb-95d8-35e88a5e3064.jpg)
![WoWScrnShot_041421_222019](https://user-images.githubusercontent.com/82544419/114780159-4fc65880-9d77-11eb-86e2-eed27c748867.jpg)

**Expected Behavior**
The weapon damage should be added to your tooltip damage without lowering your actual damage.

**Comment by kelno** [comment]
Thanks for reporting, fixed with next server update
