### ISSUE TITLE
Guild Bank Disappearance 

### ISSUE THREAD

**Issue by DeadlyMemory** [ValorenWoW/sunstrider-core#4955]
**Describe the bug**
Guild was created and guild bank tab 1 was purchased shortly thereafter. Following that purchase, deposits were made on the guild bank that only has characters from 1 user. 24 hours later a lot of the items deposited were not in the guild bank anymore. The log shows that the items were deposited but not withdrawn. I have been unable to replicate the issue by attempting to delete items without removing them which makes me believe this is a server-sided issue.

**Character name**
Guild: Chase Bank NA

**Expected behavior**
Items deposited should remain in the guild bank until withdrawn and if they are withdrawn they should be visible on the guild bank log.

Images (from April 13):
https://cdn.discordapp.com/attachments/831531622805012510/831534190994259988/WoWScrnShot_041121_153615.jpg
https://cdn.discordapp.com/attachments/831531622805012510/831534196317093889/WoWScrnShot_041121_153611.jpg

Video: 
Note the Major Healing Potions deposited, but not withdrawn and being absent from tab 1.
https://user-images.githubusercontent.com/1964809/114887329-59cb7400-9dd6-11eb-9ddd-773de7270de0.mp4

**Comment by kelno** [comment]
Investigating this because we had a few more case since: 
It looks like the items in the guild bank are discarded because the core thinks they are loaded elsewhere. Maybe the tab gets reloaded twice? Still investigating this

Example of error:
```
2021-07-15_09:15:30 Refusing to load item entry 35201 guid 174635377 because it's already loaded somewhere else.
2021-07-15_09:15:30 Item (GUID 174635377, id: 35201) not found in item_instance, deleting from guild bank!
```

**Comment by kelno** [comment]
I made a change that should prevent this, at worst the guild bank won't load at all and we'll have a clearer picture if it happens.
