### ISSUE TITLE
Problems installing launcher

### ISSUE THREAD

**Issue by waybackwhen** [ValorenWoW/sunstrider-core#4957]
Downloaded launcher then ran it, failed on second dependency then reran it and it installed. 
Tried to run the launcher and it said that I needed to install .net framework,  I have it installed but reinstalled it anyway.
It still says that I need .net and I tried to uninstall the launcher to reinstall it but the launcher say its already installed and window can not see it to uninstall it. I even did a %endless% search with no joy.

Update, edited registry and deleted launcher and then was able to reinstall.  
The issue at its core seems to be that the client is not downloading the files and only installs the "updater.exe" and nothing else.

**Comment by kelno** [comment]
@hufsa

**Comment by hufsa** [comment]
Is the issue still present? It looks like you managed to install it after removing the registry entry?
The setup should indeed only download the Updater which in turn will get the latest version.
