### ISSUE TITLE
I can not learn a profession.

### ISSUE THREAD

**Issue by ohmoxide** [ValorenWoW/sunstrider-core#4958]
**Describe the bug**

**Character name**

**To Reproduce**

**Comment by ohmoxide** [comment]
I can not learn profession on this one character. I was able to learn on another character.
I have attempted to learn mining in Silvermoon, Thrallmar and Org.

See the screenshot below.

![mining](https://user-images.githubusercontent.com/15373047/115062019-b72af800-9e9e-11eb-9d7f-86c6d2d9a9d9.png)

**Comment by darkjesterr** [comment]
What happens when you click filter? you have journyman selected but need apprentice first are you sure its not hidden?

**Comment by ohmoxide** [comment]
OMG, I am SOOOO sorry to bother you.
Somehow I had filtered out Available.
Thank you so much for your time.
Again, sorry.
Cheers,
-Rob
