### ISSUE TITLE
fast reset, feign death  tk, void reaver

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4959]
tk, Void Reaver

raid is wiping.   hunter fd's at more than double body pull range.   while boss is killing 2nd to last person (hunter being last person) pet was sent by hunter to boss with petattack (during FD while maintaining the FD condition) to prevent boss from coming to hunter (and doing pounding @ hunter's fd location).  Pet had to be resent multiple times because boss was out of petattack range (pet runs to boss, just before reaching boss, resets from out of range condition).  After second to last person (hunter last person) dies boss runs to pet who is nearby and kills it then resets.

hunter stands up from feign death (after having been FD for 10+ seconds) while boss is resetting and runs to fast reset location where raid is respawning.  3s later boss enters combat with hunter who is about 5y away from fast reset position.   boss was pretty far away (close to max pet attack range) when it killed hunter's pet and started resetting.  speculating that boss somehow maintained agro on hunter after the reset and once reaching boss's reset position suddenly remember had agro on hunter causing the 3s delay between hunter standing up and gaining combat/agro.  I have sent pet on boss many times in the past in similar FD situation with no similar re-agro (may or may not have stood up before full reset in past, can't say for sure).

fast reset is aborted and raid releases to graveyard.

if hunter failed fd, then boss should've killed him after killing pet/2nd to last person.  if sending pet was generating agro, agro should've been wiped/reset when boss reset.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report.
Please provide a clip for situations like this one, this is way too many ifs, maybes, and other rabbit holes.

**Comment by kelno** [comment]
I tried and I can't reproduce either, though I don't doubt this did happen, a video could help a lot here if someone else encounter this issue.
