### ISSUE TITLE
Battlegrounds: Idle debuff stays in PvP Combat

### ISSUE THREAD

**Issue by bchn** [ValorenWoW/sunstrider-core#4960]
**Describe the bug**
If you get reported for AFK in a battleground you get the Idle debuff.
The Idle debuff does not get removed if you enter any form of PvP.

**Character name**
does not matter

**To Reproduce**

1. get reported for afk in a battleground until you are "Idle"
2.  do pvp
3.  get kicked anyway

https://www.wowhead.com/spell=43680/idle
https://www.wowhead.com/spell=43681/inactive#triggered-by

**Expected behavior**
the idle/inactive debuff gets removed upon entering pvp combat

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Thanks that's a new one since last update, fixed and applied
