### ISSUE TITLE
Skyguard attacking players

### ISSUE THREAD

**Issue by darkjesterr** [ValorenWoW/sunstrider-core#4961]
**Describe the bug**
Skyguard faction are attacking players for pve

**Character name**

**To Reproduce**

1. Go to Skyguard outpost
2. target the boar near the camp
3. attack the boar
4. guards become hostile
5. guards will kill you

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

guards dont kill you for pve

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, will keep this one: https://github.com/SunstriderEmu/BugTracker/issues/4962

**Comment by kelno** [comment]
Thanks, fixed with next server update
