### ISSUE TITLE
Fighting with enemy NPCs next to city guards, will cause them to turn hostile and attack you.

### ISSUE THREAD

**Issue by Red86** [ValorenWoW/sunstrider-core#4962]
Hi,
it seems that whenever you engage in a fight with an enemy NPC close enough to city guards, they will turn hostile and attack you.

How to reproduce:

-Go to terokkar forest, coordinates 37, 14, that's just outside one of Shattrath's exits, there's a couple of peacekeepers guarding it.
-Engage into a fight with any of the mobs there.
-Try to go back into the town after killing the mob
-Guards are now hostile and, will attack you

**Comment by kelno** [comment]
Thanks, fixed with next server update
