### ISSUE TITLE
Primal Mote Clouds

### ISSUE THREAD

**Issue by Ashnod666** [ValorenWoW/sunstrider-core#4963]
The clouds for mote extraction have not spawned for days on this server, there are none and have been none

Ashnod

**To Reproduce**
go to any cloud spawning area and fly around for hours looking for clouds, find none for days on end

https://www.wowhead.com/npc=68816/swamp-gas
all the other engineering primal mote clouds

**Expected behavior**
to respawn periodically in the appropriate zones

**Comment by kelno** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/4966
