### ISSUE TITLE
smv aldor guards agroing player after killing mob

### ISSUE THREAD

**Issue by michaelkittrell** [ValorenWoW/sunstrider-core#4964]
on east side of aldor town in SMV

agro'd a shadow serpent, decided to kill it too close to town.  was dpsing it then friendly guards came out, attacked and killed the serpent then agro'd onto my toon (revered with aldor).

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update: https://github.com/SunstriderEmu/BugTracker/issues/4962
