### ISSUE TITLE
Account suspended for no reason

### ISSUE THREAD

**Issue by AllHailCthunn** [ValorenWoW/sunstrider-core#4965]
i was in flight from stormwind to westfall and when i arrived in westfall i was disconnected and banned for 1 week for ,,Movement AntiCheat,, when i wasn't using any cheat of any kind. I was using the ,,/who,, command just before getting kicked out of the game, but i don't think that has any correlation.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, what's the account name?

**Comment by zorgNot** [comment]
Same thing happened to me (Tranquillen -> Silvermoon).  
Account name: zorgNotZerg

**Comment by MKranker** [comment]
I also ran into this issue going from Silvermoon to Ghostlands.
Account name: DocGarbage.

**Comment by nisavicz** [comment]
i was in flight from stormwind and banned for Movement AntiCheat  i wasn't using any cheat of any kind.

**Comment by nisavicz** [comment]
i was in flight from stormwind and banned for Movement AntiCheat i wasn't using any cheat of any kind.
Account name: nisavic

**Comment by Askerwius** [comment]
I was banned for Movement AntiCheat. I didn't use any cheat of any kind.
Account name: Askerwius
Please help

**Comment by jcoeler17** [comment]
I was group farming with friends and i randomly got disconnected and couldnt log back in just to find out that my was suspended for Movement AntiCheat. I dont use any cheats. account name: Jcoeler17

**Comment by InhumanGM** [comment]
The aforementioned accounts have been unbanned!
