### ISSUE TITLE
windy cloud, arcane vortex, swamp gas not spawning

### ISSUE THREAD

**Issue by Ashnod666** [ValorenWoW/sunstrider-core#4966]
**Describe the bug**
Windy Clouds, arcane vortexs, and swamp gas are not spawning on sunstrider

**Character name**
Ashnod, sunstrider + every other engineer i know

https://db.endless.gg/?npc=17378
https://db.endless.gg/?npc=17408
https://db.endless.gg/?npc=24222

**Expected behavior**
expect mote clouds to respawn periodically in their assigned zones

**Additional context**
no engineer i know has seen a mote cloud of any kind on sunstrider for days

**Comment by kelno** [comment]
Thanks, I can see this is indeed happening with Windy Clouds for example.
To me later: Command `.pool info 6700852` does indeed indicate 0 objects are spawned instead of 15. Might be related to grid unload.

**Comment by kelno** [comment]
Fixed with next server update
