### ISSUE TITLE
Was Banned for No Reason

### ISSUE THREAD

**Issue by Channie86** [ValorenWoW/sunstrider-core#4967]
I was travelling (Tranquillen -> Silvermoon). For some reason I got Movement Anti.Cheat message when I didnt use cheats of any kind? Can anyone help me out?
Account name: Channie86

**Comment by InhumanGM** [comment]
Thanks for the issue, the account has been unbanned.

**Comment by 11thadthomas** [comment]
@InhumanGM I was also banned today. Same reason, Movement AntiCheat. I was rezzed while walking back to my body after being killed by Hogger. I accepted and instant ban. 

Account name: 11thadthomas

**Comment by InhumanGM** [comment]
> @InhumanGM I was also banned today. Same reason, Movement AntiCheat. I was rezzed while walking back to my body after being killed by Hogger. I accepted and instant ban.
> 
> Account name: 11thadthomas

Fixed
