### ISSUE TITLE
attacked by stormpike guards

### ISSUE THREAD

**Issue by novahaze** [ValorenWoW/sunstrider-core#4969]
**Describe the bug**

i was attacked by stormpike guards in netherstorm after using a quest item on the flower mobs right next to the elevator. 
**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Thanks for reporting, already fixed and will be applied with next server update today, see https://github.com/SunstriderEmu/BugTracker/issues/4962
