### ISSUE TITLE
Mongoose Enchant visual bug

### ISSUE THREAD

**Issue by sniperyi** [ValorenWoW/sunstrider-core#4970]
Mongoose enchant isn't showing up on my shiny new axe!
![Mongoose Bug](https://user-images.githubusercontent.com/83043340/115794789-949e5f00-a409-11eb-80d8-ac9f7f58d222.jpg)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, that's a client-side issue, nothing we can do anything about.
