### ISSUE TITLE
sergeant thunderhorn 

### ISSUE THREAD

**Issue by jumanss** [ValorenWoW/sunstrider-core#4972]
The NPC Sergeant Thunderhorn the weapon quartermaster in orgrimmar has no available weapons for purchase.

Kielbasa - 70 rogue

**To Reproduce**
Walk in Hall of Legends, click on NPC. There are no weapons for purchase.

https://tbc.wowhead.com/npc=14581/sergeant-thunderhorn#sells

**Expected behavior**
I should be able to buy gladiator weapons with honor.

**Screenshots/videos**
![kielbasa](https://user-images.githubusercontent.com/83185589/116008142-e987d400-a5c7-11eb-89ba-219ee5e6a0be.png)

**Comment by InhumanGM** [comment]
Thanks for the issue, we're aware of it.
Should be fixed with the next update!
