### ISSUE TITLE
Pets Sometimes Do Not Revive with talents, resistances, etc.

### ISSUE THREAD

**Issue by cmurda26** [ValorenWoW/sunstrider-core#4975]
**Describe the bug**
When your pet dies, sometimes they revive with no talents, resistances, etc. The only way to fix it is to dismiss the pet and resummon.

**Character name**
Awesomeoh

**To Reproduce**
To reproduce, kill your pet and revive it as many times as necessary to find the issue. A good way is to check the pet stat panel and you will notice there will be no resistances trained on it until you dismiss and resummon.

**Expected behavior**
Pets should revive with their talents every single time.

**Comment by michaelkittrell** [comment]
I agree that this happens, but have no data to prove it.  Sometimes my pet will die to every single aoe at alar (spec'd into fire resistance) and other times it never dies.  While it could be something related to not getting rebuffed after dieing initially, it feels more like avoidance/fire resist not getting calculated.  I always relog after I have one of these fights and that seems to clear it up.

**Comment by disis24** [comment]
This bug only happens when the hunter is in combat.

**Comment by kelno** [comment]
Thank you @disis24, this enables me to reproduce it now. I'll look into it.

**Comment by kelno** [comment]
Fixed with next server update
