### ISSUE TITLE
Tree's Company does not complete

### ISSUE THREAD

**Issue by deusduce2** [ValorenWoW/sunstrider-core#4976]
**Describe the bug**
While leveling a new Draenei character, I attempted to complete the quest Tree's Company from Admiral Odesyus on Azuremyst Isle. I found the cove, found the Naga flag described in the quest text, used the tree disguise as described, watched the dialogue between the gnome and goblin, the screen indicated the "Quest Objected Complete," but did not complete the objective in my quest log and does not allow me to turn in at Odesyus. I have dropped and repeated the quest twice and I have attempted to use the disguise multiple times with the same results. The disguise will turn you into a tree, which triggers the two npcs to come out as intended, however when their dialogue is complete, the quest "toast" pop-up on the screen above the player character will show completed, however the quest log and the quest itself will not be marked as completed.

**Character name**
Eisensturm - Sunstrider

**To Reproduce**
1. Obtain quest from Odesyus.
2. Go to location described in quest text.
3. Use tree disguise as described in quest text.

Item: https://tbc.wowhead.com/item=23792/tree-disguise-kit
Quest: https://tbc.wowhead.com/quest=9531/trees-company
Spell: https://tbc.wowhead.com/spell=30353/summon-tree-disguise-kit

**Screenshots/videos**
![WoWScrnShot_042821_220331](https://user-images.githubusercontent.com/83378039/116505294-5a044e80-a86f-11eb-88ff-6bd0d716015f.jpg)
![WoWScrnShot_042821_220356](https://user-images.githubusercontent.com/83378039/116505303-5bce1200-a86f-11eb-9aae-bbc85d85dea7.jpg)
![WoWScrnShot_042821_220435](https://user-images.githubusercontent.com/83378039/116505304-5c66a880-a86f-11eb-90da-51a57038b86e.jpg)

**Comment by Jerrythemagicdog** [comment]
I've just tried it, the quest works for me.
Try clearing your cache, the quest objective in my quest log looks different to yours.
