### ISSUE TITLE
cant turn in quest in netherstorm

### ISSUE THREAD

**Issue by novahaze** [ValorenWoW/sunstrider-core#4980]
**Describe the bug**
i finished the quest "getting down to business" in netherstorm and cant turn it in? when i use the teleport pad to contact the npc to turn it in it says the pad has fallen into disuse
**Character name**

**To Reproduce**
how about you try testing your fucking piece of shit server that is FILLED WITH BUGS. I encounter multiple bugs every fucking day!! 
1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
You end the quest by talking to "Shrouded Figure" (20154) not by interacting with the pad.
