### ISSUE TITLE
Shapeshifts can be grayed out when spell queued

### ISSUE THREAD

**Issue by Evolvee** [ValorenWoW/sunstrider-core#4982]
Currently you can do this: https://youtu.be/Odm9PUWn3Bc?t=5

1) cast something
2) try to queue shadowform at the end of the cast _(its not that easy due to currently hackfixed spell queue which isnt even full 400ms)_
3) cancel cast
4) you end up with bugged (grayed out) Shadowform and you are unable to cast it until relog

**Comment by kelno** [comment]
Nice title

**Comment by kelno** [comment]
Fixed with next server update
