### ISSUE TITLE
Issue with faction change and scryer and aldor rep

### ISSUE THREAD

**Issue by smhRaven** [ValorenWoW/sunstrider-core#4983]
I did a free faction transfer from horde. Before the faction transfer my scryer rep was unfriendly. After the faction transfer my scryer rep was set to hostile and my aldor rep was set to friendly. In order to correct this I need to farm up 80 eyes. This is a huge inconvenience and a huge time loss.

This happened on satela.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
That's to be expected when you become a Draenei.
Draeneis have a racial bonus with the Aldor that also causes you to have less reputation with the Scryers.
