### ISSUE TITLE
Quest: The Force of Neltharaku

### ISSUE THREAD

**Issue by mizmar** [ValorenWoW/sunstrider-core#4984]
**Describe the bug**
Quest events for **The Force of Neltharaku** do not behave properly and don't gain any points to the quest progression, thus making it incompletable.
Quest: https://db.endless.gg/?quest=10854

**To Reproduce**
1. Accept the quest, go to Dragonmaw Fortress area, find some *Enslaved Netherwing Drake* with nearby *Dragonmaw Subjugator*.
2. Be out of combat, use the quest item Enchanted Nethervine Crystal on *Enslaved Netherwing Drake*
3. *Enslaved Netherwing Drake* turns friendly, doesn't attack any nearby orcs and just fly into the air, granting no points to the quest progress

**Expected behavior**
After using the item on drake, the drake started attacking the Subjugator and potentially agro any nearby orcs. Only after defeating the Subjugator (with the help of player), the drake starts flying into the air. Then player should gain point to the quest progress.

**Additional context**
It used to work few weeks back.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, can you clear your Cache and try again and if that doesn't help can you screenshot your quest log page with the quest open?

**Comment by Jerrythemagicdog** [comment]
Resolved in-game, the player was Hated and at-war with the Netherwing faction.
