### ISSUE TITLE
banned Winrunner????

### ISSUE THREAD

**Issue by mattxl** [ValorenWoW/sunstrider-core#4985]
Hey, I just got banned, I dont know why i was just leveing, been playing for aprox 4 hours since yersterday. 
Char Mxl - Winrunner

Could you tell me why?

**Comment by KuroNoKensh1** [comment]
same here just got banned 5mins ago.. i did nothing wrong i was just leveling with some friends so could pls someone tell me whats going on

**Comment by Jerrythemagicdog** [comment]
Thanks for reporting here, accounts were banned due to a false positive detection in the anti-cheat and were unbanned.
