### ISSUE TITLE
Warlocks fear pulling mobs

### ISSUE THREAD

**Issue by Shadowboltie** [ValorenWoW/sunstrider-core#4986]
**Describe the bug**
Warlock fears target, target pulls mobs that are far away while running in fear even he wasnt in pack

Shadowboltie

**To Reproduce**

1. Cast fear on target affected by  pulling by tank
2. Target is feared and running 20 secundes in fear and while fear is active doesnt pull aditional mobs
3. After feared target breaks out of fear it can pull other mobs

**Comment by mechanicsTBC** [comment]
it should
