### ISSUE TITLE
Graphics bug

### ISSUE THREAD

**Issue by Evilwowshaman** [ValorenWoW/sunstrider-core#4987]
Hi! I've just started with this private server and the first issue I ended up in was an issue with graphic settings:
Going windowed mode leaves the game screen completely black. I can still perform other things so the game is still running but I can't see a thing. 
Now that I applied it, everytime I try and launch the game, it stays completely black. I can still log in to my account and everything, but I guess this is some next level hardcore gameplay.
Any tips on how to get past this issue? I would love to play the game windowed maximized.

Edit: I deleted and reinstalled the game to fix the problem, but I dare not change it to windowed anymore :(

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, try this solution:

```
If you're getting a black screen when swapping to windowed mode - it's a GAMMA issue. 
Open up config.wtf inside of your WTF folder and add these 2 lines:
SET gxWindow "1"
SET gxMaximize "1"
```
