### ISSUE TITLE
Arena Battles Not Starting (Sunstrider)

### ISSUE THREAD

**Issue by Prettiboi** [ValorenWoW/sunstrider-core#4988]
Every time we enter a rated arena battle on Sunstrider, it does not do a countdown and holds us in the waiting area not allowing the battle to start, the leave arena box around the map will also disappear, so it requires us to log out and back into the game for us to be able to get it back and leave the arena battle.

**Comment by kelno** [comment]
Thank you, restarting the server now with the fix
