### ISSUE TITLE
the exorcism of colonel jules quest , hellfire peninsula , honor hold, alliance 

### ISSUE THREAD

**Issue by invictuslol** [ValorenWoW/sunstrider-core#4989]
**Describe the bug**
<this bug has happened to my friend (and seen others getting the issue as well) and we can't continue the quest chain due to that, the quest worked fine for me but when he did it the next day the quest is being marked as complete but turning it in fails and gives the error that says that he doesn't have the required items to turn in, in this case the spirit beads despite him having them in his bags> we attempted to do the quest many times with the same error , yes we did speak to colonel jules after the ritual was over and it was marked as complete.

**Character name**
adeeria

**To Reproduce**

1. its just an error at the turn in, nothing unintended happens other than that
2. 
3. 

Item: https://www.wowhead.com/item=31828/ritual-prayer-beads
Quest: https://www.wowhead.com/quest=10935/the-exorcism-of-colonel-jules
Spell: https://wowhead.com?spell=

**Expected behavior**
<the quest is marked as complete with the yellow question mark above the NPC, turn in should happen successfully>

**Screenshots/videos**

**Additional context**

**Comment by sjoerdinio112** [comment]
same here
