### ISSUE TITLE
[Quest] The Force of Neltharaku

### ISSUE THREAD

**Issue by SXD24** [ValorenWoW/sunstrider-core#4990]
**Describe the bug**
When using the Enchanted Nethervine Crystal on Enslaved Netherwing Drakes, they never turn into friendly NPCs and do not give quest credit.

**Character name**
Katreiko, Maamlet

**To Reproduce**

1. Begin the quest chain, receiving the Enchanted Nethervine Crystal.
2. Use the Enchanted Nethervine crystal from a safe distance.
3. Watch as it begins to fly away or attack the player, never turning into a friendly NPC and giving no quest credit.

Item: https://www.wowhead.com/item=31652/enchanted-nethervine-crystal
Quest: https://www.wowhead.com/quest=10854/the-force-of-neltharaku
Creatures: https://www.wowhead.com/npc=23187/enslaved-netherwing-drake

**Expected behavior**
The Enslaved Netherwing Drake should turn friendly, attacking nearby Dragonmaw Subjugators before flying away.

**Additional context**
This quest was completable a few weeks ago on other characters, but no longer provides credit for escaped Netherwing Drakes. I saw a previous bug report was issued concerning this quest, but Netherwing is not a faction available in the Rep menu, so I am unable to set them to not be at war.

**Comment by kelno** [comment]
Thanks for reporting, I made a fix for this somewhere in june.
