### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by InquisitorSilas** [ValorenWoW/sunstrider-core#4992]
**Describe the bug**
My launcher stuck in Initializing. I tried re-installing, resetting my router and pc

![image](https://user-images.githubusercontent.com/85002862/120055891-a2b35100-c041-11eb-87ae-510eae884b70.png)

**Comment by kinerskiner** [comment]
same with me

**Comment by kelno** [comment]
See https://github.com/SunstriderEmu/BugTracker/issues/5055
