### ISSUE TITLE
buggy quests

### ISSUE THREAD

**Issue by andriasilva** [ValorenWoW/sunstrider-core#4993]
**Describe the bug**

After joining the servers there are a lot of buggy quests because before the joining I could do the quests without a problem

**Character name**

Eter,ilsa,isa,cibela,thyri.

**To Reproduce**

1. I can accept the quests but after completing them I can’t complete them. Even abandoning and doing it again
2. Some quests should show time but does not appear

**Comment by kelno** [comment]
Can you give more details on what specific quests you have issues with?
