### ISSUE TITLE
Experience Gain Bug

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#4995]
There is a bug that occurs when in a party where experience rate gain is shared among the rest of the party members.
For example if a party member has zero xp gain selected via the website, then the other party members will also have the same effect of gaining zero experience points.

**Comment by mickwow** [comment]
Hello, this issue is still continuing to occur. It happens with any amount of party members and with any faction. I assume it should be a very simple fix.

**Comment by kelno** [comment]
Thanks for reporting.
That's actually a tricky one, needing some refactoring of the XP code to work.

**Comment by mickwow** [comment]
Hi Kelno,

Thank you for acknowledging this bug. Best of luck with fixing it, and hope its easy :)

**Comment by mickwow** [comment]
Hello, are there any updates on the progress of this bug?
Looking forward to hearing from you.
Many thanks.

**Comment by kelno** [comment]
Fixed with next server update
