### ISSUE TITLE
Pet (Hunter) Training Points

### ISSUE THREAD

**Issue by unexpect3d** [ValorenWoW/sunstrider-core#4996]
**Describe the bug**
Training Points spent on purchased ranks of an ability SHOULD count toward the total TP cost of following ranks. Here you get asked to spend the whole amount while learning the next rank in a spell. 

**Character name**
Silverblue

**To Reproduce**

1. Be hunter. 
2. Get pet.
3. Get training points (increase loyalty).
4. Teach pet (rank  1) spell  with trainig points (say rank 1 _Stamina_)
5. Look at the cost required for _Stamina_ (rank  2).  

https://tbc.wowhead.com/spell=5149/beast-training

**Expected behavior**
It should cost X (determined by rank) - Y (previously learned rank) = Z (total)

**Additional context**
Read additional notes number 4: 
https://wowwiki-archive.fandom.com/wiki/Training_point

**Comment by kelno** [comment]
Thanks for reporting.

I tried just now and it seems to work.
Though the price shown on the client is not changed whenever you learned a lower rank, your pet effectively use the calculation as you describe.
Example:
My pet has 296 TP, I learn Arcane Resistance Rank 1 (5 TP), I'm at 291 TP left. I continue by learning Rank 2 (15 TP), I'm correctly at 281.

Please do tell me if you still see an issue.
