### ISSUE TITLE
Jump Under Water

### ISSUE THREAD

**Issue by unexpect3d** [ValorenWoW/sunstrider-core#4998]
**Describe the bug**
Pressing Spacebar while swimming under water makes character do jump animation.

**Character name**
Silverblue

**To Reproduce**

1. Be underwater 
2. Press spacebar

**Expected behavior**
Pressing spacebar under water should make character swim upwards.

**Comment by kelno** [comment]
Thanks for reporting.
That's a clientside issue and we have no way to change it, it will be the same on every TBC server.
