### ISSUE TITLE
requiring an account for wiki is trashy idea

### ISSUE THREAD

**Issue by oppahansi** [ValorenWoW/sunstrider-core#5]
title.

secondly:

making instance and creatures scripts closed source makes this whole "open sourcing" of your project useless.

**Comment by SUN-Leekie** [comment]
Removing our scripts is a little security for all the work we did over the years.
Everything will be open eventually.

**Comment by kelno** [comment]
We'll also migrate the wiki to a public one soon, this open thing is still a work in progress :)
