### ISSUE TITLE
Feral druid: Tiger's Fury, not adding damage

### ISSUE THREAD

**Issue by Sedrs** [ValorenWoW/sunstrider-core#5000]
Hello guys! :)

Tiger's Fury Current behavior:
Not adding any plus damage, when you open character panel you can see +damage, but your base damage gets lowered by same amount.
Resulting same damage as without buff.

Expected behavior:
Buff is adding describet amount of damage.

Steps to recreate issue:
Use Tiger's Fury with any druid and see your damage is same, AA and abilities makes same damage as w/o.

Related info:
Tried every rank till rank 4.

Source:
https://tbcdb.com/?spell=9846

**Comment by kelno** [comment]
Thanks for reporting, fixed with next server update
