### ISSUE TITLE
HELP Download stuck on "initializing"

### ISSUE THREAD

**Issue by kinerskiner** [ValorenWoW/sunstrider-core#5002]
When I start the launcher and try to download the game, the download gets stuck on "initializing...  0%".
Please help.

**Comment by Vipe8** [comment]
I also have the same problem. Tried to give it permission for changes but it didn't change anything.

**Comment by kelno** [comment]
Thanks, keeping the other one open:
https://github.com/SunstriderEmu/BugTracker/issues/4992
