### ISSUE TITLE
call of water horde

### ISSUE THREAD

**Issue by freelance747** [ValorenWoW/sunstrider-core#5003]
It says " TEMP Ruins of Stardust Fountain" Cannot click on it, cannot use Empty Blue Waterskin on it saying it is looking for the fountain.

**Character name**
Terla

**Expected behavior**
Complete Call of Water

**Screenshots/videos**
![WoWScrnShot_061321_072952](https://user-images.githubusercontent.com/85811138/121791441-688aa780-cc1c-11eb-9818-1bf00d160f72.jpg)

**Additional context**

**Comment by kelno** [comment]
Quest id 1534

**Comment by kelno** [comment]
Thanks for reporting!
I tried this quest and the item correctly activates in this place, I can't figure out what went wrong for you.
Closing until further information is given.

**Comment by freelance747** [comment]
Thank you for you time. I was able to use it after restarting, maybe it was lag I don’t know :D Sent from Mail for Windows 10 From: KelnoSent: Wednesday, 16 June 2021 4:47 PMTo: SunstriderEmu/BugTrackerCc: freelance747; AuthorSubject: Re: [SunstriderEmu/BugTracker] call of water horde (#5003) Thanks for reporting!I tried this quest and the item correctly activates in this place, I can't figure out what went wrong for you.Closing until further information is given.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
