### ISSUE TITLE
Two bugs in an alliance quests i found.

### ISSUE THREAD

**Issue by PPGGPilot** [ValorenWoW/sunstrider-core#5004]
**Describe the bug**

1. **Captain Garran Vimes** does not offer **Peace at Last** quest.
2. **Singed Letter** which starts the second in chain **Suntara Stones** quest, disapperas very quickly and never shows up again.

**Character name**

All characters (i'm playing 4 different races and classes).

**To Reproduce**

1. Start and finish the chain of alliance quests in **Dustwallow Marsh**: **Tabetha's Assistance** -> **Raze Direhorn Post!** -> **Justice for the Hyals**.
The last quest ends at **Captain Garran Vimes** who should offer the final **Peace at Last** quest with few nice rewards. He offers nothing. No possibility to end the chain.

2. Start an escort quest in **Searing George**: **Suntara Stones**.
After completing the escort and reaching the destination point, the NPC is shot and dies dropping a letter which completes the escort quest and starts the next quest in the chain. Unfortunately if you don't accept the quest very quickly or like me, you read the description carefully, leter disappears with NPC corpse and there is no possibility to start that next quest and to continue the chain. 

1. **Peace at Last** quest:
Previous quests in the chain: https://tbc.wowhead.com/quest=11149/tabethas-assistance
                                            https://tbc.wowhead.com/quest=11150/raze-direhorn-post
                                            https://tbc.wowhead.com/quest=11151/justice-for-the-hyals
Captain Garran Vimes: https://tbc.wowhead.com/npc=4944/captain-garran-vimes
The last and bugged quest: https://tbc.wowhead.com/quest=11152/peace-at-last

2. **Suntara Stones** quest.
NPC who starts the chain: https://tbc.wowhead.com/npc=8284/dorius-stonetender
An escort quest (1st in the chain): https://tbc.wowhead.com/quest=3367/suntara-stones
A letter which ends / starts quests: https://tbc.wowhead.com/object=175704/singed-letter

**Expected behavior**

1. **Captain Garran Vimes** offers **Peace at Last** quest after completing **Justice for the Hyals**.
2. **Singed Letter** remains where NPC died even if his corpse dissapears.

**Screenshots/videos**

I have no screenshots/videos.

**Additional context**

N/A

**Comment by kelno** [comment]
Thanks for the details here!

**Comment by z5n** [comment]
fixed with the next update, thanks!
