### ISSUE TITLE
Network connection issues

### ISSUE THREAD

**Issue by Deppizzymo** [ValorenWoW/sunstrider-core#5005]
I have no idea what is going on but I cannot connect to the game anymore. We had a power blip which reset our router and our internet came back up and worked as normal. However... this disconnected us from the game and now whenever we try to log on it says "Unable to Connect". I have tried on multiple computers, tried connecting my computer directly to the modem with an ethernet cable and tried resetting the modem/computers. This is for everyone in my family (me, wife and two kids)...

The strange thing is that the game works perfectly when connecting through my tethered phone. We can log in and play as normal. However I would prefer not to play over my phone connection permanently. My ISP says nothing is being blocked through my modem. I went into the modem and disabled the firewall to see if that helped and it didn't do anything. The internet works perfectly fine otherwise.

Characters are
Cascadia
Atrus
Armthrustlf
Navie

Thanks

**Comment by kelno** [comment]
It seems you reached the maximum open connections limit, the connections from before your power reset probably stayed open for a while.
I've increased the limit some more, it should be better now.
