### ISSUE TITLE
Can't recieve whisper or invites. Also can't invite ppl or whisper them

### ISSUE THREAD

**Issue by Bl00dyD3stiny** [ValorenWoW/sunstrider-core#5007]
There is not much to say tbh. Yesterday i started playing and got randomly invited by a horde rogue (me beeing alliance), i declined and kept on moving. Today i whispered a friend and he did not recieve the msg, but for me it showed up (that i have sent a message, but could'nt see his whisper aswell). Then we tried inviting and also not working. Tried relogging, deabling addons, no use at all.

Character Name: Relindeya

**Comment by Viralspell** [comment]
Hey, I have the same Issue.
It looks like, no one can see my messages or get  my group invites.

Charakter Name: Asika

**Comment by InhumanGM** [comment]
Resolved in-game!
