### ISSUE TITLE
The Force of Neltharaku...bugged

### ISSUE THREAD

**Issue by freelance747** [ValorenWoW/sunstrider-core#5011]
**Describe the bug**
The "Enchanted Nethervine Crystal" is suppose to free "Enslaved Netherwing Drake" but is does not, the drake flies away, does not turn green, does not attack enemy that is near, get stuck in the air (pic) and sometimes goes back to its original spot like nothing happened.

**Character name**
Terla

**To Reproduce**
1. Use Enchanted Nethervine Cystal on Enslaved Netherwing Drake
2. 
3. 

Item: https://www.wowhead.com/item=31652/enchanted-nethervine-crystal
Quest: https://www.wowhead.com/quest=10854/the-force-of-neltharaku

**Expected behavior**
Free Netherwing Drake or Attack Subjucator then fly away

**Screenshots/videos**
![WoWScrnShot_062321_130408](https://user-images.githubusercontent.com/85811138/123040227-02750000-d426-11eb-8703-2403897006ac.jpg)
![WoWScrnShot_062321_130424](https://user-images.githubusercontent.com/85811138/123040244-086ae100-d426-11eb-97ae-95524d1d2545.jpg)

**Additional context**
Thank you for your time :)

**Comment by lukefile** [comment]
Same problem!

**Comment by kelno** [comment]
Thanks, fixed with next server update
