### ISSUE TITLE
Cant invit party

### ISSUE THREAD

**Issue by Cochilocooo** [ValorenWoW/sunstrider-core#5013]
**Describe the bug**
 i cant invit party

**Character name**
 flippyflopy

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by AidynAmrenov** [comment]
i cant invite party too

**Comment by AidynAmrenov** [comment]
so?

**Comment by InhumanGM** [comment]
Fixed!
