### ISSUE TITLE
Can't buy gear for Honor in Orgri from Lady Palanseer

### ISSUE THREAD

**Issue by Saprape** [ValorenWoW/sunstrider-core#5014]
Hi, I can't buy "Vengeful Gladiator's Leather Tunic" for Honor in Orgri from Lady Palanseer. I have enough honor points and suitable marks but the message appears: "You don't have enough arena points".
The same issue happens with the rest of the pieces from that set for honor.

**Comment by Saprape** [comment]
Hello? Can you check it and answer smth? 5 days left and no any reaction...

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
