### ISSUE TITLE
 my group invite doesn't reach the player or whisper

### ISSUE THREAD

**Issue by Deborakujava** [ValorenWoW/sunstrider-core#5016]
**Describe the bug**
 I can't invite invites anyone to the group, I thought the problem was my game, I deleted the wtf cache folder and it didn't work, I finally downloaded the game again straight from its launch and it still has the same problem, and I couldn't invite to the group and whisper, I sent a ticket in the game do not answer me, 

I thought the problem was just my friends, but if I try to invite any random person to the game, they don't get my invite and they don't get the whisper, I invite and they don't get my group invite, I whisper and they don't get mine whisper

**Character name**
 KALICIA, my friend has the same problem, CHELEMENIS

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

 ![image](https://user-images.githubusercontent.com/87029690/124646995-c1400f80-de6b-11eb-9a82-147c118c9c1b.png)  
![image](https://user-images.githubusercontent.com/87029690/124647614-9609f000-de6c-11eb-9df5-6b3f0febb13a.png)
![image](https://user-images.githubusercontent.com/87029690/124647643-9efac180-de6c-11eb-8624-308839fc6d5b.png)
![image](https://user-images.githubusercontent.com/87029690/124647946-fbf67780-de6c-11eb-99a6-d721d1881c3b.png)

https://vimeo.com/571795385

**Additional context**

**Comment by Deborakujava** [comment]
![image](https://user-images.githubusercontent.com/87029690/124655995-0158bf80-de77-11eb-8415-26180704f0dc.png)
![image](https://user-images.githubusercontent.com/87029690/124656047-11709f00-de77-11eb-94eb-e611a214fdea.png)

**Comment by Deborakujava** [comment]
https://vimeo.com/571795385

**Comment by PPGGPilot** [comment]
Try disabling all add-ons, then check if the problem still exists.

**Comment by InhumanGM** [comment]
Fixed!
