### ISSUE TITLE
Can't buy gear for Honor in Stormwind

### ISSUE THREAD

**Issue by Novemo** [ValorenWoW/sunstrider-core#5017]
Hi, I can't buy "Vengeful Gladiator's Leather Tunic" for Honor in Stormwind . I have enough honor points and enough marks but the message appears: "You don't have enough arena points". Even if the piece requires arena points or rating points. It just doesn't work
The same issue happens with the rest of the pieces from that set for honor.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
