### ISSUE TITLE
Shatttrath Badge Vendor Missing Battlemaster's Alacrity

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5019]
As simple as Title Reads. The Shattrath Badge Vendor is Missing the Battlemaster's Alacrity. it's the one with Haste for 75 Badges. ****
PLEASE NOTE *** The PVP Vendor DOES have this Trinket Available for 40 AV Marks, so I know it is in the Game Code, but no one is running AV so it is immposiible to obtain. But according to Atlasloot, it is Clearly supposed to be Available from the Shattrath Badge Vendor as Well. Please Correct this. Thank You! .

-Draguli

**Comment by Sheikthecatman** [comment]
Thanks, issue will be fixed next server update.
