### ISSUE TITLE
Wrong currency being used when purchasing PvP gear from honor and marks

### ISSUE THREAD

**Issue by Prettiboi** [ValorenWoW/sunstrider-core#5020]
**Describe the bug**
Arena points being used instead of marks and honor when purchasing PvP gear

**Character name**
Fistoflegend

**Expected behavior**
Made a purchase for s3 chest piece with honor and AB marks but instead arena points were used when selecting the correct chest that shows 14500 honor and 30 AB marks

**Comment by Prettiboi** [comment]
If possible can I have the arena points restored and have the proper amount of honor and marks taken out instead, thank you

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
