### ISSUE TITLE
Longstanding Summoning Stone Issues

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5021]
This issue Does not Pertain to Level 70-Level 70 Players.

This Issue Pertains to An Issue That, for Instance, as myself being a GM, im helping someone in a dungeon, and arrive on the Scene, say for Instance Scholomance, and im Unable to Summon them, they might be level 60, or 62, or 70, it doesnt matter
There isnt a Single Stone that will work with a level 70 player or summon a level 70 player in any of Azeroth.
The other setback is if the player is about 6 levels different than the stone's surrounding leveling area. It will make the entire party wait and a is huge hassle. We go through this problem 8-10 times a day. People dont have their FP.

Can't we just update all of the stones in the Game to work the same, regardless of level? As Endless is a Server that Caters to Hardcore Players and has 8x XP, Flaskataur, and 2x Prof Rate, i don't think this Quality of Life Adjustment is Asking too much for one of the Devs to put some Effort into doing this for us. If you are Reading this Inhuman or one of the Kind Devs Please consider this. Thank you. I'm Draguli and I take in Many Levelers. Thank you so much for Everything you do! We Love You!

**Comment by nokia4life2000** [comment]
This issue Does not Pertain to Level 70-Level 70 Players.

This Issue Pertains to An Issue That, for Instance, as myself being a GM, im helping someone in a dungeon, and arrive on the Scene, say for Instance Scholomance, and im Unable to Summon them, they might be level 60, or 62, or 70, it doesnt matter
There isnt a Single Stone that will work with a level 70 player or summon a level 70 player in any of Azeroth.
The other setback is if the player is about 6 levels different than the stone's surrounding leveling area. It will make the entire party wait and a is huge hassle. We go through this problem 8-10 times a day. People dont have their FP. 

Can't we just update all of the stones in the Game to work the same, regardless of level? As Endless is a Server that Caters to Hardcore Players and has 8x XP, Flaskataur, and 2x Prof Rate, i don't think this Quality of Life Adjustment is Asking too much for one of the Devs to put some Effort into doing this for us. If you are Reading this Inhuman or one of the Kind Devs Please consider this. Thank you. I'm Draguli and I take in Many Levelers. Thank you so much for Everything you do! We Love You!

**Comment by kelno** [comment]
Thanks, I like the idea and it's very easy to do. I made the change and it maximum level cap will be removed with next server update.
