### ISSUE TITLE
No one sees what I am chatting and cannot add anyone to the group

### ISSUE THREAD

**Issue by Juman1e** [ValorenWoW/sunstrider-core#5022]
Hello. Help me please solve the problem. Nobody sees what I write in the chat. I can not assemble a group (the invitation to the group is not displayed). Nick Jumanie

**Comment by Juman1e** [comment]
Deleted the Cache folder, deleted the WTF folder. Reinstalled the game but that didn't fix the problem.

**Comment by kelno** [comment]
It looks like you were muted for some reason, I removed it for you
