### ISSUE TITLE
Warlock pet leveling skills

### ISSUE THREAD

**Issue by gilgrencho** [ValorenWoW/sunstrider-core#5024]
**Describe the bug**
Only void walker skills are auto learned on leveling.

**To Reproduce**
1. Normal level up of warlock 
2. void walker get his skills updated, other pets dont.

**Expected behavior**
All pets should learn skills when leveling, not just void walker.

**Comment by kelno** [comment]
Thanks for reporting.
I'm testing right now with an imp, I went from lvl 10 to 20 and observed the skills being auto learned then upgraded.
But it seems to only work when the pet is out when you level up, so that's an issue with this system.

**Comment by gilgrencho** [comment]
yes, i noticed that also after doing this post. The actual bug is: only the
currently summoned pet gets the skills leveled up.

**Comment by kelno** [comment]
Fixed with next server update
