### ISSUE TITLE
Molten core bugged

### ISSUE THREAD

**Issue by Cowbell11** [ValorenWoW/sunstrider-core#5028]
(Similar to issue #4630 and #4631)
Have been wandering arround in the id after executus was killed. Sometimes Ragnaros isnt there, sometimes its there untargeteable.
Every time you aproach to Majordomo Executus fight location u can read the after-fight dialogue; "Impossible, Stay your attack mortals! I submitt! . . . "

I would apreciate it if at least a quick fix can be made in this instance since im only missing Essence of the Firelord (100% drop from Ragnaros) in order to get my Thunderfury u.u

**Comment by kelno** [comment]
Thanks for reporting.
I won't fix vanilla instances for now but if that's the only item you miss, please give me your character name here and I'll see about it.

**Comment by Cowbell11** [comment]
Ye actually im missing that one and the last binding which im gonna keep farming knowing that i wont get stuck in the quest :) character's name is Funkylaucha
