### ISSUE TITLE
Logging into my account Issue.

### ISSUE THREAD

**Issue by Lodormi** [ValorenWoW/sunstrider-core#5030]
Hello there, today i've been trying to log into my account and havent been able to do it inside the TBC's client, but I'm able to do it on the website. I've changed my password 4 times and even changed my acc's e-mail, deleted cache+WTF folders  and checkd the realmlist too. It sais that "the information i have entered is not valid" but I've re-tried like 20 times and wrote the same "new password" that i put, and it wasnt wrong. Can someone help me? Please.

**Additional context**
The only person that have entered into my acc was my brother this morning to farm some ores with my main, and he can not log into the acc either...

**Comment by Quettoc** [comment]
I got the same problem. Did you fixed it in some way? becasue you closes the issue allready? I cant find a way to fix it. Maybe you can help me out?
