### ISSUE TITLE
Cant log in my account'' says information are not valid'' but they are

### ISSUE THREAD

**Issue by Quettoc** [ValorenWoW/sunstrider-core#5032]
Hello, i just wanted to restart my Client. When i wanted to log in again it says '' The information you have entered are not Valid. Please check the spelling of account name and Password'' I am sure my information are correct because i can log on the webside without any problems. I tried to change password allready and deleted my wtf and chache folder. Hope you can help me fix this problem.

**Character name**
 Quettoc

**Comment by kelno** [comment]
Issue with 2FA, fixed since
