### ISSUE TITLE
Cant log in to account

### ISSUE THREAD

**Issue by Prettiboi** [ValorenWoW/sunstrider-core#5033]
**Describe the bug**
When trying to log into my game, "The information you have entered is not valid" msg comes up even with proper account and password entered in, I log into website and changed password and same results when entering new password when logging in.

**Character name**
Hunglow

**Comment by Restlessboy** [comment]
Hi i have the same problem.... wtf ?! Taladinpank.

**Comment by Prettiboi** [comment]
Only way i was able to fix this was by logging into endless.gg and resetting my two way authenticator, not sure why but when disabled it doesnt allow access to my account when logging into the game

**Comment by Prettiboi** [comment]
Req account to have two way authentication and in game protection to work
