### ISSUE TITLE
cant log in to account...

### ISSUE THREAD

**Issue by Restlessboy** [ValorenWoW/sunstrider-core#5034]
**Describe the bug**
 cant log in to account 

**Character name**
im logged at website at my account but ingame cant ... why ?
Taladinpank
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Issue with 2FA, fixed since
