### ISSUE TITLE
Vengeful Gladiator's Satin Mantle is Bugged, Item 33747, does not Report Bonus from Shoulder Enchants; this MIGHT affect all Shoulder Enchants

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5040]
**Describe the bug**
My Shoulder Enchants are Bugged, it may Pertain to the Entirety of Scryer Exalted Enchants on All Shoulders, (the 15 crit (0.68%) and 12 Spell Damage. the Bonus isnt stacking for the Spell Damage. im missing the 12 spell damage bonus. i actually am noticing this on all my shoulders

**Character name**
Draguli

**Comment by kelno** [comment]
Thanks for reporting.
I've been borrowing your character to check, using your current equipped shoulderpieces: Switfheal Mantle
Those should provide 47 spell damage if we include your talents (converting spirit to spell damage) & the enchant. That's exactly how much spell damage you lose if I remove them.
Could it be a miscalculation on your part? If not, can you provide some numbers for me to look at?
