### ISSUE TITLE
SERVERWIDE :Flight Master at Sunwell Plateau, and Silvermoon CIty, has no Connecting Nodes; also affecting Allys, Unable to Fly to Silvermoon or Sunwell; this Definitely Worked on Sunstrider before Windrunner Merge

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5041]
**Describe the bug**
Ever Since Sunstrider and Windrunner Merged, im unable to fly Across Eastern Kingdoms to Sunwell Plateau, Nor from Sunwell to Silvermoon or anywhere Leaving Sunwell.. the Node at Silvermoon City and Sunwell does not appear in my flight paths. i tried to re-learn those flight paths, but both Silvermoon and Sunwell Taxis both Say that i know no connecting flights, even though i have Zul Aman taxi nearby. ive tried this many times to rule out lag. At the moment the only way to leave Sunwell Plateau is to Hearth or use a scroll or get summoned. I have Confirmed you cannot swim from Sunwell to Eastern Kingdoms. (a barrier in the water stops you from connecting to the next Continent, even though it is in sight. But back to the issue: It APPEARS that the Silvermoon Taxi might be where the Bug is, but check the older database from before the merge because it definitely worked on the original Sunstrider a few months ago before the Merge. This is affecting everyone btw. Thank you!

**Character name**
Draguli

**To Reproduce**
just port to Siilvermoon City, it will tell you that you do not know any connecting nodes, then port to Sunwell, same message. Silvermoon does not appear in my list of flight points at all. This is also affecting the allys in my Guild, and i cant remember the name of that taxi (ally equivalent to silvermoon)

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Thanks, fixed now
