### ISSUE TITLE
Longstanding Summoning Stone Issues Re: (Minimum and Maximum Level Cap not Completely Removed Yet)

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5042]
**Describe the bug**
I understand you closed my last report saying it was resolved, but it still isnt working. At the Moment, the only way to summon players outside of that stone's Range is by getting a player of the correct level "Range" to activate the stone,then a clicker of ANY level clicks on the portal to assist, not on the stone. IF WE ARE SUMMONING someone outside the stone's level Range, while the portal is activated on-screen, the first summoner must click the Name of that Person in the Party (IE Changing the Person in the middle of the summoning process) We have found these tricks to make it work, but we still have the issuee that the level 70 cant INITIATE the whole process (if in Azeorth); it still requires someone of the proper level range to initiate. Can we fix this please? It's Probably in the Vanilla code (my best guess), but shouldnt be hard to remove level cap, or initiating cap. since every stone in azeroth has a different level range currently, it shouldnt be hard to change the level range, and just comment out the original code. For example the Uldaman Stone in Badlands will NOT summon i think it was a level 35 or 36, even though the Minimum is level 30 to get in the door of the dungeon. This will Greatly Help the Leveling Process, many are deterred from dungeons because of getting flight paths, but if we can actually summon when we help boost, it would be very awesome. As a Rule i Personally dont Boost, i just heal and organize things into a group and encourage levelers to be Social, as they Really Need it. Thank You! -Draguli

IF you would like to keep level ranges, here is the definitive list of Mimimum levels to get in a dungeon:

WOW_MIN_DUNGEON_LVLS

RAGEFIRE CHASM

    Minimum level: 10
    What people call it in chat: RFC
    Where it’s located: Right in the middle of Orgrimmar
    Attunement required: No
    Bosses and wings: One wing, four bosses

WAILING CAVERNS

    Minimum: 10
    What people call it in chat: WC
    Where it’s located: Buried inside a hill in The Barrens, just southwest of 
Crossroads
    Attunement required: No
    Bosses and wings: One wing, eight bosses (sometimes an additional rare mob 
will spawn)

THE DEADMINES

    Minimum: 10
    What people call it in chat: Deadmines or VC or DM, and expect to see lots 
of arguments about that
    Where it’s located: Buried inside a shack that leads to a mine in the Westfall 
town of Moonbrook
    Attunement required: No
    Bosses and wings: One wing, seven bosses (one additional rare mob)

SHADOWFANG KEEP

    Minimum: 14
    What people call it in chat: SFK
    Where it’s located: In a castle at the top of a hill in Silverpine Forest, west 
of Ambermill, south of the Ruins of Lordaeron
    Attunement required: No
    Bosses and wings: One wing, seven bosses (plus one rare mob)

BLACKFATHOM DEEPS

    Minimum: 15
    What people call it in chat: BFD
    Where it’s located: Underwater in a ruin on a beach at the western end of 
Ashenvale
    Attunement required: No
    Bosses and wings: One wing, eight bosses

THE STOCKADE

    Minimum: 15
    What people call it in chat: Stocks
    Where it’s located: Right in the middle of Stormwind City
    Attunement required: No
    Bosses and wings: One wing, five bosses, one rare

GNOMEREGAN

    Minimum: 19
    What people call it in chat: Gnomer
    Where it’s located: Inside a gnomish building in northwestern Dun Morogh, 
west of Ironforge
    Attunement required: No, but obtaining the Workshop Key allows you to 
enter via the back door, which is much faster; Horde players can complete a 
quest to get a teleporter in Booty Bay to jump near Gnomeregan
    Bosses and wings: One wing, five bosses, and a rare

SCARLET MONASTERY

    Minimum: 21
    What people call it in chat: SM, typically followed by an abbreviation for the 
wing
    Where it’s located: In a large church northeast of Undercity and Brill, up in 
the hills
    Attunement required: Yes – the Scarlet Key from the Library wing is required 
to open the Armory or Cathedral wings
    Bosses and wings: Four wings. Graveyard: Two bosses, three rares. Library: 
two bosses. Armory: one boss. Cathedral: three bosses.

RAZORFEN KRAUL

    Minimum: 25
    What people call it in chat: RFK
    Where it’s located: Just west off the Gold Road at the far southern end of 
The Barrens
    Attunement required: No
    Bosses and wings: One wing, six bosses, and two rares

MAURADON

    Minimum: 30
    What people call it in chat: Maura, Mauradon
    Where it’s located: Buried in a hill near the southwestern coast of Desolace
    Attunement required: No, but building the Scepter of Celebras allows you to 
skip to the final boss
    Bosses and wings: Four wings. Purple side: two bosses. Orange side: two 
bosses. Poison Falls: one boss and a rare. Earth Song Falls: three bosses.

ULDAMAN

    Minimum: 30
    What people call it in chat: Ulda, Uldaman
    Where it’s located: Buried underneath the north central area of the Badlands
    Attunement required: No
    Bosses and wings: One wing, seven bosses, plus one that only Horde can 
attack

RAZORFEN DOWNS

    Minimum: 35
    What people call it in chat: RFD
    Where it’s located: Across the Gold Road from RFK, buried behind 
approximately eleventy billion quillboar and twisty little passages that all look 
alike in southern Barrens, inside an enormous quillboar skull
    Attunement required: No
    Bosses and wings: One wing, five bosses, and a rare

ZUL’FARRAK

    Minimum: 39
    What people call it in chat: ZF
    Where it’s located: Ruins in northwestern Tanaris
    Attunement required: No, but someone in the party must have the Mallet of 
Zul’Farrak if you plan to kill Gahz’rilla
    Bosses and wings: One wing, 11 (!) bosses, and three rares.

TEMPLE OF ATAL’HAKKAR

    Minimum: 45
    What people call it in chat: ST (for Sunken Temple)
    Where it’s located: Underwater in the middle of a lake in the middle of 
Swamp of Sorrows
    Attunement required: No, but you must have Yeh’kinya’s Scroll to summon 
the Avatar of Hakkar
    Bosses and wings: Not wings, but the two floors of ST are typically handled 
separately. The basement has seven bosses, while the main instance has eight.

BLACKROCK DEPTHS

    Minimum: 48
    What people call it in chat: BRD
    Where it’s located: Buried inside Blackrock Mountain (run down the chairs to 
the very bottom, then through the mine, to find the entrance)
    Attunement required: No, but the Shadowforge Key (which you get from a 
quest obtained while you’re dead) unlocks all the interior doors in the dungeon, 
making subsequent visits faster
    Bosses and wings: While the dungeon is carved into sections, it’s still one 
extraordinarily long run; 22 bosses and one rare.

DIRE MAUL

    Minimum: 48
    What people call it in chat: DME, DMN, DMW (for the various wings)
    Where it’s located: Large ogre complex north of the main road in the middle 
of Feralas
    Attunement required: Yes, the Crescent Key is required to open doors in the 
North and West wings
    Bosses and wings: Three wings. East: five bosses. West: five bosses and a 
rare. North: seven bosses

LOWER BLACKROCK SPIRE

    Minimum: 48
    What people call it in chat: LBRS
    Where it’s located: In the same mountain as Blackrock Depths, but go up 
instead of down
    Attunement required: No
    Bosses and wings: One wing, nine bosses, seven rare mobs

UPPER BLACKROCK SPIRE

    Minimum: 48
    What people call it in chat: UBRS
    Where it’s located: In the LBRS area, but a separate attunement is required 
to open the door
    Attunement required: Yes – one member of the party must have the Seal of 
Ascension to open the door
    Bosses and wings: One wing, seven bosses, one rare

SCHOLOMANCE

    Minimum: 48
    What people call it in chat: Scholo
    Where it’s located: Western Plaguelands inside the ruins of Caer Darrow
    Attunement required: Yes – one member of the party (or someone in the 
area) must have the Skeleton Key to open the door
    Bosses and wings: One wing, 15 bosses, two of which are summoned

STRATHOLME

    Minimum: 48
    What people call it in chat: Strath Live Side, Strath Dead Side
    Where it’s located: Eastern Plaguelands on the continent of Eastern 
Kingdoms
    Attunement required: No, but killing one of the bosses on Dead Side will 
award one member of the party the Key to the City for direct access to the 
Dead Side
    Bosses and wings: Two wings: Live side – eight bosses, one of which is 
summoned, and two rares. Dead side – six bosses and a rare

**Character name*

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Indeed my last change there didn't completely work, the server currently allows for the 70 characters to summon but the client itself knows the stone level and won't even ask the server to begin summoning.
I did find a workaround though, applied with server reboot.

**Comment by nokia4life2000** [comment]
@kelno awesome work man! You are a Genious of Devs. You have singlehandedly solved 14 years of summon stone heartache with this code.
