### ISSUE TITLE
fishing issue

### ISSUE THREAD

**Issue by Fredhsin** [ValorenWoW/sunstrider-core#5043]
**Describe the bug**
I can't catch anything while fishing, although I could yesterday

**Character name**
Gumbita

**To Reproduce**
Fishing in Ratchet area

Quest: None
Spell: None

**Expected behavior**
Catching something, like I was yesterday

**Screenshots/videos**
None

**Additional context**
I was farming trunks for cloth and leather

**Comment by kelno** [comment]
Thanks, fixed with next restart
