### ISSUE TITLE
Warlock macro missing

### ISSUE THREAD

**Issue by centurychilds** [ValorenWoW/sunstrider-core#5044]
**Describe the bug**
Each time i logged out (or auto-log out when i went afk) all my pre-set macro would disappeared when i log back in. I have tried deleting WTF folder but the problem hasn't resolved. What I noticed was during the loading screen, when it went busy for couple of seconds (i.e Not responding) and re-connect and when i checked all my pre-set macros missing and i have to re-do all back.

**Character name**
Deepwound (Undead Warlock)

**To Reproduce**
i have tried all the necessary steps suggested on Google. I have tried :
1. deleting wtf file..problem still occur
2. unchecked wow directory from Read only to Not-read only

i dont know what to include

**Expected behavior**
any set macro should not disappear if we log out properly (i.e using log out or auto-boot out) because the game server will save it.

**Screenshots/videos**
nil

**Additional context**
nil

**Comment by kelno** [comment]
It might be that your wow directory is not writable by the game, maybe try moving the game directory elsewhere on your computer.
