### ISSUE TITLE
Nether vortex

### ISSUE THREAD

**Issue by Bouargg** [ValorenWoW/sunstrider-core#5046]
**Describe the bug**
Nether vortex are actually bind

**To Reproduce**
Buy a Nether vortex from Gear's & try to trade it.

**Item ID**
https://db.endless.gg/?item=30183

**Expected behavior**
Nether Vortex should not be bind since 2.4.0 content release.

**Screenshots/videos**

https://wowwiki-archive.fandom.com/wiki/Patch_2.4.0

See at the bottom of this page : 

"[Nether Vortex] are no longer Bind on Pickup and can now be purchased from Neutral G'eras for 15 [Badges of Justice]!"

**Additional context**
No additionnal context. Thanks for reading.

**Comment by kelno** [comment]
The item loses it's BoP on patch 2.4.
Thanks, fixed with next restart.
