### ISSUE TITLE
Enchant Weapon: Deathfrost :(Bind-On-Pickup) Lord Mahune (MidSummer's Fire Fesival) (UNABLE TO OBTAIN?)

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5047]
**Describe the bug**
Since the Only Way to Attain this enchant if by Route of Lord Mahune, it is Impossible in Endless as we dont have this festival!
Can you Maybe Perhaps Make an NPC thats for checks for DEATHFROST and 375 Enchanting at the upcoming Brew Fest? or what are our options?

**Comment by kelno** [comment]
Thanks for reporting.
Indeed you can't get the enchant in this realm iteration, we don't plan on adding it at this point.
