### ISSUE TITLE
RAID-BUFFS DISAPPEARING AFTER CASTING MEMBER LEAVES? NOT TRUE TO 2.4.3 BEHAVIOR!

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5048]
**Describe the bug**
THIS HAS been happening for quite some time, Whenever i Buff someone in a Raid and either myself or that person leaves the Raid, they lose the buff. i havent noticed it with normal party formations and disappations. When did this change happen? This is definitely not true to 2.4.3 Behavior. please fix this. thank you! I should be able to, as a Priest, be capable of being summoned to a Raid, buffing all 24 people, then leaving, then they keep the buffs. (Prayer of Divine Spirit Rank 2, Prayer of Fortitude Rank 3, Prayer of Shadow Protection Rank 2) Thank You! -Draguli

**Comment by kelno** [comment]
Can I get some confirmation from somewhere that this indeed not TBC behavior?

Dev: Currently handled in RemoveAllGroupBuffsFromCaster

**Comment by Jerrythemagicdog** [comment]
This is custom behaviour for our server and is intended.
Thanks for the issue though!
