### ISSUE TITLE
Incorrect Change from Changelog for Power Infusion

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5049]
**Describe the bug**
Incorrect Change According to June 30th Changelog
(Fixed Power Infusion incorrectly stacking with Heroism and Bloodlust.)
True to 2.4.3 Behavior, this should be stackable, Thank you. Draguli

**Comment by kelno** [comment]
Thanks for reporting.
Can you back up that somehow?

**Comment by Jerrythemagicdog** [comment]
Patch 2.4.0 (25-Mar-2008): Infuses the target with power, increasing their spell haste by 20% and reducing the mana cost of all spells by 20%. Lasts for 15 seconds. This will not stack with other haste effects, such as Heroism or Bloodlust. Previously increased damage done by 20%.
