### ISSUE TITLE
Cannot Ressurrect Party Member of Different Faction if they release spirit

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5050]
**Describe the bug**
The Healer Cannot Resurrect a Member of the Other Faction if they Release when they die, and this has to be explained multiple times a day to all new people on the server every day. Please fix this. There must be a way around this. It has been since the server went crossfaction, but there must be a way. Thank You. 

-Draguli

**Comment by kelno** [comment]
Thanks for reporting, confirmed on my side.
I see you can't even mouse over their corpse. Don't know how to fix for now, the server is not preventing it directly. Have to find how the client decides it can even attempt the res.

**Comment by kelno** [comment]
Did a fixie, will work with the next Endless release with the custom client.
(The client decides this based on the corpse race so there is really no clean clean fix without altering client. Another less clean way would be to alter the race we send from the server but that would also change corpse appearance)
