### ISSUE TITLE
EVENT: BREWFEST isnt loaded on the Realm

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5053]
**Describe the bug**
Brewfest isnt loaded on the Realm like it was last year. Can we get it on the schedule please? thank you!

**Character name**
Draguli

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by InhumanGM** [comment]
The event has been started. We apologize for the delay!
