### ISSUE TITLE
URGENT REQUEST - SAVING PVP - UPDATING QUE REQUIREMENTS FOR WSG AND AB AND EOTS

### ISSUE THREAD

**Issue by nokia4life2000** [ValorenWoW/sunstrider-core#5054]
**Describe the bug**
As Clear as title says. Currently, to my knowledge, i believe the que reqs for WSG to pop are 9v9 (18 people total) the needs of the server have changed, and so we need to update this to something more realistic. Most other Private Vanilla servers go as low as 2v2, but to keep the spirit of PVP something along the lines of 4v4 would probably work nicely, considering the pop average daytime of 200-300 lately peak, 100 minimum, 50 nighttime. Thusly, this would assume that Roughly less than 10% of the server would do PVP. I do not know the current requirements for AB (is it 15v15?), but i believe someone at each base should suffice. (so 5v5?).  Also same thing for EOTS. AV is another story

ALSO, i DO NOT like the changing of myself into another race. i think this was implemented with the merge. no one likes it. i dont enjoy being forced to heal alliance lol
i believe that if we lower the que needs, then we can find enough people to que our own faction

PS***I also  just wish we had some feature to tell us how many people in que, and a way to que with a command line, but that's a topic for another day.

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
I've reduced the queues requirement, your request got to me from a GM a while ago.
