### ISSUE TITLE
Can't Download Game

### ISSUE THREAD

**Issue by LeFunk06** [ValorenWoW/sunstrider-core#5055]
**Describe the bug**
I want to start playing on this server but something might be wrong with the installer or .tor file because I have tried both ways and it wont start downloading the game. Its stuck on initializing...0% I have tried on diferent PC's on different networks but same issue.

**Character name**
LeFunk

**Expected behavior**
Maybe give me a different way to install.

**Additional context**

![Screenshot (3)](https://user-images.githubusercontent.com/91621623/135304927-8e0f4a6c-b06c-49bc-8230-a3ae8c706f1f.png)
![Screenshot (4)](https://user-images.githubusercontent.com/91621623/135304937-1903a708-5655-4f44-9053-8f34be4dce97.png)

**Comment by LeFunk06** [comment]
>     1. try and download the game.

**Comment by kelno** [comment]
Seems to be an issue with your network/computer disallowing torrent downloads.
I suggest trying to get the game from another server and then changing the realmlist.
