### ISSUE TITLE
Thori'dal drop rate 

### ISSUE THREAD

**Issue by disis24** [ValorenWoW/sunstrider-core#5059]
Thori'dal drop rate is actually 3% on your database : https://db.endless.gg/?item=34334

According to internet or others database, he must be 6 or 7%.

https://www.wowdb.com/items/34334-thoridal-the-stars-fury
https://www.thegeekcrusade-serveur.com/db/?item=34334
https://www.wow-mania.com/armory/?item=34334#dropped-by
https://tbc.wowhead.com/item=34334/thoridal-the-stars-fury#dropped-by
https://db.rising-gods.de/?item=34334
https://rapidfirewow.wordpress.com/2012/07/14/thoridal-the-grinders-fury/
https://eu.forums.blizzard.com/en/wow/t/legendary-bow-thoridal-the-stars-fury-have-you-seen-it-drop/122962
https://www.cymre.com/2016/01/21/thoridal-the-stars-fury/

Patch changes

    Battle for Azeroth Patch 8.3.0 (2020-01-14): Transmogable.
    Battle for Azeroth Patch 8.0.1 (2018-07-17): Stats squished, Item level squished.
    Legion Patch 7.0.3 (2016-07-19): Animation changed.
    Cataclysm Patch 4.0.1 (2010-10-12): Armor Penetration and Attack Power replaced with Haste and Stamina.
    Wrath of the Lich King Patch 3.1.0 (2009-04-14): No longer increases ranged attack speed by 15%.
    Bc Patch 2.4.3 (2008-07-15): Thori'dal, the Stars' Fury is now Unique as intended.
    Bc Patch 2.4.0 (2008-03-25): Added.

**Comment by kelno** [comment]
Fixed in next server update
