### ISSUE TITLE
Illidan Flame Burst damage is insane post update

### ISSUE THREAD

**Issue by Aeonicz** [ValorenWoW/sunstrider-core#5061]
Illidan double damage on Flame Burst

Spell: https://tbc.wowhead.com/spell=41131/flame-burst

During demon phase this spell seems to be dealing twice as much damage compared to the pre-server update damage.
One of our members mentioned that the damage in combat logs were showing two instances of damage being taken.
Sadly I do not have logs for this fight anymore.

**Comment by kelno** [comment]
Fixed with next restart
