### ISSUE TITLE
Illidan Eye Beam

### ISSUE THREAD

**Issue by Aeonicz** [ValorenWoW/sunstrider-core#5063]
Illidan's Eye Beam during phase two (Flames of Azzinoth phase) work's correctly as it casts along its designed path, however an additional patch is spawned under Illidan's idle position while he casts Eye Beam when flying around the platform.
Unsure if this does damage as we avoided the patches as well.

Spell: https://tbc.wowhead.com/spell=341722/eye-beam
https://tbc.wowhead.com/spell=26134/eye-beam

**Comment by kelno** [comment]
Fixed with next restart
