### ISSUE TITLE
BG's not popping up 

### ISSUE THREAD

**Issue by Holdmyseals** [ValorenWoW/sunstrider-core#5065]
**Describe the bug**
Since the recent update to the server (past week), BG's have no longer been functioning properly. 
Regardless of the amount of played que'd to a specifc BG i.e. AB; the BG will not pop up and therefore not allow players to join the battleground. This results in BG's not being playable and endless wait times for the BGs themselves. 

**Character name**
Yogithebear; this issue has been confirmed for all Endless players.

**To Reproduce**

1. Que any BG i.e. WSG, AB 
2. Wait until there are enough qued in the specifc BG
3. BG pop up will not show (even with min. amount)

**Expected behavior**
Players que BG's, BG pop up shows allowing to join the BG (once min. amount of players has been reached), click the pop up and enter the BG

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Fixed now
