### ISSUE TITLE
World drops

### ISSUE THREAD

**Issue by thehadding** [ValorenWoW/sunstrider-core#5068]
World drop [Formula: Enchant Shield - Shield Block](https://db.endless.gg/?item=22540) is not dropping in the world.
[Wowhead](https://tbc.wowhead.com/item=22540/formula-enchant-shield-shield-block) link.

**Comment by kelno** [comment]
It seems it should be mainly from various dungeon creatures. (from wowhead)

**Comment by z5n** [comment]
thanks, fixed with next update
