### ISSUE TITLE
Shadow Labs Heroic Gem Droprate

### ISSUE THREAD

**Issue by Aeonicz** [ValorenWoW/sunstrider-core#5071]
Been farming this heroic dungeon for a while and I am yet to see any gem drop.
Could you query the database and check that it is indeed the 15% that it is meant to be.

Item: https://db.endless.gg/?item=30563

**Comment by kelno** [comment]
Yes I checked now, you have 45% of dropping one of 3 gems, which gives you indeed 15% for that specific one.
