### ISSUE TITLE
Blessing of Life(Fecundity) spell from Ribbon of Sacrifice doesnt work, doesnt increase healing received.

### ISSUE THREAD

**Issue by Zomrizubo** [ValorenWoW/sunstrider-core#5073]
**Describe the bug**
Blessing of Life(Fecundity) spell from Ribbon of Sacrifice doesnt work, doesnt increase healing received.

**Character name**
Restobeam

**To Reproduce**

1. Activate the trinket.
2. Blessing of life is active for 20 seconds.
3. Fecundity is applied for 10 seconds to all targets healed. Fecundity can stack up 5 times (1 stack = +30 heal received so 5 = 150 healing total) /// but the healing is not increased unfortunately.

https://tbc-twinhead.twinstar.cz/?spell=38332
https://tbc-twinhead.twinstar.cz/?spell=38333
https://tbc-twinhead.twinstar.cz/?item=28590

**Expected behavior**

For the next 20sec, your direct heals grant Fecundity to your target, increasing the healing received by the target by up to 30. Fecundity lasts 10sec and stacks up to 5 times.

**Comment by kelno** [comment]
Thanks for reporting. In my testing the healing does get increased, can you give more details about your testing method here?

**Comment by Zomrizubo** [comment]
Heres a table of my tests, (Target = Myself).
https://docs.google.com/spreadsheets/d/1cKle0K3phm7l-SqN4D8SI8-jfsL80gJ1X5dEk6hppWA/edit?usp=sharing

As you can see Lesser Healing Wave results are not good. Rank 1 (NAKED) - gives only +30 healing increase, Rank 7 (NAKED) - gives about +60 healing increase. Rank 7 (GEARED) - gives about +90 healing incerase, all with Fecundity stacked 5 times on the target. Other healing spells results are around 150 so theres no problem with those. I hope it helped you.

**Comment by kelno** [comment]
I can't access the document
![image](https://user-images.githubusercontent.com/3866946/139185834-16777775-f2f7-4537-bb07-a1844f246320.png)

I'll check your formula for lesser healing wave

**Comment by Zomrizubo** [comment]
> I can't access the document ![image](https://user-images.githubusercontent.com/3866946/139185834-16777775-f2f7-4537-bb07-a1844f246320.png)
> 
> I'll check your formula for lesser healing wave

This should be good now.
https://docs.google.com/spreadsheets/d/1cKle0K3phm7l-SqN4D8SI8-jfsL80gJ1X5dEk6hppWA/edit?usp=sharing

**Comment by kelno** [comment]
Thank you.

Lesser Healing Wave rank 7 should have a spell bonus factor of:
1500 / 3500 =  0.429 

So from our trinket stacks we should get 150 * 0.429 = 64.29 (extra healing on average, without talents)
Which does fit your "naked" column test, you get about that much additional healing. 

Am I missing something more? 
I also checked on my side, with no gear no talent except the trinket with 5 stacks I get 223 bonus healing on the target, which is correctly 150 + the base 73 on the trinket.  This correctly results in 95 extra heal done compared to being completely naked.

**Comment by Zomrizubo** [comment]
> Thank you.
> 
> Lesser Healing Wave rank 7 should have a spell bonus factor of: 1500 / 3500 = 0.429
> 
> So from our trinket stacks we should get 150 * 0.429 = 64.29 (extra healing on average, without talents) Which does fit your "naked" column test, you get about that much additional healing.
> 
> Am I missing something more? I also checked on my side, with no gear no talent except the trinket with 5 stacks I get 223 bonus healing on the target, which is correctly 150 + the base 73 on the trinket. This correctly results in 95 extra heal done compared to being completely naked.

Thank you Kelno for the nice analysis. Keep up the good work!

**Comment by kelno** [comment]
Alright I'll close this one then, thanks for all the details
