### ISSUE TITLE
There is a bug i guess in shadowmoon valley , with the npc Sanoru , its supossed he give me a quest (Proof of Allegiance) but no , idk if it is a chain quest but in my map appear he giving me that quest :p.

### ISSUE THREAD

**Issue by Kanekidelau** [ValorenWoW/sunstrider-core#5074]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by InhumanGM** [comment]
Please create a ticket in-game.
