### ISSUE TITLE
Steady Shot missing from Spellbook

### ISSUE THREAD

**Issue by Holdmyseals** [ValorenWoW/sunstrider-core#5075]
**Describe the bug**
Fresh lvl70 Hunter doesn't have Steady Shot in their spellbook.

**Character name**
Missdirekt

**To Reproduce**
Look in spellbook

Spell: https://www.wowhead.com/spell=56641/steady-shot

**Additional context**
I also tried to use a /cast steady shot macro, but it also didn't work.

**Comment by kelno** [comment]
Fixed since last restart
