### ISSUE TITLE
Channeling spells.

### ISSUE THREAD

**Issue by EndlessFlack** [ValorenWoW/sunstrider-core#5077]
**Describe the bug**
Channeling spells are not recieving pushbacks. (ie. Evocation, Arcane Missiles, Mind Flay)

**To Reproduce**
Cast any spell that channels, while recieving damage.

https://tbc.wowhead.com/spell=12051/evocation
https://tbc.wowhead.com/spell=38704/arcane-missiles

**Comment by kelno** [comment]
Fixed with next restart
