### ISSUE TITLE
rogue eviscerate doesn't do any damage

### ISSUE THREAD

**Issue by overdev93** [ValorenWoW/sunstrider-core#5078]
**Describe the bug**
eviscerate doesn't do any damage, nothing is displayed and the enemy health bar also doesn't move.

**Character name**
Senika

**To Reproduce**
just use eviscerate

**Expected behavior**
well it should do damage

**Comment by Joeyskate813** [comment]
Same here, it will use combo points but it wont cause damage or even acknowledge evicerate in the combat log

**Comment by kelno** [comment]
Thanks, fixed with next server update
