### ISSUE TITLE
Rogue Evicerate will not do damage

### ISSUE THREAD

**Issue by Joeyskate813** [ValorenWoW/sunstrider-core#5079]
**Describe the bug**
When you use evicerate it will not register in combat log or do damage, it was showing in the combat log saying it was casted but not even doing that now! Please help!!

**Character name**
Bakstabdatho

**To Reproduce**

1. Cast X on target affected by ... 
2. Use evicerate and you will see the problem, i have no idea how to fix, i reinstalled and same issue
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
It should do damage and it should register in the combat log instead of using the combo points and doing 0 damage.

**Screenshots/videos**

**Additional context**
Please fix as soon as you can please

**Comment by kelno** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/5078
