### ISSUE TITLE
chat and group invite problems

### ISSUE THREAD

**Issue by AidynAmrenov** [ValorenWoW/sunstrider-core#5082]
**Describe the bug**
Chats (general, whisper, global, group) do not work, except for guild chat. I see all the messages in the chats, but no one sees my messages. My messages are visible only in the guild chat. Also, my invitations to the group and guild do not work. I can accept group and guild invitations, but no one sees my group invitations.

**Character name**
Ainiet
Ainiets
Ainiett

**Expected behavior**
Unblocking chats and group invitations

**Comment by InhumanGM** [comment]
Fixed for the aforementioned characters.
