### ISSUE TITLE
 Glimmering Naaru Sliver not affected by spell haste rating 

### ISSUE THREAD

**Issue by DadSerber** [ValorenWoW/sunstrider-core#5086]
**Describe the bug**
Glimmering Naaru Sliver should be affected by spell haste rating and lower the cast time from 8seconds. The item itself is pretty bad already and now its not lowering the casttime. 

**Character name**
Leflashz

**To Reproduce**
I have 453 spell haste, it should lower the 8s casttime to 6.22s. But it not affected at all, it starts at 8s, doesnt matter how much or less spell haste rating i use. With bloodlust it should lower the cast to 4.78s (bl + my 453 spell haste), but it also not affecting the casttime. Its still 8s.

Item: https://www.wowhead.com/item=34430/glimmering-naaru-sliver

**Expected behavior**
It should be affected by the spell haste rating

**Screenshots/videos**
Not needed. Pretty straight forward.

**Additional context**
Bloodlust should affect the casttime too.

**Comment by kelno** [comment]
Thanks, fixed with next restart
