### ISSUE TITLE
Cant log more than 1 account at same time

### ISSUE THREAD

**Issue by Atrax0921** [ValorenWoW/sunstrider-core#5087]
After creating new account 2 days ago server started to block me.
When i try to log in second account it goes till "success" but if i log out first acc it immidiatelly logs in.

I dont share my ip with anyone and nothing changed with my internet connection during last days.

One of my ingame characters nick - atrax. Also created ticket.

**Comment by kelno** [comment]
Thanks for reporting. It's a tricky issue, this happens sometimes if you get a lot of connection improperly closed, they might take a while (hours?) to close. I don't have a fix for you except waiting or using another connection (such as the phone one) when it happens.

**Comment by Atrax0921** [comment]
What do You mean "improperly closed" ? Nothing changed for a 3 days and now after morning offline i cant log in at all.
I had similar issue on sunstrider year ago, but then it was fixed after ticket.

**Comment by kelno** [comment]
I forcefully closed your connections, it should be better now.

**Comment by Atrax0921** [comment]
Thank You very much it works well. If u know what was cause of this let me know so i can avoid it in the future

**Comment by Atrax0921** [comment]
Problem came back. Today morning everything worked fine. In the afternoon i found out 2 connection are still open. 
Now i can log only 1 account so 4 connections are still open.
I dont understand what can cause it,  for almost month it was ok and now it happens again.
Please fix this. Thank you in advance.

**Comment by kelno** [comment]
Thank you for reporting it.
I've fixed it again manually again, but I don't understand yet what's specific about you causing this. I'll try to make a timeout system to avoid this.

**Comment by Atrax0921** [comment]
Thank You very much for your effort. It is very weird indeed. Nothing changed in last month, yesterday morning everything was ok, and suddenly connections stopped closing.

**Comment by kelno** [comment]
I've implemented something that could help, though I can't really be sure it will fix your specific case yet. I'll apply this with the next server update.
If you still have the issue later you can poke me on Discord to look into it.
