### ISSUE TITLE
Alchemy Discoveries

### ISSUE THREAD

**Issue by gdubeau** [ValorenWoW/sunstrider-core#5088]
I've been a transmute master on my priest since windrunner opened. and i fairly regularly transmute primal mights. I have not once discovered a new transmute other than the purchasable patterns

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
I see other, non-pattern transmutes (such as Transmute: Primal Earth to Life - 28585) are being able to be discovered with a 1% chance.
I'll up the chance to 5% since that seems too low.
