### ISSUE TITLE
Swift Flight Form (Druid) can be taught to any class.

### ISSUE THREAD

**Issue by Zomrizubo** [ValorenWoW/sunstrider-core#5089]
**Describe the bug**
A druid can teach this spell to any class. You can investigate how, but few people on the server know how to do it. If you cant find the bug I can ask someone about how its done.

**Character name**
I have a screenshot of a player using it, but I dont want to expose anyone, the population cant afford bans. But this bug is 100% real.

**To Reproduce**
Unknown.

Spell: https://tbc-twinhead.twinstar.cz/?spell=40120
Quest: https://tbc-twinhead.twinstar.cz/?quest=11001

**Expected behavior**
The Swift Flight Form is obtained via quest only for a druid.

**Screenshots/videos**
Have proof but Ill not use it.

**Additional context**
I suggest to remove the spell from all characters that have it already learned and are not druids.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed.
