### ISSUE TITLE
Meteor Slash on Brutallus bugged doesnt split the dmg (SWP Broken).

### ISSUE THREAD

**Issue by Zomrizubo** [ValorenWoW/sunstrider-core#5090]
**Describe the bug**
Meteor Slash on Brutallus is bugged and doesnt split the dmg, memebrs get 20k damage and are instantly killed no matter the position... So Sunwell is broken atm.

**Character name**
Restobeam

**To Reproduce**
Npc: https://tbc-twinhead.twinstar.cz/?npc=24882
Spell: https://tbc-twinhead.twinstar.cz/?spell=45150

**Expected behavior**
Meteor Slash - Deals 20,000 Fire damage split between enemy targets in a cone in front of the caster (as of 2.4.1, unlimited range). Increases Fire damage taken to all targets affected by 75%. Stacks to 100, duration 40 secs.

**Comment by kelno** [comment]
Thanks, we restarted with a fix
