### ISSUE TITLE
Missing last ranks of spells and abilities of mages warriors such as fronst bolt rank 14 fire bolt heroic strike etc help!

### ISSUE THREAD

**Issue by Mangezov** [ValorenWoW/sunstrider-core#5094]
**Describe the bug**
Missing last ranks of spells and abilities of mages warriors such as fronst bolt rank 14 fire bolt heroic strike etc reloging switching specks or  going to trainers didn't work spells still missing 

**Character name**
kurq

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://tbc.wowhead.com/spell=38697/frostbolt

**Expected behavior**

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/63115180/154579109-1563ada2-1e16-4b7d-b784-071f39a3fc95.png)

**Additional context**

**Comment by Mangezov** [comment]
Just loged into the game and notice that i miss my last ranks of spells on mage and warrior frost bolt rank 14 fire bolt rank 14 arcane missiles rank 11 heroic strike rank 11 ask in global people were saying that they have same problems not sure if other classes have some missing spells and abilities too.

**Comment by Mangezov** [comment]
![image](https://user-images.githubusercontent.com/63115180/154577878-96ef879c-ab39-4a29-a7a9-1ea811fd7e9a.png)

**Comment by Mangezov** [comment]
![image](https://user-images.githubusercontent.com/63115180/154578023-522a9436-a88e-4205-9674-82d666987917.png)

**Comment by Mangezov** [comment]
![image](https://user-images.githubusercontent.com/63115180/154578147-48e085e9-fcc5-4059-8033-a9739feed814.png)

**Comment by Mangezov** [comment]
![image](https://user-images.githubusercontent.com/63115180/154578280-5213d198-d44c-433f-b743-07b0314aadfe.png)

**Comment by Mangezov** [comment]
reloging or switching specks or going to trainers don't work spells are still missing

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
These are the correct max ranks available in TBC. 
Due to a mistake I've made earlier, higher ranks (like r14 Frostbolt, r11 Heroic Strike, etc) were made available.

**Comment by Mangezov** [comment]
> Thanks for the issue. These are the correct max ranks available in TBC. Due to a mistake I've made earlier, higher ranks (like r14 Frostbolt, r11 Heroic Strike, etc) were made available.

yes and why we are still missing them ?

**Comment by Jerrythemagicdog** [comment]
To clarify: the ranks you've screenshotted (Rank 13 Frostbolt, Rank 10 Heroic Strike, Rank 13 Fireball, Rank 10 Arcane Missiles) are the correct max ranks for TBC.
