### ISSUE TITLE
Can't train Engineering from 300 to 375 at Outland trainers

### ISSUE THREAD

**Issue by Dwarvensnip** [ValorenWoW/sunstrider-core#5096]
Character name - Arhont
I get engineering 300/300 but can't up it to 375 at Outland trainers in Honor Hold and Area 52. I see at trainers red recipes only which I'll be able to train from 310 and further, but can't up engineering from 300 to 375.

**Comment by kelno** [comment]
Thanks for reporting. I'm restarting the server now, this should be fixed.
