### ISSUE TITLE
Error message when downloading the client

### ISSUE THREAD

**Issue by Peympour** [ValorenWoW/sunstrider-core#5097]
**Describe the bug**
When you click on "Download for Windows"
another web page opens with:

HTTP 404: Nothing found
The web page was not found

I tested it on Firefox/Edge/Internet Explorer. All over the same message.

![error](https://user-images.githubusercontent.com/56338736/156930214-fe04387d-d63a-4c1c-99fb-381bf835e910.PNG)

**Comment by kelno** [comment]
Thanks for reporting
