### ISSUE TITLE
Can not link items in chat

### ISSUE THREAD

**Issue by PadreWoW** [ValorenWoW/sunstrider-core#51]
**Description:**

Can not link items in chat

**Current behaviour:**

When you try to link any item in chat you can see error in logs:
Player Test (GUID: 1) sent a message with an invalid link:
 |cff0070dd|Hitem:17718:0:0:0:0:0:0:0|h[Gizlock's Hypertech Buckler]|h|r
Player Test (GUID: 1) sent a message with an invalid link:
 |cff0070dd|Hitem:9375:0:0:0:0:0:0:0|h[Expert Goldminer's Helmet]|h|r
Player Test (GUID: 1) sent a message with an invalid link:
 |cff1eff00|Hitem:6092:0:0:0:0:0:0:0|h[Black Whelp Boots]|h|r

**rev. hash/commit:** 
last

**Operating system and compiler:**
Win Serv 2016

**Comment by woiwoz** [comment]
confirm

**Comment by Nolin7777** [comment]
Set [this](https://github.com/ValorenWoW/sunstrider-core/blob/master/src/server/worldserver/worldserver.conf.dist#L1351) to 0.

**Comment by woiwoz** [comment]
thanks
