### ISSUE TITLE
r1 buffs dampen magic and amplify magic are debuffs 

### ISSUE THREAD

**Issue by bstajduhar** [ValorenWoW/sunstrider-core#5102]
**Describe the bug**

When I use rank 1 dampen magic or amplifying magic I get it as debuff instead of buff 
**Character name**

michaelscarn
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

I should have those spells as buffs instead of debuffs
**Screenshots/videos**

https://prnt.sc/q5AiURrDoSeT
**Additional context**

**Comment by kelno** [comment]
Thanks, fixed with next restart
