### ISSUE TITLE
Mirror image, target bug

### ISSUE THREAD

**Issue by bstajduhar** [ValorenWoW/sunstrider-core#5104]
**Describe the bug**

When I cast a mirror image enemies can't target me, the target is constantly switching from me to my mirror images whenever they cast a spell 
**Character name**

Michaelscarn
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

Whenever they target me, target should not be switching if I casted mirror images.
**Screenshots/videos**

can't provide it at the moment.
**Additional context**

**Comment by kelno** [comment]
Thanks, fixed with next restart
