### ISSUE TITLE
Pets get stuck on Dalaran Arena

### ISSUE THREAD

**Issue by Jgrenier91** [ValorenWoW/sunstrider-core#5105]
**Describe the bug**
When exiting the buffing zone upon arena match start, players will leave the area but their pets are left stuck above.

**Character name**
Jpg

**To Reproduce**
Play any arena match on Dalaran Arena with a pet summoned

**Screenshots/videos**
https://i.imgur.com/ZFSBfod.jpeg

**Comment by Jerrythemagicdog** [comment]
Thanks, the issue should be resolved now.
Let us know if it's still happening and we'll reopen it. 
0d39357e1a7d9d95ea401373e38c1218a1b7f207
