### ISSUE TITLE
engi enchants

### ISSUE THREAD

**Issue by ckxdax2** [ValorenWoW/sunstrider-core#5106]
**Describe the bug**
Engineering enchants on enchants vender on boots section instead of hands,

**Character name**
joleax

**To Reproduce**
@vendor
1. 
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, it will be resolved with the next update.
