### ISSUE TITLE
Warrior can shield wall while beeing disarmed 

### ISSUE THREAD

**Issue by bstajduhar** [ValorenWoW/sunstrider-core#5107]
**Describe the bug**

If a warrior is disarmed he still can shield wall even tho that's not how it's intended to work.
**Character name**

Michaelscarn
**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

Warrior should not be able to shield wall while being disarmed.
**Screenshots/videos**

https://prnt.sc/-SCEzlI3NfQz
**Additional context**

**Comment by BugWar** [comment]
Apologies, but you are wrong, war only can NOT use shield spells when he is DISMANTLE by rogue, others disarms allows him to use the shield skills.
