### ISSUE TITLE
Berserker rage into Enraged regeneration (WARRIOR)

### ISSUE THREAD

**Issue by BugWar** [ValorenWoW/sunstrider-core#5108]
**Describe the bug**
When u have berserker rage up and u want to use Enraged Regeneration, this last spell just got on CD and the effect does no work,

**To Reproduce**
1. Having enough rage to use enraged regeneration
2. Use berserker rage
3. Use enraged regeneration

**Expected behavior**
Berserker rage should be autocanceled in order to let u use enraged regeneration

**Screenshots/videos**
Problem here
(https://gyazo.com/bf3daa8c459a78551ca739b455f2894a)

**Comment by Jerrythemagicdog** [comment]
Thanks for the report!

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.
