### ISSUE TITLE
Empower Rune Weapon - Death Rune Mastery not all of death runes reset

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5109]
Empower Rune Weapon doesn't reset all death runes from Death Rune Mastery talent (Blood). 

Right Unholy Rune doesn't get refreshed ever and I am not sure if other runes also sometimes don't reset. 

Empower Rune Weapon (ability, 5min cd) should make all runes - including death runes from talents and Blood Tap - instantly available.

**Comment by kelno** [comment]
Thanks for reporting, fixed with next update
