### ISSUE TITLE
Death Knights can wear only Cloths and Plates

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5110]
**Describe the bug**
Death Knights can't wear and can't learn to wear Leather and Mail armor. 

**Character name**
Akmonx

**To Reproduce**
1. Create Character
2. Try to Equip Mail or Leather armor
3. (optional) check in Character sheet - Skills - there are only 2 options Cloth and Plate.

**Expected behavior**
Death Knight should be able to wear all types of armor.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
