### ISSUE TITLE
Death Grip - Doesn't interrupt casts instantly

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5111]
**Describe the bug**
Death Grip does not interrupt enemy spellcast when we cast death grip, but enemy player flies all the way to us while casting and if he is not finished then his cast is interrupted on landing. 

**To Reproduce**
1. Cast Death Grip in max range on target that is close to finish of cast.
2. Observe him fly and finish his cast.

**Expected behavior**
Enemy spellcast is stopped as soon as Grip starts.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report!

**Comment by Jerrythemagicdog** [comment]
Fixed with next update
