### ISSUE TITLE
Runes go on 10 seconds cooldown when Dodged or Parried

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5112]
**Describe the bug**
When our ability that costs runes gets dodged, parried or blocked we get full 10 seconds of cooldown on them. 

**To Reproduce**
1. Cast Death Strike on enemy.
2. Get Dodge or Parry
3. Feel the pain of losing 2 runes for 10 seconds.

**Expected behavior**
When Dodged or Parried or Blocked in PvP runes should getGCD.

**Additional context**
Please if it is necessary then somebody provide links etc.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!

**Comment by kelno** [comment]
Fixed with next restart
