### ISSUE TITLE
Blood Presence and Improved Blood Presence - auto attacks don't heal

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5113]
**Describe the bug**
When in Blood Presence (or in other presence with Improved Blood Presence learned) we do not get healed from auto attacks. 
Abilities seem to be healing like they should. 

**To Reproduce**
1. Cast Blood Presence or learn Improved Blood Presence talent.
2. Use auto attacks on enemies or dummies.
3. Do not get healed.

**Expected behavior**
Autoattacks should heal for 4% of their damage done.

**Comment by kelno** [comment]
Fixed with next server update
