### ISSUE TITLE
Glyph of Death Strike - increases damage at all times, independently of Runic Power

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5114]
**Describe the bug**
Glyph of Death Strike increased Death Strike damage always - when we have 0 Runic Power our Death Strike damage is also increased.

**To Reproduce**
1. Get Glyph of Death Strike
2. Profit of 25% increased Death Strike damage at all times.

Glyph: https://wotlk.evowow.com/?item=43827

**Expected behavior**
When at 0 Runic Power we shouldn't get any damage increase on Death Strike. When at or above 25 Runic Power we should get 25% damage increase on Death Strike. 
When between 0 and 25 Runic Power - Death Strike damage should be increased by [runic power integer]%.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report!

**Comment by kelno** [comment]
Fixed with next update
