### ISSUE TITLE
Death Coil healing is too low

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5115]
**Describe the bug**
When I cast Lich Borne and try to heal myself the healing is too low. 
In spell description it says it should heal friendly Undead target for 665. It should also benefit from attack power. 
I get on myself and on my ghoul 664 healing.
I tried to equip Spell Power weapon to see if it maybe increases by it, but the healing was the same. 

**To Reproduce**
1. Cast Death Coil on Undead target.
2. Observe low healing.

Spell: https://wotlk.evowow.com/?spell=49895

**Expected behavior**
Death Coil healing should be increased by Attack Power. 

**Additional context**
I don't know where to find exact numbers for how much of attack power should benefit it.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!

**Comment by kelno** [comment]
Fixed with next server update
