### ISSUE TITLE
[DK] Blade Barrier talent - doesn't work if we do not deal dmg with Blood Rune

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5116]
**Describe the bug**
When our spell doesn't hit target it doesn't trigger Blade Barrier.

**To Reproduce**
1. Cast two times Blood Boil or Blood Boil and Death and Decay without hitting any targets.
2. Do not get buff.

**Expected behavior**
You should get buff whenever your second Blood Rune goes on cooldown.

https://wotlk.evowow.com/?spell=49500

Tested on 2/5

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!

**Comment by kelno** [comment]
Fixed with next restart
