### ISSUE TITLE
Owlkin Frenzy [Druid - Balance]

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5118]
**Describe the bug**
Owlkin Frenzy is removed when exiting Moonkin Form.

**To Reproduce**
1. Get Owlkin Frenzy proc.
2. Exit Moonkin form or change to other form.
3. Watch Owlkin Frenzy getting removed.

https://wotlk.evowow.com/?spell=48393

**Expected behavior**
Owlkin Frenzy should persist through form changes. It makes druid go Frenzy it is same group of effects as Enrage. 

**Screenshots/videos**
If very needed I can spend hours of searching for this retail video that showcases it in action. If anybody else has the link or remembers the name please link it.

**Comment by Akmonx** [comment]
https://www.youtube.com/watch?v=zzLaos13gYM
0:24

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.

**Comment by Jerrythemagicdog** [comment]
https://github.com/kelno/sunstrider/commit/845c397622df31948857314db5fdfcad0bee81af
