### ISSUE TITLE
Nature's Grace doesn't proc of off Starfall [Druid]

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5119]
**Describe the bug**
Nature's Grace doesn't proc of off Starfall crits but it should as Starfall is non-periodic. 

**To Reproduce**
1. Cast Starfall while having Nature's Grace talent.
2. Wait for crits.
3. Observe not getting Nature's Grace buff when critting with Starfall.

https://wotlk.evowow.com/?spell=61346

**Expected behavior**
Nature's Grace procs when any of Starfall stars crits.

**Comment by Akmonx** [comment]
It seems to not proc from enemy players. On dummies I get procs.

**Comment by Akmonx** [comment]
When tested on duel it did proc on enemy player.
When on Arena I have seen crits on cluster of players and didn't get proc. 
It might have been random issue or me not paying enough attention. 

Sorry if it doesn't happen on arena then this is not an issue.

**Comment by Akmonx** [comment]
![image](https://user-images.githubusercontent.com/42322589/165597721-fee4adac-9b8d-451d-be79-016303b6d72e.png)
Doesn't proc when crit did take place into absorb.

**Comment by Jerrythemagicdog** [comment]
Thanks for the details!

**Comment by kelno** [comment]
Fixed with next update
