### ISSUE TITLE
Brambles and Force of Nature [Druid]

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5120]
**Describe the bug**
Brambles [2/3] doesn't seem to give daze chance to treants. 
I have spawned Treants three times and they attacked through whole duration. I didn't get a single daze proc.

**To Reproduce**
1. Get Brambles talent.
2. Use Treants to attacks somebody.
3. Look at them not geting dazed.

**Expected behavior**
Each Treants auto attack should have 5/10/15% daze chance independently of others.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
