### ISSUE TITLE
Hurricane interrupted doesn't lock any spell school [Druid]

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5121]
**Describe the bug**
When somebody interrupts Hurricane, the Druid doesn't get locked on casting spells.

**To Reproduce**
1. Channel Hurricane.
2. Get interrupted.
3. Cast any spell you want.

**Expected behavior**
Druid should be locked out of Nature's spell school.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
