### ISSUE TITLE
Force of Nature - treants spawn too far away from each other

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5122]
**Describe the bug**
Treants spawn really far away from each other. 
It seems like they all spawn in the center of AoE mark but with small interval between their spawns (0.1s or less). 

**To Reproduce**
1. Cast Force of Nature on selected location.
2. Look how for away from each other they get spawned.

**Expected behavior**
Treants spawn at the same place or really, really close to each other. 

**Screenshots/videos**
vid: https://www.youtube.com/watch?v=zzLaos13gYM 
1:07, 2:23, 3:06, 

**Additional context**
This spell with macro for /petstay can be used to eat hunters traps but currently its not possible to do that.

**Comment by z5n** [comment]
won't be changed
