### ISSUE TITLE
Bloodworms HP is too low [DK Blood] 

### ISSUE THREAD

**Issue by Akmonx** [ValorenWoW/sunstrider-core#5123]
**Describe the bug**
Bloodworms should have higher HP (it probably should scale a bit with players stamina, if it is already then it's not enough. 

**To Reproduce**
1. Learn Bloodworms talent.
2. Check their HP.

**Expected behavior**
Bloodworms having more health. 

**Screenshots/videos**
![image](https://user-images.githubusercontent.com/42322589/165604730-8913130d-180e-4fde-94a0-5f4a59aed97a.png)
https://www.youtube.com/watch?v=zzLaos13gYM 2:22 we can see Blodworms taking 2 times 260 dmg and still having a bit of life. DK on video also had lower HP than Relentless geared DK.

**Comment by Jerrythemagicdog** [comment]
We've updated the HP a bit to at least match the source you've provided closer.
If you manage to get more sources we can get closer to the correct value.
Thanks for the issue, change applied with the next update.
