### ISSUE TITLE
Priests 'Prayer' buffs cannot be cast as discipline

### ISSUE THREAD

**Issue by CathalOR** [ValorenWoW/sunstrider-core#5127]
Priests 'Prayer' buffs cannot be cast as discipline - it says 'must be in shadow form'
![image](https://user-images.githubusercontent.com/35314724/166761224-9d9e6e86-79f2-412c-b1b0-cc69b33fb608.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
