### ISSUE TITLE
WotLK - Glyph of Smite has no effect

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-core#5129]
**Describe the bug**
Glyph of Smite is not causing the target to take additional damage when the conditions are met.

**To Reproduce**

1. Priest equips Glyph of Smite (Item 42416)
2. Priest attacks target with Holy Fire to apply debuff (eg. Holy Fire rank 11 - 48135) which applies Holy Fire debuff
3. Attack target with Smite (eg. Smite rank 12 - 48123)

Item: Glyph of Smite (Item 42416)

Spell: Holy Fire rank 11 - 48135) and Smite rank 12 - 48123

**Expected behavior**
Target should take 20% extra damage from Smite in this scenario.

rev. 33190

**Comment by kelno** [comment]
Fixed with next update
