### ISSUE TITLE
WotLK - Improved Succubus incorrect effect

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-core#5133]
Warlock talent Improved Succubus (18756) is reducing the duration of the Seduction (6358) spell.

It should only be reducing the cast time of the spell, not its duration.

In fact, the talent should increase the duration (where possible, outside pvp etc.)

rev. 33190

**Comment by Jerrythemagicdog** [comment]
fixed a while ago in https://github.com/kelno/sunstrider/commit/f662c010607e3fc47578b14fe6a13e3b6de1fde4
