### ISSUE TITLE
Changing spec on https://endless.gg do not change spec of character

### ISSUE THREAD

**Issue by kdlev** [ValorenWoW/sunstrider-core#5134]
**Describe the bug**
Character management tool on endless.gg website does not allow for the spec to be succesfully changed.  In this particular case, I am attempting to change my spec from shadow to holy, but it will not allow me to do so.

**Character name**
Hoepreest

**To Reproduce**
1. Log into https://endless.gg
2. Go to characters, change spec.
3. Log into endless.gg TBC server.
4. Spec is the same as it was, and if you refresh the `https://endless.gg/account/manage/characters` page the spec selected will revert from desired spec to previous spec.

**Expected behavior**
Normal behavior would be to select the spec you want, log in (or log out and back in) to the TBC server and have the spec you selected.

**Screenshots/videos**

![image](https://user-images.githubusercontent.com/48071903/172507513-6bdf4a3b-bc9c-408a-b6cd-0c1094f1f590.png)

**Comment by Jerrythemagicdog** [comment]
Thanks, we've made a mistake in a recent update, it'll be resolved with the next update (most likely later today)!

**Comment by kelno** [comment]
Should work now
