### ISSUE TITLE
Glyph of Shadow Dance does not apply its effect

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-core#5137]
**Describe the bug**
Glyph of Shadow Dance (45764) does not apply its effect to Shadow Dance (51713) despite tooltip updating.

**To Reproduce**

1. Equip Glyph of Shadow Dance (45764)
2. Use Shadow Dance (51713)
3. Observe the spell duration is  only 6seconds instead of 8seconds

**Expected behavior**
Spell should be extended by 2 seconds

rev. 33530

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
https://github.com/kelno/sunstrider/commit/cc6bf9c39e14f2dffd10119c743534bf276a92db
