### ISSUE TITLE
hellow

### ISSUE THREAD

**Issue by ccwower** [ValorenWoW/sunstrider-core#5140]
Hello, I am a student from China, and I hope to work with you to update the hellground project. Now I have encountered some problems, and the VS2012-2015 version cannot successfully compile your core code. Could you please help me solve the problem?

**Comment by kelno** [comment]
Hey, this bugtracker is used for the Endless server bug reports, which uses the Sunstrider Emulator. We have nothing to do with the hellground project.

**Comment by ccwower** [comment]
感谢支持 -- 邮件我已收到 ！

**Comment by ccwower** [comment]
Hello, brother administrator, I am a programming student from the Chinese community. As far as I know, Sunstrider also has members participating in China. I hope I can join and get core code support from you! I will continue to give feedback on bugs submitted by players and players in China


Can you invite me to join the closed source group?











&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunstriderEmu/BugTracker"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月9日(星期三) 凌晨2:44
***@***.***&gt;;
抄送:&nbsp;"TBC70级2.43 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [SunstriderEmu/BugTracker] hellow (Issue #5140)





 
Hey, this bugtracker is used for the Endless server bug reports, which uses the Sunstrider Emulator. We have nothing to do with the hellground project.
