### ISSUE TITLE
Hello to the SunstriderCore Open Source Group, I hope to join you

### ISSUE THREAD

**Issue by ccwower** [ValorenWoW/sunstrider-core#5141]
Hello, brother administrator, I am a programming student from the Chinese community. As far as I know, Sunstrider also has members participating in China. I hope I can join and get core code support from you! I will continue to give feedback on bugs submitted by players and players in China

Can you invite me to join the closed source group?

**Comment by woiwoz** [comment]
留下你的联系方式 QQ

**Comment by ccwower** [comment]
大佬您好, 我的QQ是 330111459 ,可以获得闭源的sunstridercore项目吗?

**Comment by ccwower** [comment]
Hello, my QQ is 330111459, can I get the closed source sunstridercore project?

**Comment by ccwower** [comment]
> 

Hello boss, can I join the closed source Sunstrider project? My QQ is 330111459
