### ISSUE TITLE
Server died

### ISSUE THREAD

**Issue by pwgrzyn** [ValorenWoW/sunstrider-core#5146]
Server Died so its Website did. Also we were still experiencing bugs connected with karazhan and dungeons.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue. We're looking into it. More news tomorrow!

**Comment by Jerrythemagicdog** [comment]
The server is back up, please create a separate detailed issue for the Karazhan and dungeon issues you've encountered.
