### ISSUE TITLE
Karazhan and other dungeons bugs

### ISSUE THREAD

**Issue by pwgrzyn** [ValorenWoW/sunstrider-core#5147]
So far i have only noticed 2 bugs with dungeons:
1.Watchkeeper Gargolmar does not spawn in ramparts
2.Characters that were moved from sunstrider cannot enter MGT Heroic it says "You need to be level 71 or above"

And the Karazhan issue is that  whenever you enter the raid server crashes after few seconds, however you can immediately log back in.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, indeed these were present on the live server.
We've restarted the server with an update, and all of the above are fixed.
