### ISSUE TITLE
Ethereum Jailors and quest bugs

### ISSUE THREAD

**Issue by pwgrzyn** [ValorenWoW/sunstrider-core#5148]
Sorry to bother you but we have encountered some bugs. I am not sure how long these bugs are in the game but surely less than 5months.
Quests:
1. Sunfury Plans Attack
2. Blast the Gateway 
simply both of those are bugged Sunfury attack plans just doesnt drop and in the second quest there is an issue that after killing Incandescent Fel Spark is killed he doesnt leave this thingy to buff the spark

Finally about Ethereum Jailors. They seem not to spawn at all.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.

1. They do drop, I've just tried myself and have gotten the drop from a Sunfury Researcher in Manaforge Coruu after about 6 kills on the other Sunfury NPCs nearby. The drop rate is around 5%.
2. I've also tried this quest and I don't really understand the issue. I've summoned the spark using the provided quest item, killed ~10 Incandescent Fel Sparks, the summoned spark grew bigger as I was killing the elementals, eventually turned green and I led it to the gateway where it flew into it and completed the quest objective for me. You'll need to be more specific about the issue you're having.
3. Ethereum Jailors are pooled together with other Ethereum NPCs in the Voidwind Plataeu and will respawn in different locations around Voidwind Plataeu as you're killing the Ethereum NPCs. I've just checked and right now there are a few of them alive on the live server in that area.

Hope this helps, don't hesitate to open another issue.
