### ISSUE TITLE
Earthmender Wilda stuck

### ISSUE THREAD

**Issue by vaeltepeter** [ValorenWoW/sunstrider-core#5150]
**Describe the bug**
Accepting the quest "Escape from Coilskar Cistern" from Earthmender Wilda, after first freeing her from her water prison, does not trigger Earthmender Wilda to move on through the cavern towards the water elementals she wish to free and ultimately to safety at the caverns entrance. She simple remains in place, aggroing close-by mobs, but otherwise not advancing. This renders the quest unable to complete entirely.

**Character name**

Orkas 

**To Reproduce**

1. Kill the naga spellcaster maintaining the water prison spell on Wilda
2. Talk to Wilda once she lands at the far end of the pool
3. Accept the quest "Escape from Coilskar Cistern"
4. observe

Quest: [https://wowhead.com?quest=](https://www.wowhead.com/tbc/quest=10451/escape-from-coilskar-cistern)
NPC: https://www.wowhead.com/tbc/npc=21027/earthmender-wilda
NPC: https://www.wowhead.com/tbc/npc=20795/keeper-of-the-cistern

**Expected behavior**

I expected Wilda to pick up her dress and move along through the cistern, ending in the liberation of her and her water elemental fellows from the clammys naga claws

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
