### ISSUE TITLE
Ride the lightning

### ISSUE THREAD

**Issue by pwgrzyn** [ValorenWoW/sunstrider-core#5152]
In the quest Ride the Lightning if you get slowed or mount up(prolly getting affeceted by any movement speed modifier) while in  Repolarized Magneto Sphere's bubble it  turns off and you cannot use the item again unless u relog.

https://www.wowhead.com/tbc/item=30818/repolarized-magneto-sphere
https://www.wowhead.com/tbc/quest=10657/ride-the-lightning

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
