### ISSUE TITLE
A character having XP locked can prevent XP for the whole party

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#5154]
When you are in a party with someone who has their xp on x0 (locked) you will not gain any experience.

Could you please try fix this so that players will still gain xp while being in a party with another player who has their xp locked?

Many thanks.

**Comment by kelno** [comment]
Related: https://github.com/SunstriderEmu/BugTracker/issues/5081

**Comment by mickwow** [comment]
Thanks for acknowledging this Kelno. If it cannot be fixed, i would recommend sunstrider to implement the same/similar system as was on excalibur wow, where players could type an in game command (.xp 2 for example), and there were no issues when using this system.

**Comment by z5n** [comment]
related: SunstriderEmu/BugTracker/issues/4995

**Comment by z5n** [comment]
duplicate
