### ISSUE TITLE
Blackrock Depths Ring of law

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#5155]
Ring of law event does not work properly.
High justice grimstone begins the event and spawns the first npcs. After killing 2 out of 3 of the worms, the event suddenly is reset and grimstone repeats the same script, then all the doors are shut and the player is stuck inside the ring of law unable to get out.

**Comment by kelno** [comment]
Thanks, we'll look into it

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, it's been fixed since.
