### ISSUE TITLE
Quest Red Snapped - Very tasty!

### ISSUE THREAD

**Issue by dole555** [ValorenWoW/sunstrider-core#5157]
**Describe the bug**
There are some "School of red snapper" in which if you use the "Draenei fishing net" the splash animation shows up a few meters above the water, and you get no fish credit for the quest, and the fish school doesn't dissapear. If you  use the net underwater, at just the right spot, it works. But some schools are in shallow water and that can't be done.

**Character name**
Character on which the issue occurred, if applicable.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 

Quest: https://wowhead.com?quest=9452/red-snapper-very-tasty

**Expected behavior**

**Additional context**
![image](https://user-images.githubusercontent.com/80955822/158027660-7e6701d4-dc4f-403b-a99a-85d074da42ef.png)

**Comment by kelno** [comment]
Thanks. It seems to work most of the time, even by just retrying the same fishes from the same position, but I can see the bug happening sometimes.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
