### ISSUE TITLE
The Bough of the Eternals not completing

### ISSUE THREAD

**Issue by z5n** [ValorenWoW/sunstrider-core#5160]
**Describe the bug**
The Bough of the Eternals doesn't complete after summoning the orphan near the bank.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Get and turn in quest [Children's Week](https://tbc-twinhead.twinstar.cz/?quest=1468)
2. Get quest [The Bough of the Eternals](https://tbc-twinhead.twinstar.cz/?quest=1479)
3. Go to the bank in Darnassus
4. Use [Human Orphan Whistle](https://tbc-twinhead.twinstar.cz/?item=18598)

**Expected behavior**
The quest should be marked as complete when the orphan is summoned.

**Comment by Jerrythemagicdog** [comment]
fixed with next update 0d313a4b0f1b58688a5cb7ceb005445fa01ef890
