### ISSUE TITLE
Warlock Pet stops fighting on character level

### ISSUE THREAD

**Issue by bmcdougald** [ValorenWoW/sunstrider-core#5164]
**Describe the bug**
New Warlock so only have the imp currently.  But when I level, the imp just stops fighting.  You cannot make him fight again without dismissing him and re-summoning him.  This can be less than ideal if you're fighting mobs at the time and need him to actually participate.  Switching from passive to defensive/agro doesn't encourage him to fight, nor does cycling his abilities on and off.

**Character name**
Morgrim

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Warlock with Imp out
2.  Fight monsters
3.  Level your character
4.  Attempt to continue fighting  
5.  Observed Behavior - Imp daydreams and lets you die.  

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
Expected Behavior - Imp continues to participate as intended.

**Additional context**

**Comment by kelno** [comment]
Thanks for reporting. I couldn't reproduce this for now with the given steps. 
In your step 4, did you attemps to command the pet to attack again or did you rely on defensive/aggressive pet state?

**Comment by bmcdougald** [comment]
I did try commanding it to attack as well with no luck.  Since then I have gotten the void walker.  It displays similar behavior but only rarely compared to the imp.
