### ISSUE TITLE
Energy regeneration rate / ticks

### ISSUE THREAD

**Issue by Tishyrogue** [ValorenWoW/sunstrider-core#5168]
**Describe the bug**

The energy regeneration rate / energy ticks are not quite correct. The ticks are always 20 energy, but actually every third energy tick should be 21 energy.

**Character name**

Tishy

**To Reproduce**

1. Check the energy regeneration rate of rogues, it's always +20 instead of (+20, +20, +21, +20, +20, +21, ...)
 

Spell: https://www.wowhead.com/tbc/resource/energy-3

**Expected behavior**

**Screenshots/videos**

Source: https://us.forums.blizzard.com/en/wow/t/rogue-energy-regeneration/475996
Source 2: 15 years of rogue gameplay experience
Source 3: https://www.youtube.com/watch?v=rVuXGew81l8 (Check the first sequence. After Shadowstep and Garrote, the energy jumps from 60 to 81. (Note the second 13 of the clip).)

**Comment by ghost** [comment]
"The rate at which pet focus regenerates is not always consistent.
Note: While the actual amount of focus that can be generated per tick is inconsistent, the total amount generated over time is flat and consistent. There are slight variations in the time between ticks that cause this to display inconsistently."

You could also get a +19 tick.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue and the research, we won't be implementing this though.
