### ISSUE TITLE
Unexpected XP while level up

### ISSUE THREAD

**Issue by Soonkz** [ValorenWoW/sunstrider-core#5170]
**Describe the bug**

I am leveling with a friend - he dinged level 10 and instantly dinged 15 again - i dont know if why he got so much xp - now the gap is 5 level between us.

**Character name**

Warlock: Dayzdots
Shaman: Nocabz

**To Reproduce**

1. Play Shaman - Ding level 10
2. Instant level 15 with so much xp

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
