### ISSUE TITLE
[Spell][Hunter] Revive Pet doesn't not ressurect dead pet if his body disappears

### ISSUE THREAD

**Issue by Gornaut** [ValorenWoW/sunstrider-core#5176]
**Describe the bug**
Description:
Currently if pet dies once his icon is visible you can simply resurrect him with Revive Pet which is correct.
However, if you run away from dead pet's body so that it disappears, you can no longer resurrect it until you use Call Pet first and revive pet after.
Getting "You do not have a pet message".

**Character name**
Kalahat

**To Reproduce**

1. Kill your pet as a Hunter;
2. Then ran out of the range of your pet's dead body, so it disappears;
3. Now try to ressurect the pet and you won't be able to getting an error message.

**Expected behavior**
Pet should be ressurectable with Revive Pet when his dead body disappears. On top of that when you try to call your dead pet, his body should not appear and instead you should get an error message. 

Here is a video proof of Dysporia reviving his dead pet, after Pet's body disappeared, successfully without using Call Pet first.
[Hunter Vs World 6 - Solo Durnholde Heroic](https://www.warcraftmovies.com/movieview.php?id=36806) by dysphoria
5:55 - 6:02
6:36 - 6:46
8:10 - 8:29
https://www.youtube.com/watch?v=jOJefvLb8Ok

Same behaviour observed in classic TBC as well.

**Comment by z5n** [comment]
related:
#2631
#2490

**Comment by kelno** [comment]
Thanks for reporting! Fixed with next server update
