### ISSUE TITLE
Hunter Pet Rename

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#5177]
Pet Rename is not working.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
That's intentional because players used rename to confuse AddOns like Gladius with renaming their pet to the same name as one of their teammates, bugging out the AddOn.
We're planning to keep it that way for the foreseeable future.

**Comment by ghost** [comment]
@Jerrythemagicdog This could lead to other issues like healers not being able to see all pets on raid frames because of identical pet names.

**Comment by Jerrythemagicdog** [comment]
We haven't seen that happen on our previous realms when we already had this in place.
That's a valid concern though, thanks, we'll act if we see it becomes an issue.

**Comment by Jerrythemagicdog** [comment]
Seems like I misremembered and didn't check when closing the issue, the pet is automatically renamed when entering arena to the base pet name, renames will now be correctly possible, sorry!
