### ISSUE TITLE
Shaman Talent points

### ISSUE THREAD

**Issue by TP-Caitlin** [ValorenWoW/sunstrider-core#5181]
**Describe the bug**
On shaman when you choose to get a new set of gear from the NPC "Camp Manager", it will wipe about half of your talent points but give you a full refresh of 61. The bug is wiped if you relog.

**Character name**
Caitlin

**To Reproduce**

1. Spend talent points as usual
2.  Talk to NPC Camp Manager request a new set of gear.
3. Spend extra 61 talent points.
4. 

Camp Manager

**Expected behavior**
When you select a new set of gear, all talents should be wiped 

**Screenshots/videos**
https://imgur.com/a/QggsSDV

**Additional context**
Only tested on Shaman and using Resto. gear request from NPC

**Comment by Jerrythemagicdog** [comment]
Thanks, the issue has been resolved since then.
