### ISSUE TITLE
[Druid] Wrath of elune procs when spell hits instead of succesfull spell cast

### ISSUE THREAD

**Issue by Aeded** [ValorenWoW/sunstrider-core#5182]
**Describe the bug**
Wrath of elune procs when wrath reaches target, instead of immidiately after spellcast

**Character name**

**To Reproduce**
https://streamable.com/1hwvoc

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=46833

**Expected behavior**

https://youtu.be/H_Lev05chmc?t=409

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
