### ISSUE TITLE
[Shaman] Grounding totem

### ISSUE THREAD

**Issue by Aeded** [ValorenWoW/sunstrider-core#5184]
**Describe the bug**
When you are grounding a cast, that consists of cast with no travel time+instant, you should be able to ground both spells. Currently only 1 spell is grounded.
For instance: Mindblast+swd, or Arcane blast+fireblast or starfire+moonfire etc.

**Character name**

**To Reproduce**

https://streamable.com/nvmqfi

**Expected behavior**
https://streamable.com/j2lb5r
should ground both (TBCC)

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
