### ISSUE TITLE
[Shaman] Fire/Earth Elemental Totems dont despawn when elemental is killed

### ISSUE THREAD

**Issue by Aeded** [ValorenWoW/sunstrider-core#5185]
**Describe the bug**

Killing elemental does not despawn totem

**Character name**

**To Reproduce**

1. Use Fire elemental totem
2. Kill Fire Elemental
3. Observe Fire Elemental Totem alive, with no elemental

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
If totem is killed, elemental should despawn (works). If Elemental itself is killed, Elemental Totem should despawn (doesnt work)

**Screenshots/videos**
https://youtu.be/_u0a6TUljyU?t=112
You can see when Fire elemental dies, totem next to it disappears

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
