### ISSUE TITLE
[Shaman] Fire elemental totem

### ISSUE THREAD

**Issue by Aeded** [ValorenWoW/sunstrider-core#5186]
**Describe the bug**
1. Fire elemental is missing fire blast and fire nova spells
2. Fire elemental doesnt seem to be scaling with shaman´s spell demage
3. Fire elemental doesnt have mana pool, and HP isnt scaling with shaman´s stamina
4. Fire elemental moves at normal speed
5. Fire elemental immolation aura is not supposed to scale with spell demage at all (now does at 100%)

**Character name**

**To Reproduce**

1. use fire elemental totem
2. observe

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

1. Fire elemental should use Fire blast and Fire nova spells
https://youtu.be/pQ7dPZtMX3o?t=5 (uses fire nova into fire blast)

2. Fire elemental should be scaling with spell demage
https://youtu.be/gaIE367SROY?t=428 enhance sham, fire ele auto attacks are around 200
https://youtu.be/_u0a6TUljyU?t=387 ele shaman, fire ele auto attacks are around 580

3. Fire elemental should have manapool, It should be scaled off shaman´s intelect
eu.battle.net/wow/en/game/patch-notes/2-1-0

"Fire Elemental Totem: This pet will now come into the game with full health and mana, including that gained from a percentage of its master’s stamina and intellect. It will also now properly get increased stamina from a percentage of its master’s stamina."

4. http://wowwiki.wikia.com/wiki/Fire_Elemental_Totem?oldid=1563567 "Elementals move surprisingly fast" 
https://youtu.be/pQ7dPZtMX3o?t=15s (watch elemental speed when he runs in fear)

5. Fire ele immolation aura should not be scaling with spell dmg
https://youtu.be/pQ7dPZtMX3o?t=9 hits for 95 on some dog geared ele
https://youtu.be/_u0a6TUljyU?t=1391 hits 95 on swp ele

**Screenshots/videos**

Clips with fire elemental:
https://youtu.be/pQ7dPZtMX3o
https://youtu.be/_u0a6TUljyU?t=1288
https://youtu.be/_u0a6TUljyU?t=1723
https://youtu.be/_u0a6TUljyU?t=41
https://youtu.be/_u0a6TUljyU?t=341
https://youtu.be/lOHOp-s6__g?t=644
**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
