### ISSUE TITLE
Hunter, autoshot

### ISSUE THREAD

**Issue by disis24** [ValorenWoW/sunstrider-core#5190]
There is a problem with /cast !Auto Shot

spam /cast !Auto Shot on a dummy (do it with a macro) -> Jump, move, or press echap etc.. > Disconnected

**Comment by fitqt** [comment]
Jumping/moving doesn't really matter, it seems its amount of calls that causes the dc. If you fill all 255 chars like this...
```/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
/cast !Auto Shot
```
...u will crash instantly after a single button press.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we are working on a fix.

**Comment by Jerrythemagicdog** [comment]
A fix has been pushed to the Endless Launcher fixing this issue. 
Make sure to start the game through the Endless Launcher when trying the fix.
