### ISSUE TITLE
Stranglethorn - Zanzil Zombie

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5194]
**Describe the bug**
Zanzil Zombies have bugged speed, moving extremely slow, therefore kiteable / ready for abuse

**Character name**
Bonja

**To Reproduce**

https://www.wowhead.com/classic/de/npc=1488/zombie-von-zanzil
https://www.wowhead.com/classic/de/quest=621/zanzils-geheimnis

**Expected behavior**
Mob moving at normal speed

**Screenshots/videos**
https://www.twitch.tv/videos/1887453721

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
