### ISSUE TITLE
Stranglethorn - Elder Shadowmaw Panther

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5195]
**Describe the bug**
Elder Shadowmaw Panthers don't adjust speed after breaking stealth and stay at stealthed speed while aggroed.

**Character name**
Bonja

**To Reproduce**
Pull mob, kite.

https://www.wowhead.com/classic/de/npc=1713/alter-schattentatzenpanther

**Expected behavior**
Mob moving at normal speed after breaking speed.

**Screenshots/videos**
https://www.twitch.tv/videos/1887453721 - starting at 25:10

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
