### ISSUE TITLE
Stranglethorn - Carefully Folded Note

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5196]
**Describe the bug**
~~#1 - Bottles times misplaced, either sitting in the water or only the tiniest bit of the bottleneck sticking out of the sand.~~
#2 - Loot table of the bottles is completely screwed. Should at best yield some scrolls for buffs - comes with raptor hides, medium and heavy leather.

**Character name**
Bonja

**To Reproduce**
Loot bottle

https://www.wowhead.com/classic/item=4098/carefully-folded-note
https://www.wowhead.com/classic/quest=594/message-in-a-bottle

**Expected behavior**
Gimme the Q item
**Screenshots/videos**
https://www.twitch.tv/videos/1887453721 - starting 02:45:40

**Comment by z5n** [comment]
first one fixed with next restart

**Comment by z5n** [comment]
thanks for the report, second issue fixed with next restart
