### ISSUE TITLE
World (1-60) - rare mobs

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5197]
**Describe the bug**
Nodrops all over the place

**Character name**
Bonja

**To Reproduce**
Kill rare mob, get sadge.

Alterac Mountains
Araga, Cranky Benj, Gravis Slipknot, Jimmy the Bleeder, Lo'Grosh, Narillasanz†, Skhowl, Stone Fury

Arathi Highlands
Darbel Montrose†, Foulbelly†, Geomancer Flintdagger, Kovork, Molok the Crusher, Nimar the Slayer, Prince Nazjak, Ruul Onestone†, Singer, Zalas Witherbark

Ashenvale
Akkrilus, Apothecary Falthis, Branch Snapper, Darkslayer Mordenthal, Eck'alom, Lady Vespia, Mist Howler, Mugglefin, Oakpaw, Prince Raze, Rorgish Jowl, Terrowulf Packlord, Ursol'lok

Azshara
Antilos, Gatekeeper Rageroar, General Fangferror, Lady Sesspira, Magister Hawkhelm, Master Feardred, Monnos the Elder†, Scalebeard†, The Evalcharr, Varo'then's Ghost

Badlands
7:XT, Anathemus†, Barnabus, Broken Tooth, Rumbler, Shadowforge Commander, Siege Golem†, War Golem, Zaricotl†

Blackrock Mountain
Scarshield Quartermaster†, The Behemoth†

Blasted Lands
Akubar the Seer, Clack the Reaver, Deatheye, Dreadscorn, Grunter, Magronos the Unyielding, Mojo the Twisted, Ravage, Spiteflayer

Burning Steppes
Deathmaw, Gorgon'och, Gruklash, Hahk'Zor, Hematos†, Malfunctioning Reaver, Terrorspark, Thauris Balgarr, Volchan†

Darkshore
Carnivous the Breaker, Firecaller Radison, Flagglemurk the Cruel, Lady Moongazer, Lady Vespira, Licillin, Lord Sinslayer, Shadowclaw, Strider Clutchmother

Desolace
Accursed Slitherblade, Crusty, Giggler, Hissperak, Kaskk, Prince Kellen

Dun Morogh
Bjarn, Edan the Howler, Gibblewilt, Great Father Arctikus, Hammerspine, Timber

Durotar
Captain Flat Tusk†, Death Flayer, Felweaver Scornn, Geolord Mottle, Warlord Kolkanis, Watch Commander Zalaphil

Duskwood
Commander Felstrom, Fenros, Lord Malathrom, Lupos, Marina DeSirrus, Naraxis, Nefaru, The Unknown Soldier

Dustwallow Marsh
Brimgore†, Burgle Eye, Darkmist Widow, Dart, Drogoth the Roamer, Hayoc, Lord Angler, Oozeworm, Ripscale, The Rot

Eastern Plaguelands
Deathspeaker Selendre, Duggan Wildhammer, Gish the Unmoving, Hed'mush the Rotting, High General Abbendis†, Lord Darkscythe, Nerubian Overseer†, Ranger Lord Hawkspear, Warlord Thresh'jin, Zul'Brin Warpbranch

Elwynn Forest
Gug Fatcandle, Fedfennel, Gruff Swiftbite, Morgaine the Sly, Mother Fang, Narg the Taskmaster, Thuros Lightfingers

Felwood
Alshirr Banebreath, Death Howl, Dessecus†, Immolatus†, Mongress, Olm the Wise, Ragepaw, The Ongar , Spinecrawl

Feralas
Antilus the Soarer, Arash-ethis, Bloodroar the Stalker, Diamond Head, Gnarl Leafbrother, Lady Szallah, Old Grizzlegut, Qirot, Snarler

Hillsbrad Foothills
Big Samras, Creepthess, Lady Zephris, Ro'Bark, Scargil, Tamra Stormpike†

Loch Modan
Morick Darkbrew, Boss Galgosh, Emogg the Crusher†, Grizlak, Gosh-Haldir, Large Loch Crocolisk, Lord Condar, Magosh, Shanda the Spinner

Mulgore
Enforcer Emilgund, Ghost Howl, Mazzranache, Sister Hatelash, Snagglespear, The Rake

Redridge Mountains
Boulderheart, Chatter, Kazon, Ribchaser, Rohh the Silent, Seeker Aqualon, Snarlflare, Squiddic

Searing Gorge
Faulty War Golem, Highlord Mastrogonde†, Rekk'tilac, Scald, Shleipnarr, Slave Master Blackheart, Smoldar

Silithus
Gretheer, Grubthor, Huricanian, Krellack, Lapress†, Rex Ashil†, Setis†, Twilight Lord Everun, Zora†

Silverpine Forest
Dalaran Spellscribe, Gorefang, Krethis Shadowspinner, Old Vicejaw, Ravenclaw Regent, Rot Hide Bruiser, Snarlmane

Stonetalon Mountains
Brother Ravenoak†, Foreman Rigger†, Nal'taszar†, Pridewing Patriarch, Sentinel Amarassan†, Sister Riven†, Sorrow Wing†, Taskmaster Whipfang†, Vengeful Ancient

Stormwind City
Sewer Beast

Stranglethorn Vale
Gluggle, High Priestess Hai'watna†, Kurmokk, Lord Sakrasis, Mosh'Ogg Butcher†, Rippa, Roloch, Scale Belly, Verifonix

Swamp of Sorrows
Fingat, Gilmorian, Lord Captain Wyrmak†, Lost One Chieftain, Lost One Cook, Molt Thorn

Tanaris
Cyclok the Mad, Greater Firebird, Haarka the Ravenous, Jin'Zallah the Sandbringer†, Kregg Keelhaul, Murderous Blisterpaw, Omgorn the Lost, Soriid the Devourer, Warleader Krazzilak†

Teldrassil
Blackmoss the Fetid, Duskstalker, Fury Shelda, Grimmaw, Threggil, Uruson

The Barrens
Aean Swiftriver†, Ambassador Bloodrage†, Azzere the Skyblade, Brokespear, Brontus†, Captain Gerogg Hammertoe†, Digger Flameforge, Dishu, Elder Mystic Razorsnout†, Engineer Whirleygig, Foreman Grills, Geopriest Gukk'rok, Gesharahan†, Hagg Taurenbane†, Hannah Bladeleaf†, Heggin Stonewhisker, Humar the Pridelord†, Malgin Barleybrew, Marcus Bel†, Rathorian, Rocklance†, Silithid Harvester, Sister Rathtalon†, Sludge Beast, Snort the Heckler, Stonearm, Swiftmane†, Swinegart Spearhide†, Takk the Leaper†, Thora Feathermoon†, Thunderstomp

The Hinterlands
Grimungous†, Ironback, Jalinde Summerdrake, Mith'rethis the Enchanter†, Old Cliff Jumper, Razortalon, Retherokk the Berserker, The Reak, Witherheart the Stalker, Zul'arek Hatefowler

Thousand Needles
Achellios the Banished†, Gibblesnik, Harb Foulmountain, Heartrazor†, Ironeye the Invincible†, Silithid Ravager, Vile Sting†

Tirisfal Glades
Bayne, Deeb, Farmer Solliden, Fellicent's Shade, Lost Soul, Muad, Ressan the Needler, Sri'skulk, Tormented Spirit

Un'Goro Crater
Clutchmother Zavas, Gruff†, King Mosh†, Ravasaur Matriarch, Uhk'loc

Western Plaguelands
Foreman Jerris†, Foreman Marcrid, Foulmane, Lord Maldazzar, Putridius, Scarlet Executioner†, Scarlet High Clerist†, Scarlet Interrogator†, Scarlet Judge†, Scarlet Smith†, The Husk

Westfall
Brack, Foe Reaper 4000, Leprithus, Master Digger, Sergeant Brashclaw, Slark, Vultros

Wetlands
Dragonmaw Battlemaster, Garneg Charskull, Gnawbone, Leech Widow, Ma'ruk Wyrmscale, Mirelow, Razormaw Matriarch, Sludginn

Winterspring
Azurous†, General Colbatann†, Grizzle Snowpaw, Kashoch the Reaver†, Lady Hederine†, Mezzir the Howler, Rak'shiri, Norissis, Bornak the Gorer, The Deep Tunneler, Manas, Bruiser

**Expected behavior**
Giev loot?

**Screenshots/videos**
https://www.twitch.tv/videos/1887453721 - 03:20:00 i.E.

**Additional context**
Rares don't give any loot (rnd greens i.E.)

Only mobs unaffected are the 11 rares that have a guaranteed loot table i.E. Scale belly with the resist pants / chromatic sword or Ironeye with the basilisk blade.

All other rare mobs with random loot tables are nodrops

**Comment by z5n** [comment]
big thanks for the info!

**Comment by Sattva-108** [comment]
Yeah it's very sad actually, i can confirm that most of Darkshore rare mobs - do not drop anything worthy.

I'm Cata enjoyer actually, there every rare mob - drops something everywhere in Azeroth, just like TBC, WoTLK content.
 And they also give improved experience (this would be a suggestion for future, not a bug)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue and the sources!
We've changed every Vanilla rare loot template, the changes will go live in the next few days.
