### ISSUE TITLE
Hellfire Peninsula - Fel Reaver

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5198]
**Describe the bug**
Fel Reaver's skills are a mess.

**Character name**
Bonja

**To Reproduce**
Pull the boie

https://www.wowhead.com/tbc/npc=18733/fel-reaver
Uses wrong abilities:
https://www.wowhead.com/tbc/spell=35056/glob-of-machine-fluid
https://www.wowhead.com/tbc/spell=29956/arcane-missiles

**Expected behavior**
Use stomp
**Screenshots/videos**
![felreaver](https://github.com/SunstriderEmu/BugTracker/assets/141223500/26986180-ac66-4f3c-a1b2-38bbf663ba59)

**Comment by blblblaz** [comment]
thanks for the report, fixed with next update
