### ISSUE TITLE
Hellfire Peninsula - Starving Hellboar

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5199]
**Describe the bug**
Hellboars using charge (shouldn't)

**Character name**
Bonja

**To Reproduce**
Pull mob, get charged

https://www.wowhead.com/tbc/npc=16879/starving-helboar

**Expected behavior**
Approach me slowly

**Comment by blblblaz** [comment]
thanks, fixed with next server update
