### ISSUE TITLE
Can't learn skill through gm command

### ISSUE THREAD

**Issue by PadreWoW** [ValorenWoW/sunstrider-core#52]
**Description:**

I taught my priest plate mail and the item no longer appers as red, however I cannot equip it as it says I don't have the right proficiency but the item isn't in red nor is the proficiency. Same goes for weapons(ie: a class that cannot learn 2h sword still cannot wield it after being taught spell 202 with gm commands). How do I fix this because in earlier versions I could equip anything through cheats(ie: mage wearing wail armor by teaching it spell id 8737)

Also if I learn for instance a weapon skill I normally can't use two times I don't get the "already learned spell message"

**Current behaviour:**

https://github.com/TrinityCore/TrinityCore/issues/13290

**Comment by PadreWoW** [comment]
I know that Priest should not learn Mail, Plate etc, but GMs should be able to learn ALL I think

**Comment by Nolin7777** [comment]
Did u even read the comments?

**Comment by PadreWoW** [comment]
Did you even read MY LAST comment?

**Comment by PadreWoW** [comment]
> 
> 
> I know that Priest should not learn Mail, Plate etc, but GMs should be able to learn ALL I think

**Comment by kelno** [comment]
Could be that the core enforce the skill per class even for gm players but we won't fix it if this doesn't affect players.
