### ISSUE TITLE
[Quest] Load Lightening - low pop quest mobs

### ISSUE THREAD

**Issue by QuadrozZz** [ValorenWoW/sunstrider-core#5201]
Low population https://www.wowhead.com/classic/npc=4154 for quest https://www.wowhead.com/classic/quest=1176
Most populatated spot have just 3 mobs at once, but should have 6-8.
OBT https://imgur.com/0LWphrR
Classic 2019y https://www.wowhead.com/classic/quest=1176/load-lightening#videos:id=170313 start from 0:30

also mb somewhere else they're missing, but i can't log on Classic rn.

**Comment by z5n** [comment]
thanks, fixed with next restart!
