### ISSUE TITLE
Petautocaston macro

### ISSUE THREAD

**Issue by disis24** [ValorenWoW/sunstrider-core#5202]
/petautocaston and /petautocastoff doesnt work (only with "Dive" ability).

Cant drag off pet's abilities from the bar.

Also can you replace the autocast animation on pet's bar by the TBC one ?

Tbc :
https://pasteboard.co/k26YzKOOErBP.png

Wotlk :
https://pasteboard.co/2hQ4TvoytO3b.png

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The macro works, as long as you specify the rank, for example: `/petautocaston Scorpid Poison(Rank 5)`
