### ISSUE TITLE
Zangarmarsh - pathing in water

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5205]
**Describe the bug**
Pathing in water is completely effed.

**Character name**
Bonja
**To Reproduce**
Pull mob - strider / boglash and mob goes on evade, except when you get into melee range.

https://www.wowhead.com/tbc/npc=18281/boglash
https://www.wowhead.com/tbc/quest=9895/the-dying-balance

**Expected behavior**
Mobs not going on evade, even in puddles, where the player can stand and is not swimming.

**Screenshots/videos**
https://www.twitch.tv/videos/1888910197 02:44:00

**Additional context**
Doesn't only apply to zangarmarsh - same for example in wetlands at the undead crew members - mobs will bug out, evade and reset. For a workaround in wetlands, mobs don't go on evade if you hit the bottom of the ocean - but that's kinda difficult in zangarmarsh, where the player is standing in a puddle and not swimming.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.

**Comment by Jerrythemagicdog** [comment]
Zangarmarsh shallow water case is not fixed yet, will update this issue.

**Comment by Fizzle-Bonja** [comment]
> Zangarmarsh shallow water case is not fixed yet, will update this issue.

Mobs behave the same for example in SMV Diemetradons in the lava - or water elementals in the shallow puddles.

I smell big fun on a main quest line area with 7 mobs in total - that go on evade as they kick you out of melee range with stormbolt :D

**Comment by Jerrythemagicdog** [comment]
Thanks for the update, we're looking into it!

**Comment by QuadrozZz** [comment]
Today i has that problem in Dustwallow marsh.
Idk fixes have been applied.

**Comment by Jerrythemagicdog** [comment]
The fixes have been applied now.
