### ISSUE TITLE
[User Interface] - Chat settings LUA error.

### ISSUE THREAD

**Issue by Sattva-108** [ValorenWoW/sunstrider-core#5206]
**Describe the bug**
Chat Settings messed up, two lines are empty, causing LUA error. 
Also on the bottom left something is wrong, overlapping.

**Character name**
Sattva

**To Reproduce**
1. Reload UI.
2. Right click **General** tab.
3. Click settings.
4. And this is where the error comes up.

**Expected behavior**
Lines shouldn't be empty, should be no overlapping in the bottom left corner.
And should be no lua error. 

**Screenshots/videos**
![Wow_yx1HfQnw8K](https://github.com/SunstriderEmu/BugTracker/assets/74269253/07469c1b-e4b2-4b94-8bfc-de68e1bbc109)

**Additional context, Lua error:**

```lua
1x Interface\FrameXML\FloatingChatFrame.lua:926: bad argument #1 to 'strsub' (string expected, got nil):
Interface\FrameXML\FloatingChatFrame.lua:926: in function `FCF_StripChatMsg':
Interface\FrameXML\ChatConfigFrame.lua:1440: in function `GetMessageTypeColor':
Interface\FrameXML\ChatConfigFrame.lua:957: in function `ChatConfig_UpdateCheckboxes':
<string>:"*:OnShow":1: in function <[string "*:OnShow"]:1>
<in C code>: in function `Show'
Interface\FrameXML\ChatConfigFrame.lua:1486: in function `ChatConfigCategory_OnClick':
<string>:"*:OnShow":10: in function <[string "*:OnShow"]:1>
<in C code>: in function `Show'
Interface\FrameXML\UIParent.lua:1580: in function `SetUIPanel':
Interface\FrameXML\UIParent.lua:1385: in function `ShowUIPanel':
Interface\FrameXML\UIParent.lua:1311: in function <Interface\FrameXML\UIParent.lua:1307>:
<in C code>: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:1974: in function `ShowUIPanel':
Interface\FrameXML\FloatingChatFrame.lua:346: in function `func':
Interface\FrameXML\UIDropDownMenu.lua:583: in function `UIDropDownMenuButton_OnClick':
<string>:"*:OnClick":1: in function <[string "*:OnClick"]:1>

Locals:
string = nil

  ---
  ```

**Comment by Sattva-108** [comment]
So things that are missing there are:
**Guild announce** and **Achievement announce.**
Just checked on normal 3.3.5 client:

![wow_JJCHq7Thjb](https://github.com/SunstriderEmu/BugTracker/assets/74269253/71b42bdf-9859-4567-95c4-05fef7901d1d)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
