### ISSUE TITLE
Summon Imp unavaible at level 1 and auto learned Imp knows no spell

### ISSUE THREAD

**Issue by panplume** [ValorenWoW/sunstrider-core#5207]
Imp pet auto learn on leveling doesn't know his basic spell: Firebolt (https://www.wowhead.com/tbc/spell=3110/firebolt).

Not having Summon Imp at character creation isn't an issue, reporting for the sack of completeness (may lead to more unpolished character/pet creation template).

**To Reproduce**
1. Create a warlock (no Summon Imp spell available)
2. Level up to auto learn Summon Imp (https://www.wowhead.com/tbc/spell=688/summon-imp)
3. Summon Imp
4. Imp knows no spell

**Expected behavior**
1. Imp should have the spell Firebolt (rank 1) baseline
2. Summon Imp should be available at level 1 (level 1 class quests:  https://www.wowhead.com/tbc/spell=688/summon-imp#reward-from-q)

**Comment by panplume** [comment]
Same thing with Summon Voidwalker, he has no spell.

Workaround: logout/login/summon (gone from logout), he has his taunt ability

**Comment by kelno** [comment]
Thanks for reporting.
At the moment the pets do learn the skills on the next resummon.

**Comment by kelno** [comment]
Fixed with next server update
