### ISSUE TITLE
SMV - Niobe Whizzlespark

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5208]
**Describe the bug**
Alliance Master Engineering trainer Niobe Whizzlespark is neutral and can be attacked as alliance.

**Character name**
Bonja

**To Reproduce**
Engage NPC with any spell / attack

https://www.wowhead.com/tbc/npc=24868/niobe-whizzlespark

**Expected behavior**
Teach me senpai.

**Screenshots/videos**
https://www.twitch.tv/videos/1888910197 - 07:40:25

**Comment by z5n** [comment]
thanks, fixed with next restart
