### ISSUE TITLE
TBC - Rare spawns

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5209]
**Describe the bug**
Somethings fishy with tbc rare spawns.

**Character name**
Bonja

**To Reproduce**

Blade's Edge Mountains	Hemathion, Morcrush (elite), Speaker Mar'grom

Hellfire Peninsula	Fulgorge (elite), Mekthorg the Wild (elite), Vorakem Doomspeaker

Nagrand	Bro'Gaz the Clanless, Goretooth, Voidhunter Yar

Netherstorm	Chief Engineer Lorthander, Ever-Core the Punisher, Nuramoc

Shadowmoon Valley	Ambassador Jerrikar, Collidus the Warp-Watcher (elite), Kraator (elite)

Terokkar Forest	Crippler, Doomsayer Jurim, Okrek

Zangarmarsh	Bog Lurker, Coilfang Emissary, Marticar (elite)

**Expected behavior**
be up

**Screenshots/videos**

**Additional context**
Seen, killed, loot table working:
Shadowmoon Valley: Collidus the Warp-Watcher, Kraator
Terokkar Forest: Crippler
Netherstorm: Ever-Core the Punisher, Nuramoc

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the pooling system responsible for spawning these creatures is currently disabled on the test realm.
