### ISSUE TITLE
World - Missing herb/mining nodes

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5210]
**Describe the bug**
Classic+tbc - all mining and herb nodes are missing

**Character name**
Bonja

**To Reproduce**
Go merryround on horse, get sadge

;tldr

**Expected behavior**
Have shiny things and smelly things in nature.

**Screenshots/videos**
-

**Additional context**
-

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the pooling system responsible for spawning these objects is currently disabled on the test realm.
