### ISSUE TITLE
World - Treasure chests

### ISSUE THREAD

**Issue by Fizzle-Bonja** [ValorenWoW/sunstrider-core#5211]
**Describe the bug**
TBC fel iron lockboxes seem to be up (at least the locations I checked)
Classic treasure chests seem to be missing completely, apart from a few scattered in starting areas for some reason.

**Character name**
Bonja

**To Reproduce**
Go into world with map, get sadge.

https://www.warcrafttavern.com/wow-classic/guides/chest-locations/

**Expected behavior**
Have abandoned stuff

**Screenshots/videos**
-

**Additional context**
-

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the pooling system responsible for spawning these objects is currently disabled on the test realm.
