### ISSUE TITLE
Layering at the River to Barrens - crocodile spawn and despawn

### ISSUE THREAD

**Issue by Soonkz** [ValorenWoW/sunstrider-core#5212]
**Describe the bug**

I'm doing the quest "Lost but not forgotten" and I don't see the NPCs until I enter the water and start "layering". Otherwise the river is very empty. Also, the crocodiles do not leave the water, I think the correct behavior is also that they go on land (some are also on land).

**Character name**

Dayzroute

**To Reproduce**

1. Stay on the left river side
2. No Crocodiles here
3. Jump into water
4. Layering starts
5. new crocodiles spawn
6. jump back again to the land
7. crococdiles disappear

**Screenshots/videos**
no croc
![image](https://github.com/SunstriderEmu/BugTracker/assets/44847104/db8d37d0-9d92-42a2-a557-0bfe6d035346)
croc
![image](https://github.com/SunstriderEmu/BugTracker/assets/44847104/57b46298-44da-44d5-951c-1787d3d90040)

**Additional context**
Its a weird behavior if you are doing this quest :) maybe the layering is intended but its not so nice for this quest here :)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The layering effect is intended, that's a performance setting we're running with, however the crocodiles will path out of the water once this issue is resolved: https://github.com/SunstriderEmu/BugTracker/issues/5205
Closing this one, thanks again for the details.
