### ISSUE TITLE
auction house not usable

### ISSUE THREAD

**Issue by Enory** [ValorenWoW/sunstrider-core#5213]
we have an error message "You cannot use auction house until you become 80" when trying to use auction house on orgrimmar.
I didn't try other cities and neutral ah.

https://www.wowhead.com/npc=9856/auctioneer-grimful
https://www.wowhead.com/npc=8673/auctioneer-thathung
https://www.wowhead.com/tbc/npc=8724/auctioneer-wabang

**Comment by kelno** [comment]
Thanks. It's disabled on purpose for now. We got an issue to fix there before enabling it.
