### ISSUE TITLE
Leaving RDF group does not tele you back to original spot you accepted RDF

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5214]
**Describe the bug**
Leaving group doesn't do anything, you still sit in the heroic ID.
**Expected behavior**
When you leave the group at the end of the dungeon, it should teleport you out and to where you accepted the queue.

**Comment by panplume** [comment]
Getting out through the dungeon portal as the same issue, you shouldn't end up at the dungeon entrance.

**Comment by z5n** [comment]
fixed with next restart, thanks!
