### ISSUE TITLE
Auchenai Crypts Issues

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5215]
**Describe the bug**
1. At the beginning of the dungeon with the packs around the coffins, the coffins force the mobs to take weird paths around the coffins. You move one inch left and they do a complete run around the coffin, and vice versa.
2. The skeletons at the end at the last boss room are not tied, I believe if you pull one of the skeletons from the group it is supposed to pull all the skeletons in that specific group and the humanoid mob in the pack.

**Comment by panplume** [comment]
Looted Fish Oil and Shiny Fish Scales which seems out of context in AC.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with next update.
Regarding Fish Oil: https://www.wowhead.com/tbc/item=17058/fish-oil#dropped-by;0+3-10-9+1
