### ISSUE TITLE
Pulling with totem won't keep player in combat (in dungeon)

### ISSUE THREAD

**Issue by panplume** [ValorenWoW/sunstrider-core#5216]
**Describe the bug**
Placing a totem in the path of mobs (tested in RDF in Auch Crypt HC) will get the totem killed, but the player gets in combat for < 1s then the patrol continue.

**To Reproduce**
0. Tested in Auch Crypt HC on the bridge before Chirac
1. Cast a stoneskin totem in the middle of the bridge with only the patrol remaining
2. Run away back to the stairs
3. Wait for the patrol to kill the totem
4. Shaman get in combat for < 1s and the patrol reset

**Expected behavior**
Getting a mob to kill a totem trigger combat for the shaman and shouldn't reset on totem death.

**Additional context**
Tested on Redridge gnolls (Redridge Mountains @17,67). Combat only reset after mob death or running away for long enough.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
This was done as an attempt to prevent some pull abuses at the time.
We've since then done work in this area and those should no longer be possible.
Fixed with next update.
