### ISSUE TITLE
RDF minimap icon disappear (may even dequeue) on reloadui

### ISSUE THREAD

**Issue by panplume** [ValorenWoW/sunstrider-core#5217]
**Describe the bug**
reloadUI() or zone loading will remove the RDF minimap icon and sometime seems to dequeue RDF.

**To Reproduce**
1. Queue RDF
2. Change zone or /script ReloadUI()
3. open RDF, the bottom button reads "Find Group" instead of "Leave Queue"
4. hit the "Find Group". Minimap icon appears sometime with "Time in Queue: <1m" (as if we just queued) sometime with more time.

**Expected behavior**
Queue should only be canceled by hitting "Leave Queue" button or being logged out for some time.
Minimap icon should be displayed after UI redraw.

**Comment by kelno** [comment]
Thanks, should be fixed with next server update
