### ISSUE TITLE
PvP objective contribution carry on after PvP flag drops

### ISSUE THREAD

**Issue by panplume** [ValorenWoW/sunstrider-core#5218]
**Describe the bug**
PvP objective contribution carry on after your character isn't flagged for PvP anymore.

**To Reproduce**
1. Enter a PvP objective without being PvP flagged (tested at Hellfire Fortifications), no contribution is added.
2.  Flag for PvP (/pvp), contribution starts
3.  Drop PvP flag (/pvp), contribution continue, wait for the PvP flag to drop
4. Contribution continue with the system warning you to flag for PvP.

**Expected behavior**
Contribution should stop as soon as you're not flag for PvP anymore.

**Comment by kelno** [comment]
Thanks, fixed with next server update
