### ISSUE TITLE
RDF shows incorrect roles missing

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5219]
**Describe the bug**
I know this from previous wotlk servers, but the RDF shows that the 5th slot dps is always missing as the last slot in the heroic. It may be you are waiting for a tank or healer but it always shows the 5th slot dps is missing.

**Expected behavior**
If tank or healer is missing, then the tank and healer icon should be greyed out when you hover over rdf.

**Comment by z5n** [comment]
fixed with next restart, thanks!
