### ISSUE TITLE
Beta RDF Issues

### ISSUE THREAD

**Issue by Jerrythemagicdog** [ValorenWoW/sunstrider-core#5223]
Merged issue gathering RDF issues on top of the other ones labeled with the RDF label.

- [x] Count while in queue always shows 1 DPS missing instead of an accurate count of missing roles.
- [x] Backfill is currently not working as intended and doesn't display the correct dungeon the players are currently in.
- [x] Completing a dungeon is missing the "Dungeon Completed!" text and correct handling (like updating the LFG status) when the dungeon ends allowing to teleport out of the dungeon back to the place the players queued from.
- [x] Completing a dungeon should clear the RDF cooldown. 
- [x] Running out of dungeon should teleport player to "queued up location".
- [x] When inside dungeon, "eye icon" on mini-map should allow players to "teleport out of dungeon" 
- [x] Related to above: players are able to teleport back to the dungeon that they just completed after leaving it.
- [x] Moving zones while in queue removes you from queue.
- [x] Queuing up for a dungeon after completing current dungeon leads to a bugged out state and spams role select.
- [x] Completing the dungeon and leaving group 1 at a time till the LFG party only has 1 player left, the last player has no way of leaving the dungeon without running back to the entrance or hearthing out.  They can not leave the group or use the eye on mini-map to teleport out. Player is stuck in a ghost party.
- [x] RDF cooldown not enforced for other party members

**Comment by kelno** [comment]
- [ ] What if two groups with saves try to queue together? We probably need to unbind one of the group.

**Comment by artieau** [comment]
Full party, partial completion of dungeon.
1 player leaves the group.

If the group re-queues then it starts new dungeon from the start, not where the current group is up to

@Jerrythemagicdog

**Comment by artieau** [comment]
Secondary issue is that sometimes new players do join the same group/dungeon.
However they get teleported to dungeon (to different ID?) and are killed.

Have to run back to their body in instance - upon zone in though its a new ID.

**Comment by Jerrythemagicdog** [comment]
Both cases above fixed with next update.

**Comment by kelno** [comment]
Some sources:
https://www.youtube.com/watch?v=cIUWlMAp-ck&t=290s

**Comment by kelno** [comment]
Lotsa fixes with next update
