### ISSUE TITLE
Shapeshift form mana gains.

### ISSUE THREAD

**Issue by elpywolf** [ValorenWoW/sunstrider-core#5224]
Mana gaines from Fel mana potion are not working on druids in shapeshift forms.
Innervate is working as intended, once you shapeshift it continues to tick and restore mana to your total mana pool
Fel mana potion's effect is similar if not the same, yet it is not working.

Autoattacks on targets affected by a paladin's Judgement of wisdom do not proc the mana restoration while in shapeshift form
It should restore mana as it does to any other attacker.

Name of the character I tested this with is - Vaereelrus

To reproduce this:
On a druid spend some of the mana pool, use Fel mana potion and shapeshift into any form.
On a druid Shapeshift in to any form and perform autoattacks on a target affected by a paladin's Judgement of wisdom.

Fel Mana Potion item ID: 31677
https://www.wowhead.com/tbc/item=31677/fel-mana-potion

The problems mentioned above are essential for Feral cats to be even viable as a dps spec at all. 
These work as intended on all high quality private severs, most recent example is Stormforge.
They also worked as I have described in TBC classic servers on Blizzard relms.
Here is a wowhead guide to feral cat's dps that mentions the mechanic as a crucial to sustaining mana while powershifting as a cat.:
https://www.wowhead.com/tbc/guide/classes/druid/feral/dps-overview-pve#strengths
Here is the important text copied from the guide in the link above ^ :
TBC more or less completely solves the mana issues which cats suffered from on longer fights in vanilla. Powershifting was one of the most mana intensive DPS/healing rotations in all of Classic, costing 479 mana every 4 seconds in vanilla with 3/3 [ Natural Shapeshifter](https://www.wowhead.com/classic/spell=16835/natural-shapeshifter). Thankfully, in TBC, the greatly expanded debuff limit allows for regular use of [ Judgement of Wisdom](https://www.wowhead.com/tbc/spell=27164/judgement-of-wisdom) in raids, which cats benefit from more than any other DPS spec due to their extremely fast 1.0 second swing timer. JoW provides an equivalent of 185 mp5 for cats, expanding their effective mana pool by 6660 on a 3 minute fight. In addition, the new [ Intensity](https://www.wowhead.com/tbc/spell=17108/intensity) talent enables spirit-based mana regeneration to continue while powershifting. Finally, the introduction of [ Fel Mana Potion](https://www.wowhead.com/tbc/item=31677/fel-mana-potion) adds a much stronger consumable which makes mana a non-issue even on longer fights. Unlike traditional mana pots, [ Fel Mana Potion](https://www.wowhead.com/tbc/item=31677/fel-mana-potion) can be popped almost immediately at the start of an encounter for maximum uptime, and it is perfectly suited for ferals since the damage/healing debuff is irrelevant.

**Comment by DMN7** [comment]
https://cdn.discordapp.com/attachments/584166216478752768/1137319000209109072/felmana3.mp4

^ was an example of fel mana potion working on shapeshift form on the stormforge tbc server

**Comment by Jerrythemagicdog** [comment]
Thanks for the report!
Showing how things work on other servers is not proof of how things should work.
When trying to determine blizzlike behavior we are interested in evidence from original TBC (for example: https://github.com/SunstriderEmu/BugTracker/issues/1816#issuecomment-581556617) or Classic TBC.

About the issue:
Innervate and Fel Mana Potion are different effects and should not be confused.
There is evidence to support JoW, Mana Spring Totem, Mana Tide Totem, and VT in the form of logs from Classic TBC, and we'll fix those issues:
https://classic.warcraftlogs.com/reports/H823796pFGzVaJmx#fight=25&type=resources&spell=100&source=36
https://classic.warcraftlogs.com/reports/bYpkf6H8rKwhR7JM#fight=14&type=resources&spell=100&source=1
https://classic.warcraftlogs.com/reports/H4Lfyvz3hpcQABmR#fight=19&type=resources&spell=100&source=16
Mana Tide: https://classic.warcraftlogs.com/reports/m8GZM47ApCYadJhK#fight=8&type=resources&source=8&spell=100
VT: https://classic.warcraftlogs.com/reports/rD97xHQLmcMpPFhA#fight=62&type=resources&source=17&spell=100
~If you can find evidence that shows Fel Mana Potion worked in shapeshifts feel free to add it here.~

**After looking at some more sources like the Feral Druid TBC Discord, we're going to fix Fel Mana Potions too. This way we stay consistent with effects like Mana Spring Totem or VT as well.**
![image](https://github.com/SunstriderEmu/BugTracker/assets/46463908/aa133808-5902-4d03-aa72-4553acee846b)
