### ISSUE TITLE
BoP dungeon items trading

### ISSUE THREAD

**Issue by weaver-0f-fate** [ValorenWoW/sunstrider-core#5225]
**Describe the bug**
1. Players are able to trade items dropped in dungeon even if they have already equipped them.
2. 2h countdown for trading an item is not expiring when character is offline.
3. Classes are not able to need on items even if it's good for them (for example I cannot need on [Black Wolf Bracers] from screenshot, being warrior tank, despite the item itself is very good for warrior tank early on.

**Character name**
Yatori

**To Reproduce**

I guess not required.

**Expected behavior**
1. Players are not able to trade BoP items from dungeons IF they have already eqiuped them.
2. 2h countdown continues even if character is offline
3. I want to be able to need on items which are good for me (even if it's not the best armor type for me).

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/45522355/92326e03-c101-45be-a01b-3907cbaeb6d1)
https://www.twitch.tv/videos/1890179624 - low level RDF testing from 04.08.

**Additional context**
Discord username for additional info if required: Weave (weave_yatori)

**Comment by DMN7** [comment]
those are not bugs. those are all normal behaviour in the 3.3.5 client and above.
#3 was introduced by blizzard to prevent ninja looting and should stay. items are tradeable anyway

i think you are thinking these are bugs because your experience on stormforge tbc.
item trading was never available on tbc 2.4.3 client, its a custom addition the devs added on their server.

**Comment by hotdogsteven** [comment]
1 - were you able to actually trade the item, or did the trade timer at the bottom simply not go away after you equipped?
2 - is correct, timer should not go down while player is offline
3 - base RDF uses need over greed, which only allows you to need roll items for your class (leather for rogues, cloth for priest)

**Comment by DMN7** [comment]
> 1 - were you able to actually trade the item, or did the trade timer at the bottom simply not go away after you equipped?

items are tradeable even if equipped in the 3.3.5 client.
even wotlk badge/pvp items from vendors are still refundable after you equip them, allowing a 2h borrow time if you change your mind.

**Comment by artieau** [comment]
All of these concerns are working as intended
