### ISSUE TITLE
Distribute Pet talent point in "Dash" does not seem to work

### ISSUE THREAD

**Issue by Soonkz** [ValorenWoW/sunstrider-core#5228]
**Describe the bug**

I wanted to distribute the first "Pet" talent point and it was in Dash - I got "see screenshot below" the following message.
When I distributed the point in "Claw" it worked

**Character name**

Dazyhunt -  Pet (Cat)

**To Reproduce**

1. Try to distribute the first pet talent point in Dash
2. Get the following message in chat "learned a new spell: Dash(Rank 1)" - "Unlearned Dash (Rank 1)
3. Does not work but as soon as I distribute in e.g. "Claw" he accepts that

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

Would have expected that I can put the first point in Dash
Correct me if im wrong
Cheers Dayz :)

**Screenshots/videos**

![image](https://github.com/SunstriderEmu/BugTracker/assets/44847104/70c5c391-b7b2-4d6f-b6cd-0a1fc14b75e5)

**Additional context**

**Comment by Soonkz** [comment]
Ah think that is correct. Must probably be able to tamed pet in the range 32+ or higher - sorry :)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue! 
You're right, your pet is too low level - however, we should provide a better message of what's going on to not create confusion.

**Comment by Jerrythemagicdog** [comment]
With the next update, the talent tree will correctly inform you of the required level your pet has to be in order to learn the talent.
It also won't allow spending the talent point if the pet is too low level.
![image](https://github.com/SunstriderEmu/BugTracker/assets/46463908/4cc186f6-1588-4b4b-bef5-871ce67cfb25)
