### ISSUE TITLE
Potential bug with Trash spell crocks Loch Modan.

### ISSUE THREAD

**Issue by kav-pav** [ValorenWoW/sunstrider-core#5229]
Ive discussed this issue on discord. Potential bug on Trash spell crocs in Loch Modan.

4sec cd on spell based on wowhead tbc database 
https://www.wowhead.com/tbc/spell=8876/thrash

Croco hitted me 6 times in 2 sec. (looks like double proc on Trash)

Also Bestiary shows double Trash spell on croco. Screenshots bellow.
![bestiary croco](https://github.com/SunstriderEmu/BugTracker/assets/9417539/a1a156e8-6883-4e72-afbc-5a6cb7517904)
![bestiary treshadon](https://github.com/SunstriderEmu/BugTracker/assets/9417539/e858c973-31bd-47c6-bec0-f54db559cd98)
![Trash](https://github.com/SunstriderEmu/BugTracker/assets/9417539/312cad48-d7d7-4a30-9e9b-6958f69949f5)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the cooldown was wrong and will be corrected with the next update.
