### ISSUE TITLE
Hidden Gnolls in textures

### ISSUE THREAD

**Issue by kav-pav** [ValorenWoW/sunstrider-core#5230]
Found spawning gnolls in Wetlands inside textures. Ive killed this particlar one that im showing on video and it spawns again inside texture. Respawn spot is wrong in my opinion.

https://github.com/SunstriderEmu/BugTracker/assets/9417539/04f3024f-e631-453a-99d3-0a6c14134974

**Comment by blblblaz** [comment]
thanks, fixed with next server update
