### ISSUE TITLE
[Engineering][NPC][Aura] Gnomish battle chicken ; Battle Squawk

### ISSUE THREAD

**Issue by Peachusftw** [ValorenWoW/sunstrider-core#5231]
**Describe the bug**
The battle Squawk aura https://www.wowhead.com/classic/spell=23060/battle-squawk seldomly used by Gnomish battle chicken https://www.wowhead.com/classic/item=10725/gnomish-battle-chicken overwrites preexisting Squawk auras regardless of their source, should stack with other chicken's Squawks.

**To Reproduce**
1. Group two or more characters together
2. Have them use the chicken
3. Observe how squawks overwrite one another

Item: https://www.wowhead.com/classic/item=10725/gnomish-battle-chicken
Spell: https://www.wowhead.com/classic/spell=23060/battle-squawk

**Expected behavior**
Repeated Squawks originating from a single chicken should indeed overwrite each other, while Squawks from each players' chicken should stack with one another as observed in Vanilla/TBC classic era. 

**Screenshots/videos**
https://imgur.com/a/6Jw69Bb - Not a definite proof but it gets you the general idea.

**Additional context**
I'd also comment on how the squawk itself feels much less common compared to Blizzards servers but thats up to a debate. It does feel, however, that while you "should" usually (say 80% of time) get a single squawk per chicken cd, here it's closer to 40%. Chicken itself also seems to cease attacking player's target after a certain amount of time has passed since the player has used an offensive ability against said target, disregards auto attacks on that matter.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The chicken will now have a guaranteed Battle Squawk cast after 10 seconds from the time it's summoned.
It will also have a chance to proc Battle Squawk whenever it attacks, providing an opportunity to refresh Battle Squawk before it expires.

Multiple Battle Squawks will not stack.

These changes will be live with the next update.
