### ISSUE TITLE
Mage Clearcasting doesnt work as it should

### ISSUE THREAD

**Issue by kav-pav** [ValorenWoW/sunstrider-core#5232]
![clearcasting issue](https://github.com/SunstriderEmu/BugTracker/assets/9417539/53359687-9c0c-4335-88c6-32a644486eff)
It doesnt proc on blizzard initial cast. It shoudnt proc at all on ticks, but there should be same chance of getting Clearcasting while u start casting blizzard as any other spell. At least thats how it worked on classic TBC.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
https://github.com/kelno/sunstrider/commit/822186b28f1bb2da3089d066fbe66b120157e634
