### ISSUE TITLE
[AI Pathing] Escort mob is stuck. 

### ISSUE THREAD

**Issue by Sattva-108** [ValorenWoW/sunstrider-core#5238]
**Describe the bug**
Escort mob terrain pathing is bad. 

**Character name**
**Absolute**

**To Reproduce**

1. Get Quest [The Sleeper Has Awakened](https://www.wowhead.com/classic/quest=5321/the-sleeper-has-awakened)
2. Loot Horn of Awakening on the ground, and follow main road to the Ashenvale, but little bit on the right. 
3. Find cliffs to the right of the main road, at the border of Darkshore and Ashenvale.
4. Jump off the cliff, exactly where i jumped on video (pinned). - **Look Minimap.**

**Expected behavior**
Mobs should never be stuck, they should try to find way to go down. 

**Screenshots/videos**

https://github.com/SunstriderEmu/BugTracker/assets/74269253/9b145099-34ed-4568-b90f-26c146288da0

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue and the video, that's very helpful!
The movement system, (chase, formation, and follow in particular), is currently undergoing a big rework.
This issue will be resolved when those changes are merged in the next few days.
