### ISSUE TITLE
Murlocs bugging out

### ISSUE THREAD

**Issue by Rockyraccooner** [ValorenWoW/sunstrider-core#5239]
**Describe the bug**

The Murlocs in Redridge seams to be "rooted" but they will still hit you even if you are 15+ yards. 

**Character name**

Leveltestdud

https://github-production-user-asset-6210df.s3.amazonaws.com/68907804/263528849-09d5b96d-b6c3-4053-9164-1d542f96ba69.mp4

**To Reproduce**

1. Go and get melee hit by the Murlocs in the water.

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The Murlocs are incorrectly using casterAI and shooting with a missing weapon which explains why they don't want to get closer to you and don't have any animation.
Fixed with the next update.
