### ISSUE TITLE
Feral Tenders do not spawn

### ISSUE THREAD

**Issue by lilskidoo** [ValorenWoW/sunstrider-core#5240]
**Describe the bug**
On Sunstrider Isle, Feral Tenders (needed for the quest 'Aggression') do not spawn. Only the regular tenders spawn.

**Character name**
N/A

**To Reproduce**
1. Go to Sunstrider Isle (Eversong Woods 32,23).
2. Run /tar Feral - you will find none.
3. Kill some regular Tenders, no Feral Tenders will replace them.

Quest: https://wowhead.com?quest=8334
NPC: https://www.wowhead.com/tbc/npc=15294

**Expected behavior**
Feral Tenders should spawn alongside regular Tenders.

**Screenshots/videos**
N/A

**Additional context**
N/A

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
