### ISSUE TITLE
Rupture for Rogues isn't displaying improved damage

### ISSUE THREAD

**Issue by dromen48** [ValorenWoW/sunstrider-core#5242]
**Describe the bug**

Check out the screenshots, you can see the first one is with improved rupture and the second is not. I think the damage is scaling still but honestly sub could use a damage boost still. Also I think Hemo isn't working right as its not increasing all physical damage (bleeds are physical)

**Character name**

Malveron
(hey also the link to the discord is bugged I cannot sign on)
**To Reproduce**

1. Play a rogue
2. play sub rogue
3. get improved rupture (Serrated Blades)
4. You will note rank 7 stayed at 1000

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

![image](https://github.com/SunstriderEmu/BugTracker/assets/111084731/2c6ab898-36e8-4c73-88a9-454315a3792c)

![image](https://github.com/SunstriderEmu/BugTracker/assets/111084731/8d08e427-e365-41b7-a1ce-f946853849ec)

**Comment by blblblaz** [comment]
Some talents don't update your tooltip, that's normal in WoW, in this case you can see Rupture and Serrated Blades work correctly, first screenshot you do 175 Rupture damage, second screenshot you do 227. Hemo works correctly too, it is not supposed to affect bleeds.

https://wowwiki-archive.fandom.com/wiki/Rupture?oldid=1513127

"The [Hemorrhage] talent/ability will not add damage to Rupture (or any other DoT)."
