### ISSUE TITLE
[Hunter] Counterattack does not benefit from Resourcefulness

### ISSUE THREAD

**Issue by Aeded** [ValorenWoW/sunstrider-core#5244]
**Describe the bug**
Mana cost of rank4 counterattack is 110 with 0/3 resourcefulness
Mana cost of rank4 counterattack is 110 with 3/3 resourcefulness, but should be 60% cheaper

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
