### ISSUE TITLE
Talent swapping won't restore actionbars

### ISSUE THREAD

**Issue by panplume** [ValorenWoW/sunstrider-core#5246]
**Describe the bug**
Talent swapping won't restore actionbars. ReloadUI() won't change anything. Relog is needed but wasn't a few days ago. Tested with 0 addon.

**To Reproduce**
1. setup a character with 2 spec, assigning a few actionbar slots in each spec.
2. switch to the other spec, actionbar are empty. switch back, still empty.
3. reloadUI() changes nothing.
4. relog will fix it.

**Expected behavior**
a few day before, switching spec would immediately restore actionbars after the spec swapping cast ends.

**Comment by kelno** [comment]
Thanks, fixed with next server update
