### ISSUE TITLE
[Quest] Mountain Giant Muisek

### ISSUE THREAD

**Issue by panplume** [ValorenWoW/sunstrider-core#5247]
**Describe the bug**
The quest "Mountain Giant Muisek" (3127) should be doable with "Zapped Giants" (7003) to remove the "Elite" status from mobs and collect both reward at the same time (source for patch 1.7 to 2.0 in wowhead comments for both quest). Actually, shrinking a giant for Zapped Giants prevents collecting it for Muisek.

**To Reproduce**
1. Target a giant (Cliff Giant or Land Walker)
2. Use Zorbin's Ultra-Shrinker (item 18904) to remove the elite status, mob change to a "Zapped whatever" non-elite
3. Kill it (loot a Miniaturization Residue (item 18956) for the Zap quest)
4. Use Mountain Giant Muisek Vessel (item 9621), the UI reports "Invalid target"

Items:

https://www.wowhead.com/tbc/item=9621/mountain-giant-muisek-vessel
https://www.wowhead.com/tbc/item=18904/zorbins-ultra-shrinker
https://www.wowhead.com/tbc/item=9597/mountain-giant-muisek
https://www.wowhead.com/tbc/item=18956/miniaturization-residue

Quests:

https://www.wowhead.com/tbc/quest=3127/mountain-giant-muisek
https://www.wowhead.com/tbc/quest=7003/zapped-giants

NPCs:

https://www.wowhead.com/tbc/npc=5358/cliff-giant
https://www.wowhead.com/tbc/npc=5357/land-walker

**Expected behavior**
step 4 should work and loot a "Mountain Giant Muisek" (item 9597)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue and the sources, fixed with next update!
