### ISSUE TITLE
Spirit Bond not working correctly

### ISSUE THREAD

**Issue by nigguJ** [ValorenWoW/sunstrider-core#5248]
The talent works fine untill the pet dies , then it fades completely without any chance of getting it back or u put second skill point into it

Spell: https://wowhead.com?spell=19578/spirit-bond

**Expected behavior**
The bond should continue after the pet is revived or/and  the player is dismounted
![Screenshot_6](https://github.com/SunstriderEmu/BugTracker/assets/144463364/24a36af9-ff12-4fb4-958c-e144cb2376df)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
