### ISSUE TITLE
Higher Regrowth Rank Hot should not be overwritten by lower Regrowth Hot

### ISSUE THREAD

**Issue by Soonkz** [ValorenWoW/sunstrider-core#5249]
**Describe the bug**

Higher Regrowth Rank Hot should not be overwritten by lower Regrowth Hot
If I cast Regrowth Rank 10, the hot of it should not be overwritten with the hot of Regrowth rank 5.

**Character name**

Daisydruid

**To Reproduce**

1. Cast Regrowth Rank 10 on yourself
2. Watch Hot per 3s
3. Cast Regrowth Rank 5 on yourself
4. Hot was overwritten

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

The expected behavior is that you do not overwrite the higher rank hot but only have the direct healing of the lower rank on the target but the higher hot remains active.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
That behavior is expected, we always allow overriding your own spells on our realms.
