### ISSUE TITLE
keyboard turning max range melee attack

### ISSUE THREAD

**Issue by rendkek** [ValorenWoW/sunstrider-core#5252]
**Describe the bug**

if you stand at max range of a target and keyboard turn back and forth slightly into and out of combat on enhance shaman you can attack a target without ever swinging your weapons. it shows as dps and everything procs just like you were attacking but there is no animation.
**Character name**

enhancement shaman

**Comment by Jerrythemagicdog** [comment]
Thanks, that's a visual issue with the client, a similar thing can be observed with creatures.
We might look into fixing it at some point.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next client update.
