### ISSUE TITLE
battle chicken

### ISSUE THREAD

**Issue by rendkek** [ValorenWoW/sunstrider-core#5253]
**Describe the bug**

the battle chicken squak is supposed to be guaranteed 100 percent if you have a hostile action performed on you by an enemy. Tested it on boars in hellfire and this does not seem to be the case.
**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, there's already an issue open though: https://github.com/SunstriderEmu/BugTracker/issues/5231
