### ISSUE TITLE
drowning too fast

### ISSUE THREAD

**Issue by rendkek** [ValorenWoW/sunstrider-core#5254]
**Describe the bug**

the rate of drowning is way too fast. you should drown in 7-8 "ticks" with about 1 second between each damage interval. On this server is is 5 ticks and the time between ticks seem to be half of what it should be.
**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Thanks, fixed with next server update
