### ISSUE TITLE
Auto shot stuck

### ISSUE THREAD

**Issue by disis24** [ValorenWoW/sunstrider-core#5255]
Auto shot get stuck

How to reproduce : Start a fight by casting an **aimed shot**, and spam any offensive ability (i mean an arrow ability who trigger auto shot by himself, like arcane shot, bug doesnt appear with hunter's mark for ex) while casting the aimed shot.

**Comment by nigguJ** [comment]
In addition , the bug occurs after Damaging cds . such as racial / rapid fire / beastial wrath, Same behavior was happening to the shamans with their  100% crit talent

**Comment by disis24** [comment]
No it has nothing to do with racial, rapid fire or bestial wrath, it appear because you may have a /cast steady shot or any other ability in your macro

**Comment by nigguJ** [comment]
Well i've none damaging abilities in the macro , therefor it buggs from the cast itself

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.

**Comment by disis24** [comment]
Did you update the server ? The bug is still there.

**Comment by Jerrythemagicdog** [comment]
Please provide a video of the issue happening, I can't reproduce it.

**Comment by disis24** [comment]
Only happens when using speedyaction or snowfallkeypress addon.
