### ISSUE TITLE
discovered a way to get permanant haste flurry executioner and focused

### ISSUE THREAD

**Issue by rendkek** [ValorenWoW/sunstrider-core#5256]
**Describe the bug**

swapping main hand enhancement shaman weapon with annihilator then quickly swapping back and using the weapon sync macro and i get all these buffs and they never go away. 
**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by rendkek** [comment]
seems like i have to swap weapons then weapon sync then quickly stormstrike and shock and it does it

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, I can't reproduce, could it be your AddOns hiding the buff durations?

**Comment by rendkek** [comment]
Ok I’ll delete my addons and give it another shot. Thought it was weird I was suddenly having all these issues an addon would make sense. 
Thanks!


Sent from Yahoo Mail for iPhone


On Monday, September 11, 2023, 4:44 PM, Jerrythemagicdog ***@***.***> wrote:




Thanks for the issue, I can't reproduce, could it be your AddOns hiding the buff durations?
