### ISSUE TITLE
water sheild and earth sheild icon with charges remaining showing missing from screen 

### ISSUE THREAD

**Issue by rendkek** [ValorenWoW/sunstrider-core#5257]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

![Screenshot 2023-09-11 130643](https://github.com/SunstriderEmu/BugTracker/assets/144680456/1f7f9b5a-b216-4642-9af7-c830bf529ca9)

**Additional context**

![Screenshot 2023-09-11 130845](https://github.com/SunstriderEmu/BugTracker/assets/144680456/74af5609-e937-49b7-9fc2-7b813743bc9c)

**Comment by rendkek** [comment]
top screenshot is what it is like on the ptr bottom screenshot is what it is supposed to be like.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, this looks to be a result of some addon you're running, I can't get this to happen.
