### ISSUE TITLE
World void of Ore Deposits

### ISSUE THREAD

**Issue by gorthal23** [ValorenWoW/sunstrider-core#5258]
**The world does not contain any Ore Deposits.**

**Gorthal**

**Valley of Heroes - Barrens appears to contain no Ore Deposits. None observed with / without Detect Minerals, checked a good number of known spawns as well as inside caves which are bound to contain 1-3 nodes**

**Comment by gorthal23** [comment]
Edit: Found my first Copper Vein in Northern Barrens. At level 24.

**Comment by z5n** [comment]
Thanks for the issue, the pooling system responsible for spawning these objects is currently disabled on the test realm.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
