### ISSUE TITLE
Torek NPC in "Torek's Assault" targetable by AoE attacks as Horde

### ISSUE THREAD

**Issue by gorthal23** [ValorenWoW/sunstrider-core#5260]
**The NPC Torek is targetable (and can become hostile) while doing the "Torek's Assault" quest.**

**Gorthal**

**I was hitting two Night elf NPCs during the quest using Cleave on my warrior. He got hit as one of the elves died, and became hostile and proceeded to hunt down and kill me.**
<!See Above. -->
1. Cast X on target affected by ...
2. 
3. 

Quest: https://wowhead.com?quest=](https://www.wowhead.com/classic/quest=6544/toreks-assault

**I did not expect the Horde NPC to be targetable by my AoE:s as a Horde warrior. It appears he was targetable, and he chased me all the way to Splintertree post where he finally killed me. Apparently does not leash either.**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
