### ISSUE TITLE
Dying on logout

### ISSUE THREAD

**Issue by panplume** [ValorenWoW/sunstrider-core#5261]
**Describe the bug**
It is possible to die while mounted (fly), out of combat, after the 20s delay on logout. Did it twice, although not 100% reproducible, did it in 3 try.

**Character name**
Stl

**To Reproduce**
1. Created a mage to test an addon using the default PvE dialog at Camp Manager
2. Get to Netherstorm, north of Manaforge Coruu
3. Get on flying mount
4. Run (land) into blood elf caster pack near the north access to get into combat
5. Fly away to the bridge toward Area 52 (went out of combat hitting one of the rock on top of the bridge)
6. logout in a safe spot, I was near the bridge, no mob around (wait 20s)
7. if not dead, login and restart at 1. (took me 3 try)

Can work elsewhere, first time was south of Sunfury Hold (could barely rez as my body was still up in the air)

**Expected behavior**
Waiting 20s out of combat to logout shouldn't kill you.

**Additional context**
At least the dead body shouldn't stay in the air, either drop to the ground or teleport to graveyard like when dying in the Twisting Nether.

**Comment by kelno** [comment]
Thank you, fixed with next server update
