### ISSUE TITLE
Warrior - Shield dissapears back into Inventory after weapon switch macro

### ISSUE THREAD

**Issue by KayaErdal** [ValorenWoW/sunstrider-core#5262]
**Describe the bug**
The Shield is unequipped after using a weaponswitch macro.
It eequips the shield but then after 1 second it gets unequipped.

**Character name**
Chevy

**To Reproduce**
1. Create a Warrior and gear him up with PVP Arena Arms Starter Set
2. Make this Macro:

#showtooltip Defensive Stance
/equipslot 16 Vengeful Gladiator's Pummeler
/equipslot 17 Vengeful Gladiator's Shield Wall
/cast Defensive Stance

3. Use Macro 

Item: https://www.wowhead.com/item=33755/vengeful-gladiators-shield-wall?bonus=9357

**Expected behavior**
After changing Weapons, the 1h Mace and the Shield should stay equipped

ADDED:
I just figured out, that this bug does not happen when in combat. Only out of combat

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, I can't get it to happen.
Try disabling AddOns and trying the macro then, or providing a list of AddOns you're using.

**Comment by KayaErdal** [comment]
Thank you for the fast replay, i could manage to find out that it is related to the "Outfitter" Addon, if i turn that one off, it works normally

Added:
i found that there was a setting "automatic changes", which could be turned off, then it works aswell, sorry for the inconvenience

**Comment by Jerrythemagicdog** [comment]
Thanks for testing!
