### ISSUE TITLE
Drinking with weapon switch Macro, doesnt consume the water but you get the mana

### ISSUE THREAD

**Issue by KayaErdal** [ValorenWoW/sunstrider-core#5267]
**Describe the bug**
I have a macro, where i switch to a mp5 weapon and in the 2nd line i use arena water to drink. When i press the macro, the weapon is switched and my character starts to drink, but the water in my inventory is not used. I had 20 water before drinking, after clicking i still have 20 water.

**Character name**
Cyrex

**To Reproduce**
1. Create a Hunter -> get pvp MM starter gear
2. Buy Arena Water (Star's Tears) from Vendor
3. Create this Macro
#showtooltip Star's Tears
/equip Staff of Dark Mending
/use Star's Tears

4. use macro when out of combat

Items: 
https://www.wowhead.com/item=32453/stars-tears
https://www.wowhead.com/item=33490/staff-of-dark-mending

**Expected behavior**
The water in the inventory should be consumed.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
You're testing in the Endless Testing Area where consumables such as water are not consumed to make testing easier.
