### ISSUE TITLE
Nameplate disctance feature

### ISSUE THREAD

**Issue by disis24** [ValorenWoW/sunstrider-core#5268]
Inconsistancy between nameplate distance (endless option) and spells distance.
Looks like one is in yards and the other in meters.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Spells use different range measurements compared to nameplates.
Nameplate distance is measured from the center of your character's model to the center of the target's model.
Spell range is calculated from the edge of your character's model to the edge of the target's model.
