### ISSUE TITLE
Loramus quest NPC dialogue in French

### ISSUE THREAD

**Issue by gorthal23** [ValorenWoW/sunstrider-core#5269]
**Describe the bug**
<I came across a quest in Azshara where the NPC dialogue is in French.>

**Character name**
<Gorthal>

**To Reproduce**
<During the quest "Loramus" in Azshara the NPC (also named Loramus) displayed the dialogue text in French rather than English->

[Quest: https://wowhead.com?quest=](https://www.wowhead.com/tbc/quest=3141/loramus)

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
