### ISSUE TITLE
Swing timers

### ISSUE THREAD

**Issue by erkmage** [ValorenWoW/sunstrider-core#5270]
**Describe the bug**

 All the swingtimers ive used either WA or Addon it resets of Sword procs for warriors, and then half way through the swing the "normal white hit" comes so its an issue when playing arms as you need to slam right on a swing.
**Character name**

Viskan
**To Reproduce**

1. any dmg spell to proc it on a target ...
2. Sword proc from warrior talents
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell:(https://www.wowhead.com/tbc/spell=12815/sword-specialization)
**Expected behavior**

Swing timer not resetting on the proc
**Screenshots/videos**

https://medal.tv/games/world-of-warcraft/clips/1v3zGipXhMq5Tc/d1337XL2ig3w?invite=cr-MSwyWVksMTUwMjY4NjE0LA
**Additional context**

**Comment by hotdogsteven** [comment]
devs can feel free to link a single swing timer that works on endless. checked 6+ including weakauras, none work here.

**Comment by Jerrythemagicdog** [comment]
Appears to be working correctly.
