### ISSUE TITLE
Draenei Language Doesn't Work

### ISSUE THREAD

**Issue by dromen48** [ValorenWoW/sunstrider-core#5271]
**Describe the bug**
When playing a Draenei the language doesn't switch from Common to Draenei.

**Character name**
Any Draenei but Donjulio

**To Reproduce**

1. Make a Draenei
2. Switch to Draenei language
3. talk in say and it doesn't work (it should work in party too)

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
All players can understand all languages as of right now because of cross-faction settings.
