### ISSUE TITLE
Quest Totem of Vark Kills Player

### ISSUE THREAD

**Issue by dromen48** [ValorenWoW/sunstrider-core#5272]
**Describe the bug**
Hello, Totem of Vark quest kills you when the panther spirit form wears off.

**Character name**

**To Reproduce**

1. Complete Totem of Vark quest (Furbolg chain quest on Azuremyst Isle)

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**
![draenei bug](https://github.com/SunstriderEmu/BugTracker/assets/111084731/b5a232ae-9025-474a-999e-1a7a4fc081ab)

**Additional context**

**Comment by dromen48** [comment]
![image](https://github.com/SunstriderEmu/BugTracker/assets/111084731/64d65556-efb7-44b4-84fc-184910c7fb2a)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update!
