### ISSUE TITLE
Eyes of Grillok not completable

### ISSUE THREAD

**Issue by gorthal23** [ValorenWoW/sunstrider-core#5273]
**This quest asks you to capture and release an Eye of Grillok; it's not possible to interact with the cauldron where you release it.**

**Gorthal**

**To Reproduce**
<It is not possible to interact with Zezzle's Cauldron where you are supposed to drop off the Eye of Grillok; not before absorbing an Eye, nor after. Walking right next to the Cauldron has no effect either.

(https://www.wowhead.com/tbc/quest=10813/the-eyes-of-grillok)>

**Comment by gorthal23** [comment]
Update: Dropping the quest, retaking it and capturing another Eye and escorting it back worked.

Weird, no idea what caused it to fail the first time but it seems fine now.

**Comment by Jerrythemagicdog** [comment]
Thanks for the update and the details!
We've updated the way the quest is credited and checked for, the previous way was a bit fragile.
