### ISSUE TITLE
Shadowfiend values too high

### ISSUE THREAD

**Issue by Deephx** [ValorenWoW/sunstrider-core#5279]
**Describe the bug**
The priest ability 'Shadow Fiend' seems to be on wrath values, not tbc. It restores too much mana and deals too much damage (from what I can remember).

**Character name**
Dffh on endless PTR

**To Reproduce**
1. cast Shadow Fiend
2. watch the values

Spell: https://www.wowhead.com/tbc/spell=34433/shadowfiend

**Expected behavior**
restores less mana, deals less damage

**Screenshots/videos**
Mana restored from one Shadow Fiend on PTR:
![image](https://github.com/SunstriderEmu/BugTracker/assets/145975311/e8a92cfd-d12b-4f94-9a8f-6ccf62b6bb8c)
Damage dealt from one Shadow Fiend on PTR:
![image](https://github.com/SunstriderEmu/BugTracker/assets/145975311/4f699da2-3734-4881-8deb-9d665c510f79)

**Additional context**
xxx

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
