### ISSUE TITLE
Druid - Spell: "Rip" - doesn't get increased damage from "Mangle"

### ISSUE THREAD

**Issue by phiLord4** [ValorenWoW/sunstrider-core#5280]
I tested this on a level 70 druid against **training dummies** and in **duels**.

Rip's damage is the same (for me 343 damage per tick) **with or without** the mangle debuff on the target which should increase bleeding damage by 30 %.

Character name is: Snuggle

**To Reproduce**
1. stack 5 combo points
2. use Mangle (Cat) / Mangle (Bear)
3. use Rip

-Repeat without step 2-

Thanks for the good work!

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue and the details!
Fixed with the next update.
