### ISSUE TITLE
Loch Modan Kobolds

### ISSUE THREAD

**Issue by youngTriceps** [ValorenWoW/sunstrider-core#5281]
The Tunnel Rat kobolds in the Silver Stream Mine in Loch Modan are dropping level 56-58 green items at 100% droprates.

Here are their wowhead links:
https://www.wowhead.com/classic/npc=1175/tunnel-rat-digger
https://www.wowhead.com/classic/npc=1174/tunnel-rat-geomancer

These are level 13 mobs dropping level 56-58 greens on every single kill.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue and the details!
We've also found a few more Kobolds with a similar issue, fixed with the next update.
