### ISSUE TITLE
'Warn Bolvar!' quest teleport

### ISSUE THREAD

**Issue by Savageferret** [ValorenWoW/sunstrider-core#5282]
**Describe the bug**
Jaina doesn't offer a Stormwind teleport to the player when they have the quest 'Warn Bolvar!'

**To Reproduce**

1. Complete the prereqs for 'Warn Bolvar!'
2. Accept 'Warn Bolvar!'
3. Talk to Jaina, she doesn't offer teleport / dialogue options

Quest: https://www.wowhead.com/tbc/quest=11222/warn-bolvar

**Expected behavior**
After accepting the quest, there should be a dialogue option to have her teleport you to Stormwind, as described in the quest description (I can't find video of this unfortunately, but I believe it is a dialogue option)

**Additional context**
After she teleports you to Stormwind, you turn in the quest to Bolvar. Bolvar then gives you https://www.wowhead.com/tbc/quest=11223/return-to-jaina which has you talk to https://www.wowhead.com/tbc/npc=2708/archmage-malin to teleport you back to Theramore (where Jaina is)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
