### ISSUE TITLE
Warlockpet Bug Felhunter

### ISSUE THREAD

**Issue by budgebudge** [ValorenWoW/sunstrider-core#5283]
**Describe the bug**

Tried to counterspell + feldom felhunter and cs again. the problem is that the felhunter is still stunned (as if u would do a normal summon when your old pet gets stunned for a few seconds when u do a new summon) when using FELDOM (insta summon). this makes the whole feldom+cs combo useless.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
