### ISSUE TITLE
Hunter's Mark

### ISSUE THREAD

**Issue by disis24** [ValorenWoW/sunstrider-core#5285]
When someone refresh hunter's mark  it should preserve the stacks (110 to 440 ranged ap).

The melee bonus given by [Improved Hunter's Mark]  should also be preserve if you refresh the mark without [Improved Hunter's Mark].

https://discord.com/channels/253213664708919296/794708850187567174/859913037035864094

**Comment by disis24** [comment]
I mean when you refresh the mark which was applied by another hunter

**Comment by kelno** [comment]
Thanks, I fixed most refresh cases.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The first part will be resolved with next update.
Can you provide proof for the melee part of attack power being kept on refresh by a Hunter without Improved Hunter's Mark?

**Comment by hotdogsteven** [comment]
> When someone refresh hunter's mark it should preserve the stacks (110 to 440 ranged ap).
> 
> The melee bonus given by [Improved Hunter's Mark] should also be preserve if you refresh the mark without [Improved Hunter's Mark].
> 
> https://discord.com/channels/253213664708919296/794708850187567174/859913037035864094

upload the image directly here or onto imgur. you cant link images from private discord channels

**Comment by disis24** [comment]
https://discord.gg/classichunter
Archives/tbc-pve => pinned message
![Screenshot_20230926-185156](https://github.com/SunstriderEmu/BugTracker/assets/65676825/84b37934-e1a2-4dd5-aeb5-e25afd7e34ee)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
