### ISSUE TITLE
Hunter pet talent while leveling

### ISSUE THREAD

**Issue by Motibeta** [ValorenWoW/sunstrider-core#5286]
**Describe the bug**
The new pet talent tree doesn't allow us to pick some talents, eventhough they are "green". For instance, I tamed a cat and can't learn Bite or Claw. I tried to wait until level 30 to see if the pet can learn "Cobra Reflexes" or "Dash" but it won't let me. As I said, the talents are "green" but when I click on it to learn it, nothing happens, and I have unspent talents. However, it works with "Great Stamina"

**Character name**
Motitest on the PTR

**To Reproduce**

1. Tame a pet that can learn said talents
2. Try to learn it
3. It doesn't work

**Expected behavior**
It should normaly learn the first rank of the spells and then learn the new ranks as it levels up. Anyway, if it's intended that the pet can't learn these talents before beeing level higher, it shouldn't be "green" as if you could learn it.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
Make sure your client is up to date by starting the game through the launcher or using the alternative download at https://endless.gg/getstarted, this is a screenshot from the PTR on the latest version: 
![image](https://github.com/SunstriderEmu/BugTracker/assets/46463908/f643066a-aeee-4396-aa64-fedec1e8956f)

**Comment by Motibeta** [comment]
Thanks for your fast answer.

I do play on the right version, downloaded from your website. I also do see the talent tree exactly as shown on your screenshot.

But, did you try to learn (put a talent point in) « claw » or « bite » on your lvl 29 character? Because that’s where I think the issue is. Same problem will appear once you and your pet hit lvl 30 for the talent « Dash », « Cobra Reflexes » or « Cower ».

Thanks for your time

**Comment by Jerrythemagicdog** [comment]
Moved to Discord to get more information.
