### ISSUE TITLE
Hunter traps triggering instant in duel

### ISSUE THREAD

**Issue by Deephx** [ValorenWoW/sunstrider-core#5289]
**Describe the bug**
When laying a hunter trap in a duel without using scatter shot before, it triggers instantly. So just laying a blank trap makes it trigger instantly.
When using scatter shot -> trap , the trap triggers after ~2secs

**Character name**
Testonetutre on the PTR

**To Reproduce**

1. Cast a hunter trap on a target without using scatter shot before.
2. It triggers instantly

Spell: https://www.wowhead.com/tbc/spell=1499/freezing-trap

**Expected behavior**
There should be a set trigger duration on a trap (~2secs).

**Comment by Jerrythemagicdog** [comment]
Trap trigger time is about the victim's combat state.
https://github.com/SunstriderEmu/BugTracker/issues/1739

**Comment by Deephx** [comment]
Ok thanks for clarifying.
