### ISSUE TITLE
Warrior - Rage loss & Anger Management

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5290]
Currently warrior rage loss out of combat is -2 rage per tick.  Correct value is -3 per tick.
![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/e0cb1673-d0b0-4773-a3df-c7abd2990698)
^ capture of talents from video

https://youtu.be/GuXcM_QSIt0?t=91

When talented with Anger Management, rage loss outside of combat should be reduced to -2.

Currently Anger Management does not do this, and the default rage loss is simply -2.
[https://www.wowhead.com/tbc/spell=12296/anger-management#comments:id=2749818](url)
[https://www.wowhead.com/tbc/spell=12296/anger-management#comments:id=2749818](url)

**Comment by kelno** [comment]
Thanks, fixed with next server update
From what we could gather, without talents the loss is something between 2 and 3.
With the talent it's between 1 and 2.

**Comment by hotdogsteven** [comment]
> Thanks, fixed with next server update From what we could gather, without talents the loss is something between 2 and 3. With the talent it's between 1 and 2.

yeah the talent is extremely odd.  they changed the text and functionality completely, but still kept all the functionality from vanilla working behind the scene.  fairly certain it works the same still on wrath classic atm.
