### ISSUE TITLE
Debuff timer increasing while offline

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5291]
Debuffs are increasing overtime while offline for long periods of time.

![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/4a3616b6-f096-4fc9-9120-12d13cee0f8a)
![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/64a407ad-295a-4f80-8595-d302522151c6)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
I can't reproduce it, the auras expire correctly when offline.

**Comment by hotdogsteven** [comment]
Characters: Gage, Tanna

**Comment by kelno** [comment]
Just stay logged out for a month and this will happen

**Comment by kelno** [comment]
Fixed with next update
