### ISSUE TITLE
Shaman - Flurry Talent

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5292]
If both the Main-hand and off-hand weapons land within 0.5 seconds of one another, Flurry is suppose to only use 1 charge for both attacks, not 2. This is an important change for Enha Shaman as this prevents your Windfury procs from instantly consuming Flurry, especially if your autos line up with Windfury & Stormstrike cooldowns.

https://www.youtube.com/watch?v=TWAP8U_6C40&ab_channel=ConnorHart

https://github.com/SunstriderEmu/BugTracker/assets/136162502/7fdef68e-dc7e-4265-a692-232306cba802

**Comment by hotdogsteven** [comment]
![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/213c0ce6-aa65-4e39-8e79-4ed434791684)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
