### ISSUE TITLE
Shaman - Lightning Overload Talent

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5293]
Currently Lightning Overload is proccing when the spell lands, not on cast.

https://youtu.be/tEh5yXau2qM?t=76

Shaman Discord:

![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/d766e70e-6f99-47dd-82d0-022b55c69371)

**Comment by Jerrythemagicdog** [comment]
The proc happens after the initial cast proccing LO arrives at the target, this is a misunderstanding of what Aeded said in the Shaman Discord.

**Comment by hotdogsteven** [comment]
https://youtu.be/tEh5yXau2qM?t=99
yeah youre right, he got a LB proc right before current cast finishes while under bloodlust here.
