### ISSUE TITLE
Warrior - Warglaives of Azzinoth

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5295]
Warglaive of Azzinoth 2-set proccing from changing stances.

https://github.com/SunstriderEmu/BugTracker/assets/136162502/c91a5b80-5ab6-4728-80cb-32bffea2284b

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.

**Comment by disis24** [comment]
Try to swap weapon if it reset the internal cd, was a bug on endless 2
