### ISSUE TITLE
Swapping group removing party-wide buffs

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5296]
Currently this does not happen on Endless, as it did in classic.

https://github.com/SunstriderEmu/BugTracker/assets/136162502/fb3c8dd1-25e0-4955-9531-0d114920b09c

Below is a list of buffs using the same party-wide targeting:

- Ancestor's Vengeance
- Arcane Absorption
- Battle Roar
- Battle Shout
- Battle Squawk
- Battlemaster
- Blessing of Shahram
- Commanding Shout
- Divine Light
- Enraged Defense
- Enraged Howl
- Ferocious Inspiration
- Fire Absorption
- Fist of Shahram
- Flametongue Totem Effect
- Frost Absorption
- Furious Howl
- Gas Bomb
- Grow
- Healing Circle
- Holy Nova
- Irradiated
- Judgement
- Mana Tide Totem
- Nature Absorption
- Pathfinding
- Prayer of Healing
- Roar of Fortitude
- Shadow Absorption
- Shrink
- Simple Teleport Group
- Spellsurge
- Tainted Howl
- The Lion Horn of Stormwind
- Unleashed Rage
- Vampiric Embrace
- Vampiric Touch
- Windfury Totem Effect
- Word of Mass Recall (OLD)

**Comment by kelno** [comment]
Thanks, fixed with next server update
https://github.com/kelno/sunstrider/commit/746e9f1557dca6a8f80f624a51770d3a7bfa4083
