### ISSUE TITLE
Hunter: Eyes of the Beast [Expires to Early]

### ISSUE THREAD

**Issue by johnmausman1** [ValorenWoW/sunstrider-core#5299]
**Describe the bug**
1. Eyes of the Beast expires prematurely.

Spell: https://www.wowhead.com/tbc/spell=1002/eyes-of-the-beast

**Expected behavior**
1. Eyes of the Beast should only be cancelled unless done so manually by the player (cancelaura) or the duration of the cast expires (1:00 minute)

**Screenshots/videos**
Endless Eyes of the Beast: https://streamable.com/j6sibn
TBCC Eyes of the Beast:  https://www.veed.io/view/33fb7a0f-377c-4ff2-a19c-27719b953ac5?panel= (file size to large for streamable)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The current max range is 100yd, we're keeping it that way.
