### ISSUE TITLE
Supply crates in stratholme instance

### ISSUE THREAD

**Issue by anderskp09** [ValorenWoW/sunstrider-core#5300]
**Describe the bug**

Might be overkill posting here, but why not.
The regular supply crates (NOT the ones in living side) inside stratholme seems to never have actual loot, only bugs/trapped ones. 
Granted this is based on limited quantative testing, but on other servers / retail the number is significantly higher
Makes it more difficult aquiring holy water :)

**To Reproduce**

1. Go to stratholme
2. Open supply crates
3.  Get trapped 24/7

**Expected behavior**
To actually have random loot from the supply crates.
Usually (on other servers / retail) its a grey/green items, random low lvl pots, some food + water and 1-4 holy water

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
Supply Crates are pooled so the chance of getting a chest or a trap is random each time you enter the instance.

We found an issue though where in some places their spawnpoints were incorrectly doubled.

**Comment by anderskp09** [comment]
Hey @Jerrythemagicdog . Honestly this still seems like a problem, now that im trying it out on live. The ones i can open are traps, and theres a lot that does not let me interract with them (perhaps those are the "working" ones?)
![image](https://github.com/SunstriderEmu/BugTracker/assets/69630725/318dc92f-56a2-450f-9591-9420362f7ed2)

**Comment by anderskp09** [comment]
... you cant see my cursor, but its not letting me open them :)
