### ISSUE TITLE
[Paladin][Seal of Righteousness not proccing twice when twisting from Seal of Command

### ISSUE THREAD

**Issue by Spartanv** [ValorenWoW/sunstrider-core#5302]
**Describe the bug**
When twisting between Seal of Command and Seal of Righteousness, 
Seal of Righteousness is proccing only once instead of twice.

**To Reproduce**

1. Cast Seal of Command
2. use macro or cast Seal of Righteousness manually
/cast Seal of Righteousness
/startattack

**Expected behavior**
Seal of Righteousness should proc twice when when twisting from Seal of Command
**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/11991518/7f9782e4-f89c-446b-96a4-ac46cf918cd1)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, but this seems correct looking at the spell's data.

**Comment by Spartanv** [comment]
@Jerrythemagicdog 
It is not correct. Please take a look at this footage from tbc classic. I can give you more footage if you want. I was twisting SoC-> SoR on tbc classic.
https://www.youtube.com/watch?v=u2SH4zHPwAU&ab_channel=pickrobber
https://www.youtube.com/watch?v=kHbp9rovpoY&ab_channel=pickrobber

**Comment by hotdogsteven** [comment]
You had reckoning in this video. Ok the second video is better.

**Comment by Spartanv** [comment]
![image](https://github.com/SunstriderEmu/BugTracker/assets/11991518/edd8d777-1c4f-4b67-9df1-ddac8bd4e9e9)
screenshot from 2nd video showing double SoR Proc from Command

**Comment by Sologrim** [comment]
yes, I can confirm, that SoR must proc twice: 1 proc from melee attack and 2nd proc from SoC
it should basically work the same for SoR and SoB

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
