### ISSUE TITLE
Druid forms dependend on racial skill rather than race . 

### ISSUE THREAD

**Issue by Qiyazu** [ValorenWoW/sunstrider-core#5305]
Issue

Currently druid forms are displayed dependend on the racial choice you select. For example when you pick a nightelf druid with tauren racial (warstomp), the cat/bear forms are displayed as the tauren ones instead of the nightelf ones. 

Expected behavior

When you pick a nightelf druid with tauren racial (warstomp), the cat/bear forms are displayed as the nightelf ones instead of the tauren ones.

**Comment by kelno** [comment]
Thank you for reporting.
Currently this is intended as it fits the arena/bg system where other players will see your model as your chosen racial race, but in this instance it's done in a different way that will show it to everyone all the time. Would be better to change it to be more consistent and always show your base race to yourself.

**Comment by kelno** [comment]
Fixed with next server update
