### ISSUE TITLE
[PET TALENT] Cobra reflexes not working as intended

### ISSUE THREAD

**Issue by Enory** [ValorenWoW/sunstrider-core#5306]
Currently the pet talent cobra reflexes increase pet melee swing by 30% and decrease melee dmg by 30%
It also don't reduce the pet dmg shown in pet stat, the swing speed is updated correctly.

Note : post edited with more readable values.

Values summary : 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

dmg type | without talent | with talent | value change
-- | -- | -- | --
min | 213 | 163 | -30,7%
avg | 234 | 181 | -29,3%
max | 257 | 197 | -30,5%
speed | 2 | 1,54 | -29,9%

</body>

</html>

spell ID : 25076
[https://www.wowhead.com/classic/spell=25076/cobra-reflexes](url)

**Stats without the talent**
![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/ee964dd0-0779-4ae3-8791-d231ff29ccdf)

**Damage without the talent**
![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/b7e9247d-b837-4227-8a6f-4ee303f13b39)

**Stat with the talent**
![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/bb01c91f-7d10-4e6e-a1f9-ade803bdf7b7)

**Damage with the talent**
![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/17d22dea-5320-4511-8749-ddea1a7056a2)

**To Reproduce**
hit on dummy with and without the talent

Spell: https://wowhead.com?spell=25076

**Expected behavior**
Cobra reflexes should grant a 30% speed swing bonus, for a 14%-15% dmg loss on melee

Sources used : 
[https://www.wowhead.com/tbc/spell=25076/cobra-reflexes#comments](url)
[https://chasseur-bc.jimdofree.com/les-familiers#Caracteristiques-de-base](url)

**Comment by hotdogsteven** [comment]
Your screenshots show no talent change in either section. Turn off lightning bolt while you are testing. Make sure you are attacking the same 0 armor target. 

What is your testing method? Time based? Theres no connection at all between the 2 screenshots and any form of stat gain or loss, you just posted 2 numbers.

**Comment by disis24** [comment]
**Without cobra reflexes** (0/0/0 troll hunter, no procs, wind serpent with 781ap and green happiness, 0 armor dummy) :
![noreflexes](https://github.com/SunstriderEmu/BugTracker/assets/65676825/b0501dc4-f87e-4510-8052-203ce810b611)

**With cobra reflexes** (0/0/0 troll hunter, no procs, wind serpent with 781ap and green happiness, 0 armor dummy) :
![reflexes](https://github.com/SunstriderEmu/BugTracker/assets/65676825/ee3a95fb-2b5f-40f5-8faf-ddae21d54e55)

182/240 = 0,7583333333333333

Melee dmg is reduced by 25% instead of 15%.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.

**Comment by Enory** [comment]
Just for note but i confirm it is fixed on beta
