### ISSUE TITLE
Mana Looms missing from Shattrath

### ISSUE THREAD

**Issue by StoneyMahoney420** [ValorenWoW/sunstrider-core#5307]
Neither mana loom appears to exist in Shattrath near the tailoring trainer or the other guy.

The mana loom in Silvermoon City does exist, does work, and the requirement to be near a loom when making Imbued Netherweave Cloth is imposed correctly.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
