### ISSUE TITLE
Gann Stonespire Stunlocked after interaction

### ISSUE THREAD

**Issue by nigguJ** [ValorenWoW/sunstrider-core#5308]
Whenever you interact with him he gets locked and does not appear to move around anymore . Tried abandoning the quest he is still locked.

1. Accept any of his quests
2. Observe his behavior 

Quest: https://www.wowhead.com/classic/npc=3341/gann-stonespire#starts

**Expected behavior**
After quest pickup , continues roaming around his coded path

**Comment by nigguJ** [comment]
Update: this is happening with most of the npcs that gives quests and have roaming pattern

**Comment by Jerrythemagicdog** [comment]
NPCs stop for some time when you interact with them, in most cases they're not updated (in the open world) when there's nobody around them.
