### ISSUE TITLE
[Quest] Suntara Stones, escort quest mob is dead at his starting position (spoiler should only die at the escort end point)

### ISSUE THREAD

**Issue by panplume** [ValorenWoW/sunstrider-core#5310]
Title: found him dead in the pit where he should be offering his escort quest.

https://www.wowhead.com/tbc/npc=8284/dorius-stonetender

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, he's not dead though you can talk to him.
Classic: https://www.youtube.com/watch?v=PWi-u6UQ8Uo

**Comment by panplume** [comment]
True but still you need to randomly click on a dead body, no exclamation mark, no cursor accommodating to the possible interaction, very much different from the video you linked.
