### ISSUE TITLE
[Hunter talent]Thrill of the hunt incorrect procrate

### ISSUE THREAD

**Issue by Enory** [ValorenWoW/sunstrider-core#5311]
**Describe the bug**
the first and second talent points don't give good procrates

**To Reproduce**
hit on dummy with 1 and 2 talent point in thrill of the hunt

For this i made 4 series of 100 crit on steady shot for each talent point, to get a viable procrate.
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

talent   point | procrate 1 | procrate 2 | procrate 3 | procrate 4 | average
-- | -- | -- | -- | -- | --
1/3 | 14% | 12% | 9% | 13% | 12%
2/3 | 41% | 48% | 44% | 42% | 44%

</body>

</html>

Thrill of the hunt 1/3 spell ID 34497 : [https://www.wowhead.com/tbc/spell=34497/thrill-of-the-hunt](url)
Thrill of the hunt 2/3 spell ID 34498 : [https://www.wowhead.com/tbc/spell=34498/thrill-of-the-hunt](url)

**Expected behavior**
Thrill of the hunt gives 33/66/100% chance to restore 40% of manacost of a spell when it crit.

Notes : 
-Thrill of the hunt talent and efficiency talent interaction is working correctly (talent -10% spellmana cost).
-Thrill of the hunt 3/3 (spell ID 34499) is working correctly

**Additional context**
The issue is that survival pve specs never use 3/3 on this talent. All spec are using 1/3 or 2/3 talent points in it (not enough talent points avilable to go 3/3)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue and the described methodology.
Turns out we were rolling the proc chance twice for all ranks outside of 3/3.
Fixed with the next update.

**Comment by hotdogsteven** [comment]
wow hunter with a brain? looking for a guild m8? xD
