### ISSUE TITLE
[NPC] Kyle the Frenzied

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5313]
NPC Kyle the Frenzied should be running at full speed, patrolling the town of Bloodhoof Village

Well his patrol path appears correct, but he is moving only at walking speed

https://www.wowhead.com/tbc/npc=23616/kyle-the-frenzied

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
