### ISSUE TITLE
[QUEST] Supplies for the Crossroads

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5314]
Quest "Supplies for the Crossroads" from NPC Thork in Barrens.

Currently - requires you to first have completed "Disrupt the Attacks" before he offers this quest.

This is incorrect - he should be able to provide this quest to you right away with nothing required (except minimum lvl of 9)

https://www.wowhead.com/tbc/quest=5041/supplies-for-the-crossroads

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Wowhead and Wowwiki seem to be wrong in this case.
Both of them list "Disrupt the Attacks" as a quest unlocking "Supplies for the Crossroads", but on Classic (https://youtu.be/vyGvs_5Nlgk?t=2) this player can pick both of them up at the same time.

Fixed with the next update.
