### ISSUE TITLE
Transmog UI Sound

### ISSUE THREAD

**Issue by Savageferret** [ValorenWoW/sunstrider-core#5315]
**Describe the bug**
Transmog UI doesn't respect sound settings

**To Reproduce**

1. Go to sound settings, lower the 'Sound' slider
2. Keybind 'Toggle Transmofigy' to something and press keybind
3. Notice how loud transmog ui is compared to every other ui action

**Expected behavior**
Transmog UI should respect 'Sound' slider

**Comment by Godmatik** [comment]
Confirmed, it is extremely loud

**Comment by kelno** [comment]
Thank you, fixed with next client release

**Comment by kelno** [comment]
Applied now! (Need the last update from the launcher)
