### ISSUE TITLE
Moonfire Dot Override

### ISSUE THREAD

**Issue by Savageferret** [ValorenWoW/sunstrider-core#5316]
**Describe the bug**
Moonfire rank 11 is overriding moonfire rank 12 dot

**To Reproduce**
1. Cast rank 12 Moonfire, applying the dot
2. Cast rank 11 Moonfire, the dot gets overridden with the rank 11 version

Spell: https://www.wowhead.com/tbc/spell=8921/moonfire
There are comments on the wowhead page referencing this behavior

**Expected behavior**
A lower rank Moonfire dot shouldn't override a higher ranked Moonfire dot

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we always allow overriding your own spells on our realms though.
