### ISSUE TITLE
Pets/Companions of enemy minions despawn when you kill their master

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5317]
This is a bug that has been around for a while now on several private servers.

Currently on Endless - if an enemy mob has a pet/companion with him - and you kill the master - the companion despawns instantly, but should not.

Example - Razormane Hunter in Barrens.

Joana video below showing how it should work (pet is still alive after master dies, must also be killed)
https://www.youtube.com/watch?v=Jgcn0jgdyvE&t=4m55s

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
This currently depends on spell data that's used to summon the pet, perhaps we are interpreting some of that wrong.

**Comment by Jerrythemagicdog** [comment]
In this case, the Razormane Hunter was despawning the pet in his script.
However, there are definitely cases where a creature pet should be despawned on summoner's death, we've looked into that quite a bit when first re-implementing this system.
We'll need to look at more examples.

**Comment by Jerrythemagicdog** [comment]
We did some testing and comparisons to Classic, can't see any other cases right now where the creature's pet is incorrectly despawned on owner's death, if you find any we'll re-open the issue, thanks!
