### ISSUE TITLE
[NPC] Barak Kodobane

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5319]
Melee damage done by Barak is simply too high, normal attacks hitting for 50+ damage, more than 2x and 3x of nearby mobs.

Shoot damage also might be slightly too high, but can't really confirm.

https://www.wowhead.com/classic/npc=3394/barak-kodobane
https://www.youtube.com/watch?v=Jgcn0jgdyvE&t=2085s

**Comment by blblblaz** [comment]
thanks, fixed with next update

**Comment by Jerrythemagicdog** [comment]
This made us look at more creatures with a similar issue, if you encounter more and feel like reporting them it would probably be better to wait until the next update (tomorrow).
