### ISSUE TITLE
[CORE] Object - can't interact with battered chest

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5320]
Noticed this chest in the below screenshot in barrens (Kolkar Camps west of Forgotten Pools)

Can not interact with it or open - not sure if it's a visual bug or if the chest itself is bugged.

![Chest](https://github.com/SunstriderEmu/BugTracker/assets/37913400/cc32eadc-c552-4476-a936-0fda83abd4a4)

**Comment by Godmatik** [comment]
Same issue with chest near Samophlange console

Core problem (at least in barrens)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update!
