### ISSUE TITLE
[QUEST] Egg Hunt

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5321]
**Currently**: When looting the Silithid Egg from the Silithid Mound - two Silithid Protector always spawn and immediately aggro you.

**How it should work**: There should only be a chance for them to spawn. Also - when they do spawn, they do not aggro you right away, you can get away in time before they turn hostile. 

https://www.wowhead.com/wotlk/quest=868/egg-hunt
https://www.youtube.com/watch?v=jX9wGm27CSc&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&index=7&t=19m35s
https://www.youtube.com/watch?v=jX9wGm27CSc&list=PL49Ga_-r7iKkxrbckm9CkUhWzxqrOnw-n&index=8&t=20m

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
The summons have the default inactivity timer already (2s).

**Comment by Godmatik** [comment]
Got it - but the inactivity timer was not working, they instant aggro upon spawn, will record it next time I level a new character (after the changes are implemented)
