### ISSUE TITLE
Heroic Strike / Cleave bug when cancelled 

### ISSUE THREAD

**Issue by B2SquareOne** [ValorenWoW/sunstrider-core#5322]
If I press HS or Cleave while waiting for my autoattack to go off and cancel it , the next autohit swing still uses HS or Cleave, depends what you pressed and cancelled.

**To Reproduce**
1. Make Warrior and go to Target Dummy
2. Queue and cancel HS/Cleave before your autohit goes off.
3. See that HS/Cleave will be used even if cancelled

**Comment by hotdogsteven** [comment]
https://github.com/SunstriderEmu/BugTracker/assets/136162502/bbc39283-19f8-4f99-b1cf-cc5d10c0560a

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
