### ISSUE TITLE
Wailing Caverns : Deviate Shambler

### ISSUE THREAD

**Issue by Zerkhal** [ValorenWoW/sunstrider-core#5324]
**Describe the bug**
-> Mobs are starting to heal as soon as they take damages when they should only start healing once reaching below 50%.

**Character name**
-> Tonyxo

**To Reproduce**
-> Attack these mobs (cast, melee, etc...)

**ID Creature**
-> Deviate Shambler ID : https://www.wowhead.com/tbc/npc=5761/deviate-shambler

**ID Spell**
-> Spell ID : https://www.wowhead.com/tbc/spell=7948/wild-regeneration

**Expected behavior**
-> They should only start healing once reaching below 50%.

**Screenshots/videos**

![b5eb2a00720518923635ced6e45f3f35](https://github.com/SunstriderEmu/BugTracker/assets/147260221/8989c520-4b4b-4f9d-94f8-7803ba8aaade)

**Comment by blblblaz** [comment]
thanks, fixed with next server update
