### ISSUE TITLE
[Hunter spells] Auto Shot and Multishot Formulas and interactions not working as intended

### ISSUE THREAD

**Issue by Enory** [ValorenWoW/sunstrider-core#5325]
**Describe the bug - resume**

> - Currently Auto shot and multi shot don't deal expected damage
> - Damage shown on character page for autoshot is correct → so formula used is OK
> - But dmg on dummy is lower than expected (maybe same type of issue than for cobra reflexes talent)
> - i have a global 2%-3% dmg reduction on autoshot compared to charcter sheet. multishot and steady shot also suffer from this reduction.
> 
> - Multishot don't take the good % of attack power

Multi shot spell ID 27021 : [https://www.wowhead.com/tbc/spell=27021/multi-shot](url)
Autoshot spell ID 75 : [https://www.wowhead.com/tbc/spell=75/auto-shot](url)

**_All tests have been made without any spec, arpen, or debuff on target_**

**_Auto shot formula : 2 possibilites_**

> weapon dmg + arrow DPS* weapon speed + Ranged attack power * weapon speed / 14
> weapon dmg + weapon speed * ( arrow dps + ranged attack power / 14)

**That gives for my char :**

> Bow damage : 223-336
> Bow speed : 3
> Arrow DPS : 53
> Ranged attack power : 2265
> DMG min = 223 + 3 * ( 53 + 2265/14) = 867
> DMG max = 336 + 3 * ( 53 + 2265/14) = 980

![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/c3df20d5-330f-4287-9bca-03adc7440769)

![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/45e06acb-1f0b-40f1-aa40-1a1837846004)

**Here the results on 0 armor dummy**
![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/ead268f8-1a18-4bd7-af9e-dbd28f32090b)

**damage on sheet 867-981 | damage on dummy  848-958**

As the dmg on charcter page is correct i conclude there is a 2-3% reduction dmg somewhere outside of the basic formula → after i tested other arrows i also found it on multi shot and steady shot.

**Auto shot formula used on endless**

> (weapon dmg + weapon speed * ( arrow dps + ranged attack power / 14)*0.975

I find this 2-3% dmg reduction using damage range of weapons.
My bow currently have a range of 113 dmg (223→336)
But on all my tests with this weap i have only a 110 dmg range
110=113 * 0.97-0.98
![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/42d97e0a-366f-48c2-ac42-afe2a7a9dcc8)
848 →958
The same % dmg reduction apply for all weapons and weapon speed, anyone can test it with the bow u currently use, comparing min and max damage dealt for autoshot, compared to ur character sheet (with no talent and on 0 armor dummies)

**_Multi shot formula   : 3 possibilites_**

> 205 + autoshot damage
> 205 + weapon dmg + arrow DPS* weapon speed + Ranged attack power * weapon speed / 14
> 205 + weapon dmg + weapon speed * ( arrow dps + ranged attack power / 14)

**Multishot formula used on server**

> (205 + weapon dmg + arrow DPS* weapon speed + Ranged attack power * 0.2)*0.975

Even with the 2-3% nerf (0.975 coeff in the formula), this result in an epic buff for fast weapon which normaly take only 10-15%  of attack power
Exemple with the gun available on beta camp which is not even a dps weapon
![image](https://github.com/SunstriderEmu/BugTracker/assets/25368657/10546987-3ccc-4ec5-83f3-7daaafb2ecbe)
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/User/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Rifle of the stoic guardian with 2076 Ranged attack power | normal value | endless value | diff value | diff %
-- | -- | -- | -- | --
dmg min | 707 | 868 | 161 | 122,7%
avg | 759 | 919 | 160 | 121,0%
dmg max | 811 | 970 | 159 | 119,5%

with around 4K attack power in raid, the dmg on multishot on fast weapon can be up to 30% in total with current script.

</body>

</html>

For the steady shot, he is also not using a blizzlike formula, which result in a nerf up to 80 dmg in raid, but as hunters spamming 1 macro button are already overpowered for me it can stay like this.

**Comment by blblblaz** [comment]
Thanks for the detailed issue.  I just found out something very stupid, turns out the "0 Armor" dummy in the BETA zone actually has 246 armor. Will fix that with next update, sorry about that.

![WoWScrnShot_100823_101120](https://github.com/SunstriderEmu/BugTracker/assets/53877162/28c3dbf6-d847-4c4c-a1bd-40f7c28bd554)

I think in the screenshots above you have 0 armor penetration, and the 246 dummy armor adds up to 2.277% reduction, which could explain the difference in damage in Auto Shot atleast.

About Multi-Shot - it is using normalized weapon damage: https://wowwiki-archive.fandom.com/wiki/Normalization?oldid=1563852. So the spell treats every weapon as if it's 2.8 speed, which explains the damage increase when you use a 1.9 speed weapon.

**Comment by Jerrythemagicdog** [comment]
Armor values being incorrect fixed with next update.

**Comment by Enory** [comment]
Ok so i got mistake in my post.

For the multishot it's totaly my bad. I spent too much time on classic and burnt my 2 brain cells left . Multishot is using standardized 20% rap, u are correct and my completely wrong.

For the armor on dummies i also seen something on 7K7 dummies but i didn't make the connection between the dmg loss on 0 armor dummies and incorrects values. → i was just starting to gather data for a 300 negative arpen dedicated post → now it completely make sense XD

If i take the problem backward i found 7K9 armor on the 7700 armor dummy. If u can confirm it or not i take.

So this post can be closed :

> -Multishot is working as expected.
> -autoshot, steady shot, aimed shot and multishot dmg reduction i observed is because dummy didn't get 0 armor

**Comment by Jerrythemagicdog** [comment]
Thanks for getting back to this post, yes all armor was off by the same (246) amount from the expected value.
