### ISSUE TITLE
[QUEST] Protect Kanati Greycloud

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5326]
Looks like credit for quest completion is only tied to one of the three Centaur Assassins that attack him. After defeating only one, the NPC returned to his spot and the quest completed.

Quest completion should be tied to defeating all 3 mobs that arrive.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update (also added the missing pre-path and corrected spawn-in positions for centaurs).
