### ISSUE TITLE
[NPC] Saltstone Crystalhide

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5327]
Saltstone Crystalhide - use ability Mana burn on me even though I had no mana, dealt no damage and had no effect.

As I understand it - mobs that have mana burn like abilities should not use these if the target has no mana. Maybe it was confused because I am a druid - but I was in cat form from start to finish of the encounter.

https://www.wowhead.com/classic/npc=4151/saltstone-crystalhide#abilities

**Comment by blblblaz** [comment]
thanks, fixed with next update.
