### ISSUE TITLE
[NPC] Mordant Grimsby

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5328]
NPC Mordant Grimsby does a very long RP with Jarl every so often.

During this time you can not accept or turn in quests to him, ends up being a bit of a bottleneck. 

**Expected Behavior**
Even while doing his RP, quests should be able to accepted/completed

https://www.wowhead.com/wotlk/npc=23843/mordant-grimsby

https://www.youtube.com/watch?v=9N4CI-9bLjg&t=85s

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
