### ISSUE TITLE
[QUEST] Twilight of the Dawn Runner

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5329]
Quest - Twilight of the Dawn Runner

When speaking to Ithania and giving her option to run, you currently don't get credit until she fully runs out and despawns, so if you die before this happens you don't get any credit.

You should instead get immediate credit after she says her line. Yeah it's nitpicking here but it allows you to do quest without killing all the mobs.

https://www.wowhead.com/wotlk/quest=9437/twilight-of-the-dawn-runner
https://www.youtube.com/watch?v=OMzJsqjzzoE&t=85s

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
