### ISSUE TITLE
[QUEST] Questioning Reethe

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5330]
A couple of issues with this quest

1 - After the RP when Reethe is shot by an arrow, only two of the four mobs became hostile and attacked the Ogre. Two of the skirmishers stayed friendly.

2 - Quest ended and finishing RP began after defeating Lieutenant Caldwell. Should instead end after all four mobs are defeated.

![Skirmishers](https://github.com/SunstriderEmu/BugTracker/assets/37913400/c70f73d1-d599-4c5a-96dc-3dc780fec65c)

https://www.wowhead.com/wotlk/quest=1273/questioning-reethe

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, quest was rewritten, fixed with the next update.
