### ISSUE TITLE
[NPC] Grimtotem Earthbinder

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5331]
**Describe the bug**
Grimtotem Earthbinder appears to be missing his Windfury ability

**Expected behavior**
Should use Windfury

https://www.wowhead.com/wotlk/npc=23595/grimtotem-earthbinder#abilities

**Comment by blblblaz** [comment]
thanks, fixed with next update

**Comment by Godmatik** [comment]
They still don't appear to be using windfury

**Comment by blblblaz** [comment]
should be fixed with next update
