### ISSUE TITLE
[QUEST] Corrosive Prevention

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5332]
**Describe the bug**
Unable to use the "Ooze Buster" on any of the "Corrosive Swamp Oozes" in the area, only works on "Acidic Swamp Ooze" or "Bubbling Swamp Ooze". 

For quest Corrosive Prevention

**Expected behavior**
Should work on all oozes in the area, and should give you credit for the quest as well.

https://www.wowhead.com/wotlk/quest=11174/corrosion-prevention

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Is this a suggestion to make the quest simpler or is this how it's supposed to work?

I see the quest item explicitly mentions "Acidic Swamp Ooze" and "Bubbling Swamp Ooze". 
I took a brief look at some Classic sources and I couldn't find anything about this being usable on Corrosive Swamp Oozes or a player using the item on a Corrosive Swamp Ooze in a video.

**Comment by Godmatik** [comment]
Hello - you are indeed correct.

I think the main issue actually is that the Corrosive Swamp Oozes should not be present at all. It can cause confusion and in looking at a TBC classic video, they aren't there (despite wowhead showing otherwise)

In fact - in reviewing a bit more, I think these mobs were removed after the Dustwallow marsh revamp in TBC

https://www.youtube.com/watch?v=9UafaB6V958&t=120s
Joana video showing they exist

https://www.youtube.com/watch?v=kcuD-REUCl8&t=30s
TBC classic video, none in sight

**Comment by Jerrythemagicdog** [comment]
Nice find!
We'll convert the existing Corrosive Swamp Oozes to Acidic Swamp Oozes / Bubbling Swamp Oozes.
