### ISSUE TITLE
[NPC] Wastewater Bandit

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5333]
Wastewater Bandit - only uses ability "Sinister Strike"

Appears to be missing both backstab and gouge abilities. Also not sure if they should be using Sinister Strike.

https://www.wowhead.com/classic/npc=5618/wastewander-bandit#abilities

**Comment by hotdogsteven** [comment]
https://www.wowhead.com/tbc/npc=5618/wastewander-bandit#abilities
I would assume the gouge only happens if you are more than 1 target.

**Comment by Godmatik** [comment]
If I recall from classic, even if you are alone, they will still cast gouge (and then break the gouge on their next auto)

Will try to find a video.

**Comment by Godmatik** [comment]
Looks like I can't find evidence of them gouging when you are solo, so disregard that portion (if its already present)

**Comment by blblblaz** [comment]
He had both Backstab and Gouge, but the spells listed on wowhead are player spells that cost energy, and he has no energy bar so he could never use them, blizzard probably has the same issue if they use those spells. Removed Sinister Strike from him. He will Gouge and Backstab after next update, thanks.
