### ISSUE TITLE
[QUEST] Stoley's Shipment

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5334]
**Describe the bug**
Quest "Stoley's Shipment" from NPC "Stoley" currently can not be picked up unless you have first completed pre-req quest "Stoley's Debt"

**Expected behavior**
You should be able to pick up "Stoley's Shipment" without having to do the quest before it - it is an optional breadcrumb

![wowheadStoley](https://github.com/SunstriderEmu/BugTracker/assets/37913400/0d0260e7-f3e3-47da-8ff4-0a5e904d7dea)

https://www.wowhead.com/wotlk/quest=2872/stoleys-debt
https://www.wowhead.com/wotlk/quest=2873/stoleys-shipment

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
