### ISSUE TITLE
[Items] Pirate's Footlocker and Captain's Key

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5335]
~~1. Captain's Key has a 100% drop rate from Southsea Swashbuckler - these should only be lootable from Pirate Footlockers~~

~~2. Pirate Footlocker has a very low drop rate chance - request a check to make sure it's correct - only looted 1 after \~50 kills~~

3. Pirate Footlocker should have a chance to give world drops as well (for the appropriate level range) according to the wowhead comments

https://www.wowhead.com/wotlk/item=9249/captains-key#contained-in-item
https://www.wowhead.com/wotlk/item=9276/pirates-footlocker#dropped-by

**Comment by Savageferret** [comment]
I also had the same experience with point 2, ~80 pirate kills and only 2 footlocker drops (and of course the quest item wasn't inside)

**Comment by z5n** [comment]
first two fixed with next restart, need to look into the third a bit more

**Comment by z5n** [comment]
the existing loot table for Pirate's Footlocker appears to be correct already
thanks for the issue!
