### ISSUE TITLE
Objects - Gahz'ridian

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5336]
The quest item "Gahz'ridian Ornament" for quest "Gah'zridian" is super sparse. A lot of the spawns it should be according to wowhead simply don't exist. Only in Southmoon Ruins is it somewhat decent supply.

Compounding this issue is that the respawn rate is fairly slow. I suspect this quest will be difficult if more than one person is attempting to complete it.

https://www.wowhead.com/wotlk/object=140971/gahzridian

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.

There will now be ~110+ spawn points with 3 min respawn time, also added to the dynamic respawn group which will make them respawn faster when there are many players in the area.
