### ISSUE TITLE
[NPC] Brontus

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5337]
Rare elite mob named Brontus - has no green drop when you kill him and no patrol path setup

https://www.wowhead.com/wotlk/npc=5827/brontus

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.

**Comment by Godmatik** [comment]
He patrols now but moves giga fast, way faster than a typical kodo does

**Comment by blblblaz** [comment]
fixed with next update
