### ISSUE TITLE
[NPC Spell] Bloodpetal Poison

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5338]
**Describe the bug**
NPC spell "Bloodpetal Poison" does not leech mana as the spell description describes.

**Expected behavior**
Should leech mana (in addition health) every 3 secs

https://www.wowhead.com/wotlk/spell=14110/bloodpetal-poison

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Can't get this to happen: 
![image](https://github.com/SunstriderEmu/BugTracker/assets/46463908/61a80b63-dc1e-4a5e-91b5-6631620cd40f)

They do not have a mana bar but perhaps that's what you were watching?
(No mana bar on Classic either: https://youtu.be/EFYrWV6UGjQ?t=48)

**Comment by Godmatik** [comment]
Tested again - looks like the mana drain component stops when the mob is dead (but the health damage component does not).
Could be blizzlike

**Comment by Jerrythemagicdog** [comment]
Leech effects stop for us when the caster is dead.
I'll close this now, thanks for testing it again.
