### ISSUE TITLE
[NPC] Mor'vek

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5339]
**Describe the bug**
This NPC Mor'vek exists currently in Un'goro

**Expected behavior**
Should not exist, he was around during vanilla but removed in TBC - not brought back until some during Wrath

![Mor'vek](https://github.com/SunstriderEmu/BugTracker/assets/37913400/a050b9a4-adb1-49ab-99e8-8ec9caed6289)

https://www.wowhead.com/wotlk/npc=11701/morvek#comments

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
