### ISSUE TITLE
[NPC] Frenzied Pterrordax

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5340]
**Describe the bug**
Frenzied Pterrordax currently use the ability "Terrify"

**Expected behavior**
They should not use the ability "Terrify", only the regular Pterrodax use this.

Although this seems wrong (even wowhead has it listed as an ability it's supposed to use) - on classic and original vanilla, you can see the mob never uses such an ability. Also the wowhead comments don't indicate anything about them using a fear either.

https://www.wowhead.com/wotlk/npc=9167/frenzied-pterrordax#comments
https://www.youtube.com/watch?v=Y2MtRLBK3pQ&t=1h57m50s
https://www.youtube.com/watch?v=STBnOaBxzuw&t=70m30s

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, indeed they seem to not have this ability.
Fixed with the next update.
