### ISSUE TITLE
Endless Brawl Buff

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5342]
**Describe the bug**
The "Endless Brawl" buff you have for being PvP flagged is removed when you cross continents or take the portal to/from Outland, but you are still PvP flagged. 

Need to toggle PvP off/on to fix it.

**Expected behavior**
Buff should remain active

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
