### ISSUE TITLE
Mobs in Cave

### ISSUE THREAD

**Issue by JGarciaOrju** [ValorenWoW/sunstrider-core#5343]
Some mobs fall and others fly through the walls on this cave(Fargodeep Mine).

**Character name**
Lumian

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/147370523/d0631f7e-50bc-4bcc-a791-1830c7f68249)

**Comment by blblblaz** [comment]
Thanks, we reworked some pathing stuff yesterday that caused this, we are aware of the issue and are working on a fix.

**Comment by B2SquareOne** [comment]
Also in the tunnel when you leave Gnome/Dwarf starting zone

**Comment by kelno** [comment]
Thanks that's something borked with the last update, fixed with next server restart
