### ISSUE TITLE
[Visual] Mend Pet dispel animation

### ISSUE THREAD

**Issue by Red86** [ValorenWoW/sunstrider-core#5344]
**Describe the bug**
If a hunter has "improved mend pet" talented, each time the spell attempts to dispel a harmful effect on the pet, the dispel animation will be played whether or not there are harmful effects that need to be dispelled.
**Character name**
N/A

**To Reproduce**

1. As a hunter, spend at least 1 point in the improved mend pet 
2. Cast Mend pet

**Expected behavior**
The dispel animation should play only if the skill is actually dispelling a harmful effect on the pet.

**Comment by Enory** [comment]
Hi, for me the animation is displaying correctly, even without any debuff on pet.

For the animation displaying only when it remove a debuff i nerver seen it on sources from tbc.


https://github.com/SunstriderEmu/BugTracker/assets/25368657/e20717f4-391a-4af6-a122-4140653e47a4

**Comment by artieau** [comment]
This is working correctly and Blizzlike even
