### ISSUE TITLE
Netherspite Beams visual bug

### ISSUE THREAD

**Issue by culjoboi** [ValorenWoW/sunstrider-core#5345]
**Describe the bug**
Visual bug:
While fighting Netherspite, beams that are connected to him and not the players (for example when tank steps out of the red beam), are not going to the center of his model, maybe not even to the edge of his hitbox, but they stop even further away from him.

**To Reproduce**
Start the Netherspite fight and watch for where beams animation stop.
Alternatively, person can intersect a beam, and then walk out of it (for example reproducing tank's behavior in red beam), and it should be more clear.

https://www.wowhead.com/tbc/npc=15689/netherspite

**Expected behavior**
Beams should go to the middle of Netherspite's model. (If no one is standing in any beam, they should intersect each other exactly in the middle of the boss' model.

**Screenshots/videos**
Don't have a screenshot, sorry, but this amazing art should explain it good enough.

![NS beam](https://github.com/SunstriderEmu/BugTracker/assets/48360367/0d3247ff-2780-47aa-9248-162a9117a001)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.

This is some of the best art to ever grace our bugtracker!
