### ISSUE TITLE
Netherspite disappearing and reappearing during the fight

### ISSUE THREAD

**Issue by culjoboi** [ValorenWoW/sunstrider-core#5346]
**Describe the bug**
Netherspite's model just disappears for couple of seconds, then appears back for some time, and then it repeats. Happened before the pull, as well as throughout the whole fight. Might be related to issue #5345, as both are visual bugs on same boss.

**To Reproduce**
Engage in combat with Netherspite and pay attention to its model.

https://www.wowhead.com/tbc/npc=15689/netherspite

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
