### ISSUE TITLE
Karazhan - Pathing of mobs in Livery Stables

### ISSUE THREAD

**Issue by culjoboi** [ValorenWoW/sunstrider-core#5348]
**Describe the bug**
In Karazhan, in Livery Stables (on the way to Attumen), pathing of mobs is not working properly - they are walking very buggy by height axis towards the roof of the room and then teleporting next to the players. It feels like if there were invisible walls stopping them from reaching the raid group.

Mobs affected by this behavior:
https://www.wowhead.com/tbc/npc=15547/spectral-charger
https://www.wowhead.com/tbc/npc=15548/spectral-stallion
https://www.wowhead.com/tbc/npc=15551/spectral-stable-hand

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.

We've made some big changes regarding creature movement/navigation recently and Karazhan didn't want to cooperate.
