### ISSUE TITLE
No Collect Quest Tooltip Information

### ISSUE THREAD

**Issue by Aom1232** [ValorenWoW/sunstrider-core#5350]
**Describe the bug**
The tool tip that shows on mobs that drop items for quests does not show.

**Character name**
Markymark

**To Reproduce**

1. Pickup a quest that requires items to be collected.
2. Hover over the mob that will drop the item.
3. You will see no information on the tool tip in the bottom right.

Item: All collect quest items
Quest: All collect quests

**Expected behavior**
On a kill quest it will show you your progress i.e 5/6 in the bottom right corner. The collect quest should do the same.

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/147445616/d379c0d1-e640-4370-a5f5-5cf2bd8991f1)
![image](https://github.com/SunstriderEmu/BugTracker/assets/147445616/003e495f-8bfd-47b0-8d76-03c5f5541280)

**Comment by Jerrythemagicdog** [comment]
These are not explicitly labeled as quest items and as such won't be tracked.

**Comment by Aom1232** [comment]
![image](https://github.com/SunstriderEmu/BugTracker/assets/147445616/b4ec5766-a040-430b-b70c-6253f8529993)
 Showing that the mob doesn't need to drop a quest item.
 
 
![image](https://github.com/SunstriderEmu/BugTracker/assets/147445616/caf3e70c-9c6c-4e62-ac06-325505e79747)
An item specifically marked quest item drops from mob.

**Comment by Jerrythemagicdog** [comment]
Seems like I was wrong and no quest items are displayed by default when mouse-overing a creature on 3.3.5a, sorry!

**Comment by Aom1232** [comment]
> Seems like I was wrong and no quest items are displayed by default when mouse-overing a creature on 3.3.5a, sorry!

No worries at all, just thought it was a tad random is all. Thanks for looking into it.
