### ISSUE TITLE
Crash at certain spot in Hellfire Peninsula

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5351]
Getting a crash at a specific spot in Outland, sorry don't have coords, but see below screenshot for location.

No error number or message - just the client hardlocks and hangs. 

Tried with all addons disabled and cache folder deleted - same result. After several relogs was able to slowly move myself out of it. Went back in and same result occurred.

![crash](https://github.com/SunstriderEmu/BugTracker/assets/37913400/b1013f30-2db8-4f2a-bfb1-8bd89d6aeb82)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we think we've found the underlying problem, a fix will be deployed with the next client update tomorrow.
Keeping this issue open until we can confirm it's resolved.

**Comment by Jerrythemagicdog** [comment]
New client update is live now on the launcher and the alternative client patches download.
Please let us know if this happens to you again, thanks for testing!

**Comment by z5n** [comment]
closing for now, if this issue resurfaces feel free to comment below.
