### ISSUE TITLE
Fel Reaver - Movement too slow

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5353]
**Description:**
Just observe a Fel Reaver - they are moving slower than intended. I also noticed they occasionally stop moving for 20ish seconds during their patrol path - at the least the one I observed was

**Current behaviour:**
See below video of what their speed should be

https://www.youtube.com/watch?v=JpQpK9IPtl4&ab_channel=Adman
https://www.wowhead.com/tbc/npc=18733/fel-reaver

**Comment by blblblaz** [comment]
thanks, fixed with next update
