### ISSUE TITLE
Fel Handler - no patrol paths

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5354]
**Describe the bug**
Fel Handlers are standing in place for the quest "Disrupt the Reinforcements"

**Expected behavior**
Fel Handlers should be patrolling around, none of them have paths setup.

https://www.youtube.com/watch?v=E1i84M1aupY&ab_channel=WoWQuests
https://www.wowhead.com/wotlk/npc=19190/fel-handler

**Comment by blblblaz** [comment]
fixed with next update, thanks
