### ISSUE TITLE
Core/Spells: SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK stacking

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5356]
Power Infusion should be useable on all targets with Heroism/Bloodust, but only the mana cost reduction should count, the haste does not go through.
![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/5ad2841d-4b1f-4bcc-9a70-990a235e9c20)
Currently 1 completely overwrites the other.

https://github.com/TrinityCore/TrinityCore/pull/23592

**Comment by hotdogsteven** [comment]
Current the Priest will lose Bloodlust if casting Power Infusion on self. Does not work on any other target.

Power Infusion should be useable on all targets with Heroism/Bloodust, but only the mana cost reduction should count, the haste does not go through.
![image](https://github.com/SunstriderEmu/BugTracker/assets/136162502/5ad2841d-4b1f-4bcc-9a70-990a235e9c20)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
