### ISSUE TITLE
Mage - Power Infusion stacking with Arcane Power

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5357]
Should not be able to stack both. 

- If mage has Power Infusion on, Arcane Power removes it. 
- If Mage has Arcane Power on, Priest gets "a more powerful spell is in effect" error message.

https://github.com/TrinityCore/TrinityCore/issues/23614
https://wowpedia.fandom.com/wiki/Patch_1.10.2

**Comment by Jerrythemagicdog** [comment]
Fixed with next update.

This seems like a leftover from the times PI used to grant damage/healing increase in Vanilla, doesn't really make much sense as a rule after 2.4.0.
