### ISSUE TITLE
Druid talent "Feral Instinct" - feels very undertuned

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5359]
**Describe the bug**
Tested both with 3/3 and without Feral Instinct talents - the mobs have a very high ability to detect you regardless (tested on mobs of same level), Feral instinct only increases your stealth power very slightly

**Expected behavior**
Feral Instincts talent should increase your stealth by 5 points per talent - up to 15 points when 3/3. That means three levels of stealth rating.

https://www.wowhead.com/wotlk/spell=16949/feral-instinct#comments

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed earlier.
