### ISSUE TITLE
Hunter - PvP Traps Instant Arming

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5360]
#1739 This was set based on a wowwiki comment.

https://www.youtube.com/watch?v=RrYnEah1MTQ&t=142s&ab_channel=ExecutusGaming

https://www.youtube.com/watch?v=RrYnEah1MTQ&t=175s&ab_channel=ExecutusGaming

https://www.youtube.com/watch?v=RrYnEah1MTQ&t=215s&ab_channel=ExecutusGaming

Can find more if needed, this was the first hunter video and the first 3 traps I found.

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/1739
