### ISSUE TITLE
Warrior - Heroic Strike/Cleave & Extra Attacks

### ISSUE THREAD

**Issue by hotdogsteven** [ValorenWoW/sunstrider-core#5361]
Extra swings granted from Sword Specialization & items triggered by off-hand attacks should use any queued up Heroic Strike or Cleave. Currently they only apply a normal white hit.

https://github.com/magey/tbc-warrior/issues/5
https://github.com/TheGroxEmpire/TBC_DPS_Warrior_Sim/issues/33
https://github.com/wowsims/tbc/issues/826

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
