### ISSUE TITLE
Warlock Bug Healthstones

### ISSUE THREAD

**Issue by budgebudge** [ValorenWoW/sunstrider-core#5362]
even though i got healthstones in my inventory already, it lets me cast (and finish the cast) new ones, which does nothing but consume another soulshard. 

it should not be possible to even conjure another one of the same size (keep in mind there are many variants of HSes possible if you skill different levels of it). if u try to conjure one of a bigger/lower hp level it should allow it.

**Comment by z5n** [comment]
are you able to elaborate on this? upon testing, I'm not able to create more than one Healthstone of the same rank.

**Comment by z5n** [comment]
found the issue, will be looked into!

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
