### ISSUE TITLE
Moving nameplates depending on range 

### ISSUE THREAD

**Issue by Qiyazu** [ValorenWoW/sunstrider-core#5363]
Describe the bug
Namplates are moving up or down depending on how close or far away you are . 

Expected behavior
Nameplates should always show in the same position no matter how close / far you are to the target . 

Link : https://www.youtube.com/watch?v=0taKj3q5CFc

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
This is default 3.3.5a behavior, we might change this in the future but definitely not now.
You can modify the anchor point height for now in Interface->Endless->Nameplate height slider
