### ISSUE TITLE
Arzeth the Powerless

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5364]
**Describe the bug**
After using the staff to turn Arzeth into "Azerth the Powerless", he is still hitting for incredibly high damage, much more than a normal level 63 mob should. And still using mortal strike/shadowbolt volley as well

**Expected behavior**
Hit for normal damage once his elite tag is removed from using the quest item

https://www.wowhead.com/tbc/npc=20680/arzeth-the-powerless

**Comment by blblblaz** [comment]
fixed the damage part, but he will still be using his spells in Powerless form, thanks
