### ISSUE TITLE
NPC - Boglash

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5365]
**Describe the bug**
His melee damage is equivalent to an elite mob, which means it is very high

**Expected behavior**
Even though he is classified as an elite, his melee damage should not be so high. Look at the below video, hitting a clothie for only 100 to 150ish

https://www.youtube.com/watch?v=9iktYuGti2Q&ab_channel=WoWQuests
https://www.wowhead.com/wotlk/npc=18281/boglash#comments

**Comment by blblblaz** [comment]
thanks, fixed with next update
