### ISSUE TITLE
NPC - Darkcrest Slaver

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5366]
**Describe the bug**
![slaver](https://github.com/SunstriderEmu/BugTracker/assets/37913400/946a0fe2-abfc-4213-b480-80cdf645e097)

After using this emote nothing happens, even when you are nearby Dreghood Drudge mob

**Expected behavior**
Should call one nearby slave to assist him, who joins the battle. Killing the Darkcrest Slaver then causes the slave to despawn.

**Comment by blblblaz** [comment]
thanks, fixed with next update.

On Classic they evade when the Slaver dies, that's going to be the behavior for us as well.
