### ISSUE TITLE
Hunter - Auto Shot and stopcasting

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#5369]
Auto Shot cant be stopped via a macro while casting a special shot (like Aimed or Steady).
Neither of the following work:
```
/stopcasting
/stopcasting
```
```
/stopcasting
/stopattack
```

**Comment by ghost** [comment]
Basically the problem here is that in order to stop auto-attacking you need to use the macro twice instead of once. This can cause issues if your melee/ranged attack is not on cooldown... pulling prematurely, breaking CC, etc.

edit: this is a general issue, not hunter-specific and not only when casting a special shot.

**Comment by Jerrythemagicdog** [comment]
Thanks for the report, fixed with next client update.
