### ISSUE TITLE
[NPC] Razormane Stalker

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5371]
**Describe the bug**
Their stealth level is much higher than it should be - impossible to detect them before they jump you

**Expected behavior**
Below classic video shows what it should look like

https://www.youtube.com/watch?v=r4cgdk8j_iE&ab_channel=BloodyFoxGaming&t=28s
https://www.wowhead.com/classic/npc=3457/razormane-stalker

**Comment by blblblaz** [comment]
thanks, fixed with next update
