### ISSUE TITLE
Holy partial resists

### ISSUE THREAD

**Issue by Auraj89** [ValorenWoW/sunstrider-core#5373]
**Describe the bug**
I have resists, and partial resists with holy spells

**Character name**
Auraj

**To Reproduce**
use consecration on dummies, as there is no holy resistance in the game, partial resist is not supposed to happen

**Expected behavior**
Holy spells can be missed but not resisted

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/144960387/7c8fff7f-cc65-435d-bed1-9f77b9ba667a)

**Additional context**
It will change a lot if Holy school spells can be resisted, imagine on Hyjal waves.

**Comment by Godmatik** [comment]
partial resist was a thing that existed on classic for holy spells/conc - the logs show it clearly

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Holy resistance exists as a stat in PvE, creatures gain it along with other resistances per level.
![image](https://github.com/SunstriderEmu/BugTracker/assets/46463908/efd247fa-a19a-4f78-ae3a-c731e914ef08)

**Comment by hotdogsteven** [comment]
https://youtu.be/h0mJI_oXFnU?t=398
full explanation, showing multiple full resists and partials.  Per level resistance includes Holy and can not be by-passed.
