### ISSUE TITLE
[QUEST] Load Lightening

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5374]
**Describe the bug**
Drop rate of Hollow Vulture Bone for quest Load Lightening is less than 100%

**Expected behavior**
Should be 100%

![100](https://github.com/SunstriderEmu/BugTracker/assets/37913400/39bb9c9f-ad20-4023-8452-7a5b1217dc65)
https://www.wowhead.com/wotlk/quest=1176/load-lightening

**Comment by z5n** [comment]
while the drop rate shouldn't be 100%, the intended rate is near-100%
the rate for one of the creatures it drops from was off by ~5% on our server, so that'll be adjusted with the next restart.
thanks for the issue!

**Comment by Godmatik** [comment]
Every single wowhead comment states 100%, even if the wowhead drop rate table doesn't agree (sometimes it's off because I believe it includes drop rates of those who do not have quest), on classic I experienced similar behavior.

The issue is that there are limited birds in the zone, will create an even bigger bottleneck if its not 100%

**Comment by z5n** [comment]
good points, also tested on classic and it does seem to be 100%, will change soon!
