### ISSUE TITLE
Empty Mail

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5375]
**Describe the bug**
I keep getting mail from "myself" as I level, which is just a blank letter. Well suffice to say I didn't send any mail.

![Mail](https://github.com/SunstriderEmu/BugTracker/assets/37913400/034114ca-d902-4602-a3f6-2e2a098c6780)

**Expected behavior**
Don't receive mail from myself

**Comment by kelno** [comment]
Dev: druid mail template id 116 & 114 for example don't show up in client?
Our template handling seems to be wrong for TLK client.

**Comment by kelno** [comment]
Fixed with next update
