### ISSUE TITLE
Decrepit Darkhound has double the HP amount

### ISSUE THREAD

**Issue by culjoboi** [ValorenWoW/sunstrider-core#5378]
**Describe the bug**
Just a short report here, not much info is needed.
Decrepit Darkhound mobs in Tirisfal Glades have double the HP amount. Around 200-260 instead of 100-130.

https://www.wowhead.com/tbc/npc=1547/decrepit-darkhound

**Comment by blblblaz** [comment]
thanks, fixed with next update
