### ISSUE TITLE
[Core] Can't logout while on flight path

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5381]
**Current behaviour**:
Unable to log out while on flight path, gives error "You can't logout now". 

**Expected behaviour**: 
Should provide instant logout similar to being in rested area - logging back in resumes your flight path where you left off - works this way on retail and classic

**Comment by z5n** [comment]
are you able to give any additional info? upon testing logout appears to be instant already

**Comment by z5n** [comment]
unable to reproduce
