### ISSUE TITLE
[NPC] Moonstalker Runt

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5382]
**Describe the bug**
Moonstalker runts are level 16-17, which sucks for lowbies first entering the zone that run into them.

**Expected behavior**
They should be level 10-11
Only the runts that patrol with Moonstalker Matriarch are level 16-17

https://www.wowhead.com/classic/npc=2070/moonstalker-runt#comments

**Comment by z5n** [comment]
thanks, fixed with next restart
