### ISSUE TITLE
[QUEST] Apprentice's Duties

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5383]
**Describe the bug**
Drop rate of Giant Crocolisk Skin is less than 100% for quest Apprentice's Duties

**Expected behavior**
Should be 100%

https://www.wowhead.com/tbc/quest=471/apprentices-duties#comments;40

![100%](https://github.com/SunstriderEmu/BugTracker/assets/37913400/5457d876-26ea-4b44-994f-b0f90738489c)

**Comment by z5n** [comment]
fixed with next restart
