### ISSUE TITLE
Eagle Eye, Far Sight

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#5385]
**Describe the bug**
Exploring beyond caster's view distance doesnt work. No NPCs/objects, and after a couple "jumps", no terrain.

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by artieau** [comment]
Was this tested in the Beta camp area or somewhere else?

If in the Beta camp area, do you get the same results if you test this in another zone completely?

**Comment by ghost** [comment]
Yes, from the beta camp to Zangarmarsh. The issue seems to occur when you explore in another zone.

**Comment by artieau** [comment]
The Beta camp is a special place, not a normal zone. So unexpected results may occur.

Can you try to use the spells again after you teleport somewhere else in the world? Perhaps use the Camp Manager to visit Shattrath and try from there?

**Comment by ghost** [comment]
I did try Stormwind to Duskwood yday, same issue.

**Comment by z5n** [comment]
eagle eye doesn't work from zone to zone, works that way on classic as well
