### ISSUE TITLE
Melee Auto Swing Timer Reset

### ISSUE THREAD

**Issue by Mammothsa** [ValorenWoW/sunstrider-core#5387]
**Describe the bug**

Melee auto swing timer on weakaura resets once a steady shot is shot.
**Character name**

Mammoth, but basically every hunter
**To Reproduce**

1. Melee hit the mob
2. Cast a steady shot

**Expected behavior**

_The Melee swing timer doesn't reset and works appropriately by showing when the next auto attack will come._
**Screenshots/videos**

https://gyazo.com/06c9c84c8a98447f2d72bd1a77f7b209
**Additional context**

I've tested this with the 2.4.3 weakaura package and surprisingly it did work, however, every other weakaura broke.
Also, The WA that I'm using: https://wago.io/1Ey7jjqBg

**Comment by kelno** [comment]
Probably the addon just following the TLK rule here, swing resets are not sent by the server but deduced by the addons

**Comment by Mammothsa** [comment]
Greetings again,

I'm sorry for the late response, but I would like to ask if any fix or adjustment exists that could somehow fix the swing bar. I am asking because I would like to try and melee weave on some situations such as Magtheridon and later some bosses in T5 and T6, however, without a swing timer I can only adjust my rotation to the raptor strike timer, which is not as efficient.  @kelno
