### ISSUE TITLE
[NPC] Bluegill Murloc

### ISSUE THREAD

**Issue by Godmatik** [ValorenWoW/sunstrider-core#5388]
**Describe the bug**
These creatures currently are able to full block melee attacks

**Expected behavior**
They don't have shields, so not sure how that should be possible

https://www.wowhead.com/classic/npc=1024/bluegill-murloc

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Funnily enough, it seems to gain 10 block value from its base strength right now.
I'm not sure whether creatures can gain block value from strength and if so at what ratio, we'll look into it!

**Comment by Godmatik** [comment]
Got it - as far as I am aware anyway, that block value should not exist unless the mob physically has a shield equipped

**Comment by Jerrythemagicdog** [comment]
Removed block value gained from Strength until the exact formula is known
