### ISSUE TITLE
Ritual of Summoning broken?

### ISSUE THREAD

**Issue by nmagane** [ValorenWoW/sunstrider-core#5389]
**Describe the bug**
Summon does not go through after channel ends.
Tried with 2 different warlocks and 3 different recepients.
Warlocks were always inside Karazhan instance, targets both inside and outside did not receive summons.

**Character name**
Warlocks: Gallufptr, Shamwow
Summon recepients: Tink (Outside raid), Beli (Inside raid), Enory (Inside raid).

**To Reproduce**

1. Cast ritual of summoning in raid group and channel with other players

**Comment by Jerrythemagicdog** [comment]
Fixed with the update a few hours ago, thanks!
