### ISSUE TITLE
quest bug [The Exorcism of Colonel Jules]

### ISSUE THREAD

**Issue by PTzabu** [ValorenWoW/sunstrider-core#5390]
this [The Exorcism of Colonel Jules] its bugged, you can do it, says "complede"  in "your" quest log. nothing more that i can say
 thanks

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
You need to talk to Colonel Jules after completing the event to get the credit.
This is consistent with Classic: https://youtu.be/kxFUl3MazFM?t=255
