### ISSUE TITLE
Chain effects do not chain behind LoS

### ISSUE THREAD

**Issue by Aeded** [ValorenWoW/sunstrider-core#5391]
**Describe the bug**
When main target of your chain spell is in line with second targets, which are not in direct line of sight to you, your chain spell only hits main target and does not chain to the secondary target (bug)

**To Reproduce**

https://streamable.com/3cgh16

Spell: https://wowhead.com?spell=25442
Spell: https://wowhead.com?spell=27021

**Expected behavior**
When main target of your chain spell is in line with second targets, which themself is not in direct line of sight to you, your chain spell should still hit the second targets. 

**Screenshots/videos**
https://www.youtube.com/watch?v=dKx0KsCNBH4#t=452
https://www.youtube.com/watch?v=VhCI3DDvGGU&t=733s
Could link also classic clips

**Additional context**
This has been reported for like 3rd time, if this is a custom change please atleast acknowledge it somewhere as a custom change.

**Comment by ghost** [comment]
https://www.youtube.com/watch?v=m8nOaNMHZIQ&t=334s

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Our stance remains the same on this, spells searching for chain targets will not search out of LoS of the caster.
That's keeping it in line with the "no hitting through pillars" that's always been the case on our realms.

**Comment by Aeded** [comment]
@Jerrythemagicdog with that logic in mind, the channeled spells should also break once target is out of LoS no?

**Comment by Jerrythemagicdog** [comment]
Sounds similar, but not the same thing though!

**Comment by Aeded** [comment]
That is very interesting and unique approach to class balance! @Jerrythemagicdog
