### ISSUE TITLE
[Hallow's End] Missing model

### ISSUE THREAD

**Issue by artieau** [ValorenWoW/sunstrider-core#5392]
**Describe the bug**
When eating the Hallow's End Pumpkin Treat (20557), one of the possible results is gaining aura (24926).
The model relating to this is missing and the player is invisible.

**To Reproduce**

1. Use Hallow's End Pumpkin Treat (20557)
2. Roll the Swashbuckler from aura (24926)
3. Be invisible man

**Expected behavior**
Should look like a Swashbuckler
https://www.wowhead.com/tbc/spell=24926/hallows-end-candy

rev. 36156

**Comment by z5n** [comment]
fixed with next restart, thanks for the issue rt
