### ISSUE TITLE
Netherspite red beam very inconsistent and weird.

### ISSUE THREAD

**Issue by nmagane** [ValorenWoW/sunstrider-core#5393]
**Describe the bug**
Netherspite red beam is very inconsistent.
 A lot of the time it did not heal me (the tank) up to full HP when receiving stacks, and some times the HP loss math makes me end up on exactly 1 HP (happened 5+ times). 

In addition, the Boss itself does not seem to be attacking properly. 
Combat log shows "Dodged", Details shows nothing, boss isn't even swinging visibly, but I ended up taking mystery physical damage.

**Character name**
Jilsen

**To Reproduce**
1. Move in and out of Netherspite red beam

**Expected behavior**
Red Beam should heal tank.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!

For the first one: https://github.com/SunstriderEmu/BugTracker/issues/5347
For the lack of animation when auto-attacking: https://github.com/SunstriderEmu/BugTracker/issues/5252

Does this seem consistent with what you've experienced?

**Comment by nmagane** [comment]
> Thanks for the issue!
> 
> For the first one: #5347 For the lack of animation when auto-attacking: #5252
> 
> Does this seem consistent with what you've experienced?

The first issue makes sense, will have to try turning off the cvar next time (on live servers). 
What effects would this cvar have on the rest of the game if it's turned off permanently?

The second one does not make sense because I am not keyboard turning and the issue is _the boss,_ not _me._
The boss' attacks do not show visually or register anywhere (combat log/details), neither does he swing. This wasn't just me either - everyone in the raid saw the same thing on their logs.
This happened while standing still and while strafing on the beam.
I understand that it could be happening because of the boss turning as I strafe, but this also results in combat logging breaking down?

**Comment by kelno** [comment]
Should be fixed now
