### ISSUE TITLE
Mage - Molten Armor triggers clearcasting

### ISSUE THREAD

**Issue by Vegancow** [ValorenWoW/sunstrider-core#5394]
**Describe the bug**
Sometimes when casting molten armor it also triggers clearcasting. This shouldn't be the case since molten armor is not a damage spell. Clearcasting should only be triggered on damaging an enemy. 

**Character name**
Vegan

**To Reproduce**
Simply spam Molten Armor and you should get a 30% crit increase

**Screenshots/videos**
https://www.youtube.com/watch?v=qSGQFjkrOJM

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
