### ISSUE TITLE
[The underbog] Fish in the water are still alive after killing Ghaz'an

### ISSUE THREAD

**Issue by Vegancow** [ValorenWoW/sunstrider-core#5395]
**Describe the bug**
To my knowledge, the fish in the water should die after you kill Ghaz'an. However, they were still alive. Can this be checked? 

**To Reproduce**
Kill Ghaz'an and then jump from the platform. 

![WoWScrnShot_101823_181030](https://github.com/SunstriderEmu/BugTracker/assets/73107622/a7b7a6cc-e36b-45c0-a21d-e70d286717d3)
![WoWScrnShot_101823_181039](https://github.com/SunstriderEmu/BugTracker/assets/73107622/7a9fa4f0-c648-4926-97fa-3715019448cb)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
