### ISSUE TITLE
RDF cooldown does not work 

### ISSUE THREAD

**Issue by Vegancow** [ValorenWoW/sunstrider-core#5397]
**Describe the bug**
I was away while dungeon finder group was ready and didn't accept. I got a cooldown but I was still able to queue regardless. 

**Character name**
Vegan

**To Reproduce**
Join dungeon finder, don't accept when it pops, get cooldown - you're still able to queue 

![WoWScrnShot_101923_125511](https://github.com/SunstriderEmu/BugTracker/assets/73107622/091254ca-161f-4858-b7af-56bbd96eb8aa)

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
