### ISSUE TITLE
Seal of Righteousness does not scale correctly with the spell power you have. should be MUCH higher. 

### ISSUE THREAD

**Issue by beastmodd** [ValorenWoW/sunstrider-core#5400]

**Comment by beastmodd** [comment]
i have 900 spell damage and my SOR is swinging for 200.... this is way way way off. it's supposed to be close to 80 percent spell damage carry over to SOR damage. if i have 1000 spell damage my SOR should be hitting for 800 not 200.

**Comment by hotdogsteven** [comment]
Seal of Rightouesness scales with weapon speed as well as spell power, not just spell power only. 

https://wowpedia.fandom.com/wiki/Seal_of_Righteousness?oldid=1432433

**Comment by beastmodd** [comment]
Fair enough. I honestly remember playing shockadin and doing a LOT more
damage though. I still feel like I'm not hitting as hard as I should be
with 900 spell damage.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, this is invalid.
