### ISSUE TITLE
RDF getting stuck on ready check, must relog to clear 

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5402]
**Describe the bug**
Sometimes when the ready check happens and I accept rdf, the group gets stuck on the ready check. I have had it happen where all 5 players hit yes and show 5 green checkmarks, but the group is never created, I'm never ported into dungeon, and I cannot leave queue. 

I just had it happen again where 2 dps did not accept, and now I am just stuck on the ready check that has been up for 5+ minutes. I cannot leave queue. Relogging however does fix it and get rid of it. 

I don't know what causes it or how to reproduce exactly. 

https://i.imgur.com/da3QeWq.png

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
