### ISSUE TITLE
Bug RDF

### ISSUE THREAD

**Issue by BelSz** [ValorenWoW/sunstrider-core#5403]
**Describe the bug**

No Teleport or Accpet gruop
**Character name**

Aluneth
. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

![image](https://github.com/SunstriderEmu/BugTracker/assets/148580866/cbc92094-6a38-48b3-b7c7-070c5b9befae)

**Additional context**

**Comment by z5n** [comment]
any steps to reproduce? @BelSz

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update (tomorrow morning server time).
