### ISSUE TITLE
Celebras in mara does not spawn his ghost to turn in quest

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5405]
**Describe the bug**
After killing celebras, he should turn into his ghost as celebras the redeemed. You should be able to turn in legends of maraudon to him, and then grab the next quest where you get the scepter of celebras. He did not spawn in as his ghost when killed.

https://www.wowhead.com/tbc/quest=7044/legends-of-maraudon
https://www.wowhead.com/tbc/quest=7046/the-scepter-of-celebras

**Comment by reetarded** [comment]
Well GM spawned him in for me and the turn in worked and the quest after did as well, but wasn't able to test how multiple people trying to do it in a row would go since I was solo.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
