### ISSUE TITLE
Mobs ignore slow effect when fleeing call backup

### ISSUE THREAD

**Issue by Aeded** [ValorenWoW/sunstrider-core#5406]
**Describe the bug**
When mob starts to flee towards other mob for help due to low health, it ignores slow effect and keeps moving with same speed

**Character name**

**To Reproduce**

1. Get mob low hp close to another
2. Starts fleeing towards another mob
3. Ignores slow

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
Slow effects should not be ignored

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Do you happen to remember which creature you've seen this with?
The random creature I am trying with respects the slow.

**Comment by z5n** [comment]
@Aeded ^

**Comment by kelno** [comment]
Fixed with next server update. Fleeing creatures usually get 66% of their base speed and can be slowed down further depending on their health and debuffs.
