### ISSUE TITLE
Gnomeragan Grubbis event NPC attacking party members

### ISSUE THREAD

**Issue by Raademar** [ValorenWoW/sunstrider-core#5407]
**Describe the bug**
Mixed group of Alliance and Horde players doing Grubbis event before the boss arrives causes NPC to attach Horde player that is in the group.

**Character name**
Should happen for everyone.

**To Reproduce**
Start the event with mixed faction group. Horde players will be attacked by NPC at the end of the current event phase.

**Expected behavior**
No players in the group should be attacked by the NPC

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/24412744/c3487594-7982-4dfc-937c-88da0c5935bd)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
