### ISSUE TITLE
Warrior rage deficiency

### ISSUE THREAD

**Issue by tupurs** [ValorenWoW/sunstrider-core#5408]
**Describe the bug**

Warrior is producing rage from couple of sources: Attacking and receiving damage.
I dont know if this is a setting or the client but it feels like the rage production from both sources is very low,
Literaly you can feel there is a rage starvation, not enough rage while attacking as dps or receiving damage as tank, the struggle is real, i asked all warriors in my guild and they all confirmed it feels like there is rage starvation/production, most of them responed with the same answer " I've never been to 100 rage since i started", and we have wide range of warrior levels from low to level 70.
Mostly is noticable when we ninjapull several groups and i use aoe taunt, even thou i get smacked hard, near death situation several times with healer spamming me, the rage hardly goes up.

**Character name**

Drangheta

**To Reproduce**

I can just say that rage production should be increased slightly, we tested the server with t6 gear and it was hard to tell, but now while leveling its more vissible.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
We've verified rage calculation works as expected.
