### ISSUE TITLE
Flight Form Fall Damage

### ISSUE THREAD

**Issue by Savageferret** [ValorenWoW/sunstrider-core#5409]
**Describe the bug**
Druid's flight form doesn't negate fall damage

**To Reproduce**
1. Fly high, then cancel flight form, fall for a good distance
2. Before hitting ground, activate flight form again
3.  Cancel flight form, touch ground, take more fall damage than you should

**Comment by nmagane** [comment]
This also occurs when flying from high distance into a no-fly/indoors zone. You take damage based on when you started the flight not when you were when cancelling form.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with an update that's already live.
