### ISSUE TITLE
Felguards fall through ramp before last boss in BF

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5410]
**Describe the bug**
As title states, when you pull the felguards up the ramp on the way to the last boss in blood furnace, they constantly clip under the ramp. Has happened all 3 bf runs I've done.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Could you provide a video of this happening if possible?
I can't get this to happen when pulling them on the ramp and running them down back and forth.

**Comment by reetarded** [comment]
I'll try to get a clip next time I run it

**Comment by z5n** [comment]
@reetarded any update?

**Comment by z5n** [comment]
cant reproduce
