### ISSUE TITLE
[Quest] Cave Mushrooms - Player name is not replaced in chat message

### ISSUE THREAD

**Issue by lilskidoo** [ValorenWoW/sunstrider-core#5411]
**Describe the bug**
After accepting the quest [Cave Mushrooms](https://www.wowhead.com/tbc/quest=947/cave-mushrooms), the giver [Barithras Moonshade](https://www.wowhead.com/tbc/npc=3583/barithras-moonshade) sends a few chat messages, the first of which is:
"Thank you $n. And luck to you."
It looks like the token `$n` fails to be replaced by the player's name.

**Character name**
Joy

**To Reproduce**

1. Accept the quest [Cave Mushrooms](https://www.wowhead.com/tbc/quest=947/cave-mushrooms).
2. Observe the issue in the chat window

**Expected behavior**
The token `$n` should be replaced with the player's name.

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/141071375/fafbd975-2343-4e6f-addf-65887d725a02)

**Additional context**
N/A

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
