### ISSUE TITLE
[Quest] WANTED: Murkdeep cannot be started

### ISSUE THREAD

**Issue by lilskidoo** [ValorenWoW/sunstrider-core#5412]
**Describe the bug**
The quest [WANTED: Murkdeep](https://www.wowhead.com/tbc/quest=4740/wanted-murkdeep) is usually started from a [wanted board game object](https://www.wowhead.com/tbc/object=175320/wanted-murkdeep) in Auberdine. However, the object cannot be interacted with despite the level requirement for the quest (9) being met.

**Character name**
Joy

**To Reproduce**

1. Go to Auberdine on a level 9 or above character.
2. Try to interact with the wanted board.
3. Realise that you cannot.

Object: [WANTED: Murkdeep!](https://www.wowhead.com/tbc/object=175320/wanted-murkdeep)
Quest: [WANTED: Murkdeep!](https://www.wowhead.com/tbc/quest=4740/wanted-murkdeep)

**Expected behavior**
The board should provide the quest starting at level 9.

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/141071375/5a053986-e1fd-47b2-a990-6b96b923e6f6)

**Additional context**
N/A

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the minimum level requirement was indeed wrong.
Fixed with the next update!
