### ISSUE TITLE
Out of Combat Mana Regen

### ISSUE THREAD

**Issue by tocmruise** [ValorenWoW/sunstrider-core#5415]
OOC mana regen is incredibly slow (20 mp tick). I am guessing this is bugged.

**Comment by kelno** [comment]
Thanks for reporting.
Will need a bit more details for those kind of issues, we ran through those numbers a few times already.

**Comment by tocmruise** [comment]
https://streamable.com/w43vio
here is a clip. Maybe it's correct, but it seems to suddenly take ages.
