### ISSUE TITLE
Can't learn Appearance for Spellfire Longsword Main-Hand

### ISSUE THREAD

**Issue by Zythris** [ValorenWoW/sunstrider-core#5417]
Unable to learn the appearance for the Spellfire Longsword Main-Hand for when I am trying to switch a One-hand sword's appearance

Screenshot for exact item.
![image](https://github.com/SunstriderEmu/BugTracker/assets/148729532/8adf5d30-b1fc-4357-b3d2-1d667d3dba40)
--------
As seen here i haven't learned it after multiple equips.
![image](https://github.com/SunstriderEmu/BugTracker/assets/148729532/8c3530cc-9068-44e5-9a63-182c70b94fca)

If this is intended then disregard, but.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we're looking into your case as there's no reason it shouldn't be added to your collection.

**Comment by kelno** [comment]
Thanks, should work since the server update now.

**Comment by Zythris** [comment]
Sadly this is mistaken.
![image](https://github.com/SunstriderEmu/BugTracker/assets/148729532/22c15659-2a4a-495f-810f-b24a16dfdddd)

the new error i am currently receiving trying to learn it's appearance.

(note, it's soul-bound and has been since i first attempted to learn it's appearance, this is giving me the same error on the gun down below)

![image](https://github.com/SunstriderEmu/BugTracker/assets/148729532/21fe24d4-3189-4b83-a106-1155b76934a1)
