### ISSUE TITLE
Gnomish Mind Control Cap not working

### ISSUE THREAD

**Issue by LSD7** [ValorenWoW/sunstrider-core#5420]
**Describe the bug**
When you use https://www.wowhead.com/classic/item=10726/gnomish-mind-control-cap on player nothing happens

**Character name**
Kenjee

**To Reproduce**

1. Equip https://www.wowhead.com/classic/item=10726/gnomish-mind-control-cap
2. Find opposite fraction player
3. Use https://www.wowhead.com/classic/item=10726/gnomish-mind-control-cap

Item: [https://wowhead.com?item=](https://www.wowhead.com/classic/item=10726/gnomish-mind-control-cap)
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
You control the player

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Are you testing on a level 70 target?
The item has an "Increased chance of failure when used against targets over level 60."

**Comment by LSD7** [comment]
yep i was trying to use it twice. First one target was under 60 lvl and second one target was above 60 and in both cases i got same result.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, works correctly against lower level targets.
