### ISSUE TITLE
Black Moras - Aeonus cleave

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5423]
Describe the bug
Currently, Aeonus does 360 degrees cleave. Melees die even if they stand on his tail.

Character name
N/A

To Reproduce
Go to Black Moras and fight last boss with people positioned on his tail.

Expected behavior
He should do frontal cleave, like any other Cleave in the game.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
