### ISSUE TITLE
Blood Furnace - reputation gains are very low

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5424]
Describe the bug:
Blood Furnace, whole dungeon in normal mode, gives like 200-300 rep instead of much more.
Big Fel guards give 5 rep instead of 25 rep.
Imps give 0, instead of 1.
Normal mobs humanoids give 1, instead of 5.

Character name
N/A

To Reproduce
Go to Blood Furnace, normal, kill mobs.

Expected behavior
Mobs should give more rep.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
