### ISSUE TITLE
Hellfire Peninsula - Gan'arg Servant draining energy

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5425]
Describe the bug
In north Hellfire Peninsula, Gan'arg Servant are mobs that can be found in the Legion camps. Currently, if they are fighting a class with energy (eg: Rogue, Feral Druid-Cat), they will sometimes drain energy. This can result in 50-60 energy drain per mob kill.

Character name
N/A

To Reproduce
Go fight Gan'arg Servant as a Rogue or Cat Druid.

Expected behavior
They should not drain energy.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
This is correct based on the spell's effects. 
Is there video proof showing they do not burn energy?
Tooltips are often copy-pasted between spells and are not the best source of information as to how a spell works.
