### ISSUE TITLE
Chest does not disappear when content is looted from it

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5426]
Describe the bug
If a player loots a chest (I found this specifically in Mana Tombs and Shadow Labs), the chest will remain spawned and can be opened again even if the whole chest is emptied already.

Character name
N/A

To Reproduce
Go to MT or SL and find a chest, ,loot it, and watch it NOT disappear.

Expected behavior
Chest should disappear when all content from it has been looted.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Can't get it to happen, is it you looting the chest yourself or someone in your party or in the distance looting it?

**Comment by z5n** [comment]
@sasadubi ^

**Comment by sasadubi** [comment]
@Jerrythemagicdog It was me as a rogue opening it via pick lock, getting all loot, and then i can see it again and open it, but its empty.

**Comment by z5n** [comment]
unable to reproduce
