### ISSUE TITLE
Mage Rift Lord in Black Moras is immune to all interrupts

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5427]
Describe the bug
There is a type of Rift Lord in Black Morass that's a mage. It can cast Pyroblast on random target / Blastwave / Frostbolt and Polymorph.
None of these spells are interrupt-able. (Blast wave is instant, so that one doesn't count, but yeah, others are not, we tried Counter spell, kick, Earth Shock)

Character name
N/A

To Reproduce
Go to Black Moras, wait for Rift lord of type Mage to spawn, try to interrupt.

Expected behavior
We should be able to interrupt his spells.

**Comment by Godmatik** [comment]
It's intended

https://www.wowhead.com/tbc/npc=21104/rift-keeper#comments;mode:normal

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, but this is indeed invalid.
We've made some adjustments to that particular type of Rift Keeper though, he should be more in line with the rest of his Rift Keepers now.
