### ISSUE TITLE
[Netherstorm] Warp Aberrations storms do not despawn 

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5428]
**Describe the bug**
Doing the quest Elemental Power Extraction in netherstorm, and killing the Warp Aberrations. Their warp storm they cast is supposed to despawn when the mob dies, instead it remains where it casted for at least a minute or more.

TBC classic footage:
https://www.youtube.com/watch?v=GVHzJFH_Awo

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
