### ISSUE TITLE
Cannot get a new chrono-beacon in black morass after leaving dungeon

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5431]
**Describe the bug**
Has happened in 4/5 of my bm runs I have done so far. Rdf pops and someone teleports out to repair or buy a reagent or something and when they come back they cannot get another chrono beacon. I am used to being able to get another chrono beacon when reentering, but I don't have any classic footage and didn't play classic so I am unsure on the interaction.

Is there any way to allow us to grab new chrono beacons until the actual portal encounter is started, and then remove the option to get a new chrono beacon?

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
