### ISSUE TITLE
Client won't run

### ISSUE THREAD

**Issue by Oskru** [ValorenWoW/sunstrider-core#5433]
**Describe the bug**
After patch downloading failure the client won't open and re-download the patch. Can't download game patch / client from the endless.gg website, as the anchor link navigates to the GitHub issues. I saw people on Discord having simillar problem. Client won't start. Happened to me at 17:15 on Tuesday, 24.10.2023.

**Character name**
Kivia (not related anyways)

**To Reproduce**

1. Try to download 24.10.2023 game patch by endless launcher with a failure error.
2. Open endless launcher.

**Expected behavior**
Patch downloads successfully and client works as usual or endless client fails to download the patch and re-downloads the patch on the 2nd client run, patch downloads successfully and client opens without error window.

**Screenshots/videos**
Error window:
![image](https://github.com/SunstriderEmu/BugTracker/assets/78699146/e7332dab-70c9-42d9-bff2-84c4026331c2)

**Additional context**
It might be related to the patch being half-way downloaded, as the patch failed downloading for me. Can't open the game from the `Wow.exe` file, as after logging in it throws an error `Update your game using Endless launcher.`.

**Comment by Oskru** [comment]
I think that it's up to close according to the Discord annoucement on `status-updates` channel. Going to try now.

**Comment by Oskru** [comment]
I think that it's to close according to the Discord annoucement on `status-updates` channel. Going to try now.

**Comment by z5n** [comment]
thanks for the issue, actually very detailed
