### ISSUE TITLE
can't open the launcher

### ISSUE THREAD

**Issue by alirezaaks** [ValorenWoW/sunstrider-core#5434]
Hello
When I try to open the launcher, it gives this error, what should I do to solve this problem?
![Untitled](https://github.com/SunstriderEmu/BugTracker/assets/60824811/ce90b2f0-82c3-49dc-859f-6954ec621464)

**Comment by alirezaaks** [comment]
I also changed Windows, but it didn't help
![IMG-20231021-WA0010](https://github.com/SunstriderEmu/BugTracker/assets/60824811/ce13200e-1158-444f-80c5-d926c0eee5b0)

**Comment by z5n** [comment]
win7/8 not supported, need to install manually
https://endless.gg/getstarted
