### ISSUE TITLE
Alchemy reroll Specialization bugged

### ISSUE THREAD

**Issue by LSD7** [ValorenWoW/sunstrider-core#5435]
**Describe the bug**
I have unlearned potion master ( i paid 150g)  and when i wanted to get Transmute spec then i got error that i don't enough money. So it looks like NPC wanted to get 150g more.

**Character name**
Future

**To Reproduce**
1. Take potion master
2. Unlearn potion master
3.  Try to take transmut master

https://www.wowhead.com/tbc/guide/alchemy-profession-burning-crusade-classic

**Expected behavior**
I should pay only once and then get other spec free.

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/31816578/2eed0aca-10c5-4efc-95d7-496bc3e06933)
![image](https://github.com/SunstriderEmu/BugTracker/assets/31816578/16751621-3827-4e09-98d2-e9b9d8c12f65)

**Additional context**

**Comment by LSD7** [comment]
oh looks like just reroll doesn't work. Because he says not enough money when i click twice

**Comment by LSD7** [comment]
it costs 20g now, but should free i guess

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, we'll remove the cost!
