### ISSUE TITLE
Paladin Seal Twisting NOT working as it should.

### ISSUE THREAD

**Issue by armand-carapetru** [ValorenWoW/sunstrider-core#5436]
![WoWScrnShot_102523_140309](https://github.com/SunstriderEmu/BugTracker/assets/55349351/970e78bb-a236-4544-8b75-708c473f7951)

What is going on here ? let me tell you .
I have twisted Seal of Command into Seal of Righteousness . What happens?
I have 81 dmg from auto attack , 146 dmg from seal of command proc and 29 dmg from seal of righteousness .
And this is NOT how it should work 
----------------------------------------------------------------------------------------------------------------------------
Let me explain to your very clearly what should be happening .
I attack with command and i seal twist with Righteousness , if the proc happens i should be getting:

Damage from Auto attack , Damage from Command proc , and now Seal of Righteousness shoult proc TWICE;

One instance of Righteous damage from the auto attack and another instance of Righteous damage from the Command proc itself. 

Yes , seal of command should count as an auto attack aswell. Same goes for Seal of Blood . 

This is how it should work . This is how it worked back in the days in retail , this is how it work even in TBC classic when blizzard acknowledged this as a thing , hell even stormforged managed to make it work like that . Endless seem to have a track record of fucking up this particular paladin trick it seems .
I very much wanna see this server succeed so
Seriously,
Get it to work correctly.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Please make sure there isn't an open issue already when opening a new one: https://github.com/SunstriderEmu/BugTracker/issues/5302

The issue will be resolved soon!
