### ISSUE TITLE
Lightning shield internal cooldown not working as intended when recasting the spell

### ISSUE THREAD

**Issue by gogogo98** [ValorenWoW/sunstrider-core#5437]
**Describe the bug**

Lightning shield should have internal cd between procs of about 3 seconds. 
This is the case when the spell is present, but it's not the case after recasting lightning shield.

Example:
If you have 1 charge left of lightning shield and the mob hits you, the charge goes of. Then if you imidiately recast lightning shield, another charge goes of imidiately (Withouth waiting 3 seconds), resulting in non-blizlike behaviour and "burst" of 2 charges going off in a shorter time window then 3 seconds.
This was not how lightning shield worked. 
Last charge should proc internal cd for another lightning shield that is recasted after the first one. 
The recasted shield should "remember" when the last proc went off and take it into account.

**Character name**
Grejp

**To Reproduce**
Test against fast hitting mob or player. After last charge of LS is expanded, recast LS imidiately and see how the charge goes off again, withouth taking into account internal cd of 3 sec.

**Expected behavior**
Last charge should proc internal cd for another lightning shield that is recasted after the first one. 
The recasted shield should "remember" when the last proc went off and take it into account.

**Comment by gogogo98** [comment]
This is also true for water shield and earth shield procs

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
