### ISSUE TITLE
"The Outcast's Plight" quest for Lower City and feathers gives wrong reward

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5439]
Describe the bug
The quest called "The Outcast's Plight" gived by NPC named Vekax, gives a bag as reward for initial quest and every next completion of 30 Arakkoa feathers. This bag called "Outcast's Cache" right now gave me x1 Super Healing Potion. Nothing else.

Character name
N/A

To Reproduce
Complete the quest.

Expected behavior
On all other servers it was always x2 greenies in that Outcast's Cache bag.

**Comment by z5n** [comment]
updated loot table, applied with next update
