### ISSUE TITLE
Fel Iron Chest gives x2 Runecloth

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5440]
Describe the bug
Fel Iron Chest in open world should've give way more loot.

Character name
N/A

To Reproduce
Open the fel iron chest, does not need lockpicking.

Expected behavior
This should give fel iron ores, mote of fire, items sometimes, etc.

**Comment by z5n** [comment]
unable to reproduce this. with how the loot table for this chest is configured right now, at least 1 green is guaranteed every time.
i'm not sure how you were only able to get x2 Runecloth. that isn't in this object's loot table in the first place

**Comment by sasadubi** [comment]
I wish I screenshoted, it, only 2 runecloth.
Okay, thanks
