### ISSUE TITLE
Vorsha the Lasher bug on quest

### ISSUE THREAD

**Issue by satias** [ValorenWoW/sunstrider-core#5441]
**Describe the bug**
When we reach the place to defend the npc, after the first wave of mobs the npc started running in the air back to the camp.
After this wave ended no more waves appear.
After a few minutes i went back to "Zoram'gar Outpost" and the npc was there.
Went to do another quest in ashenvale and when i went back to "Zoram'gar Outpost" i noticed that the quest was completed and not failed.

**Character name**
Satarina

**To Reproduce**

1. Escorted the npc
2. Killed mobs on the way
3. Killed the first wave of mobs

Quest: https://www.wowhead.com/classic/quest=6641/vorsha-the-lasher

**Expected behavior**

This quest is an escort + defend
https://www.youtube.com/watch?v=Hua5mdj0vT0

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
