### ISSUE TITLE
Sethekk Halls - Talon King Ikiss pulling all mobs in previous room when pulled

### ISSUE THREAD

**Issue by Andwhatx** [ValorenWoW/sunstrider-core#5443]
Issue:

In Sethekk Halls, when the last boss (Talon King Ikiss) is pulled, all mobs behind him and the prior room aggro. 

Expected behaviour:

When Talon King Ikiss is pulled, the pack behind him should not be put into combat and aggroed. This would allow SH last boss stealth runs. This behaviour would therefore be in line with Endless 1, Endless 2, and TBC classic.

**Comment by Andwhatx** [comment]
Hi any update on this :)?

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
