### ISSUE TITLE
Outlands Bugs List So Far

### ISSUE THREAD

**Issue by Thealbida** [ValorenWoW/sunstrider-core#5444]
1. Unyielding Knight runs away in fear when low on health despite being undead.
2. Helboars in Hellfire Peninsula have an aggro range further than normal (presumably unintended?).

No name needed.

Bugs
1. Get Unyielding Knight's health low.
2. Test Helboar aggro range.

IDs
1. Unyielding Knight ID: 16906
2. Starving Helboar ID: 16879

What Was Expected
1. Unyielding Knight to not run away when health is low.
2. Helboars of Hellfire Peninsula to have normal aggro range.

**Comment by hotdogsteven** [comment]
2 is working properly. "Starving" animals all have higher than normal aggro ranges.

**Comment by Thealbida** [comment]
Okay, makes sense. As long as it's intended!

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, Unyielding Knight is supposed to do a call for help rather than free for assistance.
Fixed with next update.
