### ISSUE TITLE
Bleed effects on bosses

### ISSUE THREAD

**Issue by Dilson82** [ValorenWoW/sunstrider-core#5445]
Bosses seem to be immune to bleed effects, Garrote and Rupture when used on bosses, even humanoid ones results in no application of the bleed and an immune message

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Could you provide some examples of the bosses you've had this issue with?

**Comment by Lazanah** [comment]
I have had the same issue with Lacerate (https://www.wowhead.com/tbc/spell=33745/lacerate) on Ramparts normal. I believe all 3 bosses were immunue but I can't recall for certain apart from Nazan (the dragon) was definitely immune to Lacerate bleed.
ETA: Normal mobs and world elites still get lacerate stacks.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
