### ISSUE TITLE
WSG 25min timer doesn't work

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5447]
Describe the bug
When we join wsg, it says it has 25min timer, which is a decider how long the BG can last the max.
![timeRemaining](https://github.com/SunstriderEmu/BugTracker/assets/49869412/52bd08ac-6a1b-42e8-b09c-852b61a6b8f3)

Character name
N/A

To Reproduce
Join wsg.

Expected behavior
After 25min, the BG should close, and winner would be team that has more captured flags, or if its 1-1 in flags, but one of teams has flag in their possession carrying it, then that team should win.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
