### ISSUE TITLE
2 items missing compared to release announcement

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5448]
Describe the bug
Battlemaster trinket and Epic Medalion are still not available.
By definition of a bug in software world, this is a bug, because the initial communicated requirement to the community was that these items would be available since day 1.
![ReleaseItems](https://github.com/SunstriderEmu/BugTracker/assets/49869412/d709ef7b-9611-4369-99e3-6a0ac70e1254)

Character name
N/A

To Reproduce
Go visit PVP vendors.

Expected behavior
Both items should be available on release.

P.S. People are unaware of epic medallion, I've seen many ppl with blue pvp trinket that costs 8k. There will be disappointment when the new trinket releases with 25 resilience more, with just 2k more honor in price.

**Comment by z5n** [comment]
these items (both horde and alliance versions) are indeed at their respective vendors in-game
