### ISSUE TITLE
Warriors taking fall damage while charging/intercepting. (Might be the case for Druid charge aswell)

### ISSUE THREAD

**Issue by Fossyyxd** [ValorenWoW/sunstrider-core#5449]
**Describe the bug**
Yesterday i jumped off a cliff in a cave and charged a mob mid air and still took fall damage when i reached the bottom. 

**Character name**
Fossmeister

**To Reproduce**
1. Cast Charge / Intercept on Mob after jumping off a high place that makes you take fall damage. 
2. 
3. 

Spell : https://www.wowhead.com/classic/spell=100/charge / https://www.wowhead.com/classic/spell=20616/intercept

**Expected behavior**
In any version of wow i have played the charge / intercept ability negates any fall damage since it stops you mid air and takes the momentum of the jump.

**Screenshots/videos**
Screenshot of my Log after charging a mob mid air and taking fall damage should be attached. i can also send a video for proof but its too big for GitHub

**Additional context**

![Proof of fall damage after charge screen](https://github.com/SunstriderEmu/BugTracker/assets/149152124/80c97aab-6b09-4d41-9b81-5c47085d8cc9)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update!
