### ISSUE TITLE
Netherwing egg wrong spawn

### ISSUE THREAD

**Issue by LSD7** [ValorenWoW/sunstrider-core#5452]
**Describe the bug**
Bad repsawn timing or wrong count of spawned netherwing eggs.

**To Reproduce**
1. Go to Netherwing Ledge or Dragonmaw Fortress
2.  You can find only 1-3 eggs

https://www.wowhead.com/tbc/object=185915/netherwing-egg#comments

**Expected behavior**
Usually there are around 10 eggs and they spawned every 40-60 minutes.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
