### ISSUE TITLE
Taking Battleground buff in Arathi Basin causes Rogue to leave Stealth

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5454]
Describe the bug
As a Rogue in Arathi Basin battleground, when I'm in stealth, and I take a berserk buff for example, it causes me to leave Stealth.

Character name
N/A

To Reproduce
Play Rogue, play AB, get the berserker buff

Expected behavior
Rogue should not leave Stealth while taking this buff.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
