### ISSUE TITLE
Crashes in Zangarmarsh

### ISSUE THREAD

**Issue by aherhsrtdbsdfhujwrts** [ValorenWoW/sunstrider-core#5455]
**Describe the bug**
I repeatedly crashed 3 times in 15 minutes in SE Zangarmarsh, Umbrafen Villlage. Twice while mounted, another time in combat.

**Character name**
Uzzaji

**To Reproduce**

1. Just be in this area i think
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
No crash

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/149196356/74533033-0d2b-4e40-9cc8-dc115af3ad16)

**Additional context**

**Comment by z5n** [comment]
turn off XPerl PartyPet addon
