### ISSUE TITLE
Spirit Healer in BGs sometimes not rezzing

### ISSUE THREAD

**Issue by Deephx** [ValorenWoW/sunstrider-core#5456]
**Describe the bug**
The spirit healer in BGs is sometimes not rezzing.

**Character name**
Athelstan

**To Reproduce**

1. die in BG and wait for the rezz

**Expected behavior**
Spirit healer should rezz every 30secs

**Screenshots/videos**

**Additional context**

**Comment by kelno** [comment]
Can't reproduce
