### ISSUE TITLE
 [An Apexis Relic] quest bugged

### ISSUE THREAD

**Issue by budgebudge** [ValorenWoW/sunstrider-core#5457]
this is the quest in blades edge where you have to click some colored buttons on the ground, the problem is sometimes they just are unclickable. idk why.

super annyoing

**Comment by budgebudge** [comment]
it appears to happen only on the buttons north of shatari skyguard camp. havent tested all locations

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
