### ISSUE TITLE
Haggard War Veteran

### ISSUE THREAD

**Issue by Jeskyll** [ValorenWoW/sunstrider-core#5458]
So I've been running around all over Shattrath trying to find the Haggard War Veteran NPC who starts the chain for the Khadgar servant escort. I was able to /tar him for a moment, before I lost him again. Presumably somebody had started the escort? I've looked on wowhead to see where he can be and I cannot find him whatsoever. Has anyone encountered this issue?

UPDATE: I just saw multiple people by Khadgar with his servant, yet I still cannot find the Haggard War Veteran in any of the places where he's supposed to be.

UPDATE 2: Found him, he's on the **north** bridge rather than the **east** bridge, where it says he is on wowhead.

**Comment by Godmatik** [comment]
https://www.wowhead.com/wotlk/npc=19684/haggard-war-veteran#map

According to wowhead he has several spawn locations
