### ISSUE TITLE
issue with Block Value

### ISSUE THREAD

**Issue by Milox23** [ValorenWoW/sunstrider-core#5459]
**Describe the bug**
Block Value (BV) from strength is not added to the total BV, or the tooltip for strength stat is bugged.

**Character name**
Mayus

**To Reproduce**

1. BV from strength for my toon should be 18
2. shield BV is 9
3. total BV shown in block stat tooltip is 10

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

If the tooltip is broken, BV from strength should be +1 for my toon. If the addition of BV from strength to total BV is broken, then total BV should be 27.

**Screenshots/videos**

![BV_str](https://github.com/SunstriderEmu/BugTracker/assets/149245865/bdb45d97-0634-4094-90dd-a1096ff1edea)
![BV_shield](https://github.com/SunstriderEmu/BugTracker/assets/149245865/bdd6d8c4-bc74-4c15-b08c-b0f795c192c8)
![BV_total](https://github.com/SunstriderEmu/BugTracker/assets/149245865/8622e7c3-381a-4a5e-a347-51110ef5be35)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The value displayed is wrong, you should be gaining 1 Block Value per 20 Strength with a penalty of 1, so you're currently correctly gaining 1 Block Value.
We'll correct the tooltip in a future client update.
