### ISSUE TITLE
[Halaa] Bombs do not work

### ISSUE THREAD

**Issue by MorbidMike** [ValorenWoW/sunstrider-core#5460]
**Describe the bug**
The bombs provided by the flying camps at Halaa (as the attacking faction) do not work. They are supposed to place a DoT on anything that gets hit that burns for 1% of maximum hp per second. At the moment the bombs do nothing at all.
This breaks Halaa. The guards have more than 1 million HP each and are pretty much unkillable without a raid group if the bombs do not work.

**To Reproduce**
1. Be on the Halaa attacking faction in Nagrand
2.  Capture one of the wyvern camps
3.  Use a wyvern camp and fly
4.  Cast one of the bombs (provided when you use the camp) on a Halaa guard

Item: [https://wowhead.com?item=](https://www.wowhead.com/item=24538/fire-bomb)

**Expected behavior**
The bombs are supposed to do a small AoE fire damage on any hostile units they hit AND apply a fire DoT on every target that was hit.

This is a very annoying bug because some important items are sold in Halaa (such as the Mystic Dawnstone resilience gem recipe). Halaa is owned by Alliance at the moment so Horde players are simply not able to get any items sold in Halaa.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
