### ISSUE TITLE
Druid's Swift flying quest not in game?

### ISSUE THREAD

**Issue by cyjanobenzen** [ValorenWoW/sunstrider-core#5462]
i've try to start my swift flying quest chain on multiple ways, but it turns out its not in game yes (?)

druid named Smiless

allow players who obtained 300 ridding skill talk to Logonr in Moonglade and pick up the quest.

NPC: https://www.wowhead.com/tbc/npc=12042/loganaar
Quest: https://www.wowhead.com/tbc/guide/druid-swift-flight-form-guide-burning-crusade-classic

i expect this to work in few days ;-; pretty please

have a nice day! thank you for your help!

**Comment by z5n** [comment]
fixed with next update
