### ISSUE TITLE
Cannot take a mage portal when a mage takes it

### ISSUE THREAD

**Issue by reetarded** [ValorenWoW/sunstrider-core#5463]
**Describe the bug**
Cannot take a portal that a mage puts downs and takes. For example at the end of a dungeon, the mage puts a portal to shattrath and takes it himself, anyone left in the dungeon cannot click and take the portal. It is a common 3.3.5 server issue and I've seen need to be fixed on various 3.3.5 client servers.

**Comment by z5n** [comment]
when testing this i'm unable to get this issue to happen, do you have any specific steps to reproduce?

**Comment by kelno** [comment]
@z5n In your test did the mage actually teleport to another map id?

**Comment by z5n** [comment]
@kelno yep

**Comment by reetarded** [comment]
> when testing this i'm unable to get this issue to happen, do you have any specific steps to reproduce?

No not really, it happened in mana tombs at last boss for me when I made this report. The portal is just uninteractable after the mage took it, can't mouse over it.

**Comment by Godmatik** [comment]
Did the mage leave group?

**Comment by reetarded** [comment]
no mage still in group

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
