### ISSUE TITLE
Swift Flight Form Quest Chain Doesn't Currently Exist

### ISSUE THREAD

**Issue by Nikrotip** [ValorenWoW/sunstrider-core#5464]
**Description**: 

On lauch it was said that Swift Flight Form quest chain for druids would be available right away. 

I spent 5,000 gold on Saturday, October 28th and learned the riding skill of 300. Then I teleported to Moonglade (Nighthaven) to talk to the quest giver but he had no quests. Disappointing, since it was my primary goal: to gather money and learn the form quick to play the game more efficient. Instead, I had to spend extra money for the mount and have this 3 sec cast time, while I assume all the other classes have full benefits of their class' quests. 

**Character name**
Shaikorth

**Expected behavior**
The quest chain should be available and working. 

**Screenshots/videos**
![WoWScrnShot_102923_170034](https://github.com/SunstriderEmu/BugTracker/assets/48246079/071abbf4-991c-4ea7-bd82-899cbaa08b52)

**Comment by z5n** [comment]
fixed with next update
