### ISSUE TITLE
Hunter talent Thrill of the Hunt don't interacting with Multi-Shot

### ISSUE THREAD

**Issue by arcwizard** [ValorenWoW/sunstrider-core#5466]
Talent [Thrill of the Hunt](https://tbc.wowhead.com/spell=34497/thrill-of-the-hunt) don't interract with [Multi-Shot](https://tbc.wowhead.com/spell=27021/multi-shot) at all, i mean talent don't give mana when Multi-Shot do critically hits.
![Screen](https://user-images.githubusercontent.com/43764742/158777915-4dba3afb-96ef-4730-a5bf-d64051fb62bb.jpg)
**Character name**
Blackgun

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Take 3/3 talent Thrill of the Hunt.
2. Attacks on the dummy until Multi-Shot fires a critical shot. 
3. Check combat log.

**Expected behavior**
If character have 3/3 talents of Thrill of the Hunt, then everytime when Multi-Shot do critically hit it should back 40% of mana cost Multi-Shot. If there less then 3/3 talents of Thrill of the Hunt, then there should be some chance of mana back.

**Additional context**
P.S. Thrill of the Hunt work properly with Arcane Shot and Steady Shot (maybe you can find a solution there).

**Comment by kelno** [comment]
Thank you, fixed with next restart
