### ISSUE TITLE
Quest Bug "Adyen the Lightwarden"

### ISSUE THREAD

**Issue by Opa4ku** [ValorenWoW/sunstrider-core#5467]
**Describe the bug**

**Character name**
Character on which the issue occurred, if applicable.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Can't end a quest "Marks of Kil'jaeden". I get 10 items for quest and come back to "Adyen".  In the course of the quest menu Adyen does not work. Also, there is no quest sign above it
2. Leto
3. Adyen the Lightwarden

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=10325/marks-of-kiljaeden
Spell: https://wowhead.com?spell=

**Expected behavior**

**Additional context**
![1](https://user-images.githubusercontent.com/75784358/164927780-eede7715-d1f0-4c8e-a66e-a0669f4ce9a1.jpg)

**Comment by z5n** [comment]
In order to interact with this NPC (and do the quest), you must be at least neutral with The Aldor. Your character is currently unfriendly.

**Comment by Opa4ku** [comment]
You're wrong
