### ISSUE TITLE
Quest - [Taming the Beast] is awarding wrong XP

### ISSUE THREAD

**Issue by MahoneTBC** [ValorenWoW/sunstrider-core#5468]
The quest [Taming the Beast] is currently only awarding 40xp instead of 840 base-xp (according to: https://tbc.wowhead.com/quest=6062/taming-the-beast)

Here's a screenshot of the granted XP:
![grafik](https://user-images.githubusercontent.com/101602143/158263561-2b91450b-ff4b-4eba-9c63-c45ecb7b766e.png)

**Comment by GM-Morsrael** [comment]
Durotar Version @ Level 10 w/ exp rates on. 
Exp values are written Rewarded vs Base

The Hunter's Path=6068 giving 5exp not 90
Taming the Beast=6062 giving 40exp not 840
Taming the Beast=6083 giving 40exp not 840
Taming the Beast=6082 giving 40exp not 840
Training the Beast=6081 giving 20exp not 420

Base Exp values gathered from https://tbc.wowhead.com/quest=6068/the-hunters-path

Hunters on our server automatically learn all taming spells at 10
