### ISSUE TITLE
Mana Tombs: Pandemonius and Shaffar should pull their room with them

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#5470]
Pandemonius and Shaffar are not linked to all mobs in their respective rooms.

**Comment by kelno** [comment]
Should those guys pull the whole room with them when pulled?

**Comment by ghost** [comment]
from [wowpedia](https://wowpedia.fandom.com/wiki/Mana-Tombs?oldid=1576711):
"Pandemonius is linked to all mobs in his room. Everything inside the room must be cleared."
"Shaffar is linked to all mobs in his room. Everything past the stairs must be cleared."

on classic they are linked and from what i can see in the videos from 2008, they always clear these two rooms entirely

**Comment by kelno** [comment]
Thanks
