### ISSUE TITLE
Search More Hovels quest

### ISSUE THREAD

**Issue by aja318** [ValorenWoW/sunstrider-core#5471]
**Describe the bug**
Object Half-buried Barrel is missing, this item is needed to finish Search More Hovels quest and start last quest in chain Return the Statuette

**Character name**
Elor

**To Reproduce**
Approach location where object should be (coordinates 13,9 34.9).

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://tbc.wowhead.com/object=259/half-buried-barrel
Quest: https://tbc.wowhead.com/quest=285/search-more-hovels
Quest: https://tbc.wowhead.com/quest=286/return-the-statuette

**Expected behavior**
Object should be present to finish Search More Hovels quest and then start Return the Statuette.

**Comment by kelno** [comment]
Thanks for reporting. It's there but not clickable.
