### ISSUE TITLE
Quest:More Spore Sacs gives 8 reputation at Unfriendly

### ISSUE THREAD

**Issue by Zenomorph001** [ValorenWoW/sunstrider-core#5473]
This repeatable quest should give 750 (some sources say 250) of reputation from the beginning (not mentioning any custom server boosts), but gives only 8 (eight)

**Zenomorph**
Character on which the issue occurred, if applicable.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Be sure to be low in reputation with Sporeggar (unfriendly)
2. Gather 10 Mature Spore Sacs
3. Give them to Fahssn in western Zangarmarsh.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://tbc.wowhead.com/item=24290/mature-spore-sac
Quest: https://tbc.wowhead.com/quest=9742/more-spore-sacs

**Additional context**
The same issue with Quest: More Tendrills! https://tbc.wowhead.com/quest=9744/more-tendrils

**Comment by kelno** [comment]
Thanks, fixed with next restart (probably today)
