### ISSUE TITLE
Dark Iron Legacy Quest Item Not Dropping

### ISSUE THREAD

**Issue by Zomrizubo** [ValorenWoW/sunstrider-core#5474]
**Describe the bug**
Fineous Darkvire should drop a quest item called Ironfel. It has a 100% drop rate, but the item never drops.

**Character name**
Restobeam

**To Reproduce**
Quest item Ironfel doesnt drop after Npc is dead. Quest cant be finished.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Npc: https://tbc-twinhead.twinstar.cz/?npc=9056
Item: https://tbc-twinhead.twinstar.cz/?item=10999
Quest: https://tbc-twinhead.twinstar.cz/?quest=3802
Object: https://tbc-twinhead.twinstar.cz/?object=164689

**Expected behavior**
Slay Fineous Darkvire and recover the great hammer, Ironfel. Take Ironfel to the Shrine of Thaurissan and place it on the statue of Franclorn Forgewright.

You start the quest as a spirit. You have to enter BRD and kill Fineous Darkvire <Chief Architect> for Ironfel. After you obtain Ironfel you talk to the Monument of Franclorn Forgewright in BRD and obtain the Shadowforge Key (BRD Key).

**Additional context**
I can provide a screenshot if needed. I killed the Npc 5 times already and still no Ironfel.

**Comment by z5n** [comment]
SunstriderEmu/BugTracker#5476

**Comment by z5n** [comment]
fixed in SunstriderEmu/BugTracker#5476
