### ISSUE TITLE
A Boaring Time for Grulloc

### ISSUE THREAD

**Issue by z5n** [ValorenWoW/sunstrider-core#5475]
**Describe the bug**
Grulloc is not running after the Huffer.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Get quest [A Boaring Time for Grulloc](https://tbc-twinhead.twinstar.cz/?quest=10721)
2. Go to Grulloc
3. Use [Huffer's Whistle](https://tbc-twinhead.twinstar.cz/?item=31350)

**Expected behavior**
Grulloc should run after the Huffer.

"Grulloc inhabits a place known as the Cursed Hollow. When you get there, let Huffer loose. The gronn will have a fine time chasing him around, and you will retrieve the bag that he guards and deliver it to Baron Sablemane." - https://tbc-twinhead.twinstar.cz/?quest=10721

**Comment by kelno** [comment]
Fixed with next server update
