### ISSUE TITLE
crusader enchant not working correctly

### ISSUE THREAD

**Issue by hellothere123222** [ValorenWoW/sunstrider-core#5478]
**Describe the bug**

Crusader enchant gives too much strength at level 70

**Character name**
Character on which the issue occurred, if applicable.

Nevermore

**To Reproduce**
Steps to reproduce the behavior. The more details the better!

1. put crusader enchant on both weapons while dual wielding
2. attack something 

https://tbc.wowhead.com/spell=20034/enchant-weapon-crusader#comments
https://tbc.wowhead.com/spell=20007/holy-strength#comments

**Expected behavior**

Chance on hit (%) = weapon speed * 1.82
Strength and healing should decrease each level past 60 by a certain amount.
If dual wielding each enchant should be able to proc and stack.

**Additional context**

[2008/04/01](https://tbc.wowhead.com/spell=20034/enchant-weapon-crusader#comments:id=8283:reply=29818) (Patch 2.4.1)
After seeing some scepticism about whether Crusader still stacks, I decided to confirm it. This screenshot was taken post-2.4.0.

2007/10/31 (Patch 2.2.3) |   |  
I've tested Crusader on a <a href="https://tbc.wowhead.com/?item=28430">Lionheart Executioner
Crusader proc is 60 str at level 70 (120 AP for Warriors and Paladins).

The "Holy Strength" buff will say 100 strength but is suppose to give 60 strength at 70. If you look at character sheet it gives full 100.

**Comment by kelno** [comment]
Thanks

**Comment by kelno** [comment]
Fixed with next server update

**Comment by hellothere123222** [comment]
You're very welcome. Thank you and the team for all you do.
