### ISSUE TITLE
Succubus minion threat not linked.

### ISSUE THREAD

**Issue by dlloyd1** [ValorenWoW/sunstrider-core#5479]
On the beach of the "Wild Shore" in Stranglethorn Vale, Bloodsail Warlocks that have a Succubus minion aggro separately from their minion. Those with an Imp minion have their aggro linked correctly.
You can kill the Bloodsail Warlock without the Succubus minion ever having aggroed, eventually, it will despawn.

**Comment by kelno** [comment]
Thanks for reporting
