### ISSUE TITLE
Chain Lightning cooldown

### ISSUE THREAD

**Issue by z5n** [ValorenWoW/sunstrider-core#5480]
**Describe the bug**
Chain Lightning has cooldown despite not successfully casting the spell

**Character name**
Character on which the issue occurred, if applicable.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Cast Lightning Bolt (perhaps any spell that has a cast time? Healing Wave works too)
2. Spam Chain Lightning *mid Lightning Bolt cast*
3. Once Chain Lightning begins casting, move your character to cancel the spell
You'll see that Chain Lightning is on cooldown despite having never successfully casted the spell

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
https://tbc-twinhead.twinstar.cz/?spell=25449
https://tbc-twinhead.twinstar.cz/?spell=25396
https://tbc-twinhead.twinstar.cz/?spell=25442

**Expected behavior**
If Chain Lightning was never successfully casted, there should not be a cooldown.

**Additional context**
[video](https://i.imgur.com/9KrKS3G.mp4)

**Comment by kelno** [comment]
I can't reproduce this 
(+ If this was true, we would see it on every spell, chain ligthning doesn't have anything special there.)

**Comment by kelno** [comment]
Fixed with next restart
