### ISSUE TITLE
Demon Forged Breastplade does not scale with SP

### ISSUE THREAD

**Issue by Maskyoftruth** [ValorenWoW/sunstrider-core#5483]
**Describe the bug**
Demon Forged Breastplate does not scale with SP currently.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
link to item listing and wowhead link.
https://tbcdb.com/?item=12628
https://www.wowhead.com/item=12628/demon-forged-breastplate#comments

**Expected behavior**
Sometimes when struck by a mob a Life Steal effect would proc onto the mob that struck the character draining X amount of health from it(modified by SP)

**Additional context**
A related link 
https://www.reddit.com/r/classicwowtbc/comments/n5px4f/beta_fix_spell_power_coefficients_have_been_fixed/

**Comment by kelno** [comment]
Fixed with next update

**Comment by kelno** [comment]
Current coef is 26%. That's 4/15, the default value for a dot of 4s, like described here: https://wowwiki-archive.fandom.com/wiki/Spell_power#Spell_coefficients
