### ISSUE TITLE
Wailing Caverns: Mutanus the Devourer waves 

### ISSUE THREAD

**Issue by mizmar** [ValorenWoW/sunstrider-core#5484]
**Describe the bug**
In Wailing Caverns dungeon during the final event of the boss *Mutanus the Devourer* - the waves of mobs and the boss itself spawned  in very quick succession (near instantly).

**Expected behavior**
Waves and boss should spawn on timer.

**Additional context**
I asked in guild and one other group experienced this as well; few other groups did not.

Found similar bug report for endless.gg: https://github.com/SunstriderEmu/BugTracker/issues/2738

**Comment by kelno** [comment]
Thanks. Vanilla dungeons need a big overhaul.

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
