### ISSUE TITLE
(From Ticket) Quest=10808 doesn't work as intended

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-core#5485]
ticket: "For the quest Thwart the Dark Conclave I am not receiving credit for killing he Dark Conscale Ritualist but completed the summoning ritual portion by jumping into the lava you can't cast it from the shore. I relogged, did the summoning ritual distruption killed another respawn of Ritualist's but it didnt help."

Morsrael: "Quest=10808 doesn't work as intended (kill guards, cast disruption spell=38482 anywhere) but you can actually disrupt it without killing the guards by either going into the middle of the lava or off to the left of the area by the leftmost ritualist. "

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.

**Comment by kelno** [comment]
You're welcome
