### ISSUE TITLE
Firs Aid bug (Heavy mageweave bandage)

### ISSUE THREAD

**Issue by Varelmind** [ValorenWoW/sunstrider-core#5488]
Hey there,

It's me, Lvr. I'm writing this post to let you know that currently you cannot get the heavy mageweave bandage training from Doctor Gregory Victor in Hammerfall. Right after you complete the quest "Triage", you have to grind 15 more points so that you get to 240 and get the training, but for some reason the instruction window is not popping up and he just talks to you.

Hope this helps and this get sorted out as soon as possible.

Thank you very much

**Comment by kelno** [comment]
Thanks for reporting

**Comment by WannaBetWannaBet** [comment]
will be fixed soon?
 i`m also stuck at 240

**Comment by kelno** [comment]
You should be able to learn it at other first aid trainers in capital cities.

**Comment by kelno** [comment]
Fixed with next update
