### ISSUE TITLE
Mudfin Frenzy not giving XP

### ISSUE THREAD

**Issue by Twisty575** [ValorenWoW/sunstrider-core#5491]
**Describe the bug**
Mudfin Frenzy fish mobs in zangarmarsh dont give XP.
common to grind on these for unidentified plant parts for honoured rep before doing quests but they dont seem to be giving XP they should , although its less XP cos they die easy.

**Character name**
Ashigaru

**To Reproduce**
killed many

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
https://tbc.wowhead.com/npc=18212/mudfin-frenzy#comments

**Expected behavior**
Fix mob to give XP

**Comment by kelno** [comment]
Thanks for reporting, fixed with next server update
