### ISSUE TITLE
Arcane Missiles/Arcane Blast issue

### ISSUE THREAD

**Issue by jongstump** [ValorenWoW/sunstrider-core#5492]
**Describe the bug**
If a mage has the Arcane Blast debuff and then casts Arcane Missiles, the debuff is removed upon completion of the cast, even if there is more time remaining (3 sec. should remain if AM is cast immediately after Arcane Blast).

**Character name**
Adeon

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Load Mage
2. Cast Arcane Blast
3. Cast Arcane Missiles
4. Note - the debuff gets removed with Arcane Missiles

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 

Spell: https://tbc.wowhead.com/spell=30451/arcane-blast
Spell: https://tbc.wowhead.com/spell=38704/arcane-missiles

**Expected behavior**
The debuff should continue, after the cast of Arcane Missiles, for it's entire 8 second duration.

**Additional context**

https://user-images.githubusercontent.com/1925019/193375866-ff6881d2-765c-4560-a712-9802a29b51d2.MOV

**Comment by kelno** [comment]
Thanks, fixed with next server update

**Comment by jongstump** [comment]
Awesome, thank you!
