### ISSUE TITLE
Return to Onu quest

### ISSUE THREAD

**Issue by aja318** [ValorenWoW/sunstrider-core#5493]
After completing The Twilight Camp quest Twilight Tome does not start Return to Onu quest.

**Character name**
Elor.

**To Reproduce**
1. Finish The Twilight Camp quest
2. Interact with Twilight Tome in Master's Glaive.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://tbc.wowhead.com/object=12666/twilight-tome
Quest: https://tbc.wowhead.com/quest=950/return-to-onu

**Expected behavior**
When finishing The Twilight Camp quest interacting with Twilight Tome should allow starting Return to Onu quest

**Comment by kelno** [comment]
Thanks fixed with next restart
