### ISSUE TITLE
Nightbane changes Phase1 to Phase2

### ISSUE THREAD

**Issue by Virsaitis** [ValorenWoW/sunstrider-core#5494]
**Description**
During phase changes from phase 1 to phase 2 in TBC, Nightbane was change a little bit. The biggest change which was gatekeeping many people from killing it was **removed magical immunity from skeletons and reduced damage from breath attack in flight**. Changes were completed month before introducing SSC and TK, so people could attune for T5 content and progress further.
These changes were not implemented before or during transition to Phase 2 on Sunstrider.

NPC - NIGHTBANE https://tbc.wowhead.com/npc=17225/nightbane
1. Damage of these spells not reduced -  Smoking Blast https://tbc.wowhead.com/spell=30128/smoking-blast - https://tbc.wowhead.com/spell=30127/searing-cinders#triggered-by
2. Smoking blast triggers Searing Cinders on the player which can stack up to 4 stacks on the player.

NPC - Restless Skeleton https://tbc.wowhead.com/npc=17261/restless-skeleton
1. Immune to non holy damage

**Expected behavior**
If we are in Phase 2 which was introduced in patch 2.1.0, Nightbane should do less damage when he is in the air phase and Restells Skaletons should no longer be immune to all spell damage, which is the biggest gatekeep of the enconter.
Information about changes.
[Hotfix](http://forums.worldofwarcraft.com/thread.html?topicId=82238244&pageNo=1&sid=1) (2007-03-09): Removed magical immunity from skeletons and reduced damage from breath attack in flight.
https://wowpedia.fandom.com/wiki/Nightbane_(tactics)#Patch_changes

**Comment by kelno** [comment]
Thanks, I'll remove skeletons immunity with with next server update (should be in a few days).
(Nightbane breath damage will remain as is.)
