### ISSUE TITLE
Quest:More Warbeads wrong reputation gain

### ISSUE THREAD

**Issue by Petarrda** [ValorenWoW/sunstrider-core#5495]
So for this repeatable quest Quest:More Warbeads and horde similar, you have to get 500 rep (i guess 550 for alliance with 10% bonus for them), instead you get only 300 rep.
https://wowwiki-archive.fandom.com/wiki/Quest:More_Warbeads

**Comment by z5n** [comment]
Thanks, fixed with next restart!
