### ISSUE TITLE
The Twilight Camp Quest

### ISSUE THREAD

**Issue by aja318** [ValorenWoW/sunstrider-core#5496]
It's impossible to complete quest, interacting with item "Twilight Tome" in Master's Glaive does not complete the quest instead display generic greeting message "Greetings <name>".

**Character name**
Elor.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Start quest "The Twilight Camp"
2. Interact (use) Twilight tome.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
https://tbc.wowhead.com/object=12666/twilight-tome
https://tbc.wowhead.com/quest=949/the-twilight-camp

**Expected behavior**
Interacting with tome should display quest window allowing quest completion followed by starting the followup quest,

**Comment by kelno** [comment]
Thanks, fixed with next server update
