### ISSUE TITLE
Shaman mana spring totem threat

### ISSUE THREAD

**Issue by dole555** [ValorenWoW/sunstrider-core#5498]
**Describe the bug**
Shaman totems generate aggro and they shouldn't.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Place down Mana spring totem.
2. Body pull mobs.
3. See as mobs go for the totem, as it generated threat while replenishing your mana.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Spell: https://wowhead.com?spell=10497/mana-spring-totem

**Expected behavior**
Mana spring should not create threat.

**Additional context**

https://www.bluetracker.gg/wow/topic/eu-en/116562109-how-do-aggro-and-threat-work-in-wow/
"Mana Spring totem doesn't cause threat"

**Comment by Jerrythemagicdog** [comment]
Thanks, fixed with the next update.
