### ISSUE TITLE
Man mobs cant be skinned

### ISSUE THREAD

**Issue by Twisty575** [ValorenWoW/sunstrider-core#5500]
**Describe the bug**
I made a nelf hunter , learned skinning, many skinnable mobs cant be skinned. been gridning cats to catch skinning up and 3 out of 4 cant even be skinned once looted. says skinnable but doesnt give the skinning option when hovered over. tried auto looting and manual looting to see but was same for both.

**Character name**
ashigaru

**To Reproduce**
tried multiple mobs multiple times

nightsaber stalker, nightsaber

**Expected behavior**
please fix it :)

**Comment by kelno** [comment]
Thank you for reporting. I couldn't reproduce it right now, when you see "says skinnable" are we talking this text?
![image](https://user-images.githubusercontent.com/3866946/160236960-ee6e0332-a421-4a27-82a3-e28296d85979.png)

And you're saying even when this text appears, the skinning icon doesn't appear on hover?
![image](https://user-images.githubusercontent.com/3866946/160236983-e7241de1-9ae5-4974-8392-39d0b79ea01d.png)

**Comment by Twisty575** [comment]
im getting the same problem on Moonstalker runt just outside auberdine, but i have realised it doesnt show the Skinabble option or the skinning icon. i kill the mob loot it and its just there not skinabble option

**Comment by kelno** [comment]
Thanks, fixed with next server update
