### ISSUE TITLE
Shattered Hand Reaver and Other Shattered Hand's - Damage

### ISSUE THREAD

**Issue by JhonKepler** [ValorenWoW/sunstrider-core#5501]
**Describe the bug**

Damage scaling of Shattered Hand Reaver

**Character name**

JohnKepler/Kitty

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Tanking Hellfire Citadel: Shattered Halls (HEROIC)  with avoidance capped Paladin tank (JhonKepler). Trash mob packs. Including:
 Shattered Hand Legionnaire
 Shattered Hand Reaver 
 Shadowmoon Acolyte
 Shadowmoon Darkcaster
 Shattered Hand Sharpshooter
 Shattered Hand Heathen
2.  Even with few mobs in constant CC (priority order Darkcaster/Acolyte) we need to tank Legionnaire, Reaver, Heather.
3.  Reaver is one of the hardest hitting mobs in the instance. Even harder than Champions (same instance). Besides absolutely obliterating anyone with general hits, he has two ultra strong abilities. Cleave (110% damage of weapon) and Uppercut which sends Reavers target into air for ~3 seconds. While player is in the air he can not attack, parry, dodge, block. but is getting damage from Reaver and all the other mobs which he is tanking in these HUGE packs. In other words - instant death. And some packs have not 1 but 2 Reavers.
4. Shattered Halls (Heroic) is one of the hardest dungeons, because of the insanely hard hitting mobs. It is doable with a lot of CC and pre-Kara gear (all other heroic dungeon gear required to even attempt SHH hc). But it is almost impossible to survive those few seconds in the air when few mobs are hitting you. Average damage I was getting while in the air was ~12k. 
5. 2.1.0 Patch states that the Damage of Shattered Hand Reavers was lessen as well as his abilities - Uppercut combat range was made shorter (that Reaver or other mobs couldn't land hits while player is in air).

Shattered Hand Reavers will do less damage in Heroic difficulty.
The Uppercut used by the Shattered Hand Reaver now has a smaller combat range.
Rabid Warhounds on Heroic will now do less damage.
https://wowwiki-archive.fandom.com/wiki/Patch_2.1.0#Hellfire_Citadel:_Shattered_Halls 

6. After 2hours we eventually finished SHH hc, with all the joy sucked out of our souls we left that forsaken place with our heads hanging low. Only treasure for us was not the loot for our overgeared character, but the friendship which we made along the way.

https://tbc.wowhead.com/spell=30471/uppercut
https://tbc.wowhead.com/npc=16699/shattered-hand-reaver

**Expected behavior**
1. No damage from mobs on the ground while tank(player) is in air from the Uppercut
2. Lower damage From Shattered Hand Reaver 
3. Lower damage from few other mobs, that we wouldn't need overgeared toons for heroic dungeon.

**Additional context**
I need therapy after those wipes

**Comment by kelno** [comment]
Thanks, I reviewed the difficulty there and reduced the damage on those NPCs and a few other ones in the instance.
