### ISSUE TITLE
Wrong reputation increase rate

### ISSUE THREAD

**Issue by dole555** [ValorenWoW/sunstrider-core#5502]
**Describe the bug**
Reputation gain for alliance at least is increased by 44% instead of 20%. Only tested on draenei.

**Character name**
Spacedole

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Complete quest
2. Notice reputation increase
3. Compare to reputation gain noted in databases

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Additional context**

**Comment by kelno** [comment]
Thanks, fixed with next server restart
