### ISSUE TITLE
[Example] Pets don't teleport with player when being summoned over a short distance

### ISSUE THREAD

**Issue by kelno** [ValorenWoW/sunstrider-core#5503]
**Describe the bug**
When you get summoned by a warlock from a short distance your pet runs to you instead of being summoned with you.

**Character name**
Kelno

**To Reproduce**
1. Have a pet summoned
2. Get summoned by a warlock over a short distance (~50y)

Spell: https://tbcdb.com/?spell=698

**Expected behavior**
Pet should be teleported with the player.

**Additional context**
/

**Comment by kelno** [comment]
Thank you good sir for your nice explanation. Good bug reports enable us to understand and reproduce the bugs ourselves, so we fix them in a timely manner. 
This has been fixed now!

**Comment by ccwower** [comment]
感谢支持 -- 邮件我已收到 ！
