### ISSUE TITLE
Dorothy in Kara meleeing

### ISSUE THREAD

**Issue by baraTBC** [ValorenWoW/sunstrider-core#5504]
Describe the bug
Dorothy using Melee attacks on targets

**Character name**
Lystria

**To Reproduce**
1. Fight the Little Red Hood Encounter in Karazhan
2. When Dorothy aggros, she runs to you and melees before starting to cast frostbolts and weaving in melee attack here and there

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
https://tbc.wowhead.com/npc=17535/dorothee

**Expected behavior**
Dorothee is part of the Theater Event.

She comes along with Roar, Strawman, and Tinhead.

She Constantly casts Frostbolts at the Raid.
(comment from 2007)

**Additional context**
she died super fast because of overgearing, dunno if that means anything

**Comment by GM-Morsrael** [comment]
Thanks! I also noticed the tornadoes caused by The Crone being present don't despawn when she dies.

**Comment by kelno** [comment]
Thank you, fixed with next restart

**Comment by kelno** [comment]
Tornadoes not despawning > Let's keep that one as a feature
