### ISSUE TITLE
Nightbane not summoning

### ISSUE THREAD

**Issue by baraTBC** [ValorenWoW/sunstrider-core#5505]
**Describe the bug**
Nightbane after using the Urn flies in and does flavour text but after a while dissappears before even engaging in combat.

**Character name**
Lystria

**To Reproduce**
1. Summon Nightbane.
2. Wait.

**Expected behavior**
He's supposed to land and start hitting the tank like a truck.

**Additional context**
N/A

**Comment by kelno** [comment]
Thanks, fixed with next server update
