### ISSUE TITLE
Hunter Shot Queueing mechanic not working properly

### ISSUE THREAD

**Issue by baraTBC** [ValorenWoW/sunstrider-core#5506]
**Describe the bug**
Queueing a steady shot seemingly triggers the GCD but doesnt actually allow you to cast another shot until around 0.5 secs after the cast. I suspect the GCD is actually occurring AFTER the autoshot fires on the server side while on the client side the GCD fires properly.

**Character name**
Lystrin

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Make a hunter
2. Get a 3.0 speed wep from the arena weapon vendor
3. Get 2 BT haste rings (Band of Devastation) and Clutch of Demise from the arena accessory vendor and some Drums of Battle w/ leatherworking skill to get your weapon speed to 2.00 (for demonstration purposes) (other gear combos that bring you to 2.00 attack speed are fine)
4. While all haste effects are active, spam steady shot at target dummy. can try with whatever macro you want, I did it without macro, I suggest you do aswell.
5. It should not let you cast 2 steady shots in a row. This is because 1.5 sec GCD makes you cast steady shot 0.5 secs before your auto shot, thus queueing it up after the auto shot. 

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
https://web.archive.org/web/20080324225736/http://elitistjerks.com/f31/t9816-hunter_spreadsheets_--_development/p50/
^ thread from 18/01/2008

**Expected behavior**
Had it been queued properly the GCD wouldve ended at 1.0 seconds into the cycle, allowing you to cast 2 steady shots in a row.
<-----Auto--Shot-----><-----Auto--Shot----->          <-----Auto--Shot----->
 <-SteadyShot>________<-SteadyShot><-SteadyShot><-SteadyShot>
 GlobalCooldown-GlobalCooldown-GlobalCooldown-GlobalCooldown-

**Additional context**
The macro mentioned by the hunter threat from 2008 is, simplified:
/cast !Auto Shot
/cast Steady Shot
I have tested this with the macro and with the pure steady shot ability and I have gotten the same results.
I suggest using an addon like quartz which shows you +500ms spell delay on the queued shot.
I choose a 3.0 weapon because slow weapons are most effected by mechanics like shot queueing. should be able to replicate with a faster weapon if you'd like (aslong as its not too fast).

**Comment by kelno** [comment]
Thanks for taking the time to explain this, I'll look into it again

**Comment by kelno** [comment]
I updated the server with a tentative fix

**Comment by kelno** [comment]
Thank you for the well documented issue and explanation. Seems fixed now.

dev: 2c8cb82d1116df00c5ba7dab1ce9bd41b0f2b885
