### ISSUE TITLE
Shortsword of Vengeance (item=754) proc always resisted

### ISSUE THREAD

**Issue by arthur-merlin** [ValorenWoW/sunstrider-core#5507]
**Describe the bug**
The smite proc effect from the sword is always 100% resisted by every mob, no matter the level/type.

**Character name**
?

**To Reproduce**
1. Equip the item and auto attack

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=754

**Comment by kelno** [comment]
Thank you, fixed with next update
