### ISSUE TITLE
Auction House - Known Recipes not filtered

### ISSUE THREAD

**Issue by MauenSteam** [ValorenWoW/sunstrider-core#5508]
**Describe the bug**
With Usable Items check in the AH interface using the recipe category, known patterns/recipes still display.

**Character name**
Mauen

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Open AH
2. Have profession with sufficient skill to see available patterns
3. Check 'Usable Items' and Search
4. Known patterns still display

**Expected behavior**
Known patterns are not usable by the player, so should not be displayed in results under these conditions.

**Comment by kelno** [comment]
Thanks, fixed with next server update
