### ISSUE TITLE
Silithus Stable Master - incorrect text

### ISSUE THREAD

**Issue by mizmar** [ValorenWoW/sunstrider-core#5509]
**Describe the bug**
Stable Master in Silithus has an incorrect dialog text. It appears to be placeholder string.

NPC: Squire Leoren Mal'derath https://tbc.wowhead.com/npc=15722/squire-leoren-malderath

![Screenshot](https://user-images.githubusercontent.com/54911858/161115371-7c97f04f-6cb2-477e-84b2-32f229a42987.png)

**Comment by kelno** [comment]
Thank you, fixed with next server update
