### ISSUE TITLE
Priest

### ISSUE THREAD

**Issue by Lacroo** [ValorenWoW/sunstrider-core#5510]
**Describe the bug**
 [Inner Fire] spell loosing stacks when  [Power Word: Shield] is active

**Character name**
Bestishor

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Cast X on target affected by ...
2.
3.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**
When [Power Word: Shield] is active, [Inner Fire] should not lose stacks.  

**Additional context**

**Comment by kelno** [comment]
Thanks for reporting, fixed with next server update
