### ISSUE TITLE
Terokk

### ISSUE THREAD

**Issue by weaver-0f-fate** [ValorenWoW/sunstrider-core#5511]
**Describe the bug**
Terokk despawns immediately as he is summoned.

**Character name**
Weavelol

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Summon terokk using https://tbc.wowhead.com/item=32720/time-lost-offering in the middle island of skettis
2. See how it despawns and the summoning urn is wasted for nothing

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://tbc.wowhead.com/item=32720/time-lost-offering
Creature: https://tbc.wowhead.com/npc=21838/terokk
Quest: https://tbc.wowhead.com/quest=11073/terokks-downfall

**Expected behavior**
NPC shouldn't despawn

**Additional context**
2 summoning items are wasted coz of the bug. would like to get 2 summoning urns back to weavelol character.

**Comment by kelno** [comment]
Thanks, fixed with next server update
