### ISSUE TITLE
Lack of old world herb nodes

### ISSUE THREAD

**Issue by Mennoknight17** [ValorenWoW/sunstrider-core#5513]
Not sure if this is bug or not but trying to gather old world materials, especially herbs seems really difficult. I'm trying to level my herb gathering and there's barely any nodes to do it. It doesn't seem like anyone else is out gathering them either when I'm doing it. Maybe just increase the respawn rate of them a little or add a few more nodes to specific areas would help a little? Thanks in advance.

**Comment by z5n** [comment]
issue has since been fixed
