### ISSUE TITLE
Blood Furnace Broggok AOE spell - Poison Cloud

### ISSUE THREAD

**Issue by JhonKepler** [ValorenWoW/sunstrider-core#5514]
Hellfire Peninsula dungeon - Blood Furnace (hc) - (NORMAL WAS NOT TESTED)

Broggok AOE spell Poison Cloud seems to take bigger area value then it has. to.

https://tbc.wowhead.com/spell=30916/poison-cloud

When dropped Poison Cloud should do damage in the radius of 3 yards and with time the cloud gets bigger (the are which deals damage should expand too), but right now it seems that area where the damage is done at the start of Poison Cloud is much bigger than the animation (3yd) , so its really hard to move from it without getting 2x ticks of damage.

**Comment by kelno** [comment]
Thank your for reporting.
The visual expanding slowly can't be matching the actual area of effect, there is no such mechanic in the game. So I can't really make anything about this.
