### ISSUE TITLE
Quest: Call of Earth - can't continue the quest

### ISSUE THREAD

**Issue by AleGlowa** [ValorenWoW/sunstrider-core#5517]
**Describe the bug**
3rd part of [Call of Earth](https://classic.wowhead.com/quest=1518/call-of-earth) can't be started because it's not possible to accept this quest from [Minor Manifestation of Earth](https://classic.wowhead.com/npc=5891/minor-manifestation-of-earth).

**Character name**
Isgaroth

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Complete 1st part of [Call of Earth](https://classic.wowhead.com/quest=1516/call-of-earth)
2. Complete 2nd part of [Call of Earth](https://classic.wowhead.com/quest=1517/call-of-earth)

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest= [Call of Earth](https://classic.wowhead.com/quest=1518/call-of-earth)
Spell: https://wowhead.com?spell=

**Expected behavior**
The interaction with [Minor Manifestation of Earth](https://classic.wowhead.com/npc=5891/minor-manifestation-of-earth) after completion of 2nd part of the quest should be enabled in order to continue the chain quest.

**Additional context**

**Comment by kelno** [comment]
What's your character name?

**Comment by AleGlowa** [comment]
> What's your character name?

Isgaroth

**Comment by kelno** [comment]
Thanks for reporting! I checked your case and this is because you already have that quest completed by the autolearn system, you won't be able complete it anymore.
