### ISSUE TITLE
Game crashing in the central road of Zangarmarsh, south of the Graveyard, connecting east and west.

### ISSUE THREAD

**Issue by Blitzace91** [ValorenWoW/sunstrider-core#5522]
**Describe the bug**
When I run mounted up on the bridge road going from east to west just south of the graveyard in Zangarmarsh, my game crashes, and I can't log back into the character.

**Character name**
Roxana, Tauren druid

**To Reproduce**
Run on the bridge road just south of the graveyard in the center of the map, run from east to west.

**Comment by kelno** [comment]
If you downloaded the game from our website, there was an issue with the previous download causing this, sorry about that. We changed the link since then, you'll need to re download the game.
