### ISSUE TITLE
Warlock Pet Health ooc regen

### ISSUE THREAD

**Issue by freshman919** [ValorenWoW/sunstrider-core#5523]
**Warlock Voidwalker pet health regen out of combat is severely low. I don't remember having to use Consume Shadows this much in original TBC**

**Ambellina**

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Fight a mob, then after a kill, fall out of combat
2.
3.

**Seems like every couple of seconds only 10HP regenerates**

**Additional context**

**Comment by kelno** [comment]
Htank your for reporting.
Can you find some sources (video maybe) showing the regen should be much faster?
