### ISSUE TITLE
Thrallmar Inn not granting rested.

### ISSUE THREAD

**Issue by arthur-merlin** [ValorenWoW/sunstrider-core#5524]
**Describe the bug**
Thrallmar Inn does not grant the "rested" effect, nor the instant log out feature.

**Character name**
Teal

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Step inside the inn of Thrallmar.
2.
3.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Additional context**

**Comment by kelno** [comment]
Thank you for reporting this.
It does appear to give "rested" for me and another tester, I'll close this for now but if you or someone else has any more detail to give like precise location we'll look into it.
