### ISSUE TITLE
Old Hillsbrad Foothills - Interval between packs on last boss is 0

### ISSUE THREAD

**Issue by MauenSteam** [ValorenWoW/sunstrider-core#5525]
**Describe the bug**
The interval of time for packs to spawn before the final boss is seemingly 0, giving no downtime. Not sure if by design, but I recall there being at least a 5sec interval between the spawns, or at least not immediate aggro.

**Character name**
Mauen

**To Reproduce**
1. Get to final boss and let the packs of 3 dragons start spawning.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
N/A

**Expected behavior**
A slight delay between waves.

**Comment by kelno** [comment]
Thanks for reporting.
The interval seems to be very short, as can be seen here: https://youtu.be/4YeERf_R_1c?t=46
Seems like a very minor difference to me
