### ISSUE TITLE
Character Stuck Forever

### ISSUE THREAD

**Issue by ghizghizghiz** [ValorenWoW/sunstrider-core#5526]
I went to Nagrand to do Ring of Blood with my friends and i passed Garadar (the Horde camp) so i went to pick up the flightpath, instead i crashed and now i get an error every time i try to login (only for that character, others work fine) 
The error is 
"this application has encountered a critical error"

"Failed to read data"
Character name is: Summer, and I couldn't try unstuck because it requires you to be online

**Comment by InhumanGM** [comment]
This is due to a broken file in your client installation, reinstalling the client from https://sunstrider.gg/getstarted will fix that issue.
I moved your character out of that area, so you should be able to log in now.
