### ISSUE TITLE
Attacking mobs in Ameth'Aran (Darkshore) crashes game

### ISSUE THREAD

**Issue by dillonoconnor** [ValorenWoW/sunstrider-core#5527]
**Bug Description**
I have had 4 crashes trying to attack Highborne mobs in this area.  I have not experienced crashes elsewhere.

<img width="284" alt="Sunstrider Crash" src="https://user-images.githubusercontent.com/60942873/160511699-b643bd5f-c382-401c-8056-57488043330d.png">

**Character name**
Songyun

**Comment by kelno** [comment]
Where did you download your game client?

**Comment by dillonoconnor** [comment]
This was on the client downloaded from your website on launch day.

**Comment by kelno** [comment]
Thanks. To fix the issue, please re-download the client from our website, the previous version unfortunately had an issue.
