### ISSUE TITLE
Multiple bug report

### ISSUE THREAD

**Issue by Metalica** [ValorenWoW/sunstrider-core#5528]
Fel reaver - he is to slow and it's stats are wrong (killing stuff for long, where he should kill it instantly). 

Boiling blood quest: https://tbc.wowhead.com/quest=10538/boiling-blood#videos:id=208591 - does not spawn little creeps ( https://youtu.be/9yXvubQaJlU?t=51 ).

Inventory bug: If you have full inventory and want to accept item. You delete the item in the inventory, but still cannot accept the item. You have to close quest screen and then accept again the quest reward.  How it should work: If you can't accept quest item, you just delete item in inventory and complete the quest.

Quest deletion bug: Where ever you got selected in quest screen it auto deletes the lower button quests. How it should work: It should only delete quests which you got chosen in selection.

**Comment by kelno** [comment]
Thank your for reporting this.
Please use the bug report template (not multiple bugs per issue).
