### ISSUE TITLE
Lightning Overload does not proc off of itself. 

### ISSUE THREAD

**Issue by Wearetestingstuff** [ValorenWoW/sunstrider-core#5529]
**Describe the bug**
Lightning Overload Talent for elemental shaman does not proc off of itself.

**Character name**
Necco

**Expected behavior**
Lightning Overload in tbc has the capabilities of proccing off itself, including any other spell tag with the ID of lightning bolt or chain lightning (I.E. lightning capacitor). 

**Additional context**
Here are historical comments from wowhead highlighting this behavior sourced from https://tbc.wowhead.com/spell=30681/lightning-overload#comments.

There are plenty of other sources about this behavior if more sources are required.

By 34146 on 2007/03/23 (Patch 2.0.10)This is a decent talent but seems to proc off of itself a lot more lately, leading to some interesting "bloody hell" moments espcially if you get 3-6 LO's on the first spell cast on a mob on a boss fight. Even with the reduced threat I've seen it rip a mob off tanks with ease at the start of fights. | By 34146 on 2007/03/23 (Patch 2.0.10)
-------------------------------------------------------------------------------------------------------------------------------------------
I believe the answer is yes. I think the first proc is considered a normal spell cast, thus you can proc off it.

This could lead to an infinite chain, but the chances of it procing of itself is rare.

At 5/5 Lightning Overload

1: 5% (1 in 20)
2: 0.25% (1 in 2000)
3: 0.125% (1 in 16,000)
4: 0.00625%
5: 0.0003125%
---------------------------------------------------------------------------------------------------------------------------------------------------

**Comment by kelno** [comment]
Thank your for reporting.
I saw this discussed before and I remember the conclusion of that previous discussion was that the proc on itself was not intended and removed later in TBC.
I'll close for now but it you or anyone wants to bring more proof you can re open a new issue or add it to this one.
