### ISSUE TITLE
Apprentice Tasserel

### ISSUE THREAD

**Issue by QuadrozZz** [ValorenWoW/sunstrider-core#5530]
**Describe the bug**
Missing NPC which start quest line for Kara attune
NPC: https://tbc.wowhead.com/npc=23948/apprentice-tasserel
Should have the quest: https://tbc.wowhead.com/quest=11216/archmage-alturus

**Comment by kelno** [comment]
Thanks for reporting.
He's added in patch 2.3 and you don't need him to start the quest line, you can go directly to Archmage Alturus
