### ISSUE TITLE
Consacration bug.

### ISSUE THREAD

**Issue by WannaBetWannaBet** [ValorenWoW/sunstrider-core#5531]
Hello, i just found a huge bug about paladin`s consacration. The spell continue ticking after the effect is over, basically the spell i ticking doing damage forever.
LE: it might happend only in nagrand zone.

**Comment by kelno** [comment]
Thank you for reporting.
I can't reproduce this, if you or anyone has any detail how this can happen, you can add it here or open a new issue.
I'll keep an eye out for people reporting similar issues.
