### ISSUE TITLE
Hellfire Peninfula - Falcon Watch: using the Orb of Translocation causes fall damage

### ISSUE THREAD

**Issue by mizmar** [ValorenWoW/sunstrider-core#5533]
**Describe the bug**
In Hellfire Peninfula - Falcon Watch, there is a tower with Orb of Translocation teleporter to teleport played up and down.
Using the upper Orb to teleport down causes fall damage. The damage is equal to jumping from tower manually.

Location: next to Ranger Captain Venn'ren
 https://tbc.wowhead.com/npc=16789/ranger-captain-vennren

**Comment by GM-Morsrael** [comment]
Thanks for reporting - I haven't seen anyone take damage from this, however the orb is definitely not working as intended. The casts for [Translocate] and [Translocation] do not happen, making you instantly teleport up and down... there should be a [cast time](https://youtu.be/DxRwrkGd0bQ?t=183)

**Comment by kelno** [comment]
@mizmar What's your character name in game?
I can't reproduce this either.
Dev: The way this works is that SetFallInformation is called with correct height on MSG_MOVE_TELEPORT_ACK, which seems to be always sent before MSG_MOVE_FALL_LAND.

**Comment by mizmar** [comment]
I went back to test it and it only happens with hunter pet.
When I dismiss my pet, I get no fall damage from this. When my pet is out, I get fall damage ever time.

**Comment by kelno** [comment]
Haha that's a very good catch, you're actually right here, it makes no sense to me.
I'll dive into this one and see what's happening.
EDIT:  I can't seem to be able to reproduce that out of the live server right now.

**Comment by kelno** [comment]
I believe we've found the issue, I'll update the server with the fix.
