### ISSUE TITLE
Dorgok not dropping Gorgrom's Favor

### ISSUE THREAD

**Issue by Eccies** [ValorenWoW/sunstrider-core#5535]
**Describe the bug**
Dorgok not dropping Gorgrom's Favor

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://tbc.wowhead.com/item=31363/gorgroms-favor
Quest: https://tbc.wowhead.com/quest=10797/favor-of-the-gronn

**Expected behavior**
Gorgrom's Favor Should drop after killing him 20 times. at least once.

**Comment by kelno** [comment]
Thanks for reporting.

Two conditions to check:
- You need to be alliance
- You need to have completed quest  https://tbc.wowhead.com/quest=10795/a-date-with-dorgok

If you already have those two conditions you can say so here, I'll reopen and look some more.
