### ISSUE TITLE
thunder clap seems like it does nothing

### ISSUE THREAD

**Issue by hellothere123222** [ValorenWoW/sunstrider-core#5536]
**Describe the bug**
i use thunder clap and demo shout on cooldown in defensive stance and it is suppose to be good and it feels like nothing happens, mobs run everywhere, people leave the group bc its a shitshow
**Character name**
nevermore

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. pull 4 mobs in a dungeon, press thunder clap on cooldown and demo shout between, press other buttons when possible
2. watch as the mobs act like you do nothing at all and run to your teammates as you get yelled at
3. ???

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://tbc.wowhead.com/spell=25264/thunder-clap
https://tbc.wowhead.com/spell=12666/improved-thunder-clap
https://tbc.wowhead.com/spell=12789/defiance
https://tbc.wowhead.com/spell=71/defensive-stance

**Expected behavior**
to hold agro on 4 mobs
**Additional context**

**Comment by kelno** [comment]
Thanks for reporting. I ran a threat test we have and it seems to work as expected.
I feel your pain, tanking as a warrior and holding threat on multitarget is hard or impossible if the group doesn't somewhat behave.
We've spent a lot of time looking into threat mechanics and afaik they're correct, thunder clap and demo shout do work but you'll never beat a druid just spamming swipe.

**Comment by hellothere123222** [comment]
the point is i have 4 class unique abilities interlaced with talents to make tanking at least 4 mobs somewhat what i thought would be easy, but it seems blizzard has no fucking clue what they are doing, yet again, so maybe fuck the old shit, and fix the fucking game, i want to thunder clap and hold fucking agro, i have talents that are meant to do this, why the fuck doesnt it do it, you want to hold agro on 500 mobs, fine, reroll prot pala, but wtf, i should be able to thunder clap on cd and hold some fucking agro, i shouldnt have to fucking tab target 8 fucking times rotating 4 abilities to hold agro on 4 mobs, this is too much work, i should want to play game wtf.
