### ISSUE TITLE
Inn at raventusk village does not make you feel rested

### ISSUE THREAD

**Issue by banreaxe** [ValorenWoW/sunstrider-core#5540]
**Describe the bug**
Normally walking into an inn gives you rested status with a Z on your character icon and boosted exp when you log in again. But the Inn in raventusk village at the hinterlands for horde does not seem to do this. Someone said there is a small area that does but not sure about that.

**Character name**
Kanna

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Walk into the inn

**Comment by z5n** [comment]
The area of rested effect is handled in the client, not the server- so there is nothing we can do about this. There are some spots in the inn that do give the rested effect though, like on the stairs.
