### ISSUE TITLE
Missclicked, dagger for priest

### ISSUE THREAD

**Issue by Opa4ku** [ValorenWoW/sunstrider-core#5541]
**Describe the bug**

**Character name**
Character on which the issue occurred, if applicable.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. I missclicked a roll on "Hypnotic Blade", can you please have it transfered to the priest from the run named "Badhealer". Tnx 
2. Leto

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=7714/hypnotic-blade

**Comment by z5n** [comment]
Create a ticket in-game.
