### ISSUE TITLE
T3 Hunter Drop chance poor

### ISSUE THREAD

**Issue by Besteiro10** [ValorenWoW/sunstrider-core#5542]
Dear Gm I want to report the drop rate of the hunter's T3 while I see many more Hourglass of the Unraveller in a run of 15, even though I go daily and I am a casual player I have gone at least 18 or 20 times to Mechanar Normal , Botanica Normal , Shattered halls and i dont see any T3 of hunter drop Beast Lord Cuirass or Beast Lord Helm , Beast Lord Handguards , I think the percentage of drop is 2% while for the other classes its 10 inclusive 15% , the T3 is really low this is not swing it is more likely to play another class and build faster than to get the full set.
I feel like it's a race and I consider it unfair call it what you want but it's a bug or error and it should be fixed it's just insane to have to do more than 20 runs while you give the other classes 4 or 5 please fix this.
![WoW_ClassicLaunchPressKit_UngoroHunter_3840x2160-scaled](https://user-images.githubusercontent.com/103686506/163465765-71be1a72-2dfd-44b4-aa0e-727383780ead.jpg)

**Comment by Godmatik** [comment]
RNG is RNG - not a bug
