### ISSUE TITLE
8x xp not working

### ISSUE THREAD

**Issue by Hlyknght** [ValorenWoW/sunstrider-core#5544]
Bought 8x xp, but it is not activated on account

**Comment by kelno** [comment]
What's your account name?

**Comment by Hlyknght** [comment]
Hlyknght2

**Comment by kelno** [comment]
Thanks, I'll check now

**Comment by kelno** [comment]
Thanks for reporting. I've fixed it, but you might need to go to your character page to enable it.
I've reset your boost to 7 days starting now.

**Comment by Hlyknght** [comment]
Thank you
