### ISSUE TITLE
Arena Grand Master

### ISSUE THREAD

**Issue by mickwow** [ValorenWoW/sunstrider-core#5545]
Hello Sunstrider Team,

Could you please fix this quest so that it is repeatable?
https://tbc.wowhead.com/quest=7838/arena-grandmaster

The NPC Short John Mithril does not have a blue question mark above him after you have completed the quest for the first time and obtained your first arena grand master trinket. 

Thank you for your attention.

**Comment by kelno** [comment]
I don't see anything saying it should be repeatable, can you give me some hints about that?

**Comment by mickwow** [comment]
Hi Kelno,

I have played many private tbc wow servers such as endless and excalibur and this quest has always been repeatable for handing in 12x arena master trinkets for the arena grand master. Players are able to equip 2 x arena grand master trinkets. Have a look at the link i send you to the tbc wowhead and you will see on the right had side in the quick facts section it does mention the quest is repeatable. This is how it has always been blizzlike. And this is also well known in the twinking community.

![image](https://user-images.githubusercontent.com/75056834/165521182-3e7e6195-3bab-4206-ad8d-47fd71f6a9b6.png)

**Comment by mickwow** [comment]
Here is a video showing the npc change to a blue question mark after hand in.
See at the 46 second mark:
https://www.youtube.com/watch?v=MjfMjyBrYwI

**Comment by kelno** [comment]
Thanks!

**Comment by kelno** [comment]
Fixed with next server update (this week-end at worst)

**Comment by mickwow** [comment]
Thank you so much Kelno, much appreciated. Enjoy the rest of your week.
