### ISSUE TITLE
Mage Cone of Cold (CoC) doesnt apply when Blizzard slow still in effect

### ISSUE THREAD

**Issue by Bugsterport** [ValorenWoW/sunstrider-core#5548]
**Describe the bug**
On attempt to apply CoC on a mob that still has the Blizzard slow debuff. The CoC debuff is not applied.

**Character name**
Prob not character related.

**To Reproduce**
1. Cast Blizzard on target
2. Apply CoC while Blizzard slow debuff is still in effect
3. Wont apply CoC slow debuff

**Expected behavior**
It should apply the CoC debuff for its full duration not just the damage.

**Comment by theyasha69** [comment]
not a bug, the best slow will stay in place.
3/3 blizzard with permafrost gives a 75% reduced speed for 4.5 seconds
cone of cold gives 60%(50% frostbolt 50%(40% and frost armor 40%(30% stays on through them 
because it has the attack speed component
