### ISSUE TITLE
Quest: Cleansing the waters

### ISSUE THREAD

**Issue by Nemesturul** [ValorenWoW/sunstrider-core#5549]
**Describe the bug**
In Hellfire Peninsula in Telhamat temple have an quest which is uncompleteable. it's name is Pools of Aggonar. I can not use the item near to bones of aggonar

**Character name**
Turul

**Comment by kelno** [comment]
https://tbc.wowhead.com/quest=9427/cleansing-the-waters#comments

**Comment by kelno** [comment]
Thank you for reporting.
Seems to work for me, I can't reproduce it at the moment. This is where I'm standing:
![image](https://user-images.githubusercontent.com/3866946/193453480-ff4dd470-0bbc-44a7-b67d-0a92fe3ad9ee.png)

I'll close but if you want to give me some more details I'll check again.
