### ISSUE TITLE
eror game

### ISSUE THREAD

**Issue by doganyelken** [ValorenWoW/sunstrider-core#5550]
**Describe the bug**

**Character name**
Character on which the issue occurred, if applicable.

**To Reproduce**
Steps to reproduce the behavior. The more details the better!
1. Cast X on target affected by ...
2.
3.

Please include ids of affected creatures / items / quests with a link to the relevant wowhead-like page. 
Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Additional context**

**Comment by doganyelken** [comment]
my 68 lvl warlock pral nagrand in bugged i go warlock game fatal eror 134 need unstack help me gm

**Comment by kelno** [comment]
Please use in game or discord support for this kind of issues
