### ISSUE TITLE
Shaman water walking is not working

### ISSUE THREAD

**Issue by mihailo9** [ValorenWoW/sunstrider-core#5551]
**Describe the bug**
Shaman water walking is not working. As soon as you try to step onto water the buff goes away

**Character name**
Miklos

**To Reproduce**
1. Cast Water walking on yourself
2. Try to step on water
3. Water walking buff disappears

Spell: [https://wowhead.com?spell=](https://www.wowhead.com/spell=546/water-walking)

**Expected behavior**
You should be able to walk on the water while you have buff

**Comment by kelno** [comment]
Can you give me a specific place? I can't reproduce for now

**Comment by mihailo9** [comment]
Ok I forgot to mention, if you mount up then the buff is lost. I'm not sure if this is a bug or expected behavior
