### ISSUE TITLE
Feral Charge clipped thru map and fell into the void

### ISSUE THREAD

**Issue by OursPolar** [ValorenWoW/sunstrider-core#5554]
I inniated the boss with a charge (to look cool), but as he aggroed mid charge he ran strait down an unpathable wall (i thought id charge around the wall/ around the balcony elevated area he stands on) but i went strait at him, and when my charge ended i fell thru the ground XD gg no re

**Comment by GM-Morsrael** [comment]
Can you please provide more information?

Your Class/Character Name
Dungeon Name
Boss Name
Any screenshots if possible, or videos if recorded.

**Comment by kelno** [comment]
Thanks for the issue. I'll close as we can't really do anything with this level of detail, but I'm sure someone else will come up with a similar case we can look into
