### ISSUE TITLE
Blood of heroes

### ISSUE THREAD

**Issue by MianLavanAelin** [ValorenWoW/sunstrider-core#5555]
https://www.wowhead.com/classic/object=176213/blood-of-heroes

This object should have regular 100% drop of https://www.wowhead.com/classic/item=12938/blood-of-heroes

This item is needed for faster leveling of alts/twinks etc. 

Currently this object only spawns 1-2 https://www.wowhead.com/classic/npc=10996/fallen-hero which is correct. 
But the actual loot is missing at the object. Should be ez and quick DB fix, please help us make low lvl alts stronger!

**Comment by z5n** [comment]
the drop rate *is* currently 100%
gonna close this for now, but if you have more info that shows otherwise i can take another look

**Comment by MianLavanAelin** [comment]
Hi. I found 4 separate GOs and none of them droped the blood. I looted all of them several times(the GO also doesnt despawn for some reason) and all it does is spawn 1-2 of those elite npcs who absolutely do not drop the blood regularly. 

So current situation is that the GO can be clicked forever without ever getting the loot window for blood and it never despawns.

Could you maybe try looting it on your local/test/ingame?  

Also when looting the GO it knockbacks, so maybe if the knockback effect is before the loot being processed and shown? But that would be some core stuff, so maybe just disabling any effects of the GO would be nice workaround if that is the issue.

**Comment by MianLavanAelin** [comment]
Also found issue from 3 years ago where someone mentioned the exact same thing: 
https://github.com/SunstriderEmu/BugTracker/issues/4284

I assume you use the same GOs and object scripts etc for it cause the issue remains.

**Comment by z5n** [comment]
fixed with next update, thanks!
