### ISSUE TITLE
solo queue games starting with uneven teams for example 1v3 or 2v3 or 2v2

### ISSUE THREAD

**Issue by dedestus** [ValorenWoW/sunstrider-core#5558]
**Describe the bug**

solo queue games starting with uneven teams for example 1v3 or 2v3 or 2v2. queue solo queue and enter and if someone doesnt join the game will still start.
**To Reproduce**

olo queue games starting with uneven teams for example 1v3 or 2v3 or 2v2. queue solo queue and enter and if someone doesnt join the game will still start.

**Expected behavior**

the game should not start unless the it is a 3vs3 match with even numbers on both sides. it was working prio to today

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Fixed since then.
