### ISSUE TITLE
afk report in bg not working properly?

### ISSUE THREAD

**Issue by dedestus** [ValorenWoW/sunstrider-core#5559]
**Describe the bug**

even if more than 3 people report a player for afk in bg they dont get flagged for afk and dont receive the debuff to remove them from the bg if they fail to engage in pvp combat

**To Reproduce**

join a bg, report afk players with multiple people and see it does not work

**Expected behavior**

as far as im aware multiple afk reports towards the same player in a bg should flag them with a debuff and remove them from the bg if they fail to engage pvp combat
**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed since then.
