### ISSUE TITLE
dwarf priest racial ability Chastise possibly wrong DR category

### ISSUE THREAD

**Issue by dedestus** [ValorenWoW/sunstrider-core#5560]
**Describe the bug**

i could not find any related info on the web but currently chastise shares dr with entangling roots, frost nova and so on but it is the first server where i encounter this behavior but i cannot find confirmation which behavior is correct
**Character name**

**To Reproduce**

cast chastise on someone previously affected by frost nova or entangling roots

https://www.wowhead.com/tbc/spell=44047/chastise
**Expected behavior**

as far as i have experienced it in the past chastise should not dr with roots but this might have been bugged on previous servers so please delete this report if i it is misinformation
**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
