### ISSUE TITLE
Incorrect overlapping of movement slow effects

### ISSUE THREAD

**Issue by Neverik90** [ValorenWoW/sunstrider-core#5561]
You cant apply slow effects when a stronger slow effect is active on the target.
E.g. if you apply improved Blizzard on a mob wich slows by 75% and 1 second before the slow of Blizzard times out you use Cone of Cold wich slows movement by 60%, the slow of the Cone of Cold does not get applied because the stronger slow of Blizzard is still active and after the 1 second the mobs run with 100% movespeed at you.

**Comment by dedestus** [comment]
as far as im concerned this is intended behavior so you cannot stack frostbolt slow, cone of cold and blizzard on the same target or crippling poison etc so only the strongest slow remains active as a debuff until it runs out and you apply a new slow

**Comment by Neverik90** [comment]
Ok I just watched some old frostmage pvp videos and it seems you are right.
