### ISSUE TITLE
You can overbuff stronger buffs

### ISSUE THREAD

**Issue by Neverik90** [ValorenWoW/sunstrider-core#5565]
It should not be possible to overbuff stronger buffs with weaker ones, e.g. overbuff Arcane Intellect rank 6 with Arcane Intellect rank 5.

**Comment by kelno** [comment]
You can do it if they are your own buffs, that's a custom rule we have. You shouldn't be able to override the other player ones. Is that what's happening?

**Comment by Neverik90** [comment]
Inside of a group it is definitly possible to overbuff stronger buffs from others. And for strangers that are not in your group it is possible too, just tested it.

**Comment by kelno** [comment]
I couldn't reproduce. Tested with Power Word Fortitude. Being in a group or not made no difference, I couldn't override the other player with talent aura. If you have a specific case where it's wrong you can tell us here and we'll test.
