### ISSUE TITLE
Item [Goblin Jumper cables XL] fails to often (always?)

### ISSUE THREAD

**Issue by Neverik90** [ValorenWoW/sunstrider-core#5566]
According to Wowhead (https://www.wowhead.com/classic/de/item=18653/bauplan-goblin-%C3%BCberbr%C3%BCckungskabel-xl#english-comments) the item should have a succes rate of about 80%. I used it like 10 times so far and it always failed.

**Comment by z5n** [comment]
just got it in two tries, bad rng maybe
