### ISSUE TITLE
[LFG] Dismount when leaving a dungeon

### ISSUE THREAD

**Issue by lordaplala** [ValorenWoW/sunstrider-core#5571]
**Describe the bug**

When you are on a flying mount and join a dungeon by using the LFG tool then leave the dungeon, you're no longer on a flying mount, fall and die.

**Character name**

Nickname (my nickname is "Nickname" 😄)

**To Reproduce**

1. Use flying mount
2. Join LFG
3. Accept invitation -> Enter the dungeon
4. Leave the dungeon by running through the door
5. Observe the bug

**Expected behavior**
We should not die and pay extra repair after exit a dungeon.

**Comment by kelno** [comment]
Thanks, fixed with next update
