### ISSUE TITLE
Trap activation range smaller than expected

### ISSUE THREAD

**Issue by Pindrought** [ValorenWoW/sunstrider-core#5572]
**Describe the bug**
Trap activation range is vanilla is 5 units, the same as melee range. If one player is standing on a trap, nobody else should be able to melee them without triggering the trap assuming neither player is tauren. It seems like the trap activation range on endless is closer to 3 or maybe 4 units.

I don't know if the trap range changed in TBC, but I couldn't find anything indicating that it did.

**To Reproduce**
Melee a player standing on a trap. It is very easy to melee people without triggering traps on this server.

**Expected behavior**
You should trigger the trap when meleeing someone standing directly on a trap.

**Screenshots/videos**
Here is a video comparing what is happening in classic vs here.
https://youtu.be/ipKF7XWL3dQ

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Because our hitbox sizes are unified the effect won't be as extreme and pronounced as it is on Classic but melee players should activate the trap much sooner.
Live with the next server update.
