### ISSUE TITLE
hunter's pet behavior

### ISSUE THREAD

**Issue by Macilious** [ValorenWoW/sunstrider-core#5573]
so , whenever i start combat , i send my pet in first , most of the time , the pet takes either left or right side then run instead of running straight to the target , tried it in multiple situations and terrains , same behavior , let's give an example here ... a target straight ahead and on a flat terrain or rather ALMOST flat , then the pet should be running toward the target directly ? nope , the pet takes let's say ... left side and going completely off course , then remembers "oh wait i have a target to attack" then goes to the target after , this happened 90% of the time , and of course causes extra pulls when i'm leveling . please take a look at it

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Can you provide a video of the situation?
The pets predict the target's movement, so if the target is moving that's expected.
If the target is stationary then the pet will go behind the target.

**Comment by z5n** [comment]
> Can you provide a video of the situation?

@Macilious
