### ISSUE TITLE
negative casting range is missing

### ISSUE THREAD

**Issue by Aeded** [ValorenWoW/sunstrider-core#5574]
**Describe the bug**
If target is standing inside of you or slightly behind you it says you are not facing your target.

**To Reproduce**
https://streamable.com/wdlj3v

**Expected behavior**
Facing your target requirement should be still fulfilled even if your target is slightly behind you.
https://www.twitch.tv/perplexity/clip/AnimatedLachrymoseMangoPipeHype
https://www.twitch.tv/perplexity/clip/BlushingAbnegateMetalANELE

On classic (vanilla tbc wotlk) this was the max range.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
We've added some tolerance with the latest update.
Melee spells and regular attacks will not follow this logic though.
