### ISSUE TITLE
 [Cleansing the Waters] quest in Hellfire Peninsula - bugged.

### ISSUE THREAD

**Issue by sasadubi** [ValorenWoW/sunstrider-core#5577]
Item should be usable like here: https://www.youtube.com/watch?v=i4BfUh5An0g&ab_channel=WCQuests
https://www.wowhead.com/tbc/quest=9427/cleansing-the-waters

Tried for like 10 minutes straight to use item anywhere in waters near Aggonar, but no success...

**Comment by z5n** [comment]
was able to use it no problem right where my cursor is

![image](https://github.com/SunstriderEmu/BugTracker/assets/40606275/ec43a7e7-a549-40c6-96bd-cff4db6cd7e7)

**Comment by sasadubi** [comment]
How is this completed, when you have to be at EXACT specific position in order to complete the quest? On all other servers, you could use the quest item anywhere in waters near Aggonar.
Just because you made it, doesn't mean other ppl will bingo it. I stood there legit 10min, keybinded the quest item and spammed ton of things in the waters around him without any success.
Definition of a bug on this server is scuffed.
If you as Engineer or QA Analyst made it to perform an action, and the User can't. You just close bug as completed?
"Hey, works on my local machine" or "Hey, works for me".

**Comment by z5n** [comment]
you don't have to be at that exact position, that was just where i used it–with my cursor on that spot for your reference...
there may be room for improvement with the range for that spell, however as of right now it does work.

**Comment by sasadubi** [comment]
I'll check it today. Thanks.
