### ISSUE TITLE
general chat disappearance

### ISSUE THREAD

**Issue by Macilious** [ValorenWoW/sunstrider-core#5578]
just like the title says , just all of a sudden , general chat while i'm in outland just disappears , tried relogging multiple times , log off and close the launcher , hell ... i was even away from pc for few hours , game closed completely ... logged back in and it's still not there .
the channel itself doesn't exist in the "global channel" chat settings , and i tried to type "/join General" , still nothing works . what makes me go crazy at this point isn't all that . it's the fact that i can see people typing in general chat :'D
but the channel doesn't exist for me ... i hope it make sense for you , because it doesn't for me xD

**Comment by Godmatik** [comment]
try /resetchat

**Comment by Macilious** [comment]
> try /resetchat

i just logged in to try that and the general chat was there , i didn't do anything , it's not the first time it happens tho

**Comment by Godmatik** [comment]
well it's something to try if it happens again i guess

**Comment by z5n** [comment]
likely an addon issue

**Comment by z5n** [comment]
atlas loot addon caused it

**Comment by Tanatsuko** [comment]
> atlas loot addon caused it

Somebody in my guild mentioned that he managed to fix it by disabling the WotLK part of AltasLoot in the addon section. Maybe you can modify the downloaded content via launcher in such a way that it won't download the WotLK part to begin with?
