### ISSUE TITLE
Weapon swing glitch? 

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5580]
I'm playing a retribution paladin, so I'm naturally using a slow two-handed weapon which makes this more noticeable. I notice that every now and then, my character doesn't do an attacking animation for what must be two weapon swings. Afterwards, I see two different white damage numbers at the same time. (Also, I don't have Hand of Justice or any other trinket or talent that would make this behavior normal).

**Comment by Jerrythemagicdog** [comment]
https://github.com/SunstriderEmu/BugTracker/issues/5252
