### ISSUE TITLE
[Paladin] Spiritual Attunement shows up in spellbook way beyond level 66.

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5582]
https://cdn.discordapp.com/attachments/1124468708283252920/1170921398101872700/image.png

I don't remember when I first noticed it, but I think it was around level 20. Definitely appears too early in the spellbook.

**Comment by z5n** [comment]
appears in spellbook at level 18, not sure what's causing it to show up yet

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
This is expected for the first rank of the ability: https://www.wowhead.com/tbc/spell=31785/spiritual-attunement#comments:id=64938
