### ISSUE TITLE
[Quest] Cauldron quests in WPL have a slight bug.

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5583]
https://cdn.discordapp.com/attachments/1124468708283252920/1170924459876700221/image.png

I tried this from Horde perspective and saw the bug for at least the first three quests in the chain. Usually, once you get close to the cauldron, a mob with a unique name spawns that have you to kill for the key. However, the mob that spawns is called "Unknown" and also not tagged as undead. For the second quest in the chain, the mob had the correct name later, so it might be a timing issue, i.e. the server renames the mob too late?

**Comment by z5n** [comment]
typically happens when you have a network issue, you aren't receiving the data from the server correctly

**Comment by z5n** [comment]
weird, happens locally too
relevant quests:
5216
5219

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
