### ISSUE TITLE
Blood Elf with Diplomacy (Human racial) doesn't get increased rep on elite trash mobs

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5586]
Like the title says. I play a blood elf paladin with human racials. In Slave Pens, I only ever got 5 rep for trash elites. I even made sure to keep the reputation bar open to check if it's just a chat issue and I secretly get it, but no. Ironically, I did get 55 reputation on bosses, though, while my group members confirmed they only got 50.

**Comment by Godmatik** [comment]
Probably because it is doing 10% bonus of 5, which is 5.5, and that rounds down to 5.
So the rep is being rounded down instead of rounding up.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
