### ISSUE TITLE
Druid flight form requesting to be on the ground when picking up herbs

### ISSUE THREAD

**Issue by Sasab94** [ValorenWoW/sunstrider-core#5587]
**Describe the bug**
When in flight form trying to pickup herbs(and in range) u can't. Need to get on the ground and pick 'em up.

**Character name**
Hooraah

**To Reproduce**

1. Get on top of the herb(but be in range, so cursor not grey)
2. Press to pick it up

**Expected behavior**
To pick it up when in range, not to be on the ground to to so(talking about using flight form).

**Screenshots/videos**
https://snipboard.io/HmKqyr.jpg

**Additional context**
When trying to do that description on action says(You are flying.) <- screenshot evidence

**Comment by Godmatik** [comment]
Pretty sure that is intended - during TBC classic you also had to be touching the ground when in flight form to be able to herb, it was only an unintended bug on some private servers afaik that you could herb while hovered above

**Comment by Zythris** [comment]
I would also believe that is correct @Godmatik

**Comment by z5n** [comment]
intended
