### ISSUE TITLE
Repeatable quest "Gaining Acceptrance" gives 625 rep instead of 25

### ISSUE THREAD

**Issue by anderskp09** [ValorenWoW/sunstrider-core#5589]
**Describe the bug**
Completing the quest "Gaining Acceptance" (4 dark iron residue turn ins) gives 625 rep, not 25
https://youtu.be/BGRc0NedR0g
https://www.wowhead.com/tbc/quest=7737/gaining-acceptance

**Comment by z5n** [comment]
thanks, fixed with next update
