### ISSUE TITLE
Lokhtos Darkbargainer does not sell me anything despite being honored

### ISSUE THREAD

**Issue by anderskp09** [ValorenWoW/sunstrider-core#5591]
**Describe the bug**
Lokhtos Darkbargainer inside BRD does not act as the quartermaster, and will not sell me rep-based items (such as spirit to weapon) despite be having correct status.

https://youtu.be/27XYfpyKPVA

**Character name**
Mike

**To Reproduce**
1. Have appropriate status with Thorium brotherhood (friendly+)
2. Lokhtos Darkbargainer will ignore your interest to buy..
https://www.wowhead.com/tbc/npc=12944/lokhtos-darkbargainer#sells

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
