### ISSUE TITLE
Every mob interrupts every time

### ISSUE THREAD

**Issue by Lanarrin** [ValorenWoW/sunstrider-core#5592]
**Describe the bug**
Working on farming stratholme and every mob interrupts me every time instantly. Can't use holy light, cant use Holy Wrath or any other casted spell. The same thing happens when tanking dungeons. At first I thought it was just the nature of TBC trash. But looking at it deeper I don't remember everything being so on point with interrupts. It may be related to casting and pushback from spell int as i can sometimes get casts off with Concentration Aura. 

If this is intended then there's really nothing to change. If not can we take a look at it?

**Character name**
Lanarrin
**To Reproduce**

1. There's a weird thing with mobs starting a cast against you that interrupts your own casts. Fly into any canon in Ogrila and the moment it aggros/starts casting, it will interrupt your "Throw Bomb" cast (and close all bags). I reckon the same thing happens in strat if you aggro a bunch of caster skeletons in strat. You have to make a github report though, not a suggestion
2. I have seen this as tank in dungeons like mecha bot etc
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://www.wowhead.com/tbc/spell=27139/holy-wrath , https://www.wowhead.com/tbc/spell=27136/holy-light , https://www.wowhead.com/tbc/spell=27180/hammer-of-wrath

**Expected behavior**
Not interrupted and locked out of school instantly upon beginning cast, pushback only from being attached successfully. 

**Screenshots/videos**

**Additional context**

**Comment by artieau** [comment]
The NPC has an ability (such as Interrupt) so it will use it. The NPC is correct, so are you asking to change the mob entirely?

**Comment by Lanarrin** [comment]
No, not at all, I am looking at the fact that I get interrupted when mobs
cast frost bolt etc. I also dont recall the zombies in stratholm having
interrupts. I may be wrong but I have been seeing this throughout the
leveling process all the way through end game when tanking its impossible
to use avengers shield, holy wrath or the pally execute (drawing a blank on
the name) but I am 100% positive I have farmed strath on other servers and
not been interrupted once.

**Comment by Lanarrin** [comment]
I’d be happy to hop in a discord call and share my screen with you so you
see what I’m seeing.

**Comment by artieau** [comment]
I believe we already understand, but comparisons to other servers are not always a great tactic.
If mobs hit you, they will push back your casts - that is how it should work.

If the mob has an interrupt ability, it will use it to interrupt your cast.

We can just check the specific mobs you engage with, whether they have the correct ability or not.

**Comment by Lanarrin** [comment]
That works for me. What I’m seeing is if the pushback causes me to be
interrupted I am not locked out of those spells. Which I agree knock back
from being hit should interrupt and not cause spell lock.

However I don’t believe the mobs in this case have an interrupt, and I
believe there is an incorrect interaction between casting mobs and my casts.
It seems down to the millisecond I start my cast I am interrupted and spell
locked from that school for 6 or 8 seconds. Which is a lot of time with
10-12 skeletons on you. I would be fine if it was you know half a second
into the cast. But it’s near instant every time.

**Comment by Lanarrin** [comment]
Looks like the mp4 is too large. try this youtube link
https://www.youtube.com/watch?v=z2joV1TEqQk
