### ISSUE TITLE
Clefthoof Bulls (and possibly other animals) in Nagrand are sometimes unskinnable.

### ISSUE THREAD

**Issue by BasedForfrost** [ValorenWoW/sunstrider-core#5593]
It appears any time they drop Oshu'gun Crystal Powder Sample in their loot table, you are unable to skin it. I noticed this while farming Clefthoof Bulls, but did not take the time to farm other animals in Nagrand to see if I got the same result.

**Character name**
Quaack

**To Reproduce**

1. Kill Clefthoof Bull
2. Loot (Oshu'gun Crystal Powder Sample drops)
3. Tooltip won't show "Skinnable" beneath the enemy level

https://www.wowhead.com/tbc/npc=17132/clefthoof-bull

**Expected behavior**
I kill bull -> bull gives me leather.

**Comment by kelno** [comment]
We did some major rewrite of the loot system, this is a regression. Fixed with next server update.
