### ISSUE TITLE
Target Dummies not dropping anything

### ISSUE THREAD

**Issue by Bangsybugs** [ValorenWoW/sunstrider-core#5596]
**Describe the bug**
Target Dummies just dissappear without being lootable

**Character name**
Bng

**To Reproduce**

1. Cast Target Dummy
2. ???
3. no profit

Item: [https://wowhead.com?item=](https://www.wowhead.com/classic/item=4366/target-dummy)

**Expected behavior**
Being lootable: some random stuff and sometimes fused wiring

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
Seems to only have been rank 1 target dummies.
