### ISSUE TITLE
Rotting Behemoth loot table is off

### ISSUE THREAD

**Issue by Sologrim** [ValorenWoW/sunstrider-core#5597]
It says, that Rotting Behemoth in Western Plaguelands has 30% drop rate for the **Heart of the Wild**
https://www.wowhead.com/tbc/npc=1812/rotting-behemoth
I`ve farmed them in Western Plaguelands for half an hour and didn`t get a single drop of Heart of the Wild :/

**Comment by z5n** [comment]
thanks, improved drop rate with next update
