### ISSUE TITLE
Sometimes arena id's are swapped in arena matches

### ISSUE THREAD

**Issue by Pindrought** [ValorenWoW/sunstrider-core#5598]
**Describe the bug**
In a 2v2 arena, there should be an arena1 unit and an arena2 unit on the enemy team. Many times, one of the players will be in the arena3 slot instead of arena1 which breaks addons like gladdy and instead of using macros intended for arena1, you will have to use macros for arena3.
Similarly, in 3v3 sometimes one of the players will be in the arena4 slot.

**To Reproduce**
I am not sure what is causing the issue, so I don't know how to consistently reproduce it.

**Expected behavior**
In a 2v2, the enemy unit id's should always be arena1 and arena2. This discrepancy is what will cause addons like gladdy to show a blank frame in one of the slots.

**Screenshots/videos**
The hunter here should be arena1, but instead is arena3 which breaks gladdy and makes it so you can not use arena1 macros to target/focus them.
![image](https://github.com/SunstriderEmu/BugTracker/assets/39708313/e46c7fd5-f9f4-4e31-a134-7ad92bbc705e)

**Comment by kelno** [comment]
Thanks, fixed now
