### ISSUE TITLE
Eyes of the Beast is broken - pet has to walk onto you before you can control it

### ISSUE THREAD

**Issue by Pindrought** [ValorenWoW/sunstrider-core#5600]
**Describe the bug**
When casting eyes of the beast, you will not be able to control the pet until it walks to your position. This should not be happening.

**Character name**
Garbageman

**To Reproduce**
Cast eyes of the beast with your pet on stay not next to you.

https://youtu.be/z2vBVrIgK9c

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
