### ISSUE TITLE
Cloaking freezing trap puts you in combat instantly

### ISSUE THREAD

**Issue by Andwhatx** [ValorenWoW/sunstrider-core#5603]
**Bug description:**

Using cloak of shadows and running through a freezing trap or shadowstepping a target standing on a freezing trap instantly puts you in combat. This effectively means that you cannot cloak and then shadowstep sap a hunter standing on freezing trap.

Side note, running through a frost trap or shadowstepping a target standing on a frost trap does not put you in combat.

**To reproduce:**

1) On hunter: place flare and freezing trap on top of yourself; and
2) On rogue: precast cloak of shadows and either run over the freezing trap, or shadowstep the hunter stood of the freezing trap.

**Expected behavior**

You are meant to be able to cast sap on the target (if the target is standing on freezing or frost trap), before flare takes you out of stealth.

**Screenshots/videos**

https://www.youtube.com/watch?v=7sg6g77ImWQ

**Additional context**

You can contact me on discord (.andyxd) if you require any further information, or if we can help with testing.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
