### ISSUE TITLE
[Quest] The Challenge. Can't loot Top Piece of Lord Valthalak's Amulet on Theldren's corpse

### ISSUE THREAD

**Issue by Lalolilole** [ValorenWoW/sunstrider-core#5604]
**Describe the bug**

Can't get item Top Piece of Lord Valthalak's Amulet (ID : 22047) for "The Challenge" quest.
You can't loot Theldren's corpse, but you should get the item on him.

**To Reproduce**

After using Banner of Provocation (ID : 21986) in the Arena and killing first wave of non-elites, Theldren and adds spawn. Kill them all and try loot Theldren's corpse.

You get credit for defeating Theldren's Team, but you don't get Amulet to finish the quest because you can't loot it on Theldren.

Item: https://classic.wowhead.com/item=22047/top-piece-of-lord-valthalaks-amulet
Quest: https://classic.wowhead.com/quest=9015/the-challenge

**Expected behavior**

You should be able to loot quest item on Theldren's corpse.

**Character name**

Lalo

**Additional context**

There're a bunch of other bugs making this event really weird

- Sometimes Theldren don't come with his adds, and despawn a few seconds after the fight begins
- If you start the fight with in stealth or invisible character (mage druid rogue), all adds keep entering and leaving in combat mode
- It seems if you manage to leave fight (rogue vanish, etc.), mobs can start fighting each other.

Also, it seems this bug has been reported and solved in 2020 (https://github.com/SunstriderEmu/BugTracker/issues/2746)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
