### ISSUE TITLE
Warlock and soul shards

### ISSUE THREAD

**Issue by Zlandicae** [ValorenWoW/sunstrider-core#5605]
**Describe the bug**
I've noticed that when I disconnect my Warlock with an active pet (like, a void walker) and I'm on a mount, when I reconnect it, I have  a soul shard in the inventory... When I leave my mount, my pet appears and I keep the extra soul shard in my inventory.

**Character name**
Zlandicae

**To Reproduce**
Each time when connecting my character

Item: https://wowhead.com?item=6265

**Expected behavior**
If I have an active pet while I'm on a mount and I dismount, my soul shard should disappear from the inventory.

**Screenshots/videos**
-

**Additional context**
-

**Comment by Zlandicae** [comment]
Here are a few screenshots to illustrate my point :

https://imgur.com/kW1DVja

https://imgur.com/GCL0qyc

https://imgur.com/D0luFDR

**Comment by z5n** [comment]
repro steps

summon pet
mount
log out
log in

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
