### ISSUE TITLE
Shadowforge Torches in The Lyceum in BRD don't seem to have a 5 min timer

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5606]
See title.

**Comment by Tanatsuko** [comment]
I was just told by a friend that this is apparently normal for the original TBC. There seems to be a timer for Classic, TBC Classic, and WotLK Classic, though, but I guess TBC and TBC Classic can be very different in some regards.

Long story short: This might not be a bug.

**Comment by Tanatsuko** [comment]
Oh, also, could you check if the drop rate on the Shadowforge Torch is 100% for Shadowforge Flame Keeper? I just had one not drop a torch, and I don't think that's supposed to happen.

**Comment by Godmatik** [comment]
Should be 100% drop rate unless you have already opened the gate.

And the wowhead tooltip for TBC clearly says 5 minutes

https://www.wowhead.com/tbc/item=11885/shadowforge-torch

**Comment by Tanatsuko** [comment]
> Should be 100% drop rate unless you have already opened the gate.
> 
> And the wowhead tooltip for TBC clearly says 5 minutes
> 
> https://www.wowhead.com/tbc/item=11885/shadowforge-torch

Thanks for your input. I didn't open the gate yet. It was my fifth run on this realm, and this time, I had to kill 3 Shadowforge Flame Keeper to get 2 torches.

About your Wowhead link: I believe Wowhead only has information for TBC Classic and WotLK Classic, but not for the original game. There are other websites that don't state the 5 minute for TBC.

https://tbc-twinhead.twinstar.cz/?item=11885 (English)
https://tbcdb.rising-gods.de/?item=11885 (German)

So my guess is that they removed the duration in TBC but kept it for TBC Classic.

**Comment by Tanatsuko** [comment]
Just happened again. Needed to kill 4 Shadowforge Flame Keeper to get 2 torches

Screenshot: https://cdn.discordapp.com/attachments/1124468708283252920/1173426927017668760/image.png

**Comment by Tanatsuko** [comment]
Just happened again. Needed to kill 4 Shadowforge Flame Keeper to get 2 torches

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
