### ISSUE TITLE
Some mobs can't be looted, and also cannot be skinned

### ISSUE THREAD

**Issue by miranda** [ValorenWoW/sunstrider-core#5611]
Some mobs you kill randomly will not be lootable, which also means they can't be skinned.
It's an annoyance when farming, as sometimes you will need to kill many more mobs than you should.

This bug also used to happen on Sunstrider quite often.

I remember on official Blizzard vanilla/TBC servers occasionally there would be mobs with no loot, but they opened an empty window and you could skin them after looting nothing.  Not sure if this bug is caused by mobs not having loot on them, but if it is there are way more mobs with no loot than I remember seeing.

**Comment by z5n** [comment]
sounds related to #5593

**Comment by miranda** [comment]
None of the Cobalt Mageweavers in Winterspring are skinnable.  After you loot them they continue sparkling and you have the bag loot mouse cursor still... you will attempt to loot every time you click but they behave as if they are not looted and therefore not skinnable.

Most of the furlbogs in Felwood have the same behaviour.  Even though you can't ever skin furlbogs, they have the same forever lootable bug.

**Comment by kelno** [comment]
We did some major rewrite of the loot system, this is a regression.

**Comment by kelno** [comment]
Fixed with next server update
