### ISSUE TITLE
Frost Oil always resist on proc

### ISSUE THREAD

**Issue by Hahabg** [ValorenWoW/sunstrider-core#5612]
**Describe the bug**
As a protection paladin, I am enchanting my weapon with frost oil for bonus damage. Sadly every time it occurs it is resisting.

**Character name**
Hahabg

**To Reproduce**

1. Cast Frost Oil on the weapon.
2. Attack monster.
3. Pray for Frost Oil to proc.
4. See the Resist message.
5.

Item: https://www.wowhead.com/item=3829/frost-oil
Item: https://www.wowhead.com/item=29185/continuum-blade

**Expected behavior**
Frostbolt to hit

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
