### ISSUE TITLE
Lokhtos Darkbargainer will sell you items that you dont have reputation for

### ISSUE THREAD

**Issue by anderskp09** [ValorenWoW/sunstrider-core#5614]
**Describe the bug**
He will sell me all items, even though i am only honored, that should require revered/exalted
![image](https://github.com/SunstriderEmu/BugTracker/assets/69630725/222d393a-41cd-4865-abd9-f1d953101856)

**Character name**
Mike

https://www.wowhead.com/classic/guide/thorium-brotherhood-reputation-wow-classic#rewards-by-reputation-exalted

**Expected behavior**
He only sell me the Formula: Enchant Weapon - Mighty Intellect untill i am revered

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/69630725/d60da8ac-a9c5-4b03-bb17-7665ef39258f)

This was probably due to the implementation of this Issue:
https://github.com/SunstriderEmu/BugTracker/issues/5591

**Comment by anderskp09** [comment]
Forgot to highlight it, but you can see my rep is only Honored with Thorium Brotherhood. I should not be able to buy i.e. Mighty Int, og the Plans: Nightfall

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed wtih the next update.
