### ISSUE TITLE
Run away speed for mobs seems way too high (noticed it in Tyr's Hand, EPL)

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5615]

**Comment by z5n** [comment]
need some specific mobs

**Comment by Tanatsuko** [comment]
> need some specific mobs

Sorry for the late reply. Have you tried the ones near the castle? I had it happen there, but I don't remember which mob type it was. I'm sorry I can't be more specific. There are mostly three types of mob there: one pala-like, one mage-like, one priest-like. Can you try those?

**Comment by Tanatsuko** [comment]
I checked Wowhead. I highly suspect it was either a Scarlet Curate or a Scarlet Archmage. I'm in BRD right now to grab some transmogs, so I cannot check right away. If you can't recreate it, I'll definitely check again myself.

Also, thanks for always replying on the bug tracker right away, z5n, you are an absolute legend! Appreciate it a lot!

**Comment by Tanatsuko** [comment]
I'm back in Tyr's Hand to grind a little. I definitely noticed it with a Scarlet Archmage. He had pretty much epic mount speed or faster while fleeing.

**Comment by kelno** [comment]
Fixed with next server update. Fleeing creatures usually get 66% of their base speed and can be slowed down further depending on their health and debuffs.
