### ISSUE TITLE
High Priest Orglum - The Vengeful Harbinger

### ISSUE THREAD

**Issue by KayTeaHolmes** [ValorenWoW/sunstrider-core#5617]
**Describe the bug**
Unable to accept the quest from giver after completing prerequisite quest.

**Character name**
Fura

**To Reproduce**
N/A unable to take quest. Clear cache has been done.

[Quest: https://wowhead.com?quest=10842](https://www.wowhead.com/tbc/quest=10842/the-vengeful-harbinger)

**Expected behavior**
Able to take quest.

**Screenshots/videos**
![image](https://github.com/SunstriderEmu/BugTracker/assets/150562548/da302ba0-4988-4707-8000-adc4939f6694)

**Comment by z5n** [comment]
quest disabled until script is reworked

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Fix is live.
