### ISSUE TITLE
BRD - Lokhtos Darkbargainer <The Thorium Brotherhood>

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5619]
I get the following message:

"The Thorium Brotherhood does not waste time on ants. Be gone!"

Expected behavior: Should usually work as a vendor NPC, regardless of reputation.

**Comment by z5n** [comment]
related to #5614

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Is there any proof this is how it's supposed to work this way?
Everywhere I read if you're not at least friendly you can't access the vendor gossip.
