### ISSUE TITLE
Scroll of Spirit V cannot be sold to a vendor

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5620]
Current behavior: No sell price
Expected behavior: Sell price 1s per Scroll of Spirit V
https://tbc-twinhead.twinstar.cz/?item=27501

**Comment by Tanatsuko** [comment]
Upon further inspection, this might be an issue for all scrolls in the game.

**Comment by z5n** [comment]
thanks, fixed with next update
