### ISSUE TITLE
Charging a Duel Opponent on the Menethil Harbor Boat leading to Dustwallow Marsh causes a SEVERE issue.

### ISSUE THREAD

**Issue by Zythris** [ValorenWoW/sunstrider-core#5621]
This is the occurring issue that happens after a charge on the boat leading to Dustwallow Marsh from Menethil, however i'd assume all boats would do this?

https://github.com/SunstriderEmu/BugTracker/assets/148729532/1ce92689-0361-4ec8-8a91-63679cf6d4b2

This evidently lead to my death, due to a permanent "fatigue" de-buff, and my character is currently under the rocks not able to respawn at corpse, hearthstone on CD for 50 minutes, running back to spirit healer to eat the spirit rez and travel a good 20+ mins back to where I initially was.

**Comment by z5n** [comment]
are you able to send a video of what caused this?

**Comment by Zythris** [comment]
I mean the title is kinda self explanatory, i pressed "Charge" on my warrior when dueling a buddy and got sent to the next dimension lol.

**Comment by z5n** [comment]
sure, but the title doesn't convey where you were standing when you hit Charge and it bugged out

after testing it seems like a player can't Charge to any players on a transport object like a boat, so i'm wondering how you were able to make that happen is all :)

**Comment by Zythris** [comment]
I don't have a clip containing the previous actions sadly i wasn't quick enough to clip it.

i can recall i was on the upper part of the boat, above the stairs leading down, and i charged my buddy when he was on his way up.

if you can't reproduce this then it's probably a low chance for it to happen, sorry i'm unable to provide more info.

**Comment by z5n** [comment]
> i can recall i was on the upper part of the boat, above the stairs leading down, and i charged my buddy when he was on his way up.

thanks! this was what i needed

**Comment by z5n** [comment]
https://streamable.com/0wudwl

**Comment by Zythris** [comment]
Appreciate all y'alls hard work with this server. Thanks for finding the time to reproduce it. as I have not had the time to do so.

**Comment by kelno** [comment]
Thanks, fixed with next server update
