### ISSUE TITLE
Rescue OOX-17/TN! is bugged

### ISSUE THREAD

**Issue by go2havefaith** [ValorenWoW/sunstrider-core#5622]
After the spawn of three scorpids the mechanical chicken flies up into the air and doesn't come back down - have attempted the quest twice and both times it did this

**Comment by Godmatik** [comment]
Have seen this bug before, it is following the Wrath script when the quests were redesigned/shortened to end after 1 set of mobs, should follow the TBC script where it goes to the very end of its path after 3 packs of mobs engage it. This might be affecting all 3 chicken quests

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
