### ISSUE TITLE
[Netherstorm] Ethereum Maces do not despawn after you kill an Ethereum Overlord

### ISSUE THREAD

**Issue by Tanatsuko** [ValorenWoW/sunstrider-core#5623]
Expected behavior: Based on this comment from Wowhead (https://www.wowhead.com/tbc/npc=21286/ethereum-mace), they should despawn as soon as the Ethereum Overlord is dead.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
