### ISSUE TITLE
Item drop chance of Shadowcraft Spaulders

### ISSUE THREAD

**Issue by LSD7** [ValorenWoW/sunstrider-core#5624]
**Describe the bug**
I did like a 30 runs for https://www.wowhead.com/classic/item=16708/shadowcraft-spaulders and it never drops. Could you please check the drop chance and etc.

Item: https://www.wowhead.com/classic/item=16708/shadowcraft-spaulders

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The drop chance is at about ~20%
