### ISSUE TITLE
Skettis, Terokkar Quest Adversarial Blood cannot be completed

### ISSUE THREAD

**Issue by aherhsrtdbsdfhujwrts** [ValorenWoW/sunstrider-core#5625]
**Describe the bug**
Adversarial Blood in Skettis in Terokkar cannot be completed. You can acquire shadow dust and time-lost-scrolls, but the scrolls cannot be used to summon the elite enemies. There are skull piles scattered around Skettis, but they are non-interactable.

**Character name**
Uzzaji

**To Reproduce**

1. Acquire Adversarial Blood and 10x time lost scrolls
2. Attempt to summon elites at one fo the circles around skettis
3. 

Item: [https://wowhead.com?item=](https://www.wowhead.com/tbc/item=32620/time-lost-scroll)
Quest: [https://wowhead.com?quest=](https://www.wowhead.com/tbc/quest=11885/adversarial-blood#comments)
Spell: https://wowhead.com?spell=

**Expected behavior**
You should be able to interact with the skull piles in the cirlces to summon elites

**Screenshots/videos**

**Additional context**

**Comment by Godmatik** [comment]
Dev might want to check the state of the quest. It changed in patch 2.4. Perhaps the version we have now is that one, which is incompatible with current version

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
The skull was never properly restored to be interactable once another player summoned a mini-boss.
