### ISSUE TITLE
Fel dom soul link bug

### ISSUE THREAD

**Issue by Scrynax** [ValorenWoW/sunstrider-core#5626]
In arena after fel domming pet and pressing soul link it does not apply, 2nd soul link application does but it costs me 1 GCD which is gamebreaking.

Clip: https://clips.twitch.tv/ZanyAntsyVelociraptorOpieOP-L2jgCOpT06DzXcZA

macro:
/cast soul link
/run local i = 7 if GetRaidTargetIndex("pet") ~= i then SetRaidTarget("pet", i) end

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
