### ISSUE TITLE
The Lost Pages quest items are not dropping

### ISSUE THREAD

**Issue by goffy59** [ValorenWoW/sunstrider-core#5627]
In Ashenvale when you kill mobs the quest item needed for this quest doesn't drop (multiple pages). Sometimes when you kill a mob it shows a box you cannot interact with.. not sure if its related but I figured it would be worth mentioning. I am playing on the horde side.

**Comment by Zlandicae** [comment]
You can loot them on Laughing Sister. (I did ^^)
https://www.wowhead.com/classic/npc=4054/laughing-sister

**Comment by goffy59** [comment]
right on thanks.
