### ISSUE TITLE
[Quest] - The Challenge

### ISSUE THREAD

**Issue by LSD7** [ValorenWoW/sunstrider-core#5628]
**Describe the bug**
Theldren NPC https://www.wowhead.com/classic/npc=16059/theldren doesn't drop https://www.wowhead.com/classic/item=22047/top-piece-of-lord-valthalaks-amulet

**To Reproduce**

1. Go to BRD
2. Place https://www.wowhead.com/classic/item=21986/banner-of-provocation
3. Kill Theldren

Quest: [The Challenge](https://www.wowhead.com/classic/quest=9015/the-challenge#comments)
NPC: https://www.wowhead.com/classic/npc=16059/theldren
Item: https://www.wowhead.com/classic/item=22047/top-piece-of-lord-valthalaks-amulet

**Expected behavior**
Theldren drops https://www.wowhead.com/classic/item=22047/top-piece-of-lord-valthalaks-amulet

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.

**Comment by LSD7** [comment]
> Thanks for the issue, fixed with the next update.

is it available after restart or we need to wait announce for update restart?
