### ISSUE TITLE
Netherspite - Red beam threat does not work correctly

### ISSUE THREAD

**Issue by Dollywog** [ValorenWoW/sunstrider-core#5630]
When you are hit by red beam - it gives you the:
https://www.wowhead.com/tbc/spell=30421/nether-portal-perseverence
Debuff - lasting 20 seconds

This debuff is meant to hold threat even when you are not in the red beam.   This is why you can pump on blue beam, at the moment, you lose threat to potential blue beam player when you step out of it to reset health and to not have too many stacks of the health decrease

https://www.youtube.com/watch?v=zxEAMfYj_Yo
View at 2mins this mechanic working as intended

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
