### ISSUE TITLE
No experience from Ally to the Netherwing quest.

### ISSUE THREAD

**Issue by rayomeara** [ValorenWoW/sunstrider-core#5631]
17th Nov, 2023

Was in a group of 5 to the the final quests for the Netherwing faction questline. We killed Zuluhead the Whacked, looted the key and freed the dragon. Upon this, received quest to fly with her and back to the questline originator to hand in. 

When we completed the quest, we were given no XP. Looking at my character, I am still 'hated' with the Netherwing faction.

Can this be looked into please.

Thanking you,

Garzoc.

**Comment by Dilson82** [comment]
I too had the same problem, was given only 550 rep with netherwing

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
If you're still not Neutral at this point, please open a ticket in-game or reach out to me on Discord: jerrythemagicdog.
