### ISSUE TITLE
pet hunter cant learn spells

### ISSUE THREAD

**Issue by Cyclope91** [ValorenWoW/sunstrider-core#5632]
I've bought the 70 climb and the hunter's pet can't learn any attacks or spells, please help

![WoWScrnShot_111823_174504](https://github.com/SunstriderEmu/BugTracker/assets/151391370/f6b9e44e-f989-4b3d-ba77-906b7430582b)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The spells are in your pet's talent tree.
