### ISSUE TITLE
withered bog lord - herbalism drops dont match tbc. 

### ISSUE THREAD

**Issue by ghost** [ValorenWoW/sunstrider-core#5636]
**Describe the bug**
drops do not match old endless TBC  drops.   
teracone and other herbs  have a 1% or less drop rate currently. 

**Character name**
spinsane / tankinabox

**To Reproduce**

1. kill withered bog lords in NE Zangermarsh and use Herbalism skill on them.
2. 
3. 

https://www.wowhead.com/tbc/npc=19402/withered-bog-lord#herbalism

**Expected behavior**
more herbs are supposed to drop.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
The drop rates from herbing the Withered Bog Lord are very close and in some cases higher for herbs than the ones listed on WoWHead.
