### ISSUE TITLE
Coilskar Cobra keeps casting Poison Spit while Polymorphed.

### ISSUE THREAD

**Issue by Vfonw** [ValorenWoW/sunstrider-core#5637]
Shouldn't keep using spells while polymorphed.

**To Reproduce**
Polymorph any Coilskar Cobra and still keep getting hit by Poison Spit from the polymorphed target.
Tested on the ones at Coilskar Point and outside the cave at Coilskar Cistern. Same behavior.

https://www.wowhead.com/tbc/spell=38030/poison-spit
https://www.wowhead.com/tbc/npc=19784/coilskar-cobra
https://www.wowhead.com/tbc/spell=12826/polymorph

**Comment by blblblaz** [comment]
fixed with next update, thanks for the report
