### ISSUE TITLE
Ruby Slippers

### ISSUE THREAD

**Issue by warg007** [ValorenWoW/sunstrider-core#5638]
**Describe the bug**
Hello. When I use HS ( [Hearthstone] ) , Ruby Slippers also get CD or vice versa.

**Character name**
Warg

**To Reproduce**
-

<>
[Item: https://wowhead.com?item=](https://www.wowhead.com/item=28585/ruby-slippers)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Every comment indicates that this is correct: https://www.wowhead.com/tbc/item=28585/ruby-slippers#comments
Is this a suggestion rather than a bug report?
