### ISSUE TITLE
No loot from Shade of Aran

### ISSUE THREAD

**Issue by Jakro98** [ValorenWoW/sunstrider-core#5639]
My guild raid killed Shade of Aran just before the server went off, when we logged the corpse and the items disappeared so we get 0 item from that kill.

The event occurred with the character Vecino in the "Inadaptados" guild and we do not have screenshots because it happened unexpectedly.

**Comment by Jerrythemagicdog** [comment]
This is a bugtracker for in-game issues, open a ticket in-game or contact @jerrythemagicdog or @blaze3043 on Discord for your problem!
