### ISSUE TITLE
ID lock without killing any boss (HC dungeons)

### ISSUE THREAD

**Issue by Roskanne** [ValorenWoW/sunstrider-core#5641]
Hello!

I entered alone in the Slave Pens, trying to sneak among mobs to go straight to the SSC quest.

Unfortunatelye, i got killed bya a patrol.

I check the LFM tool (specific HC dungeon) to find a group but I noticed that I am considered locked for this instance.

Thae fact is that I haven't killed any mob nor boss in this instance! My ID list is empty (only old ones and none of them are for the Slave Pens).

Thanks.

**Comment by Roskanne** [comment]
I entered HC Slave Pens*

**Comment by kelno** [comment]
Thanks, fixed with next update. Side not: until then you can just change your mode to normal then back to heroic and it fixes it.
