### ISSUE TITLE
[Quest] The battle of Darrowshire

### ISSUE THREAD

**Issue by Zlandicae** [ValorenWoW/sunstrider-core#5642]
**Describe the bug**

**Character name**

**To Reproduce**

1. Collecting the quest from Chromie
2. Journey to Darrowshire
3. Drop off the relic Bundle in the center of the town square.
4. Waiting for... Nothing... Nothing happen :p.

Item: https://wowhead.com?item= https://www.wowhead.com/item=15209/relic-bundle
Quest: https://wowhead.com?quest= https://www.wowhead.com/quest=27390/the-battle-of-darrowshire
Spell: https://wowhead.com?spell= None

**Expected behavior**

**Screenshots/videos**
Video of the quest bugging : https://www.youtube.com/watch?v=7KFQ4qknhQE

**Additional context**

**Comment by Zlandicae** [comment]
Some addition : https://www.youtube.com/watch?v=7KFQ4qknhQE

**Comment by Godmatik** [comment]
Quest needs to be fully scripted, right now nothing happens at all, confirmed

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
