### ISSUE TITLE
Improved Blizzard only affects one target

### ISSUE THREAD

**Issue by Dokandree** [ValorenWoW/sunstrider-core#5643]
**Describe the bug**
Mages with the improved blizzard talent are slowing only one NPC at a time inside a blizzard instead of all of the NPCs

**To Reproduce**

1. Have a mage with 3 points in Improved Blizzard talent (in the Frost tree). Having Permafrost also helps
2. Cast blizzard so that it affects multiple targets
3. Only one of the target will be affected by the chill effect, all others will not.

**Expected behavior**
Every target affected by improved blizzard should be slowed (given the mage has the proper talents)

**Additional context**
This was not an issue before today's changes. I'm not sure if this was intended to avoid abuse or not, but since I don't see this being mentioned in the changelog I'm assuming it's unintended.

**Comment by z5n** [comment]
fixed with next update
