### ISSUE TITLE
[ Quest ] The Cleansing Must Be Stopped

### ISSUE THREAD

**Issue by An4chr0n** [ValorenWoW/sunstrider-core#5645]
**Describe the bug**
Quest in Thrallmar. You are given a Signaling Gem to use near the Altar of Aggronar (in the Pools of Aggronar). But after using it at the altar, it never trigger the Draenei party to show up.

**To Reproduce**
Get the quest.
Use the Signaling Gem near the Altar of Aggronar.

Item: https://www.wowhead.com/item=23358/signaling-gem
Quest: https://www.wowhead.com/quest=9370/the-cleansing-must-be-stopped

**Expected behavior**
After you use the signaling gem, 3 draenei walk toward the altar, a lvl 62 is the quest target, and 2 paladins 57-58.

**Comment by An4chr0n** [comment]
Noticed that plantin the Gem on the northern area of the altar, make the Draenei popup, and they disappear some seconds after, so you have like 5 seconds to engage and complete the quest.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
