### ISSUE TITLE
[Open World] Herbs : Fel Lotus

### ISSUE THREAD

**Issue by tomcallejon** [ValorenWoW/sunstrider-core#5648]
**Describe the bug**
Since last server update, drop rate of FEL LOTUS are incredibly low ...

**Character name**
Badhorne

**To Reproduce**
I farm all day long in Terrokar forest and droped 2 ...
I farm all day long in Netherstorm and droped 1 ...
Before last server update i used to drop 10x per day 

I asked in World chat, and i'm not the only one to see it

**Expected behavior**
Can you please look to Fel Lotus Drop rate, and put it litle UP plz

Thanx for your work, i love this server :)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
There were no changes to Fel Lotus drop rates since the beginning of the server.
