### ISSUE TITLE
Thwart the Dark Conclave quest is broken (Shadowmoon Valley)

### ISSUE THREAD

**Issue by kizoin** [ValorenWoW/sunstrider-core#5649]
Current behavior:
Thwart the Dark Conclave quest can't be completed, unable to use the Staff of Parshah on the Summoned Old God even after the summoning event is disrupted by killing the 4 summoners.  

![image](https://github.com/SunstriderEmu/BugTracker/assets/4115286/9531d48b-68dc-40de-b3f7-2c403bfec917)

![image](https://github.com/SunstriderEmu/BugTracker/assets/4115286/88672162-2e71-4b58-b503-b10c88c15636)

![image](https://github.com/SunstriderEmu/BugTracker/assets/4115286/d0e73c99-f4aa-4b57-8756-1a46e3ab621a)

Expected behavior:
I should be able to use Staff of Parshah at the place I am standing, or alongside it, and complete the quest.  

Steps to recreate issue
Step 1: Go to 41.03, 60.84 in Shadowmoon Valley
Step 2: Kill 4 Dark Conclave Ritualists 
Step 3: Attempt to stand at the edge and use provided item from questgiver (Staff of Parshah)

Source
https://www.wowhead.com/tbc/quest=10808/thwart-the-dark-conclave

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The way the quest was previously done required the player to stand in a very specific spot to use the quest item.
Now players will be able to stand on any of the ritualists' spots once they've killed all of them, fix live with the next update.
