### ISSUE TITLE
Walking over a some buildings (on the roof), gets you dismounted. Example - The chopehouse in Orgrimar.

### ISSUE THREAD

**Issue by NikolayDzhigov** [ValorenWoW/sunstrider-core#5650]
**Describe the bug**

**Character name**

**To Reproduce**

1. Cast X on target affected by ...
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected behavior**

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, it's been around for a while now, it will be resolved with the next client update.
