### ISSUE TITLE
Prayer of Mending T4 2 pieces Set Bonus

### ISSUE THREAD

**Issue by Ronove123** [ValorenWoW/sunstrider-core#5651]
**Describe the bug**
<T4 2 set bonus for Holy Priests says that Prayer of Mending should leave a Hot, that's not happening>

**Character name**
<Ronove>

**To Reproduce**
<I tried it tons of times on ppl on Dungeons, when Mending is activated there's no hot>
(https://www.wowhead.com/tbc/item=29049/light-collar-of-the-incarnate)
(https://www.wowhead.com/tbc/spell=33076/prayer-of-mending)

**Expected behavior**
<Set bonus says: "Your prayer of healing spell now also causes an additional 150 healing over 9 sec>

**Comment by Jerrythemagicdog** [comment]
The effect mentions Prayer of Healing, not Prayer of Mending.
