### ISSUE TITLE
Mining and enchanting stuck at Vanilla 

### ISSUE THREAD

**Issue by Reafuzz** [ValorenWoW/sunstrider-core#5652]
**Describe the bug**
I have been leveling my mining and enchanting to 300+ for the Burning Crusade. While smelting Thorium the selection bar went from green to gray once I hit skill level 291/375. Now both my professions will never reach the skill needed for the expansion pack. 

**Character name**
This was on Reafuzz

**To Reproduce**

1.  Try to level both mining and enchanting to 300

**Expected behavior**
I expected the skill bar to stay green so the skill level would reach 300.

**Screenshots/videos**

![mining issue for BC](https://github.com/SunstriderEmu/BugTracker/assets/160459228/7cbb72a0-1e96-459a-bd46-a316adc5a758)

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Please refer to:
https://www.wow-professions.com/tbc/mining-leveling-guide-tbc-classic#smelting
