### ISSUE TITLE
Spell queue issue

### ISSUE THREAD

**Issue by disis24** [ValorenWoW/sunstrider-core#5654]
With the new spell queue system, while spaming your steadyshot, you get your GCD triggered at the end of a steady shot sometimes if you spam any instant ability without GCD (like a pot, or kill command) during the steady cast.

Tested as BM with 3.0 bow, can provide a video if needed.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, please test again after tomorrow's update.
