### ISSUE TITLE
Seal of Righteousness not getting its own 50% chance to proc judgement of light self-heal on target

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5656]
**Describe the bug**
On Official, and any other private server I have played paladin on, seal of righteousness bonus damage portion against a target judged with judgement of light (or wisdom) gets its own 50% chance to proc the judgement effect, resulting in additional self-heals or mana regains. On Sunfury it does not, probably a bug unless an intentional nerf has taken place.

**Character name**
Tested on my Paladin Dalzedur

**To Reproduce**

1. Judge seal of light/wisdom on target
2. Activate seal of righteousness
3. Land autoswings on the target and observe if 50% of the attacks proc heal, or if 75% of the attacks proc heals

Seal of Righteousness: https://www.wowhead.com/tbc/spell=20154/seal-of-righteousness
Judgement of light: https://www.wowhead.com/tbc/spell=20346/judgement-of-light

**Expected behavior**
Basically, when a target is judged with the judgement effect from seal of light or seal of wisdom, they get 'debuff' where anyone landing attacks (melee only for light iirc, any for wisdom) there is an exactly 50% chance for that attack, regardless of the attack/weapon speed, to proc the judgement effect, letting the attacker regain some hitpoints or mana. (tangent, unrelated to the bug: whereas the normal on-hit self-heal of seal of light is ruled by a procs-per-minute value, making slow attacks more likely to proc the self-heal and fast attacks less likely, but overall the amount of procs in a period of time should be the same +/- rounding errors)

The bonus damage portion from an active seal of righteousness also gets its own check to proc that 50% chance, allowing the paladin to proc the judgement TWICE with a single autoswing. (25% chance not to proc on either, 50% chance to proc on one, 25% chance to proc on both the attack and the seal portion, resulting in two self-heals from that single attack). 

I believe, but it's difficult to test it out, but seal of righteousness normally gets its own roll to proc any 'on attack' effects of the wielded weapon, such as the 85 arcane damage of Archeus (Mor'Ladim sword) or even the chain lightning of Thunderfury, maybe even player-enchanted effects such as Crusader or Fiery weapon. I think the code for seal of righteousness does some kind of an umbrella function call that covers all those cases, as in, if you correctly fix one proc issue, the others get fixed as well.

The few cases of gaining a double self-heal that I saw was due to reckoning making the hit land twice, so that's one source of false positive to be aware of.

Dalzedur's melee swing hits Training dummy for 45 Physical.
Dalzedur's Seal of Righteousness hits Training dummy for 40 holy.            <- the 'bonus damage portion' I refer to
Dalzedur gains 0 health from Dalzedur's Judgement of Light. (34 Overhealed)   <- when bug is fixed, this line can appear twice

**Screenshots/videos**

**Additional context**

The bug is probably in seal of righteousness code, not in judgement of light/wisdom code. Tested on both target dummies and actual hostile enemies, with hitpoints also not being at full.

Basically, if fixed, a solo paladin at low world content would choose from:
seal of righteousness against judgement of light enemy - 2nd best self-heal, potentially highest dps (holy ignores armor)
seal of crusader against judgement of light enemy - worst self-heal, potentially highest dps (physical reduced by armor)
seal of light against judgement of light enemy - highest self-healing, lowest dps

But while the bug persists, seal of crusader with its +40% attack speed is better for self-heals than seal of righteousness.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
There indeed seems to be an issue with Judgement of Light not being able to proc from SoR damage.
Judgement of Wisdom already works correctly.
Fixed with the next update.
