### ISSUE TITLE
Draenai race quest that requires use of the Gift of the Naaru

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5657]
**Describe the bug**
If you play a draenei but change your racials to the racials of some other race, you no longer have Gift of the Naaru racial. Yet, the starting zone Ammen Vale at Azuremyst Isle for Draenei has a quest where you need to heal a Draenei Survivor with that ability specifically. You can still take the quest even if you don't have the ability, making it impossible to be completed. It is intended to be a racial ability tutorial quest in TBC, afaik, so maybe altering the requirements for being able to take the quest should be a fix (no Gift, you can't accept the quest), or make any healing trigger the 'rescued' part of the npc script, allowing you to finish the quest with, let's say, bandages if you have no other heals.

**Character name**
Qirana

**To Reproduce**
1. Create a draenai character, but change racials to those of another race
2. No longer have Gift of the Naaru
3. Find yourself unable to cast Gift of the Naaru on the Draenei Survivor, making it impossible to get the quest completion

NPC: https://www.wowhead.com/tbc/npc=16483/draenei-survivor
Quest: https://www.wowhead.com/tbc/quest=9283/rescue-the-survivors
Spell: https://www.wowhead.com/tbc/spell=28880/gift-of-the-naaru

**Expected behavior**
Well, normally you do have that ability, so this quest being 'broken' is your own fault. But that doesn't mean that it cannot be or should not be adjusted to reflect the current status of things.

**Screenshots/videos**

**Additional context**
The quest is the final part of a short quest chain and gives a 4 slot bag as a reward, which could be very desirable for a new character, given how there are no mailboxes nearby.

Healing the Draenei Survivor to full with any other ability besides the Gift of the Naaru does not yield a completion for the quest.

**Comment by Dalzedur** [comment]
Similar 'obstacle' might plague the other quest where Gift of the Naaru is needed, with Draenei Youngling
Quest: https://www.wowhead.com/tbc/quest=9612/a-hearty-thanks
NPC: https://www.wowhead.com/tbc/npc=17587/draenei-youngling

To get the quest, you need to assist the Draenei Youngling with Gift of the Naaru while they are in combat with a hostile npc. Healing them with lesser heal or renew does not work towards getting the quest.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, this will be a "deal with it" angle though, there are plenty of other options to choose from on a higher-rate realm.
