### ISSUE TITLE
Amani Berserkers in Eversong Woods have a bonkers enrage

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5658]
**Describe the bug**
When the lvl 9-10 non-elite enemy Amani Berserker enrages, they (according to tooltip of their enrage buff) gain bonus 50 damage to each of their attacks and +60% attack speed. It's likely the wrong rank of enrage. Looking at WoWhead, it likely should be +1 damage and +30% attack speed.

NPC: https://www.wowhead.com/tbc/npc=15643/amani-berserker#abilities
Spell: WoWhead points to the correct enrage being: https://www.wowhead.com/tbc/spell=8599/enrage

**Expected behavior**
Not get chopped to pieces on a level 18 priest against a level 9 gray non-elite enemy.

**Comment by blblblaz** [comment]
fixed with next update, thanks
