### ISSUE TITLE
Dialogue/Quest order-priority of talking to Pratt McGrubben

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5659]
**Describe the bug**
Talking to Pratt McGrubben in Feralas won't let you access his vendor inventory, only his offered quest. He is a leatherworking supplies vendor with recipes to sell. Normally on official, talking to him opens up a dialogue menu with an option to choose either the quest of his or the other option of seeing what he has up for sale. I wonder if his Horde counterpart has the same issue?

**Character name**
Dalzedur

**To Reproduce**
1. Talk to Pratt McGrubben in Feralas
2. He should only offer you his quest, the mark of quality. Could be different if the character is too low level to get the quest?
3. No idea if completing both of his quests lets you finally access his vendor inventory as it stands

NPC: https://www.wowhead.com/tbc/npc=7852/pratt-mcgrubben
Possibly also, unable to test since I lack a high lvl horde character: https://www.wowhead.com/tbc/npc=7854/jangdor-swiftstrider

**Expected behavior**
Normally vendors who offer quests let's you choose a dialogue option to either access the quest or the vendor inventory. Such as the trade vendor in Tarren Mill who also offers the quest for turtle meat recipe (cooking 175).

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
The Horde version of this NPC has their gossip working correctly.
