### ISSUE TITLE
The Holy Spring in STV not containing holy spring water

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5660]
**Describe the bug**
The Holy Spring, guarded by naga, in STV is supposed to always contain a holy spring water, a 5min cooldown consumable that heals, dispels debuffs and replenishes mana (according to wowhead). The Holy Spring water is also a quest item, but it is one of those cases where you can get the water for its consumable properties despite not being on the quest that needs it. Except... right now the holy spring container that you interact with opens to an empty loot window.

**Character name**
Dalzedur

**To Reproduce**
1. Be in STV, possibly kill the rare naga Lord Sakrasis guarding the spring
2. Interact with the spring, the character starts looting it (progress bar appears)
3. Upon finishing the task, a window opens up that should contain 1 lootable holy spring water, as if you are looting a chest

Item: https://www.wowhead.com/tbc/item=737/holy-spring-water
Object: https://www.wowhead.com/tbc/object=759/the-holy-spring

**Expected behavior**
Regardless whether or not the character is on the quest Sweet Amber (alliance only, Westfall), the spring water can be looted from the holy spring.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
