### ISSUE TITLE
Contagion of Rot debuff 'double stacking'

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5661]
**Describe the bug**
Contagion of Rot is a debuff inflicted by some ghouls, at least in Duskwood. It has a 5% chance of spreading when hit, allowing it to erroneously double stack on the victim. First, by being initially inflicted by the undead, then another time by having that 5% chance of spreading it occur. The duration is 4 minutes for the debuff.

**Character name**
Valendra

**To Reproduce**
1. Fight the ghouls (fetid corpse) outside of Stalvan Mistmantle's cabin.
2. Get inflicted with Contagion of Rot
3. Keep getting hit in combat, proccing the debuff's condition to spread further -> two debuff icons on you now.

NPC: https://www.wowhead.com/tbc/npc=1270/fetid-corpse
Spell1: https://www.wowhead.com/tbc/spell=7102/contagion-of-rot
Spell2: https://www.wowhead.com/tbc/spell=7103/contagion-of-rot

Spell1 generates Spell2 through spreading, allowing both of them to debuff the original target at the same time. This should not happen. The spread function of either spell should remove the debuffed entity from the list of eligible targets that it spreads to.
Or easier yet, make it so that 7103 cannot be applied to target who has 7102 already. Not sure if it should reset the duration back to 5 minutes when it reapplies it to on top of itself, though.

**Expected behavior**
It is worth noting that the first debuff has 5% chance to spread, but the debuff generated through spreading has 10%. I'm not sure what the logic of them being different is, but when either of them spread, it should not debuff the original target from whom it spreads from, because then it allows the debuffing effects to 'double stack', turning a 2.8 speed melee attack into close to 5 second (4.95) swing timer (16/9 times the original speed, since the behaviour is 4/3 x 4/3 not 3/3 + 1/3 + 1/3), with two +33% debuffs into it. For four minutes' time.

**Additional context**
I've never had it behave like this on any server I've ever played on, including official.

UPDATED: fixed erroneously stated five minute duration to four minute duration

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with next update.
This also affected some other spells like Wandering Plague (3436) which are now also fixed in a generic way.
