### ISSUE TITLE
Ashenvale rare Branch Snapper resistances?

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5662]
**Describe the bug**
I fought against Branch Snapper on my lvl 38 mage. He seemed to roll a lot of 75% and full resists against the mage's spells. Wondering if those resistance values are meant to be that high, since as a player and using the resources I have at my disposal, there isn't really way for me to see if the resistance values are working as intended. WoWhead comment section only talks about frost being highly resisted, but seems like all 3 types were.

**Character name**
Exolon

**To Reproduce**
1. Cast stuff at Branch Snapper, watch what the battle log says

NPC: https://www.wowhead.com/tbc/npc=10641/branch-snapper

**Expected behavior**
With level difference of 13 to my favor, I'd have expected it to be a cakewalk.

**Screenshots/videos**

**Additional context**
Snippet from the Combat Log:
Exolon's Frostbolt was fully resisted by Branch Snapper.
Exolon's Frostbolt hits Branch Snapper for 291 Frost.
Exolon's Fire Blast hits Branch Snapper for 73 fire. (216 Resisted)
Exolon's Cone of Cold was fully resisted by Branch Snapper.
Exolon's Arcane Explosion was fully resisted by Branch Snapper.
Exolon's Arcane Explosion hits Branch Snapper for 37 arcane. (110 Resisted)
Exolon's Arcane Explosion hits Branch Snapper for 37 arcane. (110 Resisted)
Exolon's Arcane Explosion hits Branch Snapper for 75 arcane. (74 Resisted)
Exolon's Fire Blast hits Branch Snapper for 69 fire. (206 Resisted)
Exolon's Frostbolt was fully resisted by Branch Snapper.
Exolon's Frostbolt was fully resisted by Branch Snapper.
Exolon's ranged shot hit Branch Snapper for 10 Arcane. (28 Resisted)
Exolon's ranged shot hit Branch Snapper for 15 Arcane. (14 Resisted)
Exolon's ranged shot hit Branch Snapper for 7 Arcane. (18 Resisted)
Exolon's Fire Blast hits Branch Snapper for 85 fire. (127 Resisted) (42 Overkill)

Frost - 4x 100% resisted, 1x 0% resisted; Fire - 3x 75% resisted; Arcane - 1x 100% resisted, 4x 75% resisted, 2x 50% resisted

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
Here's a breakdown of Branch Snapper's resistances:
200 to Arcane
250 resistance to Fire, Nature, Frost,
375 to Shadow.
Information about stat values is taken directly from official servers and, unless a mistake was made, is as good as it gets.
This seems to be the case here as many other sources have the same values.
