### ISSUE TITLE
Stranglethorn Fever quest wave timer & enrage abilities of the gorillas

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5663]
**Describe the bug**
The quest Stranglethorn Fever in STV is a wave defence against 3 waves of enemies: An enraged silverback gorilla, Konda, and Mokk the Savage. 2 Issues:

Firstly, on this codebase there seems to be a timer that starts ticking once you start the quest that will then force the 2nd and 3rd wave enemies to spawn, regardless of if you're still fighting the previous enemies or not. On official I believe the next wave won't start until you have completed the current one, but there was maybe hardly any downtime between the waves there. Enough to at least start eating/drinking though.

Second issue is the enrage ability of the gorillas in question. On this codebase, they use a bonkers enrage giving them 60% attack speed bonus and from 80 to 86 bonus damage per hit, whereas on Official the enrage gives all three +1 damage to attacks and +30% attack speed. The first time I attempted the quest on an alt, I didn't realize their enrage was off the charts and got quickly brutalized with 200+ damage blows, even before Mokk the Savage came out.

**To Reproduce**
1. Talk to Fin Fizracket in Booty Bay to get the quest.
2. Get a gorilla fang
3. Talk to Witch Doctor Unbagwa
4. Start the wave defence
5. Apply vaseline (optional, but recommended)

Quest1: https://www.wowhead.com/tbc/quest=348/stranglethorn-fever
Quest2: https://www.wowhead.com/tbc/quest=349/stranglethorn-fever

Enraged Silverback Gorilla: https://www.wowhead.com/tbc/npc=1511/enraged-silverback-gorilla
Enrage on Official, of the Enraged Silverback: https://www.wowhead.com/tbc/spell=8599/enrage

Konda: https://www.wowhead.com/tbc/npc=1516/konda
Enrage on Official, of Konda: https://www.wowhead.com/tbc/spell=8599/enrage

Mokk the Savage: https://www.wowhead.com/tbc/npc=1514/mokk-the-savage
Enrage on Official, Mokk the Savage: https://www.wowhead.com/tbc/spell=8599/enrage

**Expected behavior**
A wave defence of 3 waves. 1 enemy per wave. The next wave won't start before you've cleared the currently ongoing one. I think that's how it was in TBC, it may have been harder during vanilla, at least I remember people going out of their way to do it in groups.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
Enrage spells were corrected, we'll keep the wave timers as they are now.
