### ISSUE TITLE
Gryphoneer Leafbeard taxi service

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5664]
**Describe the bug**
Alliance NPC Gryphoneer Leafbeard in far northeastern corner of Hellfire Peninsula does not have a dialogue option to taxi the player back to Shatter Point, even though that's his one job. Basically, this is the guy in the back corner of the three demon camps, you fly to this location from Shatter point to kill 10 Gan'arg servants, Razorsaw, then 3 Fel Cannon MKI's and then Warbringer Arix'Amal (and get a item that gives a quest turn-in) in a quest chain of 3 quests long. When you are done with those, the NPC is the one you talk to in order to get back without having to go through enemy lines including the Horde areas of the Peninsula.

**Character name**
Dalzedur

**To Reproduce**

1. Talk to Gryphoneer Leafbeard
2. And only get gossip, with no options.
3. Bummer.

NPC: https://www.wowhead.com/tbc/npc=20236/gryphoneer-leafbeard

**Expected behavior**
There should have been a dialogue option to 'Send me back to Shatter Point!' or something along such lines, which then triggers his Taxi service ability from beach head to Shatter Point.

**Additional context**
I don't know if he offers the service back at all times, or if there is some prerequisite that has to be met first. Doing the quests in order to get sent here should be enough to have the option to go back, regardless.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
You currently only get the option to fly back when you're on this quest: 
https://www.wowhead.com/tbc/quest=10340/shatter-point

It seems that's incorrect and we should be allowed to fly there even without any of the quests completed.

> Biaxident (3,723 – 8·46) on 2009/02/25 (Patch 3.0.9)
> He'll allow you to travel to Shatter point without having completed the questline leading there.

Fixed with next update.
