### ISSUE TITLE
Succubus Minion (Bloodsail Warlock) lash of pain damage?

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5665]
**Describe the bug**
In STV, Bloodsail Warlock can spawn with a succubus minion. The succubus minion uses lash of pain as her combat ability in addition to autoswings. It (the lash of pain) just seems to hit too hard for what I remember them to do, but I cannot navigate and find the proper lash of pain in WoWhead to make it any easier fix, sorry. My hunch is that it's just the wrong version of the ability being given to the succubus minion, rather than it scaling weirdly with the minion's level, although the minion is listed as having a variable level from 20 something to 60 something, so it *could* plausibly use a lvl 60 value for it, but then we'd see a lvl 20 succubus minion hitting for 310 shadow damage as well if that were to be the case and so far I haven't seen that.

**Character name**
Valendra

**To Reproduce**

1. Attack a Bloodsail Warlock who has spawned with a Succubus Minion in STV, they're around lvl 40-43
2. Get skilled at by the minion
3. See it hitting for over 300 shadow damage. (two landed, both hit exactly 310 shadow btw)

Warlock
https://www.wowhead.com/tbc/npc=1564/bloodsail-warlock

Their spell that generates the minion
https://www.wowhead.com/tbc/spell=8722/summon-succubus

The minion
https://www.wowhead.com/tbc/npc=10928/succubus-minion

WoWhead doesn't actually even list succubus minion  having a lash of pain ability so that I could link it here, but they do have that ability on official, iirc.

**Expected behavior**
Well, the warlock's own casting timed and thus interruptible shadow bolt only hit for 232 shadow damage, would make sense that the minion, whose lash of pain is instant and thus cannot be kicked or counterspelled would not hit for 310 shadow damage. If we draw comparisons to player warlock, the lash of pain for a player pet succubus is significantly lower than what the shadow bolt of the warlock is. If I had to give a gut estimate of how hard the enemy succubus minion at lvl 40-43 should hit, I'd say around 90-100 shadow damage.

**Additional context**
Could be a wider minion dps issue, I see the summoned imp firebolting for 80+ damage on the same Bloodsail Warlock. It's not a nonphysical-damage-bypasses-armor-reduction therefore seeming higher in comparison to melee damage, either.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the Succubus and the Imp were using generic spells that scale with their level, Blizzard tends to use player pet's spells for creature pets though.
Fixed with the next update.
