### ISSUE TITLE
Potential attack speed overlook issue on (STV, potentially all) enemies

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5668]
**Describe the bug**
I'm not too sure about this, but it feels like the fast hitting enemies in STV (young stranglethorn tigers, young panthers) are doing more damage than I remember them doing on other codebases. I observed tigers hitting my druid for 34-44 damage per non-crit melee swing, the value is basically the same for young panthers - they both are around lvl 30-31. As a hunter pet option, cats do have higher dps than most other pets, and as far as I know, those racial bonuses do apply even to npc enemies - bears have more hitpoints than other beasts of similar level.

But, my brother also remarked how the young tigers hit his character harder than he expected them to, so there's possibly something there. If I had to warrant a guess, the enemies are using some kind of a default damage value for their auto-attacks, which is not adjusted for their faster attack speed or only a portion of it is but some base damage value is not. Basically, it feels like a portion of the damage seems to be treated the same way attack power would be adjusted for fast or slow weapons with regards to how much damage they increase to each swing, but there is also part of the whole that is not, which then turns into elevated dps when the swing speed is faster than default... 2seconds per swing? Petopia for vanilla lists young stranglethorn tiger attack speed (as a pet) being 1.3, but that's a version of WoW where pets used the attack speed value they had before being tamed, whereas river crocolisk has 2.0 attack speed (which I believe is the enemy default value). So, we basically have an enemy hitting more than 50% as often doing -4 damage per hit in comparison

Yet, the river crocolisks and stonemaw basilisks, also the same level range, have a slower attack speed in comparison, but the damage they deal is slightly higher per swing (38-48 on basilisk, so +4 points higher against armor value 889 (21,47% reduction against lvl 34 enemies)), so I'm not entirely sure anymore - there is some adjustment for attack speed there, but let's observe the hard values:

Attack speed 2.0 : Damage per swing 38-48, average 43, DPS 21.5?
Attack speed 1.3 : Damage per swing 34-44, average 39, DPS 30?
Against my armor 889 lvl 34 druid.
The average damage for speed 1.3 to be DPS 21.5 - equal dps to 2.0 attack speed, should be 27,95, so 23-33 ish?

It seems like there is a huge dps increase for a faster attack speed in this case with the values I observed, but then again, that could be working as intended with the cat racial bonus to dps... although it should be more like +10%, not +50%.

**Character name**
Elillinr

**To Reproduce**
1. Observe battle log as enemy keeps hitting you, record the lowest and highest damage non-crit (with no reduction false positives)
2. Perform calculations: Average damage, average damage / attack speed
3. Compare

Young stranglethorn tiger: https://www.wowhead.com/tbc/npc=681/young-stranglethorn-tiger
Young panther: https://www.wowhead.com/tbc/npc=683/young-panther
River crocolisk: https://www.wowhead.com/tbc/npc=1150/river-crocolisk
Stone maw basilisk: https://www.wowhead.com/tbc/npc=688/stone-maw-basilisk
Note: Stone maw basilisk is not tameable, afaik, not sure if it matters or not

**Expected behavior**
I would have expected the faster hitting cats to land hits that deal around 20-29 damage based on how I remember them to have done, but maybe those were against mail users, not leather users. The difference between 22% reduction and 33% or 40% reduction isn't that high, regardless. If we use rough estimates, we increase the value by 25% first (0,8 -> 1,0) to get how much they'd have hit against 0% reduction, then calculate from there x 0,66 vs mail user, x 0,6 vs mail user with shield. So 39->50, and 0,66x50 = 35, and 0,6x50 = 30. Hmmh, 30 vs mail+shield still seems higher than it should, imo.

**Additional context**
This issue, if found to exist, probably plagues all enemies everywhere using default values/scaling, if they have a faster than 2.0 attack speed, which is likely the expected default value. Is the game playable if this remains unadressed - I'd say yes. It has been playable thus far. I'm not sure how much it would alter lvl 70 content if it were to be fixed/adjusted.

**Comment by blblblaz** [comment]
Hunter pet specific things such as Pet Family bonuses don't apply to creatures in the open world, they only apply once the creature becomes a pet.

To your attack speed point - the vast majority of generic open world creatures use the same formula for their damage, and attack speed has no relation to that, it's just a stat that creatures have. The fact that https://www.wowhead.com/tbc/npc=681/young-stranglethorn-tiger has 1.3 attack speed doesn't mean his DPS gets adjusted to match the DPS of a 2.0 attack speed creature.
