### ISSUE TITLE
Wild Leather (Leatherworking profession) Quests for Alliance

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5669]
**Describe the bug**
Leatherworkers get a quest chain to learn Wild Leather recipes at skill 200 in Feralas. For Alliance, the NPC who gives the quest line is Pratt McGrubben, an NPC that I previously reported for having buggy dialogue options. While his dialogue options are now fixed to a degree of being able to access his vendored items and start the Mark of Quality quest, the option to get started with Wild Leather is not there. As far as I know, the only requirements for getting that Wild Leather Armor quest chain is enough skill (200 leatherworking) and required level 30.

**Character name**
Desparossa

**To Reproduce**

1. Meet prerequisites for Wild Leather Armor quest
2. Talk to Pratt McGrubben
3. See no option offered for Wild Leather Armor

The 1st quest in the quest chain: https://www.wowhead.com/tbc/quest=2847/wild-leather-armor
Pratt McGrubben: https://www.wowhead.com/tbc/npc=7852/pratt-mcgrubben

**Expected behavior**
The option to get started with Wild Leather Armor quest should be there once you meet the prerequisites: Level 30, and 200+ leatherworking skill. It doesn't require the completion of the Mark of Quality / Improved Mark of Quality / Pristine Yeti Hide quests.

**Additional context**
You need to master the Wild Leathers in vanilla to be able to become a specialized Tribal Leatherworker. While the specialization recipes of vanilla (such as Wolfshead helmet) no longer require the specialization in TBC, the specialization recipes of TBC may. The Wild Leather quest chain is 7 quests long and gives 29050 xp total (further modified by the xp multiplier, so 145250 with 5x)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue.
The quests currently require 225 Leatherworking skill, matching the pattern's required skill.
We'll set the requirement to 200 to match wowhead's data.
Fixed with the next update.
