### ISSUE TITLE
Projectile effect of summoned imp (enemy) firebolt lingering indefinitely

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5670]
**Describe the bug**
From what I can tell, when a summoned imp minion of an npc caster casts a firebolt, and the projectile is still in the air and has not connected with its target - if the imp was to die at that time, before the firebolt projectile lands, the visual effect of the projectile will then linger indefinitely on top of the target's model, chasing it but being unable to initiate a 'hit'.

I've seen this happen in Redridge Mountains, when doing Corporal Keeshan escort. By its end, he'll have his personal arsenal of fireflies buzzing on his chest. I've seen this happen in STV, with bloodsail casters with imps and so on. The bug is probably in the firebolt code, but it might also be in the way the game handles summoned minions. Basically, it needs a killswitch check, like when the summoned imp dies, it calls all its firebolt children to cease, or have some kind of a timer added to the projectiles that forces them to cease after N seconds of having existed, shrug. It very well could be that the bug is the projectile trying to make queries to the caster object when it's supposed to calculate the effects of registering a hit, but because the caster is dead, the pointer to the caster object returns an error, since the caster object no longer exists, making the hit register function error out as well?

**To Reproduce**

1. Have a summond imp (enemy?) cast a firebolt at a target
2. While the firebolt is in the air, kill the imp
3.  The firebolt bugs out, chasing the target indefinitely (often, because it is faster, overimposing itself over the target's model)

NPC: https://www.wowhead.com/tbc/npc=12922/imp-minion
Ability: https://www.wowhead.com/tbc/spell=20801/firebolt

**Expected behavior**
The firebolt should vanish when the imp dies, or is dead, or when it connects with the target.

**Additional context**
I haven't started a warlock of my own on this server yet, so I can't say for sure if this plagues player's imps as well. It could be tricky to test, probably having the imp cast spells at a target who is further away, while some other source of damage kills the imp.
I have not seen any other spell projectile behave in this manner so far, so they are probably handling it right.

**Comment by Jerrythemagicdog** [comment]
Thanks, there is a fix pending for this already, live with next client update.
