### ISSUE TITLE
Enemy using an ability while under the effects of Hibernation

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5671]
**Describe the bug**
In Feralas, a longtooth runner aggroed at me when I was picking flowers. I hibernated it to be able to pick up a herb. While under the hibernation effect, it used the furious howl ability. Not very game breaking, unless this leads to discovery of something else that they can do while asleep that they shouldn't, like maybe store bonus attacks to thrash and unload them all after waking up, shrug.

**Character name**
Elillinr

**To Reproduce**

1. Cast Hibernation on Longtooth Runner
2. Observe how it turns red and gains a buff, while asleep, buff icon says furious howl
3. X-files music plays

https://www.wowhead.com/tbc/npc=5286/longtooth-runner
https://www.wowhead.com/tbc/spell=24603/furious-howl

**Expected behavior**
Despite having very little effect on actual gameplay experience, enemies shouldn't be using abilities while asleep, unless it's something like divine shield or will of the forsaken (do npcs even have it ever?) that is genuinely usable while incapacitated and used to dispel the cc at the same time.

**Comment by Jerrythemagicdog** [comment]
Maybe it was just having a very angry dream!
Thanks for the issue, fixed with the next update.
