### ISSUE TITLE
Ancient Stone Keeper in Uldaman not using an ability

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5673]
**Describe the bug**
In Uldaman, there's a boss called Ancient Stone Keeper. Its most annoying ability by far is summoning those pesky tiny homing tornadoes that periodically slow and silence the character caught in them. The movement speed debuff is so severe that escaping the tornado, once caught in them, is difficult, and being caught in them as a caster applies silence periodically, making casting quite impossible. Yet, when I soloed Uldaman for mageweave cloth, this boss didn't use the ability even once. Either A) outright not even trying to use it, or B) the ability is erroneously being given some kind of a hit-roll / chance to be resisted, even though there is no mention in the battle log of the ability being even used, let alone missing or being resisted. If B, then my (way overleveled) character prevented the tornadoes from spawning through level difference alone. The battle did last for quite a while, since the character's dps is not that impressive, so if the ability was on its list of combat tricks, it should have been given several opportunities to be used through the length of the fight alone.

**Character name**
Dalzedur

**To Reproduce**
1. Attack Ancient Stone Keeper
2. Ancient Stone Keeper is not using its ability
3. Ancient Stone Keeper dies

ASK: https://www.wowhead.com/tbc/npc=7206/ancient-stone-keeper
Abi1: https://www.wowhead.com/tbc/spell=10094/sand-storms
Abi2: https://www.wowhead.com/tbc/spell=10132/sand-storms

**Expected behavior**
There should be tiny tornadoes that home and pester the player characters throughout the fight.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The tornado will currently only target players within 10-30 yards.
We're keeping it this way.
