### ISSUE TITLE
Deserter Lieutenant's Shield Bash seems to have long range

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5675]
**Describe the bug**
The shield bash ability used by Deserter Lieutenant doesn't seem to have its normal 5 yard range requirement. This allows them to shield bash casters at range as soon as they detect that the enemy is casting a spell. Tested this by chaining ranged spells at one, the moment the first spell landed, and I had already casting the 2nd one (started while the projectile was still in the air), the lieutenant enters combat and shield bashes me. If I wasn't casting a 2nd spell already when they aggroed, the shield bash wasn't used. I ran away a few seconds, started casting a spell to test what happens, and immediately upon starting the spellcasting the enemy shield bashes me, again from a range greater than 5 yards. So, the AI seems to be functioning as intended, it's just the range of the ability that is bonkers.

**Character name**
Exolon

**To Reproduce**

1. Aggro Deserter Lieutenant
2. Get shield bashed the instant you are casting, regardless of the range
2b. If you had started casting your follow up spell while the projectile was still in the air streaking towards the lieutenant, now you get interrupted by the bash immediately upon the lieutenant entering combat and can't cast spells of that school for N seconds. You can basically use this to bait the bash by having started to cast a spell from a school that you didn't plan on casting, like, a fireball if you are a frost mage and plan on nuking it with frostbolts. Then the school interruption lands on the fire school and you can easily take him out with frost magic.

Deserter Lieutenant: https://www.wowhead.com/tbc/npc=23637/deserter-lieutenant
Shield bash (range: 5 yards): https://www.wowhead.com/tbc/spell=11972/shield-bash

**Expected behavior**
They shouldn't be able to use shield bash from a distance greater than 5 yards.

**Additional context**
I was solo when I tested this, not sure what happens if a party aggroes it and a caster who is not the main threat target starts casting.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
