### ISSUE TITLE
Quest-script spawned Lurking Shark lvl 1 instead of lvl 37

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5676]
**Describe the bug**
In Dustwallow Marsh, quest Nat's Bargain has you lather yourself with fishing paste, then swim to a nearby shipwreck to attract a shark. This shark is normally lvl 37 when it spawns, on this codebase it seems to be lvl 1.

**Character name**
Exolon

**To Reproduce**
1. Use Pagle's Fish Paste Extra Strength
2. Swim closer to the shipwreck
3. Get sharked on!

Lurking Shark: https://www.wowhead.com/tbc/npc=23928/lurking-shark
Quest: https://www.wowhead.com/tbc/quest=11209/nats-bargain
Fish paste: https://www.wowhead.com/tbc/item=33166/pagles-fish-paste-extra-strength
Applying paste gives you: https://www.wowhead.com/tbc/spell=42644/nat-pagles-fish-paste

**Expected behavior**
Normally the shark that spawns is lvl 37 and has hitpoints appropriate for it, not lvl 1 with 42 hpmax.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
