### ISSUE TITLE
Southsea Freebooter in Tanaris aggroing and shooting through a wall of the Stoley's Shipment house

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5677]
**Describe the bug**
In Tanaris, there is a quest Stoley's Shipment where you need to enter the upstairs of a house in the pirate cove to interact with a bunch of crates. The house contains 6 Southsea Swashbucklers, 3 in the lobby, 3 in the backroom. When clearing these Swashbucklers, one of them fled in terror upon reaching low hps, and proximity aggroed a Southsea Freebooter (musket pirate) by fleeing next to the house's wall - the freebooter was outside just on the other side of that wall. This resulted in the freebooter aggroing at my character, and the enemy was able to repeatedly use their ranged attack through that wall, without having to pathfind inside the house to have a clear line of fire. Upon my character going upstairs, the enemy was finally forced to navigate upstairs after me. This leads me to suspect that at least one wall of that house doesn't count as a line of effect obstacle, even though it might block movement. I'm not sure if proximity aggro should work through those walls either, I remember sometimes possibly pulling enemies through the walls on official, but it might have been a pet glitching through the wall that body pulled.

**Character name**
Exolon

**To Reproduce**

1. Aggro a Southsea Freebooter in Tanaris, the one between the Stoley's shipment house and the house next to it.
2. Go indoors and see if they can fire at you through the wall(s).

**Expected behavior**
Walls should generally block line of effect. There is no issue with the NPCs in question as far as I understand, unless the placement of that freebooter is too close to the house, making it glitch inside that wall initially?

**Screenshots/videos**
![WoWScrnShot_052924_161735](https://github.com/SunstriderEmu/BugTracker/assets/43206439/25433b18-4963-46db-a8fd-0a128bb0d1bc)

The far wall (with 3 paintings) I am facing was the glitchy wall, didn't test the other walls. The dead Swashbuckler on the floor is further away from the wall than where he was when the proximity aggro happened, which was pretty much right in that back corner on the right, next to the stuffed bear.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, unfortunately I can't reproduce it.
