### ISSUE TITLE
NPC Thrash is weird. Has a range greater than 5 yards instead of modifying next melee hit?

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5678]
**Describe the bug**
Was blasting Retherokk the Berserker down with frostbolts. Before he could close the distance to reach me in melee, he suddenly hit me twice in a burst with what seemed at first like normal melee hits. Battle log states it was Thrash and gave him 2 extra attacks, and those apparently had a range greater than normal 5 yard melee ability range. The extra attacks from thrash are supposed to come as a burst when the attacker lands their next attack, not have a range of their own. This allows the number of extra hits to keep stacking if you keep kiting the enemy, only for them all to be discharged at the same time once the enemy actually gets to land a hit. I think they are meant to stack to number like 4 extra attacks over time, if they get to use the thrash ability twice before landing the hit. You can observe this on official when you employ entangling roots or other immobilizing ability like frost nova to keep the enemy from landing hits, then let them land a singular hit to see 5 damage numbers pop up instead.

**Character name**
Exolon

**To Reproduce**

1. Aggro a Thrasher enemy at range
2. See the Thrash get used
3. Get hit through space and time

Retherokk the Berserker: https://www.wowhead.com/tbc/npc=8216/retherokk-the-berserker#abilities;mode:normal
Thrash: https://www.wowhead.com/tbc/spell=3391/thrash

**Expected behavior**
To my knowledge, Thrash is an ability that gives you N stacks of 'extra hit' when used (stacks with itself to a max of 4 stacks?), which are automatically consumed when next melee attack is used (might even be limited to next auto swing, but since that automatically happens when the enemy is within reach, it doesn't probably matter if they get discharged through auto swing only or any melee hit, since the reach is the same). The ability has a cooldown and can be used regardless of the distance, but the thrash itself is not an attack ability, rather, a self-buff. Looking at how Wowhead describes, the cooldown might be actually only like 4 seconds, but using it doesn't always work and give extra attacks, instead there is like... 10-35% chance to get 2 extra attacks? So you might see 4 extra attacks in 8 seconds, or 0 extra attacks in 30 seconds?

**Screenshots/videos**

**Additional context**
Seems there is a similar range issue with some abilities that supposedly modify the next melee attack of an enemy. Instead of being treated as a preparatory conditional (triggered through next melee hit) self-buff whose actual debuff portion of effect is delivered through next melee attack, such as applying poison or disease through the next melee attack, the debuff itself is treated as an actual attack ability with a range of its own, often greater than standard 5 yards of being a melee ability. But so far these kinds of abilities have been too numerous to conveniently report, still thinking of how to approach them properly, since I cannot remember which poisons/diseases on official modify the next melee hit instead of being an attack ability of their own.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
This case was specific to this creature and its AI script, it was recasting thrash attacks on a timer in a workaround way.
Since you've mentioned seeing other examples of this behavior we'll check if some other creature scripts have the same issue.

**Comment by Dalzedur** [comment]
Yeah, some enemies that have a poison/disease style debuff, they'll cast it at range, rather than deliver it through their next melee attack. Like, skeleton raiders and defias nightblades in Duskwood, I think, mangy silvermanes in Hinterlands, maybe rabid thistle bears in darkshore. It's difficult to say which it should be by default, because official does also have poison debuff attacks that are delivered at range, such as venom spits style attacks, I believe.
