### ISSUE TITLE
Crypt Scarab permanency

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5679]
**Describe the bug**
Some of the nerubian spider-undeads (crypt stalker at least) in EPL summon crypt scarabs through an ability. It is basically a homing attack where the individual scarabs are untargettable 'projectiles' that have a melee attack of their own. They chase after the target and keep hitting them. If you get to an evade spot out of their reach, they wait indefinitely until they can hit you again. The only thing that seems to work against them is to run away until the chase timer expires and they actually reset. I'm not sure in what way these differ from the scarabs on official, but I think they 1) do less damage per attack (took 1s and 2s, basically preventing spellcasting but not being too dangerous, the annoying part was staying in combat mode which prevented use of some abilities and halting hp regen), 2) they don't have a short timer that kills them. I feel like the scarabs on official did considerably more damage but expired soon after being summoned (wowhead mentions they stay for 10 seconds), not staying around indefinitely.

**Character name**
Exolon

**To Reproduce**

1. Aggro crypt stalker
2. Crypt stalker summons scarabs
3. Scarabs annoy you

Crypt stalker: https://www.wowhead.com/tbc/npc=8555/crypt-stalker#abilities

**Expected behavior**
The summoned crypt scarabs despawn on their own on a timer (10 seconds?)

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The scarabs last for 10s and are resummoned every 10-15s, they correctly evade when they can't reach their target:
https://streamable.com/3rpchn

Seems like you were fighting a lot of these Crypt Stalkers at the same time and maybe there were a lot of scarabs up at the same time?

**Comment by Dalzedur** [comment]
Negative, just aggroed one nerubian at a time, in that small village in northwestern EPL (terrordale? that place just next to the tunnel connecting to Tirion Fordring). I jumped to an inaccessible location (top of a shed) when testing the scarab permanency before submitting the report and they just tried to get to melee range if I was too close to the edge, otherwise persisted for over a few minutes. The leash timer (7 seconds + 1 second per 10 levels roughly) is what finally made them reset and therefore despawn once they got back to the spot where they spawned in, once I had ran far enough from the original battle site. Maybe by being too close to where the scarabs were summoned their leash timer doesn't start counting down? The original nerubian who summoned them was dead, so there was no one to resummon them. Shrug.

**Comment by Dalzedur** [comment]
Hmmhmm, regarding that streamable you linked. The nerubian in that clip was alive at all times. Wondering, since we have had imp firebolts persist after the imp dies, that the scarabs could behave in a similar manner? If they are up and about and the entity that spawned them dies and gets removed, the projectile 'stays', except this time the projectile obj is a semi-living creature that can enter combat mode, so their melee attack only makes function calls to the scarab object itself, not the nerubian object that spawned it (which could error if the obj is not found), thus the code finds the scarab object when they attack so they actually are able to land hits, which is different from the imp firebolt, which could error if the function call cannot find the caster object anymore for function calls? Wild guesses on my part, I've done some hobby coding to a LPMUD and a fairly common coding error was making function calls to a creature that has died, which results in the code that attempts to make the call aborting whatever they were in the middle of doing, with some lines of code never being executed, such as making a buff expire.

**Comment by Dalzedur** [comment]
Got some footage about it. Character still in combat after compressing/uploading the clip, because of the scarab stuck on the roof of the shed, unable to use abilities that cannot be used in combat, such as teleport to stormwind.
https://streamable.com/4mjp4c

**Comment by Jerrythemagicdog** [comment]
Thanks for the details here, that's helpful!
It seems we were defaulting to the wrong behavior and keeping the summons alive for until they were out of combat for 20s.
Fixed with the next update.
