### ISSUE TITLE
Fished Mithril Bound Trunks often totally empty - loot table issue?

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5680]
**Describe the bug**
As is known, fishing can be used to fish up 'treasure chests' from the waters, with a high likelihood of doing so when fishing at spots of floating shipwreck debris. In lvl 45 and above fishing spots in Azeroth, fishing in these spots yield Mithril Bound Trunks, which are an item that you can open in your inventory to access the goods within. They contain money, potions, leather and processed tailoring materials mostly, with sometimes ~lvl 45 random drops. On official, these trunks are never(?) empty, they may be empty enough to only contain < 2 silver coins, but from what I've seen, all of them contain at least something. On Sunfury, I went around STV and fished up every debris spot and they barely gave anything. At least 7 were totally empty (3 of those empty ones were in a row), so the loot table for those trunks seems very sus.

**Character name**
Elillinr

**To Reproduce**

1. Fish in a lvl 40+ zone
2. Get mithril bound trunk, either from a fish/flotsam node
3. Open it in your inventory

Item: https://www.wowhead.com/tbc/item=21228/mithril-bound-trunk

**Expected behavior**
Each trunk should contain money at the minimum (1s + random(101) copper?). Then the loot generation process rolls separately for every trade good in the list, so 1 trunk may contain all of the following: thick leather, rugged leather, bolts of mageweave, bolt of runecloth. Then it rolls for potions: superior healing potion and greater mana potion. Then it might have a check to see if there's a weather-beaten journal (which might not drop if you have already used it, might explain empty trunks in the code - my character had read the journal already) and another check to see if it has an additional loot item (ilvl 40-50 green drop / recipe / 14slot bag / gem etc) - I've never seen more than 1 green random item in a trunk, so it likely just rolls to see if there is one, then it chooses what it is, rather than roll separately for each one. Also, with some logic there may even be very specific blue items (recipes such as mithril shield spike or runed mithril hammer, broken blade of heroes, which are probably options in the extra loot list). I'm not sure how accurate the % chances on Wowhead are for the list of items contained, but at least the leathers and bolts seem more or less what my own experiences on official match.

**Screenshots/videos**

**Additional context**
I remember fishing to be a very viable way to get leather and bolts of cloth. I would've gathered a comprehensive list of what I got from opening the trunks, but I didn't think of it at the time, I just opened them whenever I got one and by the time I was convinced things were fishy (pun intended) I ran out of flotsam nodes to fish in. There is something weird with the respawn behaviour/times of those nodes, too, not sure if they can even respawn if there isn't a player within render distance of them - the timer script might become inactive if no one is there to see it. The ones I fished in the previous session had still not respawned when I relogged in the following day and ran the STV shores.

WOWhead comment on the mithril trunks shows a player reporting what they got from opening 8 trunks, doesn't seems untrue:

1st trunk
> 1s62c
> superior healing potion
> thick leather(2)
> bolt of mageweave(3)

2nd trunk
> 1s97c
> superior healing potion

3rd trunk
> 1s2c
> thick leather(3)

4th trunk
> 1s2c

5th trunk
> 1s79c
> thick leather(4)
> rugges leather(2)
> bolt of runecloth

6th trunk
> 1s25c
> Brigade Leggings of the Eagle (green)
> Rugged leather

7th trunk
> 1s94c
> greater mana potion

8th trunk
> 1s21c
> greater mana potion(2)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
