### ISSUE TITLE
Cliff Walker (Azshara) has one third the hitpoints it should (elite hitpoint bonus not applied?)

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5681]
**Describe the bug**
Cliff Walker giant in Azshara had 2453 hitpoints, which is low for a lvl 52 elite monster. Should be ~7113 (according to WoWhead)
Chances are that other elite modifiers to its stats are not applied either. It did hit for 175 to 213 in melee against my lvl 62 cat druid, if that helps at all. Armor 1382, so 16,85% mitigation against lvl 62 opponents. Chances are that the other Azshara giants are similarly impacted.

NPC: https://www.wowhead.com/tbc/npc=6148/cliff-walker
NPC: https://www.wowhead.com/tbc/npc=6147/cliff-thunderer
NPC: https://www.wowhead.com/tbc/npc=6146/cliff-breaker

**Expected behavior**
Normal elite monsters have three times the hitpoints of a non-elite of equal level. If they are intended for a party size larger than one, even more.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
Only https://www.wowhead.com/tbc/npc=6148/cliff-walker was affected.
