### ISSUE TITLE
Quest: Unexpected Results (Eversong Woods), npc faction fault

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5682]
**Describe the bug**
This quest is the one that follows up gathering corrupted soil for Apprentice Mirveda. It is a quest where she is to be attacked by one Gharsul the Remorseless, flanked by two Angershade, so a 1v3 fight where the player character is expected to help her survive the assault. Yet, on this codebase, the two Angershades immediately attack Gharsul, as if being hostile to each other from the start.
I assume Gharsul's faction has been wrongly set to be one which the angershades is hostile to, rather than the angershades having a wrong faction.

**To Reproduce**

1. Initiate the quest
2. Monsters spawn
3. Infighting

Gharsul: https://www.wowhead.com/tbc/npc=15958/gharsul-the-remorseless
Angershade: https://www.wowhead.com/tbc/npc=15656/angershade
Quest: https://www.wowhead.com/tbc/quest=8488/unexpected-results

**Expected behavior**
Gharsul and the two angershades should attack Apprentice Mirveda by default. Maybe even a player character if they are in a closer proximity to them upon them spawning.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
