### ISSUE TITLE
Mistbat in Eversong Woods, far from home

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5683]
**Describe the bug**
There is a mistbat just north of the Fartstrider Retreat in Eversong Woods. It's not supposed to be there. They are a Ghostlands zone monster. As a lvl 10 enemy, it is slightly above the intended level range for this spot, probably. I've never seen a bat in that spot on any other server / official realm.

**To Reproduce**

1. Get to Farstrider Retreat from Silvermoon City.
2.  The bat is just by the road right next to the Retreat.
3. Say hi.

NPC: https://www.wowhead.com/tbc/npc=16353/mistbat

**Expected behavior**
They're supposed to spawn in Ghostlands, near the Eversong Woods border by the bridge, generally speaking. 

**Screenshots/videos**

**Additional context**

This smells like it was manually spawned for bug testing using an admin command that made it a permanent spawn, rather than just a temporary one?

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
