### ISSUE TITLE
Eldinarcus (rare, 11 elemental, Eversong Woods) melee damage

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5684]
**Describe the bug**
Eldinarcus melee damage is bonkers. Hit mail wearing lvl appropriate character for 73-92 physical damage per melee swing, the character I played at lvl 11 had 273 hp (includes +5 for the bracers enchant). The non-rare enemies in the area hit for 11-16 by comparison. Despite using minor healing potion, divine protection, and lay on hands, was unable to defeat it. Eldinarcus is not an elite enemy, either.

**Character name**
Rudezlad

**To Reproduce**

1. Go to the northeastern part of Eversong Woods
2. See the arcane elemental wandering about - that's it
3. Engage it in combat

NPC: https://www.wowhead.com/tbc/npc=16854/eldinarcus

**Expected behavior**
Expected damage to be closer to 15-30 range per swing.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
