### ISSUE TITLE
NPC Ranger Lilatha in Escape from the Catacombs quest in Ghostlands is pvp tagged, but cannot be buffed.

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5686]
**Describe the bug**
Typically, escort npcs which are pvp tagged can be buffed with spells like blessing of might. They may shake the buff off by resetting back to full hps after each combat encounter, but that's another issue. If I attempt to cast blessing of might on Ranger Lilatha, it targets my own character instead, implying that the Ranger cannot be buffed during the escort.

**Character name**
Rudezlad

**To Reproduce**

1. Start the escort
2. Attempt to buff the escort NPC
3. Buff lands on your own character as per default targeting of unbuffable target.

NPC: https://www.wowhead.com/tbc/npc=16295/ranger-lilatha
Not sure if this same npc number is used for the npc that is being escorted, or if initiating the quest spawns another version
Quest: https://www.wowhead.com/tbc/quest=9212/escape-from-the-catacombs

**Expected behavior**
Typically, escort npcs which are pvp tagged can be buffed with spells like blessing of might.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
