### ISSUE TITLE
Spellbook: Spiritual Attunement rank 1 tooltip when hovered

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5687]
**Describe the bug**
I just dinged to 18 on my x1 paladin and learned rank 1 of Spiritual Attunement. I looked it up in the spellbook and noticed that the tooltip for that rank 1 spiritual attunement has a red text that says 'requires lvl 66'. If I was a more social player, I could test if it still works regardless of that stated level requirement not being met, I assume that it does, because people would have reported it not working if it doesn't, right? It is rank 2 which is learned at lvl 66.

**Character name**
Rudezlad

**To Reproduce**

1. Learn rank 1 spiritual attunement (paladin 18, protection page)
2. Hover over the ability's icon in the spellbook (default hotkey to open 'p')
3. Read and weep

Spell: https://www.wowhead.com/tbc/spell=31785/spiritual-attunement

**Expected behavior**
The tooltip should not show lvl 66 as required for the rank 1 version. (assuming that it actually works, too)

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next (big) client update.
It seems to be a mistake present in clean 2.4.3 client files, which is where we get our data from.
