### ISSUE TITLE
Debilitated Mag'har Grunt hps/lvl

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5688]
**Describe the bug**
In Hellfire Peninsula, there is a small Mag'har orc presence in the north-northwestern part of the area, up a mountain. They are suffering from some sort of debilitating disease, which saps the strength of their grunts. For horde players, there is a quest to cure that disease, which turns debilitated mag'har grunts into just mag'har grunts. The effect of the cure, if I study WoWhead correctly, is +3 to their level and doubling their hitpoints. As an alliance character, I cannot explore if this works, but what I do notice is that the debilitated mag'har grunts are lvl 61 and not lvl 58, and they have ~double the hitpoints that WoWhead says they should have. Whatever penalties other than halved hitpoints and -3 levels the conditions should give them, like lesser combat performance, I cannot really confirm.

**Character name**
Elillinr

**To Reproduce**

1. Target a Debilitated Mag'har Grunt
2. See their hitpoins, see their level, see that they have more hitpoints than some of the healthy ones
3. Compare to WoWhead data and confirm that there is a marked difference with official data

Debilitated:
NPC: https://www.wowhead.com/tbc/npc=16847/debilitated-maghar-grunt
healed version:
NPC: https://www.wowhead.com/tbc/npc=16846/maghar-grunt

**Expected behavior**
The debilitated grunts should be easier to kill than healthy ones. Doesn't seem like there is a penalty to them, as it stands.

**Comment by Dalzedur** [comment]
Furthermore, all the 'grunts' that I came across were debilitated. I didn't see any normal Mag'har Grunts. Maybe that's how it is when no one has been here earlier during this server uptime to cure them, but this is the first time I don't see any normal grunts when I come here. I could've sworn that on other codebases when the killed grunts respawn, they don't all respawn as debilitated ones, there should be normal ones as well.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, the levels will be corrected with the next update.
Won't be changing the amounts of debilitated grunts up simultaneously, it helps finishing the quest quicker when there are many players around.
