### ISSUE TITLE
Quest: Testing the Antidote - wrong skin on Dreadtusk

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5689]
**Describe the bug**
When doing the quest Testing the Antidote, using the Cenarion Antidote on a hellboar turns it into a Dreadtusk. The dreadtusk should have the Shadowmoon Valley demonic boar skin (dark gray skin, green eyes), but there is no cosmetic change currently when using the blood.

**To Reproduce**

1. Use the quest item Cenarion Antidote when targeting a hellboar
2. The hellboar changes into a Dreadtusk
3. But doesn't look like a Dreadtusk

Dreadtusk: https://www.wowhead.com/tbc/npc=16992/dreadtusk
Quest: https://www.wowhead.com/tbc/quest=10255/testing-the-antidote
Antidote: https://www.wowhead.com/tbc/item=23337/cenarion-antidote

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue! 
I've looked into it for a bit and I couldn't find the reason why this model doesn't consistently work for this particular creature, not really willing to spend more time looking into it right now.
