### ISSUE TITLE
Bleeding Hollow Necrolyte's instant armor

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5690]
**Describe the bug**
When a Bleeding Hollow Necrolyte enters combat mode, it instantly activates some kind of a demonic armor buff, even if the attack that puts it into combat mode stuns it, which should prevent casting of spells while the stun persists. As in, feral druid cat form pounce. This might mean that the increased armor gets applied before the attack that initiates the combat can deal its damage, allowing the increased armor to soak damage from stealth starters such as ambush or ravage? Previously reported 'instant ability use when combat starts of Deserter Lieutenants' in Theramore, which is extremely similar in game mechanics, I think, was fixed by applying a fraction of a second of delay to the AI that attempts to use their first designated ability, so that the delay postpones the activation of the ability until the stun actually has landed, which then prevents the ability from being used maybe? Furthermore, as explained in additional context, I didn't see them use Raise Dead while I was questing in the area.

**Character name**

**To Reproduce**

1. Target Bleeding Hollow Necrolyte
2. Pounce from stealth, stunning them
3. But their instant cast ability gets triggered between combat start and the pounce stun immediately landing.

NPC: https://www.wowhead.com/tbc/npc=19422/bleeding-hollow-necrolyte

**Expected behavior**

**Screenshots/videos**

**Additional context**

Also, I didn't see them cast a single raise dead when I was gathering the cursed talismans and killed a bunch of them. Maybe the corpses despawn too fast, leaving no corpses for them to animate?

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update (all cases of "on aggro" casting ignoring CCs)
