### ISSUE TITLE
Druid flight form unable to do some stuff while maintaining the form (shapeshift form issue)

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5691]
**Describe the bug**

This one might be working as intended, if the intent has been to balance what made the druid flight form exceptionally good in TBC. 

Finally got my druid to 68 and learned the flight form. Tested some stuff. Can skin while maintaining form (even if not touching the ground), can use herbalism while maintaining form (but must land for this), don't have mining but I assume since it requires pick-axe animation it'll revert back to normal form for that, which is how they behave on official.

But, when it comes to interacting with quest objects, such as Feralfen Idols (gather 6 for a quest), or harvesting mature spore sacs for the repeatable Sporeggar reputation quest, or attempting to pick up glowcaps (the sporeggar currency), this codebase wouldn't permit those to be done in flight form, citing a 'You are in shapeshift form' as the reason for not being able to do so, and upon landing and attempting to use them again, it'll force the druid back to druid form from the animal form to do it. Yet, those were definitely gatherable in flight form in TBC. In fact, I preferred to harvest the spore sacs on my druid for my alts, because I could just pick them up from the air, without pulling aggro from the fungal giants, making the overall process many times faster than on another character. 

The flight forms seems to use a different AI reaction from official as well. Enemies on the ground actually aggro at the flying druid and attempt to pathfind their way to them and attack them. On official they just ignore flying characters until they actually land, and only then start to use their abilities at them (I can't remember if ranged-combat-capable enemies would actually shoot at a flying player who hasn't yet landed), with some definite exceptions (flying faction guards attack flying players, attempting to force them to land etc)

**Character name**

Elillinr

**To Reproduce**

1. Activate flight form
2. Try to get close to various interactions, so you can reach them.
3. Attempt to do them without landing, attempt to do them after landing. See if you revert back to druid form from flight form or not.

The ability, probably, https://www.wowhead.com/tbc/spell=33943/flight-form

**Expected behavior**

Quest gatherables, such as feralfen idols and mature spore sacs do not break shapeshift form on official codebase, and you can gather them in animal form, without having to land (but you still need to get close to the ground to be able to reach them). 

It is possible that there was some kind of a default setting which permitted some stuff to be doable while in shapeshift form, probably according to the animation that the interaction uses. The default 'doing something' animation is used by picking up a feralfen idol, a mature spore sac, skinning, or using herbalism. But picking up a glowcap mushroom uses a kneeling animation instead, I cannot remember if those were harvestable in flight form on official or not. I assume the default 'doing something' animation may have been supported by the shapeshift code to be permitted and not break form, thus making skinning and herbalism usable while in flight form, but mining, which uses a pick-axe swinging animation, could not be, that animation forces reverting back to druid form, I assume.

**Additional context**

I also see enemies aggroing to the flying character even when the druid is not touching the ground, which on official was enough to force an 'evades'-behaviour in enemies, so they wouldn't aggro unless you were as low as possible. Seems like normal aggro range rules apply here and the enemy, once aggroed, tries to pathfind its way right under the druid, and if it can reach the druid with attacks, it attempts to use them. It does make more sense for the enemy to behave like they do on this codebase, imo, but it is, still, a different behaviour from what they exhibit on official against flying players.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
The usage of Mature Spore Sacs and similar while in flight form is prevented by the client, which seems intended for its time.
We could change it but it's too low impact to bother, sorry!
Enemies engaging while you're flying is intended for us and will remain the same.

**Comment by Dalzedur** [comment]
Intended for its time... or intended for world pvp servers? On official it is possible, in both TBC and WotLK (and WotLK made flight form available as early as 60, and sped the flight speed up to be faster than epic land mount), so why would the private client intend to deviate from it knowingly? Anyways, I'm not too sure I wholly agree about the low impact, though, since:
- not everyone plays with 5x xp rate, for 1x crowd the 68->70 is still some work, and there are gather quests in 68+ content.
- and even at 70 it is a huge time saver, since you cannot shift into flight form while in combat. For example, when doing the dailies, such as gathering mana berries in Netherstorm, or the Smuggled Mana Cells in Bash'ir Landing in Blade's Edge, if you can retain your flight form while you pick up the quest objective, you can then fly into the sky and shake off the aggro, whereas if you are forced into druid form while gathering the item, you are landlocked while the combat status remains, risk pulling additional enemies etc and fighting takes time. The heightened aggro range on fliers in this codebase should balance this to some extent. Being able to do these chores faster means having more time to do potentially more fun and meaningful stuff that may involve other players as well. I can see a fix saving ~30 minutes of time per week going forwards.
- even at 70 these gather quests are worth doing to work towards the epic flying mount, since the max lvl additional gold.
- Druid flight form is not counted as a mount, so any +mount speed effects there are do not apply to it (riding crop, paladin crusader aura, for example), so being able to gather objectives overall faster compensates for this.
- it would be a fix that makes the flight form, and tedious gathering when playing on a druid, _more fun_, and more fun is priceless

As there is no in-game reward system for actually writing these reports, and these do take time to write (and test prior to writing), and that's probably why no one else seems to be writing these, I would like to cash in the good boy points I've accumulated through making bug reports and implore you to fix this regardless, since it sounds like you've identified what's causing the issue already, so maybe you've already formulated how to actually go about fixing it. If it involves patching the client and is not, by itself, enough to justify having the players go through a patching process, you can put it in later along with something else that does warrant going through the motions, maybe? :)

**Comment by Jerrythemagicdog** [comment]
Here's roughly what happens when you interact with the gameobject while in flight form:
1. The game client processes your input.
2. The game client does a series of checks before sending a packet to the server, ranging from e.g. "is the player moving" or, in this case, "is the player shapeshifted", and so on. **This is currently the stopping point, which is why I said it's intended. While we do change the game client in some ways to add/modify some of its functionality, the overwhelming majority of it is the same as it was written originally ~14 years ago**.
3. If those checks pass a packet is sent to the server.
4. The server does its own series of checks, some similar to the game client checks.
5. If everything passes the server sends a packet to the game client telling it to start the requested spell cast/interaction.

I don't want to make empty promises, changing this shouldn't be complicated, if we have the time we will look into matching current Classic behavior you mentioned.
