### ISSUE TITLE
Gorlash movement speed?

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5693]
**Describe the bug**

In Stranglethorn Vale, there is a quest called The Captain's Chest. It involves killing the sea giant Gorlash, who is an elite enemy. The chest required by the quest is looted from his corpse. Usually, the solo tactic is to kite him to the Booty Bay guards, who will quickly chop him into pieces. It felt that on this codebase, Gorlash moves too slowly compared to the official servers. It was ridiculously easy to kite him, without even using any kind of movement speed buffs on my own character, or debuffs on him - to emphasize, normal movement speed at 100% was faster than his movement speed.

**Character name**

Qirana

**To Reproduce**

1. Aggro Gorlash
2. Kite him
3. Compare movement speed difference and feel like something's amiss

NPC: https://www.wowhead.com/tbc/npc=1492/gorlash

**Expected behavior**

On official realms, enemy movement speed improves in a linear manner according to their level, or that's my understanding of it, with some creature specific adjustments, murloc coastrunners in Westfall have abnormally high movement speed for their level, for example. I remember struggling to stay alive on melee characters to pull Gorlash to the guards, because 100% movement speed was slower than his, so once he caught up, you'd struggle to get away from him again. Now, in TBC Gorlash was nerfed by a few levels, but he is still a lvl 42 enemy and should move at least as fast as lvl 42 enemies by default.

**Screenshots/videos**

**Additional context**

I tried to google for a chart that shows the movement speed by level of npc creatures, but couldn't find one.

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue!
All creature movement speed values are taken from Classic.
