### ISSUE TITLE
Quest: Grim Message, item: Nimboya's Laden Pike

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5694]
**Describe the bug**

The pike is very picky as to which Witherbark Village counts as the right spot for the quest completion action. On Official you can strike it into the ground in the western Witherbark Village (where cages #1 and #2 are), but on this codebase it didn't let me, I had to go the the next village, where the cage #3 is.

**Character name**

Qirana

**To Reproduce**

1. Start completing the quest - gather 20 skulls, create the pike
2. Try to use the created pike at a witherbark village
3. The game might not let you, but it works somewhere else

Quest item: https://www.wowhead.com/tbc/item=9319/nimboyas-laden-pike
Quest: https://www.wowhead.com/tbc/quest=2932/grim-message
Quest item action: https://www.wowhead.com/tbc/spell=11547/drive-nimboyas-laden-pike

**Expected behavior**

All(?) the witherbark village-like locations in the zone should count as the correct place for the pike to be used at. Even the quest description says 'at one of the witherbark villages', which implies 'any' instead of 'specific one'.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
