### ISSUE TITLE
Lard's Special Picnic Basket loot table

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5695]
**Describe the bug**

In Hinterlands there is a quest Lard Lost His Lunch. Completing the quest gives a reward in the form of Lard's Special Picnic Basket, a container that generates randomly loot inside once opened. You generally get at least one world drop recipe or a bag from it, and a bunch of stuff - treat it basically as if looting a very good chest. Yet, on this codebase, it only contained one serving of moonberry juice. The WoWHead comments speak volumes.

**Character name**

Qirana

**To Reproduce**

1. Get the basket
2. Open basket in excited anticipation
3. Kick in the balls.

Item: https://www.wowhead.com/tbc/item=19035/lards-special-picnic-basket
Quest: https://www.wowhead.com/tbc/quest=7840/lard-lost-his-lunch

**Expected behavior**

The picnic basket's loot table should've spawned several items inside, not just 1 moonberry juice.

**Screenshots/videos**

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, it appears you just got very unlucky, here's my unboxing: 
![image](https://github.com/user-attachments/assets/8e6ca537-472a-46f4-81d3-81ce7c1863a5)
