### ISSUE TITLE
Quest: Natural Enemies cannot be turned in after reaching friendly rep, despite being active and completed?

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5697]
**Describe the bug**

Natural Enemies is a Sporeggar rep quest, where you turn in 6 bog lord tendrils, it is repeatable until friendly. It seems that once you ding to friendly, you can no longer turn the quest in, even if you had picked it up prior to getting to friendly rep. I am carrying 10 tendrils, but the 'continue' button in the dialogue window is grayed out. On official, as long as you had the quest active, you could turn it in, even if it had a reputation range during which it was possible to be picked up. This allowed players to grind out repeatable rep quests until going past that threshold, then turn in all the other quests that would at that point become ungettable due to player reputation being past the threshold, to get additional reputation. Not sure if intended to be disabled this way to prevent getting the reputation as high as you can prior to doing any dungeon content.

**Character name**

Elillinr

**To Reproduce**

1. Pick up the quest prior to getting Sporeggar reputation to friendly
2. Gather 6 bog lord tendrils.
3. Attempt to turn in the quest, but cannot.

Quest: https://www.wowhead.com/tbc/quest=9743/natural-enemies

**Expected behavior**

You should be able to, normally, turn in quests if you meet the stated quest objectives, as in 6/6 bog lord tendrils, regardless of any other factors, such as the quest only being able to be pickup before you hit friendly reputation with the faction.

**Screenshots/videos**

**Additional context**

From what I've understood, some people don't turn in any of the reputation affecting Zangarmarsh quests before exhausting the option to turn in repeatables: unidentified plant parts for Cenarion Expedition or the Mature Spore Sacs for Sporeggar, thus getting their faction reputation so much closer to higher tiers, without having to grind the dungeons for reputation. This is mainly helpful for solo players, who would struggle to find dungeon groups, as it provides easier access to reputation quartermaster's honored and revered wares. It just requires time and effort to get enough of those repeatable turn ins, especially if there is no auction house economy to speak of.

**Comment by Dalzedur** [comment]
Same issue seems to be true for: Glowcap Mushrooms ( https://www.wowhead.com/tbc/quest=9808/glowcap-mushrooms ) and likely More Glowcaps ( https://www.wowhead.com/tbc/quest=9809/more-glowcaps ), which I am unable to test, since I cannot turn in the first quest. (the difference between the two is that the first time gives an xp reward as well, whereas further turn-ins only give rep).

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
