### ISSUE TITLE
Wrekt Slave melee damage probably broken

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5698]
**Describe the bug**

Wrekt Slaves can be found near Bloodscale Slavedrivers in at least western Zangarmarsh. Attacking a Slavedriver may alert a nearby slave to come and assist them in battle. If the slave is not attacked directly, but the slavedriver is slain, the slaves often unaggro at that point and return back to where they were. The issue is, however, their melee damage. If Slavedrives hit my character for around 165-180 every two seconds, a slave hits me for 350 every 2 seconds. The slave is 2 levels lower than a slavedriver. Not sure what causes their abnormally high melee damage, they are not elite, but sometimes they have a <minion of Bloodscale Slavedriver> tag under their name, but the melee damage seems to be same for those with the tag and those without. There is a battle shout effect often in these fights, but it does not explain why one type of enemy would be doing twice the damage as another, more higher level, enemy, especially since they are not giants and both hit physical.

**Character name**

Elillinr

**To Reproduce**

1. Aggro wrekt slave
2. get wrekt?
3. Rinse and repeat.

NPC: https://www.wowhead.com/tbc/npc=18123/wrekt-slave

**Expected behavior**

Their melee damage should be lower, I remember it as being lower, and they used to aggro in pairs, with a spirit link between them. Don't see that happening on this codebase, but that should probably warrant a separate bug report, maybe.

**Screenshots/videos**

**Additional context**

They might be getting an additional lvl-related boost to their melee damage or stats that affect it, if the game treats them as summoned minions, maybe? There were issues earlier with some enemy warlock minion damages, at least.

**Comment by kelno** [comment]
Thanks for reporting this, I reduced their damage which was indeed too high.
