### ISSUE TITLE
Freezing Circle lacking visual cues

### ISSUE THREAD

**Issue by Dalzedur** [ValorenWoW/sunstrider-core#5699]
**Describe the bug**

Freezing circle is a powerful ability used by some naga casters, such as Bloodscale Enchantress. It is a stationary ground aoe spell that once cast, detonates a few seconds after, dealing massive damage and freezing targets caught in it for 10+ seconds. On official, once the spell has been cast, there is a visual cue provided that gives strong hints and indicates when the spell is about to detonate: Small chunks of ice appear in a circular pattern as the spell ticks towards its detonation, Once the chunks of ice form a full circle, the explosion happens. But not on this codebase. There is no visual cue. It can be very unfortunate in group fights, since you may not even be alerted that a freezing circle has been cast.

**Character name**

Elillinr

**To Reproduce**

1. Aggro Bloodscale Enchantress
2. Have them cast Freezing Circle
3. Observe

NPC: https://www.wowhead.com/tbc/npc=18088/bloodscale-enchantress
SPELL: https://www.wowhead.com/tbc/spell=34787/freezing-circle

**Expected behavior**

**Screenshots/videos**

https://www.wowhead.com/tbc/spell=34787/freezing-circle#screenshots:id=69979

**Additional context**

**Comment by Jerrythemagicdog** [comment]
Thanks for the issue, fixed with the next update.
