### ISSUE TITLE
The server cannot be logged in after the installation is successful.

### ISSUE THREAD

**Issue by woiwoz** [ValorenWoW/sunstrider-core#6]
After the installation is successful, the startup server can't log in, prompting the account number and password error.
I'm sure my account number and password are not incorrectly entered.

**Comment by szhxjt1334** [comment]
confirm

**Comment by kelno** [comment]
Can you please provide the exact message or a screenshot?

**Comment by woiwoz** [comment]
Always prompts account password error.
I am sure that my account and password have not entered errors.

**Comment by woiwoz** [comment]
This problem should appear in Authserver. 
According to my test, even if my account and password were typed correctly, the server would still think it was wrong.

**Comment by kelno** [comment]
This seems to be a problem in your setup.
1 - Can you detail how did you create the account? Which *exact* command did you use?
2 - There should be a default account with both login and password being "test", does this account work for you?

**Comment by woiwoz** [comment]
my is windows7 x64
The account I created in the console
use  command   account create acc pass pass

**Comment by woiwoz** [comment]
Can't we solve this problem?

**Comment by kelno** [comment]
Interesting. The core is supposed to build with the c++17 flag enabled, but it may be that cmake is not enforcing a recent msvc version.

**Comment by kelno** [comment]
I still need to be able to reproduce it.
To narrow it down, can you please respond to my question:
There should be a default account with login 'test' and password 'test', does this account work for you?

**Comment by woiwoz** [comment]
vs version：vs2017 Community ， MSVC 19.15.26726.0
OS：windos10 x64
Boost version: 1.67.0
Mysql: 5.6.26
OpenSSL: Win64OpenSSL-1_0_2o

Below is all information about Cmake built by the project:
The C compiler identification is MSVC 19.15.26726.0
The CXX compiler identification is MSVC 19.15.26726.0
Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe
Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.15.26726/bin/Hostx86/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:11 (cmake_policy):
  The OLD behavior for policy CMP0043 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


Detected 64-bit platform
MSVC: 64-bit platform, enforced -D_WIN64 parameter
MSVC: Enabled increased number of sections in object files
MSVC: Overloaded standard names
MSVC: Disabled NON-SECURE warnings
MSVC: Disabled POSIX warnings
MSVC: Enabled C++17
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Found MySQL library C:/Program Files/MySQL/MySQL Server 5.6/lib/libmysql.lib
Found MySQL headers: C:/Program Files/MySQL/MySQL Server 5.6/include
cotire 1.7.10 loaded.
Found git binary : D:/Program Files/Git/cmd/git.exe

* Sunstrider revision:   9405 (43e369d9b5f2) 2018-08-15 14:41:45 +0200 (master branch)

* Will install to:        C:/Program Files/Sunstrider
* Build map/vmap/mmaps tools:   No
* Debug mode:                   No
* All warnings:                 No
* Playerbot:                    Yes
* Tests:                        Yes
* Use gperftools:               No 
CMake Warning (dev) at dep/boost/CMakeLists.txt:44 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Environment variable Boost_ROOT is set to:

    D:\local\boost_1_67_0

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

Boost version: 1.67.0
Found the following Boost libraries:
  system
  filesystem
  thread
  program_options
  iostreams
  regex
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM
Performing Test boost_filesystem_copy_links_without_NO_SCOPED_ENUM - Success
Looking for open
Looking for open - found
Found OpenSSL library: optimized;D:/OpenSSL-Win64/lib/VC/ssleay32MD.lib;D:/OpenSSL-Win64/lib/VC/libeay32MD.lib;debug;D:/OpenSSL-Win64/lib/VC/ssleay32MDd.lib;D:/OpenSSL-Win64/lib/VC/libeay32MDd.lib
Found OpenSSL headers: D:/OpenSSL-Win64/include
CXX target common cotired without unity build.
CXX target database cotired without unity build.
CXX target shared cotired without unity build.
CXX target game cotired without unity build.

* Script configuration (static):
    |
    +- worldserver
    |   +- Pet
    |   +- Spells
    |   +- Tests
    |
CXX target scripts cotired without unity build.

CXX RC target authserver cotired without unity build.
Configuring done

**Comment by kelno** [comment]
Thanks! I'll look into it when I get home

**Comment by woiwoz** [comment]
According to my debugging trace, when the code runs to password verification, whether the account password is correct or not, it fails to verify. I have a default test account and password, and I provide a screenshot below
![qq 20180820213652](https://user-images.githubusercontent.com/11075449/44343670-3040da00-a4c1-11e8-855e-653c4b9cc3d3.png)

**Comment by kelno** [comment]
Okay. I did a fresh install but did not encounter the same problem.
If it fails at this point this is indeed related to AuthServer only and not WorldServer.
I'm still looking for cues.
Reading your
`If I migrate the AuthServer project code to the Trinity 3.35 core code for compilation, I can log in normally. So the core code should be no problem. I doubt it is cmakelist related issues.`
Can you detail what you did there? What do you mean by "migrate"?

I'm currently building on MSVC 19.14.26428.1, also in 64 bits.

**Comment by kelno** [comment]
I'm also noticing the error is before any use of OpenSSL so don't bother trying to change the version.

**Comment by woiwoz** [comment]
Please forgive me for this bad English, ha ha.

I mean, if I compile with the full sunstrider-core code, I'm going to make this unreachable error.

But when I copy the authserver folder contained in sunstrider-core to the Trinity 3.35 corresponding authserver directory overlay and compile the auth data SQL in accordance with sunstrider-core, the error will not occur.

**Comment by kelno** [comment]
Okay I see.
Here is what my authserver property page:
https://i.imgur.com/1kaJtov.pngr 
Maybe try removing  the c++17 flag, or change with with c++14

**Comment by woiwoz** [comment]
Similarly, change the authserver project into a language standard and change it to c++14.
![qq 20180821205909](https://user-images.githubusercontent.com/11075449/44402726-313b3f80-a585-11e8-9d55-7bb444c410ed.png)

**Comment by kelno** [comment]
Okay. I guess c++17 would have worked too. The problem seems to be in the cmake then, the c++17 flag is supposed to be added automatically.

**Comment by woiwoz** [comment]
Do you have any other contact information? For example, MSN or something like that, I hope there will be more communication in the future.

**Comment by kelno** [comment]
You can join here: https://discord.gg/ss5REry
Note that I'd like to continue using this issue tracker for issues with the core.

**Comment by woiwoz** [comment]
Damn the the Great Wall firewall of China, I can't access this link.

I have a question. Do I think the core can join biological AI scripts and dungeon scripts? Of course, it can be the most primitive script that you haven't corrected. For example, the original TC.

I think this will be more convenient for the maintenance of the project.

**Comment by woiwoz** [comment]
Ha ha, I woke up.

**Comment by kelno** [comment]
Using old scripts would be problematic because the structure and the functions from the core changed a lot over time, making those old scripts incompatibles.

**Comment by kelno** [comment]
I'm recreating a new clean issue.

**Comment by woiwoz** [comment]
I've learned that I'm currently trying to merge the latest three-bit core scripts, but not necessarily fully compatible. But for research, I decided to try.
