### ISSUE TITLE
compile IS error very very

### ISSUE THREAD

**Issue by irajviky** [ValorenWoW/sunstrider-core#65]
14>C:\Users\IRAJ\Downloads\Compressed\sunstrider-core-2018_09_10\sunstrider-core-2018_09_10\src\server\game\Chat\ChatCommands\ChatCommand.h(243): error C2975: 'Idx': invalid template argument for 'std::get', expected compile-time constant expression (compiling source file C:\Users\IRAJ\Downloads\Compressed\sunstrider-core-2018_09_10\sunstrider-core-2018_09_10\src\server\scripts\Commands\cs_account.cpp)
14>C:\local\boost_1_66_0\boost/array.hpp(445): note: see declaration of 'Idx' (compiling source file C:\Users\IRAJ\Downloads\Compressed\sunstrider-core-2018_09_10\sunstrider-core-2018_09_10\src\server\scripts\Commands\cs_account.cpp)

AND
SPELL TESTS

14>C:\Users\IRAJ\Downloads\Compressed\sunstrider-core-2018_09_10\sunstrider-core-2018_09_10\src\server\scripts\Tests\spells\talents\talents_warlock.cpp(1103): error C2065: 'dealtMin': undeclared identifier

**Comment by kelno** [comment]
Your compiler is not C++17 compliant, use the last version of MSVC.

**Comment by irajviky** [comment]
ty
