### ISSUE TITLE
Yellow exclaimation marks aren't visible on re-log.

### ISSUE THREAD

**Issue by Nolin7777** [ValorenWoW/sunstrider-core#73]
**Description:**

Quest NPC's yellow exclaimation mark isn't visible after relog.
Need to move out of sight or port away to make the yellow exclaimation marks visible again.

**Expected behaviour:**

Available quests should be visible directly on log on.

**Steps to reproduce the problem:**

1. Log on in front of a quest giver.
2. Quest NPC's yellow exclaimation mark isn't visible.
3. Need to move out of sight or port away to make the yellow exclaimation marks visible again.

**rev. hash/commit:**  d686752

**Operating system and compiler:** Debian 9 / Clang

**Comment by kelno** [comment]
I could not reproduce this, can you give a specific character level + quest + npc ?

**Comment by kelno** [comment]
Reproducing steps:
- Create a lvl 1 human char
- (See the quest marker in the npc in front)
- Relog
- Quest marker has disappeared.
