### ISSUE TITLE
NPCs in cinematics aren't visible anymore

### ISSUE THREAD

**Issue by Nolin7777** [ValorenWoW/sunstrider-core#74]
**Description:**

NPCs in cinematics aren't visible anymore.

**Expected behaviour:**

NPCs should be visible in character creation cinematic.

**Steps to reproduce the problem:**

1. Create a new character
2. Log on
3. Watch the cinematic

**rev. hash/commit:**  d686752

**Operating system and compiler:** Debian 9 / Clang

**Comment by Kittnz** [comment]
Did it work at all?

**Comment by Nolin7777** [comment]
Visibility of NPCs? Yes

**Comment by Kittnz** [comment]
I ment on this core

**Comment by Nolin7777** [comment]
It was working a couple months ago on this core

**Comment by kelno** [comment]
This was broken in dd497f4e, because the cinematic object being moved was prevented to move fast enough.

**Comment by Nolin7777** [comment]
NPCs are still not visible

**Comment by kelno** [comment]
We found the issue, Cameras data directory was missing on Nolin server.
