### ISSUE TITLE
 Black temple and SunWell scripts

### ISSUE THREAD

**Issue by danqu** [ValorenWoW/sunstrider-core#79]
### Good instance and boss scripts
Most high level instance scripts are decent seeing other BC server ones (but still need work). Black temple and SunWell scripts have been the most worked on and are close to perfect.

I didn't see the script code when I read the contents of the file.

**Comment by kelno** [comment]
Please read the readme for the reason those scripts are not currently included.

**Comment by kelno** [comment]
Here is the relevant part:
"With the exception of instance and creatures scripts, as well as the AntiCheat. The core is not currently meant to be used as is outside of the Valoren server, but you're free to re use parts of it."
So Black Temple and Sunwell scripts are not public as of now.

**Comment by danqu** [comment]
I am from Germany!

I'm sorry! My English is not good.

Can I buy a complete source code?

I really like this project!

**Comment by woiwoz** [comment]
At present, the project is still in the process of development. For security, we do not intend to expose script code until Valoren server is officially launched.

**Comment by woiwoz** [comment]
You said you were German, I think you should be Chinese. @danqu

**Comment by danqu** [comment]
Chinese？NO

**Comment by woiwoz** [comment]
Your name betrayed you. This is Chinese Pinyin.
