### ISSUE TITLE
Taking out guild bank item makes it soulbound

### ISSUE THREAD

**Issue by oppahansi** [ValorenWoW/sunstrider-core#89]
**Description:**

After depositing an item that is not yet souldbound to you and taking it back out of the guild bank the item becomes soulbound.

**Current behaviour:**

If you have an item that is not yet souldbound https://vgy.me/4icvTr.png
and you deposit this item in the guild bank and then take this item back into your bag,
it becomes soulbound https://vgy.me/ivvoKN.png

**Expected behaviour:**

Depositing an item that is not yet soulbound and taking that item back out should not make the item soulbound.

**Steps to reproduce the problem:**

1. Join a guild / Create a guild
2. Deposit an item that is not yet soulbound to you into the guild bank
3. Take the item back out of the guild bank into your bag
4. Check its state.

**rev. hash/commit:** 
Current sunstrider test server build.
Latest commit bc08cbb

**Operating system and compiler:**
Current sunstrider test server, 
Latest commit bc08cbb

**Comment by kelno** [comment]
It notices the item here is "Binds when picked up", how do you added it to your inventory?
It should have been soulbound even before putting in the guild bank.

**Comment by oppahansi** [comment]
I added item using the additem command. 
In the end this is a fail on my side, just tested it with more items, it is working correct.

**Comment by kelno** [comment]
Ok!
